Repository SerenityOS/serenity, pull requests merged in 2022-11, with the labels that each got.

#15866 Base: Add Black&White Square Button emoji
  Base/res/emoji/U+1F532.png
  Base/res/emoji/U+1F533.png
Labels: 👀 pr-needs-review

#15876 AK: Allow destruction of JsonObjectSerializer objects after errors
  AK/JsonArraySerializer.h
  AK/JsonObjectSerializer.h
Labels: 👀 pr-needs-review

#15160 HexEditor: Implement undo and redo actions
  Userland/Applications/HexEditor/HexDocument.cpp
  Userland/Applications/HexEditor/HexDocument.h
  Userland/Applications/HexEditor/HexEditor.cpp
  Userland/Applications/HexEditor/HexEditor.h
  Userland/Applications/HexEditor/HexEditorWidget.cpp
  Userland/Applications/HexEditor/HexEditorWidget.h
Labels: ⏳ pr-waiting-for-author

#15874 Kernel: Handle some allocation failures in IPv4Socket and TCPSocket
  AK/SinglyLinkedList.h
  AK/SinglyLinkedListWithCount.h
  Kernel/Net/IPv4Socket.cpp
  Kernel/Net/TCPSocket.cpp
Labels: 👀 pr-needs-review

#15878 Browser: Update Storage Inspector's cookie model when deleting cookies
  Userland/Applications/Browser/CookiesModel.cpp
  Userland/Applications/Browser/CookiesModel.h
  Userland/Applications/Browser/StorageWidget.cpp
Labels: 👀 pr-needs-review

#15882 LibWeb: Register PendingResponse with a Request to keep it alive
  Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
  Userland/Libraries/LibWeb/Fetch/Fetching/PendingResponse.cpp
  Userland/Libraries/LibWeb/Fetch/Fetching/PendingResponse.h
  Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Requests.cpp
  Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Requests.h
Labels: 👀 pr-needs-review

#15536 PixelPaint: Allow resizing images and layers.
  Userland/Applications/PixelPaint/Layer.cpp
  Userland/Applications/PixelPaint/ResizeImageDialog.cpp
  Userland/Applications/PixelPaint/ResizeImageDialog.gml
  Userland/Applications/PixelPaint/ResizeImageDialog.h
  Userland/Libraries/LibGfx/Painter.cpp
  Userland/Libraries/LibGfx/Painter.h
Labels: 👀 pr-needs-review

#15766 TextEditor: Save the selected font
  Userland/Applications/TextEditor/MainWidget.cpp
Labels: 👀 pr-needs-review

#15891 Browser: Add a context menu item to take a screenshot of the current tab
  Userland/Applications/Browser/BrowserWindow.cpp
  Userland/Applications/Browser/BrowserWindow.h
  Userland/Applications/Browser/Tab.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15571 Games: Add Flood
  Base/res/apps/Flood.af
  Base/res/icons/16x16/app-flood.png
  Base/res/icons/32x32/app-flood.png
  Base/usr/share/man/man6/Flood.md
  Userland/Games/CMakeLists.txt
  Userland/Games/Flood/Board.cpp
  Userland/Games/Flood/Board.h
  Userland/Games/Flood/BoardWidget.cpp
  Userland/Games/Flood/BoardWidget.h
  Userland/Games/Flood/CMakeLists.txt
  Userland/Games/Flood/FloodWindow.gml
  Userland/Games/Flood/SettingsDialog.cpp
  Userland/Games/Flood/SettingsDialog.gml
  Userland/Games/Flood/SettingsDialog.h
  Userland/Games/Flood/main.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15904 CI: Also update the main workflow to use actions/checkout version 3
  .github/workflows/cmake.yml
Labels: 👀 pr-needs-review

#15848 LibUnicode: Make the generated .h and .cpp paths for emoji data optional
  Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateEmojiData.cpp
Labels: 👀 pr-needs-review

#15906 Base: Update ports serenity-theming use latest commit 490a15a
  Ports/AvailablePorts.md
  Ports/serenity-theming/package.sh
Labels: ⏳ pr-waiting-for-author

#15913 LibJS: Fix length of PlainDateTime.withPlainTime
  Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp
  Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDateTime/PlainDateTime.prototype.withPlainTime.js
Labels: 👀 pr-needs-review

#15917 FileManager: Improve error handling when posix_spawn() fails
  Userland/Applications/FileManager/DirectoryView.cpp
Labels: 👀 pr-needs-review

#15916 LibTimeZone: Update to TZDB version 2022f
  Meta/CMake/time_zone_data.cmake
Labels: 👀 pr-needs-review

#15918 Meta: Make file-system resizing work on macOS
  Meta/build-image-qemu.sh
Labels: 👀 pr-needs-review

#15925 LibJS: Rename ToShowCalendarOption to ToCalendarNameOption
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
  Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDayPrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonthPrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
Labels: ✅ pr-community-approved

#15923 LibWeb: Bring XHR::open() closer to spec
  Userland/Libraries/LibWeb/XHR/XMLHttpRequest.cpp
Labels: ⏳ pr-waiting-for-author

#15903 CI: Check out PR merge branch instead of source
  .github/workflows/cmake.yml
Labels: ✅ pr-community-approved

#15936 LibGUI: Hold down Alt when clicking TreeView to expand full subtree
  Userland/Libraries/LibGUI/TreeView.cpp
  Userland/Libraries/LibGUI/TreeView.h
Labels: 👀 pr-needs-review

#15896 LibWeb: Use relative units for gradients until painting
  Userland/Libraries/LibWeb/Painting/GradientPainting.cpp
Labels: 👀 pr-needs-review

#15938 LibJS: Rename ToShowTimeZoneNameOption to ToTimeZoneNameOption
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
  Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
Labels: ✅ pr-community-approved

#15932 Toolchain: Disable makeinfo for binutils.
  Toolchain/BuildIt.sh
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15920 AK: Check for width of floating point types properly
  AK/FloatingPoint.h
  AK/Types.h
Labels: ✅ pr-community-approved

#15947 LibWeb: Replace some unnecessary ShadowRoot verify_cast with static_cast
  Userland/Libraries/LibWeb/DOM/Node.cpp
Labels: ⏳ pr-waiting-for-author

#15957 VideoPlayer: Show current open file in the title
  Userland/Applications/VideoPlayer/VideoPlayerWidget.cpp
  Userland/Applications/VideoPlayer/VideoPlayerWidget.h
  Userland/Applications/VideoPlayer/main.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15765 Everywhere: Remove redundant inequality comparison operators
  AK/ByteBuffer.h
  AK/Complex.h
  AK/DistinctNumeric.h
  AK/FlyString.h
  AK/IntrusiveList.h
  AK/JsonPath.h
  AK/NonnullRefPtr.h
  AK/RefPtr.h
  AK/String.h
  AK/StringUtils.h
  AK/StringView.h
  AK/Time.h
  AK/UUID.cpp
  AK/UUID.h
  AK/Utf16View.h
  AK/Utf32View.h
  Userland/Applications/Spreadsheet/Position.h
  Userland/Libraries/LibDebug/DebugInfo.h
  Userland/Libraries/LibDeviceTree/FlattenedDeviceTree.h
  Userland/Libraries/LibGUI/ModelIndex.h
  Userland/Libraries/LibGfx/Color.h
  Userland/Libraries/LibGfx/Point.h
  Userland/Libraries/LibGfx/Rect.h
  Userland/Libraries/LibGfx/Size.h
  Userland/Libraries/LibJS/Runtime/PropertyAttributes.h
  Userland/Libraries/LibLine/KeyCallbackMachine.h
  Userland/Libraries/LibRegex/RegexMatch.h
  Userland/Libraries/LibSQL/HashIndex.h
  Userland/Libraries/LibVT/Attribute.h
  Userland/Libraries/LibWeb/CSS/Angle.h
  Userland/Libraries/LibWeb/CSS/Display.h
  Userland/Libraries/LibWeb/CSS/Frequency.h
  Userland/Libraries/LibWeb/CSS/Length.h
  Userland/Libraries/LibWeb/CSS/Percentage.h
  Userland/Libraries/LibWeb/CSS/Resolution.h
  Userland/Libraries/LibWeb/CSS/StyleProperties.h
  Userland/Libraries/LibWeb/CSS/StyleValue.h
  Userland/Libraries/LibWeb/CSS/Time.h
  Userland/Libraries/LibWeb/DOM/Position.h
  Userland/Libraries/LibWeb/HTML/Origin.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15967 Ports: Update fio to version 3.33
  Ports/AvailablePorts.md
  Ports/fio/package.sh
Labels: 👀 pr-needs-review

#15962 Base+VideoPlayer: Add an icon for video player
  Base/res/icons/16x16/app-video-player.png
  Base/res/icons/32x32/app-video-player.png
  Userland/Applications/VideoPlayer/CMakeLists.txt
  Userland/Applications/VideoPlayer/VideoPlayerWidget.cpp
  Userland/Applications/VideoPlayer/main.cpp
Labels: 👀 pr-needs-review

#15770 LibWeb: Skip anonymous layout nodes while finding the event target
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
Labels: 👀 pr-needs-review

#15961 Base: Add media emojis
  Base/res/emoji/U+1F500.png
  Base/res/emoji/U+1F501.png
  Base/res/emoji/U+1F502.png
  Base/res/emoji/U+1F503.png
  Base/res/emoji/U+1F504.png
  Base/res/emoji/U+1F519.png
  Base/res/emoji/U+1F520.png
  Base/res/emoji/U+1F521.png
  Base/res/emoji/U+1F522.png
  Base/res/emoji/U+1F523.png
  Base/res/emoji/U+1F524.png
Labels: ⏳ pr-waiting-for-author

#15963 AudioServer: Skip mixing when volume is zero
  Userland/Services/AudioServer/Mixer.cpp
Labels: 👀 pr-needs-review

#15941 PixelPaint: Remember visibility for histogram and vectorscope
  Userland/Applications/PixelPaint/MainWidget.cpp
Labels: 👀 pr-needs-review

#15747 Base: Added manpages for which(1) and stat(1)
  Base/usr/share/man/man1/stat.md
  Base/usr/share/man/man1/which.md
Labels: ⏳ pr-waiting-for-author

#15969 LibWeb: Pick the correct DOM node for mouse-move events
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
Labels: 👀 pr-needs-review

#15970 WindowServer: Cycle through menu items with the same Alt shortcut
  Userland/Services/WindowServer/Menu.h
  Userland/Services/WindowServer/MenuManager.cpp
Labels: 👀 pr-needs-review

#15974 LibC: Implement getpwent_r
  Userland/Libraries/LibC/pwd.cpp
  Userland/Libraries/LibC/pwd.h
Labels: 👀 pr-needs-review

#15980 LibWeb: Apply the current transform in CRC2D.stroke()
  Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
Labels: 👀 pr-needs-review

#15983 LibJS: Add thorough tests for try/finally using continue and break
  Userland/Libraries/LibJS/Tests/try-finally-break.js
  Userland/Libraries/LibJS/Tests/try-finally-continue.js
Labels: 👀 pr-needs-review

#15985 Meta: Compile new WebContent IPC endpoints for WebDriver in Lagom
  Meta/Lagom/CMakeLists.txt
Labels: 👀 pr-needs-review

#15886 PixelPaint: Make filters apply to a selection if one is present
  Userland/Applications/PixelPaint/FilterGallery.cpp
  Userland/Applications/PixelPaint/FilterPreviewWidget.cpp
  Userland/Applications/PixelPaint/FilterPreviewWidget.h
  Userland/Applications/PixelPaint/ImageProcessor.cpp
Labels: 👀 pr-needs-review

#15832 LibGUI: Shift+Tab unindents line
  Userland/Libraries/LibGUI/TextEditor.cpp
  Userland/Libraries/LibGUI/TextEditor.h
Labels: 👀 pr-needs-review

#16002 AK: Allow Variant::downcast<OtherVariantType>()
  AK/Variant.h
  Tests/AK/TestVariant.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16009 LibIDL: Also handle anonymous union types in resolve_typedef()
  Userland/Libraries/LibIDL/IDLParser.cpp
Labels: 👀 pr-needs-review

#16024 Kernel: Add missing includes for Mount.h file
  Kernel/FileSystem/Mount.h
Labels: 👀 pr-needs-review

#15975 LibVideo: Treat BT.601/709/2020 input transfer characteristics as sRGB
  Userland/Libraries/LibVideo/Color/ColorConverter.cpp
  Userland/Libraries/LibVideo/PlaybackManager.cpp
Labels: 👀 pr-needs-review

#15942 LibJS: Add explicit assertion for days
  Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
Labels: ⏳ pr-waiting-for-author

#16014 LibLine: fix save line condition
  Userland/Libraries/LibLine/Editor.cpp
Labels: ✅ pr-community-approved

#16032 Toolchain: Fix missing makeinfo on macOS Ventura
  Toolchain/BuildIt.sh
Labels: ✅ pr-community-approved

#15995 WebDriver: Implement `POST /session/{id}/window/fullscreen` endpoint
  Userland/Applications/Browser/Tab.cpp
  Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
  Userland/Libraries/LibWebView/OutOfProcessWebView.h
  Userland/Libraries/LibWebView/ViewImplementation.h
  Userland/Libraries/LibWebView/WebContentClient.cpp
  Userland/Libraries/LibWebView/WebContentClient.h
  Userland/Services/WebContent/WebContentClient.ipc
  Userland/Services/WebContent/WebDriverClient.ipc
  Userland/Services/WebContent/WebDriverConnection.cpp
  Userland/Services/WebContent/WebDriverConnection.h
  Userland/Services/WebDriver/Client.cpp
  Userland/Services/WebDriver/Client.h
Labels: 👀 pr-needs-review

#16003 AudioServer: Stop glitching when toggling mute
  Userland/Services/AudioServer/Mixer.cpp
  Userland/Services/AudioServer/Mixer.h
Labels: ✅ pr-community-approved

#16053 Piano: Alphabetize sources
  Userland/Applications/Piano/CMakeLists.txt
Labels: 👀 pr-needs-review

#16052 Piano: Guard against all allocations at top level of the audio pipeline
  Userland/Applications/Piano/TrackManager.cpp
Labels: 👀 pr-needs-review

#16051 LibAudio: Revert to using buffered file reading
  Userland/Libraries/LibAudio/Loader.cpp
Labels: 👀 pr-needs-review

#16041 Toolchain: Add libxcrypt to serenity.nix
  Toolchain/serenity.nix
Labels: 👀 pr-needs-review

#16050 LibThreading: Add thread priority controls to Thread
  Userland/Libraries/LibThreading/Thread.cpp
  Userland/Libraries/LibThreading/Thread.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15899 WindowServer: Add "[user]" to titlebar when uid differs from login user
  Userland/Services/WindowServer/Window.cpp
  Userland/Services/WindowServer/Window.h
  Userland/Services/WindowServer/main.cpp
Labels: 👀 pr-needs-review

#15910 PixelPaint: Fix Tool ImageEditor sync
  Userland/Applications/PixelPaint/ImageEditor.cpp
Labels: 👀 pr-needs-review

#15930 Userland: Accept drag_enter events for widgets supporting file drops
  Userland/Applications/3DFileViewer/main.cpp
  Userland/Applications/FontEditor/MainWidget.cpp
  Userland/Applications/FontEditor/MainWidget.h
  Userland/Applications/HexEditor/HexEditorWidget.cpp
  Userland/Applications/HexEditor/HexEditorWidget.h
  Userland/Applications/ImageViewer/ViewWidget.cpp
  Userland/Applications/ImageViewer/ViewWidget.h
  Userland/Applications/PixelPaint/MainWidget.cpp
  Userland/Applications/PixelPaint/MainWidget.h
  Userland/Applications/SoundPlayer/SoundPlayerWidgetAdvancedView.cpp
  Userland/Applications/SoundPlayer/SoundPlayerWidgetAdvancedView.h
  Userland/Applications/TextEditor/MainWidget.cpp
  Userland/Applications/TextEditor/MainWidget.h
  Userland/Applications/ThemeEditor/PreviewWidget.cpp
  Userland/Applications/ThemeEditor/PreviewWidget.h
  Userland/DevTools/HackStudio/Editor.cpp
  Userland/DevTools/HackStudio/Editor.h
  Userland/DevTools/SQLStudio/MainWidget.cpp
  Userland/DevTools/SQLStudio/MainWidget.h
  Userland/Services/Taskbar/QuickLaunchWidget.cpp
  Userland/Services/Taskbar/QuickLaunchWidget.h
Labels: 👀 pr-needs-review

#16016 Kernel: Disallow jail creation from a process within a jail
  Kernel/Syscalls/jail.cpp
Labels: 👀 pr-needs-review

#16059 LibWeb: Define the route for the Fullscreen Window command
  Userland/Libraries/LibWeb/WebDriver/Client.cpp
Labels: 👀 pr-needs-review

#15834 LibC: Implement getpass()
  Userland/Libraries/LibC/limits.h
  Userland/Libraries/LibC/unistd.cpp
Labels: 👀 pr-needs-review

#15965 LibCore: Add query for all accounts and groups
  Userland/Libraries/LibCore/Account.cpp
  Userland/Libraries/LibCore/Account.h
  Userland/Libraries/LibCore/Group.cpp
  Userland/Libraries/LibCore/Group.h
Labels: 👀 pr-needs-review

#16036 Keymaps: Add Arabic keymap
  Base/res/keymaps/ar.json
Labels: 👀 pr-needs-review

#15885 WindowServer: Update alt shortcuts for menu items when text changes
  Userland/Services/WindowServer/Menu.cpp
  Userland/Services/WindowServer/Menu.h
  Userland/Services/WindowServer/Window.cpp
Labels: 👀 pr-needs-review

#16046 LibGfx: Two small changes for ttf font compatibility
  Userland/Libraries/LibGfx/Font/TrueType/Font.cpp
  Userland/Libraries/LibGfx/Font/TrueType/Tables.h
Labels: 👀 pr-needs-review

#16048 LibWeb: XHR cleanups
  Userland/Libraries/LibWeb/XHR/XMLHttpRequest.cpp
  Userland/Libraries/LibWeb/XHR/XMLHttpRequest.h
  Userland/Libraries/LibWeb/XHR/XMLHttpRequest.idl
Labels: 👀 pr-needs-review

#16030 VideoPlayer: Remove PlaybackManager from children when opening a video
  Userland/Applications/VideoPlayer/VideoPlayerWidget.cpp
  Userland/Applications/VideoPlayer/VideoPlayerWidget.h
  Userland/Libraries/LibVideo/PlaybackManager.cpp
  Userland/Libraries/LibVideo/PlaybackManager.h
Labels: 👀 pr-needs-review, ✅ pr-maintainer-approved-but-awaiting-ci

#15792 seq: Support the --separator and --terminator options
  Userland/Utilities/seq.cpp
Labels: ⏳ pr-waiting-for-author

#15763 LibWeb: Respect media attribute of style tag
  Userland/Libraries/LibWeb/CSS/CSSStyleSheet.cpp
  Userland/Libraries/LibWeb/CSS/CSSStyleSheet.h
  Userland/Libraries/LibWeb/CSS/MediaList.cpp
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/CSS/StyleSheet.cpp
  Userland/Libraries/LibWeb/CSS/StyleSheet.h
  Userland/Libraries/LibWeb/CSS/StyleSheet.idl
Labels: 👀 pr-needs-review

#15692 hexdump: Support truncating output with -n
  Userland/Utilities/hexdump.cpp
Labels: ⏳ pr-waiting-for-author

#16074 LibWeb+WebContent+WebDriver: Implement shadow root commands
  Userland/Libraries/LibWeb/WebDriver/Client.cpp
  Userland/Libraries/LibWeb/WebDriver/Client.h
  Userland/Services/WebContent/WebDriverClient.ipc
  Userland/Services/WebContent/WebDriverConnection.cpp
  Userland/Services/WebContent/WebDriverConnection.h
  Userland/Services/WebDriver/Client.cpp
  Userland/Services/WebDriver/Client.h
Labels: 👀 pr-needs-review

#16065 Meta: Don't try to enable GDB support on Windows
  Meta/run.sh
Labels: 👀 pr-needs-review

#16080 LibJS: Remove workaround for Clang misalignment in MathematicalValue
  Userland/Libraries/LibJS/Runtime/Intl/MathematicalValue.h
Labels: 👀 pr-needs-review

#16103 LibWeb: Fix clicking on links
  Userland/Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp
Labels: 👀 pr-needs-review

#16112 Kernel: Fix includes when building aarch64
  Kernel/Arch/aarch64/init.cpp
  Kernel/Bus/PCI/Access.h
  Kernel/Jail.h
Labels: 👀 pr-needs-review

#16102 LibC+Tests: Simplify getpwuid_r() and getpwnam_r() and add tests
  Tests/LibC/CMakeLists.txt
  Tests/LibC/TestPwd.cpp
  Userland/Libraries/LibC/pwd.cpp
Labels: 👀 pr-needs-review

#16117 LibJS: Some spec comments & compliance in TypedArray
  Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16119 LibJS: Fix UTF-16 corruption in String.prototype.replace()
  Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
  Userland/Libraries/LibJS/Tests/builtins/String/String.prototype.replace.js
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16087 LibVT/LibLine: Delete words when pressing Ctrl+Backspace in Terminal
  Userland/Libraries/LibLine/Editor.cpp
  Userland/Libraries/LibVT/Terminal.cpp
Labels: 👀 pr-needs-review

#16115 LibWeb: Don't add margin twice to y absolute box offset
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Labels: ⏳ pr-waiting-for-author

#16132 LibWeb: Remove unused should_invalidate_styles_on_attribute_changes() hack
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Labels: 👀 pr-needs-review

#16144 3DFileViewer: Propagate key events to the window
  Userland/Applications/3DFileViewer/main.cpp
Labels: ✅ pr-community-approved

#16140 LibWeb: Support box-sizing in BFC
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/FormattingContext.h
Labels: 👀 pr-needs-review

#16168 Ports: Fix warning when building with `useconfigure="false"`
  Ports/.port_include.sh
Labels: 👀 pr-needs-review

#16166 LibIPC: Handle `ECONNRESET` when reading from the IPC socket
  Userland/Libraries/LibIPC/Connection.cpp
Labels: 👀 pr-needs-review

#15948 Meta: Look for e2fsck path on build-image-qemu.sh
  Meta/build-image-qemu.sh
Labels: 👀 pr-needs-review, ✅ pr-community-approved

#16079 LibVideo: Make all block intermediates stack-allocated arrays
  Userland/Libraries/LibVideo/VP9/Decoder.cpp
  Userland/Libraries/LibVideo/VP9/Decoder.h
Labels: 👀 pr-needs-review

#16169 cat: Use `Core::Stream::File`
  Userland/Utilities/cat.cpp
Labels: 👀 pr-needs-review

#16040 Kernel: Update the ".." inode for directories after a rename
  Kernel/FileSystem/DevPtsFS/Inode.cpp
  Kernel/FileSystem/DevPtsFS/Inode.h
  Kernel/FileSystem/Ext2FS/Inode.cpp
  Kernel/FileSystem/Ext2FS/Inode.h
  Kernel/FileSystem/FATFS/Inode.cpp
  Kernel/FileSystem/FATFS/Inode.h
  Kernel/FileSystem/ISO9660FS/Inode.cpp
  Kernel/FileSystem/ISO9660FS/Inode.h
  Kernel/FileSystem/Inode.h
  Kernel/FileSystem/Plan9FS/Inode.cpp
  Kernel/FileSystem/Plan9FS/Inode.h
  Kernel/FileSystem/ProcFS/Inode.cpp
  Kernel/FileSystem/ProcFS/Inode.h
  Kernel/FileSystem/SysFS/Inode.cpp
  Kernel/FileSystem/SysFS/Inode.h
  Kernel/FileSystem/TmpFS/Inode.cpp
  Kernel/FileSystem/TmpFS/Inode.h
  Kernel/FileSystem/VirtualFileSystem.cpp
Labels: ✅ pr-community-approved

#16180 Documentation: Add guidelines document for kernel development
  Documentation/Kernel/DevelopmentGuidelines.md
Labels: 👀 pr-needs-review

#16025 Documentation: Add a document about TmpFS
  Documentation/Kernel/TmpFS.md
Labels: 👀 pr-needs-review

#16173 shuf: Support reading input from a file
  Userland/Utilities/shuf.cpp
Labels: ✅ pr-community-approved

#16058 PixelPaint: Add the Pen tool as the default tool
  Userland/Applications/PixelPaint/ToolboxWidget.cpp
Labels: 👀 pr-needs-review

#16034 LibWeb: Add initial implementation of structured clone
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
  Userland/Libraries/LibWeb/HTML/StructuredSerialize.h
  Userland/Libraries/LibWeb/HTML/Window.cpp
  Userland/Libraries/LibWeb/HTML/Window.h
Labels: 👀 pr-needs-review

#16056 LibGfx: Better ellipses
  Userland/Applications/PixelPaint/Tools/EllipseTool.cpp
  Userland/Libraries/LibGfx/Painter.cpp
Labels: 👀 pr-needs-review

#16181 FuzzTar+tar: Advance the stream before continuing
  Meta/Lagom/Fuzzers/FuzzTar.cpp
  Userland/Utilities/tar.cpp
Labels: 👀 pr-needs-review

#16191 LibVT: Prevent `u16` underflow when resizing terminal to a height of 1
  Userland/Libraries/LibVT/Terminal.cpp
Labels: 👀 pr-needs-review

#16203 LibPDF: Fix path coordinates calculation
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: 👀 pr-needs-review

#16171 LibGfx: Prevent calling `to_type<T>()` on `Line/Point/Rect/Size<T>`
  Userland/Libraries/LibGfx/Line.h
  Userland/Libraries/LibGfx/Point.h
  Userland/Libraries/LibGfx/Rect.h
  Userland/Libraries/LibGfx/Size.h
Labels: 👀 pr-needs-review

#16190 Ports/bc: Update to version 6.1.1
  Ports/AvailablePorts.md
  Ports/bc/package.sh
Labels: ⏳ pr-waiting-for-author

#16023 Userland: Enhance jail-attach utility to support existing and new jails
  Base/usr/share/man/man1/jail-attach.md
  Userland/Utilities/jail-attach.cpp
Labels: 👀 pr-needs-review

#16193 Meta: Update actions/libjs-test262 action to newer version
  .github/workflows/libjs-test262.yml
Labels: 👀 pr-needs-review

#16165 hexdump: Replace Core::File with Core::Stream::File
  Userland/Utilities/hexdump.cpp
Labels: ⏳ pr-waiting-for-author

#15373 Userland: Add BuggieBox program
  Userland/BuggieBox/CMakeLists.txt
  Userland/BuggieBox/main.cpp
  Userland/CMakeLists.txt
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16163 LibJS: Switch to bytecode interpreter to run generator functions for AST
  Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
  Userland/Libraries/LibJS/Runtime/GeneratorObject.cpp
Labels: 👀 pr-needs-review

#16216 WebDriver: Add stub for `/session/{id}/print` endpoint
  Userland/Libraries/LibWeb/WebDriver/Client.cpp
  Userland/Libraries/LibWeb/WebDriver/Client.h
  Userland/Services/WebContent/WebDriverClient.ipc
  Userland/Services/WebContent/WebDriverConnection.cpp
  Userland/Services/WebContent/WebDriverConnection.h
  Userland/Services/WebDriver/Client.cpp
  Userland/Services/WebDriver/Client.h
Labels: 👀 pr-needs-review, ⏳ pr-waiting-for-author

#16218 LibJS: Remove some parser state from the AST
  Userland/Libraries/LibJS/AST.h
  Userland/Libraries/LibJS/Parser.cpp
  Userland/Libraries/LibJS/Parser.h
Labels: ⏳ pr-waiting-for-author

#16227 Base: Set transparent rubber band for all themes
  Base/res/themes/Olive.ini
  Base/res/themes/Pumpkin.ini
  Base/res/themes/Scarlett.ini
Labels: 👀 pr-needs-review

#16212 LibGfx: Allow float thickness lines and fix fill path glitches
  Userland/Libraries/LibGfx/AntiAliasingPainter.cpp
Labels: 👀 pr-needs-review

#16221 Ports/SDL2: Listen for window change events instead of input preemption
  Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch
Labels: ⏳ pr-waiting-for-author

#16223 LibCore: Add %l conversion specification to DateTime
  Userland/Libraries/LibCore/DateTime.cpp
Labels: 👀 pr-needs-review

#16116 LibC: Treat argument "-" the same as arguments that don't start with "-"
  Userland/Libraries/LibC/getopt.cpp
Labels: 👀 pr-needs-review

#16250 LibWeb: Remove outdated FIXME regarding application cache selection
  Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Labels: 👀 pr-needs-review

#16237 LibGfx+LibGUI: Use constant for line spacing instead of magic number
  Userland/Libraries/LibGUI/Label.cpp
  Userland/Libraries/LibGfx/Painter.cpp
  Userland/Libraries/LibGfx/Painter.h
Labels: 👀 pr-needs-review

#16257 LibCore: Add support for ReadonlyBytes to MemoryStream
  Meta/Lagom/Fuzzers/FuzzBrotli.cpp
  Meta/Lagom/Fuzzers/FuzzTar.cpp
  Userland/Libraries/LibCore/MemoryStream.h
  Userland/Libraries/LibHTTP/Job.cpp
Labels: 👀 pr-needs-review

#16253 Base: Add emoji flags for provinces in Liberia
  Base/home/anon/Documents/emoji-serenity.txt
  Base/res/emoji/U+1F3F4_U+E006C_U+E0072_U+E0062_U+E0067_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006C_U+E0072_U+E0062_U+E006D_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006C_U+E0072_U+E0063_U+E006D_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006C_U+E0072_U+E0067_U+E0062_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006C_U+E0072_U+E0067_U+E0067_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006C_U+E0072_U+E0067_U+E006B_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006C_U+E0072_U+E0067_U+E0070_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006C_U+E0072_U+E006C_U+E006F_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006C_U+E0072_U+E006D_U+E0067_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006C_U+E0072_U+E006D_U+E006F_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006C_U+E0072_U+E006D_U+E0079_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006C_U+E0072_U+E006E_U+E0069_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006C_U+E0072_U+E0072_U+E0067_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006C_U+E0072_U+E0072_U+E0069_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006C_U+E0072_U+E0073_U+E0069_U+E007F.png
Labels: 👀 pr-needs-review

#16262 HackStudio: Replace blank file when opening a new one
  Userland/DevTools/HackStudio/HackStudioWidget.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16268 LibWeb: Add @@toStringTag to platform object prototypes
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Labels: 👀 pr-needs-review

#16267 LibWeb: Handle <absolute-size> and <relative-size> values in `font-size`
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci
