Repository SerenityOS/serenity, pull requests merged in 2022-10, with the labels that each got.

#15499 Browser: Add a custom icon for the "New Window" action
  Base/res/icons/16x16/new-window.png
  Userland/Applications/Browser/IconBag.cpp
  Userland/Applications/Browser/IconBag.h
  Userland/Applications/Browser/WindowActions.cpp
Labels: enhancement

#15583 LibAudio: Fix two PCM rescaling errors
  Userland/Libraries/LibAudio/WavLoader.cpp
Labels: ✅ pr-approved-but-awaiting-ci

#15562 HexEditor: Render selection background without gaps between rows
  Userland/Applications/HexEditor/HexEditor.cpp
Labels: ✅ pr-approved-but-awaiting-ci

#15598 LibJS/Temporal: Move time zone annotation parsing into ParseISODateTime
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
  Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.cpp
Labels: ✅ pr-approved-but-awaiting-ci

#15600 NetworkSettings+SpiceAgent: Update and add required unveil paths
  Userland/Applications/NetworkSettings/main.cpp
  Userland/Services/SpiceAgent/ConnectionToClipboardServer.h
  Userland/Services/SpiceAgent/main.cpp
Labels: 👀 pr-needs-review

#15603 Kernel: Fix build error on AARCH64
  Kernel/Arch/aarch64/CurrentTime.cpp
Labels: build issue

#15602 Ports: Add dosfstools port
  Ports/AvailablePorts.md
  Ports/dosfstools/package.sh
  Userland/Libraries/LibC/paths.h
Labels: 👀 pr-needs-review

#15611 Spider: Make the last move undoable
  Userland/Games/Spider/Game.cpp
  Userland/Games/Spider/Game.h
  Userland/Games/Spider/main.cpp
Labels: ✅ pr-approved-but-awaiting-ci

#15623 WebDriver: Implement POST /session/{id}/back and POST /session/{id}/forward endpoints
  Userland/Applications/Browser/WebDriverConnection.cpp
  Userland/Applications/Browser/WebDriverConnection.h
  Userland/Applications/Browser/WebDriverSessionClient.ipc
  Userland/Services/WebDriver/Client.cpp
  Userland/Services/WebDriver/Client.h
  Userland/Services/WebDriver/Session.cpp
  Userland/Services/WebDriver/Session.h
Labels: ✅ pr-approved-but-awaiting-ci

#15617 Ports: Add file utility port
  Ports/AvailablePorts.md
  Ports/file/package.sh
Labels: ✅ pr-approved-but-awaiting-ci

#15621 Ports: Add GNU which port
  Ports/AvailablePorts.md
  Ports/which/package.sh
Labels: ✅ pr-approved-but-awaiting-ci

#15616 Documentation: Add FAQ regarding MP3 patents
  Documentation/FAQ.md
Labels: 👀 pr-needs-review

#15627 LibJS: Subtract time zone offsets when converting from local time to UTC
  Userland/Libraries/LibJS/Runtime/Date.cpp
Labels: 👀 pr-needs-review

#15625 GMLPlayground: Allow previewing GML in a separate window
  Userland/DevTools/GMLPlayground/main.cpp
Labels: 👀 pr-needs-review

#15632 Ports: Add GNU tar port
  Ports/AvailablePorts.md
  Ports/tar/package.sh
Labels: 👀 pr-needs-review

#15634 LibJS: Pass dateAdd through MoveRelativeDate
  Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/Duration.h
Labels: 👀 pr-needs-review

#15636 LibJS: Rename Get{IANA => Named}TimeZone{Next,Previous}Transition
  Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.h
  Userland/Libraries/LibJS/Runtime/Temporal/TimeZonePrototype.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15080 LibJS: Fix TemporalCalendarString ambiguity
  Userland/Libraries/LibJS/Runtime/ErrorTypes.h
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
  Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/ISO8601.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/ISO8601.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15624 WebDriver: GET named cookie
  Userland/Applications/Browser/WebDriverConnection.cpp
  Userland/Applications/Browser/WebDriverConnection.h
  Userland/Applications/Browser/WebDriverSessionClient.ipc
  Userland/Services/WebDriver/Client.cpp
  Userland/Services/WebDriver/Client.h
  Userland/Services/WebDriver/Session.cpp
  Userland/Services/WebDriver/Session.h
Labels: 👀 pr-needs-review

#15619 Kernel/SysFS: Expose file size of ACPI tables in /sys/firmware/acpi
  Kernel/Firmware/ACPI/Parser.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15606 Meta: Add a few more e-mail addresses to the .mailmap file
  .mailmap
Labels: 👀 pr-needs-review

#15635 Fuzzers: Add fuzzer for the Tar parser
  Meta/Lagom/Fuzzers/CMakeLists.txt
  Meta/Lagom/Fuzzers/FuzzTar.cpp
Labels: 👀 pr-needs-review

#15594 SystemServer: Make system-mode=text the default in case of read failure
  Userland/Services/SystemServer/main.cpp
Labels: 👀 pr-needs-review

#15172 Kernel: Use more fine-grained content data block granularity in TmpFS
  Kernel/FileSystem/TmpFS.cpp
  Kernel/FileSystem/TmpFS.h
  Tests/LibC/TestIo.cpp
Labels: 👀 pr-needs-review

#15104 Meta: Print error if cmake does not exist
  Meta/CMake/processor-count.cmake
  Meta/serenity.sh
Labels: 👀 pr-needs-review

#15642 Meta: Remove unused "prefix" variable from invoke_generator() helper
  Meta/CMake/libweb_generators.cmake
  Meta/CMake/locale_data.cmake
  Meta/CMake/pnp_ids.cmake
  Meta/CMake/time_zone_data.cmake
  Meta/CMake/unicode_data.cmake
  Meta/CMake/utils.cmake
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15650 AK: Document the non-standard extensions in TRY
  AK/Try.h
Labels: ⏳ pr-waiting-for-author

#15651 LibThreading: Only set pthread name on Serenity
  Userland/Libraries/LibThreading/Thread.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15643 SpiceAgent: Add unveil call on the /proc/all node path
  Userland/Services/SpiceAgent/main.cpp
Labels: 👀 pr-needs-review

#15647 Ports: Add tree utility port
  Ports/AvailablePorts.md
  Ports/tree/package.sh
  Ports/tree/patches/0001-Allow-to-override-the-default-C-compiler.patch
  Ports/tree/patches/ReadMe.md
Labels: 👀 pr-needs-review

#15640 Base: Add more emoji
  Base/res/emoji/U+1F42D.png
  Base/res/emoji/U+1F994.png
  Base/res/emoji/U+1F9A4.png
  Base/res/emoji/U+1F9A9.png
  Base/res/emoji/U+1F9AD.png
Labels: ✅ pr-community-approved

#14761 WindowServer: Fix inconsistencies when redrawing wallpaper in stretch mode
  Userland/Applications/FileManager/main.cpp
  Userland/Services/WindowServer/Compositor.cpp
  Userland/Services/WindowServer/Compositor.h
Labels: 👀 pr-needs-review

#15648 Ports/dmidecode: Remove install and post_install overriden sequences
  Ports/dmidecode/package.sh
Labels: 👀 pr-needs-review

#15401 LibJS: Forward a string aproximation of the CallExpression to Call Ops
  Userland/Libraries/LibJS/AST.cpp
  Userland/Libraries/LibJS/AST.h
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
  Userland/Libraries/LibJS/Bytecode/Op.cpp
  Userland/Libraries/LibJS/Bytecode/Op.h
Labels: 👀 pr-needs-review

#15579 PixelPaint: Make Alt-Clicking with all tool act like the PickerTool
  Userland/Applications/PixelPaint/ImageEditor.cpp
  Userland/Applications/PixelPaint/ImageEditor.h
  Userland/Applications/PixelPaint/Tools/CloneTool.h
  Userland/Applications/PixelPaint/Tools/LineTool.h
  Userland/Applications/PixelPaint/Tools/PickerTool.cpp
  Userland/Applications/PixelPaint/Tools/Tool.h
Labels: ⏳ pr-waiting-for-author

#15585 LibJS: Implement RegExp legacy static properties
  Userland/Libraries/LibJS/AST.cpp
  Userland/Libraries/LibJS/CMakeLists.txt
  Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
  Userland/Libraries/LibJS/Runtime/ErrorTypes.h
  Userland/Libraries/LibJS/Runtime/RegExpConstructor.cpp
  Userland/Libraries/LibJS/Runtime/RegExpConstructor.h
  Userland/Libraries/LibJS/Runtime/RegExpLegacyStaticProperties.cpp
  Userland/Libraries/LibJS/Runtime/RegExpLegacyStaticProperties.h
  Userland/Libraries/LibJS/Runtime/RegExpObject.cpp
  Userland/Libraries/LibJS/Runtime/RegExpObject.h
  Userland/Libraries/LibJS/Runtime/RegExpPrototype.cpp
  Userland/Libraries/LibJS/Tests/builtins/RegExp/RegExp.legacy.js
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15505 route: Accept CIDR notation when specifying network
  Userland/Utilities/route.cpp
Labels: ⏳ pr-waiting-for-author

#15670 LibWeb: Use calculate_min_content_height() for sizing of grid children
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#15631 Kernel/USB: Refactor USB Pipe
  Kernel/Bus/USB/USBDevice.cpp
  Kernel/Bus/USB/USBDevice.h
  Kernel/Bus/USB/USBHub.cpp
  Kernel/Bus/USB/USBHub.h
  Kernel/Bus/USB/USBPipe.cpp
  Kernel/Bus/USB/USBPipe.h
Labels: 👀 pr-needs-review

#15673 LibC: Use proper casting in fgetc and fgetc_unlocked functions
  Userland/Libraries/LibC/stdio.cpp
Labels: 👀 pr-needs-review

#15682 LibTimeZone+LibJS: Update to TZDB version 2022e
  Meta/CMake/time_zone_data.cmake
  Tests/LibTimeZone/TestTimeZone.cpp
  Userland/Libraries/LibJS/Tests/builtins/Temporal/TimeZone/TimeZone.prototype.getOffsetNanosecondsFor.js
Labels: 👀 pr-needs-review

#15679 Ports: Make the quake3 port buildable on ARM64 hosts
  Ports/quake3/patches/0001-Meta-Refactor-Makefile-to-support-Serenity.patch
  Ports/quake3/patches/0004-Meta-Add-ldl-library-for-Serenity-target.patch
  Ports/quake3/patches/0006-Meta-Add-ARCH-to-TOOLS_CFLAGS.patch
  Ports/quake3/patches/0007-Meta-Remove-extension-from-main-game-exe.patch
Labels: 👀 pr-needs-review

#15683 PixelPaint: Make Wand Select tool select correctly on moved layers
  Userland/Applications/PixelPaint/Tools/WandSelectTool.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15684 PixelPaint: Add action to invert selection
  Base/res/icons/pixelpaint/invert-selection.png
  Userland/Applications/PixelPaint/IconBag.cpp
  Userland/Applications/PixelPaint/IconBag.h
  Userland/Applications/PixelPaint/MainWidget.cpp
  Userland/Applications/PixelPaint/Selection.cpp
  Userland/Applications/PixelPaint/Selection.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15576 LibGUI: Insert first displayed emoji on return
  Userland/Libraries/LibGUI/EmojiInputDialog.cpp
  Userland/Libraries/LibGUI/EmojiInputDialog.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15704 WebDriver: Implement `GET /session/{session id}/window/handles` endpoint
  Userland/Services/WebDriver/Client.cpp
  Userland/Services/WebDriver/Client.h
  Userland/Services/WebDriver/Session.cpp
  Userland/Services/WebDriver/Session.h
Labels: 👀 pr-needs-review

#15595 Kernel: Don't assume paths to children PID directories in ProcFS code
  Kernel/ProcessSpecificExposed.cpp
Labels: 👀 pr-needs-review

#15706 Base: Add more emoji
  Base/res/emoji/U+1F411.png
  Base/res/emoji/U+1F417.png
  Base/res/emoji/U+1F437.png
  Base/res/emoji/U+1F43B.png
  Base/res/emoji/U+1F43C.png
Labels: ✅ pr-community-approved

#15709 LibJS: A couple of Temporal editorial simplifications
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/ISO8601.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/ISO8601.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15710 LibJS: Refactor CalendarFields for better linearity
  Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
Labels: ✅ pr-community-approved

#15708 Snake: Use emoji for in-game food graphics
  Base/res/icons/snake/cauliflower.png
  Base/res/icons/snake/eggplant.png
  Base/res/icons/snake/paprika.png
  Base/res/icons/snake/tomato.png
  Userland/Games/Snake/SnakeGame.cpp
  Userland/Games/Snake/SnakeGame.h
Labels: ✅ pr-community-approved

#15711 LibWeb: Move pointer-events property check from hit_test method enter to exit
  Userland/Libraries/LibWeb/Painting/Paintable.h
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Labels: 👀 pr-needs-review

#15716 AK: Do not append string bytes as code points when title-casing a string
  AK/StringUtils.cpp
  Tests/AK/TestStringUtils.cpp
Labels: 👀 pr-needs-review

#15727 Webdriver endpoints in tab
  Userland/Applications/Browser/BrowserWindow.cpp
  Userland/Applications/Browser/Tab.h
  Userland/Applications/Browser/WebDriverConnection.cpp
  Userland/Applications/Browser/WebDriverEndpoints.h
Labels: 👀 pr-needs-review

#15734 Base: Add more emoji
  Base/res/emoji/U+1F400.png
  Base/res/emoji/U+1F401.png
  Base/res/emoji/U+1F407.png
  Base/res/emoji/U+1F415.png
  Base/res/emoji/U+1F416.png
  Base/res/emoji/U+1F423.png
  Base/res/emoji/U+1F425.png
  Base/res/emoji/U+1F429.png
  Base/res/emoji/U+1F43F.png
  Base/res/emoji/U+1F98C.png
  Base/res/emoji/U+1F98E.png
  Base/res/emoji/U+1F997.png
  Base/res/emoji/U+1F9A5.png
  Base/res/emoji/U+1F9EE.png
  Base/res/emoji/U+1FAB3.png
Labels: 👀 pr-needs-review

#15738 Magnifier: Add Always on Top
  Userland/Applications/Magnifier/main.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15737 Base: Add some clock emoji
  Base/res/emoji/U+23F0.png
  Base/res/emoji/U+23F1.png
  Base/res/emoji/U+23F2.png
Labels: ✅ pr-community-approved

#15739 Base: Add WC emoji and other blue block ones
  Base/res/emoji/U+1F6B9.png
  Base/res/emoji/U+1F6BE.png
  Base/res/emoji/U+1F6C2.png
  Base/res/emoji/U+1F6C3.png
  Base/res/emoji/U+1F6C4.png
  Base/res/emoji/U+1F6C5.png
  Base/res/emoji/U+1F6D7.png
Labels: ✅ pr-community-approved

#15735 Base: Add cool emoji
  Base/res/emoji/U+1F32B.png
  Base/res/emoji/U+1F361.png
  Base/res/emoji/U+1F3A3.png
  Base/res/emoji/U+1F3B4.png
  Base/res/emoji/U+1F413.png
  Base/res/emoji/U+1F456.png
  Base/res/emoji/U+1F45C.png
  Base/res/emoji/U+1F5EF.png
  Base/res/emoji/U+1F684.png
  Base/res/emoji/U+1F685.png
  Base/res/emoji/U+1F686.png
  Base/res/emoji/U+1F6B0.png
  Base/res/emoji/U+1F6B1.png
  Base/res/emoji/U+1F6FB.png
  Base/res/emoji/U+1F9C6.png
  Base/res/emoji/U+1F9F4.png
  Base/res/emoji/U+1FAB0.png
  Base/res/emoji/U+1FAB1.png
  Base/res/emoji/U+1FAD4.png
  Base/res/emoji/U+2618.png
Labels: 👀 pr-needs-review

#15743 Snake: Add 18 new animals for the snake to eat
  Userland/Games/Snake/SnakeGame.cpp
Labels: 👀 pr-needs-review

#15557 Utilities: Add jq-like json query functionality to `jp`
  Userland/Utilities/CMakeLists.txt
  Userland/Utilities/json.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15749 Base: Rename jp(1) manual page to json(1)
  Base/usr/share/man/man1/jp.md
  Base/usr/share/man/man1/json.md
Labels: 👀 pr-needs-review

#15752 SystemServer: Fix race condition in Service::determine_account()
  Userland/Services/SystemServer/Service.cpp
Labels: 👀 pr-needs-review

#15529 Kernel+USB: Fix USB on 64-bit platforms
  Kernel/Bus/USB/UHCI/UHCIDescriptorTypes.h
Labels: 👀 pr-needs-review

#15742 Base: Add 25 emojis
  Base/res/emoji/U+1F696.png
  Base/res/emoji/U+1F6A2.png
  Base/res/emoji/U+1F9DF.png
  Base/res/emoji/U+1F9F8.png
  Base/res/emoji/U+1FA97.png
  Base/res/emoji/U+1FAAF.png
  Base/res/emoji/U+1FAB7.png
  Base/res/emoji/U+1FAC1.png
  Base/res/emoji/U+1FAD9.png
  Base/res/emoji/U+2194.png
  Base/res/emoji/U+2195.png
  Base/res/emoji/U+2196.png
  Base/res/emoji/U+2197.png
  Base/res/emoji/U+2198.png
  Base/res/emoji/U+2199.png
  Base/res/emoji/U+24C2.png
  Base/res/emoji/U+25AA.png
  Base/res/emoji/U+25AB.png
  Base/res/emoji/U+25FB.png
  Base/res/emoji/U+25FC.png
  Base/res/emoji/U+25FD.png
  Base/res/emoji/U+25FE.png
  Base/res/emoji/U+2733.png
  Base/res/emoji/U+27B0.png
  Base/res/emoji/U+2B55.png
Labels: ✅ pr-community-approved

#15760 Kernel/Graphics: Handle correctly unknown ioctls on a DisplayConnector
  Kernel/Graphics/DisplayConnector.cpp
  Kernel/Graphics/DisplayConnector.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15762 Ports: Prefix output with the build step and port name
  Ports/.port_include.sh
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15726 Toolchain: Update LLVM to 15.0.3
  CMakeLists.txt
  Ports/AvailablePorts.md
  Ports/llvm/package.sh
  Toolchain/BuildClang.sh
Labels: 👀 pr-needs-review

#15780 LibWeb: Layout inner floats/abspos boxes after laying out the top float
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Labels: 👀 pr-needs-review

#15779 LibWeb: Teach MainThreadVM about module scripts
  Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp
  Userland/Libraries/LibWeb/Bindings/MainThreadVM.h
Labels: 👀 pr-needs-review

#15785 LiBJS: Accept calendar names case-insensitively
  Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
Labels: 👀 pr-needs-review, ✅ pr-community-approved

#15777 LibGfx: Make Rect::set_{bottom,right}_without_resize() work for non-int
  Userland/Libraries/LibGfx/Rect.h
Labels: 👀 pr-needs-review

#15755 PixelPaint: Limit editing tools to selection
  Userland/Applications/PixelPaint/Layer.cpp
  Userland/Applications/PixelPaint/Layer.h
  Userland/Applications/PixelPaint/Tools/BrushTool.cpp
  Userland/Applications/PixelPaint/Tools/BucketTool.cpp
  Userland/Applications/PixelPaint/Tools/EllipseTool.cpp
  Userland/Applications/PixelPaint/Tools/LineTool.cpp
  Userland/Applications/PixelPaint/Tools/RectangleTool.cpp
  Userland/Applications/PixelPaint/Tools/SprayTool.cpp
Labels: 👀 pr-needs-review

#15712 mv: Support the '--no-clobber' option
  Userland/Utilities/mv.cpp
Labels: 👀 pr-needs-review

#15721 Inspector: Reopen picker UI after selecting Inspector
  Userland/DevTools/Inspector/main.cpp
Labels: 👀 pr-needs-review

#15705 LibLocale+LibJS: Update to CLDR version 42.0.0
  Meta/CMake/locale_data.cmake
  Meta/Lagom/Tools/CodeGenerators/LibLocale/GenerateDateTimeFormatData.cpp
  Meta/Lagom/Tools/CodeGenerators/LibLocale/GenerateLocaleData.cpp
  Userland/Libraries/LibJS/Tests/builtins/Date/Date.prototype.toLocaleString.js
  Userland/Libraries/LibJS/Tests/builtins/Date/Date.prototype.toLocaleTimeString.js
  Userland/Libraries/LibJS/Tests/builtins/Intl/DateTimeFormat/DateTimeFormat.prototype.format.js
  Userland/Libraries/LibJS/Tests/builtins/Intl/DateTimeFormat/DateTimeFormat.prototype.formatRange.js
  Userland/Libraries/LibJS/Tests/builtins/Intl/DateTimeFormat/DateTimeFormat.prototype.formatRangeToParts.js
  Userland/Libraries/LibJS/Tests/builtins/Intl/DateTimeFormat/DateTimeFormat.prototype.formatToParts.js
  Userland/Libraries/LibJS/Tests/builtins/Intl/DisplayNames/DisplayNames.prototype.of.js
  Userland/Libraries/LibJS/Tests/builtins/Intl/NumberFormat/NumberFormat.prototype.format.js
  Userland/Libraries/LibJS/Tests/builtins/Intl/NumberFormat/NumberFormat.prototype.formatToParts.js
  Userland/Libraries/LibJS/Tests/builtins/Intl/PluralRules/PluralRules.prototype.select.js
  Userland/Libraries/LibJS/Tests/builtins/Intl/RelativeTimeFormat/RelativeTimeFormat.prototype.format.js
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15774 Base: Add just a bit more emojis
  Base/res/emoji/U+1F4D6.png
  Base/res/emoji/U+1F4F9.png
  Base/res/emoji/U+1F52C.png
  Base/res/emoji/U+1F52D.png
  Base/res/emoji/U+1F697.png
  Base/res/emoji/U+1F69B.png
  Base/res/emoji/U+1F9FE.png
  Base/res/emoji/U+1F9FF.png
  Base/res/emoji/U+1FAA1.png
  Base/res/emoji/U+1FAD3.png
Labels: 👀 pr-needs-review

#15793 Ports/python3: Update Python to 3.11.0
  Ports/AvailablePorts.md
  Ports/python3/package.sh
  Ports/python3/patches/0001-Enforce-UTF-8-as-the-locale-encoding.patch
  Ports/python3/patches/0002-Tweak-configure-and-configure.ac.patch
  Ports/python3/patches/0003-Include-sys-uio.h-in-socketmodule.c.patch
  Ports/python3/patches/0004-Tweak-setup.py.patch
  Ports/python3/patches/0005-Tweak-setup.py-sysroot-detection.patch
  Ports/python3/patches/0006-Workaround-for-unsupported-socket-option.patch
  Ports/python3/version.sh
Labels: 👀 pr-needs-review

#15691 LibGUI: Fix EditingEngine Shift + Up/Down highlight behavior
  Userland/Libraries/LibGUI/EditingEngine.cpp
Labels: ⏳ pr-waiting-for-author

#15799 LibWeb: Remove old assertion in host_enqueue_promise_job context hack
  Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp
Labels: 👀 pr-needs-review

#15797 Everywhere: Require version >= 12 for GCC host compiler
  .github/workflows/cmake.yml
  .github/workflows/pvs-studio-static-analysis.yml
  .github/workflows/sonar-cloud-static-analysis.yml
  Documentation/BuildInstructions.md
  Documentation/SelfHostedRunners.md
  Documentation/Troubleshooting.md
  Meta/Azure/Lagom.yml
  Meta/Azure/Serenity.yml
  Meta/Azure/Setup.yml
  Meta/serenity.sh
  Toolchain/Dockerfile
Labels: 👀 pr-needs-review

#15782 LibGUI: Make sure combobox list windows can't be moved
  Userland/DevTools/HackStudio/Locator.cpp
  Userland/Libraries/LibGUI/AutocompleteProvider.cpp
  Userland/Libraries/LibGUI/ComboBox.cpp
  Userland/Services/WindowServer/WindowManager.cpp
  Userland/Services/WindowServer/WindowManager.h
  Userland/Services/WindowServer/WindowType.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15816 GMLPlayground: Replace /proc/all unveil with /sys/kernel/processes
  Userland/DevTools/GMLPlayground/main.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#15806 PixelPaint: Make scopes hideable
  Userland/Applications/PixelPaint/MainWidget.cpp
  Userland/Applications/PixelPaint/PixelPaintWindow.gml
Labels: 👀 pr-needs-review

#15825 LibCore: Limit to the user buffer size when reading lines from a stream
  Userland/Libraries/LibCore/Stream.h
Labels: 👀 pr-needs-review

#15801 Base: Add elephant emoji (U+1F418)
  Base/res/emoji/U+1F418.png
Labels: ✅ pr-community-approved

#15824 Ports: Update RetroArch to 1.12.0 and SDL2_sound to never commit build
  Ports/AvailablePorts.md
  Ports/RetroArch/package.sh
  Ports/SDL2_sound/package.sh
Labels: 👀 pr-needs-review

#15821 Toolchain: Update BuildQemu.sh to qemu-7.1
  Toolchain/BuildQemu.sh
  Toolchain/Patches/qemu-cf-protection-none.patch
Labels: 👀 pr-needs-review

#15818 ntpquery: Fix pledge and unveil invocations
  Userland/Utilities/ntpquery.cpp
Labels: 👀 pr-needs-review

#15829 Emoji: Add Transgender Emoji (⚧ U+2617)
  Base/res/emoji/U+26A7.png
Labels: ⏳ pr-waiting-for-author

#15434 Meta: Convert build directory path to be completely absolute
  Meta/CMake/Superbuild/CMakeLists.txt
Labels: 👀 pr-needs-review, ✅ pr-community-approved

#15460 Ports: Add Lite-XL
  Ports/AvailablePorts.md
  Ports/lite-xl/package.sh
  Ports/lite-xl/patches/0001-Add-SerenityOS-platform-support.patch
  Ports/lite-xl/patches/ReadMe.md
Labels: ⛔️ pr-is-blocked, ✅ pr-community-approved

#15804 Meta: Add configuration file for YouCompleteMe
  .ycm_extra_conf.py
  Documentation/VimConfiguration.md
Labels: 👀 pr-needs-review

#15845 Base: Add Houses, Safety pin emoji
  Base/res/emoji/U+1F3D8.png
  Base/res/emoji/U+1F9F7.png
Labels: 👀 pr-needs-review

#15856 LibGUI: Update buttons' text/tooltips in Action::set_text
  Userland/Libraries/LibGUI/Action.cpp
  Userland/Libraries/LibGUI/Button.cpp
  Userland/Libraries/LibGUI/Button.h
  Userland/Libraries/LibGUI/Toolbar.cpp
Labels: 👀 pr-needs-review

#15841 Meta: Make YCM work when the current dir is not the root of the tree
  .ycm_extra_conf.py
Labels: 👀 pr-needs-review

#15854 Userland: Use Threading::MutexLocker to lock/unlock mutexes
  Userland/Applications/PixelPaint/ImageProcessor.cpp
  Userland/Libraries/LibAudio/ConnectionToServer.cpp
  Userland/Services/AudioServer/Mixer.cpp
Labels: 👀 pr-needs-review

#15839 LibThreading: Set BackgroundAction's thread name correctly
  Userland/Libraries/LibThreading/BackgroundAction.cpp
Labels: 👀 pr-needs-review

#15847 Base: Set PATH in text mode
  Base/etc/SystemServer.ini
Labels: 👀 pr-needs-review

#15850 LibVideo: Make DecoderError getters const
  Userland/Libraries/LibVideo/DecoderError.h
Labels: 👀 pr-needs-review

#15855 Base: Add Scissors & arrows emoji
  Base/res/emoji/U+2702.png
  Base/res/emoji/U+27A1.png
  Base/res/emoji/U+2934.png
  Base/res/emoji/U+2935.png
  Base/res/emoji/U+2B05.png
  Base/res/emoji/U+2B06.png
  Base/res/emoji/U+2B07.png
Labels: 👀 pr-needs-review

#15852 Utilities: Add nologin application
  Userland/Utilities/CMakeLists.txt
  Userland/Utilities/nologin.cpp
Labels: 👀 pr-needs-review, ✅ pr-community-approved
