Repository SerenityOS/serenity, pull requests merged in 2022-12, with the labels that each got.

#16187 AK: Implement FloatExtractor<f128>
  AK/BuiltinWrappers.h
  AK/FloatingPoint.h
  AK/IntegralMath.h
Labels: ✅ pr-community-approved

#16274 Meta+CI: Add CI job specifically for bundling serenity-js artifacts
  .github/workflows/libjs-test262.yml
  .github/workflows/serenity-js-artifacts.yml
  Meta/Lagom/CMakeLists.txt
Labels: 👀 pr-needs-review

#16280 LibGfx: Fix some more antialiased line off-by-ones
  Userland/Libraries/LibGfx/AntiAliasingPainter.cpp
  Userland/Libraries/LibGfx/AntiAliasingPainter.h
  Userland/Libraries/LibGfx/FillPathImplementation.h
Labels: 👀 pr-needs-review

#16284 LibWeb: Fix integer overflow in gradient painting
  Userland/Libraries/LibWeb/Painting/GradientPainting.cpp
Labels: 👀 pr-needs-review

#16287 LibJS: Reduce flakes??
  Userland/Libraries/LibJS/Tests/builtins/Temporal/Now/Now.plainDateTime.js
  Userland/Libraries/LibJS/Tests/builtins/Temporal/Now/Now.plainDateTimeISO.js
  Userland/Libraries/LibJS/Tests/test-common.js
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16289 Kernel: Implement PIT::set_periodic() and PIT::set_non_periodic()
  Kernel/Arch/x86/Time/PIT.cpp
Labels: ✅ pr-community-approved

#16178 Documentation: Recommend CLion code style settings over manual steps
  Documentation/CLionCodeStyleSettings.xml
  Documentation/CLionConfiguration.md
  Documentation/CLion_Naming_Convention.png
Labels: 👀 pr-needs-review

#16301 Utilities: Add strings
  Base/usr/share/man/man1/strings.md
  Userland/Utilities/CMakeLists.txt
  Userland/Utilities/strings.cpp
Labels: 👀 pr-needs-review

#16060 WebDriver: Implement `POST /session/{id}/window` endpoint
  Userland/Libraries/LibWeb/WebDriver/Client.cpp
  Userland/Libraries/LibWeb/WebDriver/Client.h
  Userland/Services/WebContent/WebDriverClient.ipc
  Userland/Services/WebContent/WebDriverConnection.cpp
  Userland/Services/WebContent/WebDriverConnection.h
  Userland/Services/WebDriver/Client.cpp
  Userland/Services/WebDriver/Client.h
Labels: 👀 pr-needs-review

#16313 Kernel: Don't memset() allocated memory twice in kcalloc()
  Kernel/Heap/Heap.h
  Kernel/Heap/kmalloc.cpp
Labels: 👀 pr-needs-review

#16321 LibGUI: Fix a typo
  Userland/Libraries/LibGUI/GroupBox.cpp
  Userland/Libraries/LibGUI/ListView.cpp
  Userland/Libraries/LibGUI/ListView.h
  Userland/Libraries/LibGUI/ScrollableContainerWidget.cpp
  Userland/Libraries/LibGUI/ScrollableContainerWidget.h
  Userland/Libraries/LibGUI/TabWidget.cpp
  Userland/Libraries/LibGUI/Widget.cpp
  Userland/Libraries/LibGUI/Widget.h
Labels: ✅ pr-community-approved

#16317 LibWeb: Fix box-shadows where the border-radius is < the blur-radius
  Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp
Labels: 👀 pr-needs-review

#16192 LibWeb: Do not try to place floating blocks in anonymous nodes
  Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Labels: 👀 pr-needs-review

#16314 AK: Take the chunk header size into account when freeing objects
  AK/BumpAllocator.h
Labels: 👀 pr-needs-review

#16332 Meta: Manually compute the length of the WASM JS REPL source string
  Meta/Lagom/Wasm/js_repl.cpp
Labels: 👀 pr-needs-review

#16330 AK: Introduce the new String, replacement for DeprecatedString
  AK/CMakeLists.txt
  AK/Forward.h
  AK/String.cpp
  AK/String.h
  AK/StringBuilder.cpp
  AK/StringBuilder.h
  AK/StringUtils.cpp
  AK/StringUtils.h
  Tests/AK/CMakeLists.txt
  Tests/AK/TestString.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16302 3DFileViewer: Properly propagate errors from WavefrontOBJLoader
  Userland/Applications/3DFileViewer/MeshLoader.h
  Userland/Applications/3DFileViewer/WavefrontOBJLoader.cpp
  Userland/Applications/3DFileViewer/WavefrontOBJLoader.h
  Userland/Applications/3DFileViewer/main.cpp
Labels: ⏳ pr-waiting-for-author, ⚠️ pr-has-conflicts

#16342 LibGL: Generate GL_OUT_OF_MEMORY error in `glBufferData` when OOM
  Userland/Libraries/LibGL/Buffer.cpp
Labels: 👀 pr-needs-review

#16360 FileManager: Silence the "not found" error when setting no wallpaper
  Userland/Applications/FileManager/main.cpp
Labels: 👀 pr-needs-review

#16123 LibPDF: Add missing character quirk for WinAnsiEncoding Type1 fonts
  Userland/Libraries/LibPDF/Encoding.cpp
  Userland/Libraries/LibPDF/Encoding.h
  Userland/Libraries/LibPDF/Fonts/TrueTypeFont.cpp
  Userland/Libraries/LibPDF/Fonts/Type1Font.cpp
Labels: 👀 pr-needs-review

#16312 WindowServer+MouseSettings: Fix `buttons_switched` naming
  Userland/Applications/MouseSettings/Mouse.gml
  Userland/Applications/MouseSettings/MouseWidget.cpp
  Userland/Demos/Mouse/main.cpp
  Userland/Services/WindowServer/ConnectionFromClient.cpp
  Userland/Services/WindowServer/ConnectionFromClient.h
  Userland/Services/WindowServer/EventLoop.cpp
  Userland/Services/WindowServer/WindowManager.cpp
  Userland/Services/WindowServer/WindowManager.h
  Userland/Services/WindowServer/WindowServer.ipc
Labels: 👀 pr-needs-review

#16365 Tests: add test case for Checked<> decrement operator
  Tests/AK/TestChecked.cpp
Labels: ✅ pr-community-approved

#16398 WebContent+LibWeb+LibJS: Simplify injection of JS console globals
  Userland/Libraries/LibJS/Interpreter.cpp
  Userland/Libraries/LibJS/Interpreter.h
  Userland/Libraries/LibWeb/HTML/Scripting/ClassicScript.cpp
  Userland/Libraries/LibWeb/HTML/Scripting/ClassicScript.h
  Userland/Services/WebContent/CMakeLists.txt
  Userland/Services/WebContent/ConsoleGlobalEnvironmentExtensions.cpp
  Userland/Services/WebContent/ConsoleGlobalEnvironmentExtensions.h
  Userland/Services/WebContent/ConsoleGlobalObject.cpp
  Userland/Services/WebContent/ConsoleGlobalObject.h
  Userland/Services/WebContent/Forward.h
  Userland/Services/WebContent/WebContentConsoleClient.cpp
  Userland/Services/WebContent/WebContentConsoleClient.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16404 LibJS: Remove redundant starts_with()s from is_less_than() string branch
  Userland/Libraries/LibJS/Runtime/Value.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16402 LibWeb: Get rid of some TODOs in Selection
  Userland/Libraries/LibWeb/Selection/Selection.cpp
  Userland/Libraries/LibWeb/Selection/Selection.h
Labels: ✅ pr-community-approved

#16283 Documentation: Add a note on paths in the kernel development guidelines
  Documentation/Kernel/DevelopmentGuidelines.md
Labels: 👀 pr-needs-review

#16307 Documentation: Describe extra clang tools built alongside BuildClang.sh
  CONTRIBUTING.md
  Documentation/AdvancedBuildInstructions.md
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16405 LibJS: Comment all the things, Value.cpp edition
  Userland/Libraries/LibJS/Runtime/Value.cpp
Labels: ✅ pr-community-approved

#16379 LibCore: Use `Core::Stream` for `ProcessStatisticsReader`
  Userland/Applications/SystemMonitor/ProcessModel.cpp
  Userland/Demos/CatDog/CatDog.cpp
  Userland/Demos/CatDog/CatDog.h
  Userland/DevTools/Profiler/main.cpp
  Userland/Libraries/LibCore/ProcessStatisticsReader.cpp
  Userland/Libraries/LibCore/ProcessStatisticsReader.h
  Userland/Libraries/LibCore/SessionManagement.cpp
  Userland/Libraries/LibGUI/RunningProcessesModel.cpp
  Userland/Services/WindowServer/Window.cpp
  Userland/Utilities/killall.cpp
  Userland/Utilities/lsof.cpp
  Userland/Utilities/netstat.cpp
  Userland/Utilities/pgrep.cpp
  Userland/Utilities/pidof.cpp
  Userland/Utilities/pkill.cpp
  Userland/Utilities/ps.cpp
  Userland/Utilities/top.cpp
  Userland/Utilities/w.cpp
Labels: ✅ pr-community-approved

#16392 KeyboardSettings: Disable "activate keymap" button if keymap is active
  Userland/Applications/KeyboardSettings/KeyboardSettingsWidget.cpp
Labels: ✅ pr-community-approved

#16120 CI: Add a check to report git merge commit
  .github/workflows/lintcommits.yml
  Meta/lint-commit.sh
Labels: 👀 pr-needs-review

#16129 Kernel: Set EFLAGS/RFLAGS to a known-good value on signal entry
  Kernel/Thread.cpp
Labels: 👀 pr-needs-review

#16256 LibWeb: Fix buggy text selection
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Labels: 👀 pr-needs-review

#16315 LibGUI: Disable corresponding Scrollbar button when reaching min or max
  Userland/Libraries/LibGUI/Scrollbar.cpp
Labels: 👀 pr-needs-review

#16318 Meta: Switch to the Lagom directory before building fuzzers
  Meta/Lagom/BuildFuzzers.sh
Labels: 👀 pr-needs-review

#16281 LibGUI: Add shortcut for inserting new line in TextEditor
  Userland/Libraries/LibGUI/TextDocument.cpp
  Userland/Libraries/LibGUI/TextDocument.h
  Userland/Libraries/LibGUI/TextEditor.cpp
Labels: ⏳ pr-waiting-for-author

#16434 Help: Link to LibLocale
  Userland/Applications/Help/CMakeLists.txt
Labels: 👀 pr-needs-review

#16411 LibX86: Fix disassembly on x86-64
  Userland/DevTools/UserspaceEmulator/Emulator.cpp
  Userland/Libraries/LibX86/Disassembler.h
  Userland/Libraries/LibX86/Instruction.h
Labels: 👀 pr-needs-review

#16444 Shell: Disable interactive mode on '-c'
  Userland/Shell/main.cpp
Labels: ✅ pr-community-approved

#16069 Browser: Go back/forward when pressing back/forward mouse buttons
  Userland/Applications/Browser/Tab.cpp
  Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
  Userland/Libraries/LibWebView/OutOfProcessWebView.h
Labels: ⏳ pr-waiting-for-author

#16374 LibGUI+TextEditor: Relative line number for TextEditor
  Userland/Applications/TextEditor/MainWidget.cpp
  Userland/Applications/TextEditor/MainWidget.h
  Userland/Libraries/LibGUI/TextEditor.cpp
  Userland/Libraries/LibGUI/TextEditor.h
Labels: ⏳ pr-waiting-for-author, ✅ pr-community-approved

#15986 Games: Add ColorLines
  Base/res/apps/ColorLines.af
  Base/res/icons/16x16/app-colorlines.png
  Base/res/icons/32x32/app-colorlines.png
  Base/res/icons/colorlines/colorlines.png
  Base/usr/share/man/man6/ColorLines.md
  Userland/Games/CMakeLists.txt
  Userland/Games/ColorLines/CMakeLists.txt
  Userland/Games/ColorLines/ColorLines.cpp
  Userland/Games/ColorLines/ColorLines.h
  Userland/Games/ColorLines/HueFilter.h
  Userland/Games/ColorLines/Marble.h
  Userland/Games/ColorLines/MarbleBoard.h
  Userland/Games/ColorLines/MarblePath.h
  Userland/Games/ColorLines/main.cpp
Labels: 👀 pr-needs-review

#16441 PixelPaint: Single-clicking the BrushTool now adds to undo_stack
  Userland/Applications/PixelPaint/Tools/BrushTool.cpp
Labels: 👀 pr-needs-review

#16451 LibHTTP: Don't read and drop data if status line can't be read
  Userland/Libraries/LibHTTP/Job.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16454 AK: Fix build with !USING_AK_GLOBALLY (AK + Jakt Part 3 of N!)
  AK/BuiltinWrappers.h
  AK/NonnullRefPtr.h
  AK/StdLibExtras.h
Labels: ✅ pr-community-approved

#16460 Ports/git: Update git to version 2.39.0
  Ports/AvailablePorts.md
  Ports/git/package.sh
  Ports/git/patches/0001-Remove-some-unimplemented-function-calls.patch
  Ports/git/patches/0002-Remove-uname-detection-in-config.mak.uname.patch
Labels: 👀 pr-needs-review

#16433 Kernel: Propagate errors during network adapter detection/initialization
  Kernel/Net/Intel/E1000ENetworkAdapter.cpp
  Kernel/Net/Intel/E1000ENetworkAdapter.h
  Kernel/Net/Intel/E1000NetworkAdapter.cpp
  Kernel/Net/Intel/E1000NetworkAdapter.h
  Kernel/Net/NE2000/NetworkAdapter.cpp
  Kernel/Net/NE2000/NetworkAdapter.h
  Kernel/Net/NetworkingManagement.cpp
  Kernel/Net/NetworkingManagement.h
  Kernel/Net/Realtek/RTL8139NetworkAdapter.cpp
  Kernel/Net/Realtek/RTL8139NetworkAdapter.h
  Kernel/Net/Realtek/RTL8168NetworkAdapter.cpp
  Kernel/Net/Realtek/RTL8168NetworkAdapter.h
Labels: 👀 pr-needs-review

#16459 Base: Reenable the disabled LibCore::Stream tests
  Base/home/anon/.config/Tests.ini
Labels: 👀 pr-needs-review

#16442 PixelPaint: Use source alpha for CloneTool drawing
  Userland/Applications/PixelPaint/Tools/CloneTool.cpp
Labels: 👀 pr-needs-review

#16467 LibCore: fix struct msghdr initialization
  Userland/Libraries/LibCore/Stream.cpp
Labels: ⏳ pr-waiting-for-author

#16471 LibTimeZone: Update to TZDB version 2022g
  Meta/CMake/time_zone_data.cmake
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16477 LibJS: Support MM/DD/YYYY HH:MM <timezone-offset> format for Date
  Userland/Libraries/LibJS/Runtime/DateConstructor.cpp
  Userland/Libraries/LibJS/Tests/builtins/Date/Date.parse.js
Labels: 👀 pr-needs-review

#16456 Lagom: Don't compile with `-fPIC` on WIN32
  Meta/CMake/lagom_compile_options.cmake
Labels: ✅ pr-community-approved

#16480 LibJS: Explictly assert that a null GCPtr is not dereferenced
  Userland/Libraries/LibJS/Heap/GCPtr.h
Labels: 👀 pr-needs-review

#16475 Everywhere: !USING_AK_GLOBALLY (Jakt integration part 4 of 4)
  AK/Atomic.h
  AK/DeprecatedString.h
  AK/Format.h
  AK/Function.h
  AK/OwnPtr.h
  AK/RefPtr.h
  AK/StdLibExtras.h
  AK/TypedTransfer.h
  AK/Types.h
  AK/WeakPtr.h
  Kernel/Library/LockRefPtr.h
  Kernel/Library/LockWeakPtr.h
  Tests/AK/TestTypeTraits.cpp
  Tests/LibAudio/TestFLACSpec.cpp
  Userland/Applications/BrowserSettings/ContentFilterSettingsWidget.cpp
  Userland/Applications/Presenter/Presentation.cpp
  Userland/DevTools/Profiler/Profile.h
  Userland/Libraries/LibCore/System.h
  Userland/Libraries/LibCrypto/ASN1/DER.cpp
  Userland/Libraries/LibCrypto/ASN1/DER.h
  Userland/Libraries/LibGUI/FileIconProvider.cpp
  Userland/Libraries/LibJS/Bytecode/Op.h
  Userland/Libraries/LibJS/Heap/GCPtr.h
  Userland/Libraries/LibJS/SafeFunction.h
  Userland/Libraries/LibPDF/Value.cpp
  Userland/Libraries/LibPDF/Value.h
  Userland/Libraries/LibSQL/SQLClient.cpp
Labels: 👀 pr-needs-review

#16489 LibJS+LibWeb: Remove NonnullGCPtr<T>::operator=(GCPtr<T>) footgun
  Userland/Libraries/LibJS/Heap/GCPtr.h
  Userland/Libraries/LibWeb/DOM/EventDispatcher.cpp
  Userland/Libraries/LibWeb/DOM/NodeIterator.cpp
  Userland/Libraries/LibWeb/DOM/Range.cpp
  Userland/Libraries/LibWeb/DOM/TreeWalker.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16162 Meta: Don't depend on sudo for privilleged operations
  Meta/.shell_include.sh
  Meta/build-image-extlinux.sh
  Meta/build-image-grub.sh
  Meta/build-image-limine.sh
  Meta/build-image-qemu.sh
  Meta/build-native-partition.sh
Labels: 👀 pr-needs-review

#16490 Help: Move-capture help page path
  Userland/Applications/Help/MainWidget.cpp
Labels: 👀 pr-needs-review

#16474 Base: Add a quote to the fortunes database
  Base/res/fortunes.json
Labels: 👀 pr-needs-review

#16325 Kernel: Add the auxiliary vector to the stack size validation
  Kernel/Process.h
  Kernel/Syscalls/execve.cpp
Labels: ✅ pr-community-approved

#16440 AK: Create relative path even if prefix is not an ancestor of the path
  AK/LexicalPath.cpp
  Tests/AK/TestLexicalPath.cpp
Labels: 👀 pr-needs-review

#16450 Kernel: Convert TCP pseudo-headers through a union
  Kernel/Net/TCPSocket.cpp
Labels: 👀 pr-needs-review

#16447 Kernel: Start implementing `kmalloc_aligned` more efficiently
  Kernel/Heap/Heap.h
  Kernel/Heap/kmalloc.cpp
  Kernel/Heap/kmalloc.h
Labels: 👀 pr-needs-review

#16484 LibArchive: Port `TarOutputStream` to `Core::Stream`
  Userland/Libraries/LibArchive/TarStream.cpp
  Userland/Libraries/LibArchive/TarStream.h
  Userland/Utilities/tar.cpp
Labels: 👀 pr-needs-review

#16481 PixelPaint: Add background color options to "new image" dialog
  Userland/Applications/PixelPaint/CreateNewImageDialog.cpp
  Userland/Applications/PixelPaint/CreateNewImageDialog.h
  Userland/Applications/PixelPaint/MainWidget.cpp
Labels: 👀 pr-needs-review

#16458 LibJS: Don't update names of resulting functions in object expression
  Userland/Libraries/LibJS/AST.cpp
  Userland/Libraries/LibJS/Parser.cpp
  Userland/Libraries/LibJS/Tests/builtins/Object/Object.freeze.js
  Userland/Libraries/LibJS/Tests/object-basic.js
Labels: 👀 pr-needs-review

#16416 Meta+CMake: Extract Wasm spec tests into the binary directory
  CMakeLists.txt
  Meta/CMake/wasm_spec_tests.cmake
  Meta/Lagom/CMakeLists.txt
  Meta/build-root-filesystem.sh
  Userland/Libraries/LibWasm/CMakeLists.txt
Labels: 👀 pr-needs-review

#16345 Kernel: Ignore an invalid QEMU multiboot entry
  Kernel/Memory/MemoryManager.cpp
  Meta/run.sh
Labels: ⏳ pr-waiting-for-author

#16335 LibGfx+Userland: Make LibGfx::SystemTheme propagate errors
  Userland/Applications/DisplaySettings/ThemePreviewWidget.cpp
  Userland/Applications/DisplaySettings/ThemePreviewWidget.h
  Userland/Applications/DisplaySettings/ThemesSettingsWidget.cpp
  Userland/Applications/ThemeEditor/MainWidget.cpp
  Userland/Applications/ThemeEditor/MainWidget.h
  Userland/Applications/ThemeEditor/PreviewWidget.cpp
  Userland/Applications/ThemeEditor/main.cpp
  Userland/Libraries/LibGUI/AbstractThemePreview.cpp
  Userland/Libraries/LibGUI/AbstractThemePreview.h
  Userland/Libraries/LibGfx/SystemTheme.cpp
  Userland/Libraries/LibGfx/SystemTheme.h
  Userland/Services/Taskbar/main.cpp
  Userland/Services/WindowServer/WindowManager.cpp
  Userland/Services/WindowServer/main.cpp
  Userland/Utilities/headless-browser.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16320 Implement remaining value sanitation algorithms
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Labels: ⏳ pr-waiting-for-author

#16472 Base: Add man page for the dd command
  Base/usr/share/man/man1/dd.md
Labels: 👀 pr-needs-review

#16497 gron: Add options for enabling/disabling colored output
  Userland/Utilities/gron.cpp
Labels: ⏳ pr-waiting-for-author

#16505 VirGLDemo: Make a factory function for Demo and propagate errors
  Userland/Demos/VirGLDemo/VirGLDemo.cpp
  Userland/Demos/VirGLDemo/Widget.cpp
  Userland/Demos/VirGLDemo/Widget.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16394 Kernel: Allocate VirtIOGPU context IDs from a bitmap
  Kernel/Graphics/VirtIOGPU/GPU3DDevice.cpp
  Kernel/Graphics/VirtIOGPU/GraphicsAdapter.cpp
  Kernel/Graphics/VirtIOGPU/GraphicsAdapter.h
Labels: ⏳ pr-waiting-for-author

#16438 PixelPaint: Replace vectorscope boxes with colored corner brackets
  Userland/Applications/PixelPaint/VectorscopeWidget.cpp
Labels: ✅ pr-community-approved

#16518 LibWeb: Fix bug in BFC that independent FC assigned to wrong variable
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Labels: ⏳ pr-waiting-for-author

#16517 LibWeb: Stop crashing when assigning null to nullable HTMLTableElement accessors
  Userland/Libraries/LibWeb/HTML/HTMLTableElement.cpp
Labels: 👀 pr-needs-review

#16528 Kernel: Propagate properly errors from ISAIDEController initialization
  Kernel/Arch/x86/ISABus/IDEController.cpp
  Kernel/Arch/x86/ISABus/IDEController.h
  Kernel/Storage/StorageManagement.cpp
Labels: 👀 pr-needs-review

#16502 CatDog: Refactor to simplify animation frame logic and fix minor bugs
  Userland/Demos/CatDog/CatDog.cpp
  Userland/Demos/CatDog/CatDog.h
  Userland/Demos/CatDog/SpeechBubble.cpp
  Userland/Demos/CatDog/main.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16539 Kernel/Plan9FS: Propagate errors in Plan9FSMessage::append_data
  Kernel/FileSystem/Plan9FS/Inode.cpp
  Kernel/FileSystem/Plan9FS/Message.cpp
  Kernel/FileSystem/Plan9FS/Message.h
Labels: 👀 pr-needs-review

#16538 Tests: ASCII-betical-ize CMakeLists AK tests
  Tests/AK/CMakeLists.txt
Labels: 👀 pr-needs-review

#16545 Kernel: Add a factory function for E1000NetworkAdapter
  Kernel/Net/Intel/E1000NetworkAdapter.cpp
Labels: ⏳ pr-waiting-for-author

#16535 LibWeb: Improve variable name in HTMLTableElement
  Userland/Libraries/LibWeb/HTML/HTMLTableElement.cpp
Labels: 👀 pr-needs-review

#16533 SystemMonitor: Propagate errors when trying to load an icon
  Userland/Applications/SystemMonitor/main.cpp
Labels: ✅ pr-community-approved

#16525 AK+Everywhere: Move custom deleter capability to OwnPtr
  AK/DefaultDelete.h
  AK/Forward.h
  AK/NonnullRefPtr.h
  AK/OwnPtr.h
  AK/OwnPtrWithCustomDeleter.h
  AK/RefPtr.h
  Kernel/Library/LockRefPtr.h
  Kernel/Library/NonnullLockRefPtr.h
  Tests/AK/CMakeLists.txt
  Tests/AK/TestOwnPtr.cpp
  Userland/Libraries/LibCore/System.cpp
  Userland/Libraries/LibCore/System.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16563 LibWeb: Don't const_cast layout_box() when calling const functions
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Labels: 👀 pr-needs-review

#16585 LibGfx: Split VERIFY statements in various Bitmap class methods
  Userland/Libraries/LibGfx/Bitmap.h
Labels: 👀 pr-needs-review

#16582 LibCore: Convert explicit timezone to local in `DateTime::parse`
  Userland/Libraries/LibCore/DateTime.cpp
Labels: 👀 pr-needs-review

#16508 LibWeb: Fully Implement `get_an_elements_noopener`
  Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.h
  Userland/Libraries/LibWeb/HTML/HTMLAreaElement.h
  Userland/Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp
  Userland/Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.h
Labels: ⏳ pr-waiting-for-author

#16540 Documentation: Adjusted default TARGET to x86_64 in the documentation
  Documentation/BuildInstructions.md
  Meta/serenity.sh
Labels: ⏳ pr-waiting-for-author

#16586 AK: Use __has_builtin() in Checked.h
  AK/Checked.h
Labels: 👀 pr-needs-review

#16573 LibGfx: Support BMP favicons with less than 32 bpp
  Base/res/icons/16x16/serenity.ico
  Tests/LibGfx/TestImageDecoder.cpp
  Userland/Libraries/LibGfx/BMPLoader.cpp
  Userland/Libraries/LibGfx/BMPLoader.h
  Userland/Libraries/LibGfx/ICOLoader.cpp
Labels: 👀 pr-needs-review

#16591 LibGUI: Fix bug in the ColorPicker's spinbox not changing colors
  Userland/Libraries/LibGUI/ColorPicker.cpp
Labels: 👀 pr-needs-review

#16461 Ports: Add grepcidr port
  Ports/AvailablePorts.md
  Ports/grepcidr/package.sh
Labels: 👀 pr-needs-review, ✅ pr-community-approved

#16559 PixelPaint: Propagate errors when creating images or layers
  Userland/Applications/PixelPaint/MainWidget.cpp
  Userland/Applications/PixelPaint/MainWidget.h
  Userland/Applications/PixelPaint/main.cpp
Labels: 👀 pr-needs-review

#16552 FileManager: Handle possible ByteBuffer allocation failure
  Userland/Applications/FileManager/FileOperationProgressWidget.cpp
Labels: 👀 pr-needs-review

#16519 AK: Add DeprecatedString::find_last(StringView)
  AK/DeprecatedString.h
  AK/StringUtils.cpp
  AK/StringUtils.h
  AK/StringView.h
Labels: ⏳ pr-waiting-for-author

#16588 Meta: Tweak shell_include.sh
  Meta/build-image-extlinux.sh
  Meta/build-image-grub.sh
  Meta/build-image-limine.sh
  Meta/build-image-qemu.sh
  Meta/build-native-partition.sh
  Meta/shell_include.sh
Labels: ✅ pr-community-approved

#16600 Lagom: Remove test apps
  Meta/Lagom/CMakeLists.txt
  Meta/Lagom/TestApp.cpp
  Meta/Lagom/TestJson.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16598 LibUnicode: Use www.unicode.org domain to download emoji-test.txt
  Meta/CMake/unicode_data.cmake
Labels: 👀 pr-needs-review

#16593 CMake: Fall back to the Web Archive when downloading files
  Meta/CMake/utils.cmake
Labels: 👀 pr-needs-review

#16547 Kernel/FileSystem: Prevent symlink creation in veiled directory paths
  Kernel/FileSystem/VirtualFileSystem.cpp
Labels: ✅ pr-community-approved

#16624 AK: Rearrange Error's members to reduce its size by 8 bytes
  AK/Error.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16529 Base: Mention new immutable memory mappings security feature
  Base/usr/share/man/man7/Mitigations.md
Labels: 👀 pr-needs-review

#16621 Spreadsheet: Allow Functions Help HorizontalSplitter to resize
  Userland/Applications/Spreadsheet/HelpWindow.cpp
Labels: 👀 pr-needs-review

#16608 pro: Add ability to log request/response metadata for HTTP URLs
  Userland/Utilities/CMakeLists.txt
  Userland/Utilities/pro.cpp
Labels: 👀 pr-needs-review

#16607 LibSQL: Specific error message on failed socket creation
  Userland/Libraries/LibSQL/SQLClient.cpp
Labels: 👀 pr-needs-review

#16635 TextEditor: Add option to open the current file in File Manager
  Userland/Applications/TextEditor/MainWidget.cpp
  Userland/Applications/TextEditor/MainWidget.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16646 LibWeb: Apply CSS text-transform during layout
  Userland/Libraries/LibWeb/Layout/TextNode.cpp
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Labels: 👀 pr-needs-review

#16651 LibWeb: Keep unhandledrejection event promises alive when task is queued
  Userland/Libraries/LibWeb/HTML/Scripting/Environments.cpp
  Userland/Libraries/LibWeb/HTML/Scripting/Environments.h
Labels: 👀 pr-needs-review

#16654 LibGL+LibWeb: Remove WebGL-specific API from GLContext
  Tests/LibGL/TestAPI.cpp
  Userland/Libraries/LibGL/ContextParameter.cpp
  Userland/Libraries/LibGL/GL/gl.h
  Userland/Libraries/LibGL/GLContext.h
  Userland/Libraries/LibWeb/WebGL/WebGLRenderingContextBase.cpp
Labels: 👀 pr-needs-review

#16565 HackStudio: Remove `release_value_but_fixme_should_propogate_errors`s
  Userland/DevTools/HackStudio/HackStudioWidget.cpp
  Userland/DevTools/HackStudio/HackStudioWidget.h
  Userland/DevTools/HackStudio/main.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16662 Base: Mention pledge promise for jail-specific syscalls
  Base/usr/share/man/man2/pledge.md
Labels: 👀 pr-needs-review

#16667 LibJS: Add yearOfWeek calendar methods and properties
  Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
  Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/Calendar.h
  Userland/Libraries/LibJS/Runtime/Temporal/CalendarPrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/CalendarPrototype.h
  Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.h
  Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.h
  Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.h
  Userland/Libraries/LibJS/Tests/builtins/Temporal/Calendar/Calendar.prototype.yearOfWeek.js
  Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.prototype.yearOfWeek.js
  Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDateTime/PlainDateTime.prototype.yearOfWeek.js
  Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.yearOfWeek.js
Labels: 👀 pr-needs-review

#16542 PixelPaint: Redraw active layer boundary when the active layer changes
  Userland/Applications/PixelPaint/ImageEditor.cpp
Labels: 👀 pr-needs-review

#16647 Kernel: Add some Aarch64 processor register accessors
  Kernel/Arch/aarch64/Registers.h
Labels: ✅ pr-community-approved

#16672 LibWeb: Add missing return statement in an element scrolling error case
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16669 LibWeb: Fix out of bounds grid error in Github
  Base/res/html/misc/display-grid.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#16660 Shell: Add where builtin
  Userland/Shell/Builtin.cpp
  Userland/Shell/Shell.h
Labels: 👀 pr-needs-review

#16693 Demos: Add ability to use scroll wheel in starfield
  Userland/Demos/Starfield/Starfield.cpp
Labels: 👀 pr-needs-review

#16696 CI: Remove extraneous toolchain job from Azure CI
  Meta/Azure/Serenity.yml
  Meta/Azure/Toolchain.yml
  azure-pipelines.yml
Labels: 👀 pr-needs-review

#16708 AK: Add tests for LittleEndian<enum class>
  Tests/AK/TestEndian.cpp
Labels: 👀 pr-needs-review

#16703 AK: Fix constructing ErrorOr from ErrorOr of a related type
  AK/Error.h
Labels: 👀 pr-needs-review

#16713 Presenter: Accept file drops
  Userland/Applications/Presenter/PresenterWidget.cpp
  Userland/Applications/Presenter/PresenterWidget.h
Labels: 👀 pr-needs-review

#16716 Base: Add more emoji
  Base/res/emoji/U+1F462.png
  Base/res/emoji/U+1F469_U+200D_U+2764_U+200D_U+1F469.png
  Base/res/emoji/U+1F4C7.png
  Base/res/emoji/U+1F4DA.png
  Base/res/emoji/U+1F575.png
  Base/res/emoji/U+1F5B2.png
  Base/res/emoji/U+1F5C3.png
  Base/res/emoji/U+1F6B8.png
  Base/res/emoji/U+1F99D.png
  Base/res/emoji/U+1F9C4.png
  Base/res/emoji/U+1F9F9.png
  Base/res/emoji/U+1FAC2.png
  Base/res/emoji/U+26F2.png
Labels: 👀 pr-needs-review

#16712 Documentation: Update FontEditor document to be in-sync with latest
  Base/usr/share/man/man1/FontEditor.md
Labels: 👀 pr-needs-review

#16720 MouseSettings: Update "switch buttons" icon to reflect checkbox state
  Base/res/graphics/mouse-button-left.png
  Base/res/graphics/mouse-button-right.png
  Base/res/graphics/switch-mouse-buttons.png
  Userland/Applications/MouseSettings/Mouse.gml
  Userland/Applications/MouseSettings/MouseWidget.cpp
  Userland/Applications/MouseSettings/MouseWidget.h
Labels: 👀 pr-needs-review

#16725 Toolchain: Fix aarch64 toolchain GDB build
  Toolchain/BuildIt.sh
Labels: 👀 pr-needs-review

#16634 Kernel: Disallow executing SUID binaries if process is jailed
  Base/usr/share/man/man7/Mitigations.md
  Kernel/Process.h
  Kernel/Syscalls/execve.cpp
  Kernel/Syscalls/jail.cpp
Labels: 👀 pr-needs-review

#16617 Ports: Use absolute path of script
  Ports/.hosted_defs.sh
  Ports/.port_include.sh
Labels: 👀 pr-needs-review

#16683 Utilities: Fix top utility not calling exit() on SIGINT
  Userland/Utilities/top.cpp
Labels: 👀 pr-needs-review

#16309 LibAudio: Prevent int overflow in the user buffer queue.
  Userland/Libraries/LibAudio/UserSampleQueue.cpp
Labels: ✅ pr-community-approved

#16704 LibGUI: fix invalid ModelIndices during shift-click multiselection
  Userland/Libraries/LibGUI/AbstractView.cpp
Labels: ✅ pr-community-approved

#16414 Browser: Add window to inspect history
  Userland/Applications/Browser/BrowserWindow.cpp
  Userland/Applications/Browser/CMakeLists.txt
  Userland/Applications/Browser/History.cpp
  Userland/Applications/Browser/History.h
  Userland/Applications/Browser/History/HistoryModel.cpp
  Userland/Applications/Browser/History/HistoryModel.h
  Userland/Applications/Browser/History/HistoryWidget.cpp
  Userland/Applications/Browser/History/HistoryWidget.gml
  Userland/Applications/Browser/History/HistoryWidget.h
  Userland/Applications/Browser/Tab.cpp
  Userland/Applications/Browser/Tab.h
Labels: 👀 pr-needs-review

#16587 Kernel/Graphics: Restore VirtIO GPU framebuffer console functionality
  Kernel/Graphics/VirtIOGPU/Console.cpp
  Kernel/Graphics/VirtIOGPU/Console.h
  Kernel/Graphics/VirtIOGPU/DisplayConnector.cpp
  Kernel/Graphics/VirtIOGPU/DisplayConnector.h
  Kernel/Graphics/VirtIOGPU/GraphicsAdapter.cpp
Labels: 👀 pr-needs-review

#16740 LibWeb: Fix table-row y-position
  Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Labels: 👀 pr-needs-review

#16752 LibWeb: Paint repeating background images over entire paint box
  Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
Labels: 👀 pr-needs-review

#16751 LibGfx+icc: Print profile flags
  Userland/Libraries/LibGfx/ICCProfile.cpp
  Userland/Libraries/LibGfx/ICCProfile.h
  Userland/Utilities/icc.cpp
Labels: 👀 pr-needs-review

#16729 LibGfx+icc: Add profile connection space printing
  Userland/Libraries/LibGfx/ICCProfile.cpp
  Userland/Libraries/LibGfx/ICCProfile.h
  Userland/Utilities/icc.cpp
Labels: 👀 pr-needs-review

#16748 AK: Prefer VERIFY_NOT_REACHED in ByteBuffer
  AK/ByteBuffer.h
Labels: 👀 pr-needs-review
