Repository SerenityOS/serenity, pull requests merged in 2023-12, with the labels that each got.

#22106 Everywhere: Replace `ElfW(type)` macro usage with `Elf_type`
  Kernel/Prekernel/init.cpp
  Kernel/Syscalls/execve.cpp
  Kernel/Syscalls/mmap.cpp
  Kernel/Tasks/Coredump.cpp
  Kernel/Tasks/Process.h
  Userland/Libraries/LibC/link.h
  Userland/Libraries/LibELF/DynamicLinker.cpp
  Userland/Libraries/LibELF/DynamicLoader.cpp
  Userland/Libraries/LibELF/DynamicLoader.h
  Userland/Libraries/LibELF/DynamicObject.cpp
  Userland/Libraries/LibELF/DynamicObject.h
  Userland/Libraries/LibELF/ELFABI.h
  Userland/Libraries/LibELF/Image.cpp
  Userland/Libraries/LibELF/Image.h
  Userland/Libraries/LibELF/Relocation.cpp
  Userland/Libraries/LibELF/Validation.cpp
  Userland/Libraries/LibELF/Validation.h
  Userland/Utilities/file.cpp
  Userland/Utilities/ldd.cpp
  Userland/Utilities/readelf.cpp
Labels: 👀 pr-needs-review

#22110 LibGfx/TIFF: Automatically export all enums associated with tags
  Userland/Libraries/LibGfx/TIFFGenerator.py
Labels: 👀 pr-needs-review

#22101 LIBJS: Call builtins directly in the bytecode interpreter
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
  Userland/Libraries/LibJS/Runtime/MathObject.cpp
  Userland/Libraries/LibJS/Runtime/MathObject.h
  Userland/Libraries/LibJS/Runtime/Realm.h
Labels: 👀 pr-needs-review

#22113 CI: Disable running aarch64 tests in CI for now
  .github/workflows/cmake.yml
Labels: 👀 pr-needs-review

#22112 LibWeb: Port CSSNamespaceRule to FlyString
  Userland/Libraries/LibWeb/CSS/CSSNamespaceRule.cpp
  Userland/Libraries/LibWeb/CSS/CSSNamespaceRule.h
  Userland/Libraries/LibWeb/CSS/CSSStyleSheet.cpp
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#22088 LibWeb+WebContent: Plumb ability for WebContent process to hold N pages
  Ladybird/WebContent/CMakeLists.txt
  Ladybird/WebContent/main.cpp
  Userland/Libraries/LibWeb/Page/Page.cpp
  Userland/Libraries/LibWeb/Page/Page.h
  Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
  Userland/Services/WebContent/CMakeLists.txt
  Userland/Services/WebContent/ConnectionFromClient.cpp
  Userland/Services/WebContent/ConnectionFromClient.h
  Userland/Services/WebContent/Forward.h
  Userland/Services/WebContent/PageClient.cpp
  Userland/Services/WebContent/PageClient.h
  Userland/Services/WebContent/PageHost.cpp
  Userland/Services/WebContent/PageHost.h
Labels: 👀 pr-needs-review

#22121 LibGfx/TIFF: Support TIFF 5.0 LZW images
  Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Labels: ✅ pr-community-approved

#22122 LibWeb/HTML: Implement text attribute in HTMLTitleElement
  Tests/LibWeb/Text/expected/title.txt
  Tests/LibWeb/Text/input/title.html
  Userland/Libraries/LibWeb/HTML/HTMLTitleElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLTitleElement.h
  Userland/Libraries/LibWeb/HTML/HTMLTitleElement.idl
Labels: 👀 pr-needs-review

#22083 LibGfx/TIFF: Support the ICCProfile tag
  Tests/LibGfx/TestICCProfile.cpp
  Tests/LibGfx/test-inputs/icc/icc.tiff
  Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
  Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.h
  Userland/Libraries/LibGfx/TIFFGenerator.py
Labels: 👀 pr-needs-review

#22109 LibGfx/TIFF: Decode all PackedBits beforehand
  Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Labels: ✅ pr-community-approved

#22125 LibGfx: Eliminate multiplication integer overflow in planar_to_chunky
  Userland/Libraries/LibGfx/ImageFormats/ILBMLoader.cpp
Labels: 👀 pr-needs-review

#22132 LibGfx+LibWeb: Calculate and save glyph positions during layout
  Tests/LibWeb/Ref/reference/images/object-fit-position.png
  Tests/LibWeb/Ref/reference/images/text-shadow-ref.png
  Userland/Libraries/LibGfx/Painter.cpp
  Userland/Libraries/LibGfx/TextLayout.cpp
  Userland/Libraries/LibGfx/TextLayout.h
  Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/InlineLevelIterator.cpp
  Userland/Libraries/LibWeb/Layout/InlineLevelIterator.h
  Userland/Libraries/LibWeb/Layout/LineBox.cpp
  Userland/Libraries/LibWeb/Layout/LineBox.h
  Userland/Libraries/LibWeb/Layout/LineBoxFragment.h
  Userland/Libraries/LibWeb/Layout/LineBuilder.cpp
  Userland/Libraries/LibWeb/Layout/LineBuilder.h
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.cpp
  Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
  Userland/Libraries/LibWeb/Painting/RecordingPainter.h
Labels: 👀 pr-needs-review

#22126 LibPDF: Eliminate reference cycle between OutlineItem parent/children
  Userland/Libraries/LibPDF/Document.h
Labels: ✅ pr-community-approved

#22149 LibWeb/Painting: Use scaled font for selected text
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Labels: 👀 pr-needs-review

#22147 LibWeb: Don't get stuck in TreeWalker.nextNode() when current detached
  Tests/LibWeb/Text/expected/DOM/TreeWalker-nextNode-with-detached-currentNode.txt
  Tests/LibWeb/Text/input/DOM/TreeWalker-nextNode-with-detached-currentNode.html
  Userland/Libraries/LibWeb/DOM/TreeWalker.cpp
Labels: 👀 pr-needs-review

#22156 LibWebView: Draw some knurling on the draggable Inspector separator
  Base/res/html/inspector/inspector.css
  Userland/Libraries/LibWebView/InspectorClient.cpp
Labels: 👀 pr-needs-review

#22107 Documentation: Begin document on execution and navigation in LibWeb
  Documentation/Browser/BrowsingContextsAndNavigables.md
Labels: 👀 pr-needs-review

#22162 LibAccelGfx: Set blending for alpha separately to be sum of src and dst
  Userland/Libraries/LibAccelGfx/GL.cpp
  Userland/Libraries/LibAccelGfx/GL.h
  Userland/Libraries/LibAccelGfx/Painter.cpp
Labels: 👀 pr-needs-review

#22100 Ladybird/AppKit: Remove theme color changing background color
  Ladybird/AppKit/UI/LadybirdWebView.h
  Ladybird/AppKit/UI/LadybirdWebView.mm
  Ladybird/AppKit/UI/Tab.mm
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#22168 WebWorker: Log URL and reason for Worker script load failure
  Userland/Services/WebWorker/DedicatedWorkerHost.cpp
Labels: 👀 pr-needs-review

#22171 LibAccelGfx: Update scissor test after switching between painters
  Userland/Libraries/LibAccelGfx/Painter.cpp
Labels: 👀 pr-needs-review

#22175 LibPDF: Convert LAB values to bytes differently
  Userland/Libraries/LibPDF/ColorSpace.cpp
Labels: 👀 pr-needs-review

#22185 LibPDF: Fix decoding of IndexedColorSpace for palette sizes != 255
  Userland/Libraries/LibPDF/ColorSpace.cpp
Labels: 👀 pr-needs-review

#22184 Ports: Update curl to 8.5.0
  Ports/AvailablePorts.md
  Ports/curl/package.sh
Labels: 👀 pr-needs-review

#21889 Snake: Use new GML compiler
  Userland/Games/Snake/CMakeLists.txt
  Userland/Games/Snake/Game.cpp
  Userland/Games/Snake/MainWidget.h
  Userland/Games/Snake/Snake.gml
  Userland/Games/Snake/main.cpp
Labels: 👀 pr-needs-review

#22191 LibJS: Elide empty lexical environment in for..in/of blocks
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Labels: 👀 pr-needs-review

#22194 LibJS: Stop converting between Object <-> IteratorRecord all the time
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
  Userland/Libraries/LibJS/Bytecode/CommonImplementations.cpp
  Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
  Userland/Libraries/LibJS/Bytecode/Instruction.h
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
  Userland/Libraries/LibJS/Bytecode/Op.h
  Userland/Libraries/LibJS/Forward.h
  Userland/Libraries/LibJS/JIT/Compiler.cpp
  Userland/Libraries/LibJS/JIT/Compiler.h
  Userland/Libraries/LibJS/Runtime/ArrayConstructor.cpp
  Userland/Libraries/LibJS/Runtime/AsyncFromSyncIterator.cpp
  Userland/Libraries/LibJS/Runtime/AsyncFromSyncIterator.h
  Userland/Libraries/LibJS/Runtime/AsyncFromSyncIteratorPrototype.cpp
  Userland/Libraries/LibJS/Runtime/AsyncFromSyncIteratorPrototype.h
  Userland/Libraries/LibJS/Runtime/Iterator.cpp
  Userland/Libraries/LibJS/Runtime/Iterator.h
  Userland/Libraries/LibJS/Runtime/IteratorConstructor.cpp
  Userland/Libraries/LibJS/Runtime/IteratorHelper.cpp
  Userland/Libraries/LibJS/Runtime/IteratorHelper.h
  Userland/Libraries/LibJS/Runtime/IteratorPrototype.cpp
  Userland/Libraries/LibJS/Runtime/Object.h
  Userland/Libraries/LibJS/Runtime/PromiseConstructor.cpp
  Userland/Libraries/LibJS/Runtime/VM.cpp
Labels: 👀 pr-needs-review

#21324 LibGfx/ILBMLoader: add HAM6/HAM8 support
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/ilbm/ham6.iff
  Userland/Libraries/LibGfx/ImageFormats/ILBMLoader.cpp
Labels: ✅ pr-community-approved

#22196 LibJS: Remove dedicated iterator result instructions in favor of GetById
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
  Userland/Libraries/LibJS/Bytecode/Generator.cpp
  Userland/Libraries/LibJS/Bytecode/Generator.h
  Userland/Libraries/LibJS/Bytecode/Instruction.h
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
  Userland/Libraries/LibJS/Bytecode/Op.h
  Userland/Libraries/LibJS/JIT/Compiler.cpp
  Userland/Libraries/LibJS/JIT/Compiler.h
Labels: 👀 pr-needs-review

#21781 Userland: Make bit-fields compatible with MSVC C++ ABI
  Meta/CMake/common_compile_options.cmake
  Userland/Libraries/LibJS/Heap/Cell.h
  Userland/Libraries/LibJS/Runtime/Shape.h
  Userland/Libraries/LibWasm/Wasi.h
  Userland/Libraries/LibX86/Instruction.h
Labels: 👀 pr-needs-review

#22164 LibWeb: Add window.status property
  Userland/Libraries/LibWeb/HTML/Window.cpp
  Userland/Libraries/LibWeb/HTML/Window.h
  Userland/Libraries/LibWeb/HTML/Window.idl
Labels: 👀 pr-needs-review

#22166 LibWeb: Add input stepUp and stepDown functions
  Tests/LibWeb/Text/expected/input-number.txt
  Tests/LibWeb/Text/input/input-number.html
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.idl
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#22201 LibJS: Use a premade shape when creating iterator result objects
  Userland/Libraries/LibJS/Runtime/Intrinsics.cpp
  Userland/Libraries/LibJS/Runtime/Intrinsics.h
  Userland/Libraries/LibJS/Runtime/Iterator.cpp
  Userland/Libraries/LibJS/Runtime/Object.cpp
  Userland/Libraries/LibJS/Runtime/Object.h
Labels: 👀 pr-needs-review

#22206 Kernel/riscv64: Add `.{ro,unmap}_after_init` sections to linker script
  Kernel/Arch/riscv64/linker.ld
Labels: 👀 pr-needs-review

#22219 Ports: Update Python to 3.12.1
  Ports/AvailablePorts.md
  Ports/python3/version.sh
Labels: 👀 pr-needs-review

#22217 Ladybird: Install required html and inspector files in the CMake build
  Ladybird/cmake/InstallRules.cmake
Labels: 👀 pr-needs-review

#22227 LibWeb: Remove default font assignment in NodeWithStyle constructor
  Userland/Libraries/LibWeb/Layout/Node.cpp
Labels: 👀 pr-needs-review

#22226 LibWeb: Remove unused `StyleProperties::clone()` function
  Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
  Userland/Libraries/LibWeb/CSS/StyleProperties.h
Labels: 👀 pr-needs-review

#22220 Tests: Use `TRY_OR_FAIL` instead of `MUST` in TestImageDecoder.cpp
  Tests/LibGfx/TestImageDecoder.cpp
Labels: 👀 pr-needs-review

#22223 LibGfx/TIFF: Add support for bit-depth up to 32 bits per sample
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/tiff/16_bits.tiff
  Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Labels: 👀 pr-needs-review

#22212 LibWeb: Add input number up down UI buttons
  Tests/LibWeb/Layout/expected/input-element-with-display-inline.txt
  Tests/LibWeb/Layout/expected/input-text-node-invalidation-on-value-change.txt
  Tests/LibWeb/Layout/input/input-text-node-invalidation-on-value-change.html
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Labels: 👀 pr-needs-review

#22225 LibWeb: Add output element value
  Tests/LibWeb/Text/expected/output-value.txt
  Tests/LibWeb/Text/input/output-value.html
  Userland/Libraries/LibWeb/HTML/HTMLOutputElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLOutputElement.h
  Userland/Libraries/LibWeb/HTML/HTMLOutputElement.idl
Labels: 👀 pr-needs-review

#22204 Kernel: Make `CrashHandler` more useful before `init_stage2`
  Kernel/Tasks/CrashHandler.cpp
Labels: 👀 pr-needs-review

#22228 LibJS: Don't use Handle<Value> for JS::Object private fields
  Userland/Libraries/LibJS/AST.cpp
  Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
  Userland/Libraries/LibJS/Runtime/Object.cpp
  Userland/Libraries/LibJS/Runtime/Object.h
Labels: 👀 pr-needs-review

#22234 LibWeb: Honor negative margins on atomic inlines
  Tests/LibWeb/Layout/expected/block-and-inline/inline-block-with-negative-margin-left.txt
  Tests/LibWeb/Layout/expected/block-and-inline/inline-block-with-negative-margin-right.txt
  Tests/LibWeb/Layout/input/block-and-inline/inline-block-with-negative-margin-left.html
  Tests/LibWeb/Layout/input/block-and-inline/inline-block-with-negative-margin-right.html
  Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Labels: 👀 pr-needs-review

#22237 LibJS: Add fast path for Uint8ClampedArray Get/Put
  Userland/Libraries/LibJS/Bytecode/CommonImplementations.cpp
Labels: 👀 pr-needs-review

#22235 LibWeb: Add fieldset elements property
  Tests/LibWeb/Text/expected/fieldset-elements.txt
  Tests/LibWeb/Text/input/fieldset-elements.html
  Userland/Libraries/LibWeb/HTML/HTMLFieldSetElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLFieldSetElement.h
  Userland/Libraries/LibWeb/HTML/HTMLFieldSetElement.idl
  Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
Labels: 👀 pr-needs-review

#22239 LibWeb: Bring HTMLElement.offset{Left,Top,Parent} closer to spec
  Tests/LibWeb/Text/expected/HTML/HTMLElement-offsetFoo-in-table-cell.txt
  Tests/LibWeb/Text/input/HTML/HTMLElement-offsetFoo-in-table-cell.html
  Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLElement.h
  Userland/Libraries/LibWeb/HTML/HTMLElement.idl
Labels: 👀 pr-needs-review

#22210 LibWeb: Add internal use_pseudo_selector to element
  Tests/LibWeb/Layout/expected/input-element-with-display-inline.txt
  Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp
  Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.h
  Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
  Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.h
  Userland/Libraries/LibWeb/DOM/Element.h
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLMeterElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLMeterElement.h
  Userland/Libraries/LibWeb/HTML/HTMLProgressElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLProgressElement.h
  Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Labels: 👀 pr-needs-review

#22250 LibWeb: Skip out-of-flow boxes when wrapping inlines in anonymous block
  Tests/LibWeb/Layout/expected/block-and-inline/bfc-consider-all-currently-stacked-floats.txt
  Tests/LibWeb/Layout/expected/block-and-inline/clearfix.txt
  Tests/LibWeb/Layout/expected/block-and-inline/float-2.txt
  Tests/LibWeb/Layout/expected/position-absolute-top-left.txt
  Tests/LibWeb/Layout/expected/resolve-height-of-containing-block.txt
  Tests/LibWeb/Layout/expected/set-margin-of-floating-box.txt
  Tests/LibWeb/Text/expected/hit_testing/float-with-inline-sibling-after.txt
  Tests/LibWeb/Text/input/hit_testing/float-with-inline-sibling-after.html
  Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Labels: 👀 pr-needs-review

#22216 CMake: Don't try to enable install options if no languages are enabled
  Meta/CMake/lagom_install_options.cmake
Labels: 👀 pr-needs-review

#22245 Kernel/Graphics: Don't use `[[gnu::packed]]` on Bochs VGA MMIO register structs
  Kernel/Devices/GPU/Bochs/Definitions.h
Labels: 👀 pr-needs-review, ✅ pr-community-approved

#22257 LibJS/JIT: Add fast path for UnaryMinus on Int32
  Userland/Libraries/LibJS/JIT/Compiler.cpp
  Userland/Libraries/LibJS/JIT/Compiler.h
Labels: 👀 pr-needs-review

#22259 LibWeb: Do not treat a prefix of public suffix as a valid public suffix
  Meta/Lagom/Tools/CodeGenerators/LibWebView/GeneratePublicSuffixData.cpp
Labels: 👀 pr-needs-review

#22263 LibJS+LibWebView+WebContent+Ladybird: Output GC-graph into a file
  Ladybird/Qt/BrowserWindow.cpp
  Userland/Libraries/LibJS/Heap/Heap.cpp
  Userland/Libraries/LibJS/Heap/Heap.h
  Userland/Libraries/LibWebView/ViewImplementation.cpp
  Userland/Libraries/LibWebView/ViewImplementation.h
  Userland/Services/WebContent/ConnectionFromClient.cpp
  Userland/Services/WebContent/ConnectionFromClient.h
  Userland/Services/WebContent/WebContentServer.ipc
Labels: 👀 pr-needs-review

#22218 LibELF: Remove loader reservation after most allocating operations
  Userland/Libraries/LibELF/DynamicLoader.cpp
Labels: 👀 pr-needs-review

#22267 LibWeb: Make HTML::DecodedImageData to be GC-allocated
  Userland/Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.h
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/HTML/AnimatedBitmapDecodedImageData.cpp
  Userland/Libraries/LibWeb/HTML/AnimatedBitmapDecodedImageData.h
  Userland/Libraries/LibWeb/HTML/DecodedImageData.h
  Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLObjectElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLObjectElement.h
  Userland/Libraries/LibWeb/HTML/ImageRequest.cpp
  Userland/Libraries/LibWeb/HTML/ImageRequest.h
  Userland/Libraries/LibWeb/HTML/ListOfAvailableImages.cpp
  Userland/Libraries/LibWeb/HTML/ListOfAvailableImages.h
  Userland/Libraries/LibWeb/HTML/SharedImageRequest.cpp
  Userland/Libraries/LibWeb/HTML/SharedImageRequest.h
  Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
  Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.h
Labels: 👀 pr-needs-review

#22273 LibJS: Only consider VM-accessible execution contexts as strong roots
  Userland/Libraries/LibJS/Heap/Heap.cpp
  Userland/Libraries/LibJS/Heap/Heap.h
  Userland/Libraries/LibJS/Runtime/AsyncFunctionDriverWrapper.cpp
  Userland/Libraries/LibJS/Runtime/AsyncGenerator.cpp
  Userland/Libraries/LibJS/Runtime/ExecutionContext.cpp
  Userland/Libraries/LibJS/Runtime/GeneratorObject.cpp
  Userland/Libraries/LibJS/Runtime/VM.cpp
  Userland/Libraries/LibJS/SourceTextModule.cpp
  Userland/Libraries/LibWeb/HTML/Scripting/Environments.cpp
Labels: 👀 pr-needs-review

#22209 LibGfx/ILBMLoader: Add support for PC Deluxe Paint files
  Base/res/apps/ImageViewer.af
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/ilbm/serenity.lbm
  Userland/Libraries/LibCore/MimeData.cpp
  Userland/Libraries/LibGfx/Bitmap.h
  Userland/Libraries/LibGfx/ImageFormats/ILBMLoader.cpp
Labels: ✅ pr-community-approved

#22275 LibWeb: Fix crashing in compute_font_for_style_values on SerenityOS
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Labels: 👀 pr-needs-review

#22277 Ladybird/Qt: Listen to DPI changes and update WebContentView accordingly
  Ladybird/Qt/BrowserWindow.cpp
  Ladybird/Qt/BrowserWindow.h
  Ladybird/Qt/InspectorWidget.cpp
  Ladybird/Qt/InspectorWidget.h
  Ladybird/Qt/WebContentView.cpp
  Ladybird/Qt/WebContentView.h
Labels: 👀 pr-needs-review

#22272 LibGUI: Fix debug line causing crash when drag event has no mime data
  Userland/Libraries/LibGUI/AbstractView.cpp
Labels: 👀 pr-needs-review

#22280 LibCore: Don't leak proto-Resources when loading non-existent paths
  Userland/Libraries/LibCore/ResourceImplementation.cpp
Labels: 👀 pr-needs-review

#22282 Userland: Don't leak objects when constructor arguments throw
  Userland/Libraries/LibAudio/Loader.cpp
  Userland/Libraries/LibChess/UCICommand.cpp
  Userland/Libraries/LibGUI/InputBox.cpp
  Userland/Shell/Shell.cpp
Labels: 👀 pr-needs-review

#22286 LibWeb/Painting: Remove command to paint progress bar
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.cpp
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.h
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.h
  Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
  Userland/Libraries/LibWeb/Painting/RecordingPainter.h
Labels: 👀 pr-needs-review

#22284 LibWeb: Implement getBoundingClientRect() for inline paintables
  Tests/LibWeb/Text/expected/get-bounding-client-rect.txt
  Tests/LibWeb/Text/input/get-bounding-client-rect.html
  Userland/Libraries/LibWeb/DOM/Element.cpp
  Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
  Userland/Libraries/LibWeb/Painting/InlinePaintable.h
Labels: 👀 pr-needs-review

#20467 Meta: Replace run.sh by run.py (and accidentally fix many run modes)
  CMakeLists.txt
  Meta/run.py
  Meta/run.sh
Labels: 👀 pr-needs-review

#22292 RequestServer: Avoid race condition between cached request end/start
  Userland/Services/RequestServer/ConnectionCache.cpp
  Userland/Services/RequestServer/ConnectionCache.h
Labels: 👀 pr-needs-review

#22190 LibLine: Remove duplicate members in `CompletionSuggestion`
  Userland/Libraries/LibCodeComprehension/Shell/ShellComprehensionEngine.cpp
  Userland/Libraries/LibLine/Editor.cpp
  Userland/Libraries/LibLine/SuggestionManager.cpp
  Userland/Libraries/LibLine/SuggestionManager.h
  Userland/Libraries/LibLine/XtermSuggestionDisplay.cpp
  Userland/Shell/AST.cpp
  Userland/Shell/Shell.cpp
Labels: 👀 pr-needs-review

#22283 LibWeb: Refactor int types in WebContentServer to DevicePixels
  Ladybird/AppKit/UI/LadybirdWebView.mm
  Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
  Ladybird/AppKit/UI/LadybirdWebViewBridge.h
  Ladybird/Qt/BrowserWindow.cpp
  Ladybird/Qt/WebContentView.cpp
  Ladybird/Qt/WebContentView.h
  Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
  Userland/Libraries/LibWeb/PixelUnits.cpp
  Userland/Libraries/LibWeb/PixelUnits.h
  Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
  Userland/Libraries/LibWebView/OutOfProcessWebView.h
  Userland/Libraries/LibWebView/ViewImplementation.cpp
  Userland/Libraries/LibWebView/ViewImplementation.h
  Userland/Services/WebContent/ConnectionFromClient.cpp
  Userland/Services/WebContent/ConnectionFromClient.h
  Userland/Services/WebContent/PageClient.h
  Userland/Services/WebContent/WebContentServer.ipc
  Userland/Utilities/headless-browser.cpp
Labels: 👀 pr-needs-review

#22300 Kernel: Reject loading ELF files with no loadable segments
  Kernel/Syscalls/execve.cpp
Labels: 👀 pr-needs-review

#22285 LibWeb: History pushState/replaceState race crash
  Tests/LibWeb/Text/expected/navigation/history-replace-push-state-race.txt
  Tests/LibWeb/Text/input/navigation/history-replace-push-state-race.html
  Userland/Libraries/LibWeb/HTML/Navigable.cpp
  Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
Labels: 👀 pr-needs-review

#22301 LibWeb: Add support for the meta key modifier
  Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.cpp
  Userland/Libraries/LibWeb/UIEvents/MouseEvent.cpp
Labels: 👀 pr-needs-review

#22302 LibWeb: Refactor WebContentServer mouse input message to DevicePixel
  Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
  Ladybird/AppKit/UI/LadybirdWebViewBridge.h
  Ladybird/Qt/WebContentView.cpp
  Ladybird/Qt/WebContentView.h
  Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
  Userland/Libraries/LibWeb/Page/Page.cpp
  Userland/Libraries/LibWeb/Page/Page.h
  Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
  Userland/Services/WebContent/ConnectionFromClient.cpp
  Userland/Services/WebContent/ConnectionFromClient.h
  Userland/Services/WebContent/WebContentServer.ipc
Labels: 👀 pr-needs-review

#22308 LibPDF: Tolerate 0-sized Subrs in PS1 font subprograms
  Userland/Libraries/LibPDF/Fonts/PS1FontProgram.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#22314 Ladybird/Qt: Apply to_content_position after scaling event coordinates
  Ladybird/Qt/WebContentView.cpp
Labels: 👀 pr-needs-review

#22288 Ladybird/Qt: Dogfood RequestServer and SQLServer by default
  Ladybird/Qt/main.cpp
Labels: 👀 pr-needs-review

#22315 LibJS: Introduce "dictionary" mode for object shapes
  Userland/Libraries/LibJS/Runtime/Object.cpp
  Userland/Libraries/LibJS/Runtime/Shape.cpp
  Userland/Libraries/LibJS/Runtime/Shape.h
  Userland/Libraries/LibJS/Tests/builtins/Object/Object.freeze.js
Labels: 👀 pr-needs-review

#22322 LibAccelGfx: Add missing `bind_target_canvas()` in `Painter::clear()`
  Userland/Libraries/LibAccelGfx/Painter.cpp
Labels: 👀 pr-needs-review

#22321 LibWeb: Make private `RecordingPainter::state()`
  Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.cpp
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
  Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
  Userland/Libraries/LibWeb/Painting/RecordingPainter.h
  Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp
Labels: 👀 pr-needs-review

#22329 Kernel/riscv64: Specify correct alignment for `FPUState` struct
  Kernel/Arch/riscv64/FPUState.h
Labels: 👀 pr-needs-review

#22330 LibJS: Don't crash in CyclicModule::evaluate() when this == m_cycle_root
  Userland/Libraries/LibJS/CyclicModule.cpp
Labels: 👀 pr-needs-review

#22331 LibWeb: Fix division by zero in auto-fit/fill track calculation in GFC
  Tests/LibWeb/Layout/expected/grid/auto-fit-empty-container.txt
  Tests/LibWeb/Layout/input/grid/auto-fit-empty-container.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#22332 LibWeb: Do not crash when svg mask calculation failed
  Tests/LibWeb/Layout/expected/svg/objectBoundingBox-mask.txt
  Tests/LibWeb/Layout/input/svg/objectBoundingBox-mask.html
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Labels: 👀 pr-needs-review

#22333 LibWeb: Queue a task to proceed after module map entry finishes fetching
  Userland/Libraries/LibWeb/HTML/Scripting/Fetching.cpp
  Userland/Libraries/LibWeb/HTML/Scripting/ModuleMap.cpp
  Userland/Libraries/LibWeb/HTML/Scripting/ModuleMap.h
Labels: 👀 pr-needs-review

#22298 LibLine: Use grapheme clusters for cursor management / tiny boog fix
  Userland/Libraries/LibLine/CMakeLists.txt
  Userland/Libraries/LibLine/Editor.cpp
  Userland/Libraries/LibLine/Editor.h
  Userland/Libraries/LibLine/InternalFunctions.cpp
  Userland/Libraries/LibLine/StringMetrics.h
Labels: 👀 pr-needs-review

#22341 LibAccelGfx: Fix stack use after scope in GlyphAtlas::update()
  Userland/Libraries/LibAccelGfx/GlyphAtlas.cpp
Labels: 👀 pr-needs-review

#22326 AK/StringUtils: Ensure needle positions don't overlap in `replace`
  AK/StringUtils.cpp
  Tests/AK/TestStringUtils.cpp
Labels: 👀 pr-needs-review

#22307 LibWeb: Move use pseudo element styles from TreeBuilder to StyleComputer
  Tests/LibWeb/Layout/expected/element-use-pseudo-element.txt
  Tests/LibWeb/Layout/input/element-use-pseudo-element.html
  Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp
  Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.h
  Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
  Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.h
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
  Userland/Libraries/LibWeb/HTML/HTMLMeterElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLProgressElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp
  Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Labels: 👀 pr-needs-review

#22348 LibGfx/TIFF: Parse more common tags
  Userland/Libraries/LibGfx/TIFFGenerator.py
Labels: 👀 pr-needs-review

#22352 LibJS+LibWeb: Add JS::Value constructor for ``JS::Handle<T>``
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
  Userland/Libraries/LibJS/Runtime/Value.h
  Userland/Libraries/LibWeb/HTML/MessageEvent.cpp
  Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
  Userland/Libraries/LibWeb/Streams/ReadableStream.cpp
  Userland/Libraries/LibWeb/Streams/TransformStream.cpp
  Userland/Libraries/LibWeb/Streams/WritableStream.cpp
  Userland/Libraries/LibWeb/WebIDL/DOMException.h
Labels: 👀 pr-needs-review

#22342 LibGfx/TIFF: Add support for images with CCITT3 1D compression
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/tiff/ccitt3_1d.tiff
  Userland/Libraries/LibGfx/CMakeLists.txt
  Userland/Libraries/LibGfx/ImageFormats/CCITTDecoder.cpp
  Userland/Libraries/LibGfx/ImageFormats/CCITTDecoder.h
  Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Labels: ✅ pr-community-approved

#22359 LibWeb: Resolve box shadow data for paintable boxes during layout
  Userland/Libraries/LibWeb/Layout/LayoutState.cpp
  Userland/Libraries/LibWeb/Layout/LayoutState.h
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
  Userland/Libraries/LibWeb/Painting/PaintableBox.h
Labels: 👀 pr-needs-review

#22339 Meta: Assume virgl support to not be present if ldconfig isn't found
  Meta/run.py
Labels: 👀 pr-needs-review

#22248 LibGUI: Display commands on CommandPalette's start up
  Userland/Libraries/LibGUI/FilteringProxyModel.cpp
Labels: ✅ pr-community-approved

#22367 LibWeb: Scroll to the top after navigating to a new document
  Userland/Libraries/LibWeb/DOM/Document.cpp
Labels: 👀 pr-needs-review

#22368 LibPDF: Draw inline images
  Userland/Libraries/LibPDF/Document.h
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#21792 CMake: Query Python interpreter with `find_package`
  Meta/CMake/code_generators.cmake
Labels: stale, 👀 pr-needs-review

#22287 LibGfx/ILBMLoader: Add support for 24bit files
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/ilbm/serenity-24bit.iff
  Userland/Libraries/LibGfx/ImageFormats/ILBMLoader.cpp
Labels: ✅ pr-community-approved

#22371 headless-browser: Await `on_load_finish()` while running Text tests
  Userland/Utilities/headless-browser.cpp
Labels: 👀 pr-needs-review

#22238 LibWeb: Add basic input range rendering
  Base/res/html/misc/input-range.html
  Base/res/html/misc/input.html
  Userland/Libraries/LibWeb/CSS/Default.css
  Userland/Libraries/LibWeb/CSS/Selector.cpp
  Userland/Libraries/LibWeb/CSS/Selector.h
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
Labels: 👀 pr-needs-review

#22377 AK: Use fallback builtins for overflow checks in AK::Checked
  AK/Checked.h
Labels: 👀 pr-needs-review

#22364 LibPDF: Revert pattern support
  Userland/Libraries/LibPDF/ColorSpace.cpp
  Userland/Libraries/LibPDF/ColorSpace.h
  Userland/Libraries/LibPDF/CommonNames.h
  Userland/Libraries/LibPDF/Renderer.cpp
  Userland/Libraries/LibPDF/Renderer.h
Labels: 👀 pr-needs-review

#22379 Tests/LibWeb: Add ref-tests for "overflow: hidden"
  Tests/LibWeb/Ref/overflow-hidden-2.html
  Tests/LibWeb/Ref/overflow-hidden.html
  Tests/LibWeb/Ref/reference/overflow-hidden-2-ref.html
  Tests/LibWeb/Ref/reference/overflow-hidden-ref.html
Labels: 👀 pr-needs-review

#22387 LibWeb: Add a test for setting and getting Text data
  Tests/LibWeb/Text/expected/DOM/Text-set-get-data.txt
  Tests/LibWeb/Text/input/DOM/Text-set-get-data.html
Labels: 👀 pr-needs-review

#22384 Kernel: Mark cloned volatile purgeable AnonymousVMOjects as purged
  Kernel/Memory/AnonymousVMObject.cpp
Labels: 👀 pr-needs-review

#22388 AK: Completely disable rich debug formats on Windows
  AK/Format.cpp
Labels: 👀 pr-needs-review

#22383 LibLine: Avoid returning reference to cached suggestion
  Userland/Libraries/LibLine/SuggestionManager.cpp
Labels: 👀 pr-needs-review

#22389 LibWeb: Stop shadowing location_url
  Userland/Libraries/LibWeb/HTML/Navigable.cpp
Labels: 👀 pr-needs-review

#22385 LibWebView+WebContent: Drive repainting from WebContent process
  Ladybird/Android/src/main/cpp/WebViewImplementationNative.cpp
  Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
  Ladybird/Qt/WebContentView.cpp
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
  Userland/Libraries/LibWeb/Page/Page.cpp
  Userland/Libraries/LibWeb/Page/Page.h
  Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
  Userland/Libraries/LibWebView/ViewImplementation.cpp
  Userland/Libraries/LibWebView/ViewImplementation.h
  Userland/Libraries/LibWebView/WebContentClient.cpp
  Userland/Libraries/LibWebView/WebContentClient.h
  Userland/Services/WebContent/ConnectionFromClient.cpp
  Userland/Services/WebContent/ConnectionFromClient.h
  Userland/Services/WebContent/PageClient.cpp
  Userland/Services/WebContent/PageClient.h
  Userland/Services/WebContent/WebContentClient.ipc
  Userland/Services/WebContent/WebContentServer.ipc
Labels: 👀 pr-needs-review

#22399 LibPDF: Fix typo in a variable name
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: 👀 pr-needs-review

#22405 LibGfx: Do not use double negation in TIFFGenerator.py
  Userland/Libraries/LibGfx/TIFFGenerator.py
Labels: ✅ pr-community-approved

#22404 LibTimeZone: Update to TZDB version 2023d
  Meta/CMake/time_zone_data.cmake
  Meta/gn/secondary/Userland/Libraries/LibTimeZone/BUILD.gn
Labels: 👀 pr-needs-review

#22402 LibWeb: Use UTF-16 code unit offsets and lengths in CharacterData
  Tests/LibWeb/Text/expected/DOM/Text-methods.txt
  Tests/LibWeb/Text/input/DOM/Text-methods.html
  Userland/Libraries/LibWeb/DOM/CharacterData.cpp
  Userland/Libraries/LibWeb/DOM/CharacterData.h
  Userland/Libraries/LibWeb/DOM/CharacterData.idl
  Userland/Libraries/LibWeb/DOM/Node.cpp
Labels: 👀 pr-needs-review

#22397 LibGfx/TIFF: Add support for RGBPalette images
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/tiff/rgb_palette_alpha.tiff
  Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
  Userland/Libraries/LibGfx/TIFFGenerator.py
Labels: ✅ pr-community-approved

#22409 LibWeb: Ignore "display: contents" boxes while inserting inline nodes
  Tests/LibWeb/Layout/expected/display-contents-with-in-children.txt
  Tests/LibWeb/Layout/input/display-contents-with-in-children.html
  Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Labels: 👀 pr-needs-review

#22408 LibGfx/TIFF: Ensure baseline tags presence before decoding
  Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
  Userland/Libraries/LibGfx/TIFFGenerator.py
Labels: 👀 pr-needs-review

#22412 LibJS: Update spec comments in Array.fromAsync
  Userland/Libraries/LibJS/Runtime/ArrayConstructor.cpp
Labels: 👀 pr-needs-review

#22414 LibWeb/CSS: Fix stack use after scope in matches_attribute()
  Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
Labels: 👀 pr-needs-review

#22413 LibGfx: Clip edges above or below the visible area in the rasterizer
  Tests/LibWeb/Ref/reference/images/border-radius-ref.png
  Tests/LibWeb/Ref/reference/images/canvas-fillstyle-rgb.png
  Tests/LibWeb/Ref/reference/images/canvas-path-rect-ref.png
  Tests/LibWeb/Ref/reference/images/css-background-position-ref.png
  Tests/LibWeb/Ref/reference/images/css-background-repeat-ref.png
  Tests/LibWeb/Ref/reference/images/css-backgrounds-ref.png
  Tests/LibWeb/Ref/reference/images/css-gradients-ref.png
  Tests/LibWeb/Ref/reference/images/inline-node-ref.png
  Tests/LibWeb/Ref/reference/images/input-placeholder-ref.png
  Tests/LibWeb/Ref/reference/images/meter-ref.png
  Tests/LibWeb/Ref/reference/images/object-fit-position.png
  Tests/LibWeb/Ref/reference/images/outer-box-shadow-ref.png
  Tests/LibWeb/Ref/reference/images/svg-gradient-spreadMethod-ref.png
  Tests/LibWeb/Ref/reference/images/svg-radialGradient-ref.png
  Tests/LibWeb/Ref/reference/images/svg-textPath-ref.png
  Tests/LibWeb/Ref/reference/images/text-shadow-ref.png
  Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.cpp
  Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.h
Labels: 👀 pr-needs-review

#22407 CI: Lower the timeout for Lagom tests to 1 hour
  Meta/Azure/Lagom.yml
Labels: 👀 pr-needs-review

#22419 LibLine: Use the correct loop conditions for erase_character_forwards()
  Userland/Libraries/LibLine/InternalFunctions.cpp
Labels: 👀 pr-needs-review

#22421 LibWeb: Limit scroll position by overflow area in Window::scroll()
  Tests/LibWeb/Text/expected/window-scrollTo.txt
  Tests/LibWeb/Text/input/window-scrollTo.html
  Userland/Libraries/LibWeb/HTML/Window.cpp
Labels: 👀 pr-needs-review

#22372 LibWeb+WebWorker: Convert Workers to use MessagePorts for postMessage
  Base/res/html/misc/worker.js
  Tests/LibWeb/TestConfig.ini
  Tests/LibWeb/Text/expected/Worker/Worker-echo.txt
  Tests/LibWeb/Text/input/Worker/Worker-echo.html
  Tests/LibWeb/Text/input/Worker/worker.js
  Userland/Libraries/LibWeb/Forward.h
  Userland/Libraries/LibWeb/HTML/MessagePort.cpp
  Userland/Libraries/LibWeb/HTML/MessagePort.h
  Userland/Libraries/LibWeb/HTML/Worker.cpp
  Userland/Libraries/LibWeb/HTML/Worker.h
  Userland/Libraries/LibWeb/HTML/Worker.idl
  Userland/Libraries/LibWeb/HTML/WorkerAgent.cpp
  Userland/Libraries/LibWeb/HTML/WorkerAgent.h
  Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.cpp
  Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.h
  Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.idl
  Userland/Libraries/LibWeb/Worker/WebWorkerServer.ipc
  Userland/Services/WebWorker/ConnectionFromClient.cpp
  Userland/Services/WebWorker/ConnectionFromClient.h
  Userland/Services/WebWorker/DedicatedWorkerHost.cpp
  Userland/Services/WebWorker/DedicatedWorkerHost.h
Labels: 👀 pr-needs-review

#22433 LibWebView: Request repaint after replacing backing stores
  Userland/Libraries/LibWebView/ViewImplementation.cpp
Labels: 👀 pr-needs-review

#22436 WebContent: Remove spammy debug message from paint handler
  Userland/Services/WebContent/PageClient.cpp
Labels: 👀 pr-needs-review

#22434 LibWeb: Respect box-sizing in min-height calculation of grid container
  Tests/LibWeb/Layout/expected/grid/grid-container-min-height-border-box.txt
  Tests/LibWeb/Layout/input/grid/grid-container-min-height-border-box.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#22435 LibWeb: Apply min/max-widths to block container during intrinsic layout
  Tests/LibWeb/Layout/expected/block-and-inline/max-width-wrapped-in-max-content.txt
  Tests/LibWeb/Layout/expected/table/cell-with-max-width.txt
  Tests/LibWeb/Layout/input/block-and-inline/max-width-wrapped-in-max-content.html
  Tests/LibWeb/Layout/input/table/cell-with-max-width.html
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Labels: 👀 pr-needs-review

#22439 LibWeb: Parse more CSS properties using TokenStreams
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/CSS/Parser/Parser.h
Labels: 👀 pr-needs-review

#22428 LibGfx+LibWeb: Move Gfx::ScaledFont caching from LibWeb into LibGfx
  Meta/gn/secondary/Userland/Libraries/LibWeb/BUILD.gn
  Userland/Libraries/LibGfx/CMakeLists.txt
  Userland/Libraries/LibGfx/Font/ScaledFont.cpp
  Userland/Libraries/LibGfx/Font/Typeface.cpp
  Userland/Libraries/LibGfx/Font/VectorFont.cpp
  Userland/Libraries/LibGfx/Font/VectorFont.h
  Userland/Libraries/LibGfx/Forward.h
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
  Userland/Libraries/LibWeb/CSS/StyleComputer.h
  Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
  Userland/Libraries/LibWeb/FontCache.cpp
  Userland/Libraries/LibWeb/FontCache.h
  Userland/Libraries/LibWeb/Layout/Node.h
  Userland/Libraries/LibWeb/Painting/ButtonPaintable.cpp
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Labels: 👀 pr-needs-review

#22431 Calendar: Add a link to the Manual in Help Menu
  Userland/Applications/Calendar/CMakeLists.txt
  Userland/Applications/Calendar/CalendarWidget.cpp
  Userland/Applications/Calendar/main.cpp
Labels: 👀 pr-needs-review

#22441 LibWeb: Redo "tracks maximize" if initial run is over max-size in GFC
  Tests/LibWeb/Layout/expected/grid/max-width-grid-container-wrapper-in-max-content.txt
  Tests/LibWeb/Layout/input/grid/max-width-grid-container-wrapper-in-max-content.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#22440 LibWeb: Parse remaining grid properties using TokenStream
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/CSS/Parser/Parser.h
Labels: 👀 pr-needs-review

#22444 Kernel: A couple of TCP window-size support improvements
  Kernel/Net/IPv4Socket.cpp
  Kernel/Net/IPv4Socket.h
  Kernel/Net/NetworkTask.cpp
  Kernel/Net/TCP.h
  Kernel/Net/TCPSocket.cpp
  Kernel/Net/TCPSocket.h
Labels: 👀 pr-needs-review

#22445 LibWeb: Ensure DocumentObserver `document_completely_loaded()` is called
  Tests/LibWeb/Ref/reference/svg-use-defined-earlier.html
  Tests/LibWeb/Ref/svg-use-defined-later.html
  Userland/Libraries/LibWeb/DOM/Document.cpp
Labels: 👀 pr-needs-review

#22453 LibWeb: Don't pass StringView to RecordingPainter, to avoid copy
  Userland/Libraries/LibWeb/Painting/ImagePaintable.cpp
  Userland/Libraries/LibWeb/Painting/MarkerPaintable.cpp
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
  Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
  Userland/Libraries/LibWeb/Painting/RecordingPainter.h
Labels: 👀 pr-needs-review

#22454 LibGfx/JPEG: Add spec comment to read_start_of_frame()
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Labels: 👀 pr-needs-review

#22456 Ports: Update checksum for stpuzzles
  Ports/stpuzzles/package.sh
Labels: 👀 pr-needs-review

#22458 LibWeb: Skip erroneous blit/sample corner commands in RecordingPainter
  Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
Labels: 👀 pr-needs-review

#22462 LibJS: Implement missing conditional when creating a TypedArray subarray
  Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
  Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.subarray.js
Labels: 👀 pr-needs-review

#22460 Meta: Add support for QEMU 8.2 audio
  Meta/run.py
Labels: 👀 pr-needs-review

#22480 FileManager: Conditionally display the "ICC profile:" line
  Userland/Applications/FileManager/PropertiesWindow.cpp
  Userland/Applications/FileManager/PropertiesWindowImageTab.gml
Labels: 👀 pr-needs-review

#22479 Tests/LibGfx: Add YCCK jpeg test files
  Tests/LibGfx/test-inputs/jpg/ycck-1111.jpg
  Tests/LibGfx/test-inputs/jpg/ycck-2111.jpg
  Tests/LibGfx/test-inputs/jpg/ycck-2112.jpg
Labels: ✅ pr-community-approved

#22484 LibWeb: Do not use Optional for aa_translation in RecordingPainter
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.cpp
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.h
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.h
  Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
  Userland/Libraries/LibWeb/Painting/RecordingPainter.h
Labels: 👀 pr-needs-review

#22423 Ports: Bump gawk to 5.3.0
  Ports/AvailablePorts.md
  Ports/gawk/package.sh
Labels: 👀 pr-needs-review

#22489 Tests: Don't include LibWebView test if LibWeb is disabled
  Meta/Lagom/CMakeLists.txt
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#22488 LibGfx/JPEG: Make ycck jpegs with just cc subsampled decode correctly
  Tests/LibGfx/TestImageDecoder.cpp
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Labels: 👀 pr-needs-review

#22490 Ladybird/Qt: Ensure the Inspector widget is deleted before the WebView
  Ladybird/Qt/Tab.cpp
Labels: 👀 pr-needs-review

#22491 Kernel: Enable MULTIBOOT_VIDEO_MODE by default
  Kernel/Prekernel/multiboot.S
Labels: 👀 pr-needs-review

#22486 Kernel/riscv64: Return correct range in `kernel_virtual_range` on RISC-V
  Kernel/Memory/MemoryManager.cpp
Labels: 👀 pr-needs-review
