Repository SerenityOS/serenity, pull requests merged in 2023-06, with the labels that each got.

#19189 LibGfx: Improve glyph rendering speed for vector fonts
  Userland/Libraries/LibGfx/Painter.cpp
Labels: 👀 pr-needs-review

#19187 AK: Remove conditional `noexcept` from `Complex`
  AK/Complex.h
Labels: 👀 pr-needs-review

#19185 LibGUI: Add support for jumping to a line and column in TextEditor
  Userland/DevTools/GMLPlayground/MainWidget.cpp
  Userland/Libraries/LibGUI/TextEditor.cpp
  Userland/Libraries/LibGUI/TextEditor.h
Labels: ✅ pr-community-approved

#19192 LibWeb: Invalidate layout tree in textContent setter
  Userland/Libraries/LibWeb/DOM/Node.cpp
Labels: 👀 pr-needs-review

#19134 LibWeb: Add support for parsing place-content shorthand CSS property
  Tests/LibWeb/Layout/expected/place-content-shorthand-property.txt
  Tests/LibWeb/Layout/input/place-content-shorthand-property.html
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/CSS/Parser/Parser.h
  Userland/Libraries/LibWeb/CSS/Properties.json
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
  Userland/Libraries/LibWeb/CSS/StyleValue.cpp
  Userland/Libraries/LibWeb/CSS/StyleValue.h
  Userland/Libraries/LibWeb/CSS/StyleValues/PlaceContentStyleValue.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/PlaceContentStyleValue.h
  Userland/Libraries/LibWeb/Forward.h
Labels: 👀 pr-needs-review

#19193 LibWeb: Support `line-height: calc(...)` values that resolve to number
  Tests/LibWeb/Layout/expected/line-height-calc-number.txt
  Tests/LibWeb/Layout/input/line-height-calc-number.html
  Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
Labels: 👀 pr-needs-review

#19195 LibGfx: Multiply alpha channels for vector fonts, when necessary
  Userland/Libraries/LibGfx/Painter.cpp
Labels: 👀 pr-needs-review

#19194 LibWebView: Unbreak content-scales-to-viewport mode for Presenter
  Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Labels: 👀 pr-needs-review

#19197 LibGfx: Optimize `Painter::blit_filtered()`
  Userland/Libraries/LibGfx/Painter.cpp
Labels: 👀 pr-needs-review

#19199 LibGfx: Remove SSE version of `Color::blend()`
  Userland/Libraries/LibGfx/Color.h
Labels: 👀 pr-needs-review

#19205 LibWeb: Round lengths to 3 decimals after resolving from percentage
  Tests/LibWeb/Layout/expected/acid1.txt
  Tests/LibWeb/Layout/expected/grid/unresolvable-percentage-track.txt
  Tests/LibWeb/Layout/expected/tolerate-css-percentage-overshoot.txt
  Tests/LibWeb/Layout/input/tolerate-css-percentage-overshoot.html
  Userland/Libraries/LibWeb/CSS/Length.cpp
Labels: 👀 pr-needs-review

#19210 WindowServer: Don't crash when trying to set invalid effects
  Userland/Services/WindowServer/ConnectionFromClient.cpp
  Userland/Services/WindowServer/SystemEffects.h
Labels: 👀 pr-needs-review

#19211 LibCrypto: Don't return reference to stack frame in PBKDF
  Userland/Libraries/LibCrypto/Hash/PBKDF2.h
Labels: 👀 pr-needs-review

#19209 LibC+Tests: Reduce fuzz iteration in TestMemalign to speed up CI
  Tests/LibC/TestMemalign.cpp
Labels: ci-flakiness, 👀 pr-needs-review

#19214 LibWeb: Avoid text-aligning content that is too long for its line box
  Tests/LibWeb/Layout/expected/text-align-overflow.txt
  Tests/LibWeb/Layout/input/text-align-overflow.html
  Userland/Libraries/LibWeb/Layout/LineBuilder.cpp
Labels: 👀 pr-needs-review

#19212 LibWeb: Remove per path clipping for SVGGeometryPaintable
  Userland/Libraries/LibWeb/Painting/SVGGeometryPaintable.cpp
Labels: 👀 pr-needs-review

#19158 LibWeb: Implement CSS comparison functions
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/CSS/Parser/Parser.h
  Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
Labels: 👀 pr-needs-review

#19206 Kernel: Remove unused Platform.h include in linker script
  Kernel/Arch/x86_64/linker.ld
Labels: 👀 pr-needs-review

#19221 LibWeb: Make StackingContext sorting a lot faster
  Userland/Libraries/LibWeb/Layout/Viewport.cpp
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
  Userland/Libraries/LibWeb/Painting/StackingContext.h
Labels: 👀 pr-needs-review

#19222 LibWeb: Support flex items with calc() main size containing percentages
  Tests/LibWeb/Layout/expected/flex/flex-item-with-calc-main-size-and-layout-dependent-containing-block-size.txt
  Tests/LibWeb/Layout/input/flex/flex-item-with-calc-main-size-and-layout-dependent-containing-block-size.html
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Labels: 👀 pr-needs-review

#19213 Kernel+Userland: Ensure proper unveil permissions when deleting files/directories
  Kernel/FileSystem/VirtualFileSystem.cpp
  Userland/Utilities/userdel.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#19225 LibWeb: Fix crashing when grid track size is calc() with percentage
  Tests/LibWeb/Layout/expected/grid/track-size-calc-with-percentage.txt
  Tests/LibWeb/Layout/input/grid/track-size-calc-with-percentage.html
  Userland/Libraries/LibWeb/CSS/GridTrackSize.cpp
Labels: 👀 pr-needs-review

#19226 LibGfx/JPEG: Use `Error` to propagate errors
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Labels: 👀 pr-needs-review

#19235 LibLine: Ignore ENOENT errors when loading old history
  Userland/Libraries/LibLine/Editor.cpp
Labels: 👀 pr-needs-review

#19171 LibWeb: Resolve the `transition-delay` property
  Userland/Libraries/LibWeb/CSS/ComputedValues.h
  Userland/Libraries/LibWeb/CSS/Properties.json
  Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
  Userland/Libraries/LibWeb/Layout/Node.cpp
Labels: 👀 pr-needs-review

#19231 LibWeb: Detect and reject math functions with no resolved type
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#19240 LibWeb: Don't let it crash when document.write a script with src attr
  Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Labels: 👀 pr-needs-review

#19238 Ladybird: Assume file:// URL when URL starts with '/'
  Ladybird/Tab.cpp
Labels: 👀 pr-needs-review

#18985 SystemServer: Don't exit new service if dropping privileges failed when running as non-root user
  Userland/Services/SystemServer/Service.cpp
  Userland/Services/SystemServer/Service.h
Labels: 👀 pr-needs-review

#19243 LibWeb: Fix parsing `font: 0/0 a;`
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#19253 Ports: Update the Zig port's Serenity type definitions
  Ports/zig/patches/0012-Implement-SerenityOS-support-in-std.patch
Labels: 👀 pr-needs-review

#19252 Toolchain+Ladybird: Declare dependencies in correct nix file
  Ladybird/ladybird.nix
  Toolchain/serenity.nix
Labels: 👀 pr-needs-review

#19254 LibWeb: Account for negative margins when calculating float intrusion
  Tests/LibWeb/Layout/expected/block-and-inline/block-with-negative-margin-and-no-intruding-floats.txt
  Tests/LibWeb/Layout/input/block-and-inline/block-with-negative-margin-and-no-intruding-floats.html
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Labels: 👀 pr-needs-review

#18781 TextEditor: Prevent autoscroll looping over
  Userland/Libraries/LibGUI/TextEditor.cpp
Labels: 👀 pr-needs-review

#19266 Tests/LibWeb: Add some text tests for 'parsing a legacy color value'
  Tests/LibWeb/Text/expected/css/legacy-color-value.txt
  Tests/LibWeb/Text/input/css/legacy-color-value.html
Labels: 👀 pr-needs-review

#19265 LibWeb: Ensure that contentType in Blob::slice is basic latin
  Userland/Libraries/LibWeb/FileAPI/Blob.cpp
Labels: 👀 pr-needs-review

#19263 Base: Add .mkv file association to Video Player
  Base/res/apps/VideoPlayer.af
Labels: 👀 pr-needs-review

#19246 Shell: Add a "." builtin that aliases to "source"
  Userland/Shell/Builtin.cpp
  Userland/Shell/Shell.h
Labels: 👀 pr-needs-review

#19267 LibWeb: Take box-sizing into account when sizing replaced elements
  Tests/LibWeb/Layout/expected/img-with-box-sizing-border-box-and-padding.txt
  Tests/LibWeb/Layout/input/img-with-box-sizing-border-box-and-padding.html
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Labels: 👀 pr-needs-review

#19008 LibPartition: Migrate from DeprecatedFile to File
  Kernel/CMakeLists.txt
  Userland/Applications/PartitionEditor/PartitionModel.cpp
  Userland/Applications/PartitionEditor/PartitionModel.h
  Userland/Libraries/LibPartition/CMakeLists.txt
  Userland/Libraries/LibPartition/EBRPartitionTable.cpp
  Userland/Libraries/LibPartition/EBRPartitionTable.h
  Userland/Libraries/LibPartition/GUIDPartitionTable.cpp
  Userland/Libraries/LibPartition/GUIDPartitionTable.h
  Userland/Libraries/LibPartition/MBRPartitionTable.cpp
  Userland/Libraries/LibPartition/MBRPartitionTable.h
  Userland/Libraries/LibPartition/PartitionTable.cpp
  Userland/Libraries/LibPartition/PartitionTable.h
  Userland/Libraries/LibPartition/PartitionableDevice.cpp
  Userland/Libraries/LibPartition/PartitionableDevice.h
Labels: 👀 pr-needs-review

#19258 js: Add --disable-debug-output option
  Userland/Utilities/js.cpp
Labels: 👀 pr-needs-review

#19202 Browser: Store default config values in a single place
  Userland/Applications/Browser/BrowserWindow.cpp
  Userland/Applications/Browser/DownloadWidget.cpp
  Userland/Applications/Browser/Tab.cpp
  Userland/Applications/Browser/main.cpp
  Userland/Applications/BrowserSettings/AutoplaySettingsWidget.cpp
  Userland/Applications/BrowserSettings/BrowserSettingsWidget.cpp
  Userland/Applications/BrowserSettings/ContentFilterSettingsWidget.cpp
  Userland/Applications/BrowserSettings/Defaults.h
Labels: ✅ pr-community-approved

#19251 LibC: Do not crash if value passed to `putenv` was freed
  Tests/LibC/CMakeLists.txt
  Tests/LibC/TestEnvironment.cpp
  Userland/Libraries/LibC/stdlib.cpp
Labels: 👀 pr-needs-review

#19261 LibWeb: Allow loading of SVGs in ImageResource
  Userland/Libraries/LibWeb/Loader/ImageResource.cpp
  Userland/Libraries/LibWeb/Loader/ImageResource.h
  Userland/Libraries/LibWeb/Loader/Resource.h
Labels: 👀 pr-needs-review

#19277 js: Add --test262-global option
  Userland/Utilities/js.cpp
Labels: 👀 pr-needs-review

#19278 Tests: Un-flake the recent `TestEnvironment` addition
  Tests/LibC/TestEnvironment.cpp
  Userland/Libraries/LibC/stdlib.cpp
Labels: 👀 pr-needs-review

#19276 Meta: Enable NVME by default
  Meta/run.sh
Labels: 👀 pr-needs-review

#19273 LibC: Add `lutimes(2)` and `futimes(2)` implementations
  Userland/Libraries/LibC/sys/time.h
  Userland/Libraries/LibC/time.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#19282 LibGfx: Fix partial loading of tall and interlaced PNG files
  Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#19289 Ports: Add editline 1.17.1
  Ports/AvailablePorts.md
  Ports/editline/package.sh
Labels: 👀 pr-needs-review

#19288 Ports: Add Brotli 1.0.9
  Ports/AvailablePorts.md
  Ports/brotli/package.sh
Labels: 👀 pr-needs-review

#19285 LibGfx/PortableFormat: Reject images with a maximum value of 0
  Userland/Libraries/LibGfx/ImageFormats/PortableImageLoaderCommon.h
Labels: 👀 pr-needs-review

#18900 LibGUI: Fix wrong cursor position after undoing `RemoveTextCommand`
  Userland/Libraries/LibGUI/TextDocument.cpp
  Userland/Libraries/LibGUI/TextDocument.h
  Userland/Libraries/LibGUI/TextEditor.cpp
Labels: 👀 pr-needs-review

#18966 SystemMonitor: Ignore unveil error about unexisting HackStudio binary
  Userland/Applications/SystemMonitor/main.cpp
Labels: 👀 pr-needs-review

#18839 dd: Small statistics improvements (show elapsed time and write speed, and print it also on interrupts)
  Userland/Utilities/dd.cpp
Labels: 👀 pr-needs-review

#18925 Base: Add Unicode arrows to Katica Italic 10
  Base/res/fonts/KaticaItalic10.font
Labels: 👀 pr-needs-review

#19010 mknod: Use ArgsParser and add option for specifying file permissions
  Userland/Utilities/mknod.cpp
Labels: 👀 pr-needs-review

#18974 LibCore: Fix logic deciding when to open files in non-blocking mode
  Userland/Libraries/LibCore/File.cpp
Labels: 👀 pr-needs-review

#19284 LibWeb: Make text-shadow inherited in CSS::ComputedValues
  Userland/Libraries/LibWeb/CSS/ComputedValues.h
Labels: 👀 pr-needs-review

#19294 WebP/Lossy+Alpha: Implement filtering_method for ALPH chunk
  Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
Labels: 👀 pr-needs-review

#19296 LibWeb: Add naive support for margin-{block,inline} and padding-{block,inline} properties
  Tests/LibWeb/Layout/expected/block-and-inline/margin-padding-block-inline.txt
  Tests/LibWeb/Layout/input/block-and-inline/margin-padding-block-inline.html
  Userland/Libraries/LibWeb/CSS/Properties.json
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Labels: 👀 pr-needs-review

#19299 LibWeb: Add support for grid items with negative column-start in GFC
  Tests/LibWeb/Layout/expected/grid/negative-grid-item-column-index.txt
  Tests/LibWeb/Layout/input/grid/negative-grid-item-column-index.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#19268 Ports: Update serenity-theming use latest commit cd1fd73
  Ports/AvailablePorts.md
  Ports/serenity-theming/package.sh
Labels: 👀 pr-needs-review

#19292 Ports: Add lowdown 1.0.2
  Ports/AvailablePorts.md
  Ports/lowdown/package.sh
  Ports/lowdown/patches/0001-Exclude-arpa-nameser.h-as-it-does-not-exist-on-Seren.patch
  Ports/lowdown/patches/0002-Don-t-use-getprogname.patch
  Ports/lowdown/patches/ReadMe.md
  Userland/Libraries/LibC/paths.h
Labels: 👀 pr-needs-review

#19300 LibWeb: Use none as initial value for grid-template-column/rows
  Tests/LibWeb/Layout/expected/grid/all-implicit-rows.txt
  Tests/LibWeb/Layout/input/grid/all-implicit-rows.html
  Userland/Libraries/LibWeb/CSS/ComputedValues.h
  Userland/Libraries/LibWeb/CSS/GridTrackSize.cpp
  Userland/Libraries/LibWeb/CSS/GridTrackSize.h
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/CSS/Properties.json
  Userland/Libraries/LibWeb/CSS/StyleValues/GridTrackSizeListStyleValue.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/GridTrackSizeListStyleValue.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#19306 LibWeb: Consider all spanned tracks while finding extra space in GFC
  Tests/LibWeb/Layout/expected/grid/distribute-extra-space-across-spanned-tracks.txt
  Tests/LibWeb/Layout/input/grid/distribute-extra-space-across-spanned-tracks.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#19307 LibCore: Ensure `exec()` keeps a reference to the executable path
  Userland/Libraries/LibCore/System.cpp
Labels: 👀 pr-needs-review

#19302 CI: Don't run known-failing tests on Aarch
  Base/home/anon/Tests/run-tests-and-shutdown.sh
Labels: 👀 pr-needs-review

#19315 LibEDID: Ignore duplicate PNP IDs
  Meta/Lagom/Tools/CodeGenerators/LibEDID/GeneratePnpIDs.cpp
Labels: 👀 pr-needs-review

#19311 Meta: Re-add boot drive to aarch64 run configuration
  Meta/run.sh
Labels: 👀 pr-needs-review

#17902 Meta+Lagom: Enable CMAKE_BUILD_WITH_INSTALL_RPATH
  .github/workflows/libjs-test262.yml
  .github/workflows/wasm.yml
  Ladybird/CMakeLists.txt
  Meta/Azure/Lagom.yml
  Meta/Lagom/CMakeLists.txt
  Meta/check-markdown.sh
  Meta/lint-ci.sh
  Meta/lint-gml-format.sh
  Meta/serenity.sh
  Tests/LibWeb/Layout/layout_test.sh
  Tests/LibWeb/Text/text_test.sh
  Userland/Utilities/markdown-check.cpp
Labels: 👀 pr-needs-review

#19333 LibWeb: Allow `auto` as `animation-duration` and make that the default
  Userland/Libraries/LibWeb/CSS/Properties.json
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
  Userland/Libraries/LibWeb/CSS/StyleComputer.h
Labels: 👀 pr-needs-review

#19314 Kernel: De-atomicize fields for promises in `Process`
  Kernel/Syscalls/execve.cpp
  Kernel/Syscalls/fork.cpp
  Kernel/Tasks/Process.h
Labels: 👀 pr-needs-review

#19327 LibWeb: Implement painting for svg text
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/Layout/SVGFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/SVGTextBox.cpp
  Userland/Libraries/LibWeb/Layout/SVGTextBox.h
  Userland/Libraries/LibWeb/Painting/SVGTextPaintable.cpp
  Userland/Libraries/LibWeb/Painting/SVGTextPaintable.h
  Userland/Libraries/LibWeb/SVG/AttributeNames.h
  Userland/Libraries/LibWeb/SVG/SVGTextContentElement.cpp
  Userland/Libraries/LibWeb/SVG/SVGTextContentElement.h
Labels: 👀 pr-needs-review

#19334 LibWeb: Remove outdated layout/text test scripts
  Tests/LibWeb/Layout/layout_test.sh
  Tests/LibWeb/Text/text_test.sh
Labels: 👀 pr-needs-review

#19318 LibFileSystemAccessClient: Don't crash when formatting error messages
  Userland/Libraries/LibFileSystemAccessClient/Client.cpp
Labels: 👀 pr-needs-review

#19337 LibWebView: Unbreak spawning WebContent process with valgrind
  Userland/Libraries/LibWebView/ViewImplementation.cpp
Labels: 👀 pr-needs-review

#19339 Ladybird: Add `Userland` to the list of include directories
  Ladybird/CMakeLists.txt
Labels: 👀 pr-needs-review

#19341 LibWeb: Use fill_path() to paint <video> play buttons
  Userland/Libraries/LibWeb/Painting/VideoPaintable.cpp
Labels: 👀 pr-needs-review

#19244 man: Specify full path for Shell
  Userland/Utilities/man.cpp
Labels: 👀 pr-needs-review

#19098 LibJS: Parse slashes after reserved identifiers correctly
  Userland/Libraries/LibJS/Lexer.cpp
  Userland/Libraries/LibJS/Parser.cpp
  Userland/Libraries/LibJS/Parser.h
  Userland/Libraries/LibJS/Tests/modules/basic-modules.js
  Userland/Libraries/LibJS/Tests/modules/default-regexp-export.mjs
  Userland/Libraries/LibJS/Tests/syntax/slash-after-block.js
Labels: 👀 pr-needs-review

#19217 LibGfx/JPEG: Improve input data access
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Labels: 👀 pr-needs-review

#19321 Lagom: Allow opting into linking with mold
  Meta/CMake/lagom_options.cmake
  Meta/Lagom/CMakeLists.txt
Labels: 👀 pr-needs-review

#19345 LibWeb: Forward media attribute from link element to loaded style sheet
  Tests/LibWeb/Text/expected/link-element-media-attribute.txt
  Tests/LibWeb/Text/input/body-background-color-red.css
  Tests/LibWeb/Text/input/link-element-media-attribute.html
  Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Labels: 👀 pr-needs-review

#19347 LibC: Implement stpcpy
  Userland/Libraries/LibC/string.cpp
  Userland/Libraries/LibC/string.h
Labels: 👀 pr-needs-review

#19349 LibWeb: Avoid crash for unsupported length unit in SVG elements
  Userland/Libraries/LibWeb/SVG/SVGTextContentElement.cpp
Labels: 👀 pr-needs-review

#19358 LibGfx/PNG: Cleanup
  Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp
Labels: 👀 pr-needs-review

#19350 Shell: Reset the custom Shell keybinds before calling Editor::get_line()
  Userland/Shell/Shell.cpp
  Userland/Shell/Shell.h
Labels: 👀 pr-needs-review

#19361 Meta: Rename `BuildIt.sh` to `BuildGNU.sh`
  .github/workflows/cmake.yml
  .github/workflows/pvs-studio-static-analysis.yml
  .github/workflows/sonar-cloud-static-analysis.yml
  Documentation/CLionConfiguration.md
  Meta/Azure/Caches.yml
  Meta/serenity.sh
  Toolchain/BuildGNU.sh
Labels: 👀 pr-needs-review

#19368 LibWeb+WebContent: Forbid access to underlying type of CSSPixels
  Tests/LibWeb/Layout/expected/acid1.txt
  Tests/LibWeb/Layout/expected/grid/image-in-grid.txt
  Userland/Libraries/LibWeb/CSS/EdgeRect.cpp
  Userland/Libraries/LibWeb/CSS/Length.cpp
  Userland/Libraries/LibWeb/CSS/Screen.cpp
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/FilterValueListStyleValue.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/LinearGradientStyleValue.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/RadialGradientStyleValue.cpp
  Userland/Libraries/LibWeb/DOM/Element.cpp
  Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
  Userland/Libraries/LibWeb/HTML/SourceSet.cpp
  Userland/Libraries/LibWeb/HTML/Window.cpp
  Userland/Libraries/LibWeb/Layout/AvailableSpace.cpp
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/LayoutState.cpp
  Userland/Libraries/LibWeb/Layout/LineBox.cpp
  Userland/Libraries/LibWeb/Layout/LineBuilder.cpp
  Userland/Libraries/LibWeb/Layout/Node.cpp
  Userland/Libraries/LibWeb/Layout/SVGFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/SVGGeometryBox.cpp
  Userland/Libraries/LibWeb/Layout/SVGSVGBox.cpp
  Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
  Userland/Libraries/LibWeb/Page/Page.cpp
  Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
  Userland/Libraries/LibWeb/Painting/BorderPainting.cpp
  Userland/Libraries/LibWeb/Painting/GradientPainting.cpp
  Userland/Libraries/LibWeb/Painting/MarkerPaintable.cpp
  Userland/Libraries/LibWeb/Painting/PaintContext.cpp
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
  Userland/Libraries/LibWeb/PixelUnits.h
  Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
  Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
  Userland/Libraries/LibWeb/UIEvents/MouseEvent.cpp
  Userland/Libraries/LibWeb/UIEvents/WheelEvent.cpp
  Userland/Services/WebContent/ConnectionFromClient.cpp
  Userland/Services/WebContent/PageHost.cpp
Labels: 👀 pr-needs-review

#19369 LibGfx: Avoid fill_path() crashes due to rounding errors
  Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.cpp
Labels: 👀 pr-needs-review

#19329 LibWeb: Teach CSS transformed StackingContexts about image-rendering
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Labels: 👀 pr-needs-review

#18751 SystemServer: Handle waitpid's status correctly
  Userland/Services/SystemServer/Service.cpp
  Userland/Services/SystemServer/Service.h
Labels: 👀 pr-needs-review

#19376 AK: Simplify `Vector::padded_capacity`
  AK/Vector.h
Labels: 👀 pr-needs-review

#19377 Ladybird: Update screen rects on client creation
  Ladybird/WebContentView.cpp
Labels: 👀 pr-needs-review

#19378 LibWeb: Make stretch-fit return 0 when the available size is indefinite
  Tests/LibWeb/Layout/expected/svg/dont-stretch-fit-svg-with-indefinite-containing-block-width.txt
  Tests/LibWeb/Layout/input/svg/dont-stretch-fit-svg-with-indefinite-containing-block-width.html
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Labels: 👀 pr-needs-review

#19290 Ports/nhlohmann-json: fix pkgconf install path
  Ports/nlohmann-json/package.sh
Labels: 👀 pr-needs-review

#19374 CI: Try to fix macOS CI
  Meta/Azure/Setup.yml
Labels: 👀 pr-needs-review

#19381 LibWeb: Resolve auto margins on abspos elements in more cases
  Tests/LibWeb/Layout/expected/block-and-inline/abspos-with-auto-margins-in-inline-axis.txt
  Tests/LibWeb/Layout/input/block-and-inline/abspos-with-auto-margins-in-inline-axis.html
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Labels: 👀 pr-needs-review

#19392 Base: Rename Cupertino window-close-modified-hover.jpg to .png
  Base/res/icons/themes/Cupertino/16x16/window-close-modified-hover.png
Labels: 👀 pr-needs-review

#19391 LibWeb: Fix the x coordinate of a block after a float
  Tests/LibWeb/Layout/expected/block-and-inline/block-with-hidden-overflow-after-float.txt
  Tests/LibWeb/Layout/input/block-and-inline/block-with-hidden-overflow-after-float.html
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
  Userland/Libraries/LibWeb/Layout/FormattingContext.h
  Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Labels: 👀 pr-needs-review

#19383 LibRegex: Treat \<ORD_CHAR> as unescaped in POSIX BRE/ERE
  Userland/Libraries/LibRegex/RegexParser.cpp
Labels: 👀 pr-needs-review

#19398 LibWeb: Treat % max-width as none when containing block size indefinite
  Tests/LibWeb/Layout/expected/img-with-percentage-max-width-and-indefinite-containing-block-width.txt
  Tests/LibWeb/Layout/input/img-with-percentage-max-width-and-indefinite-containing-block-width.html
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/FormattingContext.h
  Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Labels: 👀 pr-needs-review

#19399 Tests/LibWeb: WPT runner script improvements
  Tests/LibWeb/WPT/run.sh
Labels: 👀 pr-needs-review

#19402 LibWeb: Support SVG vertical/horizontal lineto with multiple parameters
  Userland/Libraries/LibWeb/SVG/AttributeParser.cpp
Labels: 👀 pr-needs-review

#19164 LibWeb: Implement CSS sign related functions
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/CSS/Parser/Parser.h
  Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
Labels: 👀 pr-needs-review

#19161 LibWeb: Parse css math constants
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
Labels: 👀 pr-needs-review, ⚠️ pr-has-conflicts

#19410 Base: Remove unused png file
  Base/res/icons/themes/Durrque/frame-half-shadow-light.png
Labels: 👀 pr-needs-review

#19407 pkill: Add -n, -o and -O options to filter processes by age
  Base/usr/share/man/man1/pkill.md
  Userland/Utilities/pkill.cpp
Labels: 👀 pr-needs-review

#18699 LibGUI: Fix more crashes/stucks on deleting word backward
  Userland/Libraries/LibGUI/TextDocument.cpp
Labels: ✅ pr-community-approved

#19419 LibWeb: Parse identifiers last in `parse_paint_value()`
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#19421 LibWeb: Make border-collapse actually inherited
  Tests/LibWeb/Layout/expected/table/border-collapse-is-inherited.txt
  Tests/LibWeb/Layout/input/table/border-collapse-is-inherited.html
  Userland/Libraries/LibWeb/CSS/ComputedValues.h
Labels: 👀 pr-needs-review

#19432 LibWeb/CSS: Update Default.css from the HTML specification
  Userland/Libraries/LibWeb/CSS/Default.css
Labels: 👀 pr-needs-review

#19430 LibWeb: Handle calculated `vertical-align`
  Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
Labels: 👀 pr-needs-review

#19429 LibXML: Fix parser not leaving self-closing tags
  Userland/Libraries/LibXML/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#19415 LibCompress/Gzip: Replace usage of DeprecatedString
  Userland/Libraries/LibCompress/Gzip.cpp
  Userland/Libraries/LibCompress/Gzip.h
  Userland/Utilities/file.cpp
Labels: 👀 pr-needs-review

#19436 LibWeb: Add audio mime types to HTMLMediaElement.canPlayType
  Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
Labels: 👀 pr-needs-review

#19433 Ports: Update serenity-theming use latest commit 43c42c9
  Ports/AvailablePorts.md
  Ports/serenity-theming/package.sh
Labels: 👀 pr-needs-review

#19159 LibWeb: Implement CSS stepped value functions
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/CSS/Parser/Parser.h
  Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
Labels: 👀 pr-needs-review

#19437 LibWeb: Create an audio document for `audio/` MIME types on navigation
  Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
Labels: 👀 pr-needs-review

#19438 Ladybird+LibJS: Add CLI option to run browser with LibJS bytecode VM
  Ladybird/BrowserWindow.cpp
  Ladybird/BrowserWindow.h
  Ladybird/ConsoleWidget.cpp
  Ladybird/Tab.cpp
  Ladybird/Tab.h
  Ladybird/WebContent/main.cpp
  Ladybird/WebContentView.cpp
  Ladybird/WebContentView.h
  Ladybird/main.cpp
  Tests/LibJS/test-bytecode-js.cpp
  Tests/LibJS/test262-runner.cpp
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
  Userland/Libraries/LibJS/Bytecode/Interpreter.h
  Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
  Userland/Libraries/LibWeb/HTML/Scripting/ClassicScript.cpp
  Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
  Userland/Libraries/LibWebView/OutOfProcessWebView.h
  Userland/Libraries/LibWebView/ViewImplementation.cpp
  Userland/Libraries/LibWebView/ViewImplementation.h
  Userland/Utilities/headless-browser.cpp
Labels: 👀 pr-needs-review

#19445 LibWeb: Use correct reference for abspos elements with % height sizes
  Tests/LibWeb/Layout/expected/block-and-inline/abspos-with-percentage-height-resolved-against-padding-box-of-containing-block.txt
  Tests/LibWeb/Layout/input/block-and-inline/abspos-with-percentage-height-resolved-against-padding-box-of-containing-block.html
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Labels: 👀 pr-needs-review

#19446 LibWeb: Fix end position for objectBoundingBox SVG <radialGradient>s
  Base/res/html/misc/svg-gradients.html
  Userland/Libraries/LibWeb/SVG/SVGRadialGradientElement.cpp
Labels: 👀 pr-needs-review

#19453 LibWeb: Don't cap used width by available width from a constraint
  Tests/LibWeb/Layout/expected/table/row-span-and-nested-tables.txt
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Labels: 👀 pr-needs-review

#19435 Kernel: Put loopback adapter debug spam behind a flag
  Kernel/Debug.h.in
  Kernel/Net/LoopbackAdapter.cpp
  Meta/CMake/all_the_debug_macros.cmake
Labels: 👀 pr-needs-review

#19454 LibWeb: Handle leading whitespace in grid-template-* block components
  Tests/LibWeb/Layout/expected/misc/grid-template-block-components-whitespace-crash.txt
  Tests/LibWeb/Layout/input/misc/grid-template-block-components-whitespace-crash.html
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#19464 WebP/Lossless: Set alpha to 0xff if is_alpha_used is false in header
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/simple-vp8l-alpha-used-false.webp
  Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossless.cpp
Labels: 👀 pr-needs-review

#19463 LibWeb: Add HTMLButtonElement#disabled
  Userland/Libraries/LibWeb/HTML/HTMLButtonElement.idl
Labels: 👀 pr-needs-review

#19466 LibWeb: Use padding box of containing block to resolve % height size
  Tests/LibWeb/Layout/expected/block-and-inline/percentage-min-height-with-containing-block-padding.txt
  Tests/LibWeb/Layout/expected/block-and-inline/percentage-min-height.txt
  Tests/LibWeb/Layout/input/block-and-inline/percentage-min-height-with-containing-block-padding.html
  Tests/LibWeb/Layout/input/block-and-inline/percentage-min-height.html
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Labels: 👀 pr-needs-review

#19461 Ports: Point to the correct subdirectory for `gettext`
  Ports/gettext/package.sh
Labels: 👀 pr-needs-review

#19449 chmod: Don't bail immediately on error
  Userland/Utilities/chmod.cpp
Labels: 👀 pr-needs-review

#19456 LibWeb: Skip separate height computation for tables
  Tests/LibWeb/Layout/expected/table/multi-line-cell.txt
  Tests/LibWeb/Layout/input/table/multi-line-cell.html
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Labels: 👀 pr-needs-review

#19462 Browser+pro: Correctly report progress of downloads larger than 4GiB
  Userland/Applications/Browser/DownloadWidget.cpp
  Userland/Applications/Browser/DownloadWidget.h
  Userland/Libraries/LibCore/NetworkJob.cpp
  Userland/Libraries/LibCore/NetworkJob.h
  Userland/Libraries/LibHTTP/Job.cpp
  Userland/Libraries/LibHTTP/Job.h
  Userland/Libraries/LibProtocol/Request.cpp
  Userland/Libraries/LibProtocol/Request.h
  Userland/Libraries/LibProtocol/RequestClient.cpp
  Userland/Libraries/LibProtocol/RequestClient.h
  Userland/Libraries/LibWeb/Loader/ResourceLoader.h
  Userland/Libraries/LibWebView/RequestServerAdapter.cpp
  Userland/Services/RequestServer/GeminiRequest.cpp
  Userland/Services/RequestServer/HttpCommon.h
  Userland/Services/RequestServer/Request.cpp
  Userland/Services/RequestServer/Request.h
  Userland/Services/RequestServer/RequestClient.ipc
  Userland/Utilities/pro.cpp
Labels: 👀 pr-needs-review

#19470 LibGfx: Remove unneeded TODO in BMPLoader
  Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp
Labels: 👀 pr-needs-review

#19471 chown: Don't bail immediately on error
  Userland/Utilities/chown.cpp
Labels: 👀 pr-needs-review

#19051 ping: Avoid potential interval overflow and don't wait before exiting
  Userland/Utilities/ping.cpp
Labels: stale, 👀 pr-needs-review

#19475 LibWeb: Fix empty slot finding in table formation algorithm
  Tests/LibWeb/Layout/expected/table/table-formation-with-rowspan-in-the-middle.txt
  Tests/LibWeb/Layout/input/table/table-formation-with-rowspan-in-the-middle.html
  Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Labels: 👀 pr-needs-review

#19478 LibWeb: Clip cell spans past the end of the table
  Tests/LibWeb/Layout/expected/table/clip-spans-to-table-end.txt
  Tests/LibWeb/Layout/input/table/clip-spans-to-table-end.html
  Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Labels: 👀 pr-needs-review

#19473 Kernel/TCPSocket: Read window size from peer
  Kernel/Net/TCPSocket.cpp
  Kernel/Net/TCPSocket.h
Labels: 👀 pr-needs-review

#19477 Fuzzers: Update the path to fuzzer binaries
  Meta/Lagom/BuildFuzzers.sh
Labels: 👀 pr-needs-review

#19481 LibWeb/WebDriver: Close client connection socket when EOF is reached
  Userland/Libraries/LibWeb/WebDriver/Client.cpp
Labels: 👀 pr-needs-review

#19486 Browser: Set DownloadWidget progress bar minimum value correctly
  Userland/Applications/Browser/DownloadWidget.cpp
Labels: 👀 pr-needs-review

#19484 LibWeb: Allow IFC to size inline-flex boxes midway through flex layout
  Tests/LibWeb/Layout/expected/flex/inline-flex-with-main-axis-margin-on-flex-container.txt
  Tests/LibWeb/Layout/input/flex/inline-flex-with-main-axis-margin-on-flex-container.html
  Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/InlineFormattingContext.h
Labels: 👀 pr-needs-review

#19487 groupdel: Ensure the veil is closed after required files are unveiled
  Userland/Utilities/groupdel.cpp
Labels: 👀 pr-needs-review

#19492 LibWeb: Use enclosing (rather than rounded) rect for overflow clipping
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Labels: 👀 pr-needs-review

#19489 rmdir: Add `-p` to remove parent directories and `-v` to be verbose
  Base/usr/share/man/man1/rmdir.md
  Userland/Utilities/rmdir.cpp
Labels: ✅ pr-community-approved

#18553 Meta: Speed up `lint-ports` by ~99.2%
  Meta/lint-ports.py
Labels: 👀 pr-needs-review

#19259 Utilities: Add pixelflut, a Pixelflut protocol client
  Userland/Utilities/CMakeLists.txt
  Userland/Utilities/pixelflut.cpp
Labels: 👀 pr-needs-review

#19497 Tests: Factor out some repetitive code in TestImageDecoder.cpp
  Tests/LibGfx/TestImageDecoder.cpp
Labels: ✅ pr-community-approved

#19494 LibWeb: Use PaintContext::would_be_fully_clipped_by_painter() everywhere
  Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Labels: 👀 pr-needs-review
