Repository SerenityOS/serenity, pull requests merged in 2023-08, with the labels that each got.

#20212 Ports: Add cowsay
  Ports/AvailablePorts.md
  Ports/cowsay/package.sh
Labels: ports, 👀 pr-needs-review

#20293 Ladybird: Rename FontPluginQt -> Ladybird as it is unrelated to Qt now
  Ladybird/FontPluginLadybird.cpp
  Ladybird/FontPluginLadybird.h
  Ladybird/WebContent/CMakeLists.txt
  Ladybird/WebContent/main.cpp
  Meta/gn/secondary/Ladybird/WebContent/BUILD.gn
Labels: 👀 pr-needs-review

#20289 LibGfx/JPEGXL: Fix property 8
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/jxl/modular_property_8.jxl
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Labels: 👀 pr-needs-review

#19773 Kernel: Mark sys$poll as not needing the big lock
  Kernel/API/Syscall.h
  Kernel/Syscalls/poll.cpp
Labels: 👀 pr-needs-review

#20287 Ladybird: Fix JS console crash when history is empty
  Ladybird/ConsoleWidget.cpp
Labels: 👀 pr-needs-review

#20288 Ladybird: Remove unused spawn helper
  Ladybird/HelperProcess.cpp
  Ladybird/HelperProcess.h
Labels: 👀 pr-needs-review

#20249 LibWeb: Clear float boxes from inline formatting context
  Tests/LibWeb/Layout/expected/block-and-inline/clear-both-from-inline-formatting-context.txt
  Tests/LibWeb/Layout/expected/block-and-inline/float-clear-by-line-break.txt
  Tests/LibWeb/Layout/input/block-and-inline/clear-both-from-inline-formatting-context.html
  Tests/LibWeb/Layout/input/block-and-inline/float-clear-by-line-break.html
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
  Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/InlineFormattingContext.h
  Userland/Libraries/LibWeb/Layout/LineBuilder.h
Labels: 👀 pr-needs-review

#20296 LibWeb: Detach stale layout nodes from DOM during layout tree build
  Tests/LibWeb/Text/expected/setting-display-none-should-nuke-subtree.txt
  Tests/LibWeb/Text/input/setting-display-none-should-nuke-subtree.html
  Userland/Libraries/LibWeb/DOM/Node.cpp
  Userland/Libraries/LibWeb/DOM/Node.h
  Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Labels: 👀 pr-needs-review

#19850 AK: Clear buffer after leaving CannotBeABaseUrlPath in URLParser
  AK/URLParser.cpp
  Tests/AK/TestURL.cpp
Labels: ✅ pr-community-approved

#20280 LibWeb: Add tests for calc function nodes
  Tests/LibWeb/Layout/expected/css-values/comparison-functions.txt
  Tests/LibWeb/Layout/expected/css-values/exponential-functions.txt
  Tests/LibWeb/Layout/expected/css-values/numeric-constants.txt
  Tests/LibWeb/Layout/expected/css-values/sign-related-functions.txt
  Tests/LibWeb/Layout/expected/css-values/stepped-value-functions.txt
  Tests/LibWeb/Layout/expected/css-values/trigonometric-functions.txt
  Tests/LibWeb/Layout/input/css-values/comparison-functions.html
  Tests/LibWeb/Layout/input/css-values/exponential-functions.html
  Tests/LibWeb/Layout/input/css-values/numeric-constants.html
  Tests/LibWeb/Layout/input/css-values/sign-related-functions.html
  Tests/LibWeb/Layout/input/css-values/stepped-value-functions.html
  Tests/LibWeb/Layout/input/css-values/trigonometric-functions.html
Labels: 👀 pr-needs-review

#20284 LibWeb: Use viewbox attribute in SVG symbol element
  Tests/LibWeb/Layout/expected/svg/svg-symbol-with-viewbox.txt
  Tests/LibWeb/Layout/input/svg/svg-symbol-with-viewbox.html
  Userland/Libraries/LibWeb/Layout/SVGFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/SVGGeometryBox.cpp
  Userland/Libraries/LibWeb/Painting/SVGGeometryPaintable.cpp
  Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
  Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.h
  Userland/Libraries/LibWeb/SVG/SVGSymbolElement.cpp
  Userland/Libraries/LibWeb/SVG/SVGSymbolElement.h
Labels: 👀 pr-needs-review

#20299 LibJS: Use correct `this` value when callee is a `with` binding
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
  Userland/Libraries/LibJS/Bytecode/Instruction.h
  Userland/Libraries/LibJS/Bytecode/Op.cpp
  Userland/Libraries/LibJS/Bytecode/Op.h
Labels: 👀 pr-needs-review

#20300 LibWeb: Use item minimum contribution while sizing "fr" track in GFC
  Tests/LibWeb/Layout/expected/grid/row-1fr.txt
  Tests/LibWeb/Layout/input/grid/row-1fr.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#20302 LibWeb: Implement media-related pseudo-classes
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/CSS/Selector.cpp
  Userland/Libraries/LibWeb/CSS/Selector.h
  Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
  Userland/Libraries/LibWeb/Dump.cpp
  Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#20303 LibWeb: Ignore flex container size constraints during intrinsic sizing
  Tests/LibWeb/Layout/expected/flex/flex-column-container-with-max-width-max-content.txt
  Tests/LibWeb/Layout/input/flex/flex-column-container-with-max-width-max-content.html
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Labels: 👀 pr-needs-review

#20315 LibWeb: Don't lay out light DOM children of elements with a shadow root
  Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Labels: 👀 pr-needs-review

#20317 LibWeb: Set max-width for inline child boxes after inside layout
  Tests/LibWeb/Layout/expected/block-and-inline/max-width-for-box-with-inline-children.txt
  Tests/LibWeb/Layout/input/block-and-inline/max-width-for-box-with-inline-children.html
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Labels: 👀 pr-needs-review

#20322 LibWeb: Reformat inconsistent CSS JSON files
  Userland/Libraries/LibWeb/CSS/Enums.json
  Userland/Libraries/LibWeb/CSS/MediaFeatures.json
  Userland/Libraries/LibWeb/CSS/TransformFunctions.json
Labels: 👀 pr-needs-review

#20281 Base: Add a quote to the fortunes database
  Base/res/fortunes.json
Labels: 👀 pr-needs-review

#20306 LibWeb: Make sure we fallback to "Unsupported type" if type unrecognized
  Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
Labels: 👀 pr-needs-review

#20326 Ladybird: Ensure RequestServer depends on its generated sources
  Ladybird/RequestServer/CMakeLists.txt
Labels: 👀 pr-needs-review

#20329 LibGfx/OpenType: Return metrics from hmtx even if there is no glyf entry
  Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
Labels: 👀 pr-needs-review

#19384 LibCore: Fallback to fstat() on systems without d_type support
  Userland/Libraries/LibCore/DirIterator.cpp
  Userland/Libraries/LibCore/DirectoryEntry.cpp
  Userland/Libraries/LibCore/DirectoryEntry.h
Labels: 👀 pr-needs-review

#20345 LibWebView: Create BGRA bitmaps instead of BGRx
  Userland/Libraries/LibWebView/ViewImplementation.cpp
Labels: 👀 pr-needs-review

#20346 LibWeb: Reset planned_increase while distributing space to "fr" tracks
  Tests/LibWeb/Layout/expected/grid/two-items-spanning-one-1fr-row.txt
  Tests/LibWeb/Layout/input/grid/two-items-spanning-one-1fr-row.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#20340 Meta: Port GCC compile option from cmake to gn
  Meta/gn/build/BUILD.gn
Labels: 👀 pr-needs-review

#20277 LibWeb: Use CSS text-indent property on input type="submit" elements text
  Userland/Libraries/LibWeb/Painting/ButtonPaintable.cpp
Labels: 👀 pr-needs-review

#20351 watch: Use alternate buffer to display output
  Userland/Utilities/watch.cpp
Labels: 👀 pr-needs-review

#20347 CI: Disable aarch64 tests
  .github/workflows/cmake.yml
Labels: 👀 pr-needs-review

#20356 LibWeb: Remove hardcoded span = 2 while sizing spanning items in GFC
  Tests/LibWeb/Layout/expected/grid/grid-span-4.txt
  Tests/LibWeb/Layout/input/grid/grid-span-4.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#20258 Meta: Remove .gitignore from Base/
  .gitignore
  Base/.gitignore
Labels: 👀 pr-needs-review

#20354 LibMarkdown: Preserve blank lines in `CodeBlock`s
  Userland/Libraries/LibMarkdown/CodeBlock.cpp
Labels: 👀 pr-needs-review

#20311 Ports/glm: Create `/usr/local/include` if it doesn't exist
  Ports/glm/package.sh
Labels: 👀 pr-needs-review

#20360 Ladybird+Browser: Update zoom text on menu after clicking zoom button
  Ladybird/BrowserWindow.cpp
  Ladybird/BrowserWindow.h
  Ladybird/Tab.cpp
  Userland/Applications/Browser/BrowserWindow.cpp
  Userland/Applications/Browser/BrowserWindow.h
  Userland/Applications/Browser/Tab.cpp
Labels: 👀 pr-needs-review

#20363 Meta: Truncate generated IDL source files
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/main.cpp
Labels: 👀 pr-needs-review

#20295 sed: Keep correct owner and permissions with `sed -i`
  Userland/Utilities/sed.cpp
Labels: 👀 pr-needs-review

#20366 BindingsGenerator: Only truncate generated files if they have changed
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/main.cpp
Labels: 👀 pr-needs-review

#20365 Ports/sqlite: Replace the stub libtool patch with the full version
  Ports/sqlite/patches/0001-Teach-configure-about-serenity.patch
  Ports/sqlite/patches/0001-libtool-Enable-shared-library-support-for-SerenityOS.patch
  Ports/sqlite/patches/ReadMe.md
Labels: 👀 pr-needs-review

#20372 Shell: Color bareword yellow if it's a prefix of at least one command
  Userland/Shell/AST.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#20334 Ladybird: Add app icon for macOS
  Ladybird/CMakeLists.txt
  Ladybird/Icons/macos/app_icon.iconset/icon_128x128.png
  Ladybird/Icons/macos/app_icon.iconset/icon_128x128@2x.png
  Ladybird/Icons/macos/app_icon.iconset/icon_16x16.png
  Ladybird/Icons/macos/app_icon.iconset/icon_16x16@2x.png
  Ladybird/Icons/macos/app_icon.iconset/icon_256x256.png
  Ladybird/Icons/macos/app_icon.iconset/icon_256x256@2x.png
  Ladybird/Icons/macos/app_icon.iconset/icon_32x32.png
  Ladybird/Icons/macos/app_icon.iconset/icon_32x32@2x.png
  Ladybird/Icons/macos/app_icon.iconset/icon_512x512.png
  Ladybird/Icons/macos/app_icon.iconset/icon_512x512@2x.png
  Ladybird/Info.plist
Labels: 👀 pr-needs-review

#20319 Spreadsheet: Fix a crash when opening help window twice
  Userland/Applications/Spreadsheet/HelpWindow.cpp
  Userland/Applications/Spreadsheet/SpreadsheetWidget.cpp
Labels: 👀 pr-needs-review

#20370 Meta: Implement support for the new String in the gdb formatter
  Meta/serenity_gdb.py
Labels: ✅ pr-community-approved

#20375 Meta: Add myself to CODEOWNERS
  .github/CODEOWNERS
Labels: 👀 pr-needs-review

#20374 LibWeb: Fix calculating the corner radius values for SVG <rect>
  Userland/Libraries/LibWeb/SVG/SVGRectElement.cpp
Labels: 👀 pr-needs-review

#20271 LibGfx/JPEGXL: Add support for the self-correcting predictor
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Labels: 👀 pr-needs-review

#20221 LibJS: Capture UnrealizedSourceRanges in ExecutionContext, not ASTNodes
  Userland/Applications/Spreadsheet/Workbook.cpp
  Userland/Libraries/LibJS/AST.cpp
  Userland/Libraries/LibJS/AST.h
  Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
  Userland/Libraries/LibJS/Runtime/Error.cpp
  Userland/Libraries/LibJS/Runtime/Error.h
  Userland/Libraries/LibJS/Runtime/ExecutionContext.cpp
  Userland/Libraries/LibJS/Runtime/ExecutionContext.h
  Userland/Libraries/LibJS/Runtime/NativeFunction.cpp
  Userland/Libraries/LibJS/Runtime/VM.cpp
  Userland/Libraries/LibJS/SourceRange.h
Labels: 👀 pr-needs-review

#20323 LibWeb: Set min-width for inline child boxes after inside layout
  Tests/LibWeb/Layout/expected/block-and-inline/min-width-for-box-with-inline-children.txt
  Tests/LibWeb/Layout/input/block-and-inline/min-width-for-box-with-inline-children.html
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Labels: 👀 pr-needs-review

#20376 LibWeb: Improve adjustment of automatic table width with percentages
  Tests/LibWeb/Layout/expected/table/percentage-width-columns.txt
  Tests/LibWeb/Layout/expected/table/percentage-width-max-width-columns.txt
  Tests/LibWeb/Layout/expected/table/sum-of-percentage-column-widths-less-than-100.txt
  Tests/LibWeb/Layout/input/table/percentage-width-max-width-columns.html
  Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Labels: 👀 pr-needs-review

#20310 Ports/vim: Override `uname` output to fix compilation on macOS
  Ports/vim/package.sh
Labels: 👀 pr-needs-review

#20377 LibWeb: Support more kinds of indefinite widths on flex column items
  Tests/LibWeb/Layout/expected/flex/intrinsic-height-of-column-items-with-different-kinds-of-width.txt
  Tests/LibWeb/Layout/input/flex/intrinsic-height-of-column-items-with-different-kinds-of-width.html
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
Labels: 👀 pr-needs-review

#20181 top: Disable echo and line buffering on startup
  Userland/Utilities/top.cpp
Labels: 👀 pr-needs-review

#20357 LibWeb: Update reactive images according to spec after fetches finish
  Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
Labels: 👀 pr-needs-review

#20335 Ports/potrace: Add zlib dependency
  Ports/potrace/package.sh
Labels: 👀 pr-needs-review

#20380 Ladybird: Do not try to use pixelDelta() to calculate wheel offset
  Ladybird/WebContentView.cpp
Labels: 👀 pr-needs-review

#20378 LibWeb: Parse :host() selector
  Tests/LibWeb/Layout/expected/css-host-selector-gets-parsed.txt
  Tests/LibWeb/Layout/input/css-host-selector-gets-parsed.html
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/Dump.cpp
Labels: 👀 pr-needs-review

#20382 LibRegex: Keep track of instruction positions for backwards tree jumps
  Tests/LibRegex/Regex.cpp
  Userland/Libraries/LibRegex/RegexOptimizer.cpp
Labels: 👀 pr-needs-review

#20342 LibWeb: Add Canvas Context2D basic text align and text baseline support
  Base/res/html/misc/canvas-text.html
  Userland/Libraries/LibWeb/Forward.h
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasPathDrawingStyles.idl
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasState.h
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasTextDrawingStyles.h
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasTextDrawingStyles.idl
  Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
  Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.h
  Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.idl
Labels: 👀 pr-needs-review

#20381 Ports/doom: Use upstream doomgeneric SDL port
  Ports/AvailablePorts.md
  Ports/doom/package.sh
  Ports/doom/patches/0001-Update-the-makefile-for-serenity.patch
  Ports/doom/patches/0002-Use-SDL-software-renderer.patch
  Ports/doom/patches/ReadMe.md
Labels: 👀 pr-needs-review

#20386 fortune: Use simple formatting when stdout isn't connected to a terminal
  Base/usr/share/man/man1/fortune.md
  Userland/Utilities/fortune.cpp
Labels: 👀 pr-needs-review

#20390 AK: Fix IPv6 serialization on multiple '0' parts ending in a '0' part
  AK/URLParser.cpp
  Tests/LibWeb/Text/expected/URL/url.txt
  Tests/LibWeb/Text/input/URL/url.html
Labels: 👀 pr-needs-review

#20389 PixelPaint: Use a mutable lambda instead of const_cast in filters
  Userland/Applications/PixelPaint/ImageProcessor.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#20394 LibWeb: Add a simple `internals` objects only available during testing
  Ladybird/WebContent/main.cpp
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/Namespaces.h
  Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWindowOrWorkerInterfaces.cpp
  Tests/LibWeb/Text/expected/internals.txt
  Tests/LibWeb/Text/input/internals.html
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/Forward.h
  Userland/Libraries/LibWeb/HTML/Window.cpp
  Userland/Libraries/LibWeb/HTML/Window.h
  Userland/Libraries/LibWeb/Internals/Internals.cpp
  Userland/Libraries/LibWeb/Internals/Internals.h
  Userland/Libraries/LibWeb/Internals/Internals.idl
  Userland/Libraries/LibWeb/idl_files.cmake
Labels: 👀 pr-needs-review

#20396 LibGfx: Track edge extent in EdgeFlagPathRasterizer
  Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.cpp
  Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.h
Labels: 👀 pr-needs-review

#20392 LibWeb: Implement basic version of CSSOM View's VisualViewport
  Meta/gn/secondary/Userland/Libraries/LibWeb/CSS/BUILD.gn
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/CSS/VisualViewport.cpp
  Userland/Libraries/LibWeb/CSS/VisualViewport.h
  Userland/Libraries/LibWeb/CSS/VisualViewport.idl
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/Forward.h
  Userland/Libraries/LibWeb/HTML/EventNames.h
  Userland/Libraries/LibWeb/HTML/Window.cpp
  Userland/Libraries/LibWeb/HTML/Window.h
  Userland/Libraries/LibWeb/HTML/Window.idl
  Userland/Libraries/LibWeb/idl_files.cmake
Labels: 👀 pr-needs-review

#20391 Ports/nesalizer: Add SDL2 header include path to Makefile
  Ports/nesalizer/patches/0001-Add-Serenity-to-Makefile.patch
  Ports/nesalizer/patches/ReadMe.md
Labels: 👀 pr-needs-review

#20400 CI: Remove workflows dependent on the LibJS website
  .github/workflows/libjs-test262.yml
  .github/workflows/wasm.yml
Labels: 👀 pr-needs-review

#20352 LibWeb: Move the media volume slider 1:1 with the mouse cursor
  Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
  Userland/Libraries/LibWeb/Painting/MediaPaintable.cpp
  Userland/Libraries/LibWeb/Painting/MediaPaintable.h
Labels: 👀 pr-needs-review

#20401 LibGUI: Traverse into directory upon filename entry in FilePicker
  Userland/Libraries/LibGUI/FilePicker.cpp
Labels: 👀 pr-needs-review

#20320 LibWeb: Snap table grid to device pixels in collapsed borders mode
  Userland/Libraries/LibWeb/Painting/TableBordersPainting.cpp
Labels: 👀 pr-needs-review

#20407 LibCore: Only use coarse time in the Unix event loop wait_for_events()
  Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#20402 Ladybird: Copy cacert.pem into the expected build-time path on macOS
  Ladybird/CMakeLists.txt
Labels: 👀 pr-needs-review

#20330 BuildDocs: Add intructions to enable legacy renegotiation
  Documentation/Troubleshooting.md
Labels: 👀 pr-needs-review

#18841 Calendar+LibGUI: Implement saving, loading, and displaying calendars
  Base/etc/FileIconProvider.ini
  Base/res/apps/Calendar.af
  Base/res/icons/16x16/filetype-calendar.png
  Base/res/icons/32x32/filetype-calendar.png
  Userland/Applications/Calendar/AddEventDialog.cpp
  Userland/Applications/Calendar/AddEventDialog.h
  Userland/Applications/Calendar/CMakeLists.txt
  Userland/Applications/Calendar/CalendarWidget.cpp
  Userland/Applications/Calendar/CalendarWidget.h
  Userland/Applications/Calendar/CalendarWindow.gml
  Userland/Applications/Calendar/EventCalendar.cpp
  Userland/Applications/Calendar/EventCalendar.h
  Userland/Applications/Calendar/EventManager.cpp
  Userland/Applications/Calendar/EventManager.h
  Userland/Applications/Calendar/main.cpp
  Userland/Libraries/LibGUI/Calendar.cpp
  Userland/Libraries/LibGUI/Calendar.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#20371 LibLine: Fix case-change operations
  Userland/Libraries/LibLine/InternalFunctions.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#20384 Ladybird: Move Qt-specific classes and functions to a Qt subdirectory
  Ladybird/CMakeLists.txt
  Ladybird/Qt/AndroidPlatform.cpp
  Ladybird/Qt/AudioCodecPluginQt.cpp
  Ladybird/Qt/AudioCodecPluginQt.h
  Ladybird/Qt/AudioThread.cpp
  Ladybird/Qt/AudioThread.h
  Ladybird/Qt/BrowserWindow.cpp
  Ladybird/Qt/BrowserWindow.h
  Ladybird/Qt/ConsoleWidget.cpp
  Ladybird/Qt/ConsoleWidget.h
  Ladybird/Qt/EventLoopImplementationQt.cpp
  Ladybird/Qt/EventLoopImplementationQt.h
  Ladybird/Qt/EventLoopImplementationQtEventTarget.cpp
  Ladybird/Qt/EventLoopImplementationQtEventTarget.h
  Ladybird/Qt/InspectorWidget.cpp
  Ladybird/Qt/InspectorWidget.h
  Ladybird/Qt/LocationEdit.cpp
  Ladybird/Qt/LocationEdit.h
  Ladybird/Qt/ModelTranslator.cpp
  Ladybird/Qt/ModelTranslator.h
  Ladybird/Qt/RequestManagerQt.cpp
  Ladybird/Qt/RequestManagerQt.h
  Ladybird/Qt/Settings.cpp
  Ladybird/Qt/Settings.h
  Ladybird/Qt/SettingsDialog.cpp
  Ladybird/Qt/SettingsDialog.h
  Ladybird/Qt/StringUtils.cpp
  Ladybird/Qt/StringUtils.h
  Ladybird/Qt/TVGIconEngine.cpp
  Ladybird/Qt/TVGIconEngine.h
  Ladybird/Qt/Tab.cpp
  Ladybird/Qt/Tab.h
  Ladybird/Qt/WebContentView.cpp
  Ladybird/Qt/WebContentView.h
  Ladybird/Qt/WebSocketClientManagerQt.cpp
  Ladybird/Qt/WebSocketClientManagerQt.h
  Ladybird/Qt/WebSocketImplQt.cpp
  Ladybird/Qt/WebSocketImplQt.h
  Ladybird/Qt/WebSocketQt.cpp
  Ladybird/Qt/WebSocketQt.h
  Ladybird/Qt/ladybird.qrc
  Ladybird/Qt/main.cpp
  Ladybird/Utilities.cpp
  Ladybird/Utilities.h
  Ladybird/WebContent/CMakeLists.txt
  Ladybird/WebContent/main.cpp
  Ladybird/WebDriver/CMakeLists.txt
  Ladybird/WebDriver/main.cpp
  Ladybird/ladybird.qrc
  Meta/gn/secondary/Ladybird/BUILD.gn
  Meta/gn/secondary/Ladybird/WebContent/BUILD.gn
  Meta/gn/secondary/Ladybird/WebDriver/BUILD.gn
  Userland/Utilities/headless-browser.cpp
Labels: 👀 pr-needs-review

#20414 Ladybird: Ensure selected new tab URL is a valid URL before saving
  Ladybird/Qt/SettingsDialog.cpp
Labels: 👀 pr-needs-review

#20419 LibJS: Apply the correct precedence for unary + and - operators
  Userland/Libraries/LibJS/Parser.cpp
  Userland/Libraries/LibJS/Tests/parser-unary-associativity.js
Labels: 👀 pr-needs-review

#20416 Browser: Synchronize database statements used for cookies
  Userland/Applications/Browser/CookieJar.cpp
  Userland/Applications/Browser/Database.h
Labels: 👀 pr-needs-review

#20364 LibWeb: Snap table grid to device pixels in separate borders mode
  Userland/Libraries/LibWeb/Painting/BorderPainting.cpp
  Userland/Libraries/LibWeb/Painting/BorderPainting.h
  Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
  Userland/Libraries/LibWeb/Painting/TableBordersPainting.cpp
  Userland/Libraries/LibWeb/Painting/TableBordersPainting.h
Labels: 👀 pr-needs-review

#20338 LibJS: Add an optional precision argument to toBeCloseTo test function
  Userland/Libraries/LibJS/Tests/test-common-tests.js
  Userland/Libraries/LibJS/Tests/test-common.js
Labels: 👀 pr-needs-review

#20424 LibJS: Remove bytecode option from the test262 runner
  Tests/LibJS/test262-runner.cpp
Labels: 👀 pr-needs-review

#20422 Userland: Open files for save in write-only mode
  Userland/Libraries/LibAudio/WavWriter.cpp
  Userland/Utilities/shot.cpp
Labels: 👀 pr-needs-review

#20404 usermod: Don't exit immediately for non-root users
  Userland/Utilities/usermod.cpp
Labels: 👀 pr-needs-review

#20428 CI: Restore running test262 and Wasm tests
  .github/workflows/libjs-test262.yml
Labels: 👀 pr-needs-review

#20305 LibGfx/JPEGXL: Implement the ANS decoder
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Labels: 👀 pr-needs-review

#20393 Userland: Pretty print the help text in BuggieBox
  Userland/BuggieBox/main.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#20425 LibC: Expect mutexes to be locked and needing wake when calling futex()
  Userland/Libraries/LibC/pthread_integration.cpp
Labels: 👀 pr-needs-review

#20433 Ports: Update ScummVM to 2.7.1
  Ports/AvailablePorts.md
  Ports/scummvm/package.sh
  Ports/scummvm/patches/0001-Prevent-call-to-glGetIntegerv-without-context.patch
  Ports/scummvm/patches/0001-Teach-configure-about-serenity.patch
  Ports/scummvm/patches/ReadMe.md
Labels: 👀 pr-needs-review

#20435 LibWeb: Implement `background-attachment: local`
  Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
Labels: 👀 pr-needs-review

#20443 LibGfx/JPEGXL: Add support for complex distribution clustering
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Labels: 👀 pr-needs-review

#20442 LibGfx/JPEGXL: Allow `ColourEncoding` bundles with custom values
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Labels: 👀 pr-needs-review

#20445 LibGfx/JPEGXL: Compute the position inside the channel correctly
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Labels: 👀 pr-needs-review

#20454 Docs: Use the term 'amend' instead of 'squash' in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: 👀 pr-needs-review

#20452 Ladybird: Remember window position and size on close
  Ladybird/Qt/BrowserWindow.cpp
  Ladybird/Qt/BrowserWindow.h
  Ladybird/Qt/Settings.cpp
  Ladybird/Qt/Settings.h
  Ladybird/Qt/main.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#20456 LibWeb: Don't parse inline style sheets during HTML fragment parsing
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/DOM/StyleElementUtils.cpp
  Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Labels: 👀 pr-needs-review

#20440 LibWeb: Add hit testing API in `internals` object
  Tests/LibWeb/Text/expected/hit_testing/basic.txt
  Tests/LibWeb/Text/expected/hit_testing/text.txt
  Tests/LibWeb/Text/input/hit_testing/basic.html
  Tests/LibWeb/Text/input/hit_testing/text.html
  Userland/Libraries/LibWeb/Internals/Internals.cpp
  Userland/Libraries/LibWeb/Internals/Internals.h
  Userland/Libraries/LibWeb/Internals/Internals.idl
Labels: 👀 pr-needs-review

#20448 LibWeb: Implement more steps in 'fetching a single module script'
  Userland/Libraries/LibWeb/HTML/HTMLScriptElement.cpp
  Userland/Libraries/LibWeb/HTML/Scripting/Fetching.cpp
  Userland/Libraries/LibWeb/HTML/Scripting/Fetching.h
Labels: 👀 pr-needs-review

#20453 LibJS: Improve garbage collection trigger condition
  Userland/Libraries/LibJS/Heap/Heap.cpp
  Userland/Libraries/LibJS/Heap/Heap.h
Labels: 👀 pr-needs-review

#20314 LibWeb: Vertically align HTML Button content
  Tests/LibWeb/Layout/expected/block-and-inline/button-should-have-vertically-aligned-content.txt
  Tests/LibWeb/Layout/input/block-and-inline/button-should-have-vertically-aligned-content.html
  Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Labels: 👀 pr-needs-review

#20468 Ports/SDL2: Avoid accumulation errors in resampler
  Ports/SDL2/patches/0002-audio-Avoid-accumulation-errors-in-resampler.patch
  Ports/SDL2/patches/ReadMe.md
Labels: 👀 pr-needs-review

#20463 LibWeb: Implement Element.hasAttributeNS
  Userland/Libraries/LibWeb/DOM/Element.cpp
  Userland/Libraries/LibWeb/DOM/Element.h
  Userland/Libraries/LibWeb/DOM/Element.idl
Labels: 👀 pr-needs-review

#20462 LibWeb: Unregister IntersectionObserver in finalize, not the destructor
  Userland/Libraries/LibWeb/IntersectionObserver/IntersectionObserver.cpp
  Userland/Libraries/LibWeb/IntersectionObserver/IntersectionObserver.h
Labels: 👀 pr-needs-review

#20465 LibJS: Implement await properly for async functions
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
  Userland/Libraries/LibJS/Runtime/AsyncFunctionDriverWrapper.cpp
  Userland/Libraries/LibJS/Runtime/AsyncFunctionDriverWrapper.h
  Userland/Libraries/LibJS/Tests/builtins/AsyncGenerator/AsyncGenerator.prototype.next.js
  Userland/Libraries/LibJS/Tests/syntax/async-await.js
Labels: 👀 pr-needs-review

#20469 LibWeb: Check paintable of target against null in mousewheel handling
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
Labels: 👀 pr-needs-review

#20466 LibWeb: Verify that table cells have a paintable when collecting them
  Tests/LibWeb/Layout/expected/table/table-cell-not-paintable.txt
  Tests/LibWeb/Layout/input/table/table-cell-not-paintable.html
  Userland/Libraries/LibWeb/Painting/TableBordersPainting.cpp
Labels: 👀 pr-needs-review

#20464 LibWeb: Support skew{X,Y} in stacking context transforms
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Labels: 👀 pr-needs-review

#20321 FileManager: Add "Copy Path" action to the context menus
  Userland/Applications/FileManager/main.cpp
Labels: 👀 pr-needs-review

#20474 LibWeb: Stub out SVGMaskElement
  Tests/LibWeb/Layout/expected/svg/mask-element-should-not-participate-in-layout.txt
  Tests/LibWeb/Layout/input/svg/mask-element-should-not-participate-in-layout.html
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/DOM/ElementFactory.cpp
  Userland/Libraries/LibWeb/Forward.h
  Userland/Libraries/LibWeb/SVG/SVGMaskElement.cpp
  Userland/Libraries/LibWeb/SVG/SVGMaskElement.h
  Userland/Libraries/LibWeb/SVG/SVGMaskElement.idl
  Userland/Libraries/LibWeb/SVG/TagNames.h
  Userland/Libraries/LibWeb/idl_files.cmake
Labels: 👀 pr-needs-review

#20480 LibGfx/JPEGXL: Add support for LZ77 encoded streams
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Labels: 👀 pr-needs-review

#20470 Documentation: Update Ports package.sh example to use single quotes
  Ports/README.md
Labels: 👀 pr-needs-review

#20475 Toolchain: Add (basic) support for riscv64
  Kernel/Arch/mcontext.h
  Kernel/Arch/riscv64/mcontext.h
  Toolchain/Patches/binutils/0001-Add-support-for-SerenityOS.patch
  Toolchain/Patches/gcc/0001-Add-a-gcc-driver-for-SerenityOS.patch
  Toolchain/Patches/gcc/0003-libgcc-Build-for-SerenityOS.patch
Labels: 👀 pr-needs-review

#20485 Ports: Fix `clean_dist` function in .port_include.sh
  Ports/.port_include.sh
Labels: 👀 pr-needs-review

#20473 LibWeb: Fix buttons with TextNode label
  Tests/LibWeb/Layout/expected/block-and-inline/button-should-have-vertically-aligned-content.txt
  Tests/LibWeb/Layout/expected/block-and-inline/button-with-multiple-words-text-node-label.txt
  Tests/LibWeb/Layout/expected/block-and-inline/button-with-text-node-label.txt
  Tests/LibWeb/Layout/expected/table/table-cell-not-paintable.txt
  Tests/LibWeb/Layout/input/block-and-inline/button-with-multiple-words-text-node-label.html
  Tests/LibWeb/Layout/input/block-and-inline/button-with-text-node-label.html
  Tests/LibWeb/Layout/input/table/table-cell-not-paintable.html
  Userland/Libraries/LibWeb/Layout/Node.h
  Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Labels: 👀 pr-needs-review

#20486 LibGfx/JPEGXL: Support images encoded with the YCbCr color space
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#20489 LibWeb: Remove 3 decimal places rounding hack in Length::percentage_of
  Tests/LibWeb/Layout/expected/grid/min-max-content.txt
  Userland/Libraries/LibWeb/CSS/Length.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#20477 Ports: Add xorriso port
  Ports/AvailablePorts.md
  Ports/xorriso/package.sh
  Ports/xorriso/patches/0001-parse_exec-replace-wait3-with-waitpid.patch
  Ports/xorriso/patches/ReadMe.md
Labels: 👀 pr-needs-review

#20495 Ports/tree: Update to version 2.1.1
  Ports/AvailablePorts.md
  Ports/tree/package.sh
Labels: 👀 pr-needs-review

#20437 Base: Document IPC syntax formally and informally
  Base/usr/share/man/man5/ipc.md
Labels: 👀 pr-needs-review

#20491 Shell: Add builtin command to reset the internal state
  Userland/Shell/Builtin.cpp
  Userland/Shell/Shell.cpp
  Userland/Shell/Shell.h
Labels: 👀 pr-needs-review

#20497 LibWeb: Use available space to resolve table container width
  Tests/LibWeb/Layout/expected/table/columns-width-distribution-1.txt
  Tests/LibWeb/Layout/expected/table/infinite-padding.txt
  Tests/LibWeb/Layout/input/table/infinite-padding.html
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/LayoutState.cpp
  Userland/Libraries/LibWeb/Layout/LayoutState.h
  Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Labels: 👀 pr-needs-review

#20412 Ports: Improve build_all.sh script
  Ports/build_all.sh
Labels: 👀 pr-needs-review

#20499 LibGfx/JPEGXL: Remove unused variables in `JPEGXLLoadingContext`
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Labels: 👀 pr-needs-review

#20504 Ports/mgba: Explicitly exclude optional dependencies
  Ports/mgba/package.sh
Labels: 👀 pr-needs-review

#20490 Kernel+LibC: Pass 64-bit integers in syscalls by value
  Kernel/Syscalls/fallocate.cpp
  Kernel/Syscalls/ftruncate.cpp
  Kernel/Syscalls/profiling.cpp
  Kernel/Syscalls/read.cpp
  Kernel/Syscalls/write.cpp
  Kernel/Tasks/Process.h
  Userland/DevTools/UserspaceEmulator/Emulator.h
  Userland/DevTools/UserspaceEmulator/Emulator_syscalls.cpp
  Userland/Libraries/LibC/fcntl.cpp
  Userland/Libraries/LibC/serenity.cpp
  Userland/Libraries/LibC/sys/uio.cpp
  Userland/Libraries/LibC/unistd.cpp
Labels: 👀 pr-needs-review

#20502 Ports/poppler: Explicitly exclude optional dependencies
  Ports/poppler/package.sh
Labels: 👀 pr-needs-review

#20355 Utilities: Fix title formatting in `man`
  Userland/Utilities/man.cpp
Labels: 👀 pr-needs-review

#20508 Ports/cpio: Update to version 2.14
  Ports/AvailablePorts.md
  Ports/cpio/package.sh
  Ports/cpio/patches/0001-Use-global-program_name-variable-from-gnu-dir.patch
  Ports/cpio/patches/ReadMe.md
Labels: 👀 pr-needs-review

#20509 Ladybird: Install an impl library for WebContent when ENABLE_QT=OFF
  Ladybird/WebContent/CMakeLists.txt
  Ladybird/cmake/InstallRules.cmake
Labels: 👀 pr-needs-review

#20507 CMake: Set `-fvisibility-inlines-hidden` on ELF platforms
  Meta/CMake/common_compile_options.cmake
  Meta/CMake/lagom_compile_options.cmake
  Meta/CMake/serenity_compile_options.cmake
Labels: 👀 pr-needs-review

#20505 LibGfx/JPEGXL: Support cropped images
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Labels: 👀 pr-needs-review

#20512 LibWeb: Remove unused computed values for removed button flow-root
  Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Labels: 👀 pr-needs-review

#20484 Kernel: Add PCISerialDevice WCH CH351 IDs
  Kernel/Devices/PCISerialDevice.h
Labels: 👀 pr-needs-review

#20515 LibWeb: Copy button style properties for generated table and cell
  Tests/LibWeb/Layout/expected/block-and-inline/button-with-text-node-label-and-font-size.txt
  Tests/LibWeb/Layout/input/block-and-inline/button-with-text-node-label-and-font-size.html
  Userland/Libraries/LibWeb/Layout/Node.h
  Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Labels: 👀 pr-needs-review

#20514 Ports/wayland: Add `libffi` dependency
  Ports/wayland/package.sh
Labels: 👀 pr-needs-review

#20444 Ports: Add Julius
  Ports/AvailablePorts.md
  Ports/julius/package.sh
  Ports/julius/patches/0001-Skip-including-execinfo.h-for-Serenity.patch
  Ports/julius/patches/ReadMe.md
Labels: 👀 pr-needs-review

#20494 Ports/tar: Update to version 1.35
  Ports/AvailablePorts.md
  Ports/tar/package.sh
  Ports/tar/patches/0001-Fix-savannah-bug-64441.patch
  Ports/tar/patches/ReadMe.md
Labels: 👀 pr-needs-review

#20520 LibWeb: Forbid usage of indefinite width in calculate_min{max}_height
  Tests/LibWeb/Layout/expected/table/inline-table-width.txt
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/FormattingContext.h
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/LayoutState.h
  Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Labels: 👀 pr-needs-review

#20525 LibWeb: Fetch CSS @font-face fonts in @import'ed style sheets
  Userland/Libraries/LibWeb/CSS/CSSImportRule.cpp
Labels: 👀 pr-needs-review

#20526 Meta: Fix ENABLE_LAGOM_LIBWEB CMake configuration
  Meta/Lagom/CMakeLists.txt
Labels: 👀 pr-needs-review

#20500 Documentation: Update the kernel development guide on FixedStringBuffer
  Documentation/Kernel/DevelopmentGuidelines.md
Labels: 👀 pr-needs-review

#20527 Ports: Add groff
  Ports/AvailablePorts.md
  Ports/groff/package.sh
  Ports/groff/patches/0001-Include-config.h-in-math.h.patch
  Ports/groff/patches/0002-Don-t-redeclare-signbit-function.patch
  Ports/groff/patches/ReadMe.md
Labels: 👀 pr-needs-review

#20539 LibGUI: Fix typo
  Userland/Libraries/LibGUI/Splitter.cpp
  Userland/Libraries/LibGUI/Splitter.h
Labels: 👀 pr-needs-review

#20530 LibWeb: Use current platform for navigator.platform
  Userland/Libraries/LibWeb/HTML/NavigatorID.cpp
  Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
  Userland/Libraries/LibWeb/Loader/ResourceLoader.h
Labels: 👀 pr-needs-review

#20531 Utilities: Add zcat
  Userland/Utilities/CMakeLists.txt
  Userland/Utilities/gunzip.cpp
Labels: 👀 pr-needs-review

#20549 LibWeb: Add hack for computing the request referer during load
  Userland/Libraries/LibWeb/Loader/FrameLoader.cpp
Labels: 👀 pr-needs-review

#20540 LibWeb: Fix handling of max-content containing block for floating box
  Tests/LibWeb/Layout/expected/block-and-inline/float-max-content-containing-block-flex-display.txt
  Tests/LibWeb/Layout/expected/block-and-inline/float-max-content-containing-block.txt
  Tests/LibWeb/Layout/input/block-and-inline/float-max-content-containing-block-flex-display.html
  Tests/LibWeb/Layout/input/block-and-inline/float-max-content-containing-block.html
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Labels: 👀 pr-needs-review

#19846 Ladybird: add initial page to history
  Ladybird/Qt/BrowserWindow.cpp
Labels: 👀 pr-needs-review, ⚠️ pr-has-conflicts

#20548 LibJS: Mark classes and virtual functions `final` where possible
  Userland/Libraries/LibJS/AST.h
  Userland/Libraries/LibJS/CyclicModule.h
  Userland/Libraries/LibJS/Heap/Cell.h
  Userland/Libraries/LibJS/Heap/MarkedVector.h
  Userland/Libraries/LibJS/Runtime/Array.h
  Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.h
  Userland/Libraries/LibJS/Runtime/Environment.h
  Userland/Libraries/LibJS/Runtime/Object.h
  Userland/Libraries/LibJS/Runtime/ObjectEnvironment.h
Labels: 👀 pr-needs-review

#20547 Ports: Update serenity-theming use latest commit 7ef303d
  Ports/AvailablePorts.md
  Ports/serenity-theming/package.sh
Labels: 👀 pr-needs-review

#20563 Calendar: Promote view_type ActionGroup to CalendarWidget's member
  Userland/Applications/Calendar/CalendarWidget.cpp
  Userland/Applications/Calendar/CalendarWidget.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci
