Repository SerenityOS/serenity, pull requests merged in 2023-04, with the labels that each got.

#18125 LibWeb: Don't churn HTML::EventLoop while in microtask checkpoint
  Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
Labels: 👀 pr-needs-review

#18129 LibCompress: Reduce indentation in CompressedBlock::try_read_more()
  Userland/Libraries/LibCompress/Deflate.cpp
Labels: 👀 pr-needs-review

#18126 LibCompress: Implement block size validation for XZ streams
  Tests/LibCompress/TestXz.cpp
  Userland/Libraries/LibCompress/Xz.cpp
  Userland/Libraries/LibCompress/Xz.h
Labels: 👀 pr-needs-review

#18117 Meta: Install PCI and USB ID files directly into /res
  CMakeLists.txt
Labels: 👀 pr-needs-review

#18142 LibCompress: Make CanonicalCode::from_bytes() return ErrorOr<>
  Userland/Libraries/LibCompress/Deflate.cpp
  Userland/Libraries/LibCompress/Deflate.h
Labels: 👀 pr-needs-review

#18136 LibJS: Fix parsing of mixed `CoalesceExpression` and `Logical{AND,OR}Expression`
  Userland/Libraries/LibJS/Parser.cpp
  Userland/Libraries/LibJS/Tests/syntax/coalesce-logic-expression-mixing.js
Labels: 👀 pr-needs-review

#18090 Toolchain: Create an `nm` symlink for Clang
  Toolchain/BuildClang.sh
Labels: ✅ pr-community-approved

#18124 Toolchain: Update GDB to 13.1 and enable builds with clang > 15
  Toolchain/BuildIt.sh
  Toolchain/Patches/gdb/clang-constexpr-conversion-warning.patch
  Toolchain/Patches/gdb/gdb.patch
Labels: 👀 pr-needs-review

#18138 AK: Increase LittleEndianOutputBitStream's buffer size and remove loops
  AK/BitStream.h
  Tests/AK/TestBitStream.cpp
  Userland/Libraries/LibCompress/Deflate.cpp
Labels: 👀 pr-needs-review

#18135 Meta: Make the gdb kernel debug script work for AArch64
  Meta/debug-kernel.sh
Labels: 👀 pr-needs-review

#18156 ImageViewer: Fix crash when setting wallpaper
  Userland/Applications/ImageViewer/main.cpp
Labels: ✅ pr-community-approved

#18147 PixelPaint: Make Bloom use InplaceFilter instead of Filter
  Userland/Applications/PixelPaint/Filters/Bloom.cpp
  Userland/Applications/PixelPaint/Filters/Bloom.h
Labels: 👀 pr-needs-review

#18123 PixelPaint: Update recent files list on project save
  Userland/Applications/PixelPaint/MainWidget.cpp
Labels: 👀 pr-needs-review

#17786 LibGfx/JPEG: Support for images with four components
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Labels: ✅ pr-community-approved

#18145 Toolchain+Meta: Support kernel debugging with host AArch64 GDB
  Meta/debug-kernel.sh
  Toolchain/BuildIt.sh
Labels: 👀 pr-needs-review

#18170 Kernel/aarch64: Implement `Processor::time_spent_idle()`
  Kernel/Arch/aarch64/Processor.cpp
  Kernel/Arch/aarch64/Processor.h
Labels: 👀 pr-needs-review

#18179 Two minor behavior-preserving cleanups to the deflate code
  Userland/Libraries/LibCompress/Deflate.cpp
Labels: 👀 pr-needs-review

#18173 LibWeb: Use intrinsic aspect ratio when calculating max content height
  Tests/LibWeb/Layout/expected/flex-item-on-row-with-intrinsic-aspect-ratio.txt
  Tests/LibWeb/Layout/input/flex-item-on-row-with-intrinsic-aspect-ratio.html
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Labels: 👀 pr-needs-review

#18192 webp lossless: Some preparations for handling transforms and entropy image
  Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
Labels: 👀 pr-needs-review

#18189 GMLPlayground: Fix crash when previewing `@GUI::Calendar`
  Userland/DevTools/GMLPlayground/main.cpp
Labels: 👀 pr-needs-review

#18198 LibGfx: Fix out of bounds read in BitmapFont::masked_character_set()
  Userland/Libraries/LibGfx/Font/BitmapFont.cpp
Labels: 👀 pr-needs-review

#18128 HackStudio: Add configuration domain pledge for FileManager
  Userland/DevTools/HackStudio/main.cpp
Labels: 👀 pr-needs-review

#18077 LibGfx/JPEG: Reduce memory usage by almost 50% :^)
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Labels: 👀 pr-needs-review

#18201 LibEDID: Fix compiler error when ENABLE_PNP_IDS_DOWNLOAD=OFF
  Userland/Libraries/LibEDID/EDID.cpp
Labels: 👀 pr-needs-review

#18206 LibWeb: Transform the default path in CRC2D#fill(CanvasFillRule)
  Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
Labels: 👀 pr-needs-review

#18211 Kernel/aarch64: Actually remove Arch/aarch64/init.cpp
  Kernel/Arch/aarch64/init.cpp
Labels: 👀 pr-needs-review

#18205 Progress towards decoding Tests/LibGfx/test-inputs/simple-vp8l.webp
  Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
Labels: 👀 pr-needs-review

#18208 LibWeb: Don't put abspos grid/flex items in anonymous wrapper
  Tests/LibWeb/Layout/expected/flex-abspos-item-with-preceding-whitespace.txt
  Tests/LibWeb/Layout/input/flex-abspos-item-with-preceding-whitespace.html
  Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Labels: 👀 pr-needs-review

#18214 Kernel: Fix typo in the FramebufferGetPitchMboxMessage name
  Kernel/Arch/aarch64/RPi/Framebuffer.cpp
  Kernel/Arch/aarch64/RPi/FramebufferMailboxMessages.h
Labels: 👀 pr-needs-review

#18194 LibJS: Update spec numbers for the Intl Enumeration proposal
  Userland/Libraries/LibJS/Runtime/Intl/Intl.cpp
Labels: 👀 pr-needs-review

#18207 LibTimeZone: Update to TZDB version 2023c
  Meta/CMake/time_zone_data.cmake
Labels: ✅ pr-community-approved

#18168 Ports: Add stockfish port
  Ports/AvailablePorts.md
  Ports/stockfish/package.sh
Labels: ✅ pr-community-approved

#18227 AK: Bake CLion IDE check into AK_COMPILER_CLANG
  AK/CheckedFormatString.h
  AK/Platform.h
  AK/StdLibExtras.h
Labels: 👀 pr-needs-review

#18217 Kernel: Mark a bunch of NonnullRefPtrs also const to ensure immutability
  Kernel/Bus/PCI/Device.h
  Kernel/Coredump.h
  Kernel/FileSystem/Custody.h
  Kernel/FileSystem/FileBackedFileSystem.h
  Kernel/FileSystem/InodeFile.h
  Kernel/FileSystem/OpenFileDescription.h
  Kernel/FileSystem/SysFS/Subsystems/Bus/PCI/DeviceDirectory.h
  Kernel/Jail.h
  Kernel/Memory/InodeVMObject.h
  Kernel/Storage/ATA/AHCI/Port.h
  Kernel/Storage/NVMe/NVMeQueue.h
Labels: 👀 pr-needs-review

#18232 Ports: Update file to version 5.44
  Ports/AvailablePorts.md
  Ports/file/package.sh
Labels: 👀 pr-needs-review

#18229 Ports: Update dtc to version 1.7.0
  Ports/AvailablePorts.md
  Ports/dtc/package.sh
Labels: 👀 pr-needs-review

#18228 Ports: Update dmidecode to version 3.5
  Ports/AvailablePorts.md
  Ports/dmidecode/package.sh
Labels: 👀 pr-needs-review

#18237 LibGfx: Make webp lossless decoder 6 times as fast
  Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
Labels: 👀 pr-needs-review

#18222 Fuzzers: Add a WebP fuzzer
  Meta/Lagom/Fuzzers/CMakeLists.txt
  Meta/Lagom/Fuzzers/FuzzWebPLoader.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#18240 LibGfx: Give PrefixCodeGroup a deleted copy ctor
  Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
Labels: 👀 pr-needs-review

#18242 Toolchain: Stop building QEMU with i386 support
  Toolchain/BuildQemu.sh
Labels: 👀 pr-needs-review

#18241 Ports: Repair qt6-qtbase by disabling QDnsLookup
  Ports/qt6-qtbase/patches/0001-Add-a-SerenityOS-platform-definition.patch
  Ports/qt6-qtbase/patches/0002-Disable-shared-memory-and-semaphores.patch
  Ports/qt6-qtbase/patches/0007-Disable-QDnsLookup-entirely.patch
  Ports/qt6-qtbase/patches/ReadMe.md
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#18243 LibGfx: Correctly decode webp lossless with small palette and odd width
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/width11-height11-colors15.webp
  Tests/LibGfx/test-inputs/width11-height11-colors2.webp
  Tests/LibGfx/test-inputs/width11-height11-colors3.webp
  Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
Labels: 👀 pr-needs-review

#18193 LibCompress: Reorganize and const-correct the XZ decompressor
  Userland/Libraries/LibCompress/Xz.cpp
  Userland/Libraries/LibCompress/Xz.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#18239 Documentation+Ports: Be upfront about dependencies
  Documentation/BuildInstructions.md
Labels: 👀 pr-needs-review

#18236 BrickGame: Optionally show brick shadow hints
  Userland/Games/BrickGame/BrickGame.cpp
  Userland/Games/BrickGame/BrickGame.h
  Userland/Games/BrickGame/main.cpp
Labels: 👀 pr-needs-review

#18246 Ports: Reapply the SDL2_sound patch
  Ports/SDL2_sound/patches/0001-Use-pkgconfig-to-find-SDL2.patch
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#18247 Kernel: Fix compilation of aarch64/RPi/Framebuffer.cpp
  Kernel/Arch/aarch64/RPi/Framebuffer.cpp
Labels: 👀 pr-needs-review

#18249 Meta: Run the QEMU ISA-PC machine with a 64-bit capable CPU
  Meta/run.sh
Labels: 👀 pr-needs-review

#18254 Ports: Remove abandoned port 'fheroes2' which was never playable
  Ports/AvailablePorts.md
  Ports/fheroes2/package.sh
  Ports/fheroes2/patches/0001-Include-endian.h-on-serenity-as-well.patch
  Ports/fheroes2/patches/0002-Use-pkg-config-for-SDL_-and-SDL2.patch
  Ports/fheroes2/patches/0003-Disable-SDL-s-accelerated-rendering.patch
  Ports/fheroes2/patches/ReadMe.md
Labels: 👀 pr-needs-review

#18261 LibGfx: Remove some of the noisier logging from webp lossless decoder
  Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
Labels: 👀 pr-needs-review

#18260 LibGfx: Limit ICC-size-is-multiple-of-4 check to v4 files
  Userland/Libraries/LibGfx/ICC/Profile.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#18257 Ports: Repair the launcher icons of 'stpuzzles'
  Ports/stpuzzles/package.sh
Labels: 👀 pr-needs-review

#18256 Meta+Toolchain: Fix up detection of already installed compatible GDBs
  Meta/debug-kernel.sh
  Toolchain/BuildIt.sh
Labels: 👀 pr-needs-review

#18223 LibWeb: Add the WritableStreamDefaultController
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/Forward.h
  Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
  Userland/Libraries/LibWeb/Streams/AbstractOperations.h
  Userland/Libraries/LibWeb/Streams/WritableStream.cpp
  Userland/Libraries/LibWeb/Streams/WritableStream.h
  Userland/Libraries/LibWeb/Streams/WritableStreamDefaultController.cpp
  Userland/Libraries/LibWeb/Streams/WritableStreamDefaultController.h
  Userland/Libraries/LibWeb/Streams/WritableStreamDefaultController.idl
  Userland/Libraries/LibWeb/Streams/WritableStreamDefaultWriter.h
Labels: 👀 pr-needs-review

#18263 LibWeb: Implement WritableStream.close()
  Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
  Userland/Libraries/LibWeb/Streams/AbstractOperations.h
  Userland/Libraries/LibWeb/Streams/WritableStream.cpp
  Userland/Libraries/LibWeb/Streams/WritableStream.h
  Userland/Libraries/LibWeb/Streams/WritableStream.idl
Labels: 👀 pr-needs-review

#18199 Kernel: Ensure jailed processes can be reaped by a jailed parent process
  Kernel/Process.cpp
  Kernel/Process.h
Labels: 👀 pr-needs-review

#18253 Ports: Make libksba/libassuan/ntbtls use Serenity's gpg-error-config
  Ports/gnupg/patches/0001-Link-against-libiconv.patch
  Ports/gnupg/patches/ReadMe.md
  Ports/libassuan/package.sh
  Ports/libksba/package.sh
  Ports/ntbtls/package.sh
Labels: 👀 pr-needs-review

#18248 LibWeb/Fetch: Use a basic filtered response for redirect navigations
  Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
Labels: 👀 pr-needs-review

#18191 LibCrypto: Add PBKDF2
  Tests/LibCrypto/CMakeLists.txt
  Tests/LibCrypto/TestPBKDF2.cpp
  Userland/Libraries/LibCrypto/Hash/PBKDF2.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17861 DisplaySettings: Use FileSystemAccessServer instead of FilePicker
  Userland/Applications/DisplaySettings/BackgroundSettingsWidget.cpp
  Userland/Applications/DisplaySettings/CMakeLists.txt
Labels: 👀 pr-needs-review

#18184 Kernel/Memory: Explain better why we dont use the first 1 MiB on x86_64
  Kernel/Memory/MemoryManager.cpp
Labels: 👀 pr-needs-review

#18096 Browser: Have `BookmarksBarWidget` signal bookmark changes for `Tab`
  Userland/Applications/Browser/BookmarksBarWidget.cpp
  Userland/Applications/Browser/BookmarksBarWidget.h
  Userland/Applications/Browser/Tab.cpp
Labels: 👀 pr-needs-review

#18270 LibWeb: Convert video control dimensions from CSSPixels to DevicePixels
  Userland/Libraries/LibWeb/Painting/VideoPaintable.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#18268 Ports/lrzip: Switch to the actual preconfigured release tarball
  Ports/lrzip/package.sh
Labels: 👀 pr-needs-review

#18202 SystemMonitor: Handle zombie processes properly
  Userland/Applications/SystemMonitor/ProcessModel.cpp
Labels: 👀 pr-needs-review

#18272 Tests+LibTLS: Use `TRY_OR_FAIL` for TestTLSHandshake
  Tests/LibTLS/TestTLSHandshake.cpp
Labels: 👀 pr-needs-review

#18210 Toolchain+Meta: Only build GDB when the user asks for it + fix #18145
  Meta/debug-kernel.sh
  Toolchain/BuildGDB.sh
  Toolchain/BuildIt.sh
Labels: 👀 pr-needs-review

#18285 readelf: Pledge `map_fixed` for loading ELFs
  Userland/Utilities/readelf.cpp
Labels: 👀 pr-needs-review

#18158 Lagom: Tmux is not needed for lagom gdb
  Meta/serenity.sh
Labels: 👀 pr-needs-review

#18224 LibWeb: Return from "the end" during HTML fragment parsing
  Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Labels: 👀 pr-needs-review

#18293 LibWeb: Handle null values when making args for attributeChangedCallback
  Userland/Libraries/LibWeb/DOM/Attr.cpp
Labels: 👀 pr-needs-review

#18299 LibVideo: Don't shadow m_playing in ResumingStateHandler classes
  Userland/Libraries/LibVideo/PlaybackManager.cpp
Labels: 👀 pr-needs-review

#18294 LibTLS: Dont also include the OID when printing the RDN short name
  Userland/Libraries/LibTLS/Certificate.cpp
Labels: 👀 pr-needs-review

#18308 Shell: Add `map_fixed` to the pledges for command autocompletion
  Userland/Shell/Shell.cpp
Labels: 👀 pr-needs-review

#18112 Documentation: Remove explaination for why we don't support 32 bit CPUs
  Documentation/FAQ.md
Labels: 👀 pr-needs-review

#18330 LibGfx/WebP: Don't assert when size in header is smaller than header
  Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
Labels: 👀 pr-needs-review

#18333 Everywhere: Fix a few typos
  AK/ByteBuffer.h
  AK/FixedPoint.h
  Documentation/Links.md
  Userland/Libraries/LibGfx/GradientPainting.cpp
  Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
  Userland/Libraries/LibPDF/Fonts/CFF.cpp
  Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
  Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
  Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.h
  Userland/Utilities/sed.cpp
Labels: 👀 pr-needs-review

#18326 LibCompress: Error on truncated uncompressed DEFLATE blocks
  Tests/LibCompress/TestGzip.cpp
  Userland/Libraries/LibCompress/Deflate.cpp
Labels: 👀 pr-needs-review

#18327 LibAudio: Use `read_until_filled` to fill a buffer from a Stream
  Userland/Libraries/LibAudio/FlacLoader.cpp
Labels: 👀 pr-needs-review

#18328 Fuzzers: Stop loading audio frames once the end is reached
  Meta/Lagom/Fuzzers/FuzzFlacLoader.cpp
  Meta/Lagom/Fuzzers/FuzzMP3Loader.cpp
  Meta/Lagom/Fuzzers/FuzzQOALoader.cpp
  Meta/Lagom/Fuzzers/FuzzWAVLoader.cpp
Labels: 👀 pr-needs-review

#18338 Base: Add a 32px icon for CertificateSettings
  Base/res/icons/32x32/certificate.png
Labels: 👀 pr-needs-review

#18334 HackStudio: set_cursor even if the file is already open
  Userland/DevTools/HackStudio/HackStudioWidget.cpp
Labels: 👀 pr-needs-review

#18349 LibWeb: Don't match the root node of HTMLCollection
  Userland/Libraries/LibWeb/DOM/HTMLCollection.cpp
Labels: 👀 pr-needs-review

#18355 Base: Add US English Apple Macintosh keymap
  Base/res/keymaps/en-us-macintosh.json
Labels: 👀 pr-needs-review

#18362 LibWeb: Set Comment's prototype
  Userland/Libraries/LibWeb/DOM/Comment.cpp
  Userland/Libraries/LibWeb/DOM/Comment.h
Labels: 👀 pr-needs-review

#18353 LibRegex: Avoid calling GenericLexer::consume() past EOF
  Tests/LibRegex/Regex.cpp
  Userland/Libraries/LibRegex/RegexParser.cpp
Labels: 👀 pr-needs-review

#18357 TestVP9Decode: Dequeue frames from the decoder after sending a sample
  Tests/LibVideo/TestVP9Decode.cpp
Labels: 👀 pr-needs-review

#18348 SoundPlayer: Check if loader is null
  Userland/Applications/SoundPlayer/Player.cpp
Labels: 👀 pr-needs-review

#18363 LibWeb: Honor column-gap and row-gap CSS properties in flex layout
  Tests/LibWeb/Layout/expected/flex/flex-gap-between-items-and-lines.txt
  Tests/LibWeb/Layout/input/flex/flex-gap-between-items-and-lines.html
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
Labels: 👀 pr-needs-review

#17945 WindowServer: Fix alt shortcut navigation for non-default keymaps
  Userland/Services/WindowServer/CMakeLists.txt
  Userland/Services/WindowServer/Window.cpp
  Userland/Services/WindowServer/main.cpp
Labels: stale, 👀 pr-needs-review

#18172 LibWeb: Resolve more background-related properties
  Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
Labels: 👀 pr-needs-review

#18358 PixelPaint: Correct gradient tool's position during preview
  Userland/Applications/PixelPaint/Tools/GradientTool.cpp
Labels: 👀 pr-needs-review

#18368 AK: Make math work on arm hosts again
  AK/Math.h
Labels: 👀 pr-needs-review, ✅ pr-community-approved

#18332 LibMarkdown: Avoid catastrophic backtracking in thematic break regex
  Userland/Libraries/LibMarkdown/HorizontalRule.cpp
Labels: 👀 pr-needs-review

#18376 Documentation: Add build dependencies for SerenityOS :^)
  Documentation/BuildInstructions.md
Labels: 👀 pr-needs-review

#18373 AK: Remove workaround for old macOS SDK
  AK/Platform.h
Labels: 👀 pr-needs-review

#18275 Kernel: Stop using LockRefPtrs in the Jail code
  Kernel/Jail.cpp
  Kernel/Jail.h
Labels: 👀 pr-needs-review

#18352 Base: Complete Mathematical Operators in Katica Regular 10
  Base/res/fonts/KaticaRegular10.font
Labels: ✅ pr-community-approved

#18377 Ports/openrtc2: Update OpenRTC2 to version 0.4.4
  Ports/AvailablePorts.md
  Ports/openrct2/package.sh
Labels: 👀 pr-needs-review

#18375 Tests: Add a test for LZMA repetition lengths beyond the distance
  Tests/LibCompress/TestLzma.cpp
Labels: 👀 pr-needs-review

#18383 Ladybird+LibWebView: Add -P/--enable-callgrind-profiling option
  Ladybird/BrowserWindow.cpp
  Ladybird/BrowserWindow.h
  Ladybird/Tab.cpp
  Ladybird/Tab.h
  Ladybird/WebContentView.cpp
  Ladybird/WebContentView.h
  Ladybird/main.cpp
  Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
  Userland/Libraries/LibWebView/OutOfProcessWebView.h
  Userland/Libraries/LibWebView/ViewImplementation.cpp
  Userland/Libraries/LibWebView/ViewImplementation.h
  Userland/Utilities/headless-browser.cpp
Labels: 👀 pr-needs-review

#18335 LibTLS: Replace CertificateKeyAlgorithm enum with a AlgorithmIdentifier struct
  Userland/Libraries/LibCrypto/Hash/HashManager.h
  Userland/Libraries/LibTLS/Certificate.cpp
  Userland/Libraries/LibTLS/Certificate.h
  Userland/Libraries/LibTLS/TLSv12.cpp
Labels: 👀 pr-needs-review

#18274 Kernel: Disable interrupt signaling for the SD driver
  Kernel/Storage/SD/SDHostController.cpp
Labels: 👀 pr-needs-review

#18385 LibC: Avoid UB in strdup()/strndup()
  Userland/Libraries/LibC/string.cpp
Labels: 👀 pr-needs-review

#18388 LibWeb: Scale SVG stroke-width based on viewbox
  Tests/LibWeb/Layout/expected/svg-transforms-and-viewboxes.txt
  Userland/Libraries/LibWeb/Layout/SVGFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/SVGGeometryBox.cpp
  Userland/Libraries/LibWeb/Painting/SVGGeometryPaintable.cpp
  Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.h
Labels: 👀 pr-needs-review

#18392 Meta: Allow overriding the calculated disk image inode count
  Meta/build-image-qemu.sh
Labels: 👀 pr-needs-review

#18395 Ports: Update GLib to 2.76.1
  Ports/AvailablePorts.md
  Ports/glib/package.sh
Labels: 👀 pr-needs-review

#18400 LibWeb: Honor gap between flex lines when using align-content: stretch
  Tests/LibWeb/Layout/expected/flex/stretch-alignment-with-cross-gap.txt
  Tests/LibWeb/Layout/input/flex/stretch-alignment-with-cross-gap.html
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Labels: 👀 pr-needs-review

#18403 LibWeb: Fix multi-line flex column layouts with auto height on container
  Tests/LibWeb/Layout/expected/flex/multi-line-column-container-with-automatic-height.txt
  Tests/LibWeb/Layout/input/flex/multi-line-column-container-with-automatic-height.html
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Labels: 👀 pr-needs-review

#18393 Meta: Move some flags to common_compile_options.cmake
  Meta/CMake/common_compile_options.cmake
  Meta/CMake/lagom_compile_options.cmake
  Meta/CMake/serenity_compile_options.cmake
Labels: 👀 pr-needs-review

#18404 FileManager+LibGUI: Cache the FileSystem::can_delete_or_move value
  Userland/Applications/FileManager/DirectoryView.cpp
  Userland/Libraries/LibGUI/FileSystemModel.cpp
  Userland/Libraries/LibGUI/FileSystemModel.h
Labels: 👀 pr-needs-review

#18411 LibWeb: Support implicit lineto commands after moveto in SVG paths
  Tests/LibWeb/Layout/expected/svg/svg-path-with-implicit-lineto.txt
  Tests/LibWeb/Layout/input/svg/svg-path-with-implicit-lineto.html
  Userland/Libraries/LibWeb/SVG/AttributeParser.cpp
Labels: 👀 pr-needs-review

#18414 LibWeb: Honor box-sizing in flex item "specified size suggestion"
  Tests/LibWeb/Layout/expected/flex/specified-size-suggestion-with-box-sizing-border-box.txt
  Tests/LibWeb/Layout/input/flex/specified-size-suggestion-with-box-sizing-border-box.html
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Labels: 👀 pr-needs-review

#18412 ldd: Pledge map_fixed
  Userland/Utilities/ldd.cpp
Labels: 👀 pr-needs-review

#18418 Meta: Move more common flags to common_compile_options.cmake
  Meta/CMake/common_compile_options.cmake
  Meta/CMake/lagom_compile_options.cmake
  Meta/CMake/serenity_compile_options.cmake
  Meta/Lagom/CMakeLists.txt
Labels: 👀 pr-needs-review

#18421 LibWeb: Treat unresolvable percentage flex-basis values as 'content'
  Tests/LibWeb/Layout/expected/flex/percentage-flex-basis-with-indefinite-flex-container-size.txt
  Tests/LibWeb/Layout/input/flex/percentage-flex-basis-with-indefinite-flex-container-size.html
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Labels: 👀 pr-needs-review

#18427 Ports: Resolve some patch-related footguns
  Ports/.port_include.sh
Labels: 👀 pr-needs-review

#18428 LibWeb: Fix broken handling of `flex: <flex-grow>` shorthand
  Tests/LibWeb/Layout/expected/flex-grow-2.txt
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#18443 LibWeb/WebDriver: Handle WindowProxy in internal_json_clone_algorithm()
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/HTML/WindowProxy.cpp
  Userland/Libraries/LibWeb/HTML/WindowProxy.h
  Userland/Libraries/LibWeb/WebDriver/Contexts.cpp
  Userland/Libraries/LibWeb/WebDriver/Contexts.h
  Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
  Userland/Libraries/LibWeb/WebDriver/ExecuteScript.h
  Userland/Services/WebContent/WebDriverConnection.cpp
Labels: 👀 pr-needs-review

#18435 LibWeb: Use device pixels to translate NestedBrowsingContextPaintable
  Userland/Libraries/LibWeb/Painting/NestedBrowsingContextPaintable.cpp
Labels: 👀 pr-needs-review

#18447 Spider: Fix crash when completing a deck
  Userland/Games/Spider/Game.cpp
Labels: 👀 pr-needs-review

#18449 Kernel+Userland: Remove the `nfds` entry from `/sys/kernel/processes`
  Kernel/FileSystem/SysFS/Subsystems/Kernel/Processes.cpp
  Userland/Libraries/LibCore/ProcessStatisticsReader.cpp
  Userland/Libraries/LibCore/ProcessStatisticsReader.h
  Userland/Utilities/top.cpp
Labels: 👀 pr-needs-review

#18453 LibGfx: Move two globals into the only functions that use them
  Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.cpp
Labels: 👀 pr-needs-review

#18450 AK: Fix crash during teardown of self-owning ref-counted objects
  AK/NonnullOwnPtr.h
  AK/NonnullRefPtr.h
  AK/OwnPtr.h
  AK/RefPtr.h
  Tests/AK/CMakeLists.txt
  Tests/AK/TestIntrusiveList.cpp
  Tests/AK/TestNonnullOwnPtr.cpp
  Tests/AK/TestNonnullRefPtr.cpp
  Tests/AK/TestOwnPtr.cpp
  Tests/AK/TestRefPtr.cpp
Labels: 👀 pr-needs-review

#18457 LibGfx/JPEG: Make non-zero-terminated APPn starts non-fatal
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Labels: ✅ pr-community-approved

#18451 Kernel: Road to remove LOCK_IN_CRITICAL_DEBUG flag (part 1)
  Kernel/FileSystem/InodeWatcher.cpp
  Kernel/FileSystem/InodeWatcher.h
Labels: 👀 pr-needs-review

#18460 Ports: Prefer host python3.xx over python3
  Ports/python3/package.sh
Labels: 👀 pr-needs-review

#18471 LibWeb: Implement getting navigable's traversable and top-level traversable
  Userland/Libraries/LibWeb/HTML/Navigable.cpp
  Userland/Libraries/LibWeb/HTML/Navigable.h
Labels: 👀 pr-needs-review

#18474 Ladybird: Implement the JavaScript console using a WebContentView
  Ladybird/BrowserWindow.cpp
  Ladybird/ConsoleWidget.cpp
  Ladybird/ConsoleWidget.h
  Ladybird/WebContentView.cpp
  Ladybird/WebContentView.h
Labels: 👀 pr-needs-review

#18465 LibGfx: Decrease indent in ImageDecoder::try_create_for_raw_bytes() some
  Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.cpp
Labels: 👀 pr-needs-review

#18479 LibWeb: Convert navigationId from DeprecatedString to String
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/HTML/AbstractBrowsingContext.h
  Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
  Userland/Libraries/LibWeb/HTML/BrowsingContext.h
  Userland/Libraries/LibWeb/HTML/NavigationParams.h
  Userland/Libraries/LibWeb/HTML/RemoteBrowsingContext.h
Labels: 👀 pr-needs-review

#18475 LibWeb: Fix grid size when intrinsically sized
  Tests/LibWeb/Layout/expected/grid/intrinsic-sized-column.txt
  Tests/LibWeb/Layout/expected/grid/intrinsic-sized-grid.txt
  Tests/LibWeb/Layout/input/grid/intrinsic-sized-column.html
  Tests/LibWeb/Layout/input/grid/intrinsic-sized-grid.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#18480 LibWeb: Implement the HTMLMediaElement fastSeek method
  Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
  Userland/Libraries/LibWeb/HTML/HTMLMediaElement.idl
Labels: 👀 pr-needs-review

#16982 Kernel: Allow configuring a Jail to not impose PID isolation restriction
  Base/usr/share/man/man1/jail-create.md
  Base/usr/share/man/man7/Mitigations.md
  Kernel/API/Jail.h
  Kernel/API/Syscall.h
  Kernel/Jail.cpp
  Kernel/Jail.h
  Kernel/Syscalls/jail.cpp
  Userland/Libraries/LibCore/System.cpp
  Userland/Libraries/LibCore/System.h
  Userland/Utilities/jail-attach.cpp
  Userland/Utilities/jail-create.cpp
Labels: 👀 pr-needs-review

#18485 LibWeb/Fetch: Pass recursive=false to manual navigation redirect
  Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
  Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#18486 Ladybird: Define AK_DONT_REPLACE_STD via CMake rather than in every file
  Ladybird/AndroidPlatform.cpp
  Ladybird/CMakeLists.txt
  Ladybird/ConsoleWidget.cpp
  Ladybird/EventLoopPluginQt.cpp
  Ladybird/FontPluginQt.cpp
  Ladybird/HelperProcess.h
  Ladybird/ImageCodecPluginLadybird.cpp
  Ladybird/InspectorWidget.cpp
  Ladybird/LocationEdit.h
  Ladybird/ModelTranslator.cpp
  Ladybird/RequestManagerQt.h
  Ladybird/SQLServer/main.cpp
  Ladybird/Settings.h
  Ladybird/Tab.h
  Ladybird/TimerQt.cpp
  Ladybird/Utilities.cpp
  Ladybird/WebContent/main.cpp
  Ladybird/WebContentView.cpp
  Ladybird/WebContentView.h
  Ladybird/WebDriver/main.cpp
  Ladybird/WebSocketImplQt.cpp
  Userland/Utilities/headless-browser.cpp
Labels: 👀 pr-needs-review

#18488 WebContent: Add the 'thread' pledge for video playback
  Userland/Services/WebContent/main.cpp
Labels: 👀 pr-needs-review

#18483 Aplay: Determine absolute path before first `unveil`
  Userland/Utilities/aplay.cpp
Labels: 👀 pr-needs-review

#18491 Meta: Do not not contract the "not" in "don'ts"
  CONTRIBUTING.md
Labels: ✅ pr-community-approved

#18490 LibVideo: Do not invoke Vector2D's destructor in order to resize it
  Userland/Libraries/LibVideo/VP9/ContextStorage.h
Labels: 👀 pr-needs-review

#18498 AK: Rename `Stream::format()` to `Stream::write_formatted()`
  AK/Stream.cpp
  AK/Stream.h
  Userland/Libraries/LibJS/Print.cpp
Labels: 👀 pr-needs-review

#18499 LibWeb+WebContent: Make document background and Viewport transparent
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/Layout/Viewport.cpp
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
  Userland/Services/WebContent/PageHost.cpp
Labels: 👀 pr-needs-review

#18481 Documentation: fix markdown syntax
  Documentation/BuildInstructions.md
Labels: ✅ pr-community-approved

#18501 LibVideo/VP9: Wait for workers to finish when there are decoding errors
  Userland/Libraries/LibVideo/VP9/Parser.cpp
Labels: 👀 pr-needs-review

#18482 LibWeb: Fix the update of the favicon during navigation
  Userland/Libraries/LibWeb/Loader/FrameLoader.cpp
Labels: 👀 pr-needs-review

#18502 LibWeb: Add missing valid-identifiers for display CSS property
  Userland/Libraries/LibWeb/CSS/Properties.json
Labels: 👀 pr-needs-review

#18340 LibSQL: Handle statements with malformed exists expressions correctly
  Tests/LibSQL/TestSqlStatementParser.cpp
  Userland/Libraries/LibSQL/AST/Parser.cpp
  Userland/Libraries/LibSQL/AST/Parser.h
Labels: 👀 pr-needs-review

#18503 LibAudio: Make `WavWriter` check if a file was set during destruction
  Userland/Libraries/LibAudio/WavWriter.cpp
Labels: 👀 pr-needs-review

#18506 LibCore: Include sys/ucred.h in System.h for FreeBSD
  Userland/Libraries/LibCore/System.h
Labels: 👀 pr-needs-review
