Repository SerenityOS/serenity, pull requests merged in 2023-10, with the labels that each got.

#21280 MacPDF: Use "MacPDF" in MainMenu.xib
  Meta/Lagom/Contrib/MacPDF/MainMenu.xib
Labels: 👀 pr-needs-review

#21253 Assistant: Remember currently selected result when updating results
  Userland/Applications/Assistant/main.cpp
Labels: 👀 pr-needs-review

#21284 AK: Rename `URLParser:parse_host()` param is_not_special to is_opaque
  AK/URLParser.cpp
Labels: 👀 pr-needs-review

#21293 LibGfx: Don't read past EOF in JPEGLoader
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Labels: 👀 pr-needs-review

#21291 Ports/ffmpeg: Update to version 6.0
  Ports/AvailablePorts.md
  Ports/ffmpeg/package.sh
  Ports/ffmpeg/patches/0001-Assume-that-EDOM-exists.patch
  Ports/ffmpeg/patches/0002-Adapt-to-the-Serenity-thread-name-interface.patch
  Ports/ffmpeg/patches/0003-avcodec-x86-mathops-clip-constants-used-with-shift-i.patch
  Ports/ffmpeg/patches/ReadMe.md
Labels: 👀 pr-needs-review

#21238 SpaceAnalyzer: Port to GML compiler
  Userland/Applications/SpaceAnalyzer/CMakeLists.txt
  Userland/Applications/SpaceAnalyzer/MainWidget.h
  Userland/Applications/SpaceAnalyzer/SpaceAnalyzer.gml
  Userland/Applications/SpaceAnalyzer/TreeMapWidget.cpp
  Userland/Applications/SpaceAnalyzer/main.cpp
Labels: 👀 pr-needs-review

#21221 MasterWord: Use GML compiler
  Userland/Games/MasterWord/CMakeLists.txt
  Userland/Games/MasterWord/MainWidget.h
  Userland/Games/MasterWord/MasterWord.gml
  Userland/Games/MasterWord/WordGame.cpp
  Userland/Games/MasterWord/main.cpp
Labels: 👀 pr-needs-review

#21251 LibGUI: Don't enter TableView edit mode when a control key is pressed
  Userland/Libraries/LibGUI/TableView.cpp
Labels: 👀 pr-needs-review

#21301 pdf: Add a --dump-outline flag
  Userland/Utilities/pdf.cpp
Labels: 👀 pr-needs-review

#21297 LibWeb: Implement CSS fonts lazy loading
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Labels: 👀 pr-needs-review

#21303 LibArchive: Ensure tar extended header length is within expected range
  Userland/Libraries/LibArchive/TarStream.h
Labels: 👀 pr-needs-review

#21266 LibWeb: Implement `text-transform: capitalize`
  Userland/Libraries/LibUnicode/CharacterTypes.cpp
  Userland/Libraries/LibUnicode/CharacterTypes.h
  Userland/Libraries/LibUnicode/Forward.h
  Userland/Libraries/LibUnicode/String.cpp
  Userland/Libraries/LibUnicode/UnicodeUtils.cpp
  Userland/Libraries/LibUnicode/UnicodeUtils.h
  Userland/Libraries/LibWeb/Layout/TextNode.cpp
Labels: 👀 pr-needs-review

#21308 LibWeb: Exit event handlers if active document is not fully active
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
Labels: 👀 pr-needs-review

#21300 Maps: Fix occasional gray/missing tiles
  Userland/Applications/Maps/MapWidget.cpp
Labels: ✅ pr-community-approved

#21295 LibGfx: Check bounds of color table access in TinyVGLoader
  Userland/Libraries/LibGfx/ImageFormats/TinyVGLoader.cpp
Labels: ✅ pr-community-approved

#21041 Kernel: Share Processor class (and others) across architectures
  Kernel/Arch/CPUID.h
  Kernel/Arch/FPUState.h
  Kernel/Arch/Processor.cpp
  Kernel/Arch/Processor.h
  Kernel/Arch/ProcessorFunctions.include
  Kernel/Arch/TrapFrame.cpp
  Kernel/Arch/TrapFrame.h
  Kernel/Arch/aarch64/ASM_wrapper.h
  Kernel/Arch/aarch64/Exceptions.cpp
  Kernel/Arch/aarch64/FPUState.h
  Kernel/Arch/aarch64/Processor.cpp
  Kernel/Arch/aarch64/Processor.h
  Kernel/Arch/aarch64/TrapFrame.cpp
  Kernel/Arch/aarch64/TrapFrame.h
  Kernel/Arch/x86_64/ASM_wrapper.h
  Kernel/Arch/x86_64/CurrentTime.cpp
  Kernel/Arch/x86_64/DebugOutput.cpp
  Kernel/Arch/x86_64/FPUState.h
  Kernel/Arch/x86_64/Interrupts.cpp
  Kernel/Arch/x86_64/Processor.cpp
  Kernel/Arch/x86_64/Processor.h
  Kernel/Arch/x86_64/SyscallEntry.cpp
  Kernel/Arch/x86_64/TrapFrame.h
  Kernel/CMakeLists.txt
  Kernel/Locking/Spinlock.h
  Kernel/Syscalls/execve.cpp
Labels: 👀 pr-needs-review

#21086 LibGfx/ILBMLoader: add support for EHB mode
  Userland/Libraries/LibGfx/ImageFormats/ILBMLoader.cpp
Labels: ✅ pr-community-approved

#21165 LibWeb/MimeSniff: Implement the rest of the MIME type checks
  Userland/Libraries/LibWeb/MimeSniff/MimeType.cpp
  Userland/Libraries/LibWeb/MimeSniff/MimeType.h
Labels: 👀 pr-needs-review

#21323 LibJS: Don't evaluate computed MemberExpression LHS twice in assignments
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
  Userland/Libraries/LibJS/Bytecode/Generator.cpp
  Userland/Libraries/LibJS/Bytecode/Generator.h
Labels: 👀 pr-needs-review

#21328 LibWeb: Fix crash in XMLHttpRequest::response_xml() if response empty
  Userland/Libraries/LibWeb/XHR/XMLHttpRequest.cpp
Labels: 👀 pr-needs-review

#21322 Meta: Remove myself from LibELF-related CODEOWNERS entries
  .github/CODEOWNERS
Labels: 👀 pr-needs-review

#21334 Utilities: Remove redundant target_link_libraries
  Userland/Utilities/CMakeLists.txt
Labels: 👀 pr-needs-review

#21348 LibJS: Avoid ByteBuffer copying in RawBytesToNumeric and NumericToRawBytes
  Userland/Libraries/LibJS/Runtime/ArrayBuffer.h
  Userland/Libraries/LibJS/Runtime/AtomicsObject.cpp
Labels: 👀 pr-needs-review

#21080 grep: Hyperlink filenames in tty & other small fixes found along the way
  Base/usr/share/man/man1/grep.md
  Userland/Utilities/grep.cpp
Labels: 👀 pr-needs-review

#21166 Ladybird: Add keyboard shortcuts for jumping to a specific tab
  Ladybird/Qt/BrowserWindow.cpp
Labels: 👀 pr-needs-review

#21248 Browser: Treat absolute path as local file
  Userland/Applications/Browser/Tab.cpp
Labels: 👀 pr-needs-review

#21275 Kernel: Mark SDHC InterruptStatus structured view as const
  Kernel/Devices/Storage/SD/Registers.h
Labels: 👀 pr-needs-review

#21315 open: Display a meaningful error if the specified file doesn't exist
  Userland/Utilities/open.cpp
Labels: 👀 pr-needs-review

#21309 AK: Implement printf's "period without precision value" correctly
  AK/PrintfImplementation.h
  Tests/LibC/TestSnprintf.cpp
Labels: 👀 pr-needs-review

#21316 LibGfx/PNGLoader: Add validation for IHDR width, height and bit depth
  Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp
Labels: 👀 pr-needs-review

#21325 LibWeb: Resolve percentages in calc() for font-size
  Tests/LibWeb/Layout/expected/calc-font-size-with-percentages.txt
  Tests/LibWeb/Layout/input/calc-font-size-with-percentages.html
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
Labels: 👀 pr-needs-review

#21340 LibWeb/Canvas: Calculate text width for measureText correctly
  Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
Labels: 👀 pr-needs-review

#21342 LibHTTP: Return an error if HTTP request URL is not valid UTF-8
  Userland/Libraries/LibHTTP/HttpRequest.cpp
  Userland/Libraries/LibHTTP/HttpRequest.h
Labels: 👀 pr-needs-review

#21311 LibGUI: Improve responseiveness when generating lots of thumbnails
  Userland/Libraries/LibGUI/FileSystemModel.cpp
  Userland/Libraries/LibGUI/FileSystemModel.h
Labels: 👀 pr-needs-review

#21343 LibIMAP: Handle invalid escape sequences in Quoted-Printable parser
  Tests/LibIMAP/TestQuotedPrintable.cpp
  Userland/Libraries/LibIMAP/QuotedPrintable.cpp
Labels: 👀 pr-needs-review

#21356 LibTLS: Reorder supported ciphers
  Userland/Libraries/LibTLS/TLSv12.h
Labels: 👀 pr-needs-review

#21359 LibJS: Inline fast case for Value::to_{boolean,number,numeric,primitive}
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
  Tests/LibJS/test-value-js.cpp
  Tests/LibJS/test262-runner.cpp
  Userland/Applications/Assistant/Providers.cpp
  Userland/Applications/Spreadsheet/Cell.cpp
  Userland/Applications/Spreadsheet/CellType/Numeric.cpp
  Userland/Applications/Spreadsheet/JSIntegration.cpp
  Userland/Libraries/LibJS/AST.cpp
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
  Userland/Libraries/LibJS/Console.cpp
  Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
  Userland/Libraries/LibJS/Runtime/Array.cpp
  Userland/Libraries/LibJS/Runtime/ArrayPrototype.cpp
  Userland/Libraries/LibJS/Runtime/AsyncFunctionDriverWrapper.cpp
  Userland/Libraries/LibJS/Runtime/BigIntConstructor.cpp
  Userland/Libraries/LibJS/Runtime/BooleanConstructor.cpp
  Userland/Libraries/LibJS/Runtime/DataViewPrototype.cpp
  Userland/Libraries/LibJS/Runtime/DateConstructor.cpp
  Userland/Libraries/LibJS/Runtime/DatePrototype.cpp
  Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
  Userland/Libraries/LibJS/Runtime/Intl/AbstractOperations.cpp
  Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormatFunction.cpp
  Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormatPrototype.cpp
  Userland/Libraries/LibJS/Runtime/Intl/DurationFormat.cpp
  Userland/Libraries/LibJS/Runtime/Intl/NumberFormat.cpp
  Userland/Libraries/LibJS/Runtime/Intl/PluralRulesPrototype.cpp
  Userland/Libraries/LibJS/Runtime/Intl/RelativeTimeFormatPrototype.cpp
  Userland/Libraries/LibJS/Runtime/Iterator.cpp
  Userland/Libraries/LibJS/Runtime/IteratorPrototype.cpp
  Userland/Libraries/LibJS/Runtime/JSONObject.cpp
  Userland/Libraries/LibJS/Runtime/MathObject.cpp
  Userland/Libraries/LibJS/Runtime/ObjectEnvironment.cpp
  Userland/Libraries/LibJS/Runtime/PropertyDescriptor.cpp
  Userland/Libraries/LibJS/Runtime/ProxyObject.cpp
  Userland/Libraries/LibJS/Runtime/RegExpPrototype.cpp
  Userland/Libraries/LibJS/Runtime/SetPrototype.cpp
  Userland/Libraries/LibJS/Runtime/StringConstructor.cpp
  Userland/Libraries/LibJS/Runtime/StringPrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
  Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/DurationConstructor.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/InstantConstructor.cpp
  Userland/Libraries/LibJS/Runtime/TypedArray.cpp
  Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
  Userland/Libraries/LibJS/Runtime/Value.cpp
  Userland/Libraries/LibJS/Runtime/Value.h
  Userland/Libraries/LibJS/Runtime/ValueInlines.h
  Userland/Libraries/LibWeb/Bindings/OptionConstructor.cpp
  Userland/Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.cpp
  Userland/Libraries/LibWeb/WebGL/WebGLContextAttributes.cpp
  Userland/Utilities/js.cpp
Labels: 👀 pr-needs-review

#21360 LibGfx/ICC: Avoid overflow when checking tag bounds
  Userland/Libraries/LibGfx/ICC/Profile.cpp
Labels: ✅ pr-community-approved

#21363 LibJS: Move Heap intrusive list manipulation inline
  Userland/Libraries/LibJS/Heap/Heap.cpp
  Userland/Libraries/LibJS/Heap/Heap.h
Labels: 👀 pr-needs-review

#21146 find: Don't canonicalize path operands
  Userland/Utilities/find.cpp
Labels: 👀 pr-needs-review

#21368 LibJS: Do less work in successfully cached GetByValue* ops
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Labels: 👀 pr-needs-review

#21365 LibWeb/XML: Avoid placing all elements missing an ns in the HTML ns
  Tests/LibWeb/Text/expected/XML/parser-namespace.txt
  Tests/LibWeb/Text/input/XML/parser-namespace.html
  Userland/Libraries/LibWeb/XML/XMLDocumentBuilder.cpp
  Userland/Libraries/LibWeb/XML/XMLDocumentBuilder.h
Labels: 👀 pr-needs-review

#21337 Shell: Add support for the bashy list literals in POSIX mode
  Userland/Shell/AST.h
  Userland/Shell/PosixLexer.cpp
  Userland/Shell/PosixLexer.h
  Userland/Shell/PosixParser.cpp
  Userland/Shell/PosixParser.h
Labels: 👀 pr-needs-review

#21366 LibWeb: Destroy navigable containers not inserted into document tree
  Userland/Libraries/LibWeb/DOM/Document.cpp
Labels: 👀 pr-needs-review

#21377 LibWeb: Don't offset abspos children of flex container by padding twice
  Tests/LibWeb/Layout/expected/flex/abspos-flex-child-static-position-with-padding-on-flex-container.txt
  Tests/LibWeb/Layout/input/flex/abspos-flex-child-static-position-with-padding-on-flex-container.html
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Labels: 👀 pr-needs-review

#21378 LibGfx/PNGLoader: Don't allow multiple consecutive IHDR chunks
  Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp
Labels: 👀 pr-needs-review

#21379 LibJS: Avoid IdentifierTable lookup in cached GetGlobal op
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Labels: 👀 pr-needs-review

#21382 LibWeb: Create navigables only for iframe in a document tree
  Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.cpp
Labels: 👀 pr-needs-review

#21384 AK: Avoid overflow when passing i64 minimum value to `vformat()`
  AK/Format.cpp
  Tests/AK/TestFormat.cpp
Labels: 👀 pr-needs-review

#21387 LibJS: Remove inline capacity from MarkedVector
  Userland/Libraries/LibJS/Forward.h
Labels: 👀 pr-needs-review

#21392 Meta: Misc README fixes
  README.md
Labels: 👀 pr-needs-review

#21389 LibCompress: Fix a typo in `m_read_final_block`
  Userland/Libraries/LibCompress/Deflate.cpp
  Userland/Libraries/LibCompress/Deflate.h
Labels: 👀 pr-needs-review

#21381 LibGfx/BMPLoader: Ensure DIB size and offset are within expected range
  Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp
Labels: 👀 pr-needs-review

#21391 LibCompress: Avoid buffer overrun when building canonical Huffman code
  Tests/LibCompress/TestDeflate.cpp
  Userland/Libraries/LibCompress/Deflate.cpp
Labels: 👀 pr-needs-review

#21395 MacPDF: Unbreak persisting the current page
  Meta/Lagom/Contrib/MacPDF/MacPDFWindowController.mm
Labels: 👀 pr-needs-review

#21403 LibWeb: Stop inserting inline nodes into a generated wrapper box
  Tests/LibWeb/Layout/expected/block-and-inline/inline-node-not-inserted-into-generated-box.txt
  Tests/LibWeb/Layout/input/block-and-inline/inline-node-not-inserted-into-generated-box.html
  Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Labels: 👀 pr-needs-review

#21405 LibWeb/CSS: Parser should treat calc() with flex values as invalid
  Tests/LibWeb/Layout/expected/calc-with-fr.txt
  Tests/LibWeb/Layout/input/calc-with-fr.html
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#21341 LibTLS: Don't attempt to read past EOF when parsing TBSCertificate
  Meta/Lagom/CMakeLists.txt
  Tests/LibTLS/CMakeLists.txt
  Tests/LibTLS/TestTLSCertificateParser.cpp
  Userland/Libraries/LibTLS/Certificate.cpp
Labels: 👀 pr-needs-review

#21402 LibPDF: Cache fonts per page
  Userland/Libraries/LibPDF/Renderer.cpp
  Userland/Libraries/LibPDF/Renderer.h
Labels: 👀 pr-needs-review

#21417 LibVideo/VP9: Ensure color space is not set to reserved value
  Userland/Libraries/LibVideo/VP9/Parser.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#21416 LibGfx/BMPLoader: Ensure data offset cannot point past EOF
  Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp
Labels: 👀 pr-needs-review

#21415 AK: Fix doc comment for bit_scan_forward
  AK/BuiltinWrappers.h
Labels: 👀 pr-needs-review

#21418 CMake: Actually set the LAGOM_USE_LINKER option automatically
  Meta/CMake/use_linker.cmake
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#21399 LibWeb: Use struct to pass Navigable::navigate() params
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp
  Userland/Libraries/LibWeb/HTML/HTMLObjectElement.cpp
  Userland/Libraries/LibWeb/HTML/Location.cpp
  Userland/Libraries/LibWeb/HTML/Navigable.cpp
  Userland/Libraries/LibWeb/HTML/Navigable.h
  Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
  Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
  Userland/Libraries/LibWeb/HTML/Window.cpp
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
  Userland/Libraries/LibWeb/Page/Page.cpp
Labels: 👀 pr-needs-review

#21420 LibWeb: Resolve backdrop filter length in apply_style()
  Userland/Libraries/LibWeb/CSS/ComputedValues.h
  Userland/Libraries/LibWeb/CSS/StyleValues/FilterValueListStyleValue.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/FilterValueListStyleValue.h
  Userland/Libraries/LibWeb/Layout/Node.cpp
  Userland/Libraries/LibWeb/Painting/FilterPainting.cpp
  Userland/Libraries/LibWeb/Painting/FilterPainting.h
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Labels: 👀 pr-needs-review

#21414 LibWeb: Store the SVG `<use>` element's referenced ID as a FlyString
  Userland/Libraries/LibWeb/SVG/SVGUseElement.cpp
  Userland/Libraries/LibWeb/SVG/SVGUseElement.h
Labels: 👀 pr-needs-review

#21396 pdf: Add a --render-repeats=N flag
  Userland/Utilities/pdf.cpp
Labels: 👀 pr-needs-review

#21354 Ports/angband: Update to Angband 4.2.5
  Ports/AvailablePorts.md
  Ports/angband/package.sh
  Ports/angband/patches/0001-Disable-hardware-acceleration.patch
  Ports/angband/patches/0002-Fix-up-SDL-path-handling.patch
  Ports/angband/patches/ReadMe.md
Labels: 👀 pr-needs-review

#21423 LibWeb/HTML: Use MimeType::is_xml() in HTMLObjectElement for DRYness
  Userland/Libraries/LibWeb/HTML/HTMLObjectElement.cpp
Labels: 👀 pr-needs-review

#21426 LibPDF: Don't crash on files with float CFF defaultWidthX
  Userland/Libraries/LibPDF/Fonts/CFF.cpp
  Userland/Libraries/LibPDF/Fonts/CFF.h
Labels: 👀 pr-needs-review

#21372 Ladybird: Implement content zooming in the AppKit chrome
  Ladybird/AppKit/Application/ApplicationDelegate.mm
  Ladybird/AppKit/UI/LadybirdWebView.h
  Ladybird/AppKit/UI/LadybirdWebView.mm
  Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
  Ladybird/AppKit/UI/LadybirdWebViewBridge.h
  Ladybird/AppKit/UI/TabController.mm
Labels: 👀 pr-needs-review

#21313 Base: Add 201 Hangul syllables to font Katica Regular 10
  Base/res/fonts/KaticaRegular10.font
Labels: ✅ pr-community-approved

#21369 LibIMAP: Stop parsing immediately on error
  Userland/Applications/Mail/MailWidget.cpp
  Userland/Libraries/LibIMAP/Objects.h
  Userland/Libraries/LibIMAP/Parser.cpp
  Userland/Libraries/LibIMAP/Parser.h
  Userland/Utilities/test-imap.cpp
Labels: 👀 pr-needs-review

#21312 LibELF: Handle TLSDESC relocations in .rela.plt for GNU ld
  Userland/Libraries/LibELF/DynamicLoader.cpp
Labels: 👀 pr-needs-review

#21446 LibWeb: Use "POST" instead of "post" for POST resources in navigables
  Userland/Libraries/LibWeb/HTML/Navigable.cpp
Labels: 👀 pr-needs-review

#21449 LibWeb: Fix null optional dereference in Node::name_or_description()
  Userland/Libraries/LibWeb/DOM/Node.cpp
Labels: 👀 pr-needs-review

#21451 LibPDF: Add a CFF_DEBUG toggle
  AK/Debug.h.in
  Meta/CMake/all_the_debug_macros.cmake
  Meta/gn/secondary/AK/BUILD.gn
  Userland/Libraries/LibPDF/Fonts/CFF.cpp
Labels: 👀 pr-needs-review

#21437 LibWeb: Remove use of UnicodeData header from DOM::Element
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: 👀 pr-needs-review

#21430 LibGfx/ILBM: Avoid buffer overrun when reading header chunk
  Userland/Libraries/LibGfx/ImageFormats/ILBMLoader.cpp
Labels: 👀 pr-needs-review

#21444 Kernel: Fix SipHash aarch64 boot regression
  Kernel/Arch/init.cpp
Labels: 👀 pr-needs-review

#21452 LibPDF: Don't overflow SIDs in type 1 charset parsing (and implement type 2)
  Userland/Libraries/LibPDF/Fonts/CFF.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#21455 LibGUI: Fix FileSystemModel/FileManager after aeee98b
  Userland/Libraries/LibGUI/FileSystemModel.cpp
  Userland/Libraries/LibGUI/FileSystemModel.h
Labels: 👀 pr-needs-review

#21456 LibGfx: Fix serializing Gfx::Bitmaps
  Tests/LibGfx/TestGfxBitmap.cpp
  Userland/Libraries/LibGfx/Bitmap.cpp
Labels: 👀 pr-needs-review

#20753 Kernel: Add a framebuffer driver for 3Dfx Voodoo 3
  Kernel/Bus/PCI/IDs.h
  Kernel/CMakeLists.txt
  Kernel/Debug.h.in
  Kernel/Devices/GPU/3dfx/Definitions.h
  Kernel/Devices/GPU/3dfx/GraphicsAdapter.cpp
  Kernel/Devices/GPU/3dfx/GraphicsAdapter.h
  Kernel/Devices/GPU/3dfx/VoodooDisplayConnector.cpp
  Kernel/Devices/GPU/3dfx/VoodooDisplayConnector.h
  Kernel/Devices/GPU/DisplayConnector.cpp
  Kernel/Devices/GPU/Management.cpp
  Meta/CMake/all_the_debug_macros.cmake
Labels: 👀 pr-needs-review

#21453 LibPDF: Fix sign (and fixed point) in glyph decoding opcode 24
  Userland/Libraries/LibPDF/Fonts/Type1FontProgram.cpp
Labels: 👀 pr-needs-review

#21460 Ports/curl: Set CMake cache variable HAVE_GETADDRINFO_THREADSAFE to 1
  Ports/curl/package.sh
Labels: 👀 pr-needs-review

#20988 DynamicLoader: Add an option to explicitly run an ELF executable binary
  Userland/DynamicLoader/main.cpp
Labels: 👀 pr-needs-review

#21438 LibWeb/HTMLInputElement: Improve appearance of color picker
  Userland/Libraries/LibWeb/CSS/Default.css
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
Labels: 👀 pr-needs-review

#21462 AK: Avoid nullptr deref in DeprecatedString(DeprecatedFlyString const&)
  AK/DeprecatedString.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#21464 LibWeb: Fix min-content width calculation in dimension_box_on_line()
  Tests/LibWeb/Layout/expected/block-and-inline/inline-block-contained-by-abspos-element.txt
  Tests/LibWeb/Layout/input/block-and-inline/inline-block-contained-by-abspos-element.html
  Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Labels: 👀 pr-needs-review

#21465 LibGfx/ILBM: Explicitly fail decoding if body chunk isn't present
  Userland/Libraries/LibGfx/ImageFormats/ILBMLoader.cpp
Labels: 👀 pr-needs-review

#21479 LibTest: Remove the redefinition of VERIFY family of macros
  Userland/Libraries/LibTest/Macros.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#21481 LibGfx: Fix crash during rasterizing glyphs containing only one point
  Tests/LibGfx/TestFontHandling.cpp
  Userland/Libraries/LibGfx/Font/OpenType/Glyf.cpp
Labels: 👀 pr-needs-review

#21476 LibWeb: Forbid sharing image requests across documents
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/HTML/SharedImageRequest.cpp
  Userland/Libraries/LibWeb/HTML/SharedImageRequest.h
Labels: 👀 pr-needs-review

#21459 LibWeb: Introduce RecordingPainter to serialize painting commands
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.cpp
  Userland/Libraries/LibWeb/Forward.h
  Userland/Libraries/LibWeb/Layout/Box.cpp
  Userland/Libraries/LibWeb/Layout/CanvasBox.cpp
  Userland/Libraries/LibWeb/Painting/AudioPaintable.cpp
  Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
  Userland/Libraries/LibWeb/Painting/BorderPainting.cpp
  Userland/Libraries/LibWeb/Painting/BorderPainting.h
  Userland/Libraries/LibWeb/Painting/BorderRadiiData.cpp
  Userland/Libraries/LibWeb/Painting/BorderRadiiData.h
  Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.cpp
  Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.h
  Userland/Libraries/LibWeb/Painting/BordersData.h
  Userland/Libraries/LibWeb/Painting/CanvasPaintable.cpp
  Userland/Libraries/LibWeb/Painting/CheckBoxPaintable.cpp
  Userland/Libraries/LibWeb/Painting/FilterPainting.cpp
  Userland/Libraries/LibWeb/Painting/GradientData.h
  Userland/Libraries/LibWeb/Painting/GradientPainting.cpp
  Userland/Libraries/LibWeb/Painting/GradientPainting.h
  Userland/Libraries/LibWeb/Painting/ImagePaintable.cpp
  Userland/Libraries/LibWeb/Painting/LinearGradientData.h
  Userland/Libraries/LibWeb/Painting/MarkerPaintable.cpp
  Userland/Libraries/LibWeb/Painting/MediaPaintable.cpp
  Userland/Libraries/LibWeb/Painting/MediaPaintable.h
  Userland/Libraries/LibWeb/Painting/NestedBrowsingContextPaintable.cpp
  Userland/Libraries/LibWeb/Painting/PaintContext.cpp
  Userland/Libraries/LibWeb/Painting/PaintContext.h
  Userland/Libraries/LibWeb/Painting/PaintOuterBoxShadowParams.h
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
  Userland/Libraries/LibWeb/Painting/PaintableBox.h
  Userland/Libraries/LibWeb/Painting/ProgressPaintable.cpp
  Userland/Libraries/LibWeb/Painting/RadioButtonPaintable.cpp
  Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
  Userland/Libraries/LibWeb/Painting/RecordingPainter.h
  Userland/Libraries/LibWeb/Painting/SVGGeometryPaintable.cpp
  Userland/Libraries/LibWeb/Painting/SVGGraphicsPaintable.cpp
  Userland/Libraries/LibWeb/Painting/SVGGraphicsPaintable.h
  Userland/Libraries/LibWeb/Painting/SVGTextPaintable.cpp
  Userland/Libraries/LibWeb/Painting/ShadowData.h
  Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp
  Userland/Libraries/LibWeb/Painting/ShadowPainting.h
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
  Userland/Libraries/LibWeb/Painting/TableBordersPainting.cpp
  Userland/Libraries/LibWeb/Painting/VideoPaintable.cpp
  Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
  Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.h
  Userland/Libraries/LibWeb/SVG/SVGPathElement.cpp
  Userland/Services/WebContent/PageHost.cpp
Labels: 👀 pr-needs-review

#21480 LibPDF: Make Subrs optional in PS1FontProgram
  Userland/Libraries/LibPDF/Fonts/PS1FontProgram.cpp
Labels: 👀 pr-needs-review

#21473 LibPDF: Allow moving Reader::move_to() to end of data stream
  Userland/Libraries/LibPDF/Reader.h
Labels: 👀 pr-needs-review

#21482 find: Add the `-path` and `-ipath` options
  Base/usr/share/man/man1/find.md
  Userland/Utilities/find.cpp
Labels: 👀 pr-needs-review

#21483 Meta: Add a note about resolving PR review comments
  CONTRIBUTING.md
Labels: 👀 pr-needs-review

#21491 LibJS: Disable Temporal custom time zone test
  Userland/Libraries/LibJS/Tests/builtins/Temporal/Now/Now.plainDateTime.js
Labels: 👀 pr-needs-review

#21489 LibPDF: Use a RAII object to restore state in recursive render
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: 👀 pr-needs-review

#21496 du: Add `-x` option to not traverse directories across filesystems
  Base/usr/share/man/man1/du.md
  Userland/Utilities/du.cpp
Labels: 👀 pr-needs-review

#21498 LibPDF: Try harder to use a RAII object to restore state
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: 👀 pr-needs-review

#21499 LibPDF: Implement color_rendering_intent operator
  Userland/Libraries/LibPDF/Renderer.cpp
  Userland/Libraries/LibPDF/Renderer.h
Labels: 👀 pr-needs-review

#21500 MacPDF: Make "Open With" and dropping files on dock tile work
  Meta/Lagom/Contrib/MacPDF/AppDelegate.mm
Labels: 👀 pr-needs-review

#21501 LibPDF: Fix lookup of built-in Bold Italic strings
  Userland/Libraries/LibPDF/Fonts/PDFFont.cpp
Labels: 👀 pr-needs-review

#21503 LibWeb: Fix spec implementation mistakes in destroy_the_child_navigable
  Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
Labels: 👀 pr-needs-review

#21314 LibGfx/JPEGLoader: Check array access bounds when building lookup table
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Labels: 👀 pr-needs-review

#21514 LibPDF: Replace TODO()s in Type0Font code with Errors
  Userland/Libraries/LibPDF/Fonts/Type0Font.cpp
Labels: 👀 pr-needs-review

#21319 AK/URLParser: Complete implementation of `is_url_code_point()`
  AK/URLParser.cpp
Labels: 👀 pr-needs-review

#21519 Ports/ClassiCube: Update ClassiCube to version 1.3.6
  Ports/AvailablePorts.md
  Ports/ClassiCube/package.sh
  Ports/ClassiCube/patches/0001-Add-support-for-SerenityOS.patch
  Ports/ClassiCube/patches/0001-Ignore-warning-with-using-SDL-backend.patch
  Ports/ClassiCube/patches/0002-HACK-Disable-interrupt-hooks.patch
  Ports/ClassiCube/patches/ReadMe.md
Labels: 👀 pr-needs-review

#21522 LibWeb: Rerun rows sizings if grid auto height is less than min-height
  Tests/LibWeb/Layout/expected/grid/container-min-height.txt
  Tests/LibWeb/Layout/input/grid/container-min-height.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#21526 LibWeb: Support alignment of abspos grid items
  Tests/LibWeb/Layout/expected/grid/abspos-item-aligned-center.txt
  Tests/LibWeb/Layout/input/grid/abspos-item-aligned-center.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#21525 LibPDF: Replace another TODO with a message
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: 👀 pr-needs-review

#21512 Meta: Add a script for rendering many PDFs in parallel
  Meta/test_pdf.py
Labels: 👀 pr-needs-review

#21524 LibPDF: Fix rare assertions when constructing outlines
  Userland/Libraries/LibPDF/Document.cpp
Labels: 👀 pr-needs-review

#21531 LibWeb: Remove ClearRect command in RecordingPainter
  Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
  Userland/Libraries/LibWeb/Painting/RecordingPainter.h
  Userland/Services/WebContent/PageHost.cpp
Labels: 👀 pr-needs-review

#21530 LibPDF: Don't assert on named simple color space
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: 👀 pr-needs-review

#21441 AK: Pass correct length to convert_to_floating_point()
  AK/StringUtils.cpp
  Tests/AK/TestStringUtils.cpp
Labels: 👀 pr-needs-review

#21535 Shell: Don't try to cast NonnullRefPtrs when priting debug output
  Userland/Shell/Shell.cpp
Labels: 👀 pr-needs-review

#21546 LibWeb: Fix building of areas spanning multiple rows in GFC
  Tests/LibWeb/Layout/expected/grid/template-areas-1.txt
  Tests/LibWeb/Layout/expected/grid/template-areas-2.txt
  Tests/LibWeb/Layout/expected/grid/template-areas-3.txt
  Tests/LibWeb/Layout/input/grid/template-areas-1.html
  Tests/LibWeb/Layout/input/grid/template-areas-2.html
  Tests/LibWeb/Layout/input/grid/template-areas-3.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#21551 LibPDF: Skip inline image data in operator stream
  Userland/Libraries/LibPDF/Parser.cpp
Labels: 👀 pr-needs-review

#21509 AK: Remove rarely used ExtraMathConstants.h
  AK/ExtraMathConstants.h
  Meta/gn/secondary/AK/BUILD.gn
  Userland/Applications/PixelPaint/Filters/FastBoxBlur.cpp
  Userland/Libraries/LibC/math.cpp
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasPath.cpp
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
  Userland/Libraries/LibWeb/SVG/SVGPathElement.cpp
Labels: 👀 pr-needs-review

#21548 LibJS/Date: Ensure `YearFromTime(t)` holds invariant after approximation
  Userland/Libraries/LibJS/Runtime/Date.cpp
  Userland/Libraries/LibJS/Tests/builtins/Date/Date.UTC.js
Labels: 👀 pr-needs-review

#21557 LibPDF: Tolerate comments after dict values
  Userland/Libraries/LibPDF/Parser.cpp
Labels: 👀 pr-needs-review

#21554 LibPDF: Use TRY() to get decompression result
  Userland/Libraries/LibPDF/Filter.cpp
Labels: 👀 pr-needs-review

#21555 LibPDF: Don't crash on fixed-width type 1 fonts that use /MissingWidth
  Userland/Libraries/LibPDF/Fonts/SimpleFont.cpp
  Userland/Libraries/LibPDF/Fonts/SimpleFont.h
  Userland/Libraries/LibPDF/Fonts/TrueTypeFont.cpp
  Userland/Libraries/LibPDF/Fonts/TrueTypeFont.h
  Userland/Libraries/LibPDF/Fonts/Type1Font.cpp
  Userland/Libraries/LibPDF/Fonts/Type1Font.h
Labels: 👀 pr-needs-review

#21561 LibPDF: Don't accidentally form new tokens on pages with contents arrays
  Userland/Libraries/LibPDF/Page.cpp
Labels: 👀 pr-needs-review

#21547 LibGUI: Don't update ComboBox text when model index is invalid
  Userland/Libraries/LibGUI/ComboBox.cpp
Labels: 👀 pr-needs-review

#21288 Kernel/Ext2: Avoid overflow when updating UID and GID values
  Kernel/FileSystem/Ext2FS/FileSystem.cpp
  Kernel/FileSystem/Ext2FS/Inode.cpp
  Meta/build-root-filesystem.sh
  Tests/Kernel/CMakeLists.txt
  Tests/Kernel/TestExt2FS.cpp
Labels: 👀 pr-needs-review

#21559 LibWeb: Resolve grid item's min-width and max-width in GFC
  Tests/LibWeb/Layout/expected/grid/item-max-width.txt
  Tests/LibWeb/Layout/expected/grid/item-min-width.txt
  Tests/LibWeb/Layout/input/grid/item-max-width.html
  Tests/LibWeb/Layout/input/grid/item-min-width.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#21564 LibWeb: Use max content contribution in flex_fraction in GFC
  Tests/LibWeb/Layout/expected/grid/items-min-content-size-should-account-paddings.txt
  Tests/LibWeb/Layout/input/grid/items-min-content-size-should-account-paddings.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#21565 LibGfx/WOFF: Ensure header `totalSfntSize` matches expected value
  Tests/LibGfx/CMakeLists.txt
  Tests/LibGfx/TestWOFF.cpp
  Tests/LibGfx/test-inputs/woff/invalid_sfnt_size.woff
  Userland/Libraries/LibGfx/Font/WOFF/Font.cpp
Labels: 👀 pr-needs-review

#21492 Meta: Update libjs.dev links to test262.fyi
  Documentation/Links.md
  Meta/Lagom/ReadMe.md
Labels: 👀 pr-needs-review

#21544 Fuzzers: Add a fuzzer for JsonParser
  Meta/Lagom/Fuzzers/FuzzJsonParser.cpp
  Meta/Lagom/Fuzzers/fuzzers.cmake
  Userland/Utilities/test-fuzz.cpp
Labels: 👀 pr-needs-review

#21353 Meta: Manually redirect CI serial output to stdout
  Documentation/RunningTests.md
  Meta/run.sh
Labels: 👀 pr-needs-review

#21520 AK: Colorize log message for failed assertions
  AK/Assertions.cpp
Labels: 👀 pr-needs-review

#21571 Meta: Don't pass ^C through the serial console on CI
  Documentation/RunningTests.md
  Meta/run.sh
Labels: 👀 pr-needs-review

#21576 LibPDF: Make Reader::move_by() parameter more truthful
  Userland/Libraries/LibPDF/Reader.h
Labels: 👀 pr-needs-review

#21536 LibPDF: Don't check for `startxref` after trailer dict
  Userland/Libraries/LibPDF/DocumentParser.cpp
Labels: 👀 pr-needs-review

#21574 LibWeb: Protect ad-hoc `scroll` against a potentially null paintable box
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: 👀 pr-needs-review

#21505 LibGfx/BMPLoader: Account for header size when checking DIB bounds
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/ico/oss-fuzz-testcase-63357.ico
  Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp
Labels: 👀 pr-needs-review

#21579 LibPDF: Implement two SeparationColorSpace methods
  Userland/Libraries/LibPDF/ColorSpace.cpp
  Userland/Libraries/LibPDF/ColorSpace.h
Labels: 👀 pr-needs-review

#21577 LibWeb: Record painting commands in coordinates of stacking context
  Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.cpp
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
  Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
  Userland/Libraries/LibWeb/Painting/RecordingPainter.h
  Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Labels: 👀 pr-needs-review

#21594 LibWeb/Painting: Remove Save and Restore commands in RecordingPainter
  Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
  Userland/Libraries/LibWeb/Painting/RecordingPainter.h
Labels: 👀 pr-needs-review

#21591 LibWeb: Handle fit-content in calculate_max_content_contribution in GFC
  Tests/LibWeb/Layout/expected/grid/item-fit-content-width.txt
  Tests/LibWeb/Layout/input/grid/item-fit-content-width.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#21597 Tests/LibWeb: Add missing test-shadow.html
  Tests/LibWeb/Ref/text-shadow.html
Labels: 👀 pr-needs-review

#21582 JSSpecCompiler: Support Cpp::{BinaryExpression,StringLiteral} in C++ AST converter (simple to review!)
  Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/CppASTConverter.cpp
Labels: 👀 pr-needs-review

#21448 LibGfx/ICC: Avoid overflow when constructing `NamedColor2TagData`
  Tests/LibGfx/TestICCProfile.cpp
  Tests/LibGfx/test-inputs/icc/oss-fuzz-testcase-59551.icc
  Userland/Libraries/LibGfx/ICC/TagTypes.cpp
Labels: 👀 pr-needs-review

#21573 Ladybird+Meta: Make the AppKit chrome the default on macOS
  Documentation/BuildInstructionsLadybird.md
  Ladybird/CMakeLists.txt
  Meta/Azure/Lagom.yml
  Meta/serenity.sh
Labels: 👀 pr-needs-review
