Repository SerenityOS/serenity, pull requests merged in 2023-02, with the labels that each got.

#17262 Documentation: Rename WebServer_localhost to .jpg
  Documentation/TransferringFiles.md
  Documentation/WebServer_localhost.jpg
Labels: 👀 pr-needs-review

#17073 Meta: Derust fuzzer build docs
  Meta/Lagom/ReadMe.md
Labels: 👀 pr-needs-review

#17263 Meta: Set working directory and LD_LIBRARY_PATH for tests
  Meta/Lagom/CMakeLists.txt
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17260 Base+Presenter: Add icons for Presenter
  Base/etc/FileIconProvider.ini
  Base/res/icons/16x16/app-presenter.png
  Base/res/icons/16x16/filetype-presenter.png
  Base/res/icons/32x32/app-presenter.png
  Base/res/icons/32x32/filetype-presenter.png
  Userland/Applications/Presenter/CMakeLists.txt
  Userland/Applications/Presenter/PresenterWidget.cpp
  Userland/Applications/Presenter/main.cpp
Labels: 👀 pr-needs-review

#17084 PixelPaint: Make color picking with the Alt key behave the same as the picker tool
  Userland/Applications/PixelPaint/ImageEditor.cpp
Labels: 👀 pr-needs-review

#16832 PixelPaint: Ensure layers are painted consistently when panning and zooming
  Userland/Applications/PixelPaint/Image.cpp
  Userland/Applications/PixelPaint/Image.h
  Userland/Applications/PixelPaint/ImageEditor.cpp
Labels: 👀 pr-needs-review

#16723 Documentation: Add troubleshooting note regarding KVM GDB
  Documentation/Troubleshooting.md
Labels: 👀 pr-needs-review

#17270 SQLServer: Unveil /etc/passwd
  Userland/Services/SQLServer/main.cpp
Labels: 👀 pr-needs-review

#17265 Ladybird: Left-align long url in address bar
  Ladybird/Tab.cpp
Labels: 👀 pr-needs-review

#17269 LibJS: Format the era of ISO year 0 as BC
  Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormat.cpp
  Userland/Libraries/LibJS/Tests/builtins/Intl/DateTimeFormat/DateTimeFormat.prototype.format.js
Labels: 👀 pr-needs-review

#17274 LibWeb: Restore handling of the serenity:ladybird/headless capability
  Userland/Libraries/LibWeb/WebDriver/Capabilities.cpp
Labels: 👀 pr-needs-review

#17279 FileSystemAccessServer: Send correct error code for failed file access
  Userland/Services/FileSystemAccessServer/ConnectionFromClient.cpp
Labels: 👀 pr-needs-review

#17273 Profiler: Standardize percentage formatting
  Userland/DevTools/Profiler/DisassemblyModel.cpp
  Userland/DevTools/Profiler/PercentageFormatting.h
  Userland/DevTools/Profiler/ProfileModel.cpp
  Userland/DevTools/Profiler/ProfileModel.h
  Userland/DevTools/Profiler/main.cpp
Labels: 👀 pr-needs-review

#17268 Ports: Install all dependencies instead of just one
  Ports/.port_include.sh
Labels: 👀 pr-needs-review

#17211 PixelPaint: Show resize anchors when using the move tool
  Userland/Applications/PixelPaint/Tools/MoveTool.cpp
  Userland/Applications/PixelPaint/Tools/MoveTool.h
Labels: ✅ pr-community-approved

#17234 LibWeb+LibWebSocket: DOM WebSocket subprotocol support
  Ladybird/WebSocketClientManagerLadybird.cpp
  Ladybird/WebSocketClientManagerLadybird.h
  Ladybird/WebSocketLadybird.cpp
  Ladybird/WebSocketLadybird.h
  Userland/Libraries/LibProtocol/WebSocket.cpp
  Userland/Libraries/LibProtocol/WebSocket.h
  Userland/Libraries/LibProtocol/WebSocketClient.cpp
  Userland/Libraries/LibProtocol/WebSocketClient.h
  Userland/Libraries/LibWeb/WebSockets/WebSocket.cpp
  Userland/Libraries/LibWeb/WebSockets/WebSocket.h
  Userland/Libraries/LibWeb/WebSockets/WebSocket.idl
  Userland/Libraries/LibWebSocket/WebSocket.cpp
  Userland/Libraries/LibWebSocket/WebSocket.h
  Userland/Libraries/LibWebView/WebSocketClientAdapter.cpp
  Userland/Libraries/LibWebView/WebSocketClientAdapter.h
  Userland/Services/WebSocket/ConnectionFromClient.cpp
  Userland/Services/WebSocket/ConnectionFromClient.h
  Userland/Services/WebSocket/WebSocketServer.ipc
  Userland/Utilities/headless-browser.cpp
Labels: ✅ pr-community-approved

#17247 PixelPaint: Update text tool font color on primary color change
  Userland/Applications/PixelPaint/Tools/TextTool.cpp
  Userland/Applications/PixelPaint/Tools/TextTool.h
Labels: 👀 pr-needs-review

#17278 Piano: Propagate errors in PlayerWidget
  Userland/Applications/Piano/MainWidget.cpp
  Userland/Applications/Piano/MainWidget.h
  Userland/Applications/Piano/PlayerWidget.cpp
  Userland/Applications/Piano/PlayerWidget.h
  Userland/Applications/Piano/main.cpp
Labels: 👀 pr-needs-review

#17277 CMake: Set DWARF version before the debug information level
  Meta/CMake/serenity_compile_options.cmake
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17288 Base: Add British English Apple Macintosh keymap
  Base/res/keymaps/en-gb-macintosh.json
Labels: 👀 pr-needs-review

#17296 Kernel: Fix usermode verification in ptrace with PT_SETREGS
  Kernel/Syscalls/ptrace.cpp
Labels: 👀 pr-needs-review

#17299 SystemServer: Propagate errors properly in the main code
  Userland/Services/SystemServer/main.cpp
Labels: 👀 pr-needs-review

#17070 grep: Port to `Core::Stream`
  Userland/Utilities/grep.cpp
Labels: 👀 pr-needs-review

#17021 TextEditor: Port to Core::Stream
  Userland/Applications/TextEditor/MainWidget.cpp
  Userland/Applications/TextEditor/MainWidget.h
  Userland/Applications/TextEditor/main.cpp
Labels: 👀 pr-needs-review

#17300 Kernel/aarch64: Include Error.h to fix aarch64 missing ErrorOr
  Kernel/API/Syscall.h
Labels: 👀 pr-needs-review

#17303 Base: Fix typo of MasterWrod.af
  Base/res/apps/MasterWord.af
Labels: 👀 pr-needs-review

#17305 Base: Add more emoji
  Base/res/emoji/U+1F3C4.png
  Base/res/emoji/U+1F3C4_U+200D_U+2640.png
  Base/res/emoji/U+1F3C4_U+200D_U+2642.png
  Base/res/emoji/U+1F4F4.png
  Base/res/emoji/U+1F6AD.png
  Base/res/emoji/U+1F933.png
  Base/res/emoji/U+1F94B.png
Labels: 👀 pr-needs-review

#17307 LibPDF: Fix clipping of painting operations
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: 👀 pr-needs-review

#17294 Documentation: Reorganize Ladybird build docs to put easy path first
  Documentation/LadybirdBuildInstructions.md
Labels: 👀 pr-needs-review

#17295 Kernel+SystemServer+Base: Introduce the RAMFS filesystem
  Base/etc/fstab
  Base/usr/share/man/man2/mount.md
  Documentation/Kernel/RAMFS.md
  Kernel/CMakeLists.txt
  Kernel/FileSystem/RAMFS/FileSystem.cpp
  Kernel/FileSystem/RAMFS/FileSystem.h
  Kernel/FileSystem/RAMFS/Inode.cpp
  Kernel/FileSystem/RAMFS/Inode.h
  Kernel/FileSystem/TmpFS/FileSystem.cpp
  Kernel/Forward.h
  Kernel/Syscalls/mount.cpp
  Userland/Services/SystemServer/main.cpp
Labels: 👀 pr-needs-review

#17297 Documentation: Add formatting section to nvim documenation
  Documentation/NvimConfiguration.md
Labels: 👀 pr-needs-review

#17112 Base: Add a quote to the fortunes database
  Base/res/fortunes.json
Labels: 👀 pr-needs-review

#17178 AK: Use constexpr instead of consteval on OpenBSD
  AK/String.h
Labels: 👀 pr-needs-review

#17291 Calculator: Treat constants and pasted numbers as input
  Userland/Applications/Calculator/CalculatorWidget.cpp
  Userland/Applications/Calculator/CalculatorWidget.h
  Userland/Applications/Calculator/Keypad.cpp
  Userland/Applications/Calculator/Keypad.h
  Userland/Applications/Calculator/main.cpp
Labels: 👀 pr-needs-review

#17317 LibSQL: Actually print an error message after failing to launch a server
  Userland/Libraries/LibSQL/SQLClient.cpp
Labels: 👀 pr-needs-review

#17318 LibGfx: Extract a variable in ICC TextDescriptionTagData
  Userland/Libraries/LibGfx/ICC/TagTypes.cpp
Labels: 👀 pr-needs-review

#17314 Ports/git: Update to 2.39.1
  Ports/AvailablePorts.md
  Ports/git/package.sh
Labels: 👀 pr-needs-review

#17315 Ports/openssl: Update to 1.1.1s
  Ports/AvailablePorts.md
  Ports/openssl/package.sh
Labels: 👀 pr-needs-review

#17316 Ports/nasm: Update to 2.16.01
  Ports/AvailablePorts.md
  Ports/nasm/package.sh
Labels: 👀 pr-needs-review

#17319 AK: Always define ak_assertion_failed, even when NDEBUG is false
  AK/Assertions.cpp
  AK/Assertions.h
Labels: 👀 pr-needs-review

#17320 Kernel: Fix CPUInfo error propagation fixme
  Kernel/FileSystem/SysFS/Subsystems/Kernel/CPUInfo.cpp
Labels: 👀 pr-needs-review

#17331 Kernel: Pass `ipv4_packet_size` to `ipv4.set_length()`
  Kernel/Net/NetworkAdapter.cpp
Labels: 👀 pr-needs-review

#17336 LibGfx: Fix comment typo in ICC code
  Userland/Libraries/LibGfx/ICC/TagTypes.cpp
Labels: 👀 pr-needs-review

#17337 Meta: Use proper abbreviation for WebAssembly in README
  README.md
Labels: 👀 pr-needs-review

#17310 Base: Add some characters to Katica Regular 10
  Base/res/fonts/KaticaRegular10.font
Labels: 👀 pr-needs-review

#17325 Ports/nano: Update to 7.2
  Ports/AvailablePorts.md
  Ports/nano/package.sh
Labels: 👀 pr-needs-review

#17323 Ports/sed: Update to 4.9
  Ports/AvailablePorts.md
  Ports/sed/package.sh
Labels: 👀 pr-needs-review

#17322 Ports/grep: Update to 3.8
  Ports/AvailablePorts.md
  Ports/grep/package.sh
Labels: 👀 pr-needs-review

#17326 LibGfx: Add table size validation for ICC lut16Type
  Userland/Libraries/LibGfx/ICC/TagTypes.cpp
Labels: 👀 pr-needs-review

#17349 Meta: Automatically select best apt mirror
  .github/workflows/cmake.yml
  .github/workflows/libjs-test262.yml
  .github/workflows/pvs-studio-static-analysis.yml
  .github/workflows/serenity-js-artifacts.yml
  .github/workflows/sonar-cloud-static-analysis.yml
  .github/workflows/wasm.yml
  Meta/Azure/Setup.yml
Labels: 👀 pr-needs-review

#17348 Settings: Improve default window size
  Userland/Applications/Settings/main.cpp
Labels: 👀 pr-needs-review

#17357 LibGfx+icc: Read namedColor2Type
  Userland/Libraries/LibGfx/ICC/Profile.cpp
  Userland/Libraries/LibGfx/ICC/TagTypes.cpp
  Userland/Libraries/LibGfx/ICC/TagTypes.h
  Userland/Utilities/icc.cpp
Labels: 👀 pr-needs-review

#17361 LibGfx+icc: Read signatureType
  Userland/Libraries/LibGfx/ICC/Profile.cpp
  Userland/Libraries/LibGfx/ICC/TagTypes.cpp
  Userland/Libraries/LibGfx/ICC/TagTypes.h
  Userland/Utilities/icc.cpp
Labels: 👀 pr-needs-review

#17367 LibGfx: Add ICC v2 tags to tag list
  Userland/Libraries/LibGfx/ICC/Profile.cpp
  Userland/Libraries/LibGfx/ICC/Tags.h
Labels: 👀 pr-needs-review

#17368 LibGfx: Add another profile ID to ICC quirk list
  Userland/Libraries/LibGfx/ICC/Profile.cpp
Labels: 👀 pr-needs-review

#17369 LibGfx+icc: Read cicpType
  Userland/Libraries/LibGfx/ICC/Profile.cpp
  Userland/Libraries/LibGfx/ICC/TagTypes.cpp
  Userland/Libraries/LibGfx/ICC/TagTypes.h
  Userland/Utilities/CMakeLists.txt
  Userland/Utilities/icc.cpp
Labels: 👀 pr-needs-review

#17306 js: Remove usage of DeprecatedString
  Userland/Utilities/js.cpp
Labels: 👀 pr-needs-review

#17372 LibCrypto: Do a simple copy for buffered GHash bytes
  Userland/Libraries/LibCrypto/Authentication/GHash.cpp
Labels: 👀 pr-needs-review

#17287 LibGfx: Port `DDSLoader` to `AK::Stream`
  Userland/Libraries/LibGfx/DDSLoader.cpp
  Userland/Libraries/LibGfx/DDSLoader.h
Labels: 👀 pr-needs-review

#17343 LibCore: Propagate errors in SecretString
  Userland/Libraries/LibCore/GetPassword.cpp
  Userland/Libraries/LibCore/SecretString.cpp
  Userland/Libraries/LibCore/SecretString.h
Labels: 👀 pr-needs-review

#17355 Kernel: Use `AK::Stream` to write packed binary data
  Kernel/CMakeLists.txt
  Kernel/FileSystem/Ext2FS/Inode.cpp
  Kernel/FileSystem/OpenFileDescription.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17378 AK: Remove the deprecated Stream implementation :^)
  AK/DeprecatedMemoryStream.h
  AK/DeprecatedStream.h
  AK/DeprecatedString.cpp
  AK/DeprecatedString.h
  AK/Endian.h
  AK/Forward.h
  Tests/AK/CMakeLists.txt
  Tests/AK/TestDeprecatedMemoryStream.cpp
  Userland/Libraries/LibCore/Stream.cpp
  Userland/Libraries/LibCore/Stream.h
  Userland/Libraries/LibGfx/GIFLoader.cpp
Labels: 👀 pr-needs-review

#17358 PixelPaint: Use image coordinates for bucket tool bounds checking
  Userland/Applications/PixelPaint/Tools/BucketTool.cpp
Labels: 👀 pr-needs-review

#17282 PixelPaint: Correct move tool alignment with the layer boundary
  Userland/Applications/PixelPaint/Tools/MoveTool.cpp
Labels: 👀 pr-needs-review

#17335 LibGfx+icc: Implement half of lutAToBType and lutBToAType
  Userland/Libraries/LibGfx/ICC/Profile.cpp
  Userland/Libraries/LibGfx/ICC/TagTypes.cpp
  Userland/Libraries/LibGfx/ICC/TagTypes.h
  Userland/Utilities/icc.cpp
Labels: 👀 pr-needs-review

#17302 LibGfx: Make checkerboard patterns static when panning
  Userland/Libraries/LibGfx/Painter.cpp
Labels: 👀 pr-needs-review

#16509 Piano: Show a progress window when exporting WAV
  Userland/Applications/Piano/AudioPlayerLoop.cpp
  Userland/Applications/Piano/AudioPlayerLoop.h
  Userland/Applications/Piano/CMakeLists.txt
  Userland/Applications/Piano/ExportProgressWidget.gml
  Userland/Applications/Piano/ExportProgressWindow.cpp
  Userland/Applications/Piano/ExportProgressWindow.h
  Userland/Applications/Piano/main.cpp
Labels: 👀 pr-needs-review

#17384 SoundPlayer: Fix logic bug in bars visualization
  Userland/Applications/SoundPlayer/BarsVisualizationWidget.cpp
Labels: ✅ pr-community-approved

#17408 AK: Allow explicitly copying and provide `is_errno` for Kernel Errors
  AK/Error.h
  AK/Stream.cpp
Labels: 👀 pr-needs-review

#17410 LibWeb: Add missing GCPtr.h includes to Fetch headers
  Userland/Libraries/LibWeb/Fetch/Body.h
  Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.h
  Userland/Libraries/LibWeb/Fetch/Fetching/PendingResponse.h
  Userland/Libraries/LibWeb/Fetch/Headers.h
  Userland/Libraries/LibWeb/Fetch/HeadersIterator.h
  Userland/Libraries/LibWeb/Fetch/Infrastructure/ConnectionTimingInfo.h
  Userland/Libraries/LibWeb/Fetch/Infrastructure/FetchAlgorithms.h
  Userland/Libraries/LibWeb/Fetch/Infrastructure/FetchController.h
  Userland/Libraries/LibWeb/Fetch/Infrastructure/FetchParams.h
  Userland/Libraries/LibWeb/Fetch/Infrastructure/FetchTimingInfo.h
  Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Bodies.h
  Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Headers.h
  Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Requests.h
  Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.h
  Userland/Libraries/LibWeb/Fetch/Request.h
  Userland/Libraries/LibWeb/Fetch/Response.h
Labels: 👀 pr-needs-review

#17409 CI: Add script to post mastodon toots for commits on master
  .github/workflows/social-media.yml
  Meta/toot-commits.js
Labels: 👀 pr-needs-review

#17411 LibGfx+icc: Read viewingConditionsType
  Userland/Libraries/LibGfx/ICC/Profile.cpp
  Userland/Libraries/LibGfx/ICC/TagTypes.cpp
  Userland/Libraries/LibGfx/ICC/TagTypes.h
  Userland/Utilities/icc.cpp
Labels: 👀 pr-needs-review

#17396 LibGfx+icc: Read chromaticityTag
  Userland/Libraries/LibGfx/ICC/Profile.cpp
  Userland/Libraries/LibGfx/ICC/TagTypes.cpp
  Userland/Libraries/LibGfx/ICC/TagTypes.h
  Userland/Utilities/icc.cpp
Labels: 👀 pr-needs-review

#17403 LibWeb: Use device pixels for transform rect of stacking context
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Labels: 👀 pr-needs-review

#17389 DisplaySettings: Don't crash when selecting a wallpaper
  Userland/Applications/DisplaySettings/BackgroundSettingsWidget.cpp
Labels: 👀 pr-needs-review

#17412 LibGfx+icc: Stringify known signatureType values
  Userland/Libraries/LibGfx/ICC/TagTypes.cpp
  Userland/Libraries/LibGfx/ICC/TagTypes.h
  Userland/Utilities/icc.cpp
Labels: 👀 pr-needs-review

#17413 LibGfx: Validate ICC cicpTag some more
  Userland/Libraries/LibGfx/ICC/Profile.cpp
Labels: 👀 pr-needs-review

#17417 LibCore: Fix wrong call to stat on the Core::System::lstat method
  Userland/Libraries/LibCore/System.cpp
Labels: 👀 pr-needs-review

#17416 LibVideo/VP9: Drop the decoder intermediate bounds checks
  Userland/Libraries/LibVideo/VP9/Decoder.cpp
  Userland/Libraries/LibVideo/VP9/Decoder.h
Labels: 👀 pr-needs-review

#17422 Keymaps: Stop pt-br's r-shift printing "?"
  Base/res/keymaps/pt-br.json
Labels: 👀 pr-needs-review

#17344 Toolchain: Add fuse2fs to serenity.nix
  Toolchain/serenity.nix
Labels: 👀 pr-needs-review

#17419 LibGfx: Add scaffolding for curves in lutAToBType and lutBToAType
  Userland/Libraries/LibGfx/ICC/TagTypes.cpp
  Userland/Libraries/LibGfx/ICC/TagTypes.h
Labels: 👀 pr-needs-review

#17423 LibJS: Add missing assignment to offset_string in ZDT conversion
  Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.cpp
Labels: 👀 pr-needs-review

#17426 LibGfx: Make ICC code handle out-of-memory situations better
  Userland/Libraries/LibGfx/ICC/Profile.cpp
  Userland/Libraries/LibGfx/ICC/TagTypes.cpp
Labels: 👀 pr-needs-review

#17365 LibWeb: Add tests for flex formatting context
  Tests/LibWeb/Layout/expected/flex-auto.txt
  Tests/LibWeb/Layout/expected/flex-column-constained-wrap.txt
  Tests/LibWeb/Layout/expected/flex-column-constrained-nowrap.txt
  Tests/LibWeb/Layout/expected/flex-column-height-constrained-width-constrained.txt
  Tests/LibWeb/Layout/expected/flex-column-height-constrained.txt
  Tests/LibWeb/Layout/expected/flex-container-constrained-nowrap.txt
  Tests/LibWeb/Layout/expected/flex-container-constrained-wrap.txt
  Tests/LibWeb/Layout/expected/flex-container-width-constrained.txt
  Tests/LibWeb/Layout/expected/flex-grow-0-column.txt
  Tests/LibWeb/Layout/expected/flex-grow-1.txt
  Tests/LibWeb/Layout/expected/flex-grow-2.txt
  Tests/LibWeb/Layout/expected/flex-row.txt
  Tests/LibWeb/Layout/expected/flex-shrink-1.txt
  Tests/LibWeb/Layout/expected/flex-shrink-2.txt
  Tests/LibWeb/Layout/expected/flex-shrink-3.txt
  Tests/LibWeb/Layout/input/flex-auto.html
  Tests/LibWeb/Layout/input/flex-column-constained-wrap.html
  Tests/LibWeb/Layout/input/flex-column-constrained-nowrap.html
  Tests/LibWeb/Layout/input/flex-column-height-constrained-width-constrained.html
  Tests/LibWeb/Layout/input/flex-column-height-constrained.html
  Tests/LibWeb/Layout/input/flex-container-constrained-nowrap.html
  Tests/LibWeb/Layout/input/flex-container-constrained-wrap.html
  Tests/LibWeb/Layout/input/flex-container-width-constrained.html
  Tests/LibWeb/Layout/input/flex-grow-0-column.html
  Tests/LibWeb/Layout/input/flex-grow-1.html
  Tests/LibWeb/Layout/input/flex-grow-2.html
  Tests/LibWeb/Layout/input/flex-row.html
  Tests/LibWeb/Layout/input/flex-shrink-1.html
  Tests/LibWeb/Layout/input/flex-shrink-2.html
  Tests/LibWeb/Layout/input/flex-shrink-3.html
Labels: 👀 pr-needs-review

#17420 LibWeb: Implement Headers.getSetCookie()
  Userland/Libraries/LibWeb/Fetch/Headers.cpp
  Userland/Libraries/LibWeb/Fetch/Headers.h
  Userland/Libraries/LibWeb/Fetch/Headers.idl
  Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Headers.cpp
Labels: 👀 pr-needs-review

#17352 FileManager: Factorize code to handle drag-and-drop
  Userland/Applications/FileManager/DirectoryView.cpp
  Userland/Applications/FileManager/FileUtils.cpp
  Userland/Applications/FileManager/FileUtils.h
  Userland/Applications/FileManager/main.cpp
Labels: 👀 pr-needs-review

#17436 WindowServer: Restore cursor animation
  Userland/Services/WindowServer/Compositor.cpp
Labels: 👀 pr-needs-review

#17425 LibJS/Temporal: Allow annotations after YYYY-MM and MM-DD
  Userland/Libraries/LibJS/Runtime/ErrorTypes.h
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/ISO8601.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/ISO8601.h
  Userland/Libraries/LibJS/Tests/builtins/Temporal/Calendar/Calendar.from.js
  Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainMonthDay/PlainMonthDay.from.js
  Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainYearMonth/PlainYearMonth.from.js
  Userland/Libraries/LibJS/Tests/builtins/Temporal/TimeZone/TimeZone.from.js
Labels: 👀 pr-needs-review

#17444 LibWeb: Re-implement checkbox painting using the UA stylesheet
  Userland/Libraries/LibWeb/CSS/Default.css
  Userland/Libraries/LibWeb/Painting/CheckBoxPaintable.cpp
  Userland/Libraries/LibWeb/Painting/CheckBoxPaintable.h
Labels: 👀 pr-needs-review

#17447 LibGUI: Callback with the clamped value of Sliders on a jump to cursor
  Userland/Libraries/LibGUI/Slider.cpp
Labels: 👀 pr-needs-review

#17450 LibWeb: Use 'auto& vm =' once at beginning to reduce noise
  Userland/Libraries/LibWeb/HTML/FormControlInfrastructure.cpp
Labels: 👀 pr-needs-review

#17439 Utilities/netstat: Don't unveil /tmp/portal/lookup for numerical output
  Userland/Utilities/netstat.cpp
Labels: 👀 pr-needs-review

#17458 Utilities/arp: Don't unveil /tmp/portal/lookup for numerical output
  Userland/Utilities/arp.cpp
Labels: 👀 pr-needs-review

#17457 LibWeb: Move setting of FormDataPrototype to initialize()
  Userland/Libraries/LibWeb/XHR/FormData.cpp
  Userland/Libraries/LibWeb/XHR/FormData.h
Labels: 👀 pr-needs-review

#17438 Userland: Use allocation-failure safe functions where it's easy
  Userland/DevTools/HackStudio/ProjectConfig.cpp
  Userland/DevTools/Profiler/Profile.cpp
  Userland/Libraries/LibGLSL/Compiler.cpp
  Userland/Libraries/LibGLSL/Linker.cpp
Labels: 👀 pr-needs-review

#17449 LibVideo/VP9: Convert the Parser to use AK/BitStream.h
  Userland/Libraries/LibVideo/CMakeLists.txt
  Userland/Libraries/LibVideo/VP9/BitStream.cpp
  Userland/Libraries/LibVideo/VP9/BitStream.h
  Userland/Libraries/LibVideo/VP9/BooleanDecoder.cpp
  Userland/Libraries/LibVideo/VP9/BooleanDecoder.h
  Userland/Libraries/LibVideo/VP9/Context.h
  Userland/Libraries/LibVideo/VP9/Parser.cpp
  Userland/Libraries/LibVideo/VP9/Parser.h
  Userland/Libraries/LibVideo/VP9/TreeParser.cpp
  Userland/Libraries/LibVideo/VP9/TreeParser.h
Labels: 👀 pr-needs-review

#17429 LibPDF: Add more built-in SIDs
  Userland/Libraries/LibPDF/Fonts/CFF.cpp
  Userland/Libraries/LibPDF/Fonts/CFF.h
Labels: 👀 pr-needs-review

#17455 LibGUI+PixelPaint: Port GUI::ValueSlider's suffix to the new String
  Userland/Applications/PixelPaint/Filters/Bloom.cpp
  Userland/Applications/PixelPaint/Filters/FastBoxBlur.cpp
  Userland/Applications/PixelPaint/Filters/Sepia.cpp
  Userland/Applications/PixelPaint/Tools/BrushTool.cpp
  Userland/Applications/PixelPaint/Tools/BucketTool.cpp
  Userland/Applications/PixelPaint/Tools/CloneTool.cpp
  Userland/Applications/PixelPaint/Tools/EllipseTool.cpp
  Userland/Applications/PixelPaint/Tools/EraseTool.cpp
  Userland/Applications/PixelPaint/Tools/GuideTool.cpp
  Userland/Applications/PixelPaint/Tools/LineTool.cpp
  Userland/Applications/PixelPaint/Tools/PenTool.cpp
  Userland/Applications/PixelPaint/Tools/RectangleSelectTool.cpp
  Userland/Applications/PixelPaint/Tools/RectangleTool.cpp
  Userland/Applications/PixelPaint/Tools/SprayTool.cpp
  Userland/Applications/PixelPaint/Tools/WandSelectTool.cpp
  Userland/Applications/PixelPaint/Tools/ZoomTool.cpp
  Userland/Libraries/LibGUI/ValueSlider.cpp
  Userland/Libraries/LibGUI/ValueSlider.h
Labels: 👀 pr-needs-review

#17465 Base: Add a quote to the fortunes database
  Base/res/fortunes.json
Labels: 👀 pr-needs-review

#17464 LibWeb: Clarify WebIDL::Promise as an alias for JS::PromiseCapability
  Userland/Libraries/LibWeb/Fetch/FetchMethod.cpp
  Userland/Libraries/LibWeb/Fetch/FetchMethod.h
  Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Bodies.cpp
  Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Bodies.h
  Userland/Libraries/LibWeb/WebIDL/Promise.cpp
  Userland/Libraries/LibWeb/WebIDL/Promise.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17463 LibWeb: A couple bug fixes for algorithm 'construct the entry list given a form'
  Userland/Libraries/LibWeb/HTML/FormControlInfrastructure.cpp
Labels: 👀 pr-needs-review

#17469 Documentation: Fix Ladybird debug instructions
  Documentation/LadybirdBuildInstructions.md
Labels: 👀 pr-needs-review

#17476 LibGfx: Tweak how ICC::Profile gets constructed
  Userland/Libraries/LibGfx/ICC/Profile.cpp
  Userland/Libraries/LibGfx/ICC/Profile.h
Labels: 👀 pr-needs-review

#17452 Piano: Fix insertion and deletion of notes
  Userland/Applications/Piano/RollWidget.cpp
  Userland/Applications/Piano/RollWidget.h
  Userland/Libraries/LibDSP/Clip.cpp
  Userland/Libraries/LibDSP/Clip.h
  Userland/Libraries/LibDSP/Track.cpp
  Userland/Libraries/LibDSP/Track.h
Labels: ✅ pr-community-approved

#16979 HexEditor: Add strings to the value inspector
  Userland/Applications/HexEditor/CMakeLists.txt
  Userland/Applications/HexEditor/HexEditor.cpp
  Userland/Applications/HexEditor/HexEditor.h
  Userland/Applications/HexEditor/HexEditorWidget.cpp
  Userland/Applications/HexEditor/ValueInspectorModel.h
Labels: 👀 pr-needs-review

#17481 LibJS: Keep escaping forward slashes
  Userland/Libraries/LibJS/Runtime/RegExpObject.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17484 LibGfx: Move QOIWriter implementation-only things into cpp file
  Userland/Libraries/LibGfx/QOIWriter.cpp
  Userland/Libraries/LibGfx/QOIWriter.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17486 Everywhere: Change all XXX into FIXME or remove as appropriate
  Kernel/Arch/aarch64/CPUID.cpp
  Kernel/Arch/aarch64/CPUID.h
  Userland/DevTools/UserspaceEmulator/SoftFPU.cpp
  Userland/Libraries/LibC/elf.h
Labels: 👀 pr-needs-review

#17312 Ladybird: Close tab clicking wheel of the mouse
  Ladybird/BrowserWindow.cpp
  Ladybird/BrowserWindow.h
Labels: 👀 pr-needs-review

#17473 Ports/dos2unix: Update to 7.4.4
  Ports/AvailablePorts.md
  Ports/dos2unix/package.sh
Labels: 👀 pr-needs-review

#17466 Add some emoji
  Base/res/emoji/U+1F37E.png
  Base/res/emoji/U+1F38D.png
  Base/res/emoji/U+1F5FE.png
  Base/res/emoji/U+1F960.png
  Base/res/emoji/U+1F985.png
  Base/res/emoji/U+1FAC5.png
Labels: 👀 pr-needs-review

#17462 Base: Improve eye emoji and add mouth emoji
  Base/res/emoji/U+1F441.png
  Base/res/emoji/U+1F444.png
Labels: 👀 pr-needs-review

#17489 LibFileSystemAccessClient: Remove the deprecated API
  Userland/Applications/CrashReporter/main.cpp
  Userland/Applications/Spreadsheet/main.cpp
  Userland/Applications/ThemeEditor/MainWidget.cpp
  Userland/Applications/ThemeEditor/main.cpp
  Userland/Libraries/LibFileSystemAccessClient/Client.cpp
  Userland/Libraries/LibFileSystemAccessClient/Client.h
Labels: 👀 pr-needs-review

#17497 Presenter: Fix unintentional U+00A0 codepoint in text
  Base/usr/share/man/man5/presenter.md
Labels: 👀 pr-needs-review

#17496 LibJS: Actually escape \n|\r|LS|PS when escaping RegExp.source
  Userland/Libraries/LibJS/Runtime/RegExpObject.cpp
Labels: 👀 pr-needs-review

#17445 PixelPaint: Propagate errors from making tool property widgets
  Userland/Applications/PixelPaint/ToolPropertiesWidget.cpp
  Userland/Applications/PixelPaint/ToolPropertiesWidget.h
  Userland/Applications/PixelPaint/Tools/BrushTool.cpp
  Userland/Applications/PixelPaint/Tools/BrushTool.h
  Userland/Applications/PixelPaint/Tools/BucketTool.cpp
  Userland/Applications/PixelPaint/Tools/BucketTool.h
  Userland/Applications/PixelPaint/Tools/CloneTool.cpp
  Userland/Applications/PixelPaint/Tools/CloneTool.h
  Userland/Applications/PixelPaint/Tools/EllipseTool.cpp
  Userland/Applications/PixelPaint/Tools/EllipseTool.h
  Userland/Applications/PixelPaint/Tools/EraseTool.cpp
  Userland/Applications/PixelPaint/Tools/EraseTool.h
  Userland/Applications/PixelPaint/Tools/GradientTool.cpp
  Userland/Applications/PixelPaint/Tools/GradientTool.h
  Userland/Applications/PixelPaint/Tools/GuideTool.cpp
  Userland/Applications/PixelPaint/Tools/GuideTool.h
  Userland/Applications/PixelPaint/Tools/LassoSelectTool.cpp
  Userland/Applications/PixelPaint/Tools/LassoSelectTool.h
  Userland/Applications/PixelPaint/Tools/LineTool.cpp
  Userland/Applications/PixelPaint/Tools/LineTool.h
  Userland/Applications/PixelPaint/Tools/MoveTool.cpp
  Userland/Applications/PixelPaint/Tools/MoveTool.h
  Userland/Applications/PixelPaint/Tools/PenTool.cpp
  Userland/Applications/PixelPaint/Tools/PenTool.h
  Userland/Applications/PixelPaint/Tools/PickerTool.cpp
  Userland/Applications/PixelPaint/Tools/PickerTool.h
  Userland/Applications/PixelPaint/Tools/PolygonalSelectTool.cpp
  Userland/Applications/PixelPaint/Tools/PolygonalSelectTool.h
  Userland/Applications/PixelPaint/Tools/RectangleSelectTool.cpp
  Userland/Applications/PixelPaint/Tools/RectangleSelectTool.h
  Userland/Applications/PixelPaint/Tools/RectangleTool.cpp
  Userland/Applications/PixelPaint/Tools/RectangleTool.h
  Userland/Applications/PixelPaint/Tools/SprayTool.cpp
  Userland/Applications/PixelPaint/Tools/SprayTool.h
  Userland/Applications/PixelPaint/Tools/TextTool.cpp
  Userland/Applications/PixelPaint/Tools/TextTool.h
  Userland/Applications/PixelPaint/Tools/Tool.h
  Userland/Applications/PixelPaint/Tools/WandSelectTool.cpp
  Userland/Applications/PixelPaint/Tools/WandSelectTool.h
  Userland/Applications/PixelPaint/Tools/ZoomTool.cpp
  Userland/Applications/PixelPaint/Tools/ZoomTool.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17490 LibGfx: Remove `Bitmap::load_from_fd_and_close()`
  Userland/Libraries/LibGfx/Bitmap.cpp
  Userland/Libraries/LibGfx/Bitmap.h
Labels: 👀 pr-needs-review

#17370 Text editor delete emoji on grapheme boundaries
  Userland/Libraries/LibGUI/TextDocument.cpp
  Userland/Libraries/LibGUI/TextDocument.h
  Userland/Libraries/LibGUI/TextEditor.cpp
Labels: 👀 pr-needs-review

#17492 LibGfx: Read embedded ICC profiles in .bmp files
  Userland/Libraries/LibGfx/BMPLoader.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17508 LibWeb: Convert FormData to String and Vector storage
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
  Userland/Libraries/LibWeb/HTML/FormControlInfrastructure.cpp
  Userland/Libraries/LibWeb/HTML/FormControlInfrastructure.h
  Userland/Libraries/LibWeb/XHR/FormData.cpp
  Userland/Libraries/LibWeb/XHR/FormData.h
  Userland/Libraries/LibWeb/XHR/FormData.idl
Labels: 👀 pr-needs-review, ✅ pr-community-approved

#17510 LibGfx: Minorly simplify BMPLoader's decode_bmp_dib()
  Userland/Libraries/LibGfx/BMPLoader.cpp
Labels: 👀 pr-needs-review

#17499 PixelPaint: Propagate errors from making filter settings widgets
  Userland/Applications/PixelPaint/FilterGallery.cpp
  Userland/Applications/PixelPaint/FilterGallery.h
  Userland/Applications/PixelPaint/Filters/Bloom.cpp
  Userland/Applications/PixelPaint/Filters/Bloom.h
  Userland/Applications/PixelPaint/Filters/FastBoxBlur.cpp
  Userland/Applications/PixelPaint/Filters/FastBoxBlur.h
  Userland/Applications/PixelPaint/Filters/Filter.cpp
  Userland/Applications/PixelPaint/Filters/Filter.h
  Userland/Applications/PixelPaint/Filters/HueAndSaturation.cpp
  Userland/Applications/PixelPaint/Filters/HueAndSaturation.h
  Userland/Applications/PixelPaint/Filters/Median.cpp
  Userland/Applications/PixelPaint/Filters/Median.h
  Userland/Applications/PixelPaint/Filters/Sepia.cpp
  Userland/Applications/PixelPaint/Filters/Sepia.h
Labels: 👀 pr-needs-review

#17520 AK: Fix 64-bit alignment issue in shared-superstring substrings
  AK/String.cpp
  Tests/AK/TestString.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17501 LibGUI: Skip over grapheme clusters on left/right arrow key presses
  Userland/Libraries/LibGUI/EditingEngine.cpp
Labels: 👀 pr-needs-review

#17524 AK: Fix printing of negative FixedPoint values
  AK/FixedPoint.h
  AK/Format.cpp
  AK/Format.h
  Tests/AK/TestFixedPoint.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17522 LibJS: Use substrings-with-superstrings in Intl.NumberFormat's grouping
  Userland/Libraries/LibJS/Runtime/Intl/NumberFormat.cpp
Labels: 👀 pr-needs-review

#17528 Kernel: Dont crash if power states gets set to an invalid value
  Kernel/FileSystem/SysFS/Subsystems/Kernel/PowerStateSwitch.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17527 LibWeb: Transform translate() values to device pixels before painting
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Labels: 👀 pr-needs-review

#17381 Base: Improve BrickGame documentation
  Base/usr/share/man/man6/BrickGame.md
Labels: 👀 pr-needs-review

#17414 js: Save REPL history when exiting interpreter with `exit()`
  Userland/Utilities/js.cpp
Labels: 👀 pr-needs-review

#17401 LibGUI: Allow clipboard items to have no associated data
  Userland/Libraries/LibGUI/Clipboard.cpp
Labels: 👀 pr-needs-review

#17215 PixelPaint: Enable more text tool keyboard shortcuts
  Userland/Applications/PixelPaint/Tools/TextTool.cpp
  Userland/Applications/PixelPaint/Tools/TextTool.h
Labels: 👀 pr-needs-review

#17526 LibGfx: Correctly handle JPEG image with restart markers
  Userland/Libraries/LibGfx/JPEGLoader.cpp
Labels: ✅ pr-community-approved

#17533 Kernel: Remove unnecessary include from SysFS PowerStateSwitch code
  Kernel/FileSystem/SysFS/Subsystems/Kernel/PowerStateSwitch.cpp
Labels: 👀 pr-needs-review

#17532 LibGfx: Rename all `JPG_*` macros to `JPEG_*` in JPEGLoader
  Userland/Libraries/LibGfx/JPEGLoader.cpp
Labels: 👀 pr-needs-review

#17535 AK/StackInfo: Add support for OpenBSD pthreads
  AK/StackInfo.cpp
Labels: 👀 pr-needs-review

#17537 Base: Add and update a few body part/hand emojis
  Base/res/emoji/U+1F442.png
  Base/res/emoji/U+1F443.png
  Base/res/emoji/U+1F445.png
  Base/res/emoji/U+1F90C.png
  Base/res/emoji/U+1F918.png
Labels: 👀 pr-needs-review

#17525 Kernel+Userland: Add constants subdirectory at /sys/kernel directory
  Base/usr/share/man/man7/sys.md
  Kernel/CMakeLists.txt
  Kernel/FileSystem/SysFS/Subsystems/Kernel/CommandLine.cpp
  Kernel/FileSystem/SysFS/Subsystems/Kernel/CommandLine.h
  Kernel/FileSystem/SysFS/Subsystems/Kernel/Constants/ConstantInformation.cpp
  Kernel/FileSystem/SysFS/Subsystems/Kernel/Constants/ConstantInformation.h
  Kernel/FileSystem/SysFS/Subsystems/Kernel/Constants/Directory.cpp
  Kernel/FileSystem/SysFS/Subsystems/Kernel/Constants/Directory.h
  Kernel/FileSystem/SysFS/Subsystems/Kernel/Directory.cpp
  Kernel/FileSystem/SysFS/Subsystems/Kernel/LoadBase.cpp
  Kernel/FileSystem/SysFS/Subsystems/Kernel/LoadBase.h
  Kernel/FileSystem/SysFS/Subsystems/Kernel/SystemMode.cpp
  Kernel/FileSystem/SysFS/Subsystems/Kernel/SystemMode.h
  Userland/Libraries/LibSymbolication/Symbolication.cpp
  Userland/Services/SystemServer/main.cpp
Labels: 👀 pr-needs-review

#17539 LibGfx: Fix a slight mistake in AA ellipse error calculation
  Userland/Libraries/LibGfx/AntiAliasingPainter.cpp
Labels: 👀 pr-needs-review

#17540 HackStudio: Make wrapping modes consistent
  Userland/DevTools/HackStudio/HackStudioWidget.cpp
  Userland/DevTools/HackStudio/HackStudioWidget.h
Labels: 👀 pr-needs-review

#17541 WebDriver: Add computedlabel endpoint
  Userland/Libraries/LibWeb/WebDriver/Client.cpp
  Userland/Libraries/LibWeb/WebDriver/Client.h
  Userland/Services/WebContent/WebDriverClient.ipc
  Userland/Services/WebContent/WebDriverConnection.cpp
  Userland/Services/WebContent/WebDriverConnection.h
  Userland/Services/WebDriver/Client.cpp
  Userland/Services/WebDriver/Client.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17543 LibWeb: Replace `RefPtr` with `ValueComparingRefPtr` in StyleValue
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
  Userland/Libraries/LibWeb/CSS/StyleValue.cpp
  Userland/Libraries/LibWeb/CSS/StyleValue.h
Labels: 👀 pr-needs-review

#17547 LibCore: Implement socket credentials for NetBSD
  Userland/Libraries/LibCore/Socket.cpp
Labels: ✅ pr-community-approved

#17548 LibCore: All BSDs need sig_t instead of sighandler_t
  Userland/Libraries/LibCore/System.cpp
  Userland/Libraries/LibCore/System.h
Labels: 👀 pr-needs-review

#17553 AK/StackInfo: Add support for NetBSD
  AK/StackInfo.cpp
Labels: ✅ pr-community-approved

#17552 LibCore: Enable file descriptor passing on all BSDs
  Userland/Libraries/LibCore/Socket.cpp
Labels: 👀 pr-needs-review

#17549 LibCore: Add support for NetBSD in anon_create
  Meta/Lagom/CMakeLists.txt
  Userland/Libraries/LibCore/System.cpp
Labels: 👀 pr-needs-review

#17551 LibSQL: fchmod on sockets is not supported by any BSD
  Userland/Libraries/LibSQL/SQLClient.cpp
Labels: 👀 pr-needs-review

#17154 Kernel+LibC: Support monotonic clock in clock_getres()
  Kernel/Syscalls/clock.cpp
  Kernel/Time/TimeManagement.cpp
  Kernel/Time/TimeManagement.h
Labels: 👀 pr-needs-review
