Repository SerenityOS/serenity, pull requests merged in 2023-11, with the labels that each got.

#21722 AK: Ensure unions with bitfield structs actually have correct sizes
  AK/FPControl.h
  AK/FloatingPoint.h
Labels: 👀 pr-needs-review

#21727 FlappyBug: Unify the way of getting the final score
  Userland/Games/FlappyBug/Game.cpp
  Userland/Games/FlappyBug/Game.h
Labels: 👀 pr-needs-review

#21484 LibPDF: Simplify CallSubr for type 1 font programs
  Userland/Libraries/LibPDF/Fonts/Type1FontProgram.cpp
Labels: 👀 pr-needs-review

#21725 LibPDF: Implement type 2 flex, hflex, hflex1, flex1 operators
  Userland/Libraries/LibPDF/Fonts/Type1FontProgram.cpp
Labels: 👀 pr-needs-review

#21726 LibPDF: Improve CalRGB color space handling
  Userland/Libraries/LibPDF/ColorSpace.cpp
Labels: 👀 pr-needs-review

#21562 AK: Refactor `JSONParser::consume_and_unescape_string` a bit
  AK/JsonParser.cpp
Labels: 👀 pr-needs-review

#21738 LibWeb: Account for box-sizing in grid-items width calculation
  Tests/LibWeb/Layout/expected/grid/item-with-box-sizing-border-box.txt
  Tests/LibWeb/Layout/input/grid/item-with-box-sizing-border-box.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#21729 HackStudio: Add an 'Auto Save before Build or Run' option
  Userland/DevTools/HackStudio/HackStudioWidget.cpp
  Userland/DevTools/HackStudio/HackStudioWidget.h
Labels: 👀 pr-needs-review

#21740 LibWeb: Do not unload during same-document history step application
  Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
Labels: 👀 pr-needs-review

#21748 LibJS: Avoid crash on empty stack trace
  Userland/Libraries/LibJS/Runtime/Error.cpp
Labels: 👀 pr-needs-review

#21752 LibJS: Store the bytecode accumulator in a dedicated physical register
  Userland/Libraries/LibJS/Bytecode/CommonImplementations.cpp
  Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
  Userland/Libraries/LibJS/JIT/Compiler.cpp
  Userland/Libraries/LibJS/JIT/Compiler.h
Labels: 👀 pr-needs-review

#21672 LibJS+LibJIT: Add fast paths for more binary ops with (Int32 op Int32)
  Userland/Libraries/LibJIT/Assembler.h
  Userland/Libraries/LibJS/JIT/Compiler.cpp
  Userland/Libraries/LibJS/JIT/Compiler.h
Labels: 👀 pr-needs-review

#21758 Ports/composer: Update to version 2.6.5
  Ports/AvailablePorts.md
  Ports/composer/package.sh
Labels: 👀 pr-needs-review

#21757 Ports/php: Enable curl
  Ports/php/package.sh
Labels: 👀 pr-needs-review

#21671 HackStudio: Pass the correct `VariableInfo` address to `create_index`
  Userland/DevTools/HackStudio/Debugger/VariablesModel.cpp
Labels: 👀 pr-needs-review

#21766 LibJS: Stash thrown exception in a register before executing finalizer
  Userland/Libraries/LibJS/Bytecode/Register.h
  Userland/Libraries/LibJS/JIT/Compiler.cpp
Labels: 👀 pr-needs-review

#21772 Kernel: Allow negative value for backlog in sys$listen
  Kernel/Syscalls/socket.cpp
Labels: 👀 pr-needs-review

#21769 LibWeb: Consider colgroups while calculating table grid size
  Tests/LibWeb/Layout/expected/table/colgroup-with-two-cols.txt
  Tests/LibWeb/Layout/input/table/colgroup-with-two-cols.html
  Userland/Libraries/LibWeb/Layout/TableGrid.cpp
  Userland/Libraries/LibWeb/Layout/TableGrid.h
Labels: 👀 pr-needs-review

#21639 LibWeb: Fix width of text when using bitmap fonts being 1 pixel too long
  Tests/LibWeb/Layout/expected/textnode-width-bitmap-font.txt
  Tests/LibWeb/Layout/input/textnode-width-bitmap-font.html
  Userland/Libraries/LibWeb/Layout/InlineLevelIterator.cpp
Labels: 👀 pr-needs-review

#21717 ls: use indicator for sockets and pipes
  Userland/Utilities/ls.cpp
Labels: 👀 pr-needs-review

#21537 RISC-V disassembly, part 1/N: LibELF: Add initial RISC-V support
  Userland/Libraries/LibELF/ELFABI.h
  Userland/Libraries/LibELF/Validation.cpp
Labels: 👀 pr-needs-review

#21767 LibGfx/JPEG: Refill reservoir if necessary when discarding bits
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/jpg/oss-fuzz-testcase-63815.jpg
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Labels: ✅ pr-community-approved

#21754 NotificationServer: Two display fixes
  Userland/Services/NotificationServer/NotificationWindow.cpp
  Userland/Services/NotificationServer/NotificationWindow.h
Labels: 👀 pr-needs-review

#21787 Kernel: fix panic for Nagel's algorithm
  Kernel/Net/TCPSocket.cpp
Labels: 👀 pr-needs-review

#21802 Meta: Run test262 with JIT compilation enabled in CI
  .github/workflows/libjs-test262.yml
Labels: 👀 pr-needs-review

#21805 CI: Ensure test262 and test262-jit results are stored in the same file
  .github/workflows/libjs-test262.yml
Labels: 👀 pr-needs-review

#21811 Meta: Let test_pdf.py print number of files without problems
  Meta/test_pdf.py
Labels: 👀 pr-needs-review

#21630 AK: Avoid unnecessary String allocations for URL username and password
  AK/URLParser.cpp
  Tests/AK/TestURL.cpp
Labels: ✅ pr-community-approved

#21809 LibPDF: Fix typos in DeviceN colorspace scaffolding
  Userland/Libraries/LibPDF/ColorSpace.cpp
Labels: 👀 pr-needs-review

#21808 Kernel/Syscalls: Allow root to ptrace any process
  Kernel/Syscalls/ptrace.cpp
Labels: 👀 pr-needs-review

#21816 LibTest: Bump up MAX_GEN_ATTEMPTS_PER_VALUE to 30
  Userland/Libraries/LibTest/TestCase.h
Labels: 👀 pr-needs-review

#21817 LibJS/JIT: Resolve various pointers at JIT time
  Userland/Libraries/LibJS/Bytecode/CommonImplementations.cpp
  Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
  Userland/Libraries/LibJS/Bytecode/Executable.h
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
  Userland/Libraries/LibJS/JIT/Compiler.cpp
Labels: 👀 pr-needs-review

#21730 LibLocale: Update to CLDR version 44.0.1
  Meta/CMake/locale_data.cmake
  Userland/Libraries/LibJS/Tests/builtins/Intl/DisplayNames/DisplayNames.prototype.of.js
  Userland/Libraries/LibJS/Tests/builtins/Intl/Locale/Locale.prototype.maximize.js
  Userland/Libraries/LibJS/Tests/builtins/Intl/Locale/Locale.prototype.minimize.js
  Userland/Libraries/LibJS/Tests/builtins/Intl/NumberFormat/NumberFormat.prototype.format.js
  Userland/Libraries/LibJS/Tests/builtins/Intl/NumberFormat/NumberFormat.prototype.formatToParts.js
Labels: 👀 pr-needs-review

#21820 Shell: Add path shortening in prompt formatting option
  Base/usr/share/man/man7/Shell-vars.md
  Userland/Shell/Shell.cpp
Labels: 👀 pr-needs-review

#21827 LibJS+LibJIT: Add fast paths for shifting with Int32s
  Userland/Libraries/LibJIT/X86_64/Assembler.h
  Userland/Libraries/LibJS/JIT/Compiler.cpp
  Userland/Libraries/LibJS/JIT/Compiler.h
Labels: 👀 pr-needs-review

#21835 LibJS/JIT: Bail in UnsignedRightShift fast path if result is negative
  Userland/Libraries/LibJS/JIT/Compiler.cpp
Labels: 👀 pr-needs-review

#21839 LibEDID: Replace the HTML-based PNP ID parser with a CSV-based parser
  Meta/CMake/pnp_ids.cmake
  Meta/Lagom/Tools/CodeGenerators/LibEDID/GeneratePnpIDs.cpp
Labels: 👀 pr-needs-review

#21821 LibVideo/VP9: Ensure range decoder size is within expected range
  Userland/Libraries/LibVideo/VP9/Context.h
Labels: 👀 pr-needs-review

#21771 Kernel/Net: Implement TCP_NODELAY
  Kernel/API/POSIX/netinet/tcp.h
  Kernel/Net/TCPSocket.cpp
  Kernel/Net/TCPSocket.h
  Kernel/UnixTypes.h
  Userland/Libraries/LibC/netinet/tcp.h
Labels: 👀 pr-needs-review

#21834 LibIMAP: Make parsing of atom data fallible
  Userland/Libraries/LibIMAP/Parser.cpp
  Userland/Libraries/LibIMAP/Parser.h
Labels: 👀 pr-needs-review

#21432 LibGfx/ICC: Avoid buffer overrun when creating `TextDescriptionTagData`
  Tests/LibGfx/TestICCProfile.cpp
  Tests/LibGfx/test-inputs/icc/oss-fuzz-testcase-57426.icc
  Userland/Libraries/LibGfx/ICC/TagTypes.cpp
Labels: 👀 pr-needs-review

#21180 Assistant: Prioritize results which exactly match a query
  Userland/Applications/Assistant/Providers.cpp
Labels: stale, 👀 pr-needs-review

#21838 Shell: Avoid infinite loop when parsing heredoc entry in POSIX mode
  Userland/Shell/PosixLexer.cpp
Labels: 👀 pr-needs-review

#21836 LibJS/JIT: Add fast path for number comparisons
  Userland/Libraries/LibJS/JIT/Compiler.cpp
  Userland/Libraries/LibJS/JIT/Compiler.h
Labels: 👀 pr-needs-review

#21841 LibJS/JIT: Fast path for decrement & better opcodes
  Userland/Libraries/LibJIT/X86_64/Assembler.h
  Userland/Libraries/LibJS/JIT/Compiler.cpp
Labels: 👀 pr-needs-review

#21851 LibJS: Remove redundant Store op
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
  Userland/Libraries/LibJS/Bytecode/Generator.cpp
  Userland/Libraries/LibJS/Bytecode/Generator.h
Labels: 👀 pr-needs-review

#21845 LibWeb: Ignore document's box during overflow clip rect calculation
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Labels: 👀 pr-needs-review

#21857 LibAccelGfx: Add 1px padding between glyphs in prepare_glyph_texture()
  Userland/Libraries/LibAccelGfx/Painter.cpp
Labels: 👀 pr-needs-review

#21842 LibAccelGfx+LibWeb: Add basic line painting support
  Userland/Libraries/LibAccelGfx/Painter.cpp
  Userland/Libraries/LibAccelGfx/Painter.h
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Labels: 👀 pr-needs-review

#21352 LibGfx/JPEGWriter: Fix crash on macOS when csize coefficient is 0
  Tests/LibWeb/Text/expected/canvas/export.txt
  Tests/LibWeb/Text/input/canvas/export.html
  Userland/Libraries/LibGfx/ImageFormats/JPEGWriter.cpp
Labels: ✅ pr-community-approved

#21408 LibWeb: Add ol start and li value attributes support
  Base/res/html/misc/lists.html
  Tests/LibWeb/Layout/expected/ordered-list.txt
  Tests/LibWeb/Layout/input/ordered-list.html
  Userland/Libraries/LibWeb/HTML/AttributeNames.h
  Userland/Libraries/LibWeb/HTML/HTMLLIElement.h
  Userland/Libraries/LibWeb/HTML/HTMLLIElement.idl
  Userland/Libraries/LibWeb/HTML/HTMLOListElement.h
  Userland/Libraries/LibWeb/HTML/HTMLOListElement.idl
  Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
  Userland/Libraries/LibWeb/Layout/TreeBuilder.h
Labels: 👀 pr-needs-review

#21819 LibPDF: Implement DeviceNColorSpace
  Userland/Libraries/LibPDF/ColorSpace.cpp
  Userland/Libraries/LibPDF/ColorSpace.h
Labels: 👀 pr-needs-review

#21863 CMake: Don't recursively include Ladybird/Lagom in buggy CMake versions
  Meta/Lagom/CMakeLists.txt
Labels: 👀 pr-needs-review

#21864 LibTLS: Do not defer flushing alert packets
  Userland/Libraries/LibTLS/Record.cpp
  Userland/Libraries/LibTLS/TLSv12.h
Labels: 👀 pr-needs-review

#21865 CMake: Bump CMake minimum up to 3.21 to work around CLion bug
  Meta/Lagom/CMakeLists.txt
Labels: 👀 pr-needs-review

#21868 LibPDF: Tweak implementation of postscript `roll` op
  Userland/Libraries/LibPDF/Function.cpp
Labels: 👀 pr-needs-review

#21870 LibCrypto: Some clean-up of the SECP256r1 curve implementation
  Userland/Libraries/LibCrypto/Curves/SECP256r1.cpp
Labels: 👀 pr-needs-review

#21876 LibAccelGfx: Use wrapping functions with error check for OpenGL calls
  Userland/Libraries/LibAccelGfx/CMakeLists.txt
  Userland/Libraries/LibAccelGfx/Canvas.cpp
  Userland/Libraries/LibAccelGfx/GL.cpp
  Userland/Libraries/LibAccelGfx/GL.h
  Userland/Libraries/LibAccelGfx/Painter.cpp
  Userland/Libraries/LibAccelGfx/Painter.h
  Userland/Libraries/LibAccelGfx/Program.cpp
  Userland/Libraries/LibAccelGfx/Program.h
Labels: 👀 pr-needs-review

#21881 LibGfx/OpenType: Add validation for OpenType head table values
  Userland/Libraries/LibGfx/Font/OpenType/Tables.cpp
Labels: 👀 pr-needs-review

#21883 LibIDL: Disallow invalid nullable types; require 'attribute' keyword
  Userland/Libraries/LibIDL/IDLParser.cpp
Labels: 👀 pr-needs-review

#21874 LibJS: Skip an always-false branch in the JIT to_boolean slow case
  Userland/Libraries/LibJS/JIT/Compiler.cpp
  Userland/Libraries/LibJS/Runtime/Value.h
Labels: 👀 pr-needs-review

#21877 LibPDF: Add test for SampledFunction and fix bugs found by it
  Tests/LibPDF/TestPDF.cpp
  Userland/Libraries/LibPDF/Function.cpp
Labels: 👀 pr-needs-review

#21861 LibJS/Bytecode: Check if eval function is a function
  Userland/Libraries/LibJS/Bytecode/CommonImplementations.cpp
  Userland/Libraries/LibJS/Tests/eval-aliasing.js
Labels: 👀 pr-needs-review

#21885 Shell: Allow to parse command interactively when hitting Enter key
  Userland/Shell/Shell.cpp
Labels: 👀 pr-needs-review

#21895 LibWeb: Support [de]serialization for {Error, Map, Set, Object, Array} objects
  Tests/LibWeb/Text/expected/HTML/StructuredClone-object-primitives.txt
  Tests/LibWeb/Text/expected/HTML/Window-postMessage.txt
  Tests/LibWeb/Text/input/HTML/StructuredClone-object-primitives.html
  Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
  Userland/Libraries/LibWeb/HTML/StructuredSerialize.h
  Userland/Libraries/LibWeb/HTML/Window.cpp
  Userland/Libraries/LibWeb/HighResolutionTime/Performance.cpp
  Userland/Libraries/LibWeb/UserTiming/PerformanceMark.cpp
Labels: 👀 pr-needs-review

#21891 LibAccelGfx: Use OpenGL 3.3 and VBO to pass vertex data
  Userland/Libraries/LibAccelGfx/CMakeLists.txt
  Userland/Libraries/LibAccelGfx/Canvas.cpp
  Userland/Libraries/LibAccelGfx/Canvas.h
  Userland/Libraries/LibAccelGfx/Context.cpp
  Userland/Libraries/LibAccelGfx/Context.h
  Userland/Libraries/LibAccelGfx/Forward.h
  Userland/Libraries/LibAccelGfx/GL.cpp
  Userland/Libraries/LibAccelGfx/GL.h
  Userland/Libraries/LibAccelGfx/Painter.cpp
  Userland/Libraries/LibAccelGfx/Painter.h
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.h
  Userland/Services/WebContent/PageHost.cpp
Labels: 👀 pr-needs-review

#21894 LibGfx/OpenType: Ensure Cmap subtable offset is within expected range
  Tests/LibTTF/TestCmap.cpp
  Userland/Libraries/LibGfx/Font/OpenType/Cmap.cpp
Labels: 👀 pr-needs-review

#21886 LibPDF: Make SampledFunction::evaluate() work for n-dimensional input
  Tests/LibPDF/TestPDF.cpp
  Userland/Libraries/LibPDF/Function.cpp
Labels: 👀 pr-needs-review

#21887 LibGfx/ICC: Avoid overflow when creating MultiLocalizedUnicodeTagData
  Userland/Libraries/LibGfx/ICC/TagTypes.cpp
Labels: 👀 pr-needs-review

#21888 LibLine: Capture the current origin immediately after ^C
  Userland/Libraries/LibLine/Editor.cpp
Labels: 👀 pr-needs-review

#21906 LibWeb: Support `mask-type` style attribute for SVGs
  Tests/LibWeb/Ref/svg-alpha-mask-attribute.html
  Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
Labels: 👀 pr-needs-review

#21914 LibWeb: Remove redundant flush() call in PaintingCommandExecutorGPU
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Labels: 👀 pr-needs-review

#21909 LibPDF: Tolerate an indirect object as dict for CIE-based color spaces
  Userland/Libraries/LibPDF/ColorSpace.cpp
Labels: 👀 pr-needs-review

#21916 LibPDF: Add support for the LZW Filter
  Userland/Libraries/LibPDF/CommonNames.h
  Userland/Libraries/LibPDF/Filter.cpp
  Userland/Libraries/LibPDF/Filter.h
Labels: ✅ pr-community-approved

#21920 LibJS/JIT: Remove incorrect check for empty tag
  Userland/Libraries/LibJS/JIT/Compiler.cpp
Labels: 👀 pr-needs-review

#21921 LibPDF: In ColorSpace creation code, use resolve_to() more
  Userland/Libraries/LibPDF/ColorSpace.cpp
Labels: 👀 pr-needs-review

#21902 LibPDF: Detect DCT images correctly
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: ✅ pr-community-approved

#21926 LibAccelGfx+LibWeb: Implement SetClipRect and ClearClipRect commands
  Userland/Libraries/LibAccelGfx/GL.cpp
  Userland/Libraries/LibAccelGfx/GL.h
  Userland/Libraries/LibAccelGfx/Painter.cpp
  Userland/Libraries/LibAccelGfx/Painter.h
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Labels: 👀 pr-needs-review

#21917 LibJS: Don't hang when parsing invalid destructuring assignment target
  Userland/Libraries/LibJS/Parser.cpp
  Userland/Libraries/LibJS/Tests/parser-invalid-destructuring-assignment-target.js
Labels: 👀 pr-needs-review

#21925 LibJS/JIT: Use the x86_64 setcc instruction to remove a branch
  Userland/Libraries/LibJIT/X86_64/Assembler.h
  Userland/Libraries/LibJS/JIT/Compiler.cpp
  Userland/Libraries/LibJS/Runtime/Value.h
Labels: 👀 pr-needs-review

#21933 AK: Ban JsonValue from the kernel and remove ifdef guards
  AK/JsonValue.h
  Kernel/FileSystem/ProcFS/ProcessExposed.cpp
Labels: 👀 pr-needs-review

#21930 LibPDF: Change how CFF optional width prefix is stored
  Userland/Libraries/LibPDF/Fonts/Type1FontProgram.cpp
  Userland/Libraries/LibPDF/Fonts/Type1FontProgram.h
Labels: 👀 pr-needs-review

#21934 LibWeb: Validate `MimeType(String, String)` arguments correctly
  Userland/Libraries/LibWeb/MimeSniff/MimeType.cpp
Labels: 👀 pr-needs-review

#21939 Meta: Move .DS_Store rule to the bottom of the .gitignore file
  .gitignore
Labels: 👀 pr-needs-review

#21940 Browser: Move `BookmarksBarWidget::PerformEditOn` to anon namespace
  Userland/Applications/Browser/BookmarksBarWidget.cpp
  Userland/Applications/Browser/BookmarksBarWidget.h
Labels: 👀 pr-needs-review

#21936 LibWeb: Use inner available space to calculate auto height of abspos
  Tests/LibWeb/Layout/expected/block-and-inline/abspos-grid-with-definite-width.txt
  Tests/LibWeb/Layout/input/block-and-inline/abspos-grid-with-definite-width.html
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Labels: 👀 pr-needs-review

#21943 Documentation: Update Helix editor documentation
  Documentation/HelixConfiguration.md
Labels: 👀 pr-needs-review

#21944 AK+LibIDL: Put IDL dbgln statement behind a debug flag
  AK/Debug.h.in
  Meta/CMake/all_the_debug_macros.cmake
  Meta/gn/secondary/AK/BUILD.gn
  Userland/Libraries/LibIDL/Types.cpp
Labels: 👀 pr-needs-review

#21945 LibWeb: Do not compensate padding for abspos boxes with static position
  Tests/LibWeb/Layout/expected/block-and-inline/abspos-only-with-inset-left.txt
  Tests/LibWeb/Layout/expected/block-and-inline/abspos-with-bottom-right-insets-relative-to-box-with-paddings.txt
  Tests/LibWeb/Layout/expected/block-and-inline/abspos-without-insets-relative-top-box-with-padding-top.txt
  Tests/LibWeb/Layout/expected/block-and-inline/abspos-without-insets.txt
  Tests/LibWeb/Layout/input/block-and-inline/abspos-only-with-inset-left.html
  Tests/LibWeb/Layout/input/block-and-inline/abspos-with-bottom-right-insets-relative-to-box-with-paddings.html
  Tests/LibWeb/Layout/input/block-and-inline/abspos-without-insets-relative-top-box-with-padding-top.html
  Tests/LibWeb/Layout/input/block-and-inline/abspos-without-insets.html
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Labels: 👀 pr-needs-review

#21938 LibJS/JIT: Add a fast path for floating point comparisons
  Userland/Libraries/LibJIT/X86_64/Assembler.h
  Userland/Libraries/LibJS/JIT/Compiler.cpp
  Userland/Libraries/LibJS/JIT/Compiler.h
Labels: 👀 pr-needs-review

#21956 LibJS: Don't create `arguments` object due to `o.arguments` access
  Userland/Libraries/LibJS/Parser.cpp
  Userland/Libraries/LibJS/Parser.h
Labels: 👀 pr-needs-review

#21908 LibAccelGfx+WebContent: Add GPU painter support on macOS
  Meta/CMake/accelerated_graphics.cmake
  Userland/Libraries/LibAccelGfx/Context.cpp
  Userland/Libraries/LibAccelGfx/Context.h
  Userland/Libraries/LibAccelGfx/GL.h
  Userland/Libraries/LibAccelGfx/Painter.cpp
Labels: 👀 pr-needs-review

#21950 LibAccelGfx+LibWeb: Add basic support for linear gradients painting
  Userland/Libraries/LibAccelGfx/Painter.cpp
  Userland/Libraries/LibAccelGfx/Painter.h
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Labels: 👀 pr-needs-review

#21962 head(1): Fix typo in flag name
  Base/usr/share/man/man1/head.md
Labels: 👀 pr-needs-review

#21923 Base: Add completion for cd that suggests only directories
  Base/usr/share/shell/completion/builtin.sh
Labels: 👀 pr-needs-review

#21963 Meta: Globally disable floating point contraction
  Meta/CMake/common_compile_options.cmake
  Meta/gn/build/BUILD.gn
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#21964 Shell: Escape program-provided completions unless they're marked as code
  Userland/Shell/Shell.cpp
Labels: 👀 pr-needs-review

#21508 Calculator: Convert DeprecatedString to String
  Userland/Applications/Calculator/CalculatorWidget.cpp
  Userland/Applications/Calculator/CalculatorWidget.h
  Userland/Applications/Calculator/Keypad.cpp
  Userland/Applications/Calculator/Keypad.h
Labels: 👀 pr-needs-review

#21189 WindowServer: Introduce the window roll-up feature
  Userland/Services/WindowServer/Window.cpp
  Userland/Services/WindowServer/Window.h
Labels: 👀 pr-needs-review

#21971 LibTimeZone: Handle systems with varying zoneinfo file locations
  Userland/Libraries/LibTimeZone/TimeZone.cpp
Labels: 👀 pr-needs-review

#21965 LibPDF: Use font dictionary object as cache key, not resource name
  Userland/Libraries/LibPDF/Renderer.cpp
  Userland/Libraries/LibPDF/Renderer.h
Labels: 👀 pr-needs-review

#21972 LibWeb: Flesh out "scroll a target into view" spec implementation
  Tests/LibWeb/Text/expected/get-bounding-client-rect.txt
  Tests/LibWeb/Text/input/get-bounding-client-rect.html
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: 👀 pr-needs-review

#21974 LibPDF: Consistently asciibetize CommonNames.h
  Userland/Libraries/LibPDF/CommonNames.h
Labels: 👀 pr-needs-review

#21953 LibPDF+LibGfx: Don't invert CMYK channels in JPEG data in PDFs
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.h
  Userland/Libraries/LibPDF/Filter.cpp
Labels: ✅ pr-community-approved

#21952 LibPDF: Support images with 1, 2, 4 bits per pixel
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: 👀 pr-needs-review

#21975 LibJS: Instantiate primitive array expressions using a single operation
  Userland/Libraries/LibJS/AST.h
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
  Userland/Libraries/LibJS/Bytecode/Instruction.h
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
  Userland/Libraries/LibJS/Bytecode/Op.h
  Userland/Libraries/LibJS/JIT/Compiler.cpp
  Userland/Libraries/LibJS/JIT/Compiler.h
Labels: 👀 pr-needs-review

#21790 DisplaySettings: Prevent user from making background non-image type
  Userland/Applications/DisplaySettings/BackgroundSettingsWidget.cpp
Labels: 👀 pr-needs-review

#21979 LibLine: Reset state after invalid character in DSR response
  Userland/Libraries/LibLine/Editor.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#21984 LibWeb/LibJS: Avoid GC visit of raw pointers where possible
  Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
  Userland/Libraries/LibWeb/CSS/CSSRule.cpp
  Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp
  Userland/Libraries/LibWeb/CSS/CSSStyleSheet.cpp
  Userland/Libraries/LibWeb/CSS/MediaQueryList.cpp
  Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
  Userland/Libraries/LibWeb/CSS/Screen.cpp
  Userland/Libraries/LibWeb/CSS/StyleSheetList.cpp
  Userland/Libraries/LibWeb/Crypto/Crypto.cpp
  Userland/Libraries/LibWeb/DOM/AbortController.cpp
  Userland/Libraries/LibWeb/DOM/AbstractRange.cpp
  Userland/Libraries/LibWeb/DOM/Attr.cpp
  Userland/Libraries/LibWeb/DOM/DOMEventListener.cpp
  Userland/Libraries/LibWeb/DOM/DocumentFragment.cpp
  Userland/Libraries/LibWeb/DOM/Element.cpp
  Userland/Libraries/LibWeb/DOM/Event.cpp
  Userland/Libraries/LibWeb/DOM/EventTarget.cpp
  Userland/Libraries/LibWeb/DOM/HTMLCollection.cpp
  Userland/Libraries/LibWeb/DOM/IDLEventListener.cpp
  Userland/Libraries/LibWeb/DOM/LiveNodeList.cpp
  Userland/Libraries/LibWeb/DOM/MutationObserver.cpp
  Userland/Libraries/LibWeb/DOM/MutationRecord.cpp
  Userland/Libraries/LibWeb/DOM/NamedNodeMap.cpp
  Userland/Libraries/LibWeb/DOM/Node.cpp
  Userland/Libraries/LibWeb/DOM/NodeIterator.cpp
  Userland/Libraries/LibWeb/DOM/TreeWalker.cpp
  Userland/Libraries/LibWeb/Geometry/DOMQuad.cpp
  Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
  Userland/Libraries/LibWeb/HTML/DOMStringMap.cpp
  Userland/Libraries/LibWeb/HTML/HTMLCanvasElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLScriptElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLTemplateElement.cpp
  Userland/Libraries/LibWeb/HTML/History.cpp
  Userland/Libraries/LibWeb/HTML/ImageData.cpp
  Userland/Libraries/LibWeb/HTML/MessageChannel.cpp
  Userland/Libraries/LibWeb/HTML/MessagePort.cpp
  Userland/Libraries/LibWeb/HTML/Scripting/Script.cpp
  Userland/Libraries/LibWeb/HTML/Scripting/WindowEnvironmentSettingsObject.cpp
  Userland/Libraries/LibWeb/HTML/SubmitEvent.cpp
  Userland/Libraries/LibWeb/HTML/Timer.cpp
  Userland/Libraries/LibWeb/HTML/Window.cpp
  Userland/Libraries/LibWeb/HTML/WindowProxy.cpp
  Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.cpp
  Userland/Libraries/LibWeb/HighResolutionTime/Performance.cpp
  Userland/Libraries/LibWeb/NavigationTiming/PerformanceTiming.cpp
  Userland/Libraries/LibWeb/PerformanceTimeline/PerformanceObserver.cpp
  Userland/Libraries/LibWeb/SVG/SVGAnimatedLength.cpp
  Userland/Libraries/LibWeb/UIEvents/UIEvent.cpp
  Userland/Libraries/LibWeb/URL/URL.cpp
  Userland/Libraries/LibWeb/WebGL/WebGLRenderingContextBase.cpp
Labels: 👀 pr-needs-review

#21982 Tests: Add a type3 test pdf
  Tests/LibPDF/type3.pdf
Labels: 👀 pr-needs-review

#21942 LibGfx/Path: Round numerator in elliptical_arc_to
  Userland/Libraries/LibGfx/Path.cpp
Labels: 👀 pr-needs-review

#21955 LibJS/JIT: Add fastpath for set variable
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
  Userland/Libraries/LibJS/Bytecode/CommonImplementations.cpp
  Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
  Userland/Libraries/LibJS/Bytecode/Generator.cpp
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
  Userland/Libraries/LibJS/Bytecode/Op.h
  Userland/Libraries/LibJS/JIT/Compiler.cpp
  Userland/Libraries/LibJS/Runtime/ExecutionContext.h
Labels: 👀 pr-needs-review

#21993 LibJS/JIT: Continue to outer `finally` before returning
  Userland/Libraries/LibJS/JIT/Compiler.cpp
  Userland/Libraries/LibJS/Tests/try-return-finally.js
Labels: 👀 pr-needs-review

#21996 Kernel/FS: Fix check-then-act concurrency bug in FileSystem/Inode
  Kernel/FileSystem/Ext2FS/Inode.cpp
  Kernel/FileSystem/Inode.cpp
Labels: 👀 pr-needs-review

#21999 LibJS: Cache bytecode executables on the corresponding AST nodes
  Userland/Libraries/LibJS/AST.h
  Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Labels: 👀 pr-needs-review

#21988 Shell/PosixParser: Correctly parse the OR_IF token
  Userland/Shell/PosixParser.cpp
Labels: 👀 pr-needs-review

#22003 LibAccelGfx+LibWeb: Implement rounded corners rectangle painting
  Userland/Libraries/LibAccelGfx/GL.cpp
  Userland/Libraries/LibAccelGfx/GL.h
  Userland/Libraries/LibAccelGfx/Painter.cpp
  Userland/Libraries/LibAccelGfx/Painter.h
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Labels: 👀 pr-needs-review

#22006 LibWeb: Implement FillEllipse command for GPU executor
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Labels: 👀 pr-needs-review

#22007 LibWeb: Fix null pointer dereference in DOM::Node::remove()
  Tests/LibWeb/Text/expected/MutationObserver/removing-a-node.txt
  Tests/LibWeb/Text/input/MutationObserver/removing-a-node.html
  Userland/Libraries/LibWeb/DOM/Node.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#22015 Base: Adjust emoji
  Base/res/emoji/U+1F34A.png
  Base/res/emoji/U+1F34B.png
  Base/res/emoji/U+1F34E.png
  Base/res/emoji/U+1F34F.png
  Base/res/emoji/U+1F350.png
  Base/res/emoji/U+1F368.png
  Base/res/emoji/U+1F376.png
  Base/res/emoji/U+1F3A8.png
  Base/res/emoji/U+1F3C2.png
  Base/res/emoji/U+1F423.png
  Base/res/emoji/U+1F433.png
  Base/res/emoji/U+1F478.png
  Base/res/emoji/U+1F482.png
  Base/res/emoji/U+1F482_U+200D_U+2640.png
  Base/res/emoji/U+1F482_U+200D_U+2642.png
  Base/res/emoji/U+1F4BA.png
  Base/res/emoji/U+1F56F.png
  Base/res/emoji/U+1F58D.png
  Base/res/emoji/U+1F5D1.png
  Base/res/emoji/U+1F916.png
  Base/res/emoji/U+1F9E8.png
  Base/res/emoji/U+1FABF.png
Labels: 👀 pr-needs-review

#22016 Base: Add some long delayed emoji
  Base/res/emoji/U+1F390.png
  Base/res/emoji/U+1F3E6.png
  Base/res/emoji/U+1F54B.png
  Base/res/emoji/U+1F54D.png
  Base/res/emoji/U+1F690.png
  Base/res/emoji/U+1F95C.png
Labels: 👀 pr-needs-review

#22018 LibPDF: Tolerate comment after last dict item and before drawing operators
  Userland/Libraries/LibPDF/Parser.cpp
Labels: 👀 pr-needs-review

#22026 LibPDF+LibGfx: Make SMasks on jpeg images work
  Userland/Libraries/LibGfx/Bitmap.h
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: 👀 pr-needs-review

#22036 LibWeb: Skip flakey ref test for now
  Tests/LibWeb/Ref/skipped/css-background-repeat.html
Labels: 👀 pr-needs-review

#22037 LibAudio: Speed up WavWriter by buffering output data
  Userland/Libraries/LibAudio/WavWriter.cpp
  Userland/Libraries/LibAudio/WavWriter.h
Labels: ✅ pr-community-approved

#22025 AK: Fix bugs in Complex += -= + - * / operators
  AK/Complex.h
  Tests/AK/TestComplex.cpp
Labels: 👀 pr-needs-review

#22040 LibWeb: Fix UAF in CSSStyleSheet
  Userland/Libraries/LibWeb/CSS/CSSStyleSheet.cpp
  Userland/Libraries/LibWeb/CSS/CSSStyleSheet.h
Labels: 👀 pr-needs-review

#22023 Kernel/riscv64: Add missing input sections to linker script
  Kernel/Arch/riscv64/linker.ld
Labels: 👀 pr-needs-review

#22030 Kernel/riscv64: Generate Kernel.bin from kernel ELF
  Kernel/CMakeLists.txt
Labels: 👀 pr-needs-review

#21941 AK+Applications: Return value from JsonObject::get_double more often (and fix Inspector on Serenity)
  AK/JsonObject.cpp
  AK/JsonObject.h
  Userland/Applications/Browser/InspectorWidget.cpp
  Userland/Applications/Maps/FavoritesPanel.cpp
Labels: 👀 pr-needs-review

#22054 LibWeb: Remove exit for javascript urls in anchor activation_behavior()
  Tests/LibWeb/Text/expected/anchor-element-with-javascript-url-href.txt
  Tests/LibWeb/Text/input/anchor-element-with-javascript-url-href.html
  Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.cpp
Labels: 👀 pr-needs-review

#22059 LibWeb: Remove now-unneeded TypedArray OOM propagation
  Userland/Libraries/LibWeb/WebIDL/AbstractOperations.cpp
Labels: 👀 pr-needs-review

#22062 LibWeb: Add missing nullptr check in `HTMLImageElement::bitmap()`
  Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLImageElement.h
Labels: 👀 pr-needs-review

#22064 LibPDF: Update font size after getting font from cache
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: 👀 pr-needs-review

#22011 Meta: Add a minimal SDL2 based videoplayer for Lagom
  Meta/Lagom/CMakeLists.txt
  Meta/Lagom/Contrib/VideoPlayerSDL/CMakeLists.txt
  Meta/Lagom/Contrib/VideoPlayerSDL/main.cpp
Labels: 👀 pr-needs-review

#22039 LibGfx/TIFF: Introduce a code generator
  Userland/Libraries/LibGfx/CMakeLists.txt
  Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
  Userland/Libraries/LibGfx/ImageFormats/TIFFMetadata.h
  Userland/Libraries/LibGfx/ImageFormats/TIFFTagHandler.cpp
  Userland/Libraries/LibGfx/TIFFGenerator.py
Labels: 👀 pr-needs-review

#22067 LibWeb: Add fixed position stacking context support in GPU painter
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Labels: 👀 pr-needs-review

#22069 LibWeb: Rename painter() to recording_painter() in PaintContext
  Userland/Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.cpp
  Userland/Libraries/LibWeb/Painting/AudioPaintable.cpp
  Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
  Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.cpp
  Userland/Libraries/LibWeb/Painting/ButtonPaintable.cpp
  Userland/Libraries/LibWeb/Painting/CanvasPaintable.cpp
  Userland/Libraries/LibWeb/Painting/CheckBoxPaintable.cpp
  Userland/Libraries/LibWeb/Painting/FilterPainting.cpp
  Userland/Libraries/LibWeb/Painting/GradientPainting.cpp
  Userland/Libraries/LibWeb/Painting/ImagePaintable.cpp
  Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
  Userland/Libraries/LibWeb/Painting/MarkerPaintable.cpp
  Userland/Libraries/LibWeb/Painting/MediaPaintable.cpp
  Userland/Libraries/LibWeb/Painting/NestedBrowsingContextPaintable.cpp
  Userland/Libraries/LibWeb/Painting/PaintContext.cpp
  Userland/Libraries/LibWeb/Painting/PaintContext.h
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
  Userland/Libraries/LibWeb/Painting/ProgressPaintable.cpp
  Userland/Libraries/LibWeb/Painting/RadioButtonPaintable.cpp
  Userland/Libraries/LibWeb/Painting/SVGPathPaintable.cpp
  Userland/Libraries/LibWeb/Painting/SVGSVGPaintable.cpp
  Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
  Userland/Libraries/LibWeb/Painting/TableBordersPainting.cpp
  Userland/Libraries/LibWeb/Painting/VideoPaintable.cpp
  Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp
Labels: 👀 pr-needs-review

#22074 LibGfx: Unbreak building with Python 3.9
  Userland/Libraries/LibGfx/TIFFGenerator.py
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#22077 LibGfx/TIFF: Rename `BitPerSample` => `BitsPerSample`
  Userland/Libraries/LibGfx/TIFFGenerator.py
Labels: 👀 pr-needs-review

#22075 Meta: Silence warnings from optional CMake packages
  Meta/CMake/accelerated_graphics.cmake
  Meta/Lagom/CMakeLists.txt
Labels: ✅ pr-community-approved

#22079 AK: Ensure assigned-to Strings are dereferenced if needed
  AK/String.cpp
  Tests/AK/TestString.cpp
Labels: 👀 pr-needs-review

#22078 AK: Allow `Optional<T&>` to be constructed by `OptionalNone()`
  AK/Optional.h
Labels: 👀 pr-needs-review

#22082 LibWeb: Apply stacking context transform in GPU painter
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Labels: 👀 pr-needs-review

#22085 LibAccelGfx: Premultiply linear gradient colors by alpha
  Userland/Libraries/LibAccelGfx/GL.cpp
  Userland/Libraries/LibAccelGfx/GL.h
  Userland/Libraries/LibAccelGfx/Painter.cpp
Labels: 👀 pr-needs-review

#22089 LibAccelGfx: Deallocate VAO and VBOs in fill_rect_with_linear_gradient
  Userland/Libraries/LibAccelGfx/Painter.cpp
Labels: 👀 pr-needs-review

#22087 LibAccelGfx+LibWeb: Store state of all stacking contexts in GPU painter
  Userland/Libraries/LibAccelGfx/Painter.cpp
  Userland/Libraries/LibAccelGfx/Painter.h
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.h
Labels: 👀 pr-needs-review

#22090 LibWeb: Clear texture allocated for stacking context painting
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Labels: 👀 pr-needs-review

#22081 LibWeb: Handle window.open() when passed a navigable name
  Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
  Userland/Libraries/LibWeb/HTML/BrowsingContext.h
  Userland/Libraries/LibWeb/HTML/Navigable.cpp
Labels: 👀 pr-needs-review

#22093 LibWeb: Restore painter state if push_stacking_context() has failed
  Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.cpp
Labels: 👀 pr-needs-review
