Repository SerenityOS/serenity, pull requests merged in 2023-01, with the labels that each got.

#16594 Kernel+Tests: Handful of fixes and tests for the rmdir() syscall
  Kernel/FileSystem/VirtualFileSystem.cpp
  Tests/LibC/TestIo.cpp
Labels: 👀 pr-needs-review

#16741 LibSQL: Add parsing and evaluation of BOOLEAN type literals
  Tests/LibSQL/TestSqlExpressionParser.cpp
  Userland/Libraries/LibSQL/AST/AST.h
  Userland/Libraries/LibSQL/AST/Expression.cpp
  Userland/Libraries/LibSQL/AST/Parser.cpp
  Userland/Libraries/LibSQL/AST/Token.h
Labels: 👀 pr-needs-review

#16679 Utilities: Print arbitrary bytes in `ls` by fixing for loop in `print_escaped`
  Userland/Utilities/ls.cpp
Labels: ✅ pr-community-approved

#16761 LibGUI: Fix wrong copyright header email for recent OpacitySlider change
  Userland/Libraries/LibGUI/OpacitySlider.cpp
Labels: 👀 pr-needs-review

#16766 LibGL: Implement `GL_TEXTURE_ENV_COLOR`
  Tests/LibGL/TestRender.cpp
  Tests/LibGL/reference-images/0011_tex_env_combine_with_constant_color.qoi
  Userland/Libraries/LibGL/GL/gl.h
  Userland/Libraries/LibGL/GLAPI.json
  Userland/Libraries/LibGL/GLContext.h
  Userland/Libraries/LibGL/Tex/TextureUnit.h
  Userland/Libraries/LibGL/Texture.cpp
  Userland/Libraries/LibGPU/SamplerConfig.h
Labels: 👀 pr-needs-review

#16762 LibGL: Stop unnecessarily casting to `float`
  Userland/Libraries/LibGL/GLAPI.json
  Userland/Libraries/LibGL/GLContext.cpp
  Userland/Libraries/LibGL/GLContext.h
  Userland/Libraries/LibGL/Matrix.cpp
  Userland/Libraries/LibGL/Vertex.cpp
Labels: 👀 pr-needs-review

#16767 Base: Add 7 new emoji and improve consistency on one more
  Base/res/emoji/U+1F450.png
  Base/res/emoji/U+1F64C.png
  Base/res/emoji/U+270A.png
  Base/res/emoji/U+2734.png
  Base/res/emoji/U+2747.png
  Base/res/emoji/U+274E.png
  Base/res/emoji/U+2764_U+200D_U+1F525.png
  Base/res/emoji/U+3030.png
Labels: ✅ pr-community-approved

#16530 Kernel: Propagate properly errors from PCI IDE Controller initialization
  Kernel/Arch/x86_64/PCI/IDELegacyModeController.cpp
  Kernel/Arch/x86_64/PCI/IDELegacyModeController.h
  Kernel/Storage/StorageManagement.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16756 LibGfx+icc: Print pcs illuminant
  Userland/Libraries/LibGfx/ICCProfile.cpp
  Userland/Libraries/LibGfx/ICCProfile.h
  Userland/Utilities/icc.cpp
Labels: 👀 pr-needs-review

#16768 Base+Userland: Add menu item icons
  Base/res/icons/16x16/fit-image-to-view.png
  Base/res/icons/16x16/fullscreen.png
  Base/res/icons/16x16/play.png
  Base/res/icons/16x16/scale.png
  Userland/Applications/FontEditor/MainWidget.cpp
  Userland/Applications/ImageViewer/main.cpp
  Userland/Applications/PixelPaint/IconBag.cpp
  Userland/Applications/Presenter/PresenterWidget.cpp
Labels: ✅ pr-community-approved

#16575 AK: Combine SinglyLinkedList and SinglyLinkedListWithCount
  AK/Forward.h
  AK/SinglyLinkedList.h
  AK/SinglyLinkedListSizePolicy.h
  AK/SinglyLinkedListWithCount.h
  Kernel/Net/IPv4Socket.h
  Tests/AK/TestSinglyLinkedList.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16786 LibGUI: Fix highlighting of elements in TreeView
  Userland/Libraries/LibGUI/TreeView.cpp
Labels: 👀 pr-needs-review

#16784 Ladybird: install SQLServer binary
  Ladybird/cmake/InstallRules.cmake
Labels: 👀 pr-needs-review

#16789 LibGUI: Don't highlight extension text when saving files with FilePicker
  Userland/Libraries/LibGUI/FilePicker.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16738 LibJS: More Temporal refactoring
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
  Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
Labels: 👀 pr-needs-review

#16780 LibGfx: Improve non-antialiased and filled ellipse rendering
  Userland/Libraries/LibGfx/Painter.cpp
Labels: 👀 pr-needs-review

#16670 Documentation: Add Neovim configuration documentation
  Documentation/NvimConfiguration.md
Labels: ✅ pr-community-approved

#16695 Documentation: Document fix for missing /etc/mtab
  Documentation/BuildInstructions.md
Labels: ✅ pr-community-approved

#16730 LibWeb: CSS don't set resolve-failures (var/attr)
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Labels: ⏳ pr-waiting-for-author

#16792 Meta: Add CODEOWNERS file
  .github/CODEOWNERS
Labels: 👀 pr-needs-review

#16797 LibGfx: Fix typos in ICC spec comments
  Userland/Libraries/LibGfx/ICCProfile.cpp
Labels: 👀 pr-needs-review

#16796 Meta: Mark myself a CODEOWNER of some paths to be alerted of related PRs
  .github/CODEOWNERS
Labels: 👀 pr-needs-review

#16803 Lagom: Fix up a missed usage of `Compress::Zlib` in the fuzzers
  Meta/Lagom/Fuzzers/FuzzZlibDecompression.cpp
Labels: 👀 pr-needs-review

#16815 Ports: Fix the libmpg123 patch
  Ports/libmpg123/patches/0001-Teach-the-multiple-configure-files-that-serenity-is-.patch
Labels: 👀 pr-needs-review

#16822 SoundPlayer: Parse Main::Arguments with Core::ArgsParser
  Userland/Applications/SoundPlayer/main.cpp
Labels: 👀 pr-needs-review

#16813 LibWeb: Implement missing parent table fixup
  Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Labels: 👀 pr-needs-review

#16811 SystemMonitor: Update stats/graph immediately on launch
  Userland/Applications/SystemMonitor/main.cpp
Labels: 👀 pr-needs-review

#16071 Kernel: Add dmesgln_pci logging for Kernel::PCI
  Kernel/Arch/x86_64/PCI/IDELegacyModeController.h
  Kernel/Bus/PCI/Device.h
  Kernel/Bus/USB/UHCI/UHCIController.cpp
  Kernel/Bus/USB/UHCI/UHCIController.h
  Kernel/Bus/VirtIO/Console.h
  Kernel/Bus/VirtIO/RNG.h
  Kernel/Devices/Audio/AC97.h
  Kernel/Graphics/Bochs/GraphicsAdapter.h
  Kernel/Graphics/Intel/NativeGraphicsAdapter.cpp
  Kernel/Graphics/Intel/NativeGraphicsAdapter.h
  Kernel/Graphics/VMWare/GraphicsAdapter.h
  Kernel/Graphics/VirtIOGPU/GraphicsAdapter.h
  Kernel/Net/Intel/E1000NetworkAdapter.cpp
  Kernel/Net/Intel/E1000NetworkAdapter.h
  Kernel/Net/NE2000/NetworkAdapter.cpp
  Kernel/Net/NE2000/NetworkAdapter.h
  Kernel/Net/Realtek/RTL8139NetworkAdapter.cpp
  Kernel/Net/Realtek/RTL8139NetworkAdapter.h
  Kernel/Net/Realtek/RTL8168NetworkAdapter.cpp
  Kernel/Net/Realtek/RTL8168NetworkAdapter.h
  Kernel/Storage/ATA/AHCI/Controller.cpp
  Kernel/Storage/ATA/AHCI/Controller.h
  Kernel/Storage/NVMe/NVMeController.cpp
  Kernel/Storage/NVMe/NVMeController.h
Labels: ✅ pr-community-approved

#16830 Documentation: Update QtCreator setup instructions
  Documentation/QtCreatorConfiguration.md
Labels: 👀 pr-needs-review

#16831 LibGfx+LibPDF: Apply subpixel offset in affine transformation
  Userland/Libraries/LibGfx/Font/OpenType/Glyf.cpp
  Userland/Libraries/LibGfx/Font/OpenType/Glyf.h
  Userland/Libraries/LibGfx/Font/PathRasterizer.cpp
  Userland/Libraries/LibGfx/Font/PathRasterizer.h
  Userland/Libraries/LibPDF/Fonts/PS1FontProgram.cpp
  Userland/Libraries/LibPDF/Fonts/PS1FontProgram.h
Labels: 👀 pr-needs-review

#16776 Meta: Overhaul the build-manpages-website.sh script to support nested sections
  Meta/build-manpages-website.sh
Labels: ✅ pr-community-approved

#16798 Kernel: Repair build for aarch64
  Kernel/Arch/aarch64/RPi/InterruptController.h
Labels: ✅ pr-community-approved

#16827 LibJS: Convert calendar operation results to floats
  Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/Calendar.h
  Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonthPrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
Labels: ⏳ pr-waiting-for-author

#16837 Base: Add some unlisted test pages to welcome.html
  Base/res/html/misc/welcome.html
Labels: 👀 pr-needs-review

#16839 LibWeb: Return floats from color stop resolution functions
  Userland/Libraries/LibWeb/Painting/GradientPainting.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16844 LibWeb: Pass FloatRect to Painter::draw_text in fill_text
  Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
Labels: ✅ pr-community-approved

#16842 LibJS: Add and begin using a completion-compatible string builder
  Userland/Libraries/LibJS/CMakeLists.txt
  Userland/Libraries/LibJS/Runtime/StringPrototype.cpp
  Userland/Libraries/LibJS/Runtime/ThrowableStringBuilder.cpp
  Userland/Libraries/LibJS/Runtime/ThrowableStringBuilder.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16802 Kernel/SysFS: Don't refresh/set-values inside the Jail spinlock scope
  Kernel/FileSystem/SysFS/Subsystems/Kernel/GlobalInformation.cpp
  Kernel/FileSystem/SysFS/Subsystems/Kernel/Variables/BooleanVariable.cpp
  Kernel/FileSystem/SysFS/Subsystems/Kernel/Variables/StringVariable.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16808 CI: Automatically apply pull request labels for generic PR actions
  .github/workflows/label-pull-requests.yml
  Meta/label-pull-requests.js
Labels: 👀 pr-needs-review

#16833 Meta/Lagom: Link Threads::Threads
  Meta/Lagom/CMakeLists.txt
Labels: 👀 pr-needs-review

#16564 AK: Support fixed formatting to print real numbers
  AK/Format.cpp
  AK/Format.h
Labels: 👀 pr-needs-review

#16596 PixelPaint: Move tool scaling function now works in all directions
  Userland/Applications/PixelPaint/Tools/MoveTool.cpp
  Userland/Applications/PixelPaint/Tools/MoveTool.h
Labels: 👀 pr-needs-review

#16849 Kernel: Add helper function to check if a Process is in jail
  Kernel/FileSystem/SysFS/Subsystems/Kernel/PowerStateSwitch.cpp
  Kernel/FileSystem/SysFS/Subsystems/Kernel/Variables/BooleanVariable.cpp
  Kernel/FileSystem/SysFS/Subsystems/Kernel/Variables/StringVariable.cpp
  Kernel/Process.h
Labels: 👀 pr-needs-review

#16857 LibGfx: ICO: Prefer largest image with best depth
  Userland/Libraries/LibGfx/ICOLoader.cpp
Labels: 👀 pr-needs-review

#16863 LibGfx: Verify reserved ICC header bytes are zero
  Userland/Libraries/LibGfx/ICCProfile.cpp
Labels: 👀 pr-needs-review

#16865 Documentation: Add section about curly braces to CodingStyle.md
  Documentation/CodingStyle.md
Labels: 👀 pr-needs-review

#16866 LibGfx+icc: Verify ICCProfile ID at parse time instead of in icc
  Userland/Libraries/LibGfx/ICCProfile.cpp
  Userland/Utilities/icc.cpp
Labels: 👀 pr-needs-review

#16864 LibWeb: Verify optional argument has a value before static_cast-ing it
  Userland/Libraries/LibWeb/FileAPI/File.cpp
Labels: 👀 pr-needs-review

#16867 LibGfx+icc: Print device attribute flags
  Userland/Libraries/LibGfx/ICCProfile.cpp
  Userland/Libraries/LibGfx/ICCProfile.h
  Userland/Utilities/icc.cpp
Labels: 👀 pr-needs-review

#16689 AK: Use base URL when the specified URL is empty
  AK/URLParser.cpp
  Tests/AK/TestURL.cpp
Labels: 👀 pr-needs-review

#16750 Ports: Set `$LD` for Clang, GCC and host in `.hosted_defs.sh`
  Ports/.hosted_defs.sh
  Ports/.port_include.sh
Labels: 👀 pr-needs-review

#16872 Base: Make the serenity-application HackStudio template build again
  Base/res/devel/templates/serenity-application/main.cpp
Labels: 👀 pr-needs-review

#16868 LibCrypto: Use default Crypto::Hash::Digest comparison operators
  Userland/Libraries/LibCrypto/Hash/HashFunction.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16850 Kernel: Mark Process::jail() method as const
  Kernel/Devices/Device.cpp
  Kernel/FileSystem/SysFS/Subsystems/Kernel/GlobalInformation.cpp
  Kernel/JailManagement.cpp
  Kernel/Process.cpp
  Kernel/Process.h
  Kernel/Syscalls/execve.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16871 Spreadsheet: Allow navigation keys to navigate an in focus cell
  Userland/Applications/Spreadsheet/SpreadsheetView.h
Labels: 👀 pr-needs-review

#16878 Meta: Mark myself as a CODEOWNER of a bunch of paths
  .github/CODEOWNERS
Labels: 👀 pr-needs-review

#16557 Kernel/Net: Introduce a new mechanism to initialize a PCI device
  Kernel/Net/Intel/E1000ENetworkAdapter.cpp
  Kernel/Net/Intel/E1000ENetworkAdapter.h
  Kernel/Net/Intel/E1000NetworkAdapter.cpp
  Kernel/Net/Intel/E1000NetworkAdapter.h
  Kernel/Net/LoopbackAdapter.h
  Kernel/Net/NE2000/NetworkAdapter.cpp
  Kernel/Net/NE2000/NetworkAdapter.h
  Kernel/Net/NetworkAdapter.h
  Kernel/Net/NetworkingManagement.cpp
  Kernel/Net/Realtek/RTL8139NetworkAdapter.cpp
  Kernel/Net/Realtek/RTL8139NetworkAdapter.h
  Kernel/Net/Realtek/RTL8168NetworkAdapter.cpp
  Kernel/Net/Realtek/RTL8168NetworkAdapter.h
Labels: 👀 pr-needs-review

#16870 AK: Change Statistics::median() to be mathematically correct
  AK/Statistics.h
Labels: 👀 pr-needs-review

#16860 LibWeb: Remove redundant BFC::is_block_formatting_context() method
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
Labels: 👀 pr-needs-review

#16876 LibWeb: Consider span in table column width calculation
  Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/TableFormattingContext.h
Labels: 👀 pr-needs-review

#16556 Kernel/Graphics: Introduce a new mechanism to initialize a PCI device
  Kernel/Graphics/Bochs/GraphicsAdapter.cpp
  Kernel/Graphics/Bochs/GraphicsAdapter.h
  Kernel/Graphics/GraphicsManagement.cpp
  Kernel/Graphics/GraphicsManagement.h
  Kernel/Graphics/Intel/NativeDisplayConnector.cpp
  Kernel/Graphics/Intel/NativeDisplayConnector.h
  Kernel/Graphics/Intel/NativeGraphicsAdapter.cpp
  Kernel/Graphics/Intel/NativeGraphicsAdapter.h
  Kernel/Graphics/VMWare/GraphicsAdapter.cpp
  Kernel/Graphics/VMWare/GraphicsAdapter.h
  Kernel/Graphics/VirtIOGPU/GraphicsAdapter.cpp
  Kernel/Graphics/VirtIOGPU/GraphicsAdapter.h
Labels: 👀 pr-needs-review

#16800 WindowServer: Do not add existing menu items (by ptr) to m_menus
  Userland/Services/WindowServer/Menubar.h
Labels: 👀 pr-needs-review

#16888 Chess: Port to `Core::Stream`
  Userland/Games/Chess/ChessWidget.cpp
  Userland/Games/Chess/ChessWidget.h
  Userland/Games/Chess/main.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16893 ThemeEditor: Port to `Core::Stream`
  Userland/Applications/ThemeEditor/MainWidget.cpp
  Userland/Applications/ThemeEditor/MainWidget.h
  Userland/Applications/ThemeEditor/main.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16894 LibGfx+icc: Print primary platform
  Userland/Libraries/LibGfx/ICCProfile.cpp
  Userland/Libraries/LibGfx/ICCProfile.h
  Userland/Utilities/icc.cpp
Labels: 👀 pr-needs-review

#16902 LibXML+LibWeb: Avoid implicit cast from StringView{}->DeprecatedString
  Userland/Libraries/LibWeb/XML/XMLDocumentBuilder.cpp
  Userland/Libraries/LibWeb/XML/XMLDocumentBuilder.h
  Userland/Libraries/LibXML/Parser/Parser.cpp
  Userland/Libraries/LibXML/Parser/Parser.h
Labels: 👀 pr-needs-review

#16897 LibCore: Teach MimeData about ICC file extension and contents
  Userland/Libraries/LibCore/MimeData.cpp
Labels: 👀 pr-needs-review

#16905 blockdev: Use fallible and modern Serenity APIs
  Userland/Utilities/blockdev.cpp
Labels: 👀 pr-needs-review

#16904 passwd: Use StringView instead of DeprecatedString
  Userland/Utilities/passwd.cpp
Labels: 👀 pr-needs-review, ✅ pr-community-approved

#16908 chgrp: Use StringView instead of 'char const*'
  Userland/Utilities/chgrp.cpp
Labels: 👀 pr-needs-review

#16910 Ladybird: Add Qt's standard refresh key (F5) to reload shortcuts
  Ladybird/Tab.cpp
Labels: 👀 pr-needs-review

#16912 Documentation: Fix typo in CLionConfiguration.md
  Documentation/CLionConfiguration.md
Labels: 👀 pr-needs-review

#16889 Magnifier: Port to `Core::Stream`
  Userland/Applications/Magnifier/main.cpp
Labels: ⏳ pr-waiting-for-author

#16916 base64: TRY() the fallible function encode_base64()
  Userland/Utilities/base64.cpp
Labels: 👀 pr-needs-review

#16753 Ports/timidity: Use fresh `config.guess` for timidity
  Ports/timidity/package.sh
Labels: 👀 pr-needs-review

#16924 fortunes: Fix broken links to now-defunct freenode.logbot.info
  Base/res/fortunes.json
Labels: 👀 pr-needs-review

#16919 LibGUI: Make CommonLocationsProvider::load_from_json() failable
  Userland/Libraries/LibGUI/CommonLocationsProvider.cpp
  Userland/Libraries/LibGUI/CommonLocationsProvider.h
Labels: 👀 pr-needs-review

#16921 Help: Update browse view when opening a new help page
  Userland/Applications/Help/MainWidget.cpp
Labels: 👀 pr-needs-review

#16915 LibWeb: Respect `box-sizing: content-box` inside inline-blocks
  Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Labels: 👀 pr-needs-review

#16841 LibWeb+WebContent: Use new String class in CSS::StyleValue
  Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSMediaFeatureID.cpp
  Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSValueID.cpp
  Userland/Libraries/LibWeb/CSS/Angle.cpp
  Userland/Libraries/LibWeb/CSS/Angle.h
  Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp
  Userland/Libraries/LibWeb/CSS/Frequency.cpp
  Userland/Libraries/LibWeb/CSS/Frequency.h
  Userland/Libraries/LibWeb/CSS/GridTrackPlacement.cpp
  Userland/Libraries/LibWeb/CSS/GridTrackPlacement.h
  Userland/Libraries/LibWeb/CSS/GridTrackSize.cpp
  Userland/Libraries/LibWeb/CSS/GridTrackSize.h
  Userland/Libraries/LibWeb/CSS/Length.cpp
  Userland/Libraries/LibWeb/CSS/Length.h
  Userland/Libraries/LibWeb/CSS/MediaList.cpp
  Userland/Libraries/LibWeb/CSS/MediaQuery.cpp
  Userland/Libraries/LibWeb/CSS/MediaQuery.h
  Userland/Libraries/LibWeb/CSS/Number.h
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/CSS/Percentage.h
  Userland/Libraries/LibWeb/CSS/Ratio.cpp
  Userland/Libraries/LibWeb/CSS/Ratio.h
  Userland/Libraries/LibWeb/CSS/Resolution.cpp
  Userland/Libraries/LibWeb/CSS/Resolution.h
  Userland/Libraries/LibWeb/CSS/Serialize.cpp
  Userland/Libraries/LibWeb/CSS/Serialize.h
  Userland/Libraries/LibWeb/CSS/Size.cpp
  Userland/Libraries/LibWeb/CSS/Size.h
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
  Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
  Userland/Libraries/LibWeb/CSS/StyleValue.cpp
  Userland/Libraries/LibWeb/CSS/StyleValue.h
  Userland/Libraries/LibWeb/CSS/Time.cpp
  Userland/Libraries/LibWeb/CSS/Time.h
  Userland/Libraries/LibWeb/Dump.cpp
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
  Userland/Services/WebContent/ConnectionFromClient.cpp
  Userland/Services/WebContent/WebDriverConnection.cpp
Labels: 👀 pr-needs-review

#16705 AK: Reoder AK/Math after the removal of i686
  AK/Math.h
Labels: 👀 pr-needs-review

#16922 Ports: Use sha256 hash for libmpg123
  Ports/libmpg123/package.sh
Labels: 👀 pr-needs-review, ✅ pr-community-approved

#16929 Meta: Add myself to CODEOWNERS
  .github/CODEOWNERS
Labels: 👀 pr-needs-review

#16899 LibWeb: Table Formatting Context refactoring
  Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/TableFormattingContext.h
Labels: 👀 pr-needs-review

#16930 LibWeb: Move clear property from table-root to table-wrapper
  Userland/Libraries/LibWeb/Layout/Node.cpp
  Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Labels: 👀 pr-needs-review

#16920 Ports: Make `sed` work on macOS
  Ports/.port_include.sh
  Ports/libvorbis/package.sh
  Ports/readline/package.sh
  Ports/timidity/package.sh
Labels: 👀 pr-needs-review, ✅ pr-community-approved

#16901 Kernel/FileSystem: Fix kernel panic during File System initialization or mount failure
  Kernel/FileSystem/VirtualFileSystem.cpp
Labels: ✅ pr-community-approved

#16941 LibWeb: Fix y position calculation for blocks with clearance
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Labels: 👀 pr-needs-review

#16940 LibJS: Update ISODaysInMonth in Calendar.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
Labels: 👀 pr-needs-review

#16949 LibWeb: Ensure legacy constructors are defined on the global object
  Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWindowOrWorkerInterfaces.cpp
Labels: 👀 pr-needs-review

#16950 LibJS: Use a work queue instead of the C++ stack for the GC mark phase
  Userland/Libraries/LibJS/Heap/Heap.cpp
  Userland/Libraries/LibJS/Tests/gc-deeply-nested-object-graph.js
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#16956 HackStudio: Hide autocomplete popup when switching tabs
  Userland/DevTools/HackStudio/HackStudioWidget.cpp
  Userland/Libraries/LibGUI/TextEditor.h
Labels: 👀 pr-needs-review

#16953 LibGUI: Lex INI files as Utf8
  Userland/Libraries/LibGUI/INILexer.cpp
  Userland/Libraries/LibGUI/INILexer.h
Labels: 👀 pr-needs-review

#16726 LibCore: Explain EventLoop and reorder some members in the header
  Userland/Libraries/LibCore/EventLoop.cpp
  Userland/Libraries/LibCore/EventLoop.h
Labels: 👀 pr-needs-review

#16958 AK: Implement FlyString for the new String class
  AK/CMakeLists.txt
  AK/FlyString.cpp
  AK/FlyString.h
  AK/Forward.h
  AK/String.cpp
  AK/String.h
  Tests/AK/CMakeLists.txt
  Tests/AK/TestFlyString.cpp
Labels: 👀 pr-needs-review

#16965 PixelPaint: Scale lasso tool preview path on zoom level change
  Userland/Applications/PixelPaint/Tools/LassoSelectTool.cpp
  Userland/Applications/PixelPaint/Tools/LassoSelectTool.h
Labels: 👀 pr-needs-review

#16963 LibGUI: Port AbstractThemePreview::set_theme_from_file to Core::Stream
  Userland/Applications/DisplaySettings/ThemePreviewWidget.cpp
  Userland/Libraries/LibGUI/AbstractThemePreview.cpp
  Userland/Libraries/LibGUI/AbstractThemePreview.h
Labels: 👀 pr-needs-review

#16977 Browser: Implement zoom :^)
  Userland/Applications/Browser/BrowserWindow.cpp
  Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
  Userland/Libraries/LibWebView/OutOfProcessWebView.h
Labels: 👀 pr-needs-review

#16978 Ladybird: Add Ctrl+= as alternate shortcut for "zoom in" + use platform standard shortcuts
  Ladybird/BrowserWindow.cpp
Labels: 👀 pr-needs-review

#16954 Base: Add video file type icon
  Base/etc/FileIconProvider.ini
  Base/res/icons/16x16/filetype-video.png
  Base/res/icons/32x32/filetype-video.png
Labels: 👀 pr-needs-review

#16989 LibJS: Use integer days in RoundDuration
  Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
Labels: 👀 pr-needs-review

#16946 LibCore: Call the mkstemp function in a slightly prettier way
  Userland/Libraries/LibCore/Account.cpp
  Userland/Libraries/LibCore/Group.cpp
Labels: ⏳ pr-waiting-for-author

#16991 Kernel: Remove outdated FIXME in the DeviceManagement code
  Kernel/Devices/DeviceManagement.h
Labels: 👀 pr-needs-review

#16984 PixelPaint: Don't allow the move tool to resize to zero pixels
  Userland/Applications/PixelPaint/Tools/MoveTool.cpp
Labels: 👀 pr-needs-review

#16981 PixelPaint: Hold shift to constrain polygonal select tool line angle
  Userland/Applications/PixelPaint/Tools/LineTool.cpp
  Userland/Applications/PixelPaint/Tools/PolygonalSelectTool.cpp
  Userland/Applications/PixelPaint/Tools/Tool.cpp
  Userland/Applications/PixelPaint/Tools/Tool.h
Labels: 👀 pr-needs-review

#16997 LibCore: Enable file descriptor passing on FreeBSD
  Userland/Libraries/LibCore/Stream.cpp
Labels: 👀 pr-needs-review

#17002 Meta: Fix copyright header in Kernel/Syscalls/jail.cpp file
  Kernel/Syscalls/jail.cpp
Labels: 👀 pr-needs-review

#17007 LibSQL: Don't do fchmod on FreeBSD
  Userland/Libraries/LibSQL/SQLClient.cpp
Labels: 👀 pr-needs-review

#17012 LibCore: On OpenBSD, handle anon_create() like on MacOS
  Userland/Libraries/LibCore/System.cpp
Labels: 👀 pr-needs-review

#17010 LibSQL: Don't do fchmod on OpenBSD
  Userland/Libraries/LibSQL/SQLClient.cpp
Labels: 👀 pr-needs-review

#17008 AK: Remove `CircularDuplexStream`
  AK/CircularDuplexStream.h
  AK/CircularQueue.h
  AK/Forward.h
  Tests/AK/CMakeLists.txt
  Tests/AK/TestCircularDuplexStream.cpp
Labels: 👀 pr-needs-review

#16898 AK: Default move operators for `CircularBuffer`
  AK/CircularBuffer.h
Labels: 👀 pr-needs-review

#17022 Everywhere: Fully qualify IsLvalueReference in TRY() macros
  AK/Try.h
  Kernel/Net/Socket.h
  Meta/Lagom/Tools/CodeGenerators/LibLocale/GenerateLocaleData.cpp
  Userland/Libraries/LibAudio/LoaderError.h
  Userland/Libraries/LibJS/Runtime/Completion.h
  Userland/Libraries/LibJS/Runtime/PromiseCapability.h
  Userland/Libraries/LibVideo/DecoderError.h
  Userland/Libraries/LibVideo/PlaybackManager.cpp
  Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
  Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
  Userland/Utilities/matroska.cpp
Labels: 👀 pr-needs-review

#17019 Fix incorrect limits
  Userland/Libraries/LibC/limits.h
Labels: 👀 pr-needs-review

#17013 LibCore: Enable file descriptor passing on OpenBSD
  Userland/Libraries/LibCore/Stream.cpp
Labels: 👀 pr-needs-review

#17024 Presenter: Use the non-deprecated API of `LibFileSystemAccessClient`
  Userland/Applications/Presenter/PresenterWidget.cpp
Labels: 👀 pr-needs-review

#17030 LibWeb: Make sure that fetch() response cookies get saved
  Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
Labels: 👀 pr-needs-review

#17027 hexdump: Add an option to specify dump offset
  Userland/Utilities/hexdump.cpp
Labels: 👀 pr-needs-review

#17025 WidgetGallery: Use the non-deprecated API of `LibFileSystemAccessClient`
  Userland/Demos/WidgetGallery/GalleryWidget.cpp
Labels: 👀 pr-needs-review

#16998 PixelPaint: Hold shift to increase move tool speed with the arrow keys
  Userland/Applications/PixelPaint/Tools/MoveTool.cpp
Labels: 👀 pr-needs-review

#17017 ClipboardHistory: Add clear history action
  Userland/Applets/ClipboardHistory/ClipboardHistoryModel.cpp
  Userland/Applets/ClipboardHistory/ClipboardHistoryModel.h
  Userland/Applets/ClipboardHistory/main.cpp
Labels: 👀 pr-needs-review

#17033 LibGfx: Prevent reading OOB in TGA header decode
  Userland/Libraries/LibGfx/TGALoader.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17036 AK+Test: Fix a logic error in `CircularBuffer::offset_of()`
  AK/CircularBuffer.cpp
  Tests/AK/TestCircularBuffer.cpp
Labels: 👀 pr-needs-review

#16967 Meta: Add myself to CODEOWNERS
  .github/CODEOWNERS
Labels: 👀 pr-needs-review

#17038 LibWeb: Prevent floats from being positioned higher than preceding blocks
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Labels: 👀 pr-needs-review

#16994 LibLine: Port most functions to `Core::Stream` and start propagating errors
  Userland/Libraries/LibLine/Editor.cpp
  Userland/Libraries/LibLine/Editor.h
  Userland/Libraries/LibLine/InternalFunctions.cpp
  Userland/Libraries/LibLine/SuggestionDisplay.h
  Userland/Libraries/LibLine/SuggestionManager.cpp
  Userland/Libraries/LibLine/SuggestionManager.h
  Userland/Libraries/LibLine/VT.h
  Userland/Libraries/LibLine/XtermSuggestionDisplay.cpp
Labels: 👀 pr-needs-review, ✅ pr-community-approved

#17032 WebDriver: Add computedrole endpoint
  Userland/Libraries/LibWeb/WebDriver/Client.cpp
  Userland/Libraries/LibWeb/WebDriver/Client.h
  Userland/Services/WebContent/WebDriverClient.ipc
  Userland/Services/WebContent/WebDriverConnection.cpp
  Userland/Services/WebContent/WebDriverConnection.h
  Userland/Services/WebDriver/Client.cpp
  Userland/Services/WebDriver/Client.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17040 Meta: Add dependabot configuration to update github actions
  .github/dependabot.yml
Labels: 👀 pr-needs-review

#17042 LibCore: Correctly map seek offsets for buffered streams (and optimize short seeks)
  Tests/LibCore/TestLibCoreStream.cpp
  Userland/Libraries/LibCore/Stream.h
Labels: 👀 pr-needs-review, ✅ pr-community-approved

#17003 Base: Add more emoji 🤱 💃 🪶 🧉 👩‍👦‍👦 (ᵈᵒ ʷᵉ ʳᵉᵃˡˡʸ ⁿᵉᵉᵈ ᵐᵒʳᵉ ᵉᵐᵒʲᶦ? ʸᵉˢ!)
  Base/res/emoji/U+1F468_U+200D_U+1F466_U+200D_U+1F466.png
  Base/res/emoji/U+1F469_U+200D_U+1F466.png
  Base/res/emoji/U+1F469_U+200D_U+1F466_U+200D_U+1F466.png
  Base/res/emoji/U+1F469_U+200D_U+1F467.png
  Base/res/emoji/U+1F469_U+200D_U+1F467_U+200D_U+1F466.png
  Base/res/emoji/U+1F469_U+200D_U+1F467_U+200D_U+1F467.png
  Base/res/emoji/U+1F483.png
  Base/res/emoji/U+1F4AE.png
  Base/res/emoji/U+1F6A3.png
  Base/res/emoji/U+1F6A3_U+200D_U+2640.png
  Base/res/emoji/U+1F6A3_U+200D_U+2642.png
  Base/res/emoji/U+1F931.png
  Base/res/emoji/U+1F9C9.png
  Base/res/emoji/U+1FAB6.png
  Base/res/emoji/U+26F4.png
  Base/res/emoji/U+26F9.png
  Base/res/emoji/U+26F9_U+200D_U+2640.png
  Base/res/emoji/U+26F9_U+200D_U+2642.png
Labels: 👀 pr-needs-review

#17068 Presenter: Restructure menu, increase minimum size
  Userland/Applications/Presenter/PresenterWidget.cpp
Labels: 👀 pr-needs-review

#17072 Lagom/Fuzzers: Add fuzzer for ICCProfile
  Meta/Lagom/Fuzzers/CMakeLists.txt
  Meta/Lagom/Fuzzers/FuzzICCProfile.cpp
Labels: 👀 pr-needs-review

#17074 LibWeb: Define window.isSecureContext
  Userland/Libraries/LibWeb/HTML/Window.cpp
  Userland/Libraries/LibWeb/HTML/Window.h
Labels: 👀 pr-needs-review

#17079 FuzzilliJs: Print the result of `JS::Value::to_string` using `AK::outln`
  Meta/Lagom/Fuzzers/FuzzilliJs.cpp
Labels: 👀 pr-needs-review

#17080 CI: Ignore dependabot in commit linter for PRs
  .github/workflows/lintcommits.yml
Labels: 👀 pr-needs-review

#17034 LibGfx+Ladybird+Userland: Don't sniff for TGA images with only raw bytes
  Ladybird/ImageCodecPluginLadybird.cpp
  Userland/Applications/ImageViewer/ViewWidget.cpp
  Userland/Libraries/LibGUI/ImageWidget.cpp
  Userland/Libraries/LibGfx/Bitmap.cpp
  Userland/Libraries/LibGfx/ImageDecoder.cpp
  Userland/Libraries/LibGfx/ImageDecoder.h
  Userland/Libraries/LibImageDecoderClient/Client.cpp
  Userland/Libraries/LibImageDecoderClient/Client.h
  Userland/Services/ImageDecoder/ConnectionFromClient.cpp
  Userland/Services/ImageDecoder/ConnectionFromClient.h
  Userland/Services/ImageDecoder/ImageDecoderServer.ipc
  Userland/Utilities/file.cpp
  Userland/Utilities/headless-browser.cpp
Labels: 👀 pr-needs-review

#17083 LibWeb: Convert the Location object to IDL
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
  Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWindowOrWorkerInterfaces.cpp
  Userland/Libraries/LibWeb/Bindings/LocationConstructor.cpp
  Userland/Libraries/LibWeb/Bindings/LocationConstructor.h
  Userland/Libraries/LibWeb/Bindings/LocationPrototype.h
  Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/DOM/Document.idl
  Userland/Libraries/LibWeb/Forward.h
  Userland/Libraries/LibWeb/HTML/CrossOrigin/AbstractOperations.cpp
  Userland/Libraries/LibWeb/HTML/CrossOrigin/AbstractOperations.h
  Userland/Libraries/LibWeb/HTML/Location.cpp
  Userland/Libraries/LibWeb/HTML/Location.h
  Userland/Libraries/LibWeb/HTML/Location.idl
  Userland/Libraries/LibWeb/HTML/Window.cpp
  Userland/Libraries/LibWeb/HTML/Window.h
  Userland/Libraries/LibWeb/idl_files.cmake
Labels: 👀 pr-needs-review

#17075 LibC: Remove the stub iconv header
  Userland/Libraries/LibC/iconv.h
Labels: 👀 pr-needs-review

#17089 Presenter: Disable actions when there is no loaded presentation
  Userland/Applications/Presenter/PresenterWidget.cpp
  Userland/Applications/Presenter/PresenterWidget.h
Labels: 👀 pr-needs-review

#17097 CI: Add GitHub author presence check in commit linter
  .github/workflows/lintcommits.yml
Labels: 👀 pr-needs-review

#17110 AK: Disable use of consteval in String::from_utf8_short_string for Apple
  AK/String.h
Labels: 👀 pr-needs-review

#17106 LibCore: Avoid logical OOB read in AllocatingMemoryStream::offset_of()
  Tests/LibCore/TestLibCoreStream.cpp
  Userland/Libraries/LibCore/MemoryStream.cpp
Labels: 👀 pr-needs-review

#17108 LibGfx: Scaffolding for reading ICC tag table
  Userland/Libraries/LibGfx/ICCProfile.cpp
  Userland/Libraries/LibGfx/ICCProfile.h
  Userland/Utilities/icc.cpp
Labels: 👀 pr-needs-review

#17117 icc: Tweak output to look nicer
  Userland/Utilities/icc.cpp
Labels: 👀 pr-needs-review

#17056 LibWeb: Fix floats y offset calculation
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Labels: 👀 pr-needs-review

#17136 AK: Reduce String's allocated data by one byte
  AK/String.cpp
Labels: 👀 pr-needs-review

#17134 LibJS: Use is_unicode_surrogate more
  Userland/Libraries/LibJS/Runtime/JSONObject.cpp
  Userland/Libraries/LibJS/Runtime/StringPrototype.cpp
Labels: 👀 pr-needs-review

#17145 LibWeb: Use CSS Pixels for overflow clip rect
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
  Userland/Libraries/LibWeb/Painting/PaintableBox.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17146 LibGfx+icc: Add ICCProfile support for XYZType and print it
  Userland/Libraries/LibGfx/ICCProfile.cpp
  Userland/Libraries/LibGfx/ICCProfile.h
  Userland/Utilities/icc.cpp
Labels: 👀 pr-needs-review

#17147 LibGfx: Do not repeat class name in ICC from_bytes() functions
  Userland/Libraries/LibGfx/ICCProfile.cpp
Labels: 👀 pr-needs-review
