Repository SerenityOS/serenity, pull requests merged in 2023-09, with the labels that each got.

#20884 Meta: Port recent build changes to gn build
  Meta/gn/secondary/Ladybird/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWebView/BUILD.gn
Labels: 👀 pr-needs-review

#20886 LibCore: Don't print class_name() from EventReceiver::stop_timer()
  Userland/Libraries/LibCore/EventReceiver.cpp
Labels: 👀 pr-needs-review

#20870 LibWeb: Add presentation hints to the canvas element
  Userland/Libraries/LibWeb/HTML/HTMLCanvasElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLCanvasElement.h
Labels: 👀 pr-needs-review

#20852 AK: Always use our assertion failure method, and add backtrace to it
  AK/Assertions.cpp
  AK/Assertions.h
  Meta/Lagom/CMakeLists.txt
Labels: 👀 pr-needs-review

#20867 Userland: Migrate to String in notification system
  Userland/Applets/Network/main.cpp
  Userland/DevTools/HackStudio/LanguageClient.cpp
  Userland/DevTools/HackStudio/main.cpp
  Userland/Libraries/LibGUI/Notification.h
  Userland/Services/NotificationServer/ConnectionFromClient.cpp
  Userland/Services/NotificationServer/ConnectionFromClient.h
  Userland/Services/NotificationServer/NotificationServer.ipc
  Userland/Services/NotificationServer/NotificationWindow.cpp
  Userland/Services/NotificationServer/NotificationWindow.h
  Userland/Utilities/notify.cpp
Labels: 👀 pr-needs-review

#20857 Ports/dos2unix: Update to 7.5.1
  Ports/AvailablePorts.md
  Ports/dos2unix/package.sh
Labels: 👀 pr-needs-review

#20885 Userland+Tests: Don't use MAP_FILE when mmap-ing
  Tests/Kernel/TestEmptyPrivateInodeVMObject.cpp
  Tests/Kernel/TestEmptySharedInodeVMObject.cpp
  Tests/Kernel/TestPrivateInodeVMObject.cpp
  Tests/Kernel/TestSharedInodeVMObject.cpp
  Tests/Kernel/elf-execve-mmap-race.cpp
  Tests/Kernel/mmap-write-into-running-programs-executable-file.cpp
  Tests/LibC/TestIo.cpp
  Userland/Libraries/LibCore/AnonymousBuffer.cpp
  Userland/Libraries/LibELF/DynamicLoader.cpp
Labels: 👀 pr-needs-review

#20868 LibAudio: Fix uncommon 16-bit block size symbol
  Userland/Libraries/LibAudio/FlacTypes.h
Labels: 👀 pr-needs-review

#20838 find: Add the `-newer`, `-anewer` and `-cnewer` options
  Base/usr/share/man/man1/find.md
  Userland/Utilities/find.cpp
Labels: 👀 pr-needs-review

#20788 Ports: Add libwebp
  Ports/AvailablePorts.md
  Ports/libwebp/package.sh
  Ports/libwebp/patches/0001-libtool-Enable-shared-library-support-for-SerenityOS.patch
  Ports/libwebp/patches/ReadMe.md
Labels: 👀 pr-needs-review

#20893 find: Add the `-empty` option
  Base/usr/share/man/man1/find.md
  Userland/Utilities/find.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#20905 LibJS: Add file & line number to bytecode VM stack traces :^)
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
  Userland/Libraries/LibJS/Bytecode/Executable.h
  Userland/Libraries/LibJS/Bytecode/Generator.cpp
  Userland/Libraries/LibJS/Bytecode/Generator.h
  Userland/Libraries/LibJS/Bytecode/Instruction.cpp
  Userland/Libraries/LibJS/Bytecode/Instruction.h
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
  Userland/Libraries/LibJS/Bytecode/Interpreter.h
  Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
  Userland/Libraries/LibJS/Runtime/Error.cpp
  Userland/Libraries/LibJS/Runtime/ExecutionContext.cpp
  Userland/Libraries/LibJS/Runtime/ExecutionContext.h
  Userland/Libraries/LibJS/Runtime/NativeFunction.cpp
  Userland/Libraries/LibJS/Runtime/VM.cpp
  Userland/Libraries/LibJS/Tests/builtins/Error/Error.prototype.stack.js
  Userland/Utilities/js.cpp
Labels: 👀 pr-needs-review

#20909 LibWeb: Support `readonly` attribute for HTMLInputElement
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
Labels: 👀 pr-needs-review

#20911 About: Display Application's Icon in File Manager
  Userland/Applications/About/CMakeLists.txt
Labels: 👀 pr-needs-review

#20907 Userland: Always call syscall(SC_prctl, ...) with 4 arguments
  Userland/Libraries/LibC/assert.cpp
  Userland/Libraries/LibC/unistd.cpp
  Userland/Libraries/LibELF/DynamicLinker.cpp
Labels: 👀 pr-needs-review

#20914 LibJS: Only update EC instruction pointer when pushing to EC stack
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
  Userland/Libraries/LibJS/Runtime/ExecutionContext.h
  Userland/Libraries/LibJS/Runtime/VM.cpp
  Userland/Libraries/LibJS/Runtime/VM.h
Labels: 👀 pr-needs-review

#20921 LibWeb: Don't send audio time updates until audio is playing
  Userland/Libraries/LibWeb/Platform/AudioCodecPluginAgnostic.cpp
Labels: 👀 pr-needs-review

#20774 Ports: Add liblzf
  Ports/AvailablePorts.md
  Ports/liblzf/package.sh
Labels: 👀 pr-needs-review

#20908 Ports: Add lcms2
  Ports/AvailablePorts.md
  Ports/lcms2/package.sh
Labels: 👀 pr-needs-review

#20918 AK: Demangle symbols on assertion failure on Linux as well
  AK/Assertions.cpp
Labels: 👀 pr-needs-review

#20916 LibWeb: Stub out HTMLDialogElement APIs
  Userland/Libraries/LibWeb/HTML/HTMLDialogElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLDialogElement.h
  Userland/Libraries/LibWeb/HTML/HTMLDialogElement.idl
Labels: 👀 pr-needs-review

#20922 LibC: Set `(U)LONG_WIDTH` correctly for 64-bit
  Userland/Libraries/LibC/limits.h
Labels: 👀 pr-needs-review

#20928 LibWeb: Use flex layout for button content alignment
  Tests/LibWeb/Layout/expected/block-and-inline/button-baseline-align.txt
  Tests/LibWeb/Layout/expected/block-and-inline/button-image-only.txt
  Tests/LibWeb/Layout/expected/block-and-inline/button-should-have-vertically-aligned-content.txt
  Tests/LibWeb/Layout/expected/block-and-inline/button-with-abspos-pseudo-element.txt
  Tests/LibWeb/Layout/expected/block-and-inline/button-with-block-content-baseline-align.txt
  Tests/LibWeb/Layout/expected/block-and-inline/button-with-multiple-words-text-node-label.txt
  Tests/LibWeb/Layout/expected/block-and-inline/button-with-text-node-label-and-font-size.txt
  Tests/LibWeb/Layout/expected/block-and-inline/button-with-text-node-label.txt
  Tests/LibWeb/Layout/expected/table/table-cell-not-paintable.txt
  Tests/LibWeb/Layout/input/block-and-inline/button-with-abspos-pseudo-element.html
  Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Labels: 👀 pr-needs-review

#20929 LibCore: Recognize .xht as an HTML document
  Userland/Libraries/LibCore/MimeData.cpp
Labels: 👀 pr-needs-review

#20895 LibGfx: Remove maximum size limit for decoded images
  Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp
  Userland/Libraries/LibGfx/ImageFormats/GIFLoader.cpp
  Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.h
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
  Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp
  Userland/Libraries/LibGfx/ImageFormats/PortableImageLoaderCommon.h
Labels: 👀 pr-needs-review

#20930 LibWeb: Add DOMMatrix multiply and translate
  Tests/LibWeb/Text/expected/geometry/dommatrix.txt
  Tests/LibWeb/Text/input/geometry/dommatrix.html
  Userland/Libraries/LibWeb/Geometry/DOMMatrix.cpp
  Userland/Libraries/LibWeb/Geometry/DOMMatrix.h
  Userland/Libraries/LibWeb/Geometry/DOMMatrix.idl
  Userland/Libraries/LibWeb/Geometry/DOMMatrixReadOnly.cpp
  Userland/Libraries/LibWeb/Geometry/DOMMatrixReadOnly.h
  Userland/Libraries/LibWeb/Geometry/DOMMatrixReadOnly.idl
Labels: 👀 pr-needs-review

#20932 LibWeb: Handle case where abspos flex child position depends on height
  Tests/LibWeb/Layout/expected/flex/abspos-flex-child-with-auto-height.txt
  Tests/LibWeb/Layout/input/flex/abspos-flex-child-with-auto-height.html
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Labels: 👀 pr-needs-review

#20701 Maps: Add new basic maps application and maps widget
  Base/res/apps/Maps.af
  Userland/Applications/CMakeLists.txt
  Userland/Applications/Maps/CMakeLists.txt
  Userland/Applications/Maps/MapWidget.cpp
  Userland/Applications/Maps/MapWidget.h
  Userland/Applications/Maps/main.cpp
Labels: 👀 pr-needs-review

#20936 LibWeb: Remove GC allocations in FetchAlgorithms constructor
  Userland/Libraries/LibWeb/Fetch/Infrastructure/FetchAlgorithms.cpp
  Userland/Libraries/LibWeb/Fetch/Infrastructure/FetchAlgorithms.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#20942 Meta: Add `-fno-omit-frame-pointer` flag
  Meta/CMake/serenity_compile_options.cmake
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#20938 LibWasm: Explicitly place the paddings in the WASI API types
  Userland/Libraries/LibWasm/WASI/Wasi.cpp
  Userland/Libraries/LibWasm/Wasi.h
Labels: 👀 pr-needs-review

#20933 Ladybird: Hide the WebDriver-to-WebContent IPC path from the help menu
  Ladybird/AppKit/main.mm
  Ladybird/Qt/main.cpp
  Userland/Applications/Browser/main.cpp
Labels: 👀 pr-needs-review

#20952 Maps: Add Application Icons
  Base/res/icons/16x16/app-maps.png
  Base/res/icons/32x32/app-maps.png
  Userland/Applications/Maps/CMakeLists.txt
  Userland/Applications/Maps/main.cpp
Labels: 👀 pr-needs-review

#20903 Calendar: Save time of the event and display it in Calendar
  Userland/Applications/Calendar/AddEventDialog.cpp
  Userland/Applications/Calendar/EventCalendar.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#20960 LibWeb: Print FIXME if vertical-align value is not supported in TFC
  Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Labels: 👀 pr-needs-review

#20959 Maps: Add pledge and unveils
  Userland/Applications/Maps/main.cpp
Labels: 👀 pr-needs-review

#20964 Ladybird: Fix the include of use_linker in CMakeLists.txt
  Ladybird/CMakeLists.txt
Labels: 👀 pr-needs-review

#20967 AK: Use arc4random_buf() for Random on all BSDs
  AK/Random.h
Labels: 👀 pr-needs-review

#20902 Userland: Fix absolute paths in man page links
  Userland/Libraries/LibMarkdown/Text.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#20966 Meta: Run Android CI via gradle wrapper instead of via CMake
  Ladybird/Android/build.gradle.kts
  Meta/Azure/Lagom.yml
  Meta/Azure/Setup.yml
Labels: 👀 pr-needs-review

#20973 Documentation: Fix Ladybird executable path in `BuildInstructionsLadybird.md`
  Documentation/BuildInstructionsLadybird.md
Labels: 👀 pr-needs-review

#20975 Ports/devilutionX: Update to version 1.5.1
  Ports/AvailablePorts.md
  Ports/devilutionX/package.sh
Labels: 👀 pr-needs-review

#20979 LibWeb+WebContent: Set ConsoleClient for nested browsing contexts
  Userland/Libraries/LibWeb/Loader/FrameLoader.cpp
  Userland/Libraries/LibWeb/Page/Page.h
  Userland/Services/WebContent/ConnectionFromClient.cpp
  Userland/Services/WebContent/ConnectionFromClient.h
  Userland/Services/WebContent/PageHost.cpp
  Userland/Services/WebContent/PageHost.h
Labels: 👀 pr-needs-review

#20919 Ports: Add giflib
  Ports/AvailablePorts.md
  Ports/giflib/package.sh
Labels: 👀 pr-needs-review

#20976 find: Print hyperlinks when standard output is attached to a terminal
  Userland/Utilities/CMakeLists.txt
  Userland/Utilities/find.cpp
Labels: 👀 pr-needs-review

#20931 Shell: Allow the user to set the prompt using PROMPT()
  Userland/Shell/Builtin.cpp
  Userland/Shell/Shell.cpp
  Userland/Shell/Shell.h
Labels: 👀 pr-needs-review

#20920 Kernel/riscv64: Add basic SBI support
  Kernel/Arch/riscv64/SBI.cpp
  Kernel/Arch/riscv64/SBI.h
  Kernel/CMakeLists.txt
Labels: 👀 pr-needs-review

#20974 LibWeb: Implement support for parsing CSS column-count property
  Userland/Libraries/LibWeb/CSS/ColumnCount.h
  Userland/Libraries/LibWeb/CSS/ComputedValues.h
  Userland/Libraries/LibWeb/CSS/Properties.json
  Userland/Libraries/LibWeb/Layout/Node.cpp
Labels: 👀 pr-needs-review

#20712 LibCore: Implement waiting for the debugger on FreeBSD
  Userland/Libraries/LibCore/Process.cpp
Labels: 👀 pr-needs-review

#20995 LibWeb: Stop crashing when textarea element is modified before insertion
  Tests/LibWeb/Layout/expected/textarea-content.txt
  Tests/LibWeb/Layout/input/textarea-content.html
  Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
Labels: 👀 pr-needs-review

#20984 Correct link in BuildInstructionsOther.md
  Documentation/BuildInstructionsOther.md
Labels: 👀 pr-needs-review

#20999 LibWeb: Use actual line height to calculate float y in IFC
  Tests/LibWeb/Layout/expected/block-and-inline/float-should-avoid-inline-block.txt
  Tests/LibWeb/Layout/input/block-and-inline/float-should-avoid-inline-block.html
  Userland/Libraries/LibWeb/Layout/LineBox.cpp
  Userland/Libraries/LibWeb/Layout/LineBuilder.cpp
Labels: 👀 pr-needs-review

#20998 Base: Fix sys(7) manual page
  Base/usr/share/man/man7/sys.md
Labels: 👀 pr-needs-review

#20941 Snake: Replace DeprecatedString with String
  Userland/Games/Snake/Game.cpp
  Userland/Games/Snake/Game.h
  Userland/Games/Snake/Skins/ImageSkin.cpp
  Userland/Games/Snake/Skins/ImageSkin.h
  Userland/Games/Snake/main.cpp
Labels: 👀 pr-needs-review

#20978 Ladybird: Add WebContentService for Android port
  Ladybird/Android/src/main/AndroidManifest.xml
  Ladybird/Android/src/main/cpp/WebContentService.cpp
  Ladybird/Android/src/main/cpp/WebViewImplementationNative.cpp
  Ladybird/Android/src/main/java/org/serenityos/ladybird/WebContentService.kt
  Ladybird/Android/src/main/java/org/serenityos/ladybird/WebContentServiceConnection.kt
  Ladybird/Android/src/main/java/org/serenityos/ladybird/WebView.kt
  Ladybird/Android/src/main/java/org/serenityos/ladybird/WebViewImplementation.kt
  Ladybird/WebContent/CMakeLists.txt
  Ladybird/cmake/InstallRules.cmake
Labels: 👀 pr-needs-review

#20896 find: Add `!` operator to negate the following command
  Base/usr/share/man/man1/find.md
  Userland/Utilities/find.cpp
Labels: 👀 pr-needs-review

#20925 LibWebSocket: Adds capability for receiving fragmented messages
  Userland/Libraries/LibWebSocket/WebSocket.cpp
  Userland/Libraries/LibWebSocket/WebSocket.h
Labels: 👀 pr-needs-review

#20962 find: Allow '+' and '-' prefix for `-links` and `-size` options
  Base/usr/share/man/man1/find.md
  Userland/Utilities/find.cpp
Labels: 👀 pr-needs-review

#20923 LibIMAP: Don't crash on mails with attachments
  Userland/Applications/Mail/MailWidget.cpp
  Userland/Libraries/LibIMAP/Objects.h
  Userland/Libraries/LibIMAP/Parser.cpp
Labels: 👀 pr-needs-review

#20910 Add AK::InvokeResult
  AK/StdLibExtraDetails.h
Labels: 👀 pr-needs-review

#20890 Ladybird: Add ladybird.nix to nix flake in Toolchain/
  Documentation/BuildInstructionsLadybird.md
  Toolchain/flake.nix
Labels: 👀 pr-needs-review

#19950 Kernel+ProfileViewer: Monitor and display more filesystem events
  Kernel/API/POSIX/serenity.h
  Kernel/CMakeLists.txt
  Kernel/Syscalls/open.cpp
  Kernel/Syscalls/profiled_syscalls.cpp
  Kernel/Syscalls/read.cpp
  Kernel/Tasks/PerformanceEventBuffer.cpp
  Kernel/Tasks/PerformanceEventBuffer.h
  Kernel/Tasks/PerformanceManager.h
  Kernel/Tasks/Process.h
  Userland/DevTools/Profiler/FilesystemEventModel.cpp
  Userland/DevTools/Profiler/FilesystemEventModel.h
  Userland/DevTools/Profiler/Profile.cpp
  Userland/DevTools/Profiler/Profile.h
  Userland/DevTools/Profiler/SamplesModel.cpp
  Userland/DevTools/Profiler/main.cpp
  Userland/Utilities/profile.cpp
Labels: 👀 pr-needs-review

#21003 Meta: Do not spam "<compiler-name>: command not found"
  Meta/find_compiler.sh
Labels: 👀 pr-needs-review

#20996 AK: Add to_radians and to_degrees math functions
  AK/Math.h
  Userland/Applications/Maps/MapWidget.cpp
  Userland/Applications/PixelPaint/ImageMasking.cpp
  Userland/Applications/PixelPaint/Tools/GradientTool.cpp
  Userland/Games/ColorLines/HueFilter.h
  Userland/Libraries/LibGL/Matrix.cpp
  Userland/Libraries/LibGfx/DeltaE.cpp
  Userland/Libraries/LibGfx/Filters/HueRotateFilter.h
  Userland/Libraries/LibGfx/GradientPainting.cpp
  Userland/Libraries/LibGfx/Gradients.h
  Userland/Libraries/LibSoftGPU/Device.cpp
  Userland/Libraries/LibWeb/CSS/Angle.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/LinearGradientStyleValue.cpp
  Userland/Libraries/LibWeb/Geometry/DOMMatrix.cpp
  Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
Labels: 👀 pr-needs-review

#20963 Maps: Fix a hang, use cached tiles from other zoom levels, and zoom on doubleclick
  Userland/Applications/Maps/MapWidget.cpp
  Userland/Applications/Maps/MapWidget.h
Labels: 👀 pr-needs-review

#21002 Ladybird: Add an audio context menu to the AppKit chrome
  Ladybird/AppKit/UI/LadybirdWebView.mm
Labels: 👀 pr-needs-review

#21010 LibDiff: Fix wrong index used when prepending context lines
  Tests/CMakeLists.txt
  Tests/LibDiff/CMakeLists.txt
  Tests/LibDiff/TestDiff.cpp
  Userland/Libraries/LibDiff/Generator.cpp
Labels: 👀 pr-needs-review

#21026 Ladybird: Allow opening multiple URLs at once from the command line
  Ladybird/Qt/BrowserWindow.cpp
  Ladybird/Qt/BrowserWindow.h
  Ladybird/Qt/main.cpp
Labels: 👀 pr-needs-review

#21037 Revert "AK: Refill a BufferedStream when it has less than the requested size"
  AK/BufferedStream.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#21044 LibJS: Make line-and-column resolution fast for large minified JS
  Userland/Libraries/LibJS/Position.h
  Userland/Libraries/LibJS/SourceCode.cpp
  Userland/Libraries/LibJS/SourceCode.h
  Userland/Libraries/LibJS/SourceRange.h
Labels: 👀 pr-needs-review

#21014 Base: Add manpage for pkg
  Base/usr/share/man/man1/pkg.md
Labels: 👀 pr-needs-review

#21053 2048: Disable the undo and redo actions when unavailable
  Userland/Games/2048/main.cpp
Labels: 👀 pr-needs-review

#21055 GameOfLife: Ensure BoardWidget can always contain the board
  Userland/Games/GameOfLife/BoardWidget.cpp
  Userland/Games/GameOfLife/main.cpp
Labels: 👀 pr-needs-review

#21007 Ladybird/Android: Add EventLoopImplementation for ALooper
  Ladybird/Android/src/main/cpp/ALooperEventLoopImplementation.cpp
  Ladybird/Android/src/main/cpp/ALooperEventLoopImplementation.h
  Ladybird/Android/src/main/cpp/JNIHelpers.h
  Ladybird/Android/src/main/cpp/LadybirdActivity.cpp
  Ladybird/Android/src/main/cpp/TimerExecutorService.cpp
  Ladybird/Android/src/main/cpp/WebContentService.cpp
  Ladybird/Android/src/main/cpp/WebViewImplementationNative.cpp
  Ladybird/Android/src/main/java/org/serenityos/ladybird/LadybirdActivity.kt
  Ladybird/Android/src/main/java/org/serenityos/ladybird/TimerExecutorService.kt
  Ladybird/CMakeLists.txt
  Ladybird/WebContent/CMakeLists.txt
Labels: 👀 pr-needs-review

#21068 LibWeb: Fix missing 'get an output encoding' step in HTMLFormElement
  Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
Labels: 👀 pr-needs-review

#21072 LibJS: Store bytecode instruction length in instruction itself
  Userland/Libraries/LibJS/Bytecode/Instruction.h
  Userland/Libraries/LibJS/Bytecode/Op.h
Labels: 👀 pr-needs-review

#21079 LibWeb: Don't generate ::before/::after for BR elements
  Tests/LibWeb/Layout/expected/br-should-not-generate-pseudo-before.txt
  Tests/LibWeb/Layout/input/br-should-not-generate-pseudo-before.html
  Userland/Libraries/LibWeb/Layout/BreakNode.h
  Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Labels: 👀 pr-needs-review

#21025 LibGfx/ILBM: Add support for uncompressed files
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/ilbm/gradient-uncompressed.iff
  Userland/Libraries/LibGfx/ImageFormats/ILBMLoader.cpp
Labels: 👀 pr-needs-review

#21035 LibWeb: Add XMLHttpRequest Document response type
  Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
  Userland/Libraries/LibWeb/DOM/DocumentLoading.h
  Userland/Libraries/LibWeb/MimeSniff/MimeType.cpp
  Userland/Libraries/LibWeb/MimeSniff/MimeType.h
  Userland/Libraries/LibWeb/XHR/XMLHttpRequest.cpp
  Userland/Libraries/LibWeb/XHR/XMLHttpRequest.h
  Userland/Libraries/LibWeb/XHR/XMLHttpRequest.idl
Labels: 👀 pr-needs-review

#21083 Documentation: Update clang-format version where it was missed
  CONTRIBUTING.md
Labels: 👀 pr-needs-review

#21040 LibWeb: Allow calculated values for `background-size` dimensions
  Tests/LibWeb/Ref/assets/2x2checkerboard.png
  Tests/LibWeb/Ref/background-size-calc.html
  Tests/LibWeb/Ref/reference/background-size-calc-ref.html
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#21078 Userland: Don't use `String::from_utf8()` for literal strings
  Userland/Applications/DisplaySettings/BackgroundSettingsWidget.cpp
  Userland/Applications/FontEditor/MainWidget.cpp
  Userland/Applications/PixelPaint/main.cpp
  Userland/Libraries/LibGUI/UIDimensions.h
  Userland/Services/DeviceMapper/DeviceEventLoop.cpp
  Userland/Utilities/cal.cpp
  Userland/Utilities/pkg/AvailablePort.cpp
  Userland/Utilities/pkg/InstalledPort.cpp
Labels: 👀 pr-needs-review

#21073 LibWeb+WebContent+headless-browser: Support async text tests
  Tests/LibWeb/Text/expected/css/style-sheet-with-byte-order-mark.txt
  Tests/LibWeb/Text/expected/scripted-dom-insertion-during-html-parse.txt
  Tests/LibWeb/Text/input/css/style-sheet-with-byte-order-mark.html
  Tests/LibWeb/Text/input/include.js
  Tests/LibWeb/Text/input/link-element-media-attribute.html
  Tests/LibWeb/Text/input/link-element-onload-attribute.html
  Tests/LibWeb/Text/input/link-element-rel-preload-load-event.html
  Tests/LibWeb/Text/input/link-element-search.html
  Tests/LibWeb/Text/input/scripted-dom-insertion-during-html-parse.html
  Userland/Libraries/LibWeb/Internals/Internals.cpp
  Userland/Libraries/LibWeb/Internals/Internals.h
  Userland/Libraries/LibWeb/Internals/Internals.idl
  Userland/Libraries/LibWeb/Page/Page.h
  Userland/Libraries/LibWebView/ViewImplementation.h
  Userland/Libraries/LibWebView/WebContentClient.cpp
  Userland/Libraries/LibWebView/WebContentClient.h
  Userland/Services/WebContent/PageHost.cpp
  Userland/Services/WebContent/PageHost.h
  Userland/Services/WebContent/WebContentClient.ipc
  Userland/Utilities/headless-browser.cpp
Labels: 👀 pr-needs-review

#21087 LibJS: Avoid pointless HashTable copying during GC mark phase
  Userland/Libraries/LibJS/Heap/Heap.cpp
Labels: 👀 pr-needs-review

#21064 LibRegex: Don't add the Repeat instruction size to its jump target
  Tests/LibRegex/Regex.cpp
  Userland/Libraries/LibRegex/RegexOptimizer.cpp
Labels: 👀 pr-needs-review

#21094 LibWeb: Allow fractional font sizes in CSS
  Tests/LibWeb/Layout/expected/font-fractional-size.txt
  Tests/LibWeb/Layout/input/font-fractional-size.html
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Labels: 👀 pr-needs-review

#21092 LibUnicode: Update to Unicode version 15.1.0
  Meta/CMake/unicode_data.cmake
  Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodeData.cpp
  Tests/LibUnicode/TestSegmentation.cpp
  Userland/Libraries/LibUnicode/Segmentation.cpp
Labels: 👀 pr-needs-review

#21045 Kernel: Use Processor::wait_check in loops waiting for HW to respond
  Kernel/Arch/aarch64/RPi/Mailbox.cpp
  Kernel/Arch/aarch64/RPi/MiniUART.cpp
  Kernel/Arch/aarch64/RPi/UART.cpp
  Kernel/Arch/x86_64/DebugOutput.cpp
  Kernel/Arch/x86_64/Time/APICTimer.cpp
  Kernel/Devices/SerialDevice.cpp
  Kernel/Net/Intel/E1000ENetworkAdapter.cpp
  Kernel/Net/Intel/E1000NetworkAdapter.cpp
  Kernel/Net/Realtek/RTL8168NetworkAdapter.cpp
Labels: 👀 pr-needs-review

#21097 Base: Update serenity-application template so that it compiles
  Base/res/devel/templates/serenity-application/main.cpp
Labels: 👀 pr-needs-review

#21062 LibGUI+Applications: Use String in `make_about_action()`
  Userland/Applications/3DFileViewer/main.cpp
  Userland/Applications/Browser/WindowActions.cpp
  Userland/Applications/Calculator/main.cpp
  Userland/Applications/Calendar/CalendarWidget.cpp
  Userland/Applications/CharacterMap/CharacterMapWidget.cpp
  Userland/Applications/FileManager/main.cpp
  Userland/Applications/FontEditor/MainWidget.cpp
  Userland/Applications/Help/MainWidget.cpp
  Userland/Applications/HexEditor/HexEditorWidget.cpp
  Userland/Applications/ImageViewer/main.cpp
  Userland/Applications/KeyboardMapper/main.cpp
  Userland/Applications/Magnifier/main.cpp
  Userland/Applications/Mail/main.cpp
  Userland/Applications/Maps/main.cpp
  Userland/Applications/PDFViewer/PDFViewerWidget.cpp
  Userland/Applications/PartitionEditor/main.cpp
  Userland/Applications/Piano/main.cpp
  Userland/Applications/PixelPaint/MainWidget.cpp
  Userland/Applications/Presenter/PresenterWidget.cpp
  Userland/Applications/Settings/main.cpp
  Userland/Applications/SoundPlayer/main.cpp
  Userland/Applications/SpaceAnalyzer/main.cpp
  Userland/Applications/Spreadsheet/SpreadsheetWidget.cpp
  Userland/Applications/SystemMonitor/main.cpp
  Userland/Applications/Terminal/main.cpp
  Userland/Applications/TextEditor/MainWidget.cpp
  Userland/Applications/ThemeEditor/MainWidget.cpp
  Userland/Applications/VideoPlayer/VideoPlayerWidget.cpp
  Userland/Demos/CatDog/main.cpp
  Userland/Demos/Eyes/main.cpp
  Userland/Demos/Mandelbrot/Mandelbrot.cpp
  Userland/Demos/Screensaver/main.cpp
  Userland/DevTools/GMLPlayground/MainWidget.cpp
  Userland/DevTools/HackStudio/HackStudioWidget.cpp
  Userland/DevTools/Profiler/main.cpp
  Userland/DevTools/SQLStudio/MainWidget.cpp
  Userland/Games/2048/main.cpp
  Userland/Games/BrickGame/main.cpp
  Userland/Games/Chess/main.cpp
  Userland/Games/ColorLines/main.cpp
  Userland/Games/FlappyBug/main.cpp
  Userland/Games/Flood/main.cpp
  Userland/Games/GameOfLife/main.cpp
  Userland/Games/Hearts/main.cpp
  Userland/Games/MasterWord/main.cpp
  Userland/Games/Minesweeper/main.cpp
  Userland/Games/Snake/main.cpp
  Userland/Games/Solitaire/main.cpp
  Userland/Games/Spider/main.cpp
  Userland/Libraries/LibGUI/AboutDialog.cpp
  Userland/Libraries/LibGUI/AboutDialog.h
  Userland/Libraries/LibGUI/Action.h
  Userland/Libraries/LibGUI/CommonActions.cpp
Labels: 👀 pr-needs-review

#21082 GameOfLife: Use the same play/pause action in the menu and toolbar
  Userland/Games/GameOfLife/main.cpp
Labels: 👀 pr-needs-review

#21050 less: Add `-N` option to show line numbers
  Base/usr/share/man/man1/less.md
  Userland/Utilities/less.cpp
Labels: 👀 pr-needs-review

#21061 3DFileViewer: Remove DeprecatedString usage in object loader
  Userland/Applications/3DFileViewer/WavefrontOBJLoader.cpp
Labels: 👀 pr-needs-review

#20316 FileOperation: Set umask to 0 when creating new files or directories
  Userland/Services/FileOperation/main.cpp
Labels: 👀 pr-needs-review

#21104 LibJS: Unescape incorrectly escaped code units in regex patterns
  Userland/Libraries/LibJS/Runtime/RegExpObject.cpp
  Userland/Libraries/LibJS/Tests/builtins/RegExp/RegExp.js
Labels: 👀 pr-needs-review

#21105 LibWeb: Don't break for atomic inline elements in `white-space: nowrap`
  Tests/LibWeb/Layout/expected/block-and-inline/atomic-inline-with-white-space-nowrap.txt
  Tests/LibWeb/Layout/input/block-and-inline/atomic-inline-with-white-space-nowrap.html
  Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Labels: 👀 pr-needs-review

#21115 Meta: Update LibJSGCVerifier to build with llvm 16.0.6
  Meta/Lagom/Tools/LibJSGCVerifier/src/CellsHandler.cpp
Labels: 👀 pr-needs-review

#21126 LibWeb: Add initial CanvasPath arcTo support
  Userland/Libraries/LibGfx/Path.cpp
  Userland/Libraries/LibGfx/Path.h
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasPath.cpp
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasPath.h
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasPath.idl
Labels: 👀 pr-needs-review

#21128 LibWeb: Create `WebContentConsoleClient` for every new document
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/Page/Page.h
  Userland/Services/WebContent/ConnectionFromClient.cpp
  Userland/Services/WebContent/ConnectionFromClient.h
  Userland/Services/WebContent/PageHost.cpp
  Userland/Services/WebContent/PageHost.h
  Userland/Services/WebContent/WebContentConsoleClient.h
Labels: 👀 pr-needs-review

#21116 LibWeb: Port Node interface from DeprecatedString to String
  Userland/Libraries/LibWeb/DOM/Attr.h
  Userland/Libraries/LibWeb/DOM/CDATASection.h
  Userland/Libraries/LibWeb/DOM/Comment.h
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/DOM/DocumentFragment.h
  Userland/Libraries/LibWeb/DOM/DocumentType.h
  Userland/Libraries/LibWeb/DOM/Element.h
  Userland/Libraries/LibWeb/DOM/Node.cpp
  Userland/Libraries/LibWeb/DOM/Node.h
  Userland/Libraries/LibWeb/DOM/Node.idl
  Userland/Libraries/LibWeb/DOM/ProcessingInstruction.h
  Userland/Libraries/LibWeb/DOM/ShadowRoot.h
  Userland/Libraries/LibWeb/DOM/StyleElementUtils.cpp
  Userland/Libraries/LibWeb/DOM/Text.h
  Userland/Libraries/LibWeb/Dump.cpp
  Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
  Userland/Libraries/LibWeb/XML/XMLDocumentBuilder.cpp
  Userland/Services/WebContent/WebDriverConnection.cpp
Labels: 👀 pr-needs-review

#21130 LibJS: Use OrderedHashMap for the Shape property table
  Userland/Libraries/LibJS/MarkupGenerator.cpp
  Userland/Libraries/LibJS/Runtime/Object.cpp
  Userland/Libraries/LibJS/Runtime/Shape.cpp
  Userland/Libraries/LibJS/Runtime/Shape.h
  Userland/Libraries/LibJS/Runtime/StringObject.cpp
  Userland/Libraries/LibJS/Runtime/TypedArray.h
  Userland/Libraries/LibWeb/Bindings/LegacyPlatformObject.cpp
Labels: 👀 pr-needs-review

#21031 Toolchain: Remove dependency on `gnu-sed` for Clang on Darwin
  Toolchain/BuildClang.sh
Labels: 👀 pr-needs-review

#21016 find: Add the `-maxdepth` and `-mindepth` options
  Base/usr/share/man/man1/find.md
  Userland/Utilities/find.cpp
Labels: 👀 pr-needs-review

#21034 LibELF: Use the first `PT_LOAD` element to calculate base address
  Userland/Libraries/LibELF/DynamicObject.cpp
Labels: 👀 pr-needs-review

#21036 Toolchain+Ports: Update QEMU to 8.1.0
  .github/workflows/cmake.yml
  Ports/AvailablePorts.md
  Ports/qemu/version.sh
  Toolchain/BuildQemu.sh
  Toolchain/Patches/qemu/raspberry-pi-command-line.patch
Labels: 👀 pr-needs-review

#21004 find: Add `-gid` and `-uid` options to filter files by group and user ID
  Base/usr/share/man/man1/find.md
  Userland/Utilities/find.cpp
Labels: 👀 pr-needs-review

#21027 LibJS+LibWeb: Track SharedArrayBuffers' shared state
  Userland/Libraries/LibJS/Runtime/ArrayBuffer.cpp
  Userland/Libraries/LibJS/Runtime/ArrayBuffer.h
  Userland/Libraries/LibJS/Runtime/ArrayBufferPrototype.cpp
  Userland/Libraries/LibJS/Runtime/ErrorTypes.h
  Userland/Libraries/LibJS/Runtime/SharedArrayBufferPrototype.cpp
  Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
Labels: 👀 pr-needs-review

#20607 Ports/julius: Add a launcher entry and setup instructions
  Ports/julius/package.sh
Labels: 👀 pr-needs-review

#21099 PackageManager: Fix runtime errors
  Userland/Utilities/pkg/AvailablePort.cpp
  Userland/Utilities/pkg/main.cpp
Labels: 👀 pr-needs-review

#21102 Userland: Make `GUI::Window` construction non-fallible
  Base/res/devel/templates/serenity-application/main.cpp
  Userland/Applets/Audio/main.cpp
  Userland/Applets/ClipboardHistory/main.cpp
  Userland/Applets/Network/main.cpp
  Userland/Applications/AnalogClock/main.cpp
  Userland/Applications/Calculator/main.cpp
  Userland/Applications/Calendar/main.cpp
  Userland/Applications/CharacterMap/main.cpp
  Userland/Applications/CrashReporter/main.cpp
  Userland/Applications/FileManager/FileUtils.cpp
  Userland/Applications/FileManager/main.cpp
  Userland/Applications/FontEditor/MainWidget.cpp
  Userland/Applications/FontEditor/main.cpp
  Userland/Applications/Help/main.cpp
  Userland/Applications/HexEditor/main.cpp
  Userland/Applications/ImageViewer/main.cpp
  Userland/Applications/Maps/main.cpp
  Userland/Applications/PDFViewer/main.cpp
  Userland/Applications/PartitionEditor/main.cpp
  Userland/Applications/Piano/main.cpp
  Userland/Applications/Presenter/main.cpp
  Userland/Applications/Settings/main.cpp
  Userland/Applications/SoundPlayer/main.cpp
  Userland/Applications/SpaceAnalyzer/main.cpp
  Userland/Applications/SystemMonitor/main.cpp
  Userland/Applications/Terminal/main.cpp
  Userland/Applications/TextEditor/main.cpp
  Userland/Applications/VideoPlayer/main.cpp
  Userland/Applications/Welcome/main.cpp
  Userland/Demos/CatDog/main.cpp
  Userland/Demos/Eyes/main.cpp
  Userland/Demos/LibGfxDemo/main.cpp
  Userland/Demos/LibGfxScaleDemo/main.cpp
  Userland/Demos/Mandelbrot/Mandelbrot.cpp
  Userland/Demos/ModelGallery/main.cpp
  Userland/Demos/Screensaver/main.cpp
  Userland/Demos/WidgetGallery/main.cpp
  Userland/DevTools/GMLPlayground/MainWidget.cpp
  Userland/DevTools/GMLPlayground/main.cpp
  Userland/DevTools/Profiler/main.cpp
  Userland/DevTools/SQLStudio/main.cpp
  Userland/Games/2048/main.cpp
  Userland/Games/BrickGame/main.cpp
  Userland/Games/Chess/main.cpp
  Userland/Games/ColorLines/main.cpp
  Userland/Games/FlappyBug/main.cpp
  Userland/Games/Flood/main.cpp
  Userland/Games/GameOfLife/main.cpp
  Userland/Games/Hearts/main.cpp
  Userland/Games/MasterWord/main.cpp
  Userland/Games/Minesweeper/main.cpp
  Userland/Games/Snake/main.cpp
  Userland/Games/Solitaire/main.cpp
  Userland/Games/Spider/main.cpp
  Userland/Libraries/LibDesktop/Screensaver.cpp
Labels: 👀 pr-needs-review

#21111 GameOfLife: Add a tick counter to the status bar
  Userland/Games/GameOfLife/BoardWidget.cpp
  Userland/Games/GameOfLife/BoardWidget.h
  Userland/Games/GameOfLife/GameOfLife.gml
  Userland/Games/GameOfLife/main.cpp
Labels: 👀 pr-needs-review

#21121 less: Allow quitting with uppercase 'Q'
  Userland/Utilities/less.cpp
Labels: 👀 pr-needs-review

#21070 AK: Fix MemoryStream seek from end
  AK/MemoryStream.cpp
  Tests/AK/TestMemoryStream.cpp
Labels: 👀 pr-needs-review

#21109 Ladybird/Appkit: Remember last window position and size
  Ladybird/AppKit/UI/Tab.mm
Labels: 👀 pr-needs-review

#21140 LibWeb: Handle custom ident values for the CSS font-family property
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Labels: 👀 pr-needs-review

#21141 LibJS: Get initial_value from local variables if id represents a local
  Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
  Userland/Libraries/LibJS/Tests/functions/function-default-parameters.js
Labels: 👀 pr-needs-review

#21076 LibWeb: Use more CSSPixelFractions in GFC::expand_flexible_tracks
  Tests/LibWeb/Layout/expected/grid/placement-1.txt
  Tests/LibWeb/Layout/expected/grid/placement-2.txt
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#21032 LibWeb: Add basic Navigator send beacon support
  Meta/gn/secondary/Userland/Libraries/LibWeb/HTML/BUILD.gn
  Tests/LibWeb/Text/expected/HTML/navigator-beacon.txt
  Tests/LibWeb/Text/input/HTML/navigator-beacon.html
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/HTML/Navigator.h
  Userland/Libraries/LibWeb/HTML/Navigator.idl
  Userland/Libraries/LibWeb/HTML/NavigatorBeacon.cpp
  Userland/Libraries/LibWeb/HTML/NavigatorBeacon.h
  Userland/Libraries/LibWeb/HTML/NavigatorBeacon.idl
Labels: 👀 pr-needs-review

#21136 Meta: Port recent build changes to gn build
  Meta/gn/secondary/Userland/Libraries/LibCrypto/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibUnicode/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWeb/CSS/StyleValues/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWeb/DOM/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWeb/FileAPI/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWeb/HTML/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWeb/idl_files.gni
  Meta/gn/secondary/Userland/Libraries/LibWebView/BUILD.gn
Labels: 👀 pr-needs-review

#21110 Ladybird: Add tooltips for buttons in AppKit version
  Ladybird/AppKit/UI/TabController.mm
Labels: 👀 pr-needs-review

#21077 Maps: Add context menu to the map widget
  Userland/Applications/Maps/MapWidget.cpp
  Userland/Applications/Maps/MapWidget.h
Labels: 👀 pr-needs-review

#21060 GameOfLife: Replace DeprecatedString with String
  Userland/Games/GameOfLife/BoardWidget.cpp
  Userland/Games/GameOfLife/Pattern.cpp
  Userland/Games/GameOfLife/Pattern.h
Labels: 👀 pr-needs-review

#21133 Documentation: Hide `Meta/serenity.sh rebuild-toolchain`
  Documentation/BuildInstructions.md
  Documentation/NvimConfiguration.md
  Documentation/RunningOnRaspberryPi.md
  Documentation/Troubleshooting.md
Labels: 👀 pr-needs-review

#21013 Maps: Add Maps Settings with multiple tile providers options
  Base/home/anon/.config/MapsTileProviders.json
  Base/res/apps/MapsSettings.af
  Userland/Applications/CMakeLists.txt
  Userland/Applications/Maps/MapWidget.cpp
  Userland/Applications/Maps/MapWidget.h
  Userland/Applications/Maps/UsersMapWidget.cpp
  Userland/Applications/Maps/UsersMapWidget.h
  Userland/Applications/Maps/main.cpp
  Userland/Applications/MapsSettings/CMakeLists.txt
  Userland/Applications/MapsSettings/Defaults.h
  Userland/Applications/MapsSettings/MapsSettingsWidget.cpp
  Userland/Applications/MapsSettings/MapsSettingsWidget.gml
  Userland/Applications/MapsSettings/MapsSettingsWidget.h
  Userland/Applications/MapsSettings/main.cpp
Labels: 👀 pr-needs-review

#21149 LibJS: Run reusable steps of FunctionDeclarationInstantiation only once
  Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
  Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h
Labels: 👀 pr-needs-review

#21153 LibWeb/URL: Use the correct spec URL comment for `URL::port()`
  Userland/Libraries/LibWeb/URL/URL.cpp
Labels: 👀 pr-needs-review

#21158 Meta: Lint .mm files with lint-clang-format.sh
  Ladybird/AppKit/UI/TabController.mm
  Meta/lint-clang-format.sh
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#21160 AK: Number the spec step comments in `URL::serialize_path()`
  AK/URL.cpp
Labels: ✅ pr-community-approved

#21124 Ladybird/AppKit: Add mouse wheel events
  Ladybird/AppKit/UI/LadybirdWebView.mm
  Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
  Ladybird/AppKit/UI/LadybirdWebViewBridge.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#21075 LibWeb: Fix infinite loop in GFC growth limit distribution
  Tests/LibWeb/Layout/expected/grid/should-not-hang-in-size-distribution.txt
  Tests/LibWeb/Layout/input/grid/should-not-hang-in-size-distribution.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#21162 LibWeb: Stop adding extra whitespace when serializing CSS Functions
  Tests/LibWeb/Text/expected/css/attr-serialization.txt
  Tests/LibWeb/Text/input/css/attr-serialization.html
  Userland/Libraries/LibWeb/CSS/Parser/Function.cpp
Labels: 👀 pr-needs-review

#21131 SystemServer: Use correct unix device numbers for null, full and random
  Userland/Services/SystemServer/main.cpp
Labels: 👀 pr-needs-review

#21186 Meta: Add myself to CODEOWNERS
  .github/CODEOWNERS
Labels: 👀 pr-needs-review

#21190 LibWeb: Boxes that establish FFC or GFC should avoid overlapping floats
  Tests/LibWeb/Layout/expected/block-and-inline/flex-container-should-avoid-overlapping-floats.txt
  Tests/LibWeb/Layout/expected/block-and-inline/grid-container-should-avoid-overlapping-floats.txt
  Tests/LibWeb/Layout/input/block-and-inline/flex-container-should-avoid-overlapping-floats.html
  Tests/LibWeb/Layout/input/block-and-inline/grid-container-should-avoid-overlapping-floats.html
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
Labels: 👀 pr-needs-review

#21071 AK: Use outline Function storage if alignment requirements are not met
  AK/Function.h
Labels: 👀 pr-needs-review

#21208 ls: Add the `-S` option to sort files by size
  Base/usr/share/man/man1/ls.md
  Userland/Utilities/ls.cpp
Labels: 👀 pr-needs-review

#21170 Ports: Add libenet
  Ports/AvailablePorts.md
  Ports/libenet/package.sh
  Ports/libenet/patches/0001-Make-library-shared.patch
  Ports/libenet/patches/0002-Add-missing-install-options.patch
  Ports/libenet/patches/0003-Fix-cmake-deprecation-warning.patch
  Ports/libenet/patches/ReadMe.md
Labels: 👀 pr-needs-review

#21219 AK: Implement reverse iterators for `OrderedHashTable`
  AK/HashTable.h
  Tests/AK/TestHashTable.cpp
Labels: 👀 pr-needs-review

#21195 AK: Replace unsafe Span::offset_pointer usage in OpenType code
  Userland/Libraries/LibGfx/Font/OpenType/Cmap.cpp
  Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
  Userland/Libraries/LibGfx/Font/OpenType/Glyf.cpp
Labels: 👀 pr-needs-review

#21194 Kernel/VirtIO: Ensure proper error propagation in core methods
  Kernel/Bus/VirtIO/Console.cpp
  Kernel/Bus/VirtIO/Console.h
  Kernel/Bus/VirtIO/Device.cpp
  Kernel/Bus/VirtIO/Device.h
  Kernel/Bus/VirtIO/RNG.cpp
  Kernel/Bus/VirtIO/RNG.h
  Kernel/Bus/VirtIO/Transport/Entity.cpp
  Kernel/Bus/VirtIO/Transport/Entity.h
  Kernel/Devices/GPU/VirtIO/GraphicsAdapter.cpp
  Kernel/Devices/GPU/VirtIO/GraphicsAdapter.h
  Kernel/Net/VirtIO/VirtIONetworkAdapter.cpp
  Kernel/Net/VirtIO/VirtIONetworkAdapter.h
Labels: 👀 pr-needs-review

#21178 Userland: Remember window state of productivity / editor applications
  Userland/Applications/Browser/BrowserWindow.cpp
  Userland/Applications/Calendar/main.cpp
  Userland/Applications/FontEditor/main.cpp
  Userland/Applications/HexEditor/main.cpp
  Userland/Applications/KeyboardMapper/main.cpp
  Userland/Applications/Mail/main.cpp
  Userland/Applications/Piano/main.cpp
  Userland/Applications/PixelPaint/main.cpp
  Userland/Applications/Presenter/main.cpp
  Userland/Applications/Spreadsheet/main.cpp
  Userland/Applications/SystemMonitor/main.cpp
  Userland/Applications/TextEditor/main.cpp
  Userland/Applications/ThemeEditor/main.cpp
  Userland/DevTools/GMLPlayground/main.cpp
  Userland/DevTools/HackStudio/main.cpp
  Userland/DevTools/Profiler/main.cpp
  Userland/DevTools/SQLStudio/main.cpp
Labels: 👀 pr-needs-review

#21217 LibWeb: Fix memory leak in CSS::ImageStyleValue
  Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp
  Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.h
  Userland/Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#21224 LibWeb: Fix document leak in SVGDecodedImageData
  Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
Labels: 👀 pr-needs-review

#21074 Base+Maps: Add manpage for Maps
  Base/usr/share/man/man1/Applications.md
  Base/usr/share/man/man1/Applications/Maps.md
  Userland/Applications/Maps/main.cpp
Labels: ✅ pr-community-approved

#21226 LibJS: Avoid creating empty environment for `catch` without parameter
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Labels: 👀 pr-needs-review

#21218 LibWasm: Make sure to place imported functions before the module's
  Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp
  Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.h
Labels: 👀 pr-needs-review

#21232 ls: Add the `-p` option to append a trailing slash to directories
  Base/usr/share/man/man1/ls.md
  Userland/Utilities/ls.cpp
Labels: 👀 pr-needs-review

#21231 LibCrypto: Add Chacha20Poly1305
  Tests/LibCrypto/CMakeLists.txt
  Tests/LibCrypto/TestChacha20Poly1305.cpp
  Userland/Libraries/LibCrypto/AEAD/ChaCha20Poly1305.cpp
  Userland/Libraries/LibCrypto/AEAD/ChaCha20Poly1305.h
  Userland/Libraries/LibCrypto/CMakeLists.txt
  Userland/Libraries/LibCrypto/Cipher/ChaCha20.h
Labels: 👀 pr-needs-review

#21237 du: Prevent multiple counting of the same file
  Userland/Utilities/du.cpp
Labels: 👀 pr-needs-review

#21006 LibELF: Calculate size of relocation table correctly in all cases
  Userland/Libraries/LibELF/DynamicObject.cpp
Labels: 👀 pr-needs-review
