Repository SerenityOS/serenity, pull requests merged in 2023-03, with the labels that each got.

#17677 PixelPaint: Do not change layers when scaling with the move tool
  Userland/Applications/PixelPaint/ImageEditor.cpp
  Userland/Applications/PixelPaint/Tools/MoveTool.h
Labels: 👀 pr-needs-review

#17676 SoundPlayer: Add action with icon for toggling mute
  Userland/Applications/SoundPlayer/SoundPlayerWidgetAdvancedView.cpp
  Userland/Applications/SoundPlayer/SoundPlayerWidgetAdvancedView.h
Labels: ✅ pr-community-approved

#17675 LibWeb: Bail FrameLoader's load callbacks if associated BC is discarded (The Great Upstream 11/n)
  Userland/Libraries/LibWeb/Loader/FrameLoader.cpp
Labels: 👀 pr-needs-review

#17670 LibGUI: Give SeparatorWidget a minimum size
  Userland/Libraries/LibGUI/SeparatorWidget.cpp
  Userland/Libraries/LibGUI/SeparatorWidget.h
Labels: 👀 pr-needs-review

#17678 Toolchain: Don't abuse crt{begin,end}.o for shared or PIE binaries
  Toolchain/Patches/gcc/0001-Add-a-gcc-driver-for-SerenityOS.patch
  Toolchain/Patches/gcc/0003-libgcc-Build-for-SerenityOS.patch
Labels: 👀 pr-needs-review

#17688 LibWeb: Store all members of WebIDL::ExceptionOr<T> in a single Variant
  Userland/Libraries/LibWeb/WebIDL/ExceptionOr.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17691 AK: Make FixedPoint(FloatingPoint) ctor round instead of truncating
  AK/FixedPoint.h
  Tests/AK/TestFixedPoint.cpp
  Tests/LibEDID/TestEDID.cpp
Labels: 👀 pr-needs-review

#17692 AK: Issue error when using ARCH(arch) with nonexistent arch
  AK/Platform.h
  AK/SIMDMath.h
  Userland/Utilities/readelf.cpp
Labels: 👀 pr-needs-review, ✅ pr-community-approved

#17705 LibGUI: Compute syntax-highlighted visual text spans using float rects
  Userland/Libraries/LibGUI/TextEditor.cpp
Labels: 👀 pr-needs-review

#17673 LibWeb: Make Window.screen a replaceable attribute (The Great Upstream 10/n)
  Userland/Libraries/LibWeb/HTML/Window.cpp
  Userland/Libraries/LibWeb/HTML/Window.h
Labels: 👀 pr-needs-review

#17706 Base: Add more emoji
  Base/res/emoji/U+1F3FB.png
  Base/res/emoji/U+1F3FC.png
  Base/res/emoji/U+1F3FD.png
  Base/res/emoji/U+1F3FE.png
  Base/res/emoji/U+1F3FF.png
Labels: 👀 pr-needs-review

#17708 Base: Add 6 new emojis
  Base/res/emoji/U+1F479.png
  Base/res/emoji/U+1F47A.png
  Base/res/emoji/U+1F91B.png
  Base/res/emoji/U+1F91C.png
  Base/res/emoji/U+1F9B6.png
  Base/res/emoji/U+1FAA9.png
Labels: 👀 pr-needs-review

#17712 AK: Add StackInfo implementation for Windows
  AK/StackInfo.cpp
Labels: 👀 pr-needs-review

#17711 Base+Meta: Remove invalid symlinks from Base for more and env
  Base/bin/more
  Base/usr/bin/env
  Meta/build-root-filesystem.sh
Labels: 👀 pr-needs-review

#17710 Base: Add 14 new emojis
  Base/res/emoji/U+1F3C8.png
  Base/res/emoji/U+1F3C9.png
  Base/res/emoji/U+1F596.png
  Base/res/emoji/U+1F5FF.png
  Base/res/emoji/U+1F91E.png
  Base/res/emoji/U+1F91F.png
  Base/res/emoji/U+1F9B5.png
  Base/res/emoji/U+1F9FA.png
  Base/res/emoji/U+1FAE6.png
  Base/res/emoji/U+1FAF0.png
  Base/res/emoji/U+1FAF5.png
  Base/res/emoji/U+261D.png
  Base/res/emoji/U+26BD.png
Labels: 👀 pr-needs-review

#17687 Kernel+Userland: Add support for using the PCSpeaker with various tones
  Base/usr/share/man/man1/beep.md
  Kernel/Process.h
  Kernel/Syscalls/beep.cpp
  Userland/Libraries/LibC/unistd.cpp
  Userland/Libraries/LibC/unistd.h
  Userland/Libraries/LibCore/System.cpp
  Userland/Libraries/LibCore/System.h
  Userland/Libraries/LibVT/TerminalWidget.cpp
  Userland/Utilities/beep.cpp
Labels: 👀 pr-needs-review

#17721 AK+LibAudio: Remove UFixedBigInt::my_size
  AK/FloatingPointStringConversions.cpp
  AK/UFixedBigInt.h
  Userland/Libraries/LibAudio/FlacLoader.cpp
Labels: 👀 pr-needs-review

#17716 Kernel: Actually check Process unveil data when creating perfcore dump
  Kernel/FileSystem/VirtualFileSystem.cpp
  Kernel/FileSystem/VirtualFileSystem.h
  Kernel/Process.cpp
Labels: 👀 pr-needs-review

#17724 LibUnicode: Use binary search for lookups into the generated emoji data
  Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateEmojiData.cpp
Labels: 👀 pr-needs-review

#17685 Kernel: Move process coredump metadata modification to the prctl syscall
  Kernel/API/Syscall.h
  Kernel/API/prctl_numbers.h
  Kernel/Process.h
  Kernel/Syscalls/prctl.cpp
  Kernel/Syscalls/process.cpp
  Userland/DevTools/UserspaceEmulator/Emulator.h
  Userland/DevTools/UserspaceEmulator/Emulator_syscalls.cpp
  Userland/Libraries/LibC/assert.cpp
Labels: 👀 pr-needs-review

#17725 LibGfx: Fill in remaining values in built-in sRGB profile
  Userland/Libraries/LibGfx/ICC/WellKnownProfiles.cpp
Labels: 👀 pr-needs-review

#17732 LibWeb: Fix currentColor as a background-color (and maybe other places)
  Userland/Libraries/LibWeb/Layout/Node.cpp
Labels: 👀 pr-needs-review

#17734 LibWeb: Share WindowOrWorkerGlobalScope code
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
  Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.h
  Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.cpp
  Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.h
Labels: 👀 pr-needs-review

#17735 Base: Improve a few ball emojis
  Base/res/emoji/U+1F3B1.png
  Base/res/emoji/U+1F3C0.png
  Base/res/emoji/U+1F3D0.png
  Base/res/emoji/U+1F94E.png
  Base/res/emoji/U+26BE.png
Labels: 👀 pr-needs-review

#17731 LibCore: Don't use DT_WHT in DirectoryEntry on OpenBSD
  Userland/Libraries/LibCore/DirectoryEntry.cpp
Labels: 👀 pr-needs-review

#17703 VideoPlayer: Create submenu to set sizing mode
  Userland/Applications/VideoPlayer/VideoFrameWidget.cpp
  Userland/Applications/VideoPlayer/VideoFrameWidget.h
  Userland/Applications/VideoPlayer/VideoPlayerWidget.cpp
  Userland/Applications/VideoPlayer/VideoPlayerWidget.h
  Userland/Applications/VideoPlayer/VideoPlayerWindow.gml
Labels: 👀 pr-needs-review

#17736 less: Stop adding extra blank lines
  Userland/Utilities/less.cpp
Labels: 👀 pr-needs-review, ✅ pr-community-approved

#17740 man: Skip shellrc when invoking pager using sh
  Userland/Utilities/man.cpp
Labels: 👀 pr-needs-review

#17726 Help: Don't defer tree view selection updates
  Userland/Applications/Help/MainWidget.cpp
Labels: 👀 pr-needs-review

#17751 LibWeb/Fetch: Actually check if the response is null in recursive fetch
  Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
Labels: 👀 pr-needs-review

#17753 LibWeb: Make WindowOrWorkerGlobalScope#atob use forgiving base64 decode
  Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
Labels: 👀 pr-needs-review

#17754 Kernel/VirtIO: Ignore Configurations that have length of zero bytes
  Kernel/Bus/VirtIO/Device.cpp
Labels: 👀 pr-needs-review

#17764 LibWeb: Do not discard String returned from url_encode() to avoid UAF
  Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
Labels: 👀 pr-needs-review

#17773 HackStudio: Store correct address in ClassViewModel's ModelIndices
  Userland/DevTools/HackStudio/ClassViewWidget.cpp
Labels: 👀 pr-needs-review

#17776 Ladybird: Send window size and position to WebContent process
  Ladybird/BrowserWindow.cpp
  Ladybird/BrowserWindow.h
  Ladybird/WebContentView.cpp
  Ladybird/WebContentView.h
Labels: 👀 pr-needs-review

#17777 LibGUI: FilePicker imporvements
  Userland/Libraries/LibGUI/FilePicker.cpp
Labels: 👀 pr-needs-review

#17767 Ports: Add hexedit port
  Ports/AvailablePorts.md
  Ports/hexedit/package.sh
Labels: 👀 pr-needs-review

#17771 PixelPaint: Add recently opened files to file menu (+ error propagation)
  Userland/Applications/PixelPaint/MainWidget.cpp
  Userland/Applications/PixelPaint/main.cpp
Labels: ✅ pr-community-approved

#17762 Applets/Keymap: Repaint applet on keymap change
  Userland/Applets/Keymap/KeymapStatusWidget.cpp
Labels: 👀 pr-needs-review

#17745 AK: Replace C-style casts
  AK/Bitmap.h
  AK/BitmapView.h
  AK/BumpAllocator.h
  AK/ByteBuffer.h
  AK/DeprecatedString.h
  AK/NonnullOwnPtr.h
  AK/StdLibExtras.h
  AK/StringHash.h
  AK/StringView.h
  AK/Traits.h
  AK/Types.h
  AK/UnicodeUtils.h
  AK/Userspace.h
  AK/Utf8View.h
Labels: 👀 pr-needs-review

#17475 Base: Replace office.png icon with BSD licensed one
  Base/res/icons/16x16/office.png
Labels: 👀 pr-needs-review

#17795 LibWeb: Fix row-height bug in Grid when there is a column gap
  Base/res/html/misc/display-grid.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#17756 Shell: Error out on invalid `export' argument
  Userland/Shell/Builtin.cpp
Labels: 👀 pr-needs-review

#17797 Ladybird+CI: Move layout_test.sh test runner from CI yml into CMake
  Ladybird/CMakeLists.txt
  Meta/Azure/Lagom.yml
Labels: 👀 pr-needs-review

#17803 Ladybird: Delete unused ConsoleClient and ConsoleGlobalObject
  Ladybird/ConsoleClient.cpp
  Ladybird/ConsoleClient.h
  Ladybird/ConsoleGlobalObject.cpp
  Ladybird/ConsoleGlobalObject.h
Labels: 👀 pr-needs-review

#17799 LibWeb: Don't overflow flex containers on margin auto
  Tests/LibWeb/Layout/expected/flex-margin-auto-justify-content.txt
  Tests/LibWeb/Layout/input/flex-margin-auto-justify-content.html
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Labels: 👀 pr-needs-review

#17796 CI: Remove stale dependence on Toolchain.yml from nightly job
  Meta/Azure/nightly-pipeline.yml
Labels: 👀 pr-needs-review

#17791 Kernel: Fix variable shadowing issue in PCIIDELegacyModeController
  Kernel/Arch/x86_64/PCI/IDELegacyModeController.cpp
Labels: 👀 pr-needs-review

#17790 Kernel: Add `_SC_PHYS_PAGES` to sys$sysconf
  Kernel/API/POSIX/unistd.h
  Kernel/Syscalls/sysconf.cpp
Labels: 👀 pr-needs-review

#17804 WebDriver: Fix crash in async execute script endpoint
  Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
Labels: 👀 pr-needs-review

#17809 LibWeb: Establish a stacking context for root element
  Userland/Libraries/LibWeb/Layout/Node.cpp
Labels: 👀 pr-needs-review

#17780 LibGfx: Speed up fill_path() with per scanline clipping & fast fills
  Userland/Libraries/LibGfx/AntiAliasingPainter.cpp
  Userland/Libraries/LibGfx/CMakeLists.txt
  Userland/Libraries/LibGfx/FillPathImplementation.cpp
  Userland/Libraries/LibGfx/Painter.cpp
  Userland/Libraries/LibGfx/Painter.h
Labels: 👀 pr-needs-review

#17812 LibGfx: Fix segfault and painting off-by-one in fill_path()
  Userland/Libraries/LibGfx/FillPathImplementation.cpp
Labels: 👀 pr-needs-review

#17818 Meta+CMake: Remove "image" ninja target in favor of "qemu-image"
  .github/workflows/cmake.yml
  CMakeLists.txt
  Documentation/RunningTests.md
  Meta/Azure/Serenity.yml
  Meta/serenity.sh
Labels: 👀 pr-needs-review

#17817 Userland: Add an `image` utility
  Meta/Lagom/CMakeLists.txt
  Userland/Utilities/CMakeLists.txt
  Userland/Utilities/image.cpp
Labels: 👀 pr-needs-review

#17819 LibGfx: Use StringView literals for CSS color list
  Userland/Libraries/LibGfx/Color.cpp
Labels: 👀 pr-needs-review

#17821 LibGfx: Make QOIWriter use ErrorOr
  Tests/LibGL/TestRender.cpp
  Userland/Applications/PixelPaint/Image.cpp
  Userland/Demos/Mandelbrot/Mandelbrot.cpp
  Userland/Libraries/LibGfx/QOIWriter.cpp
  Userland/Libraries/LibGfx/QOIWriter.h
  Userland/Utilities/image.cpp
Labels: 👀 pr-needs-review

#16980 Kernel: Make the Jails' internal design a lot more sane
  Kernel/Arch/aarch64/init.cpp
  Kernel/Arch/x86_64/init.cpp
  Kernel/CMakeLists.txt
  Kernel/FileSystem/SysFS/Subsystems/Kernel/Jails.cpp
  Kernel/Jail.cpp
  Kernel/Jail.h
  Kernel/JailManagement.cpp
  Kernel/JailManagement.h
  Kernel/Process.cpp
  Kernel/Process.h
  Kernel/ProcessList.cpp
  Kernel/Syscalls/execve.cpp
  Kernel/Syscalls/fork.cpp
  Kernel/Syscalls/jail.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17829 LibGfx: Make BMPWriter::dump() return ErrorOr
  Userland/Libraries/LibGfx/BMPWriter.cpp
  Userland/Libraries/LibGfx/BMPWriter.h
Labels: 👀 pr-needs-review

#17815 PixelPaint: Display color information on mousemove with the PickerTool
  Userland/Applications/PixelPaint/ImageEditor.cpp
  Userland/Applications/PixelPaint/ImageEditor.h
  Userland/Applications/PixelPaint/Tools/PickerTool.cpp
Labels: 👀 pr-needs-review

#17820 LibC: Correctly reset the getopt state on `optind = 1`
  Userland/Libraries/LibC/getopt.cpp
  Userland/Libraries/LibC/unistd.h
Labels: 👀 pr-needs-review

#17824 Base: Add Batak to font Katica Regular 10
  Base/res/fonts/KaticaRegular10.font
Labels: 👀 pr-needs-review

#17822 SpiceAgent: Remove unused BMPWriter.h include
  Userland/Services/SpiceAgent/SpiceAgent.cpp
Labels: 👀 pr-needs-review

#17830 LibCompress: Make DeflateCompressor::write() use loop, not recursion
  Userland/Libraries/LibCompress/Deflate.cpp
Labels: 👀 pr-needs-review

#17832 LibWeb: Escape HTML text fragments with multi-byte code point awareness
  Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Labels: 👀 pr-needs-review

#17807 Ports: Add lrzip port
  Ports/AvailablePorts.md
  Ports/lrzip/package.sh
  Ports/lrzip/patches/0001-Remove-Linux-specific-code.patch
  Ports/lrzip/patches/ReadMe.md
Labels: 👀 pr-needs-review

#17811 Meta+Documentation: Fix x86-64 kernel debugging on Apple Silicon
  Documentation/BuildInstructionsMacOS.md
  Meta/debug-kernel.sh
Labels: 👀 pr-needs-review

#17839 LibAudio: Update stream APIs used when reading audio metadata
  Userland/Libraries/LibAudio/VorbisComment.cpp
Labels: 👀 pr-needs-review

#17828 Documentation: Start documenting LibWeb code style & patterns
  Documentation/Browser/Patterns.md
  Documentation/README.md
Labels: 👀 pr-needs-review

#17848 LibWeb: Consider margins of atomic inlines in layout
  Tests/LibWeb/Layout/expected/inline-box-with-vertical-margins-vertical-align-top.txt
  Tests/LibWeb/Layout/expected/inline-box-with-vertical-margins.txt
  Tests/LibWeb/Layout/expected/replaced-box-with-vertical-margins.txt
  Tests/LibWeb/Layout/input/buggie.png
  Tests/LibWeb/Layout/input/inline-box-with-vertical-margins-vertical-align-top.html
  Tests/LibWeb/Layout/input/inline-box-with-vertical-margins.html
  Tests/LibWeb/Layout/input/replaced-box-with-vertical-margins.html
  Userland/Libraries/LibWeb/Layout/LayoutState.cpp
  Userland/Libraries/LibWeb/Layout/LineBoxFragment.cpp
  Userland/Libraries/LibWeb/Layout/LineBoxFragment.h
  Userland/Libraries/LibWeb/Layout/LineBuilder.cpp
Labels: 👀 pr-needs-review

#17853 Ladybird: Rely on transparent text color for location highlighting
  Ladybird/LocationEdit.cpp
Labels: 👀 pr-needs-review

#17856 LibWeb: Prevent variadic arguments from reserving heaps of memory
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Labels: 👀 pr-needs-review

#17858 LibWeb: Invalidate styles on font load
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Labels: 👀 pr-needs-review

#17857 LibWeb: Implement the [PutForwards] IDL extended attribute
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
  Userland/Libraries/LibWeb/HTML/Window.cpp
  Userland/Libraries/LibWeb/HTML/Window.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17760 Ports: Add bzip3 port
  Ports/AvailablePorts.md
  Ports/bzip3/package.sh
Labels: 👀 pr-needs-review

#17850 AK: Rename CaseInsensitiveStringViewTraits to CaseInsensitiveASCIIStringViewTraits
  AK/StringView.h
  Meta/Lagom/Tools/CodeGenerators/LibTimeZone/GenerateTimeZoneData.cpp
  Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodeData.cpp
  Meta/Lagom/Tools/CodeGenerators/LibUnicode/GeneratorUtil.h
  Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSValueID.cpp
  Tests/AK/TestHashMap.cpp
  Tests/AK/TestStringView.cpp
Labels: 👀 pr-needs-review

#17852 LibGUI: Do not attempt to close non-existent notifications
  Userland/Libraries/LibGUI/Notification.cpp
Labels: 👀 pr-needs-review

#17794 Ports: Add taskwarrior port
  Ports/AvailablePorts.md
  Ports/taskwarrior/package.sh
Labels: 👀 pr-needs-review

#17859 Meta: Download pci.ids and usb.ids to Build/caches
  CMakeLists.txt
Labels: 👀 pr-needs-review

#17860 PartitionEditor: Add missing unveils
  Userland/Applications/PartitionEditor/main.cpp
Labels: 👀 pr-needs-review

#17728 Kernel: Merge {get,set}_process_name syscalls to the prctl syscall
  Kernel/API/Syscall.h
  Kernel/API/prctl_numbers.h
  Kernel/Process.h
  Kernel/Syscalls/prctl.cpp
  Kernel/Syscalls/process.cpp
  Userland/DevTools/UserspaceEmulator/Emulator.h
  Userland/DevTools/UserspaceEmulator/Emulator_syscalls.cpp
  Userland/Libraries/LibC/unistd.cpp
  Userland/Utilities/strace.cpp
Labels: 👀 pr-needs-review

#17873 AK: Clear OrderedHashTable previous/next pointers on removal
  AK/HashTable.h
  Tests/AK/TestHashTable.cpp
Labels: ✅ pr-community-approved

#17879 CI: Bump Android NDK version used in CI to 25.2.9519653
  Meta/Azure/Lagom.yml
Labels: 👀 pr-needs-review

#17877 LibGUI: Store correct address in TreeViewModel's ModelIndices
  Userland/Libraries/LibGUI/TreeViewModel.cpp
Labels: 👀 pr-needs-review

#17875 LibWeb: Don't drop single <br/> lines
  Tests/LibWeb/Layout/expected/single-br-inline-layout.txt
  Tests/LibWeb/Layout/input/single-br-inline-layout.html
  Userland/Libraries/LibWeb/Layout/LineBox.h
  Userland/Libraries/LibWeb/Layout/LineBuilder.cpp
Labels: 👀 pr-needs-review

#17880 image: Add --strip-color-profile, --assign-color-profile= flags
  Userland/Utilities/image.cpp
Labels: 👀 pr-needs-review

#17889 LibWeb: Fix `is<HTML::HTMLProgressElement>()` check
  Userland/Libraries/LibWeb/HTML/HTMLProgressElement.h
Labels: 👀 pr-needs-review

#17727 LibJS: Fix a bunch of unwind related errors in GenerateCFG
  Userland/Libraries/LibJS/Bytecode/Pass/GenerateCFG.cpp
Labels: 👀 pr-needs-review

#17595 Browser: Have the bookmark button use the editor dialog
  Userland/Applications/Browser/BookmarksBarWidget.cpp
  Userland/Applications/Browser/BookmarksBarWidget.h
  Userland/Applications/Browser/Tab.cpp
Labels: 👀 pr-needs-review

#17891 LibGfx/OpenType: Fix bound-check
  Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
Labels: 👀 pr-needs-review

#17895 LibWeb: Give generated constructor functions a name
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Labels: 👀 pr-needs-review

#17896 Meta: Ensure the main thread VM is created before use in the CSS fuzzer
  Meta/Lagom/Fuzzers/FuzzCSSParser.cpp
Labels: 👀 pr-needs-review

#17897 LibVT: Fix integer overflow when parsing long OSC sequences
  Userland/Libraries/LibVT/EscapeSequenceParser.h
Labels: 👀 pr-needs-review

#17874 Userland: Use standard WAV MIME type
  Base/res/apps/SoundPlayer.af
  Userland/Libraries/LibCore/MimeData.cpp
  Userland/Utilities/file.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17901 Fuzzers: Skip trying to parse invalid UTF-8 in LibJS Fuzzers
  Meta/Lagom/Fuzzers/FuzzJs.cpp
  Meta/Lagom/Fuzzers/FuzzilliJs.cpp
Labels: 👀 pr-needs-review

#17913 LibWeb: Invalidate sibling styles on input element checked state change
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Labels: 👀 pr-needs-review

#17917 LibWeb: Don't deref HTMLInputElement parent if its null
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Labels: 👀 pr-needs-review

#17898 Meta: Move global VM creation to fuzzer "global" structure
  Meta/Lagom/Fuzzers/FuzzCSSParser.cpp
Labels: 👀 pr-needs-review

#17916 LibGfx: Correct the type of Lookup.subtable_offsets
  Userland/Libraries/LibGfx/Font/OpenType/Tables.h
Labels: 👀 pr-needs-review

#17919 LibGfx/JPEG: Make JPEGImageDecoderPlugin's constructor take a Stream
  Userland/Libraries/LibGfx/JPEGLoader.cpp
  Userland/Libraries/LibGfx/JPEGLoader.h
Labels: 👀 pr-needs-review

#17834 Ladybird: Fix build failure caused by missing WebDriver header
  Ladybird/cmake/EnableLagom.cmake
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17920 LibWeb: Stub out a few form validation and selection methods
  Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLFormElement.h
  Userland/Libraries/LibWeb/HTML/HTMLFormElement.idl
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.idl
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17932 LibWeb: Add keep-alive in response if it present in request
  Userland/Libraries/LibWeb/WebDriver/Client.cpp
Labels: 👀 pr-needs-review

#17941 Base: Add 7 new emojis
  Base/res/emoji/U+1F360.png
  Base/res/emoji/U+1F362.png
  Base/res/emoji/U+1F399.png
  Base/res/emoji/U+1F3E7.png
  Base/res/emoji/U+1F485.png
  Base/res/emoji/U+1F6C1.png
  Base/res/emoji/U+26B0.png
Labels: 👀 pr-needs-review

#17943 LibJS: Update spec numbers / text for the Change Array by Copy proposal
  Userland/Libraries/LibJS/Runtime/Array.cpp
  Userland/Libraries/LibJS/Runtime/Array.h
  Userland/Libraries/LibJS/Runtime/ArrayPrototype.cpp
  Userland/Libraries/LibJS/Runtime/TypedArray.cpp
  Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
Labels: 👀 pr-needs-review

#17942 LibLine: Unify the is-empty flag in Style::unify_with() as well
  Userland/Libraries/LibLine/Editor.cpp
Labels: 👀 pr-needs-review

#17922 LibWeb: Support more length types in SVG width/height attributes
  Userland/Libraries/LibWeb/Layout/SVGSVGBox.cpp
  Userland/Libraries/LibWeb/SVG/SVGForeignObjectElement.cpp
  Userland/Libraries/LibWeb/SVG/SVGSVGElement.cpp
Labels: 👀 pr-needs-review

#17948 VideoPlayer: Add drag and drop support
  Userland/Applications/VideoPlayer/CMakeLists.txt
  Userland/Applications/VideoPlayer/VideoPlayerWidget.cpp
  Userland/Applications/VideoPlayer/VideoPlayerWidget.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17951 LibGfx/OpenType: Extend support for GPOS glyph positioning
  Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
  Userland/Libraries/LibGfx/Font/OpenType/Tables.h
Labels: 👀 pr-needs-review

#17929 Presenter: Change how full-screening works, and add a "Resize to Fit Content" action
  Userland/Applications/Presenter/PresenterWidget.cpp
  Userland/Applications/Presenter/PresenterWidget.h
Labels: 👀 pr-needs-review

#17954 Base: Add 7 new emojis
  Base/res/emoji/U+1F412.png
  Base/res/emoji/U+1F6B2.png
  Base/res/emoji/U+1F6C0.png
  Base/res/emoji/U+1F6DD.png
  Base/res/emoji/U+1F9A6.png
  Base/res/emoji/U+1F9A7.png
  Base/res/emoji/U+1FA7C.png
Labels: 👀 pr-needs-review

#17980 LibGUI: Resolve use-after-free error
  Userland/Libraries/LibGUI/FileSystemModel.cpp
Labels: 👀 pr-needs-review

#17978 LibGfx/JPEG: Replace a FIXME with some explanations
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Labels: 👀 pr-needs-review

#17981 LibFileSystemAccessClient: Don't make illegal operation on files
  Userland/Libraries/LibFileSystemAccessClient/Client.cpp
Labels: 👀 pr-needs-review

#17986 LibFileSystem: Fix leak in `real_path`
  Userland/Libraries/LibFileSystem/FileSystem.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17990 PDFViewer: Fix crash in OutlineModel
  Userland/Applications/PDFViewer/OutlineModel.cpp
Labels: 👀 pr-needs-review

#17992 Spreadsheet: Port to Core::File
  Userland/Applications/Spreadsheet/Spreadsheet.cpp
Labels: 👀 pr-needs-review

#17991 ImageViewer: Various improvements
  Userland/Applications/ImageViewer/ViewWidget.cpp
  Userland/Applications/ImageViewer/ViewWidget.h
Labels: 👀 pr-needs-review

#17997 LibWeb: Add workaround to restore cross-origin stylesheet functionality
  Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Labels: 👀 pr-needs-review

#18003 LibJS: Support the yy{/,-}mm{/,-}dd hh:mm format for Date
  Userland/Libraries/LibJS/Runtime/DateConstructor.cpp
  Userland/Libraries/LibJS/Tests/builtins/Date/Date.parse.js
Labels: 👀 pr-needs-review

#18009 WebDriver: Unlink server socket before binding to it
  Userland/Services/WebDriver/Session.cpp
Labels: 👀 pr-needs-review

#18017 ImageViewer: Fix crash when opening ImageViewer without an image
  Userland/Applications/ImageViewer/ViewWidget.cpp
Labels: 👀 pr-needs-review

#18015 LibThreading: Resolve BackgroundAction error callback use-after-free
  Userland/Libraries/LibThreading/BackgroundAction.h
Labels: ✅ pr-community-approved

#18019 ImageViewer: Use `LibFileSystemAccessClient`
  Userland/Applications/ImageViewer/CMakeLists.txt
  Userland/Applications/ImageViewer/ViewWidget.cpp
  Userland/Applications/ImageViewer/ViewWidget.h
  Userland/Applications/ImageViewer/main.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#18035 Kernel: Remove 2 duplicated listings of cpp files in CMakeLists.txt file
  Kernel/CMakeLists.txt
Labels: 👀 pr-needs-review

#18039 LibRegex: Make ^ and $ accept all `LineTerminator`s instead of just '\n'
  Tests/LibRegex/Regex.cpp
  Userland/Libraries/LibRegex/RegexByteCode.cpp
  Userland/Libraries/LibRegex/RegexOptions.h
Labels: 👀 pr-needs-review

#17709 LibGfx/JPEG: More support for scans with a single component
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/several_scans_odd_number_mcu.jpg
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Labels: 👀 pr-needs-review

#17654 PixelPaint: Make wand tool work when layer and image rects differ
  Userland/Applications/PixelPaint/Tools/WandSelectTool.cpp
Labels: 👀 pr-needs-review

#18028 PixelPaint: Add a Duplicate Layer action
  Userland/Applications/PixelPaint/Image.cpp
  Userland/Applications/PixelPaint/Image.h
  Userland/Applications/PixelPaint/ImageEditor.cpp
  Userland/Applications/PixelPaint/ImageEditor.h
  Userland/Applications/PixelPaint/Layer.cpp
  Userland/Applications/PixelPaint/Layer.h
  Userland/Applications/PixelPaint/MainWidget.cpp
Labels: 👀 pr-needs-review

#18043 PixelPaint: Remove unused function definition from Image
  Userland/Applications/PixelPaint/Image.h
Labels: 👀 pr-needs-review

#18045 LibWeb: Fix mistype in `LayoutState`
  Userland/Libraries/LibWeb/Layout/LayoutState.cpp
Labels: 👀 pr-needs-review

#18042 PixelPaint: Correctly set default layer name
  Userland/Applications/PixelPaint/CreateNewLayerDialog.cpp
  Userland/Applications/PixelPaint/CreateNewLayerDialog.h
Labels: 👀 pr-needs-review

#18048 LibWeb: Fix non return in overflow value check
  Userland/Libraries/LibWeb/Layout/Box.cpp
Labels: 👀 pr-needs-review

#18050 LibTimeZone: Update to TZDB version 2023b
  Meta/CMake/time_zone_data.cmake
Labels: 👀 pr-needs-review

#18021 LibWeb: Run XML parser input through encoding decoder
  Userland/Libraries/LibWeb/Loader/FrameLoader.cpp
Labels: 👀 pr-needs-review

#18001 Ladybird: Open target _blank links in new tab
  Ladybird/BrowserWindow.cpp
  Ladybird/WebContentView.cpp
  Ladybird/WebContentView.h
Labels: 👀 pr-needs-review

#18051 LibWeb: Don't force relayout whole page on programmatic scroll
  Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
Labels: 👀 pr-needs-review

#18055 Browser: Remove unused variables in `BookmarksBarWidget`
  Userland/Applications/Browser/BookmarksBarWidget.cpp
Labels: 👀 pr-needs-review

#18060 LibWeb: Stop returning the left padding for resolved padding-bottom
  Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
Labels: 👀 pr-needs-review

#18056 Ports: Update serenity-theming use latest commit ba2ddd0
  Ports/AvailablePorts.md
  Ports/serenity-theming/package.sh
Labels: 👀 pr-needs-review

#18061 Toolchain: Update binutils to version 2.40
  Meta/serenity.sh
  Toolchain/BuildIt.sh
Labels: 👀 pr-needs-review

#18064 LibWeb: Fix condition to early return in intrinsic sizing for TFC
  Tests/LibWeb/Layout/expected/table-in-auto-height-flex-item.txt
  Tests/LibWeb/Layout/input/table-in-auto-height-flex-item.html
  Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Labels: 👀 pr-needs-review

#18025 Meta: Remove SonarCloud cache and threads setup as it is now offered by default
  .github/workflows/sonar-cloud-static-analysis.yml
Labels: 👀 pr-needs-review

#18071 AK: Add DeprecatedString::from_utf8(StringView)
  AK/DeprecatedString.h
Labels: 👀 pr-needs-review

#18070 LibGfx: Don't render OpenType glyphs that have no outline
  Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
  Userland/Libraries/LibGfx/Font/OpenType/Glyf.cpp
Labels: 👀 pr-needs-review

#18074 Tests/LibWeb: Add layout test for layout fix in PR #15780
  Tests/LibWeb/Layout/expected/position-absolute-ignores-padding-of-position-relative-floating-parent.txt
  Tests/LibWeb/Layout/input/position-absolute-ignores-padding-of-position-relative-floating-parent.html
Labels: 👀 pr-needs-review

#18078 README: Add a jump section for easy access to documentation
  README.md
Labels: 👀 pr-needs-review

#18076 LibGfx/OpenType: Ignore glyphs with bogus offsets
  Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
  Userland/Libraries/LibGfx/Font/OpenType/Glyf.cpp
  Userland/Libraries/LibGfx/Font/OpenType/Glyf.h
Labels: 👀 pr-needs-review

#18081 LibWeb: Parse Element.style url functions relative to the document
  Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp
Labels: 👀 pr-needs-review

#18079 LibWeb+LibWasm: Implement and use the "reset the Memory buffer" steps
  Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.h
  Userland/Libraries/LibWeb/WebAssembly/Memory.cpp
  Userland/Libraries/LibWeb/WebAssembly/Memory.h
Labels: 👀 pr-needs-review
