Repository SerenityOS/serenity, pull requests merged in 2023-05, with the labels that each got.

#18598 LibGUI: Only clear `TreeView::m_view_metadata` when required
  Userland/Libraries/LibGUI/TreeView.cpp
Labels: 👀 pr-needs-review

#18604 LibWeb: Set zero underflow when calculating intrinsic width of block
  Tests/LibWeb/Layout/expected/table/columns-width-distribution-1.txt
  Tests/LibWeb/Layout/expected/table/size.txt
  Tests/LibWeb/Layout/input/table/columns-width-distribution-1.html
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Labels: 👀 pr-needs-review

#18595 LibVideo/VP9: Revert framebuffer size reduction to allow OOB blocks
  Tests/LibVideo/CMakeLists.txt
  Tests/LibVideo/TestVP9Decode.cpp
  Tests/LibVideo/vp9_oob_blocks.webm
  Userland/Libraries/LibVideo/VP9/Context.h
Labels: 👀 pr-needs-review

#18606 LibWeb: Fix intrinsic sizing when min or max width is specified
  Tests/LibWeb/Layout/expected/block-and-inline/intrinsic-sizing-with-min-width-specified.txt
  Tests/LibWeb/Layout/input/block-and-inline/intrinsic-sizing-with-min-width-specified.html
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Labels: 👀 pr-needs-review

#18599 HexEditor: Remember all of the layout options in the configuration
  Userland/Applications/HexEditor/HexEditorWidget.cpp
Labels: 👀 pr-needs-review

#18616 profile: Small improvements to the profile utility
  Userland/Utilities/profile.cpp
Labels: 👀 pr-needs-review

#18622 LibWeb: Implement more box type transformation edge cases
  Tests/LibWeb/Layout/expected/blockify-layout-internal-box-without-crashing.txt
  Tests/LibWeb/Layout/input/blockify-layout-internal-box-without-crashing.html
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Labels: 👀 pr-needs-review

#18623 LibWeb: Take floats into account when measuring automatic width of IFC
  Tests/LibWeb/Layout/expected/block-and-inline/automatic-size-of-block-container-with-inline-children-and-nonempty-floating-child.txt
  Tests/LibWeb/Layout/input/block-and-inline/automatic-size-of-block-container-with-inline-children-and-nonempty-floating-child.html
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Labels: 👀 pr-needs-review

#18625 AK: Have `JsonArray::set()` change values instead of inserting values
  AK/JsonArray.h
  Userland/Libraries/LibGUI/JsonArrayModel.cpp
Labels: 👀 pr-needs-review

#18632 LibWeb: Narrow width of boxes that create BFC to avoid overlap of float
  Tests/LibWeb/Layout/expected/block-and-inline/narrow-bfc-width-to-avoid-overlap-with-floats.txt
  Tests/LibWeb/Layout/input/block-and-inline/narrow-bfc-width-to-avoid-overlap-with-floats.html
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Labels: 👀 pr-needs-review

#18634 LibWeb: Make module maps GC-allocated
  Userland/Libraries/LibWeb/HTML/Scripting/Environments.cpp
  Userland/Libraries/LibWeb/HTML/Scripting/Environments.h
  Userland/Libraries/LibWeb/HTML/Scripting/ModuleMap.cpp
  Userland/Libraries/LibWeb/HTML/Scripting/ModuleMap.h
Labels: 👀 pr-needs-review

#18594 LibWeb: Don't divide by 0 in DOMMatrix::invert_self()
  Userland/Libraries/LibWeb/Geometry/DOMMatrix.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#18637 LibWeb: Honor fill, stroke and stroke-width attribute on SVGSVGElement
  Userland/Libraries/LibWeb/SVG/SVGSVGElement.cpp
Labels: 👀 pr-needs-review

#18628 LibWeb: Implement the EventTarget constructor
  Userland/Libraries/LibWeb/DOM/EventTarget.cpp
  Userland/Libraries/LibWeb/DOM/EventTarget.h
  Userland/Libraries/LibWeb/DOM/EventTarget.idl
Labels: 👀 pr-needs-review

#18591 Ports/ncdu: Update to version 1.18.1
  Ports/AvailablePorts.md
  Ports/ncdu/package.sh
Labels: 👀 pr-needs-review

#18643 PixelPaint: Minor gradient tool fixes
  Userland/Applications/PixelPaint/Tools/GradientTool.cpp
Labels: ✅ pr-community-approved

#17648 Piano: Allow per-track controls (again)
  Userland/Applications/Piano/MainWidget.cpp
  Userland/Applications/Piano/MainWidget.h
  Userland/Applications/Piano/PlayerWidget.cpp
  Userland/Applications/Piano/PlayerWidget.h
  Userland/Applications/Piano/RollWidget.cpp
  Userland/Applications/Piano/TrackControlsWidget.cpp
  Userland/Applications/Piano/TrackControlsWidget.h
  Userland/Applications/Piano/TrackManager.h
  Userland/Libraries/LibDSP/Track.h
Labels: 👀 pr-needs-review

#18645 LibXML: Notify the listener about the root node as well
  Userland/Libraries/LibXML/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#18644 LibWeb: Remove setting length to 0px if it is not definite
  Tests/LibWeb/Layout/expected/block-and-inline/max-width-percentage-100.txt
  Tests/LibWeb/Layout/input/block-and-inline/max-width-percentage-100.html
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Labels: 👀 pr-needs-review

#18651 LibWeb: Remove early resolve to auto while calculating border-box width
  Tests/LibWeb/Layout/expected/block-and-inline/max-width-percentage-100-border-box.txt
  Tests/LibWeb/Layout/input/block-and-inline/max-width-percentage-100-border-box.html
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Labels: 👀 pr-needs-review

#18653 LibWeb: Zero out margins if width is not 'auto' in BFC's compute_width
  Tests/LibWeb/Layout/expected/block-and-inline/width-auto-margins-set-zero-if-containing-size-smaller.txt
  Tests/LibWeb/Layout/input/block-and-inline/width-auto-margins-set-zero-if-containing-size-smaller.html
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#18647 FileSystemAccessServer: Use `ECANCELED` instead of -1
  Userland/Libraries/LibFileSystemAccessClient/Client.cpp
  Userland/Services/FileSystemAccessServer/ConnectionFromClient.cpp
Labels: 👀 pr-needs-review

#18605 LibGUI: Fix stuck and crash on deleting word forward/backword
  Userland/Libraries/LibGUI/TextDocument.cpp
Labels: 👀 pr-needs-review

#18569 LibChess+Chess: Ensure no pawns have moved when invoking 50 move rule
  Userland/Games/Chess/ChessWidget.cpp
  Userland/Libraries/LibChess/Chess.cpp
Labels: 👀 pr-needs-review

#18665 Ports: Unbreak SDL2 by using GUI::Application::create()
  Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch
Labels: 👀 pr-needs-review

#18660 Kernel/FS: Promote the entry to the front during a cache hit
  Kernel/FileSystem/BlockBasedFileSystem.cpp
Labels: 👀 pr-needs-review

#18659 LibGfx/WebP: Some steps towards supporting animated webp files, and two bug fixes
  Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
Labels: 👀 pr-needs-review

#18664 Kernel/Memory: Fix UNMAP_AFTER_INIT page fault handling
  Kernel/Memory/MemoryManager.cpp
Labels: 👀 pr-needs-review

#18669 LibWeb: Fill PageHost root with document background color
  Userland/Services/WebContent/PageHost.cpp
  Userland/Services/WebContent/PageHost.h
Labels: 👀 pr-needs-review

#18671 LibGUI: Guard us from trying to slice an empty Arguments::strings
  Userland/Libraries/LibGUI/Application.cpp
Labels: 👀 pr-needs-review

#18652 Documentation: Correct some typos found in kernel markdown files
  Documentation/Kernel/DevelopmentGuidelines.md
  Documentation/Kernel/GraphicsSubsystem.md
  Documentation/Kernel/ProcFSIndexing.md
  Documentation/Kernel/RAMFS.md
Labels: 👀 pr-needs-review

#18672 LibWeb: Invalidate style *and* layout when removing a DOM node
  Userland/Libraries/LibWeb/DOM/Node.cpp
Labels: 👀 pr-needs-review

#18676 Ladybird: Stop telling Qt to use HTTP pipelining
  Ladybird/RequestManagerQt.cpp
Labels: 👀 pr-needs-review

#18631 WindowServer: Fix window content scaling when switching from fullscreen
  Userland/Services/WindowServer/Window.cpp
Labels: 👀 pr-needs-review

#18674 Ports: Update serenity-theming to use the latest commit (f4b6f7f)
  Ports/AvailablePorts.md
  Ports/serenity-theming/package.sh
Labels: 👀 pr-needs-review

#18680 ThemeEditor: Remove one usage of DeprecatedString
  Userland/Applications/ThemeEditor/MainWidget.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#18679 Toolchain: Use ninja to bootstrap CMake
  Toolchain/BuildCMake.sh
Labels: 👀 pr-needs-review

#18687 LibGfx+WindowServer: Ensure constrain-to-rect ends up inside the rect
  Userland/Libraries/LibGfx/Point.cpp
  Userland/Services/WindowServer/Screen.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#18683 Base+Snake: Capitalize snake skin names
  Base/res/graphics/snake/skins/Blue Malaysian Coral Snake (Calliophis bivirgatus)/corner.png
  Base/res/graphics/snake/skins/Blue Malaysian Coral Snake (Calliophis bivirgatus)/head.png
  Base/res/graphics/snake/skins/Blue Malaysian Coral Snake (Calliophis bivirgatus)/horizontal.png
  Base/res/graphics/snake/skins/Blue Malaysian Coral Snake (Calliophis bivirgatus)/tail.png
  Base/res/graphics/snake/skins/Blue Malaysian Coral Snake (Calliophis bivirgatus)/vertical.png
  Base/res/graphics/snake/skins/Eastern Coral Snake (Micrurus fulvius)/corner.png
  Base/res/graphics/snake/skins/Eastern Coral Snake (Micrurus fulvius)/head.png
  Base/res/graphics/snake/skins/Eastern Coral Snake (Micrurus fulvius)/horizontal.png
  Base/res/graphics/snake/skins/Eastern Coral Snake (Micrurus fulvius)/tail.png
  Base/res/graphics/snake/skins/Eastern Coral Snake (Micrurus fulvius)/vertical.png
  Base/res/graphics/snake/skins/Ladybird/corner.png
  Base/res/graphics/snake/skins/Ladybird/head.png
  Base/res/graphics/snake/skins/Ladybird/horizontal.png
  Base/res/graphics/snake/skins/Ladybird/tail.png
  Base/res/graphics/snake/skins/Ladybird/vertical.png
  Base/res/graphics/snake/skins/San Francisco Garter Snake (Thamnophis sirtalis tetrataenia)/corner.png
  Base/res/graphics/snake/skins/San Francisco Garter Snake (Thamnophis sirtalis tetrataenia)/head.png
  Base/res/graphics/snake/skins/San Francisco Garter Snake (Thamnophis sirtalis tetrataenia)/horizontal.png
  Base/res/graphics/snake/skins/San Francisco Garter Snake (Thamnophis sirtalis tetrataenia)/tail.png
  Base/res/graphics/snake/skins/San Francisco Garter Snake (Thamnophis sirtalis tetrataenia)/vertical.png
  Base/res/graphics/snake/skins/Snake/corner.png
  Base/res/graphics/snake/skins/Snake/head.png
  Base/res/graphics/snake/skins/Snake/horizontal.png
  Base/res/graphics/snake/skins/Snake/tail.png
  Base/res/graphics/snake/skins/Snake/vertical.png
  Base/res/graphics/snake/skins/Sri Lankan Green Vine Snake (Ahaetulla nasuta)/corner.png
  Base/res/graphics/snake/skins/Sri Lankan Green Vine Snake (Ahaetulla nasuta)/head.png
  Base/res/graphics/snake/skins/Sri Lankan Green Vine Snake (Ahaetulla nasuta)/horizontal.png
  Base/res/graphics/snake/skins/Sri Lankan Green Vine Snake (Ahaetulla nasuta)/tail.png
  Base/res/graphics/snake/skins/Sri Lankan Green Vine Snake (Ahaetulla nasuta)/vertical.png
  Userland/Games/Snake/Game.cpp
  Userland/Games/Snake/Skins/SnakeSkin.cpp
  Userland/Games/Snake/main.cpp
Labels: 👀 pr-needs-review

#18689 LibWeb: Enforce min/max height constraints on abspos replaced boxes
  Tests/LibWeb/Layout/expected/abspos-image-with-min-height-constraint.txt
  Tests/LibWeb/Layout/input/abspos-image-with-min-height-constraint.html
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Labels: 👀 pr-needs-review

#18694 LibWeb: Implement IDL overload resolution steps to clamp argument counts
  Userland/Libraries/LibWeb/WebIDL/OverloadResolution.cpp
Labels: 👀 pr-needs-review

#18686 Base: Improve Assistant App Icon (16px)
  Base/res/icons/16x16/app-assistant.png
Labels: 👀 pr-needs-review

#18685 Base: Add web server tip to Tips-and-Tricks(7)
  Base/usr/share/man/man7/Tips-and-Tricks.md
Labels: 👀 pr-needs-review

#18695 Ladybird: Don't ask Qt to decode SVG images for us
  Ladybird/ImageCodecPluginLadybird.cpp
Labels: 👀 pr-needs-review

#18583 LibGfx/JPEG: Performance work regarding the Huffman stream
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Labels: 👀 pr-needs-review

#18698 LibGfx/OpenType: Cache kerning values for faster text layout
  Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
  Userland/Libraries/LibGfx/Font/OpenType/Font.h
Labels: 👀 pr-needs-review

#18697 LibWeb: Add fast_is<T>() helper for HTMLScriptElement
  Userland/Libraries/LibWeb/DOM/Node.h
  Userland/Libraries/LibWeb/HTML/HTMLScriptElement.h
Labels: 👀 pr-needs-review

#18700 LibJS: Revert to original text in spec
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Labels: 👀 pr-needs-review

#18709 LibWeb: Don't force relayout on scheduled layout update
  Userland/Libraries/LibWeb/DOM/Document.cpp
Labels: 👀 pr-needs-review

#18703 LibGUI: Always paint vertical lines for Frames in unmaximized windows
  Userland/Libraries/LibGUI/Frame.cpp
Labels: 👀 pr-needs-review

#18706 Ladybird: Don't ask Qt to decode any images for us
  Ladybird/ImageCodecPluginLadybird.cpp
Labels: 👀 pr-needs-review

#18713 LibWeb: Don't relayout when visibility changes between visible/hidden
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: 👀 pr-needs-review

#18702 LibCrypto+LibTLS: Avoid crashing on invalid input
  Userland/Libraries/LibCrypto/ASN1/DER.h
  Userland/Libraries/LibTLS/Certificate.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#18693 Tests: Add more tests for `JsonArray`
  Tests/AK/TestJSON.cpp
Labels: 👀 pr-needs-review

#18715 Documentation: Add libslirp-dev as a required dependency for QEMU
  Documentation/BuildInstructions.md
Labels: 👀 pr-needs-review

#18714 LibGUI: Increase autoscroll threshold value
  Userland/Libraries/LibGUI/AbstractScrollableWidget.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#18719 LibWeb: Cache the root element font metrics when calculating them
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
  Userland/Libraries/LibWeb/CSS/StyleComputer.h
Labels: 👀 pr-needs-review

#18707 LibGfx/WebP: Move lossless decoder to its own file
  Userland/Libraries/LibGfx/CMakeLists.txt
  Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
  Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossless.cpp
  Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossless.h
Labels: 👀 pr-needs-review

#18731 LibGfx/JPEG: Fix faded 4-channels images
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Labels: 👀 pr-needs-review

#18722 Documentation: Homogenize Ladybird build instructions
  Documentation/BuildInstructionsLadybird.md
  Ladybird/README.md
Labels: 👀 pr-needs-review

#18508 LibManual: Open page from a help URL
  Userland/Libraries/LibManual/Node.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#17775 Applets/ClipboardHistory: Add persistent storage
  Userland/Applets/ClipboardHistory/ClipboardHistoryModel.cpp
  Userland/Applets/ClipboardHistory/ClipboardHistoryModel.h
  Userland/Applets/ClipboardHistory/main.cpp
  Userland/Libraries/LibGUI/Clipboard.cpp
  Userland/Libraries/LibGUI/Clipboard.h
Labels: 👀 pr-needs-review

#18733 Ladybird: Allow right clicking and inspecting elements
  Ladybird/BrowserWindow.cpp
  Ladybird/BrowserWindow.h
  Ladybird/InspectorWidget.cpp
  Ladybird/InspectorWidget.h
  Ladybird/ModelTranslator.h
  Ladybird/WebContentView.cpp
  Ladybird/WebContentView.h
Labels: 👀 pr-needs-review

#18734 AK: Remove `must_set()` from `JsonArray`
  AK/JsonArray.h
  Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
Labels: 👀 pr-needs-review

#18736 Ports: Fix issue with `./package.sh dev` not able to extract files after cleaning build directory
  Ports/.port_include.sh
Labels: 👀 pr-needs-review

#18727 LibWeb: Initial offset in reverse flex layout moved to opposite side
  Tests/LibWeb/Layout/expected/flex/flex-row-reverse-with-centered-content.txt
  Tests/LibWeb/Layout/input/flex/flex-row-reverse-with-centered-content.html
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Labels: 👀 pr-needs-review

#18741 LibWeb: Improve handling of min/max constraint violations on images
  Tests/LibWeb/Layout/expected/image-with-multiple-constraint-violations.txt
  Tests/LibWeb/Layout/input/image-with-multiple-constraint-violations.html
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Labels: 👀 pr-needs-review

#18742 ClipboardHistory: Replace Core::BufferedFile use with InputBufferedFile
  Userland/Applets/ClipboardHistory/ClipboardHistoryModel.cpp
Labels: 👀 pr-needs-review

#18744 CI: Update the action to package the JS REPL to macOS 13
  .github/workflows/serenity-js-artifacts.yml
Labels: 👀 pr-needs-review

#18745 LibGfx/WebP: Do not add alpha channel for animated images without alpha
  Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
Labels: 👀 pr-needs-review

#18746 LibWeb: GridFormattingContext refactoring. Part 2
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#18743 Help: Fix link to Contents page
  Userland/Applications/Help/MainWidget.cpp
Labels: 👀 pr-needs-review

#18752 LibWeb: Adjust flex item main size through aspect ratio if needed
  Tests/LibWeb/Layout/expected/flex/flex-item-with-intrinsic-aspect-ratio-and-max-height.txt
  Tests/LibWeb/Layout/input/flex/flex-item-with-intrinsic-aspect-ratio-and-max-height.html
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
Labels: 👀 pr-needs-review

#18748 Chess+GameSettings: Optionally highlight the king when in check
  Userland/Applications/GamesSettings/ChessSettingsWidget.cpp
  Userland/Applications/GamesSettings/ChessSettingsWidget.gml
  Userland/Applications/GamesSettings/ChessSettingsWidget.h
  Userland/Games/Chess/ChessWidget.cpp
  Userland/Games/Chess/ChessWidget.h
  Userland/Games/Chess/main.cpp
Labels: 👀 pr-needs-review

#18754 LibWeb: Handle CSS "color: currentcolor"
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Labels: 👀 pr-needs-review

#18755 LibWeb: Don't resolve CSS property values for unconnected elements
  Tests/LibWeb/Layout/expected/getComputedStyle-on-unconnected-element.txt
  Tests/LibWeb/Layout/input/getComputedStyle-on-unconnected-element.html
  Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
Labels: 👀 pr-needs-review

#18756 LibWeb: Fix percentage min/max sizes on flex items with intrinsic ratio
  Tests/LibWeb/Layout/expected/flex/flex-column-item-with-intrinsic-aspect-ratio-and-percentage-max-width.txt
  Tests/LibWeb/Layout/input/flex/flex-column-item-with-intrinsic-aspect-ratio-and-percentage-max-width.html
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Labels: 👀 pr-needs-review

#18768 errno: Include error code names in output and allow lookup by name
  Userland/Utilities/errno.cpp
Labels: 👀 pr-needs-review

#18770 LibWeb: Resolve grid items preferred width in GFC
  Tests/LibWeb/Layout/expected/grid/grid-item-fixed-size.txt
  Tests/LibWeb/Layout/expected/grid/grid-item-percentage-width.txt
  Tests/LibWeb/Layout/input/grid/grid-item-fixed-size.html
  Tests/LibWeb/Layout/input/grid/grid-item-percentage-width.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#18771 HexEditor: Add list of recently opened files
  Userland/Applications/HexEditor/HexEditorWidget.cpp
  Userland/Applications/HexEditor/main.cpp
Labels: 👀 pr-needs-review

#18780 ClipboardHistory: Use titlecasing in the applet's window title
  Userland/Applets/ClipboardHistory/main.cpp
Labels: 👀 pr-needs-review

#18785 Base: Run `SpiceAgent` as a user service
  Base/etc/SystemServer.ini
  Base/home/anon/.config/SystemServer.ini
Labels: 👀 pr-needs-review

#18788 LibWeb: Align calculate_min/max_content_contribution with the spec
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#18789 LibWeb: Fix typo in containing_block_size_for_item in GFC
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#18790 LibWeb: Make PercentageOr<T> equality comparison work for calc() values
  Userland/Libraries/LibWeb/CSS/PercentageOr.h
Labels: 👀 pr-needs-review

#18791 Ladybird: Disable SQL database by default (until we can trust it)
  Ladybird/main.cpp
Labels: 👀 pr-needs-review

#18779 Ports: Update and fix nethack
  Ports/AvailablePorts.md
  Ports/nethack/package.sh
Labels: 👀 pr-needs-review

#18777 LibDebug: Propagate errors around LineProgram
  Userland/Libraries/LibDebug/Dwarf/DwarfInfo.cpp
  Userland/Libraries/LibDebug/Dwarf/LineProgram.cpp
  Userland/Libraries/LibDebug/Dwarf/LineProgram.h
Labels: 👀 pr-needs-review

#18784 Kernel/aarch64: Remove drawing of logo on the framebuffer during init
  Kernel/Arch/aarch64/RPi/Framebuffer.cpp
  Kernel/Arch/aarch64/RPi/Framebuffer.h
  Kernel/Arch/aarch64/SerenityLogoRGB.ppm
  Kernel/Arch/init.cpp
  Kernel/CMakeLists.txt
Labels: 👀 pr-needs-review

#18794 SpiceAgent: Gracefully handle the host clearing the clipboard
  Userland/Services/SpiceAgent/SpiceAgent.cpp
Labels: 👀 pr-needs-review

#18760 Ladybird: Add common handy actions to context menu
  Ladybird/BrowserWindow.cpp
  Ladybird/BrowserWindow.h
  Ladybird/Tab.cpp
  Ladybird/Tab.h
Labels: 👀 pr-needs-review

#18811 LibJS/Bytecode: Variable declarators should always prefer lexical env
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Labels: 👀 pr-needs-review

#18805 test-pthread: Check for correct return value from sem_trywait()
  Userland/Utilities/test-pthread.cpp
Labels: 👀 pr-needs-review

#18816 AK: Fix typo in instructions for adopt_nonnull_REF_or_enomem
  AK/NonnullRefPtr.h
Labels: 👀 pr-needs-review

#18806 LibWeb: Flesh out basic support for min-width/height for grid items
  Tests/LibWeb/Layout/expected/grid/grid-item-min-size.txt
  Tests/LibWeb/Layout/input/grid/grid-item-min-size.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#18826 LibWeb: Change implicit background-size height to auto
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#18809 SystemMonitor: Prefer Core::File, fix username polling
  Userland/Applications/SystemMonitor/ProcessModel.cpp
  Userland/Applications/SystemMonitor/ProcessModel.h
Labels: 👀 pr-needs-review

#18830 LibWeb: Separate grid tracks from gaps in GFC
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#18831 LibWeb: Start implementing sizing for tracks with span > 1 items in GFC
  Tests/LibWeb/Layout/expected/grid/row-span-2.txt
  Tests/LibWeb/Layout/input/grid/row-span-2.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#18711 Tests: Prefer MUST() over EXPECT(!.is_error())
  Tests/AK/TestBase64.cpp
  Tests/AK/TestCircularBuffer.cpp
  Tests/Kernel/TestKernelFilePermissions.cpp
  Tests/LibC/TestIo.cpp
  Tests/LibC/TestLibCMkTemp.cpp
  Tests/LibCompress/TestDeflate.cpp
  Tests/LibCompress/TestGzip.cpp
  Tests/LibCore/TestLibCoreFilePermissionsMask.cpp
  Tests/LibCore/TestLibCoreSharedSingleProducerCircularQueue.cpp
  Tests/LibCore/TestLibCoreStream.cpp
  Tests/LibEDID/TestEDID.cpp
  Tests/LibELF/test-elf.cpp
  Tests/LibGfx/TestFontHandling.cpp
  Tests/LibJS/test-bytecode-js.cpp
  Tests/LibPDF/TestPDF.cpp
  Tests/LibSQL/TestSqlBtreeIndex.cpp
  Tests/LibSQL/TestSqlDatabase.cpp
  Tests/LibSQL/TestSqlExpressionParser.cpp
  Tests/LibSQL/TestSqlHashIndex.cpp
  Tests/LibSQL/TestSqlStatementExecution.cpp
  Tests/LibSQL/TestSqlStatementParser.cpp
  Tests/LibSQL/TestSqlValueAndTuple.cpp
  Tests/LibThreading/TestThread.cpp
Labels: 👀 pr-needs-review

#18759 AK+LookupServer: Migrate from DeprecatedFile to File
  Userland/Services/LookupServer/LookupServer.cpp
  Userland/Services/LookupServer/LookupServer.h
Labels: 👀 pr-needs-review

#18810 ls: Migrate away from DeprecatedFile
  Userland/Utilities/ls.cpp
Labels: 👀 pr-needs-review

#18832 LibGfx: Stop assuming the target format is always BGRA8888
  Userland/Libraries/LibGfx/Painter.cpp
Labels: 👀 pr-needs-review

#18840 LibCore: Use StringView in Object::find_{child,descendant}_of_type_named
  Userland/Libraries/LibCore/Object.h
Labels: 👀 pr-needs-review

#18825 LibGUI: Fix two small OpacitySlider issues
  Userland/Libraries/LibGUI/OpacitySlider.cpp
Labels: 👀 pr-needs-review

#18838 Spreadsheet: Don't release the file buffer when importing CSV files
  Userland/Applications/Spreadsheet/ImportDialog.cpp
Labels: 👀 pr-needs-review

#18847 Ladybird+LibWebView: Move backing store management code to LibWebView
  Ladybird/WebContentView.cpp
  Ladybird/WebContentView.h
  Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
  Userland/Libraries/LibWebView/OutOfProcessWebView.h
  Userland/Libraries/LibWebView/ViewImplementation.cpp
  Userland/Libraries/LibWebView/ViewImplementation.h
  Userland/Utilities/headless-browser.cpp
Labels: 👀 pr-needs-review

#18849 LibWeb: Fix iframes flickering on window resize
  Userland/Libraries/LibWeb/Layout/Box.h
  Userland/Libraries/LibWeb/Layout/FrameBox.cpp
  Userland/Libraries/LibWeb/Layout/FrameBox.h
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Labels: 👀 pr-needs-review

#18848 LibWeb: Cache state of the contenteditable attribute on HTMLElement
  Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLElement.h
Labels: 👀 pr-needs-review

#18852 LibWeb: Fix UBSAN issue caused by invalid TemporaryTrack pointer in GFC
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#18853 LibWeb: Fix specified_size_suggestion to use size of dimension
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#18851 LibWeb: Do not layout grid items during grid container intrinsic sizing
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#18869 Kernel: Restore kernel8.img for aarch64 build
  Kernel/CMakeLists.txt
Labels: 👀 pr-needs-review

#18862 LibWeb: Implement location.assign
  Userland/Libraries/LibWeb/HTML/Location.cpp
  Userland/Libraries/LibWeb/HTML/Location.h
  Userland/Libraries/LibWeb/HTML/Location.idl
Labels: 👀 pr-needs-review

#18858 LibJS/Bytecode: Implement initial support for super member expressions
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
  Userland/Libraries/LibJS/Bytecode/Generator.cpp
  Userland/Libraries/LibJS/Bytecode/Instruction.h
  Userland/Libraries/LibJS/Bytecode/Op.cpp
  Userland/Libraries/LibJS/Bytecode/Op.h
Labels: 👀 pr-needs-review

#18863 LibVT: Correctly wrap text when the scrollbar is hidden
  Userland/Libraries/LibVT/TerminalWidget.cpp
Labels: 👀 pr-needs-review

#18856 ps: Add `-A`, `-a`, `-p`, and `-u` options, plus various other updates and improvements
  Base/usr/share/man/man1/ps.md
  Userland/Utilities/ps.cpp
Labels: 👀 pr-needs-review

#18843 LibWeb: Fix for absolutely positioned elements with specified height
  Tests/LibWeb/Layout/expected/height-of-absolute-position-box-with-padding.txt
  Tests/LibWeb/Layout/input/height-of-absolute-position-box-with-padding.html
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Labels: 👀 pr-needs-review

#18877 GMLPlayground: Keep view_frame_action around to prevent a crash
  Userland/DevTools/GMLPlayground/MainWidget.cpp
  Userland/DevTools/GMLPlayground/MainWidget.h
Labels: 👀 pr-needs-review

#18880 Ladybird: Fix context menus being in slightly the wrong position
  Ladybird/Tab.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#18879 LibWebView: Remove the DumpLayoutTree program
  Userland/DevTools/HackStudio/ProjectBuilder.cpp
  Userland/Libraries/LibWebView/CMakeLists.txt
  Userland/Libraries/LibWebView/DumpLayoutTree/CMakeLists.txt
  Userland/Libraries/LibWebView/DumpLayoutTree/main.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#18883 lsirq: Restore enumeration of interrupt line
  Userland/Utilities/lsirq.cpp
Labels: 👀 pr-needs-review

#18773 Meta: Only enable SPICE integration when using the SPICE display
  Meta/run.sh
Labels: 👀 pr-needs-review

#18890 LibWeb: Remove borders from TemporaryTrack in GFC
  Tests/LibWeb/Layout/expected/grid/borders.txt
  Tests/LibWeb/Layout/expected/grid/intrinsic-sized-column.txt
  Tests/LibWeb/Layout/expected/grid/intrinsic-sized-grid-2.txt
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#18763 Meta/ShellCompletions: Add toolchain and Lagom binary zsh completion
  Meta/ShellCompletions/zsh/_serenity
Labels: 👀 pr-needs-review

#18894 LibWeb: Resolve CSS custom properties on pseudo elements
  Tests/LibWeb/Layout/expected/pseudo-element-with-custom-properties-2.txt
  Tests/LibWeb/Layout/expected/pseudo-element-with-custom-properties.txt
  Tests/LibWeb/Layout/input/pseudo-element-with-custom-properties-2.html
  Tests/LibWeb/Layout/input/pseudo-element-with-custom-properties.html
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
  Userland/Libraries/LibWeb/CSS/StyleComputer.h
  Userland/Libraries/LibWeb/DOM/Element.cpp
  Userland/Libraries/LibWeb/DOM/Element.h
  Userland/Services/WebContent/ConnectionFromClient.cpp
Labels: 👀 pr-needs-review

#18897 CatDog: Stop recognizing name of deleted program
  Userland/Demos/CatDog/CatDog.cpp
Labels: 👀 pr-needs-review

#17621 Kernel+Userland: Split bind-mounting and re-mounting from mount syscall
  Base/usr/share/man/man2/bindmount.md
  Base/usr/share/man/man2/mount.md
  Base/usr/share/man/man2/remount.md
  Kernel/API/Syscall.h
  Kernel/Process.h
  Kernel/Syscalls/mount.cpp
  Userland/Libraries/LibCore/System.cpp
  Userland/Libraries/LibCore/System.h
  Userland/Services/SystemServer/main.cpp
  Userland/Utilities/mount.cpp
Labels: 👀 pr-needs-review

#18899 Meta: Build abench on Lagom
  Meta/Lagom/CMakeLists.txt
Labels: 👀 pr-needs-review

#18908 LibWeb: Use grid item used width as available width during track sizing
  Tests/LibWeb/Layout/expected/grid/auto-fill.txt
  Tests/LibWeb/Layout/expected/grid/auto-fit.txt
  Tests/LibWeb/Layout/expected/grid/borders.txt
  Tests/LibWeb/Layout/expected/grid/grid-gap-2.txt
  Tests/LibWeb/Layout/expected/grid/grid-item-percentage-width-2.txt
  Tests/LibWeb/Layout/expected/grid/named-tracks.txt
  Tests/LibWeb/Layout/expected/grid/positions-and-spans.txt
  Tests/LibWeb/Layout/expected/grid/row-span-2.txt
  Tests/LibWeb/Layout/expected/grid/template-lines-and-areas.txt
  Tests/LibWeb/Layout/input/grid/grid-item-percentage-width-2.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#18904 AK: Add dbg()
  AK/Format.cpp
  AK/Format.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#18912 Ports: Update serenity-theming use latest commit 83fb3e7
  Ports/AvailablePorts.md
  Ports/serenity-theming/package.sh
Labels: 👀 pr-needs-review

#18828 AK: Include Array.h in Base64.h
  AK/Base64.cpp
  AK/Base64.h
Labels: 👀 pr-needs-review

#18911 LibWeb: Resolve grid item fixed size paddings in GFC
  Tests/LibWeb/Layout/expected/grid/grid-item-fixed-paddings.txt
  Tests/LibWeb/Layout/input/grid/grid-item-fixed-paddings.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#18918 LibWeb: Make sure that margins don't collapse across a nested BFC
  Tests/LibWeb/Layout/expected/block-and-inline/margin-must-not-collapse-across-nested-bfc.txt
  Tests/LibWeb/Layout/expected/table/basic.txt
  Tests/LibWeb/Layout/input/block-and-inline/margin-must-not-collapse-across-nested-bfc.html
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Labels: 👀 pr-needs-review

#18919 LibWeb: Fix null dereference on SVG element with bogus fill URL
  Tests/LibWeb/Layout/expected/svg/svg-fill-with-bogus-url.txt
  Tests/LibWeb/Layout/input/svg/svg-fill-with-bogus-url.html
  Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
Labels: 👀 pr-needs-review

#17909 Kernel: Move a bunch of generic devices code into new subdirectory
  Kernel/Arch/init.cpp
  Kernel/CMakeLists.txt
  Kernel/Devices/Audio/Channel.cpp
  Kernel/Devices/DeviceManagement.h
  Kernel/Devices/Generic/ConsoleDevice.cpp
  Kernel/Devices/Generic/ConsoleDevice.h
  Kernel/Devices/Generic/DeviceControlDevice.cpp
  Kernel/Devices/Generic/DeviceControlDevice.h
  Kernel/Devices/Generic/FullDevice.cpp
  Kernel/Devices/Generic/FullDevice.h
  Kernel/Devices/Generic/MemoryDevice.cpp
  Kernel/Devices/Generic/MemoryDevice.h
  Kernel/Devices/Generic/NullDevice.cpp
  Kernel/Devices/Generic/NullDevice.h
  Kernel/Devices/Generic/RandomDevice.cpp
  Kernel/Devices/Generic/RandomDevice.h
  Kernel/Devices/Generic/SelfTTYDevice.cpp
  Kernel/Devices/Generic/SelfTTYDevice.h
  Kernel/Devices/Generic/ZeroDevice.cpp
  Kernel/Devices/Generic/ZeroDevice.h
  Kernel/FileSystem/SysFS/Subsystems/Kernel/Log.cpp
  Kernel/Net/TCPSocket.cpp
  Kernel/Net/UDPSocket.cpp
  Kernel/Process.cpp
  Kernel/Random.cpp
  Kernel/TTY/VirtualConsole.h
  Kernel/kprintf.cpp
Labels: 👀 pr-needs-review

#18898 Kernel/ScatterGatherList: Improve error propagation
  Kernel/Memory/ScatterGatherList.cpp
  Kernel/Memory/ScatterGatherList.h
  Kernel/Storage/ATA/AHCI/Port.cpp
Labels: ✅ pr-community-approved

#18923 aplay: Determine absolute path before raising the veil
  Userland/Utilities/aplay.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#18916 Ports/dos2unix: Update to 7.5.0
  Ports/AvailablePorts.md
  Ports/dos2unix/package.sh
Labels: 👀 pr-needs-review

#18926 IPCCompiler: Nicer error message for invalid template spelling
  Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
Labels: 👀 pr-needs-review

#18903 LibWasm: Change dir_fd to auto instead of int
  Userland/Libraries/LibWasm/WASI/Wasi.cpp
Labels: 👀 pr-needs-review

#18874 Kernel: Check only for the first equal sign in the kernel command line key-value decomposition
  Kernel/CommandLine.cpp
Labels: ✅ pr-community-approved

#18933 Base: Move user nona from group 200 into existing group users
  Base/etc/passwd
  Meta/build-root-filesystem.sh
Labels: 👀 pr-needs-review

#18942 SystemServer: Print useful information when failing to drop privileges
  Userland/Services/SystemServer/Service.cpp
Labels: 👀 pr-needs-review

#18932 tail: Don't read past EOF and handle trailing newlines correctly
  Userland/Utilities/tail.cpp
Labels: 👀 pr-needs-review

#18935 Meta: Also run markdown-check on markdown files in each Port subdir
  Meta/check-markdown.sh
  Userland/Utilities/markdown-check.cpp
Labels: 👀 pr-needs-review

#18929 Ladybird: Remove unused IODevice.h include
  Ladybird/WebContentView.cpp
Labels: 👀 pr-needs-review

#18917 Kernel/aarch64: Detect if access faults come from SafeMem
  Kernel/Arch/aarch64/SafeMem.cpp
  Kernel/Arch/aarch64/linker.ld
Labels: 👀 pr-needs-review

#18955 LibWeb: Don't crash on percentage values for CSS stroke-width
  Tests/LibWeb/Layout/expected/misc/percentage-stroke-width-crash.txt
  Tests/LibWeb/Layout/input/misc/percentage-stroke-width-crash.html
  Userland/Libraries/LibWeb/Layout/Node.cpp
Labels: 👀 pr-needs-review
