Repository SerenityOS/serenity, pull requests merged in 2024-11, with the labels that each got.

#25209 Cherry-pick "LibWasm: Clean up module sections API"
  Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp
  Userland/Libraries/LibWasm/AbstractMachine/Validator.cpp
  Userland/Libraries/LibWasm/Parser/Parser.cpp
  Userland/Libraries/LibWasm/Printer/Printer.cpp
  Userland/Libraries/LibWasm/Types.h
  Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp
  Userland/Utilities/wasm.cpp
Labels: 👀 pr-needs-review

#25208 Cherry-pick "LibWeb: Cache the Document's node navigable when possible"
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/DOM/Node.cpp
Labels: 👀 pr-needs-review

#25211 Cherry-pick "UI/Qt: Set debug menu options across all tabs"
  Ladybird/Qt/BrowserWindow.cpp
  Ladybird/Qt/BrowserWindow.h
  Ladybird/Qt/Tab.cpp
  Ladybird/Qt/Tab.h
Labels: 👀 pr-needs-review

#25212 Cherry-pick "LibWeb: Bail early from doomed pseudo-element style computation"
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Labels: 👀 pr-needs-review

#25213 Cherry-pick "LibWeb: Bucket CSS rules by pseudo-element"
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
  Userland/Libraries/LibWeb/CSS/StyleComputer.h
Labels: 👀 pr-needs-review

#25214 Cherry-pick "LibWeb/CSS: Implement revert-layer"
  Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSKeyword.cpp
  Tests/LibWeb/Text/expected/css/revert-layer.txt
  Tests/LibWeb/Text/input/css/revert-layer.html
  Userland/Libraries/LibWeb/CSS/CSSStyleValue.h
  Userland/Libraries/LibWeb/CSS/Keywords.json
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/CSSKeywordValue.h
Labels: 👀 pr-needs-review

#25191 Document: Modify the storage type of VirtualBox
  Documentation/VirtualBox.md
Labels: 👀 pr-needs-review

#25010 Base: Add CrashReporter(1), dbgputstr(2), dump_backtrace(2) manpages
  Base/usr/share/man/man1/Applications/CrashReporter.md
  Base/usr/share/man/man1/Applications/CrashReporter.png
  Base/usr/share/man/man1/crash.md
  Base/usr/share/man/man2/dbgputstr.md
  Base/usr/share/man/man2/dump_backtrace.md
Labels: 👀 pr-needs-review

#25216 Cherry-pick "UI/Qt: Ensure we don't add the same zoom shortcut key more than once"
  Ladybird/Qt/BrowserWindow.cpp
Labels: 👀 pr-needs-review

#25218 Cherry-pick "LibWeb: Ensure a repaint occurs when the current selection is cleared"
  Userland/Libraries/LibWeb/DOM/Range.cpp
Labels: 👀 pr-needs-review

#25217 Cherry-pick "UI/Qt: Update placeholder text if search disabled"
  Ladybird/Qt/LocationEdit.cpp
Labels: 👀 pr-needs-review

#25220 Cherry-pick "Ladybird/AppKit: Add actions to set navigator compatibility mode"
  Ladybird/AppKit/Application/ApplicationDelegate.mm
  Ladybird/AppKit/UI/TabController.h
  Ladybird/AppKit/UI/TabController.mm
Labels: 👀 pr-needs-review

#25225 Cherry-pick "LibJS: Update console spec's use of "Type()" -> "is a""
  Userland/Libraries/LibJS/Console.cpp
Labels: 👀 pr-needs-review

#25223 Cherry-pick "LibWeb: Support finding text split across multiple text nodes"
  Userland/Libraries/LibWeb/DOM/Document.cpp
Labels: 👀 pr-needs-review

#25219 Cherry-pick "UI/Qt: Don't show URL when a new tab is initially focused"
  Ladybird/Qt/BrowserWindow.cpp
  Ladybird/Qt/LocationEdit.cpp
  Ladybird/Qt/LocationEdit.h
  Ladybird/Qt/Tab.cpp
  Ladybird/Qt/Tab.h
Labels: ci-flakiness, 👀 pr-needs-review

#25221 Cherry-pick "UI/Qt: Add standard shortcuts for find in page actions"
  Ladybird/Qt/BrowserWindow.cpp
  Ladybird/Qt/FindInPageWidget.cpp
  Ladybird/Qt/FindInPageWidget.h
  Ladybird/Qt/Tab.cpp
  Ladybird/Qt/Tab.h
Labels: 👀 pr-needs-review

#25222 Cherry-pick "LibWeb: Rerun find in page query when navigating between URLs"
  Userland/Libraries/LibWeb/Page/Page.cpp
  Userland/Libraries/LibWeb/Page/Page.h
  Userland/Services/WebContent/ConnectionFromClient.cpp
Labels: 👀 pr-needs-review

#25224 Cherry-pick "LibWebView: Append remaining source after consuming all tokens"
  Userland/Libraries/LibWebView/SourceHighlighter.cpp
Labels: 👀 pr-needs-review

#25226 Cherry-pick "LibIDL: Allow trailing comma in enumerations"
  Userland/Libraries/LibIDL/IDLParser.cpp
Labels: 👀 pr-needs-review

#25228 Cherry-pick "Meta: ENABLE_NETWORK_DOWNLOADS for ca_certificates and public_suffix"
  Meta/CMake/ca_certificates_data.cmake
  Meta/CMake/public_suffix.cmake
Labels: 👀 pr-needs-review

#25227 Cherry-pick "UI/Qt: Show search engine name in location bar"
  Ladybird/Qt/LocationEdit.cpp
  Ladybird/Qt/LocationEdit.h
  Ladybird/Qt/Settings.cpp
  Ladybird/Qt/Settings.h
Labels: 👀 pr-needs-review

#25233 Cherry-pick "LibWeb: Save float-intrusion for marker before list elements layout"
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
Labels: 👀 pr-needs-review

#25238 Cherry-pick "WebDriver: Launch Ladybird with `--force-new-process`"
  Ladybird/WebDriver/main.cpp
Labels: 👀 pr-needs-review

#25240 Meta: Add DragEvent to GN build
  Meta/gn/secondary/Userland/Libraries/LibWeb/HTML/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWeb/idl_files.gni
Labels: 👀 pr-needs-review

#25237 Ports: Add qop
  Ports/AvailablePorts.md
  Ports/qop/package.sh
Labels: 👀 pr-needs-review

#25245 Cherry-pick "LibMedia: Hide Matroska debug message behind a flag"
  Userland/Libraries/LibMedia/Containers/Matroska/Reader.cpp
Labels: 👀 pr-needs-review

#25244 Cherry-pick "LibWeb: Implement popover property and attribute"
  Userland/Libraries/LibWeb/HTML/AttributeNames.h
  Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLElement.h
  Userland/Libraries/LibWeb/HTML/HTMLElement.idl
Labels: 👀 pr-needs-review

#25246 Cherry-pick "LibWeb: Implement HTMLTrackElement.readyState"
  Tests/LibWeb/Text/expected/HTML/HTMLTrackElement-readyState-attribute.txt
  Tests/LibWeb/Text/input/HTML/HTMLTrackElement-readyState-attribute.html
  Userland/Libraries/LibWeb/HTML/HTMLTrackElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLTrackElement.h
  Userland/Libraries/LibWeb/HTML/HTMLTrackElement.idl
Labels: 👀 pr-needs-review

#25254 Ports/nyancat: Remove patch for printf() workaround
  Ports/nyancat/patches/0002-Use-d-for-time-diff-printing.patch
  Ports/nyancat/patches/ReadMe.md
Labels: 👀 pr-needs-review

#25249 Cherry-pick "LibWeb: Don't crash on getClientRects() in document without navigable"
  Tests/LibWeb/Text/expected/CSSOMView/getClientRects-in-detached-document.txt
  Tests/LibWeb/Text/input/CSSOMView/getClientRects-in-detached-document.html
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: 👀 pr-needs-review

#25252 Cherry-pick "LibWeb: Don't crash with invalid import maps"
  Tests/LibWeb/Text/expected/HTML/import-maps-invalid.txt
  Tests/LibWeb/Text/input/HTML/import-maps-invalid.html
  Userland/Libraries/LibWeb/HTML/Scripting/ImportMapParseResult.cpp
  Userland/Libraries/LibWeb/HTML/Scripting/ImportMapParseResult.h
Labels: 👀 pr-needs-review

#25251 Cherry-pick "LibWeb: Don't crash when converting small CSS::Ratio to CSSPixelFraction"
  Tests/LibWeb/Text/expected/css/small-aspect-ratio.txt
  Tests/LibWeb/Text/input/css/small-aspect-ratio.html
  Userland/Libraries/LibWeb/Layout/Box.cpp
  Userland/Libraries/LibWeb/PixelUnits.h
Labels: 👀 pr-needs-review

#25255 Utilities/pkg: Resolve FIXME
  Userland/Utilities/pkg/InstalledPortDatabase.cpp
Labels: 👀 pr-needs-review

#25259 Cherry-pick "LibWeb: Introduce variable `dom_node` in EventHandler::handle_mousedown"
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
Labels: 👀 pr-needs-review

#25256 Utilities/xxd: Colorize output
  Userland/Utilities/xxd.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#25262 Ports/cmatrix: Bump version to 5c082c6
  Ports/AvailablePorts.md
  Ports/cmatrix/package.sh
  Ports/cmatrix/patches/0001-Use-manual-include-library-paths-for-ncurses.patch
Labels: 👀 pr-needs-review

#25264 Ports: Fallback to 'convert' if 'magick' doesn't exist in install_icon
  Ports/.port_include.sh
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#25266 Utilities/fortune: Improve help & error messages
  Userland/Utilities/fortune.cpp
Labels: 👀 pr-needs-review

#25268 Utilities/iconv: Improve help message
  Userland/Utilities/iconv.cpp
Labels: 👀 pr-needs-review

#25269 Utilities/head: Make the function static & move it before `serenity_main`
  Userland/Utilities/head.cpp
Labels: 👀 pr-needs-review

#25261 Meta: Enable `qemu-vdagent` (for copy/paste support) by default on Linux
  Meta/run.py
  Toolchain/BuildQemu.sh
Labels: 👀 pr-needs-review

#25271 Cherry-pick "LibWeb: Honor `appearance: none` when creating input element layout node"
  Tests/LibWeb/Layout/expected/css-appearance-none.txt
  Tests/LibWeb/Layout/input/css-appearance-none.html
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Labels: 👀 pr-needs-review

#25273 Cherry-pick "LibWeb: Add “valid floating-point number” for HTMLInputElement.value"
  Tests/LibWeb/TestNumbers.cpp
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
  Userland/Libraries/LibWeb/HTML/Numbers.cpp
  Userland/Libraries/LibWeb/HTML/Numbers.h
Labels: 👀 pr-needs-review

#25276 Cherry-pick "LibWeb: Don't group radio buttons from different trees together"
  Tests/LibWeb/Text/expected/HTML/HTMLInputElement-radio-groups.txt
  Tests/LibWeb/Text/input/HTML/HTMLInputElement-radio-groups.html
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Labels: 👀 pr-needs-review

#25279 Cherry-pick "LibWeb: Readonly input element's arrow buttons don't change the value"
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Labels: 👀 pr-needs-review

#25283 Cherry-pick "LibWeb: Add missing fetch step & update for spec change"
  Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
  Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.h
Labels: 👀 pr-needs-review

#25274 Cherry-pick "LibWeb: Don't propagate key events that are handled by the media player"
  Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
Labels: 👀 pr-needs-review

#25287 Cherry-pick "LibWeb: Ensure Elements don't need style update after computing style"
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: 👀 pr-needs-review

#25284 Utilities/yes: Change the default output string to "y"
  Userland/Utilities/yes.cpp
Labels: 👀 pr-needs-review

#25291 Cherry-pick "Ladybird/Qt: Apply selected color scheme for new tabs"
  Ladybird/Qt/BrowserWindow.cpp
  Ladybird/Qt/BrowserWindow.h
Labels: 👀 pr-needs-review

#25293 Tests: Remove unused Kernel/ include
  Tests/LibCore/TestLibCoreFileWatcher.cpp
Labels: 👀 pr-needs-review

#25297 Cherry-pick "Ladybird/Qt: Only update navigation buttons for current tab"
  Ladybird/Qt/Tab.cpp
Labels: 👀 pr-needs-review

#25296 Cherry-pick "UI/Qt: Set a minimum size policy for the navigation control toolbar"
  Ladybird/Qt/Tab.cpp
Labels: 👀 pr-needs-review

#25294 Cherry-pick "Meta: Make check-debug-flags.sh runnable in Bash 3.2"
  Meta/check-debug-flags.sh
Labels: 👀 pr-needs-review

#25260 Meta: Add a script that prints potential Ladybird cherry-picks
  Meta/lb-cherry-picks.py
Labels: 👀 pr-needs-review

#25298 Utilities/yes: Remove unnecessary headers
  Userland/Utilities/yes.cpp
Labels: 👀 pr-needs-review

#25300 Cherry-pick "UI/Qt: Don't hide the location bar URL when creating a tab from a URL"
  Ladybird/Qt/Application.cpp
  Ladybird/Qt/BrowserWindow.cpp
  Ladybird/Qt/main.cpp
Labels: 👀 pr-needs-review

#25301 Cherry-pick "LibWeb: Don't extrapolate transition properties for unknown properties"
  Tests/LibWeb/Text/expected/WebAnimations/transition-unknown-property.txt
  Tests/LibWeb/Text/input/WebAnimations/transition-unknown-property.html
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Labels: 👀 pr-needs-review

#25308 Documentation: Remove reference to closed bug bounty program
  SECURITY.md
Labels: 👀 pr-needs-review

#25305 Ports/stb: Bump version to 2e2bef4
  Ports/AvailablePorts.md
  Ports/stb/package.sh
Labels: 👀 pr-needs-review

#25306 Libshell/Builtin: Improve spacing for the `time` builtin
  Userland/Libraries/LibShell/Builtin.cpp
Labels: 👀 pr-needs-review

#25307 Services/EchoServer: Improve UX
  Userland/Services/EchoServer/main.cpp
Labels: 👀 pr-needs-review

#25317 Meta: Add Sönke Holz to the maintainers list :^)
  CONTRIBUTING.md
Labels: 👀 pr-needs-review

#25316 LibWeb: Implement canvas setLineDash(), getLineDash(), lineDashOffset
  Tests/LibWeb/Screenshot/canvas-stroke-styles.html
  Tests/LibWeb/Screenshot/images/canvas-stroke-styles-ref.png
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasPathDrawingStyles.h
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasPathDrawingStyles.idl
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasState.h
  Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
Labels: 👀 pr-needs-review

#25324 Cherry-pick "LibWebView: Insert line numbers before each line in about:srcdoc"
  Userland/Libraries/LibWebView/SourceHighlighter.cpp
Labels: 👀 pr-needs-review

#25329 Meta: Tweak lb-cherry-picks.py script
  Meta/lb-cherry-picks.py
Labels: 👀 pr-needs-review

#25286 Cherry-pick "LibWeb: Handle calculations without a context better"
  Tests/LibWeb/Text/expected/css/calc-missing-context.txt
  Tests/LibWeb/Text/input/css/calc-missing-context.html
  Userland/Libraries/LibWeb/CSS/Length.h
  Userland/Libraries/LibWeb/CSS/StyleValues/CSSMathValue.cpp
Labels: 👀 pr-needs-review

#25335 Meta: Add ConsoleObjectPrototype.cpp to GN build
  Meta/gn/secondary/Userland/Libraries/LibJS/BUILD.gn
Labels: 👀 pr-needs-review

#25336 Utilities/json: Make variable `spaces_in_indent` unsigned to prevent negative values
  Userland/Utilities/json.cpp
Labels: 👀 pr-needs-review

#25339 Cherry-pick "LibWeb: Implement ServiceWorkerContainer.on{message,messageerror}"
  Userland/Libraries/LibWeb/HTML/ServiceWorkerContainer.cpp
  Userland/Libraries/LibWeb/HTML/ServiceWorkerContainer.h
  Userland/Libraries/LibWeb/HTML/ServiceWorkerContainer.idl
Labels: 👀 pr-needs-review

#25341 Utilities/fortune: Fix typo
  Userland/Utilities/fortune.cpp
Labels: ✅ pr-community-approved

#25342 Screenshot: Add checkbox to copy screenshot to clipboard
  Userland/Applications/Screenshot/MainWindow.cpp
  Userland/Applications/Screenshot/MainWindow.h
  Userland/Applications/Screenshot/Screenshot.gml
Labels: 👀 pr-needs-review

#25210 Cherry-pick "LibTimeZone: Read /etc/timezone for current TZ"
  Userland/Libraries/LibTimeZone/TimeZone.cpp
Labels: 👀 pr-needs-review

#25358 Cherry-pick "LibWeb: Stub out SVGGraphicsElement.getScreenCTM()"
  Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
  Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.h
  Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.idl
Labels: 👀 pr-needs-review

#25359 Terminal: Unveil `/dev/beep` to make the "Audible bell" mode work
  Userland/Applications/Terminal/main.cpp
Labels: 👀 pr-needs-review

#25319 Cherry-pick "LibWeb/DOM: Implement Node.lookupPrefix", reloaded
  Tests/LibWeb/Text/expected/DOM/Node-lookupPrefix.txt
  Tests/LibWeb/Text/input/DOM/Node-lookupPrefix.html
  Userland/Libraries/LibWeb/DOM/Element.cpp
  Userland/Libraries/LibWeb/DOM/Element.h
  Userland/Libraries/LibWeb/DOM/Node.cpp
  Userland/Libraries/LibWeb/DOM/Node.h
  Userland/Libraries/LibWeb/DOM/Node.idl
Labels: 👀 pr-needs-review

#25369 LibWeb+LibWebView+WebContent: Return a named enum from UI event handlers
  Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
  Userland/Libraries/LibWeb/Page/DragAndDropEventHandler.cpp
  Userland/Libraries/LibWeb/Page/DragAndDropEventHandler.h
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
  Userland/Libraries/LibWeb/Page/EventHandler.h
  Userland/Libraries/LibWeb/Page/EventResult.h
  Userland/Libraries/LibWeb/Page/Page.cpp
  Userland/Libraries/LibWeb/Page/Page.h
  Userland/Libraries/LibWebView/ViewImplementation.cpp
  Userland/Libraries/LibWebView/ViewImplementation.h
  Userland/Libraries/LibWebView/WebContentClient.cpp
  Userland/Libraries/LibWebView/WebContentClient.h
  Userland/Services/WebContent/ConnectionFromClient.cpp
  Userland/Services/WebContent/ConnectionFromClient.h
  Userland/Services/WebContent/WebContentClient.ipc
Labels: 👀 pr-needs-review

#25370 Terminal: Set alpha channel to 0xFF
  Userland/Libraries/LibVT/TerminalWidget.cpp
  Userland/Libraries/LibVT/TerminalWidget.h
  Userland/Libraries/LibVT/XtermColors.h
Labels: 👀 pr-needs-review

#25377 Ports/python3: Backport gh-126688: Reinit import lock after fork
  Ports/python3/patches/0007-Backport-gh-126688-Reinit-import-lock-after-fork.patch
  Ports/python3/patches/ReadMe.md
Labels: 👀 pr-needs-review

#25382 Meta: Add more commits and PRs to lb-cherry-picks.py
  Meta/lb-cherry-picks.py
Labels: 👀 pr-needs-review

#25379 Ports: Add lolcat
  Ports/AvailablePorts.md
  Ports/lolcat/package.sh
  Ports/lolcat/patches/0001-Remove-unnecessary-headers.patch
  Ports/lolcat/patches/ReadMe.md
Labels: 👀 pr-needs-review

#25347 Games/BrickGame: Bind `Key_Z` to rotate left
  Userland/Games/BrickGame/BrickGame.cpp
Labels: 👀 pr-needs-review

#25393 Cherry-pick "HTMLEncodingDetection: Use mime type in encoding sniffing"
  Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
  Userland/Libraries/LibWeb/HTML/Parser/HTMLEncodingDetection.cpp
  Userland/Libraries/LibWeb/HTML/Parser/HTMLEncodingDetection.h
Labels: 👀 pr-needs-review

#25395 Cherry-pick "AK: Pass `(Deprecated)FlyString::is_one_of` arguments by reference"
  AK/DeprecatedFlyString.h
  AK/FlyString.h
Labels: 👀 pr-needs-review

#25396 Everywhere: Convert from_string_view -> from_string_literal where static
  Ladybird/Qt/AutoComplete.cpp
  Ladybird/RequestServer/main.cpp
  Tests/AK/TestJSON.cpp
  Userland/Libraries/LibAudio/FlacWriter.cpp
  Userland/Libraries/LibAudio/MultiChannel.h
  Userland/Libraries/LibAudio/VorbisComment.cpp
  Userland/Libraries/LibCore/Process.cpp
  Userland/Libraries/LibCore/ResourceImplementation.cpp
  Userland/Libraries/LibCore/System.cpp
  Userland/Libraries/LibCrypto/ASN1/DER.h
  Userland/Libraries/LibCrypto/Hash/MGF.h
  Userland/Libraries/LibCrypto/Hash/PBKDF2.h
  Userland/Libraries/LibCrypto/Padding/OAEP.h
  Userland/Libraries/LibTLS/Certificate.cpp
  Userland/Libraries/LibWeb/ARIA/RoleType.cpp
  Userland/Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp
  Userland/Libraries/LibWeb/DOM/Element.cpp
  Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.cpp
  Userland/Libraries/LibWeb/WebDriver/Capabilities.cpp
  Userland/Libraries/LibWebView/ViewImplementation.cpp
  Userland/Services/WebDriver/Client.cpp
  Userland/Utilities/aconv.cpp
  Userland/Utilities/animation.cpp
  Userland/Utilities/image.cpp
Labels: 👀 pr-needs-review

#25398 Cherry-pick "LibWeb: Let determine_the_origin() take an optional URL after all", second commit
  Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
  Userland/Libraries/LibWeb/HTML/BrowsingContext.h
  Userland/Libraries/LibWeb/HTML/Navigable.cpp
Labels: 👀 pr-needs-review

#25285 Meta: Add a SSH server to the devcontainer
  .devcontainer/devcontainer.json
Labels: 👀 pr-needs-review

#25401 Cherry-pick "UI/Qt: Process drag-and-drop events through the web view"
  Ladybird/Qt/WebContentView.cpp
  Ladybird/Qt/WebContentView.h
Labels: 👀 pr-needs-review

#25410 LibGfx: Fix crash when calling draw_triangle_wave() offscreen
  Tests/LibGfx/TestPainter.cpp
  Userland/Libraries/LibGfx/Painter.cpp
Labels: 👀 pr-needs-review

#25412 Cherry-pick "LibWeb: Skip DedicatedWorkerGlobalScope-instanceof test"
  Tests/LibWeb/TestConfig.ini
Labels: 👀 pr-needs-review

#25380 Ports: Add open-adventure
  Ports/AvailablePorts.md
  Ports/open-adventure/package.sh
  Ports/open-adventure/patches/0001-Use-libeditline-instead-of-libedit.patch
  Ports/open-adventure/patches/ReadMe.md
Labels: 👀 pr-needs-review

#25414 notify: Add `--launch-url` option
  Base/usr/share/man/man1/notify.md
  Userland/Utilities/CMakeLists.txt
  Userland/Utilities/notify.cpp
Labels: 👀 pr-needs-review

#25419 Meta: Add more commits and PRs to lb-cherry-picks.py
  Meta/lb-cherry-picks.py
Labels: 👀 pr-needs-review

#25421 Cherry-pick "LibWeb: Make MessageEvents from {Window,MessagePort}.postMessage trusted"
  Tests/LibWeb/Text/expected/HTML/MessagePort-MessageEvents-should-be-trusted.txt
  Tests/LibWeb/Text/expected/HTML/Window-MessageEvents-should-be-trusted.txt
  Tests/LibWeb/Text/input/HTML/MessagePort-MessageEvents-should-be-trusted.html
  Tests/LibWeb/Text/input/HTML/Window-MessageEvents-should-be-trusted.html
  Userland/Libraries/LibWeb/HTML/MessagePort.cpp
  Userland/Libraries/LibWeb/HTML/Window.cpp
Labels: 👀 pr-needs-review

#25420 Cherry-pick "LibWeb: Don't discard PostedMessage tasks when closing a worker"
  Tests/LibWeb/TestConfig.ini
  Tests/LibWeb/Text/expected/Worker/Worker-close-after-postMessage.txt
  Tests/LibWeb/Text/input/Worker/Worker-close-after-postMessage.html
  Tests/LibWeb/Text/input/Worker/worker-close-after-postMessage.js
  Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.cpp
Labels: 👀 pr-needs-review

#25425 Cherry-pick "LibWeb: Make HTMLVideoElement part of CanvasImageSource union"
  Tests/LibWeb/Text/expected/canvas/pattern-from-video.txt
  Tests/LibWeb/Text/input/canvas/pattern-from-video.html
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasDrawImage.cpp
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasDrawImage.h
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasDrawImage.idl
  Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
  Userland/Libraries/LibWeb/HTML/HTMLVideoElement.h
Labels: 👀 pr-needs-review

#25424 Cherry-pick "LibWeb/CSS: Bring TokenStream in line with spec"
  Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSMathFunctions.cpp
  Tests/LibWeb/CMakeLists.txt
  Tests/LibWeb/TestCSSTokenStream.cpp
  Userland/Libraries/LibWeb/CSS/Parser/GradientParsing.cpp
  Userland/Libraries/LibWeb/CSS/Parser/MediaParsing.cpp
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp
  Userland/Libraries/LibWeb/CSS/Parser/TokenStream.h
Labels: 👀 pr-needs-review

#25437 AK: Don't define IsFloatingPoint and the FloatingPoint concept in KERNEL
  AK/Concepts.h
  AK/FixedPoint.h
  AK/SIMD.h
  AK/StdLibExtraDetails.h
Labels: 👀 pr-needs-review

#25439 Tests: Port dash-related paths.pdf changes to svg-stroke-styles.html
  Tests/LibWeb/Screenshot/images/svg-stroke-styles-ref.png
  Tests/LibWeb/Screenshot/svg-stroke-styles.html
Labels: 👀 pr-needs-review

#25442 Cherry-pick "LibWeb: Rename 'cross-origin opener policy' to 'opener policy'"
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/DOM/DocumentLoading.h
  Userland/Libraries/LibWeb/Forward.h
  Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
  Userland/Libraries/LibWeb/HTML/CrossOrigin/OpenerPolicy.h
  Userland/Libraries/LibWeb/HTML/CrossOrigin/OpenerPolicyEnforcementResult.h
  Userland/Libraries/LibWeb/HTML/CrossOrigin/Reporting.cpp
  Userland/Libraries/LibWeb/HTML/Navigable.cpp
  Userland/Libraries/LibWeb/HTML/NavigationParams.h
  Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
Labels: 👀 pr-needs-review

#25387 Games/BrickGame: Update man page to indicate `Key_Z` rotates left
  Base/usr/share/man/man6/BrickGame.md
Labels: 👀 pr-needs-review

#25451 Meta: Delete jakt toolchain in delete_toolchain too
  Meta/serenity.sh
Labels: 👀 pr-needs-review

#25455 Calendar: Fix crash on quit via file menu
  Userland/Applications/Calendar/CalendarWidget.cpp
Labels: 👀 pr-needs-review

#25458 LibUnicode+LibWeb: Rework bidirectional_class() API a bit
  Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodeData.cpp
  Tests/LibUnicode/TestUnicodeCharacterTypes.cpp
  Userland/Libraries/LibUnicode/CharacterTypes.cpp
  Userland/Libraries/LibUnicode/CharacterTypes.h
  Userland/Libraries/LibUnicode/Forward.h
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: 👀 pr-needs-review

#25459 Cherry-pick "LibWeb: Layout text chunks based on their Unicode direction"
  Tests/LibWeb/Layout/expected/acid1.txt
  Tests/LibWeb/Layout/expected/block-and-inline/float-left-and-right-with-justified-text-in-between.txt
  Tests/LibWeb/Layout/expected/block-and-inline/float-left-and-right-with-text-in-between.txt
  Tests/LibWeb/Layout/expected/block-and-inline/inline-block-contained-by-abspos-element.txt
  Tests/LibWeb/Layout/expected/div_align.txt
  Tests/LibWeb/Layout/expected/pseudo-element-with-custom-properties-2.txt
  Tests/LibWeb/Screenshot/images/object-fit-position.png
  Tests/LibWeb/Screenshot/images/text-direction-ref.png
  Tests/LibWeb/Screenshot/reference/text-direction-ref.html
  Tests/LibWeb/Screenshot/text-direction.html
  Userland/Libraries/LibGfx/TextLayout.h
  Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/InlineLevelIterator.cpp
  Userland/Libraries/LibWeb/Layout/InlineLevelIterator.h
  Userland/Libraries/LibWeb/Layout/LineBox.cpp
  Userland/Libraries/LibWeb/Layout/LineBox.h
  Userland/Libraries/LibWeb/Layout/LineBoxFragment.cpp
  Userland/Libraries/LibWeb/Layout/LineBoxFragment.h
  Userland/Libraries/LibWeb/Layout/LineBuilder.cpp
  Userland/Libraries/LibWeb/Layout/LineBuilder.h
  Userland/Libraries/LibWeb/Layout/TextNode.cpp
  Userland/Libraries/LibWeb/Layout/TextNode.h
  Userland/Libraries/LibWeb/Painting/DisplayListRecorder.cpp
Labels: 👀 pr-needs-review

#25454 Cherry-pick "LibWeb: Don't let input element placeholders influence line-height"
  Tests/LibWeb/Layout/expected/input-placeholder-with-line-height.txt
  Tests/LibWeb/Layout/expected/input-placeholder.txt
  Tests/LibWeb/Layout/input/input-placeholder-with-line-height.html
  Userland/Libraries/LibWeb/CSS/Default.css
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Labels: 👀 pr-needs-review

#25465 Cherry-pick "LibWeb: Begin implementing FontFaceSet.prototype.load"
  Tests/LibWeb/Text/expected/css/FontFaceSet-load.txt
  Tests/LibWeb/Text/input/css/FontFaceSet-load.html
  Userland/Libraries/LibWeb/CSS/FontFace.h
  Userland/Libraries/LibWeb/CSS/FontFaceSet.cpp
Labels: 👀 pr-needs-review

#25467 Cherry-pick "LibWeb: Do not resolve inline block height early if height is definite"
  Tests/LibWeb/Layout/expected/svg/svg-inside-inline-block.txt
  Tests/LibWeb/Layout/input/svg/svg-inside-inline-block.html
  Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Labels: 👀 pr-needs-review

#25474 Meta: Make LibIDL depend on LibCoreMinimal in GN build
  Meta/gn/secondary/Userland/Libraries/LibIDL/BUILD.gn
Labels: 👀 pr-needs-review

#25483 Documentation: Make the SerenityOS Patterns documentation more idiomatic
  Documentation/Patterns.md
Labels: 👀 pr-needs-review

#25487 Cherry-pick "LibWeb: Use a Unicode text segmenter to select words on double-click"
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
  Userland/Libraries/LibWeb/Page/EventHandler.h
Labels: 👀 pr-needs-review

#25491 Meta: Add more commits and PRs to lb-cherry-picks.py
  Meta/lb-cherry-picks.py
Labels: 👀 pr-needs-review

#25490 Cherry-pick "LibWeb: Iterate over text chunks using a grapheme-aware segmenter"
  Tests/LibWeb/Layout/expected/multi-code-point-graphemes.txt
  Tests/LibWeb/Layout/input/multi-code-point-graphemes.html
  Userland/Libraries/LibWeb/Layout/TextNode.cpp
  Userland/Libraries/LibWeb/Layout/TextNode.h
Labels: 👀 pr-needs-review

#25495 LibUnicode: Fix a spec link in a comment
  Userland/Libraries/LibUnicode/Segmentation.cpp
Labels: 👀 pr-needs-review

#25498 Utilities/markdown-check: Use `ByteString` (instead of `String`) for file…
  Userland/Utilities/markdown-check.cpp
Labels: 👀 pr-needs-review

#25509 Meta: Remove Ladybird dep on LibGUI in GN build
  Meta/gn/secondary/Ladybird/BUILD.gn
Labels: 👀 pr-needs-review

#25505 LibCore: Make `get_salt()` fallible so we get an error instead of crashing
  Userland/Libraries/LibCore/Account.cpp
  Userland/Libraries/LibCore/Account.h
  Userland/Utilities/passwd.cpp
Labels: 👀 pr-needs-review

#25515 Cherry-pick "LibWeb: Compute mimetype when loading a document"
  Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
Labels: 👀 pr-needs-review

#25504 Utilities/cut: Show error instead of crashing for invalid UTF-8 lines
  Userland/Utilities/cut.cpp
Labels: 👀 pr-needs-review

#25517 Cherry-pick "LibIPC: Pass AK::Duration by value over IPC"
  Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
Labels: 👀 pr-needs-review

#25518 Cherry-pick "LibWeb: Implement indexed property support for HTML::Storage"
  Tests/LibWeb/Text/expected/localStorage.txt
  Tests/LibWeb/Text/input/localStorage.html
  Userland/Libraries/LibWeb/HTML/Storage.cpp
  Userland/Libraries/LibWeb/HTML/Storage.h
Labels: 👀 pr-needs-review

#25519 Meta: Don't use the `gtk,gl=on` display backend with NVIDIA graphics
  Meta/run.py
Labels: 👀 pr-needs-review
