Repository SerenityOS/serenity, pull requests merged in 2024-05, with the labels that each got.

#24175 LibCore: Don't use designated initializers for struct cmsghdr
  Userland/Libraries/LibCore/Socket.cpp
Labels: 👀 pr-needs-review

#23442 Run: Don't wait for child process to end when adding it to history
  Userland/Applications/Run/RunWindow.cpp
  Userland/Applications/Run/RunWindow.h
Labels: 👀 pr-needs-review

#24174 Ladybird+LibWebView: Introduce a cache for cookies backed by SQL storage
  Ladybird/AppKit/Application/ApplicationDelegate.h
  Ladybird/AppKit/Application/ApplicationDelegate.mm
  Ladybird/Qt/main.cpp
  Userland/Applications/Browser/main.cpp
  Userland/Libraries/LibWebView/CookieJar.cpp
  Userland/Libraries/LibWebView/CookieJar.h
  Userland/Utilities/headless-browser.cpp
Labels: 👀 pr-needs-review

#24177 LibWeb: Implement XMLHttpRequest.responseURL
  Tests/LibWeb/Text/expected/XHR/XMLHttpRequest-responseURL.txt
  Tests/LibWeb/Text/input/XHR/XMLHttpRequest-responseURL.html
  Userland/Libraries/LibWeb/XHR/XMLHttpRequest.cpp
  Userland/Libraries/LibWeb/XHR/XMLHttpRequest.h
  Userland/Libraries/LibWeb/XHR/XMLHttpRequest.idl
Labels: 👀 pr-needs-review

#24180 LibJS: Merge CallFrame into ExecutionContext
  Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
  Userland/Libraries/LibJS/Bytecode/Interpreter.h
  Userland/Libraries/LibJS/Heap/Heap.cpp
  Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
  Userland/Libraries/LibJS/Runtime/AsyncGenerator.cpp
  Userland/Libraries/LibJS/Runtime/AsyncGenerator.h
  Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
  Userland/Libraries/LibJS/Runtime/ExecutionContext.cpp
  Userland/Libraries/LibJS/Runtime/ExecutionContext.h
  Userland/Libraries/LibJS/Runtime/GeneratorObject.cpp
  Userland/Libraries/LibJS/Runtime/GeneratorObject.h
  Userland/Libraries/LibJS/Runtime/ShadowRealm.cpp
  Userland/Libraries/LibJS/Runtime/VM.cpp
  Userland/Libraries/LibJS/SourceTextModule.cpp
Labels: 👀 pr-needs-review

#24178 CI: Use a local GitHub Action to setup installed packages
  .github/actions/setup/action.yml
  .github/workflows/cmake.yml
  .github/workflows/pvs-studio-static-analysis.yml
  .github/workflows/serenity-js-artifacts.yml
  .github/workflows/sonar-cloud-static-analysis.yml
Labels: 👀 pr-needs-review

#24187 LibWeb: Use GCPtr for Element::layout_node
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Element.cpp
  Userland/Libraries/LibWeb/DOM/Element.h
  Userland/Libraries/LibWeb/SVG/SVGCircleElement.cpp
  Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
Labels: 👀 pr-needs-review

#24194 LibWeb+LibJS: Skip function environment allocation if possible
  Userland/Libraries/LibJS/AST.cpp
  Userland/Libraries/LibJS/AST.h
  Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
  Userland/Libraries/LibJS/Parser.cpp
  Userland/Libraries/LibJS/Parser.h
  Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
  Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
  Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h
  Userland/Libraries/LibJS/Runtime/FunctionConstructor.cpp
  Userland/Libraries/LibJS/SourceTextModule.cpp
  Userland/Libraries/LibWeb/DOM/EventTarget.cpp
  Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
Labels: 👀 pr-needs-review

#24196 LibGfx/WebP: Rename two variables to be a bit clearer
  Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossless.cpp
Labels: 👀 pr-needs-review

#24202 LibWeb: Implement Element.outerHTML setter
  Tests/LibWeb/Text/expected/HTML/set-outerHTML.txt
  Tests/LibWeb/Text/input/HTML/set-outerHTML.html
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: 👀 pr-needs-review

#24192 LibGUI: Add tooltips to DynamicWidgetContainer control buttons
  Userland/Libraries/LibGUI/DynamicWidgetContainerControls.gml
Labels: 👀 pr-needs-review

#24201 LibWeb: Handle non-object JSON in XMLHttpRequest response
  Tests/LibWeb/Text/expected/XHR/XMLHttpRequest-response-is-json-number.txt
  Tests/LibWeb/Text/input/XHR/XMLHttpRequest-response-is-json-number.html
  Userland/Libraries/LibWeb/XHR/XMLHttpRequest.cpp
Labels: 👀 pr-needs-review

#24217 LibPDF: Added empty read check to parse_hex_string
  Userland/Libraries/LibPDF/Parser.cpp
Labels: 👀 pr-needs-review

#24223 LibWeb: Fix null layout node dereference in SVGMaskable
  Userland/Libraries/LibWeb/Painting/SVGMaskable.cpp
Labels: 👀 pr-needs-review

#24226 LibWeb: Log error instead of crashing if stacking context painted twice
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Labels: 👀 pr-needs-review

#23721 LibJS: Truncate roundingIncrement before range check
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
  Userland/Libraries/LibJS/Runtime/Temporal/DurationPrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/InstantPrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
Labels: ✅ pr-community-approved

#24224 Ladybird/Qt: Introduce a hamburger menu and use by default
  Ladybird/Icons/hamburger.tvg
  Ladybird/Qt/BrowserWindow.cpp
  Ladybird/Qt/BrowserWindow.h
  Ladybird/Qt/Settings.cpp
  Ladybird/Qt/Settings.h
  Ladybird/Qt/Tab.cpp
  Ladybird/Qt/Tab.h
  Ladybird/Qt/ladybird.qrc
Labels: 👀 pr-needs-review

#24213 LibJS: Skip some declarative env allocations in function instantiation
  Userland/Libraries/LibJS/AST.cpp
  Userland/Libraries/LibJS/AST.h
  Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Labels: 👀 pr-needs-review

#24235 Ladybird: Remove menu indicator on hamburger icon
  Ladybird/Qt/Tab.cpp
Labels: 👀 pr-needs-review

#24205 Ladybird: Update Android build to work with current LibWebView/LibCore
  Documentation/AndroidStudioConfiguration.md
  Ladybird/Android/build.gradle.kts
  Ladybird/Android/gradle/wrapper/gradle-wrapper.properties
  Ladybird/Android/src/main/cpp/ALooperEventLoopImplementation.cpp
  Ladybird/Android/src/main/cpp/ALooperEventLoopImplementation.h
  Ladybird/Android/src/main/cpp/ImageDecoderService.cpp
  Ladybird/Android/src/main/cpp/LadybirdActivity.cpp
  Ladybird/Android/src/main/cpp/LadybirdServiceBase.h
  Ladybird/Android/src/main/cpp/LadybirdServiceBaseJNI.cpp
  Ladybird/Android/src/main/cpp/RequestServerService.cpp
  Ladybird/Android/src/main/cpp/TimerExecutorService.cpp
  Ladybird/Android/src/main/cpp/WebContentService.cpp
  Ladybird/Android/src/main/cpp/WebContentService.h
  Ladybird/Android/src/main/cpp/WebContentServiceJNI.cpp
  Ladybird/Android/src/main/cpp/WebViewImplementationNative.cpp
  Ladybird/Android/src/main/cpp/WebViewImplementationNative.h
  Ladybird/Android/src/main/cpp/WebViewImplementationNativeJNI.cpp
  Ladybird/Android/src/main/java/org/serenityos/ladybird/LadybirdServiceBase.kt
  Ladybird/Android/src/main/java/org/serenityos/ladybird/LadybirdServiceConnection.kt
  Ladybird/Android/src/main/java/org/serenityos/ladybird/TimerExecutorService.kt
  Ladybird/Android/src/main/java/org/serenityos/ladybird/WebContentService.kt
  Ladybird/Android/src/main/java/org/serenityos/ladybird/WebView.kt
  Ladybird/Android/src/main/java/org/serenityos/ladybird/WebViewImplementation.kt
  Ladybird/ImageDecoder/CMakeLists.txt
  Meta/Azure/Lagom.yml
Labels: 👀 pr-needs-review

#24232 CI: Run `brew update` before installing macOS packages
  .github/actions/setup/action.yml
Labels: 👀 pr-needs-review

#24234 LibWeb: Ignore setting zero, negative, or non-finite CRC2D.lineWidths
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasPathDrawingStyles.h
Labels: 👀 pr-needs-review

#24242 Ladybird: Add the "Debug" category back to the menubar
  Ladybird/Qt/BrowserWindow.cpp
Labels: 👀 pr-needs-review

#24169 Meta+Documentation+Ports: Move from C++20 to C++23
  Base/home/anon/Source/little/Makefile
  Base/res/devel/templates/cpp-basic.postcreate
  Base/res/devel/templates/cpp-library.postcreate
  CONTRIBUTING.md
  Documentation/BuildInstructions.md
  Documentation/BuildInstructionsLadybird.md
  Documentation/Links.md
  Documentation/NvimConfiguration.md
  Documentation/QtCreatorConfiguration.md
  Documentation/VSCodeConfiguration.md
  Ladybird/Android/build.gradle.kts
  Meta/CMake/common_compile_options.cmake
  Meta/gn/build/BUILD.gn
  Ports/OpenJDK/patches/0002-make-Build-with-c-23-when-targeting-serenity.patch
  Ports/OpenJDK/patches/ReadMe.md
  Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch
  Ports/stpuzzles/package.sh
  Ports/xmp-cli/patches/0001-Add-support-for-Serenity-LibAudio.patch
Labels: 👀 pr-needs-review

#24189 Chess: Improve PGN importing
  Userland/Games/Chess/ChessWidget.cpp
  Userland/Games/Chess/ChessWidget.h
  Userland/Games/Chess/main.cpp
Labels: 👀 pr-needs-review

#24243 LibGfx+LibWeb: Allow inexact size lookups when requesting scaled fonts
  Userland/Libraries/LibGfx/Font/BitmapFont.cpp
  Userland/Libraries/LibGfx/Font/BitmapFont.h
  Userland/Libraries/LibGfx/Font/Font.h
  Userland/Libraries/LibGfx/Font/ScaledFont.cpp
  Userland/Libraries/LibGfx/Font/ScaledFont.h
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
  Userland/Libraries/LibWeb/Layout/Node.h
  Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
  Userland/Libraries/LibWeb/Painting/CommandExecutorCPU.cpp
  Userland/Libraries/LibWeb/Painting/CommandExecutorGPU.cpp
  Userland/Libraries/LibWeb/Painting/CommandList.cpp
  Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp
Labels: 👀 pr-needs-review

#24228 LibWeb: Do not consume scroll event in PaintableBox without overflow
  Tests/LibWeb/Ref/box-without-scrollable-overflow-should-not-consume-scroll-events.html
  Tests/LibWeb/Ref/reference/box-without-scrollable-overflow-should-not-consume-scroll-events-ref.html
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Labels: 👀 pr-needs-review

#24251 Tests/LibGfx: Add a test for bilevel images with only required tags
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/tiff/ccitt3_no_tags.tiff
Labels: ✅ pr-community-approved

#24249 LibGfx/WebPLossless: Update spec comments with newest version of spec
  Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossless.cpp
Labels: 👀 pr-needs-review

#24247 LibGfx/WebPWriter: Implement ICC color profile data writing
  Userland/Libraries/LibGfx/ImageFormats/WebPWriter.cpp
Labels: ✅ pr-community-approved

#24246 LibGfx/WebPWriter: Use one-element huffman tree for opaque images
  Userland/Libraries/LibGfx/ImageFormats/WebPWriter.cpp
Labels: 👀 pr-needs-review

#24245 TestImageWriter: Add tests for most other image writers
  Tests/LibGfx/TestImageWriter.cpp
Labels: ✅ pr-community-approved

#24227 Ladybird: Add Wikipedia search button to newtab.html
  Base/res/ladybird/newtab.html
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#24253 CI: Use common cache restore and cache save action on GitHub Actions
  .github/actions/cache-restore/action.yml
  .github/actions/cache-save/action.yml
  .github/workflows/cmake.yml
  .github/workflows/libjs-test262.yml
  .github/workflows/pvs-studio-static-analysis.yml
  .github/workflows/serenity-js-artifacts.yml
  .github/workflows/sonar-cloud-static-analysis.yml
  .github/workflows/wasm.yml
Labels: 👀 pr-needs-review

#24166 Documentation: Describe how to use add_libweb_test.py for Text tests
  Documentation/Browser/Patterns.md
Labels: 👀 pr-needs-review

#24209 HexEditor: Move endianness selector to Value Inspector panel
  Userland/Applications/HexEditor/HexEditorWidget.cpp
  Userland/Applications/HexEditor/HexEditorWidget.gml
  Userland/Applications/HexEditor/HexEditorWidget.h
  Userland/Applications/HexEditor/ValueInspectorModel.h
Labels: 👀 pr-needs-review

#24218 AK: Replace FP math in `is_power_of` with a purely integral algorithm
  AK/IntegralMath.h
  Tests/AK/TestIntegerMath.cpp
Labels: 👀 pr-needs-review

#24231 LibWeb/SVG: Stub SVGTransform functions
  Userland/Libraries/LibWeb/SVG/SVGTransform.cpp
  Userland/Libraries/LibWeb/SVG/SVGTransform.h
  Userland/Libraries/LibWeb/SVG/SVGTransform.idl
Labels: 👀 pr-needs-review, ✅ pr-community-approved

#24257 Ladybird: Ensure hamburger menu is placed within the browser window
  Ladybird/Qt/BrowserWindow.cpp
  Ladybird/Qt/BrowserWindow.h
  Ladybird/Qt/Tab.h
Labels: 👀 pr-needs-review

#24067 LibELF: Make orders in which we store/call things explicit
  Userland/DynamicLoader/main.cpp
  Userland/Libraries/LibELF/DynamicLinker.cpp
  Userland/Libraries/LibELF/DynamicLinker.h
  Userland/Libraries/LibELF/DynamicLoader.cpp
  Userland/Libraries/LibELF/DynamicLoader.h
Labels: 👀 pr-needs-review

#24259 Meta: Remove check-symbols.sh
  .github/workflows/cmake.yml
  Meta/check-symbols.sh
  Meta/lint-ci.sh
Labels: 👀 pr-needs-review

#24271 LibWeb: Don't try to click a form image until it has loaded
  Tests/LibWeb/Text/input/HTML/form-image-submission.html
Labels: 👀 pr-needs-review

#24274 LibChess: Fix crash when importing PGN
  Userland/Games/Chess/ChessWidget.cpp
  Userland/Libraries/LibChess/Chess.cpp
Labels: 👀 pr-needs-review

#24282 LibWeb/Tests: Add a layout test for insertAdjacentHTML
  Tests/LibWeb/Layout/expected/Element-insertAdjacentHTML.txt
  Tests/LibWeb/Layout/input/Element-insertAdjacentHTML.html
Labels: 👀 pr-needs-review

#24261 LibGfx/GIF: Bag of small tweaks
  Userland/Libraries/LibGfx/ImageFormats/GIFLoader.cpp
Labels: ✅ pr-community-approved

#24283 LibJS: Manually limit the recursion depth in Proxy
  Userland/Libraries/LibJS/Runtime/ProxyObject.cpp
Labels: 👀 pr-needs-review

#24266 LibWebView: Add Wikipedia to builtin search engines list
  Userland/Libraries/LibWebView/SearchEngine.cpp
Labels: 👀 pr-needs-review

#24286 LibJS: Delete named_evaluation_if_anonymous_function()
  Userland/Libraries/LibJS/AST.cpp
  Userland/Libraries/LibJS/AST.h
  Userland/Libraries/LibJS/Runtime/VM.cpp
  Userland/Libraries/LibJS/Runtime/VM.h
Labels: 👀 pr-needs-review

#24285 CI: Remove the Sonar Cloud and PVS Studio workflow
  .github/workflows/pvs-studio-static-analysis.yml
  .github/workflows/sonar-cloud-static-analysis.yml
  Documentation/Links.md
  README.md
Labels: 👀 pr-needs-review

#24173 Base: Add more emoji
  Base/res/emoji/U+1F93D.png
  Base/res/emoji/U+1F93D_U+200D_U+2640.png
  Base/res/emoji/U+1F93D_U+200D_U+2642.png
  Base/res/emoji/U+1F9A8.png
  Meta/emoji-file-list.txt
Labels: 👀 pr-needs-review

#24289 LibWeb: Implement AudioBuffer.copyFromChannel
  Tests/LibWeb/Text/expected/WebAudio/AudioBuffer-copyFromChannel.txt
  Tests/LibWeb/Text/input/WebAudio/AudioBuffer-copyFromChannel.html
  Userland/Libraries/LibWeb/WebAudio/AudioBuffer.cpp
Labels: 👀 pr-needs-review

#24299 Kernel: Run clang-format
  Kernel/Bus/VirtIO/Device.cpp
  Kernel/Devices/GPU/Console/VGATextModeConsole.cpp
Labels: 👀 pr-needs-review

#24302 Browser: Pledge thread for FilePicker
  Userland/Applications/Browser/main.cpp
Labels: 👀 pr-needs-review

#24304 LibLocale: Move includes below `#pragma once` in generated headers
  Meta/Lagom/Tools/CodeGenerators/LibLocale/GenerateNumberFormatData.cpp
  Meta/Lagom/Tools/CodeGenerators/LibLocale/GeneratePluralRulesData.cpp
Labels: 👀 pr-needs-review

#24309 LibWeb: Implement URL.parse
  Tests/LibWeb/Text/expected/URL/url.txt
  Tests/LibWeb/Text/input/URL/url.html
  Userland/Libraries/LibWeb/DOMURL/DOMURL.cpp
  Userland/Libraries/LibWeb/DOMURL/DOMURL.h
  Userland/Libraries/LibWeb/DOMURL/DOMURL.idl
Labels: 👀 pr-needs-review

#24307 MouseSettings: Only allow valid cursor themes
  Userland/Applications/MouseSettings/ThemeWidget.cpp
Labels: 👀 pr-needs-review

#24316 LibJS: Join locals, constants and registers into single vector
  Userland/Libraries/LibJS/AST.cpp
  Userland/Libraries/LibJS/Bytecode/Generator.cpp
  Userland/Libraries/LibJS/Bytecode/Instruction.cpp
  Userland/Libraries/LibJS/Bytecode/Instruction.h
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
  Userland/Libraries/LibJS/Bytecode/Interpreter.h
  Userland/Libraries/LibJS/Bytecode/Op.h
  Userland/Libraries/LibJS/Bytecode/Operand.h
  Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
  Userland/Libraries/LibJS/Runtime/ExecutionContext.cpp
  Userland/Libraries/LibJS/Runtime/ExecutionContext.h
Labels: 👀 pr-needs-review

#24320 LibWeb: Stub out FontFaceSet.status and .ready attributes
  Userland/Libraries/LibWeb/CSS/FontFaceSet.cpp
  Userland/Libraries/LibWeb/CSS/FontFaceSet.h
  Userland/Libraries/LibWeb/CSS/FontFaceSet.idl
Labels: 👀 pr-needs-review

#24315 LibGfx: Correctly round values when computing the luminosity of a Color
  Tests/LibGfx/CMakeLists.txt
  Tests/LibGfx/TestColor.cpp
  Userland/Libraries/LibGfx/Color.h
Labels: ✅ pr-community-approved

#24317 LibWeb: Specify the correct argument type in IDL for AbortSignal::any()
  Userland/Libraries/LibWeb/DOM/AbortSignal.cpp
  Userland/Libraries/LibWeb/DOM/AbortSignal.h
  Userland/Libraries/LibWeb/DOM/AbortSignal.idl
Labels: 👀 pr-needs-review

#24323 LibJS: Replace SetLocal instruction usage with Mov
  Userland/Libraries/LibJS/Bytecode/Generator.cpp
  Userland/Libraries/LibJS/Bytecode/Instruction.h
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
  Userland/Libraries/LibJS/Bytecode/Op.h
Labels: 👀 pr-needs-review

#24321 LibJS/Bytecode: Add environment coordinate caching to SetVariable
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
  Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.cpp
  Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.h
Labels: 👀 pr-needs-review

#24312 LibWeb: Implement Document.dir
  Tests/LibWeb/Text/expected/DOM/Document-dir.txt
  Tests/LibWeb/Text/input/DOM/Document-dir.html
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/DOM/Document.idl
Labels: 👀 pr-needs-review

#24319 LibWeb: Support loading FontFaces constructed with binary data
  Tests/LibWeb/Text/expected/css/FontFace-binary-data.txt
  Tests/LibWeb/Text/input/css/FontFace-binary-data.html
  Userland/Libraries/LibWeb/CSS/FontFace.cpp
  Userland/Libraries/LibWeb/CSS/FontFace.h
  Userland/Libraries/LibWeb/CSS/FontFace.idl
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/CSS/Parser/Parser.h
  Userland/Libraries/LibWeb/HTML/EventLoop/Task.h
Labels: 👀 pr-needs-review

#24160 Kernel/Storage: Remove ATA IDE support
  Base/usr/share/man/man7/boot_parameters.md
  Kernel/Arch/init.cpp
  Kernel/Arch/x86_64/ISABus/IDEController.cpp
  Kernel/Arch/x86_64/ISABus/IDEController.h
  Kernel/Arch/x86_64/PCI/IDELegacyModeController.cpp
  Kernel/Arch/x86_64/PCI/IDELegacyModeController.h
  Kernel/Boot/CommandLine.cpp
  Kernel/Boot/CommandLine.h
  Kernel/CMakeLists.txt
  Kernel/Devices/Storage/AHCI/ATADevice.cpp
  Kernel/Devices/Storage/AHCI/ATADevice.h
  Kernel/Devices/Storage/AHCI/ATADiskDevice.cpp
  Kernel/Devices/Storage/AHCI/ATADiskDevice.h
  Kernel/Devices/Storage/AHCI/Controller.cpp
  Kernel/Devices/Storage/AHCI/Controller.h
  Kernel/Devices/Storage/AHCI/Definitions.h
  Kernel/Devices/Storage/AHCI/InterruptHandler.cpp
  Kernel/Devices/Storage/AHCI/InterruptHandler.h
  Kernel/Devices/Storage/AHCI/Port.cpp
  Kernel/Devices/Storage/AHCI/Port.h
  Kernel/Devices/Storage/ATA/ATAController.cpp
  Kernel/Devices/Storage/ATA/ATAController.h
  Kernel/Devices/Storage/ATA/ATADevice.h
  Kernel/Devices/Storage/ATA/ATAPort.cpp
  Kernel/Devices/Storage/ATA/ATAPort.h
  Kernel/Devices/Storage/ATA/Definitions.h
  Kernel/Devices/Storage/ATA/GenericIDE/Channel.cpp
  Kernel/Devices/Storage/ATA/GenericIDE/Channel.h
  Kernel/Devices/Storage/ATA/GenericIDE/Controller.cpp
  Kernel/Devices/Storage/ATA/GenericIDE/Controller.h
  Kernel/Devices/Storage/StorageManagement.cpp
  Kernel/Devices/Storage/StorageManagement.h
  Meta/gn/secondary/Kernel/BUILD.gn
Labels: 👀 pr-needs-review

#24287 AK: Add stack size fixup for musl libc
  AK/StackInfo.cpp
Labels: 👀 pr-needs-review

#24007 nix-shell: Disable gcc hardening to be able to build toolchain
  Toolchain/default.nix
Labels: stale, 👀 pr-needs-review

#24297 Base: Add more emoji (Emoji 16 edition)
  Base/home/anon/Documents/emoji-serenity.txt
  Base/res/emoji/U+1F1E8_U+1F1F6.png
  Base/res/emoji/U+1FA89.png
  Base/res/emoji/U+1FA8F.png
  Base/res/emoji/U+1FABE.png
  Base/res/emoji/U+1FAC6.png
  Base/res/emoji/U+1FADC.png
  Base/res/emoji/U+1FADF.png
  Base/res/emoji/U+1FAE9.png
  Meta/emoji-file-list.txt
Labels: 👀 pr-needs-review

#24280 Kernel/x86: Bake the Prekernel and the Kernel into one image
  Kernel/Arch/init.cpp
  Kernel/Boot/BootInfo.h
  Kernel/CMakeLists.txt
  Kernel/Memory/MemoryManager.cpp
  Kernel/Prekernel/CMakeLists.txt
  Kernel/Prekernel/Prekernel.h
  Kernel/Prekernel/init.cpp
  Kernel/Prekernel/linker.ld
  Meta/debug-kernel.sh
  Meta/run.py
Labels: 👀 pr-needs-review

#24267 Demos: Add sleep option to CatDog
  Base/res/icons/16x16/catdog-sleeping.png
  Base/res/icons/16x16/catdog-wake-up.png
  Userland/Demos/CatDog/CatDog.cpp
  Userland/Demos/CatDog/CatDog.h
  Userland/Demos/CatDog/main.cpp
Labels: 👀 pr-needs-review

#24331 Tests/TestImageWriter: Remove is_gif parameter again
  Tests/LibGfx/TestImageWriter.cpp
Labels: ci-flakiness, ✅ pr-community-approved

#24333 LibGUI: Don't crash when rendering a collapsible toolbar with no items
  Userland/Libraries/LibGUI/Toolbar.cpp
Labels: 👀 pr-needs-review

#24341 LibWeb: Use correct IDL definition for CanvasImageData methods
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasImageData.h
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasImageData.idl
  Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
  Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.h
Labels: 👀 pr-needs-review

#24340 LibWeb: Implement the `HTMLOptionElement.form` attribute
  Tests/LibWeb/Text/expected/HTML/HTMLOptionElement-form.txt
  Tests/LibWeb/Text/input/HTML/HTMLOptionElement-form.html
  Userland/Libraries/LibWeb/HTML/HTMLOptionElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLOptionElement.h
  Userland/Libraries/LibWeb/HTML/HTMLOptionElement.idl
Labels: 👀 pr-needs-review

#24338 LibWeb: Use correct type for `MessageEventInit.ports`
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
  Userland/Libraries/LibWeb/HTML/MessageEvent.cpp
  Userland/Libraries/LibWeb/HTML/MessageEvent.h
  Userland/Libraries/LibWeb/HTML/MessageEvent.idl
  Userland/Libraries/LibWeb/HTML/MessagePort.cpp
  Userland/Libraries/LibWeb/HTML/Window.cpp
Labels: 👀 pr-needs-review

#24336 Toolchain: Set cpu_family in meson cross files to SERENITY_ARCH
  Toolchain/CMake/meson-cross-file-Clang.txt.in
  Toolchain/CMake/meson-cross-file-GNU.txt.in
Labels: ci-flakiness, 👀 pr-needs-review

#24343 LibWeb: Flesh out `DOMTokenList::supports()` implementation
  Tests/LibWeb/Text/expected/DOMTokenList-supports.txt
  Tests/LibWeb/Text/input/DOMTokenList-supports.html
  Userland/Libraries/LibWeb/DOM/DOMTokenList.cpp
Labels: 👀 pr-needs-review

#24353 LibWeb: Return NonnullGCPtr<DOMTokenList> from `relList` getters
  Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.h
  Userland/Libraries/LibWeb/HTML/HTMLAreaElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLAreaElement.h
  Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLFormElement.h
  Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLLinkElement.h
Labels: 👀 pr-needs-review

#24344 LibWeb: Implement the `HTMLOutputElement.htmlFor` attribute
  Tests/LibWeb/Text/expected/HTML/HTMLOutputElement-htmlfor.txt
  Tests/LibWeb/Text/input/HTML/HTMLOutputElement-htmlfor.html
  Userland/Libraries/LibWeb/HTML/HTMLOutputElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLOutputElement.h
  Userland/Libraries/LibWeb/HTML/HTMLOutputElement.idl
Labels: ✅ pr-community-approved

#24359 LibWeb: Implement the `labels` attribute for all labelable elements
  Tests/LibWeb/Text/expected/HTML/HTMLElement-labels.txt
  Tests/LibWeb/Text/input/HTML/HTMLElement-labels.html
  Userland/Libraries/LibWeb/HTML/HTMLButtonElement.idl
  Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLElement.h
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.idl
  Userland/Libraries/LibWeb/HTML/HTMLMeterElement.idl
  Userland/Libraries/LibWeb/HTML/HTMLOutputElement.idl
  Userland/Libraries/LibWeb/HTML/HTMLProgressElement.idl
  Userland/Libraries/LibWeb/HTML/HTMLSelectElement.idl
  Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.idl
Labels: 👀 pr-needs-review

#24362 LibJS: Prepare yield object before re-routing it through finally
  Userland/Libraries/LibJS/Bytecode/Generator.h
  Userland/Libraries/LibJS/Bytecode/Instruction.h
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
  Userland/Libraries/LibJS/Bytecode/Interpreter.h
  Userland/Libraries/LibJS/Bytecode/Op.h
  Userland/Libraries/LibJS/Tests/try-return-finally.js
Labels: 👀 pr-needs-review

#24354 LibJS+AK: Fix integer overflow UB on (any Int32 - -2147483648)
  AK/Checked.h
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
  Userland/Libraries/LibJS/Tests/math/integer-overflow-basic.js
Labels: 👀 pr-needs-review

#24360 AK: Don't put element count next to heap-allocated data in FixedArray
  AK/FixedArray.h
Labels: 👀 pr-needs-review

#24368 LibGfx/GIF: Small tweaks to ease the introduction of animated GIFs
  Userland/Libraries/LibGfx/ImageFormats/GIFWriter.cpp
Labels: ✅ pr-community-approved

#24367 LibWeb: Factor out IDL generator using namespace hack into a function
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Labels: 👀 pr-needs-review

#24369 LibWeb: Implement scrollIntoView with 'center' block position
  Tests/LibWeb/Text/expected/scroll-into-view-center.txt
  Tests/LibWeb/Text/input/scroll-into-view-center.html
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: 👀 pr-needs-review

#24372 LibWeb: Log a FIXME when parsing fragments for XML documents
  Userland/Libraries/LibWeb/DOMParsing/InnerHTML.cpp
Labels: 👀 pr-needs-review

#24350 LibWeb: Add a few missing visits to m_rel_list members
  Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.h
  Userland/Libraries/LibWeb/HTML/HTMLAreaElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLAreaElement.h
  Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#24383 LibJS: Remove an old VERIFY from break handling in try-finally blocks
  Userland/Libraries/LibJS/Bytecode/Generator.cpp
  Userland/Libraries/LibJS/Tests/try-finally-break.js
Labels: 👀 pr-needs-review

#24388 LibWeb: Implement the `MouseEvent.relatedTarget` attribute
  Tests/LibWeb/Text/expected/UIEvents/mouse-events.txt
  Tests/LibWeb/Text/input/UIEvents/mouse-events.html
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/UIEvents/MouseEvent.cpp
  Userland/Libraries/LibWeb/UIEvents/MouseEvent.h
  Userland/Libraries/LibWeb/UIEvents/MouseEvent.idl
Labels: 👀 pr-needs-review

#24390 LibJS/Bytecode: Add dedicated instruction for getting `length` property
  Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
  Userland/Libraries/LibJS/Bytecode/Generator.cpp
  Userland/Libraries/LibJS/Bytecode/Instruction.h
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
  Userland/Libraries/LibJS/Bytecode/Op.h
Labels: 👀 pr-needs-review

#24393 LibThreading: Remove extra spammy log message upon starting a thread
  Userland/Libraries/LibThreading/Thread.cpp
Labels: 👀 pr-needs-review

#24380 LibGfx/GIF+animation: Support animated GIFs
  Userland/Libraries/LibGfx/ImageFormats/GIFWriter.cpp
  Userland/Libraries/LibGfx/ImageFormats/GIFWriter.h
  Userland/Utilities/animation.cpp
Labels: ✅ pr-community-approved

#24399 LibJS: Use a local variable for arguments object when possible
  Userland/Libraries/LibJS/Bytecode/Generator.cpp
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
  Userland/Libraries/LibJS/Bytecode/Op.h
  Userland/Libraries/LibJS/Parser.cpp
  Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Labels: 👀 pr-needs-review

#24392 RequestServer: Account for null sockets in recreate_socket_if_needed()
  Userland/Services/RequestServer/ConnectionCache.h
Labels: 👀 pr-needs-review

#24403 LibJS: Do not count arguments as env binding when local variable is used
  Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Labels: 👀 pr-needs-review

#24409 Revert "LibCore: Add Core::deferred_invoke_if(F, Condition)"
  Userland/Libraries/LibCore/DeferredInvocationContext.h
  Userland/Libraries/LibCore/EventLoop.cpp
  Userland/Libraries/LibCore/EventLoop.h
  Userland/Libraries/LibCore/ThreadEventQueue.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#24408 LibCrypto: Don't compute 2*N remainders in Adler32
  Userland/Libraries/LibCrypto/Checksum/Adler32.cpp
Labels: 👀 pr-needs-review

#24405 LibJS: Get `this` from execution context for non-arrow functions
  Userland/Libraries/LibJS/AST.cpp
  Userland/Libraries/LibJS/AST.h
  Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
  Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
  Userland/Libraries/LibJS/Parser.cpp
  Userland/Libraries/LibJS/Parser.h
  Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
  Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
  Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h
  Userland/Libraries/LibJS/Runtime/FunctionConstructor.cpp
  Userland/Libraries/LibJS/SourceTextModule.cpp
  Userland/Libraries/LibWeb/DOM/EventTarget.cpp
  Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
Labels: 👀 pr-needs-review

#24415 Kernel: Actually set physical base pointer correctly in prekernel stage
  Kernel/Prekernel/init.cpp
Labels: 👀 pr-needs-review

#24326 Ports/file: Build host version to ensure we can properly cross compile
  Ports/file/package.sh
Labels: 👀 pr-needs-review

#24417 IDLGenerators: Use spec-compliant algorithm to parse integer values
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
  Tests/LibWeb/Text/expected/HTML/reflected-integer-attributes.txt
  Tests/LibWeb/Text/input/HTML/reflected-integer-attributes.html
Labels: 👀 pr-needs-review

#24373 Chess: Add display widget for moves
  Userland/Games/Chess/Chess.gml
  Userland/Games/Chess/ChessWidget.cpp
  Userland/Games/Chess/ChessWidget.h
  Userland/Games/Chess/main.cpp
Labels: ✅ pr-community-approved

#23908 Toolchain+Docs: Improve the way to enable clangd
  Documentation/AdvancedBuildInstructions.md
  Toolchain/CMake/LLVMConfig.cmake
Labels: stale, 👀 pr-needs-review

#24378 LibWeb: Make exported Wasm functions keep the module instance alive
  Userland/Libraries/LibWeb/WebAssembly/Instance.cpp
  Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp
  Userland/Libraries/LibWeb/WebAssembly/WebAssembly.h
Labels: 👀 pr-needs-review

#24394 Meta: Fix detection of default compiler versions
  Meta/find_compiler.sh
  Meta/gn/README.md
Labels: 👀 pr-needs-review

#24308 Kernel: Implement virtio-blk driver.
  Kernel/Bus/VirtIO/Transport/PCIe/Detect.cpp
  Kernel/CMakeLists.txt
  Kernel/Devices/Storage/StorageManagement.cpp
  Kernel/Devices/Storage/VirtIO/VirtIOBlockController.cpp
  Kernel/Devices/Storage/VirtIO/VirtIOBlockController.h
  Kernel/Devices/Storage/VirtIO/VirtIOBlockDevice.cpp
  Kernel/Devices/Storage/VirtIO/VirtIOBlockDevice.h
  Meta/run.py
Labels: 👀 pr-needs-review

#24420 LibWeb: Enable callbacks in chunk steps for ReadableStreamDefaultTee
  Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
Labels: 👀 pr-needs-review

#24418 LibWeb: Stop spamming animation events on the wrong event target
  Tests/LibWeb/Text/expected/WebAnimations/misc/animation-events-basic.txt
  Tests/LibWeb/Text/input/WebAnimations/misc/animation-events-basic.html
  Userland/Libraries/LibWeb/Animations/Animation.cpp
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
Labels: 👀 pr-needs-review

#24363 Kernel: Move VGATextModeConsole code to the Arch/x86_64/ISABus directory
  Kernel/Arch/init.cpp
  Kernel/Arch/x86_64/VGA/TextModeConsole.cpp
  Kernel/Arch/x86_64/VGA/TextModeConsole.h
  Kernel/CMakeLists.txt
  Meta/gn/secondary/Kernel/BUILD.gn
Labels: 👀 pr-needs-review

#24421 LibJS: Add fast ExecutionContext allocator
  Userland/Libraries/LibJS/Runtime/ExecutionContext.cpp
  Userland/Libraries/LibJS/Runtime/ExecutionContext.h
Labels: 👀 pr-needs-review

#24094 Kernel/riscv64: Handle breakpoint traps
  Kernel/Arch/riscv64/Interrupts.cpp
Labels: 👀 pr-needs-review

#24427 LibWeb: Save time for animationcancel event before transitioning to idle
  Tests/LibWeb/Text/expected/css/sending-animationcancel-event-crash.txt
  Tests/LibWeb/Text/input/css/sending-animationcancel-event-crash.html
  Userland/Libraries/LibWeb/Animations/Animation.cpp
  Userland/Libraries/LibWeb/Animations/Animation.h
  Userland/Libraries/LibWeb/DOM/Document.cpp
Labels: 👀 pr-needs-review

#24433 Tests/LibGfx: Don't use a color name as an ARGB32 value
  Tests/LibGfx/TestImageWriter.cpp
Labels: ✅ pr-community-approved

#24416 LibGfx/GIF: Correctly write frames with a non-null position
  Tests/LibGfx/TestImageWriter.cpp
  Userland/Libraries/LibGfx/ImageFormats/GIFWriter.cpp
Labels: 👀 pr-needs-review

#24436 LibWasm: Properly read data section tags
  Userland/Libraries/LibWasm/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#24442 LibWasm: Use u32's instead of size_t's when reading LEB128 numbers
  Userland/Libraries/LibWasm/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#24439 LibWeb: Apply corner clip before scroll offset for PaintableWithLines
  Tests/LibWeb/Ref/reference/scrolled-text-with-clipped-corners-ref.html
  Tests/LibWeb/Ref/scrolled-text-with-clipped-corners.html
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Labels: 👀 pr-needs-review

#24443 LibWeb: Use LengthPercentage for calc values in Transformation matrix
  Tests/LibWeb/Text/expected/css/animating-transform-with-calc-crash.txt
  Tests/LibWeb/Text/input/css/animating-transform-with-calc-crash.html
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Labels: ci-flakiness, 👀 pr-needs-review

#24445 LibWeb: Implement HTMLFormElement.enctype & encoding
  Tests/LibWeb/Text/expected/HTML/form-element-enctype.txt
  Tests/LibWeb/Text/input/HTML/form-element-enctype.html
  Userland/Libraries/LibWeb/HTML/HTMLFormElement.idl
Labels: 👀 pr-needs-review

#24447 LibWeb: Implement BaseAudioContext.createBuffer
  Userland/Libraries/LibWeb/Forward.h
  Userland/Libraries/LibWeb/WebAudio/AudioBuffer.cpp
  Userland/Libraries/LibWeb/WebAudio/AudioBuffer.h
  Userland/Libraries/LibWeb/WebAudio/BaseAudioContext.cpp
  Userland/Libraries/LibWeb/WebAudio/BaseAudioContext.h
  Userland/Libraries/LibWeb/WebAudio/BaseAudioContext.idl
Labels: 👀 pr-needs-review

#24449 LibJS: Remove non-spec compliant code from internal_construct
  Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
  Userland/Libraries/LibJS/Tests/classes/class-inheritance.js
Labels: 👀 pr-needs-review

#24429 LibGfx/PNG: Read metadata from the eXIf chunk
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/png/exif.png
  Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp
  Userland/Libraries/LibGfx/ImageFormats/PNGLoader.h
Labels: 👀 pr-needs-review

#24450 LibWeb: Fix clip box calculation in PaintableWithLines
  Tests/LibWeb/Ref/paintablewithlines-corner-clip-in-scroll-container.html
  Tests/LibWeb/Ref/reference/paintablewithlines-corner-clip-in-scroll-container-ref.html
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Labels: 👀 pr-needs-review

#24454 LibCompress: When limiting huffman tree depth, sacrifice bottom of tree
  Userland/Libraries/LibCompress/Huffman.h
  Userland/Libraries/LibGfx/ImageFormats/WebPWriterLossless.cpp
Labels: 👀 pr-needs-review

#24457 LibWasm: Use TRY macro when possible
  Userland/Libraries/LibWasm/Parser/Parser.cpp
  Userland/Libraries/LibWasm/Types.h
Labels: 👀 pr-needs-review

#24459 LibGfx: Minor `EdgeFlagPathRasterizer` tweaks/fixes
  Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.cpp
Labels: 👀 pr-needs-review

#24455 Tests/LibWeb: Initialize 'arrayBuffer' to an UInt8Array
  Tests/LibWeb/Text/input/HTML/StructuredClone-object-primitives.html
Labels: 👀 pr-needs-review

#24456 LibWasm: Implement parsing all element variants
  Userland/Libraries/LibWasm/Parser/Parser.cpp
  Userland/Libraries/LibWasm/Types.h
Labels: 👀 pr-needs-review

#24466 LibWeb: Don't crash on clicking a label with an associated text input
  Tests/LibWeb/Text/expected/HTML/click-label-to-focus-text-input.txt
  Tests/LibWeb/Text/input/HTML/click-label-to-focus-text-input.html
  Userland/Libraries/LibWeb/Layout/Label.cpp
Labels: 👀 pr-needs-review

#24248 LibWeb: Improve resolution of `ResolvedCSSStyleDeclaration` properties
  Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
  Tests/LibWeb/Text/expected/css/getComputedStyle-relative-property-values.txt
  Tests/LibWeb/Text/input/css/getComputedStyle-relative-property-values.html
  Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
Labels: ci-flakiness, 👀 pr-needs-review

#24472 LibWeb: Cast to the correct type in `Element::auto_directionality()`
  Tests/LibWeb/Text/expected/css/dir-pseudo-on-form-associated-element.txt
  Tests/LibWeb/Text/expected/css/dir-pseudo-on-input-element.txt
  Tests/LibWeb/Text/input/css/dir-pseudo-on-form-associated-element.html
  Tests/LibWeb/Text/input/css/dir-pseudo-on-input-element.html
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: 👀 pr-needs-review

#24473 Meta: Use ```find_package``` for configuring backtraces
  Meta/Lagom/CMakeLists.txt
Labels: 👀 pr-needs-review

#24464 LibWasm: Properly read blocktypes
  Userland/Libraries/LibWasm/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#24481 Ladybird/Qt: Calculate the 'physical pixels' for screens
  Ladybird/Qt/WebContentView.cpp
Labels: 👀 pr-needs-review

#24488 LibWeb/WebDriver: Ensure error responses are serialized correctly
  Userland/Libraries/LibWeb/WebDriver/Client.cpp
Labels: 👀 pr-needs-review

#24496 Base: Add a manual page for the shred utility
  Base/usr/share/man/man1/shred.md
Labels: 👀 pr-needs-review

#24498 LibCore: Don't leak EventLoopImplementationUnix's ThreadData
  Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp
Labels: 👀 pr-needs-review

#24493 LibWasm: Fix memory limits validator discrepancy
  Userland/Libraries/LibWasm/AbstractMachine/Validator.cpp
  Userland/Libraries/LibWasm/AbstractMachine/Validator.h
Labels: 👀 pr-needs-review
