Repository SerenityOS/serenity, pull requests merged in 2024-07, with the labels that each got.

#24636 Cherry-pick "LibWeb: Implement the `HTMLTrackElement.kind` attribute"
  Tests/LibWeb/Text/expected/HTML/HTMLTrackElement-kind-attribute.txt
  Tests/LibWeb/Text/input/HTML/HTMLTrackElement-kind-attribute.html
  Userland/Libraries/LibWeb/HTML/AttributeNames.h
  Userland/Libraries/LibWeb/HTML/HTMLTrackElement.idl
Labels: 👀 pr-needs-review

#24635 Cherry-pick "UI/Qt: Ignore tab bar middle clicks if the user didn't click on a tab"
  Ladybird/Qt/BrowserWindow.cpp
Labels: 👀 pr-needs-review

#24640 Kernel/Memory: Remove duplicate code in try_create_purgeable_with_size()
  Kernel/Memory/AnonymousVMObject.cpp
Labels: 👀 pr-needs-review

#24631 AudioServer: Handle missing audio device gracefully
  Userland/Services/AudioServer/Mixer.cpp
  Userland/Services/AudioServer/Mixer.h
  Userland/Services/AudioServer/main.cpp
Labels: 👀 pr-needs-review

#24646 Cherry-pick "LibWeb/Geometry: Make DOMRect doubles unrestricted"
  Tests/LibWeb/Text/expected/geometry/domrect-create.txt
  Tests/LibWeb/Text/input/geometry/domrect-create.html
  Userland/Libraries/LibWeb/Geometry/DOMQuad.cpp
  Userland/Libraries/LibWeb/Geometry/DOMRect.idl
  Userland/Libraries/LibWeb/Geometry/DOMRectReadOnly.idl
Labels: 👀 pr-needs-review

#24643 Meta: Make disk_usage() not depend on GNU du
  Meta/shell_include.sh
Labels: 👀 pr-needs-review

#24645 Cherry-pick "LibWeb: Use double as the argument for AnimationFrameCallbacks"
  Userland/Libraries/LibWeb/HTML/AnimationFrameCallbackDriver.h
Labels: 👀 pr-needs-review

#24648 Grammar fixes
  Documentation/BuildInstructions.md
  Documentation/Kernel/RAMFS.md
  Kernel/Syscalls/jail.cpp
  Userland/Libraries/LibCore/Socket.h
  Userland/Libraries/LibLine/InternalFunctions.cpp
Labels: 👀 pr-needs-review

#24652 Cherry-pick "Ladybird/AppKit: Enable reload action"
  Ladybird/AppKit/UI/TabController.mm
Labels: 👀 pr-needs-review

#24653 Cherry-pick "UI/AppKit: Make the header buttons more accessible"
  Ladybird/AppKit/UI/TabController.mm
Labels: 👀 pr-needs-review

#24651 Cherry-pick "LibWeb: Reschedule HTML event loop processing if navigable needs repaint"
  Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
Labels: 👀 pr-needs-review

#24664 LibCrypto: Use ARM C Language Extensions (ACLE) for CRC32 intrinsics
  Userland/Libraries/LibCrypto/Checksum/CRC32.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#24358 Kernel: Remove the ConsoleManagement singleton
  Kernel/Arch/init.cpp
  Kernel/CMakeLists.txt
  Kernel/Devices/GPU/Console/ContiguousFramebufferConsole.cpp
  Kernel/Devices/GPU/Console/GenericFramebufferConsole.cpp
  Kernel/Devices/GPU/VirtIO/Console.cpp
  Kernel/Devices/HID/KeyboardDevice.cpp
  Kernel/Devices/HID/PS2/KeyboardDevice.cpp
  Kernel/Devices/TTY/ConsoleManagement.cpp
  Kernel/Devices/TTY/ConsoleManagement.h
  Kernel/Devices/TTY/VirtualConsole.cpp
  Kernel/Devices/TTY/VirtualConsole.h
  Kernel/Tasks/PowerStateSwitchTask.cpp
  Kernel/kprintf.cpp
  Meta/gn/secondary/Kernel/BUILD.gn
Labels: 👀 pr-needs-review

#24669 AK: Do not build against libexecinfo on non-glibc systems
  AK/Assertions.cpp
Labels: ✅ pr-community-approved

#24658 FileManager: Add keyboard shortcut for new window
  Userland/Applications/FileManager/main.cpp
Labels: ✅ pr-community-approved

#24670 AK: Re-enable execinfo for GNU Hurd
  AK/Assertions.cpp
Labels: 👀 pr-needs-review

#24674 Meta: Remove myself from CODEOWNERS
  .github/CODEOWNERS
Labels: 👀 pr-needs-review

#24667 LibAudio: Use clamp() in Sample::clip()
  Userland/Libraries/LibAudio/Sample.h
Labels: 👀 pr-needs-review

#24663 Meta: Update the Ladybird repo notice and remove it from the README
  Documentation/BuildInstructionsLadybird.md
  Ladybird/README.md
  README.md
Labels: 👀 pr-needs-review

#24666 Window.cpp: Remove TODOs
  Userland/Services/WindowServer/Window.cpp
Labels: 👀 pr-needs-review

#24679 CI: Remove `esvu` LibJS REPL jobs
  .github/workflows/serenity-js-artifacts.yml
  Meta/Lagom/ReadMe.md
Labels: 👀 pr-needs-review

#24676 PixelPaint: Disable Crop to Selection if empty
  Userland/Applications/PixelPaint/MainWidget.cpp
  Userland/Applications/PixelPaint/MainWidget.h
Labels: 👀 pr-needs-review

#24559 LibWeb: Use viewport position for did_enter_tooltip_area
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
Labels: 👀 pr-needs-review

#24690 Calendar: Sort Events by start DateTime
  Userland/Applications/Calendar/EventManager.cpp
Labels: 👀 pr-needs-review

#24382 cat: Add the -n line numbering feature
  Userland/Utilities/cat.cpp
Labels: ✅ pr-community-approved

#24677 LibPDF: Use `draw_rect()` to show debug clipping rects
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: 👀 pr-needs-review

#24665 LibGUI: Add alt shortcut for make_quit_action
  Userland/Applications/Browser/BrowserWindow.cpp
  Userland/Applications/KeyboardMapper/main.cpp
  Userland/Applications/PixelPaint/MainWidget.cpp
  Userland/Applications/Terminal/main.cpp
  Userland/Demos/CatDog/main.cpp
  Userland/Libraries/LibGUI/Action.h
  Userland/Libraries/LibGUI/CommonActions.cpp
Labels: ✅ pr-community-approved

#24673 DeviceMapper: Remove hardcoded lists of device node families
  Base/etc/DeviceMapper.ini
  Userland/Services/DeviceMapper/DeviceEventLoop.cpp
  Userland/Services/DeviceMapper/DeviceEventLoop.h
  Userland/Services/DeviceMapper/main.cpp
Labels: 👀 pr-needs-review

#24697 LibGfx/WebPLoader: Use transparent black as animation background color
  Tests/LibGfx/TestImageDecoder.cpp
  Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
Labels: 👀 pr-needs-review

#24696 Documentation: Add a note on construction of `Device` objects in Kernel
  Documentation/Kernel/DevelopmentGuidelines.md
Labels: 👀 pr-needs-review

#24701 Cherry-pick "LibMedia: Support videos with BT470BG color matrix"
  Userland/Libraries/LibMedia/Color/ColorConverter.cpp
  Userland/Libraries/LibMedia/PlaybackManager.cpp
  Userland/Libraries/LibMedia/VideoFrame.cpp
Labels: 👀 pr-needs-review

#24703 Cherry-pick "LibWeb: Ensure EC on stack when resolving/rejecting image decode promise"
  Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
Labels: 👀 pr-needs-review

#24710 Cherry-pick "LibWeb: Add customElements.getName"
  Userland/Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.cpp
  Userland/Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.h
  Userland/Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.idl
Labels: 👀 pr-needs-review

#24706 Cherry-pick "LibWeb/CSS: Use correct initial values for CSS properties"
  Userland/Libraries/LibWeb/CSS/Properties.json
Labels: 👀 pr-needs-review

#24704 Cherry-pick "LibWeb/HTML: Update Text Input Styling"
  Tests/LibWeb/Layout/expected/input-placeholder.txt
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Labels: 👀 pr-needs-review

#24711 Cherry-pick "LibWeb: Add initial implementation of global.reportError()"
  Tests/LibWeb/Text/expected/HTML/WindowOrWorkerGlobalScope-reportError.txt
  Tests/LibWeb/Text/input/HTML/WindowOrWorkerGlobalScope-reportError.html
  Userland/Libraries/LibWeb/HTML/Window.h
  Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
  Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.h
  Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.idl
Labels: 👀 pr-needs-review

#24712 Cherry-pick "LibWeb: Use system colors for input type range and progress as default"
  Userland/Libraries/LibWeb/CSS/Default.css
Labels: 👀 pr-needs-review

#24717 Cherry-pick "LibWeb: Invalidate input element style on focus change"
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
Labels: 👀 pr-needs-review

#24713 Cherry-pick "LibWeb: Implement :modal pseudo class"
  Tests/LibWeb/Layout/expected/dialog-open-modal.txt
  Tests/LibWeb/Layout/expected/dialog-open-non-modal.txt
  Tests/LibWeb/Layout/expected/top-layer.txt
  Tests/LibWeb/Layout/input/dialog-open-modal.html
  Tests/LibWeb/Layout/input/dialog-open-non-modal.html
  Userland/Libraries/LibWeb/CSS/PseudoClasses.json
  Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
  Userland/Libraries/LibWeb/HTML/HTMLDialogElement.h
Labels: 👀 pr-needs-review

#24715 Cherry-pick "LibWeb: Prepare script when src is set the first time"
  Tests/LibWeb/Text/expected/script-src-set-after-insertion.txt
  Tests/LibWeb/Text/input/script-src-set-after-insertion.html
  Tests/LibWeb/Text/input/script-src-set-after-insertion.js
  Userland/Libraries/LibWeb/HTML/HTMLScriptElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLScriptElement.h
Labels: 👀 pr-needs-review

#24719 Cherry-pick "LibWeb: Legacy Platform Objects don't force [[Configurable]]"
  Userland/Libraries/LibWeb/Bindings/PlatformObject.cpp
Labels: 👀 pr-needs-review

#24714 Cherry-pick "LibJS: Cache environment index for global declarative bindings"
  Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
  Userland/Libraries/LibJS/Bytecode/Executable.h
Labels: 👀 pr-needs-review

#24716 Cherry-pick "LibWeb: Don't fire resize event until document actually resizes once"
  Tests/LibWeb/Text/expected/no-window-resize-on-load.txt
  Tests/LibWeb/Text/input/no-window-resize-on-load.html
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
Labels: 👀 pr-needs-review

#24721 Cherry-pick "LibWeb: Implement HTML DragEvent class"
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
  Tests/LibWeb/Text/expected/all-window-properties.txt
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/Forward.h
  Userland/Libraries/LibWeb/HTML/DragEvent.cpp
  Userland/Libraries/LibWeb/HTML/DragEvent.h
  Userland/Libraries/LibWeb/HTML/DragEvent.idl
  Userland/Libraries/LibWeb/idl_files.cmake
Labels: 👀 pr-needs-review

#24720 Cherry-pick "LibWeb: When solving abspos lengths, use min max constrained height"
  Tests/LibWeb/Layout/expected/abspos-box-bottom-with-max-height.txt
  Tests/LibWeb/Layout/input/abspos-box-bottom-with-max-height.html
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Labels: 👀 pr-needs-review

#24729 Cherry-pick "LibWeb: Implement `Node.normalize()`"
  Tests/LibWeb/Text/expected/DOM/Node-normalize.txt
  Tests/LibWeb/Text/input/DOM/Node-normalize.html
  Userland/Libraries/LibWeb/DOM/Node.cpp
  Userland/Libraries/LibWeb/DOM/Node.h
  Userland/Libraries/LibWeb/DOM/Node.idl
Labels: 👀 pr-needs-review

#24728 Cherry-pick "LibWeb: Remove set_event_characteristics()"
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/UIEvents/MouseEvent.cpp
  Userland/Libraries/LibWeb/UIEvents/MouseEvent.h
  Userland/Libraries/LibWeb/UIEvents/WheelEvent.cpp
  Userland/Libraries/LibWeb/UIEvents/WheelEvent.h
Labels: 👀 pr-needs-review

#24727 Cherry-pick "LibWeb: Pass event_init to base class constructor in FocusEvent"
  Userland/Libraries/LibWeb/UIEvents/FocusEvent.cpp
Labels: 👀 pr-needs-review

#24726 Cherry-pick "LibWeb: Harmonize look of range input element"
  Userland/Libraries/LibWeb/CSS/Default.css
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
Labels: 👀 pr-needs-review

#24722 Cherry-pick "LibWeb: Populate filename in `WindowOrWorkerGlobalScope.reportError()`"
  Tests/LibWeb/Text/expected/HTML/WindowOrWorkerGlobalScope-reportError.txt
  Tests/LibWeb/Text/input/HTML/WindowOrWorkerGlobalScope-reportError.html
  Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
Labels: 👀 pr-needs-review

#24718 Cherry-pick "LibWeb: Define width for -webkit-slider-runnable-track"
  Userland/Libraries/LibWeb/CSS/Default.css
Labels: 👀 pr-needs-review

#24731 Cherry-pick "LibWeb: Use correct default value for <input type=range>"
  Tests/LibWeb/Layout/expected/input-range.txt
  Tests/LibWeb/Layout/input/input-range.html
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Labels: 👀 pr-needs-review

#24739 Cherry-pick "LibWeb: Implement EmbedderPolicy struct"
  Meta/gn/secondary/Userland/Libraries/LibWeb/HTML/BUILD.gn
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Requests.cpp
  Userland/Libraries/LibWeb/Forward.h
  Userland/Libraries/LibWeb/HTML/EmbedderPolicy.cpp
  Userland/Libraries/LibWeb/HTML/EmbedderPolicy.h
  Userland/Libraries/LibWeb/HTML/PolicyContainers.h
  Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.h
Labels: 👀 pr-needs-review

#24740 Cherry-pick "LibWeb: Handle inline-start and inline-end as float values"
  Tests/LibWeb/Layout/expected/block-and-inline/float-logical.txt
  Tests/LibWeb/Layout/input/block-and-inline/float-logical.html
  Userland/Libraries/LibWeb/CSS/Enums.json
  Userland/Libraries/LibWeb/CSS/Identifiers.json
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Labels: 👀 pr-needs-review

#24742 Cherry-pick "LibWeb: Implement WebIDL constructor flow for derived classes"
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
  Tests/LibWeb/Text/expected/DOM/derived-interface-prototype.txt
  Tests/LibWeb/Text/input/DOM/derived-interface-prototype.html
Labels: 👀 pr-needs-review

#24741 Cherry-pick "LibWeb: Change flex remaining space distribution to include gap"
  Tests/LibWeb/Layout/expected/flex/justify-content-on-min-content-with-gap.txt
  Tests/LibWeb/Layout/input/flex/justify-content-on-min-content-with-gap.html
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Labels: 👀 pr-needs-review

#24746 Cherry-pick "LibWeb/CSS: Serialize transform scale percentage values as numbers"
  Tests/LibWeb/Text/expected/css/transform-serialization.txt
  Tests/LibWeb/Text/input/css/transform-serialization.html
  Userland/Libraries/LibWeb/CSS/StyleValues/TransformationStyleValue.cpp
Labels: 👀 pr-needs-review

#24747 Cherry-pick "LibWebView: Trim whitespace when sanitizing file paths"
  Userland/Libraries/LibWebView/URL.cpp
Labels: 👀 pr-needs-review

#24748 Cherry-pick "LibWeb: Add null check in Document::ancestor_navigables()"
  Userland/Libraries/LibWeb/DOM/Document.cpp
Labels: 👀 pr-needs-review

#24745 Cherry-pick: "LibWeb: Implement support for scrollbar-gutter"
  Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
  Userland/Libraries/LibWeb/CSS/Enums.json
  Userland/Libraries/LibWeb/CSS/Identifiers.json
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/CSS/Parser/Parser.h
  Userland/Libraries/LibWeb/CSS/Properties.json
  Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
  Userland/Libraries/LibWeb/CSS/StyleValue.cpp
  Userland/Libraries/LibWeb/CSS/StyleValue.h
  Userland/Libraries/LibWeb/CSS/StyleValues/ScrollbarGutterStyleValue.h
  Userland/Libraries/LibWeb/Forward.h
Labels: 👀 pr-needs-review

#24752 LibWeb: Implement min option for ReadableStreamBYOBReader.read()
  Tests/LibWeb/Text/expected/Streams/ReadableStreamBYOBReader-read-min.txt
  Tests/LibWeb/Text/input/Streams/ReadableStreamBYOBReader-read-min.html
  Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
  Userland/Libraries/LibWeb/Streams/AbstractOperations.h
  Userland/Libraries/LibWeb/Streams/ReadableByteStreamController.cpp
  Userland/Libraries/LibWeb/Streams/ReadableByteStreamController.h
  Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBReader.cpp
  Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBReader.h
  Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBReader.idl
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#24754 CI: Stop running WPT on Lagom (Linux, ubuntu-22.04, NO_FUZZ) / CI)
  .github/workflows/lagom-template.yml
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#24735 LibC: Call pthread key destructors before global destructors
  Userland/Libraries/LibC/stdlib.cpp
Labels: 👀 pr-needs-review

#24753 Kernel/FileSystem: Clean up duplicated if statements
  Kernel/FileSystem/OpenFileDescription.cpp
Labels: 👀 pr-needs-review

#24755 Meta: Update Wasm LibJS build for "recent" emscripten changes
  Meta/Lagom/CMakeLists.txt
Labels: 👀 pr-needs-review

#24757 LibGUI: Improve how SpinBox handles negative numbers
  Userland/Libraries/LibGUI/SpinBox.cpp
Labels: 👀 pr-needs-review

#24494 Utilities: Introduce the watchfs utility
  Base/usr/share/man/man1/watchfs.md
  Userland/Utilities/CMakeLists.txt
  Userland/Utilities/watchfs.cpp
Labels: 👀 pr-needs-review

#24761 Ports: Add patchelf
  Ports/AvailablePorts.md
  Ports/patchelf/package.sh
Labels: 👀 pr-needs-review

#24767 Cherry-pick "LibWeb: Implement the `:has()` pseudo-class"
  Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPseudoClass.cpp
  Tests/LibWeb/Ref/css-has-compound.html
  Tests/LibWeb/Ref/css-has-descendant.html
  Tests/LibWeb/Ref/css-has-direct-child.html
  Tests/LibWeb/Ref/css-has-next-sibling.html
  Tests/LibWeb/Ref/css-has-subsequent-sibling.html
  Tests/LibWeb/Ref/css-nested-has.html
  Tests/LibWeb/Ref/css-pseudo-element-in-has.html
  Tests/LibWeb/Ref/reference/css-has-compound.html
  Tests/LibWeb/Ref/reference/css-has-descendant.html
  Tests/LibWeb/Ref/reference/css-has-direct-child.html
  Tests/LibWeb/Ref/reference/css-has-next-sibling.html
  Tests/LibWeb/Ref/reference/css-has-subsequent-sibling.html
  Tests/LibWeb/Ref/reference/css-nested-has.html
  Tests/LibWeb/Ref/reference/css-pseudo-element-in-has.html
  Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp
  Userland/Libraries/LibWeb/CSS/PseudoClasses.json
  Userland/Libraries/LibWeb/CSS/Selector.cpp
  Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
  Userland/Libraries/LibWeb/CSS/SelectorEngine.h
  Userland/Libraries/LibWeb/Dump.cpp
Labels: 👀 pr-needs-review

#24768 Cherry-pick "LibWeb: Propagate margin and offset when computing a box's baseline"
  Tests/LibWeb/Layout/expected/block-and-inline/button-baseline-align.txt
  Tests/LibWeb/Layout/expected/block-and-inline/button-image-only.txt
  Tests/LibWeb/Layout/expected/block-and-inline/button-should-have-vertically-aligned-content.txt
  Tests/LibWeb/Layout/expected/block-and-inline/button-with-after-pseudo.txt
  Tests/LibWeb/Layout/expected/block-and-inline/button-with-before-pseudo.txt
  Tests/LibWeb/Layout/expected/block-and-inline/button-with-block-content-baseline-align.txt
  Tests/LibWeb/Layout/expected/block-and-inline/button-with-min-height.txt
  Tests/LibWeb/Layout/expected/block-and-inline/button-with-multiple-words-text-node-label.txt
  Tests/LibWeb/Layout/expected/block-and-inline/button-with-text-node-label-and-font-size.txt
  Tests/LibWeb/Layout/expected/block-and-inline/button-with-text-node-label.txt
  Tests/LibWeb/Layout/expected/block-and-inline/inline-block-baseline-1.txt
  Tests/LibWeb/Layout/expected/block-and-inline/inline-block-baseline-2.txt
  Tests/LibWeb/Layout/expected/block-and-inline/margin-collapse-5.txt
  Tests/LibWeb/Layout/expected/box-sizing-border-box-for-definite-sizes-without-layout.txt
  Tests/LibWeb/Layout/expected/css-line-height-zero.txt
  Tests/LibWeb/Layout/expected/flex/inline-flex-baseline-of-child.txt
  Tests/LibWeb/Layout/expected/flex/inline-flex-early-resolution-of-percentage-height.txt
  Tests/LibWeb/Layout/expected/flex/inline-flex-with-main-axis-margin-on-flex-container.txt
  Tests/LibWeb/Layout/expected/grid/inline-grid-simple.txt
  Tests/LibWeb/Layout/expected/input-file.txt
  Tests/LibWeb/Layout/expected/input-image-to-text.txt
  Tests/LibWeb/Layout/expected/input-password-to-text.txt
  Tests/LibWeb/Layout/expected/input-placeholder.txt
  Tests/LibWeb/Layout/expected/input-text-node-invalidation-on-value-change.txt
  Tests/LibWeb/Layout/expected/input-text-to-password.txt
  Tests/LibWeb/Layout/expected/select-with-option-selected.txt
  Tests/LibWeb/Layout/expected/table/border-collapse-is-inherited.txt
  Tests/LibWeb/Layout/expected/table/inline-table-width.txt
  Tests/LibWeb/Layout/expected/textarea-content.txt
  Tests/LibWeb/Layout/expected/textarea-reset.txt
  Tests/LibWeb/Layout/input/flex/inline-flex-baseline-of-child.html
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Labels: 👀 pr-needs-review

#24769 Cherry-pick "LibWeb: Add support for indexed setter of HTMLOptionsCollection"
  Tests/LibWeb/Ref/options-set-index.html
  Tests/LibWeb/Ref/reference/options-set-index.html
  Tests/LibWeb/Text/expected/select-options-limit.txt
  Tests/LibWeb/Text/input/select-options-limit.html
  Userland/Libraries/LibWeb/HTML/HTMLOptionsCollection.cpp
  Userland/Libraries/LibWeb/HTML/HTMLOptionsCollection.h
Labels: 👀 pr-needs-review

#24771 Cherry-pick "LibJS: Implement CreatePerIterationEnvironment for 'for' statements"
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
  Userland/Libraries/LibJS/Tests/loops/for-scopes.js
Labels: 👀 pr-needs-review

#24772 Cherry-pick "LibWeb: Make getElementById() always return first match in tree order"
  Tests/LibWeb/Text/expected/DOM/getElementById-multiple.txt
  Tests/LibWeb/Text/input/DOM/getElementById-multiple.html
  Userland/Libraries/LibWeb/DOM/NonElementParentNode.h
Labels: 👀 pr-needs-review

#24770 Cherry-pick "LibJS: Create exception messages as Strings"
  Userland/Libraries/LibJS/Runtime/VM.h
Labels: 👀 pr-needs-review

#24695 Calendar: Initial support for iCalendar format
  Userland/Applications/Calendar/CalendarWidget.cpp
  Userland/Applications/Calendar/EventManager.cpp
  Userland/Applications/Calendar/EventManager.h
Labels: 👀 pr-needs-review

#24782 Cherry-pick "LibWeb: Change grid item placement to look for area by boundary lines"
  Tests/LibWeb/Layout/expected/grid/define-area-using-line-names.txt
  Tests/LibWeb/Layout/input/grid/define-area-using-line-names.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#24784 Cherry-pick "LibWeb: Fix flexible track sizing in GFC"
  Tests/LibWeb/Layout/expected/grid/1fr-1000px.txt
  Tests/LibWeb/Layout/input/grid/1fr-1000px.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#24778 Cherry-pick "LibWeb: Fix assertion failure on telekom.de"
  Userland/Libraries/LibWeb/HTML/Scripting/Fetching.cpp
Labels: 👀 pr-needs-review

#24795 Cherry-pick "LibWebView: Prevent displaying two scroll bars in the inspector console"
  Base/res/ladybird/inspector.css
  Base/res/ladybird/inspector.js
Labels: 👀 pr-needs-review

#24797 Cherry-pick "LibWeb: Update 'update_for_history_step_application' to meet new specs"
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/HTML/Navigable.cpp
  Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
Labels: 👀 pr-needs-review

#24798 Cherry-pick "LibWeb: Support `accent-color` for range input and progress element"
  Userland/Libraries/LibWeb/CSS/Default.css
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
  Userland/Libraries/LibWeb/HTML/HTMLProgressElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLProgressElement.h
Labels: 👀 pr-needs-review

#24806 Kernel: Don't truncate the pc value in the scheduler state dump
  Kernel/Tasks/Scheduler.cpp
Labels: 👀 pr-needs-review

#24808 Cherry-pick "LibWeb: Implement Text.wholeText"
  Tests/LibWeb/Text/expected/DOM/Text-wholeText.txt
  Tests/LibWeb/Text/input/DOM/Text-wholeText.html
  Userland/Libraries/LibWeb/DOM/Text.cpp
  Userland/Libraries/LibWeb/DOM/Text.h
  Userland/Libraries/LibWeb/DOM/Text.idl
Labels: 👀 pr-needs-review

#24799 Cherry-pick "LibWeb: Implement Element::check_visibility"
  Tests/LibWeb/Text/expected/HTML/Element-checkVisibility.txt
  Tests/LibWeb/Text/input/HTML/Element-checkVisibility.html
  Userland/Libraries/LibWeb/DOM/Element.cpp
  Userland/Libraries/LibWeb/DOM/Element.h
  Userland/Libraries/LibWeb/DOM/Element.idl
Labels: 👀 pr-needs-review

#24810 Base: Add more emoji
  Base/res/emoji/U+1F38E.png
  Base/res/emoji/U+1F3E3.png
  Base/res/emoji/U+1F3EC.png
  Base/res/emoji/U+1F68A.png
  Base/res/emoji/U+1F99F.png
  Base/res/emoji/U+1F9D9.png
  Base/res/emoji/U+1F9D9_U+200D_U+2640.png
  Base/res/emoji/U+1F9D9_U+200D_U+2642.png
  Meta/emoji-file-list.txt
Labels: 👀 pr-needs-review

#24805 Kernel/x86: Stop the APIC timer before configuring it
  Kernel/Arch/x86_64/Interrupts/APIC.cpp
Labels: 👀 pr-needs-review

#24818 Mail: Don't spam commands on mailbox node selection
  Userland/Applications/Mail/MailWidget.cpp
  Userland/Applications/Mail/MailWidget.h
Labels: 👀 pr-needs-review

#24813 LibIMAP: Avoid crashing on Group Addresses
  Userland/Libraries/LibIMAP/Parser.cpp
Labels: 👀 pr-needs-review

#24823 LibIMAP: Properly parse parenthesized address lists
  Userland/Libraries/LibIMAP/Parser.cpp
Labels: 👀 pr-needs-review

#24824 Kernel/USB: Correctly parse USB descriptors
  Kernel/Bus/USB/USBConfiguration.cpp
  Kernel/Bus/USB/USBDescriptors.h
  Kernel/Bus/USB/USBInterface.h
Labels: 👀 pr-needs-review

#24817 Base: Add 4 more emojis
  Base/res/emoji/U+1F68B.png
  Base/res/emoji/U+1F68C.png
  Base/res/emoji/U+1F68D.png
  Base/res/emoji/U+1F69F.png
  Meta/emoji-file-list.txt
Labels: 👀 pr-needs-review

#24830 Cherry-pick "LibWeb: Use absolute padding box to calculate max scroll offset"
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Labels: 👀 pr-needs-review

#24828 Cherry-pick "LibTextCodec: Use String::from_utf8() when decoding UTF-8 to UTF-8"
  Userland/Libraries/LibTextCodec/Decoder.cpp
Labels: 👀 pr-needs-review

#24827 Cherry-pick "LibWeb: Make details and summary elements display:block in the UA style"
  Tests/LibWeb/Layout/expected/details-closed.txt
  Tests/LibWeb/Layout/expected/details-open.txt
  Tests/LibWeb/Layout/expected/details-summary-default-ua-style.txt
  Tests/LibWeb/Layout/input/details-summary-default-ua-style.html
  Userland/Libraries/LibWeb/CSS/Default.css
Labels: 👀 pr-needs-review

#24826 LibIMAP: Handle escaped quotes in parse_quoted_string()
  Userland/Libraries/LibIMAP/Parser.cpp
Labels: 👀 pr-needs-review

#24836 Cherry-pick "LibWeb: Bring 'construct_entry_list' closer to specs"
  Userland/Libraries/LibWeb/HTML/FormControlInfrastructure.cpp
Labels: 👀 pr-needs-review

#24832 Mail: Remove CRLF chars from base64 data before decoding
  Userland/Applications/Mail/MailWidget.cpp
Labels: 👀 pr-needs-review

#24834 Cherry-pick "LibWeb: Check CanvasTextDrawingStyles.font assignment is valid"
  Tests/LibWeb/Text/expected/canvas/invalid-font-property.txt
  Tests/LibWeb/Text/input/canvas/invalid-font-property.html
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasTextDrawingStyles.h
Labels: 👀 pr-needs-review

#24851 Cherry-pick "LibWeb: Implement Blob::bytes()"
  Tests/LibWeb/Text/expected/FileAPI/Blob-intialized-with-strings-read-from-bytes.txt
  Tests/LibWeb/Text/input/FileAPI/Blob-intialized-with-strings-read-from-bytes.html
  Userland/Libraries/LibWeb/Clipboard/Clipboard.cpp
  Userland/Libraries/LibWeb/DOMURL/DOMURL.cpp
  Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
  Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Bodies.cpp
  Userland/Libraries/LibWeb/FileAPI/Blob.cpp
  Userland/Libraries/LibWeb/FileAPI/Blob.h
  Userland/Libraries/LibWeb/FileAPI/Blob.idl
  Userland/Libraries/LibWeb/HTML/FormControlInfrastructure.cpp
  Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
  Userland/Libraries/LibWeb/WebSockets/WebSocket.cpp
Labels: 👀 pr-needs-review

#24850 Cherry-pick "LibWeb: Don't proceed with Element.click() on disabled form controls"
  Tests/LibWeb/Text/expected/HTML/submit-button-click-when-disabled.txt
  Tests/LibWeb/Text/input/HTML/submit-button-click-when-disabled.html
  Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
Labels: 👀 pr-needs-review

#24848 Cherry-pick 'LibWeb: Fix typo "rtr" -> "rtl"'
  Userland/Libraries/LibWeb/HTML/FormControlInfrastructure.cpp
Labels: 👀 pr-needs-review

#24846 Cherry-pick "LibWeb: Cache name->element mappings in HTMLCollection"
  Userland/Libraries/LibWeb/Bindings/PlatformObject.cpp
  Userland/Libraries/LibWeb/Bindings/PlatformObject.h
  Userland/Libraries/LibWeb/DOM/HTMLCollection.cpp
  Userland/Libraries/LibWeb/DOM/HTMLCollection.h
Labels: 👀 pr-needs-review

#24845 Cherry-pick "LibWeb: Stop trying to guess include paths in IDL codegen"
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Labels: 👀 pr-needs-review

#24838 Cherry-pick "LibWeb: Make offsetTop and offsetLeft behave more like other browsers"
  Tests/LibWeb/Layout/expected/block-and-inline/relpos-inline-element-js-offsets.txt
  Tests/LibWeb/Text/expected/DOM/Offset-of-empty-inline-element.txt
  Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
Labels: 👀 pr-needs-review

#24843 Cherry-pick "LibWeb: Parse fill and stroke values"
  Tests/LibWeb/Ref/canvas-fillstyle-rgb.html
  Tests/LibWeb/Ref/reference/images/canvas-fillstyle-rgb.png
  Tests/LibWeb/Text/expected/canvas/fillstyle.txt
  Tests/LibWeb/Text/input/canvas/fillstyle.html
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasFillStrokeStyles.h
Labels: 👀 pr-needs-review

#24839 Cherry-pick "LibWeb: Inherit CSS variables across shadow boundaries"
  Tests/LibWeb/Text/expected/ShadowDOM/css-variable-inheritance-across-shadow-boundary.txt
  Tests/LibWeb/Text/input/ShadowDOM/css-variable-inheritance-across-shadow-boundary.html
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#24825 LibGfx/WebPWriterLossless: Use predictor transform
  Tests/LibGfx/TestImageWriter.cpp
  Userland/Libraries/LibGfx/ImageFormats/WebPWriterLossless.cpp
Labels: 👀 pr-needs-review

#24858 Cherry-pick "Utilities/js: Make it possible to exit via two consecutive ^C's"
  Userland/Libraries/LibLine/Editor.cpp
  Userland/Libraries/LibLine/Editor.h
  Userland/Libraries/LibLine/InternalFunctions.cpp
  Userland/Libraries/LibLine/KeyCallbackMachine.cpp
  Userland/Utilities/js.cpp
Labels: 👀 pr-needs-review

#24860 Cherry-pick "LibWeb/DOM: Check if name is valid in Element.toggleAttribute"
  Tests/LibWeb/Text/expected/Element-toggleAttribute-invalid-name.txt
  Tests/LibWeb/Text/input/Element-toggleAttribute-invalid-name.html
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: 👀 pr-needs-review

#24864 Cherry-pick "LibWeb: Only inject "User-Agent"/"Accept" headers when they're missing"
  Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
Labels: 👀 pr-needs-review

#24863 Cherry-pick "LibWeb: Make `document.createElementNS()` case-sensitive"
  Tests/LibWeb/Text/expected/DOM/Document-createElementNS-uppercase.txt
  Tests/LibWeb/Text/input/DOM/Document-createElementNS-uppercase.html
  Userland/Libraries/LibWeb/DOM/ElementFactory.cpp
Labels: 👀 pr-needs-review

#24870 Cherry-pick "LibWeb: Add Web Worker Origin Inheritance"
  Userland/Libraries/LibWeb/HTML/Scripting/WorkerEnvironmentSettingsObject.cpp
  Userland/Libraries/LibWeb/HTML/Scripting/WorkerEnvironmentSettingsObject.h
  Userland/Services/WebWorker/DedicatedWorkerHost.cpp
Labels: 👀 pr-needs-review

#24868 Cherry-pick "LibWeb: Stub BroadcastChannel interface"
  Meta/gn/secondary/Userland/Libraries/LibWeb/HTML/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWeb/idl_files.gni
  Tests/LibWeb/Text/expected/all-window-properties.txt
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/Forward.h
  Userland/Libraries/LibWeb/HTML/BroadcastChannel.cpp
  Userland/Libraries/LibWeb/HTML/BroadcastChannel.h
  Userland/Libraries/LibWeb/HTML/BroadcastChannel.idl
  Userland/Libraries/LibWeb/idl_files.cmake
Labels: 👀 pr-needs-review

#24872 Cherry-pick "LibWeb+RequestServer: Let RequestServer set HTTP Accept-Encoding header"
  Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
  Userland/Services/RequestServer/ConnectionFromClient.cpp
Labels: 👀 pr-needs-review

#24867 Cherry-pick "Documentation: Fixed typo at BrowsingContextsAndNavigables"
  Documentation/Browser/BrowsingContextsAndNavigables.md
Labels: 👀 pr-needs-review

#24866 Cherry-pick "LibWeb: Rename HTMLInputElement members related to range shadow tree"
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
Labels: 👀 pr-needs-review

#24875 Cherry-pick "LibWeb: Set correct prototype for `WorkerLocation`"
  Tests/LibWeb/Text/expected/Worker/Worker-location.txt
  Tests/LibWeb/Text/input/Worker/Worker-location.html
  Tests/LibWeb/Text/input/Worker/Worker-location.js
  Userland/Libraries/LibWeb/HTML/WorkerLocation.cpp
  Userland/Libraries/LibWeb/HTML/WorkerLocation.h
Labels: 👀 pr-needs-review

#24879 Cherry-pick "LibJS: Fix crash in bytecode generator on https://twinings.co.uk/"
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
  Userland/Libraries/LibJS/Tests/for-loop-per-iteration-env-bug.js
Labels: 👀 pr-needs-review

#24880 Cherry-pick "LibWeb: WebIDL::OverloadResolution::resolve_overload, add dbgln FIXMEs"
  Userland/Libraries/LibWeb/WebIDL/OverloadResolution.cpp
Labels: 👀 pr-needs-review

#24877 Cherry-pick "LibWeb/DOM: Avoid repeated calls to Node::navigable"
  Userland/Libraries/LibWeb/DOM/Document.cpp
Labels: 👀 pr-needs-review

#24882 Cherry-pick "LibWeb/Painting: Delete unused LinearGradientData.h"
  Userland/Libraries/LibWeb/Painting/LinearGradientData.h
Labels: 👀 pr-needs-review

#24881 Cherry-pick 2 PRs from Ladybird
  Meta/gn/secondary/Userland/Libraries/LibWeb/HTML/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWeb/idl_files.gni
  Tests/LibWeb/Text/expected/all-window-properties.txt
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/Forward.h
  Userland/Libraries/LibWeb/HTML/DOMStringList.cpp
  Userland/Libraries/LibWeb/HTML/DOMStringList.h
  Userland/Libraries/LibWeb/HTML/DOMStringList.idl
  Userland/Libraries/LibWeb/idl_files.cmake
Labels: 👀 pr-needs-review

#24816 Kernel/Net: IPv6 preparations
  Kernel/CMakeLists.txt
  Kernel/FileSystem/SysFS/Subsystems/Kernel/Network/ARP.cpp
  Kernel/Net/ICMP.h
  Kernel/Net/IPv4/ARP.h
  Kernel/Net/IPv4/IPv4.h
  Kernel/Net/IPv4/Socket.cpp
  Kernel/Net/IPv4/Socket.h
  Kernel/Net/IPv4/SocketTuple.h
  Kernel/Net/NetworkAdapter.h
  Kernel/Net/NetworkTask.cpp
  Kernel/Net/Socket.cpp
  Kernel/Net/TCP.h
  Kernel/Net/TCPSocket.cpp
  Kernel/Net/TCPSocket.h
  Kernel/Net/UDP.h
  Kernel/Net/UDPSocket.h
  Meta/gn/secondary/Kernel/BUILD.gn
  Userland/Libraries/LibC/netdb.cpp
Labels: 👀 pr-needs-review

#24756 Documentation: Fix BuildInstructions.md capitialization
  Documentation/BuildInstructions.md
Labels: 👀 pr-needs-review

#24886 Kernel/USB: Make USBHubDescriptor::hub_characteristics union packed
  Kernel/Bus/USB/USBDescriptors.h
Labels: 👀 pr-needs-review
