Repository SerenityOS/serenity, pull requests merged in 2024-08, with the labels that each got.

#24884 Kernel/PCI: Handle 64-bit MSI-X BARs
  Kernel/Bus/PCI/Device.cpp
Labels: 👀 pr-needs-review

#24885 ImageViewer: Call clear() in the ViewWidget before loading a new image
  Userland/Applications/ImageViewer/ViewWidget.cpp
Labels: 👀 pr-needs-review

#24865 Cherry-pick "LibThreading: Guard closing the background thread on the thread existing"
  Userland/Libraries/LibThreading/BackgroundAction.cpp
Labels: 👀 pr-needs-review

#24822 Terminal: Remove unveiling portal/config
  Userland/Applications/Terminal/main.cpp
Labels: 👀 pr-needs-review

#24888 Kernel/x86: Properly restore rflags in the syscall handler
  Kernel/Arch/x86_64/SyscallEntry.cpp
Labels: 👀 pr-needs-review

#24890 Ports/harfbuzz: upgrade to 9.0.0
  Ports/AvailablePorts.md
  Ports/harfbuzz/package.sh
Labels: 👀 pr-needs-review

#24892 Ports/aria2: Upgrade to 1.37.0
  Ports/AvailablePorts.md
  Ports/aria2/package.sh
Labels: 👀 pr-needs-review

#24889 Ports: Update RetroArch to version 1.19.1
  Ports/AvailablePorts.md
  Ports/RetroArch/package.sh
Labels: 👀 pr-needs-review

#24878 Cherry-pick "LibGfx: Handle UTF-16-encoded OpenType font names"
  Userland/Libraries/LibGfx/Font/OpenType/Tables.cpp
Labels: 👀 pr-needs-review

#24899 Ports: Update Python to 3.12.4
  Ports/AvailablePorts.md
  Ports/python3/version.sh
Labels: 👀 pr-needs-review

#24693 LibELF: Fix incorrect treatment of DT_REL&DT_RELA
  Userland/Libraries/LibELF/DynamicObject.cpp
Labels: 👀 pr-needs-review

#24734 Kernel: Change internal handling of filesystem-specific options
  Kernel/API/FileSystem/MountSpecificFlags.h
  Kernel/API/Ioctl.h
  Kernel/CMakeLists.txt
  Kernel/FileSystem/DevLoopFS/FileSystem.cpp
  Kernel/FileSystem/DevLoopFS/FileSystem.h
  Kernel/FileSystem/DevPtsFS/FileSystem.cpp
  Kernel/FileSystem/DevPtsFS/FileSystem.h
  Kernel/FileSystem/Ext2FS/FileSystem.cpp
  Kernel/FileSystem/Ext2FS/FileSystem.h
  Kernel/FileSystem/FATFS/FileSystem.cpp
  Kernel/FileSystem/FATFS/FileSystem.h
  Kernel/FileSystem/FUSE/FileSystem.cpp
  Kernel/FileSystem/FUSE/FileSystem.h
  Kernel/FileSystem/FileSystemSpecificOption.cpp
  Kernel/FileSystem/FileSystemSpecificOption.h
  Kernel/FileSystem/ISO9660FS/FileSystem.cpp
  Kernel/FileSystem/ISO9660FS/FileSystem.h
  Kernel/FileSystem/Initializer.h
  Kernel/FileSystem/MountFile.cpp
  Kernel/FileSystem/MountFile.h
  Kernel/FileSystem/Plan9FS/FileSystem.cpp
  Kernel/FileSystem/Plan9FS/FileSystem.h
  Kernel/FileSystem/ProcFS/FileSystem.cpp
  Kernel/FileSystem/ProcFS/FileSystem.h
  Kernel/FileSystem/RAMFS/FileSystem.cpp
  Kernel/FileSystem/RAMFS/FileSystem.h
  Kernel/FileSystem/SysFS/FileSystem.cpp
  Kernel/FileSystem/SysFS/FileSystem.h
  Kernel/FileSystem/VirtualFileSystem.cpp
Labels: 👀 pr-needs-review

#24893 Toolchain: Fix default library paths when building with clang
  Ports/epsilon/patches/0001-Add-serenity-toolchain-information-and-makefile-file.patch
  Ports/git/package.sh
  Ports/ja2/patches/0001-Make-it-build-with-SDL-2-instead-of-1.2.patch
  Ports/openssl/package.sh
  Ports/sam/patches/0002-Manually-set-the-SDL2-include-path-and-library-dir.patch
  Ports/sl/package.sh
  Ports/stress-ng/package.sh
  Toolchain/Patches/llvm/0001-clang-Add-support-for-SerenityOS.patch
Labels: 👀 pr-needs-review

#24894 Ports/SuperTuxKart: Fix building on Clang
  Ports/SuperTuxKart/package.sh
Labels: 👀 pr-needs-review

#24891 Ports/SDL2: Update SDL2 and fix Clang build
  Ports/AvailablePorts.md
  Ports/SDL2/package.sh
  Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch
Labels: 👀 pr-needs-review

#24904 Toolchain: On macOS, remove dependency on coreutils from BuildClang.sh
  Toolchain/BuildClang.sh
Labels: 👀 pr-needs-review

#24907 Presenter: Modify CSS to hide scrollbars
  Userland/Applications/Presenter/Presentation.cpp
  Userland/Applications/Presenter/PresenterWidget.cpp
Labels: 👀 pr-needs-review

#24897 RequestServer: Make the ThreadPool global
  Userland/Services/RequestServer/ConnectionFromClient.cpp
  Userland/Services/RequestServer/ConnectionFromClient.h
Labels: 👀 pr-needs-review

#24686 AK: Fix {:c} formatter for big-endian
  AK/Format.cpp
Labels: 👀 pr-needs-review

#24912 Tests/Kernel: Add test for Ext2FS reads and writes
  Tests/Kernel/TestExt2FS.cpp
Labels: 👀 pr-needs-review

#24909 AK: Add `simd_cast<T>` and replace `to_TxN` with it
  AK/SIMD.h
  AK/SIMDExtras.h
  AK/SIMDMath.h
  Userland/Libraries/LibGfx/ImageFormats/PNGWriter.cpp
  Userland/Libraries/LibSoftGPU/Device.cpp
  Userland/Libraries/LibSoftGPU/SIMD.h
  Userland/Libraries/LibSoftGPU/Sampler.cpp
Labels: 👀 pr-needs-review

#24898 Meta: Remove /mod
  Meta/build-root-filesystem.sh
Labels: 👀 pr-needs-review

#24853 Kernel: Create coredump by using the crashed process VFS root context
  Kernel/Tasks/Coredump.cpp
Labels: 👀 pr-needs-review

#24911 Kernel/Memory: Fix crash on writes to shared file mmaps
  Kernel/Memory/Region.cpp
Labels: 👀 pr-needs-review

#24922 PDFViewer: Fix outline page number off-by-one
  Userland/Applications/PDFViewer/OutlineModel.cpp
Labels: 👀 pr-needs-review

#24923 LibGfx/PNGWriter: Compute which predictor to use first, store data then
  Userland/Libraries/LibGfx/ImageFormats/PNGWriter.cpp
Labels: 👀 pr-needs-review

#24925 Kernel/USB: Always check for the Intel xHCI port routing quirk
  Kernel/Bus/USB/xHCI/xHCIController.cpp
Labels: 👀 pr-needs-review

#24931 Cherry-pick "LibWebView: Sort vendor-prefixed properties last in the inspector"
  Base/res/ladybird/inspector.js
Labels: 👀 pr-needs-review

#24932 Cherry-pick "LibWeb: Add additional padding to the end of the scrollable overflow"
  Tests/LibWeb/Layout/expected/flex/abspos-flex-child-static-position-with-padding-on-flex-container.txt
  Tests/LibWeb/Layout/expected/input-placeholder.txt
  Tests/LibWeb/Layout/expected/overflow-with-padding.txt
  Tests/LibWeb/Layout/expected/position-absolute-ignores-padding-of-position-relative-floating-parent.txt
  Tests/LibWeb/Layout/expected/table/avoid-div-by-zero-in-table-measures.txt
  Tests/LibWeb/Layout/input/overflow-with-padding.html
  Userland/Libraries/LibWeb/Layout/LayoutState.cpp
Labels: 👀 pr-needs-review

#24936 Cherry-pick "LibWeb: No longer return `undefined` on null table entry in Wasm API"
  Userland/Libraries/LibWeb/WebAssembly/Table.cpp
  Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp
Labels: 👀 pr-needs-review

#24937 Cherry-pick "LibWeb: Apply scroll offset and clip rectangle to table borders"
  Tests/LibWeb/Ref/reference/scrollable-contains-table-ref.html
  Tests/LibWeb/Ref/scrollable-contains-table.html
  Userland/Libraries/LibWeb/Painting/Paintable.h
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Labels: 👀 pr-needs-review

#24938 Cherry-pick "LibWeb: Account for header size when reading MessagePort message payload"
  Userland/Libraries/LibWeb/HTML/MessagePort.cpp
Labels: 👀 pr-needs-review

#24901 Utilities/du: Set minimum width when printing sizes
  Userland/Utilities/du.cpp
Labels: 👀 pr-needs-review

#24934 Cherry-pick "LibWeb: Keep Wasm-imported functions alive"
  Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp
  Userland/Libraries/LibWeb/WebAssembly/WebAssembly.h
Labels: 👀 pr-needs-review

#24942 Kernel: Remove Processor::is_kernel_mode
  Kernel/Arch/Processor.cpp
  Kernel/Arch/Processor.h
  Kernel/Arch/aarch64/Processor.h
  Kernel/Arch/riscv64/Processor.h
  Kernel/Arch/x86_64/Processor.cpp
  Kernel/Arch/x86_64/Processor.h
Labels: 👀 pr-needs-review

#24941 LibGfx/PNGWriter: Some final (?) cleanups
  Userland/Libraries/LibGfx/ImageFormats/PNGWriter.cpp
Labels: 👀 pr-needs-review

#24924 PDFViewer: Implement thumbnail previews
  Userland/Applications/PDFViewer/CMakeLists.txt
  Userland/Applications/PDFViewer/PDFViewer.h
  Userland/Applications/PDFViewer/PDFViewerWidget.cpp
  Userland/Applications/PDFViewer/PDFViewerWidget.h
  Userland/Applications/PDFViewer/SidebarWidget.cpp
  Userland/Applications/PDFViewer/SidebarWidget.h
  Userland/Applications/PDFViewer/ThumbnailsListView.cpp
  Userland/Applications/PDFViewer/ThumbnailsListView.h
  Userland/Applications/PDFViewer/ThumbnailsModel.cpp
  Userland/Applications/PDFViewer/ThumbnailsModel.h
Labels: 👀 pr-needs-review

#24947 LibGfx/ICC: Tolerate v2 profiles with D65 PCS illuminant
  Tests/LibGfx/TestICCProfile.cpp
  Tests/LibGfx/test-inputs/icc/pcs-v2.icc
  Userland/Libraries/LibGfx/ICC/Profile.cpp
Labels: 👀 pr-needs-review

#24948 Meta: Port recent changes to the GN build
  Meta/gn/secondary/AK/BUILD.gn
  Meta/gn/secondary/Ladybird/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibJS/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibMedia/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWeb/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWeb/CSS/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWeb/CSS/StyleValues/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWeb/DOM/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWeb/Fetch/Infrastructure/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWeb/HTML/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWeb/idl_files.gni
Labels: 👀 pr-needs-review

#24946 Documentation: Correct fuse2fs instructions for Fedora
  Documentation/BuildInstructionsOther.md
Labels: 👀 pr-needs-review

#24903 TextEditor: Port TextEditor to GML Compiler
  Userland/Applications/TextEditor/CMakeLists.txt
  Userland/Applications/TextEditor/MainWidget.cpp
  Userland/Applications/TextEditor/MainWidget.h
  Userland/Applications/TextEditor/TextEditorWindow.gml
  Userland/Applications/TextEditor/main.cpp
Labels: 👀 pr-needs-review

#24950 ImageViewer: Set scaling mode's default value to "Box Sampling"
  Userland/Applications/ImageViewer/ViewWidget.h
  Userland/Applications/ImageViewer/main.cpp
Labels: 👀 pr-needs-review

#24538 LibCrypto: Implement AES by using x86 intrinsics
  AK/CPUFeatures.cpp
  AK/CPUFeatures.h
  Userland/Libraries/LibCrypto/Cipher/AES.cpp
  Userland/Libraries/LibCrypto/Cipher/AES.h
Labels: 👀 pr-needs-review

#24957 Meta: Make `unzip` buildable on lagom
  Meta/Lagom/CMakeLists.txt
Labels: 👀 pr-needs-review

#24949 AK/FuzzyMatch: Return the best possible score for equality
  AK/FuzzyMatch.cpp
  Tests/AK/TestFuzzyMatch.cpp
Labels: ci-flakiness, 👀 pr-needs-review

#24956 Tests: Modernize TestDeflate a bit
  Tests/LibCompress/TestDeflate.cpp
Labels: 👀 pr-needs-review

#24954 Base: Add poweroff alias to shellrc
  Base/etc/shellrc
Labels: 👀 pr-needs-review

#24955 LibVT: Handle concealed ANSI escape codes
  Userland/Libraries/LibVT/Attribute.h
  Userland/Libraries/LibVT/Terminal.cpp
  Userland/Libraries/LibVT/TerminalWidget.cpp
Labels: 👀 pr-needs-review

#24964 LibIMAP+Mail: Show unseen message count for mailboxes
  Userland/Applications/Mail/AccountHolder.cpp
  Userland/Applications/Mail/AccountHolder.h
  Userland/Applications/Mail/InboxModel.cpp
  Userland/Applications/Mail/InboxModel.h
  Userland/Applications/Mail/MailWidget.cpp
  Userland/Applications/Mail/MailWidget.h
  Userland/Applications/Mail/MailboxTreeModel.cpp
  Userland/Libraries/LibIMAP/Client.cpp
  Userland/Libraries/LibIMAP/Client.h
  Userland/Libraries/LibIMAP/Objects.h
  Userland/Libraries/LibIMAP/Parser.cpp
  Userland/Utilities/test-imap.cpp
Labels: 👀 pr-needs-review

#24967 shot: Use "popup" window type for screenshot area selection
  Userland/Utilities/shot.cpp
Labels: 👀 pr-needs-review

#24971 AK: Make workaround for broken coroutine type deduction more specific
  AK/Platform.h
Labels: 👀 pr-needs-review

#24968 CI: Build riscv64 in CI
  .github/workflows/ci.yml
  .github/workflows/serenity-template.yml
Labels: 👀 pr-needs-review, ✅ pr-community-approved

#24750 Kernel/Ext2FS: Reduce allocations in compute_block_list_impl()
  Kernel/FileSystem/Ext2FS/Inode.cpp
Labels: 👀 pr-needs-review

#24979 Ports/devilutionX: Update to version 1.5.3
  Ports/AvailablePorts.md
  Ports/devilutionX/package.sh
Labels: 👀 pr-needs-review
