Repository SerenityOS/serenity, pull requests merged in 2024-06, with the labels that each got.

#24509 LibWeb: Set import map scopes when parsing
  Userland/Libraries/LibWeb/HTML/Scripting/ImportMap.cpp
Labels: ✅ pr-community-approved

#24510 Ladybird/Qt: Flatten the buttons in the find-in-page panel
  Ladybird/Qt/FindInPageWidget.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#24492 LibWasm: Improve table support
  Meta/generate-libwasm-spec-test.py
  Tests/LibWasm/test-wasm.cpp
  Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp
  Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.h
  Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
  Userland/Libraries/LibWeb/WebAssembly/Table.cpp
Labels: 👀 pr-needs-review

#24507 Utilities/tar: Open archive file before changing directory
  Userland/Utilities/tar.cpp
Labels: 👀 pr-needs-review

#24426 Kernel: Ignore dirfd if absolute path is given in VFS-related syscalls
  Kernel/CMakeLists.txt
  Kernel/FileSystem/CustodyBase.cpp
  Kernel/FileSystem/CustodyBase.h
  Kernel/FileSystem/Inode.cpp
  Kernel/FileSystem/Inode.h
  Kernel/FileSystem/VirtualFileSystem.cpp
  Kernel/FileSystem/VirtualFileSystem.h
  Kernel/Forward.h
  Kernel/Syscalls/chdir.cpp
  Kernel/Syscalls/chmod.cpp
  Kernel/Syscalls/chown.cpp
  Kernel/Syscalls/faccessat.cpp
  Kernel/Syscalls/link.cpp
  Kernel/Syscalls/mkdir.cpp
  Kernel/Syscalls/mknod.cpp
  Kernel/Syscalls/open.cpp
  Kernel/Syscalls/rename.cpp
  Kernel/Syscalls/stat.cpp
  Kernel/Syscalls/unlink.cpp
  Kernel/Syscalls/utimensat.cpp
  Kernel/Tasks/Coredump.cpp
  Kernel/Tasks/Process.cpp
  Kernel/Tasks/Process.h
Labels: 👀 pr-needs-review

#24515 LibWasm: Check section lengths when parsing
  Userland/Libraries/LibWasm/Parser/Parser.cpp
  Userland/Libraries/LibWasm/Types.h
Labels: 👀 pr-needs-review

#24444 LibWeb: Support interpolation of mixed percentage dimension units
  Tests/LibWeb/Text/expected/WebAnimations/misc/animate-with-mixed-percentages.txt
  Tests/LibWeb/Text/input/WebAnimations/misc/animate-with-mixed-percentages.html
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Labels: ci-flakiness, 👀 pr-needs-review

#24516 LibWasm: Properly check active data segment offset in instantiation
  Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp
Labels: 👀 pr-needs-review

#24517 LibWasm: Properly check table bounds in element instantiation
  Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp
Labels: 👀 pr-needs-review

#24519 LibWasm: Properly check `memory.copy` addresses
  Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
Labels: 👀 pr-needs-review

#24527 LibSyntax: Remove minor unnecessary use of LibGUI
  Userland/Libraries/LibSyntax/Highlighter.cpp
  Userland/Libraries/LibSyntax/Language.cpp
Labels: 👀 pr-needs-review

#24526 LibWeb: Add Web::UIEvents::MouseButton enum, drop dependency on LibGUI
  Ladybird/AppKit/UI/Event.h
  Ladybird/AppKit/UI/Event.mm
  Ladybird/AppKit/UI/LadybirdWebView.mm
  Ladybird/Qt/WebContentView.cpp
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/Layout/Label.cpp
  Userland/Libraries/LibWeb/Layout/RadioButton.cpp
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
  Userland/Libraries/LibWeb/Page/EventHandler.h
  Userland/Libraries/LibWeb/Page/InputEvent.cpp
  Userland/Libraries/LibWeb/Page/InputEvent.h
  Userland/Libraries/LibWeb/Painting/AudioPaintable.cpp
  Userland/Libraries/LibWeb/Painting/ButtonPaintable.cpp
  Userland/Libraries/LibWeb/Painting/CheckBoxPaintable.cpp
  Userland/Libraries/LibWeb/Painting/LabelablePaintable.cpp
  Userland/Libraries/LibWeb/Painting/MediaPaintable.cpp
  Userland/Libraries/LibWeb/Painting/RadioButtonPaintable.cpp
  Userland/Libraries/LibWeb/Painting/VideoPaintable.cpp
  Userland/Libraries/LibWeb/UIEvents/MouseButton.h
  Userland/Libraries/LibWeb/UIEvents/MouseEvent.cpp
  Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Labels: 👀 pr-needs-review

#23882 Ports: Update freeciv to version 3.1.1
  Ports/AvailablePorts.md
  Ports/freeciv/package.sh
Labels: ci-flakiness, 👀 pr-needs-review

#24533 LibWasm: Fix memarg multi-memory reading
  Userland/Libraries/LibWasm/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#24537 LibWeb/Fetch: Update "HTTP fetch" algorithm to latest spec comments
  Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
Labels: 👀 pr-needs-review

#24511 Kernel: Remove redundant VERIFY()
  Kernel/Memory/Region.cpp
Labels: 👀 pr-needs-review

#24544 Test: Skip flakey Text/input/WebAnimations/misc/DocumentTimeline test
  Tests/LibWeb/TestConfig.ini
Labels: 👀 pr-needs-review

#24540 LibWeb/CSS: Make FontFaceSet extend EventTarget & implement event handlers
  Userland/Libraries/LibWeb/CSS/FontFaceSet.cpp
  Userland/Libraries/LibWeb/CSS/FontFaceSet.h
  Userland/Libraries/LibWeb/CSS/FontFaceSet.idl
  Userland/Libraries/LibWeb/HTML/EventNames.h
Labels: 👀 pr-needs-review

#24541 Ports: Update dmidecode to version 3.6
  Ports/AvailablePorts.md
  Ports/dmidecode/package.sh
Labels: ci-flakiness, 👀 pr-needs-review

#24520 Kernel: Add method to clean up remapping region loops
  Kernel/Memory/AnonymousVMObject.cpp
  Kernel/Memory/InodeVMObject.cpp
  Kernel/Memory/SharedFramebufferVMObject.cpp
  Kernel/Memory/VMObject.cpp
  Kernel/Memory/VMObject.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci, ✅ pr-community-approved

#24547 LibWeb: Do not release_value twice parsing a referrer policy
  Userland/Libraries/LibWeb/ReferrerPolicy/AbstractOperations.cpp
Labels: 👀 pr-needs-review

#24550 Meta: Update notice to new Ladybird repository name
  Documentation/BuildInstructionsLadybird.md
  README.md
Labels: 👀 pr-needs-review

#24552 Meta: Use Python>=3.10 in the test262 action
  .github/workflows/libjs-test262.yml
Labels: 👀 pr-needs-review

#24551 Kernel: Clean up duplicated code
  Kernel/Memory/InodeVMObject.cpp
Labels: 👀 pr-needs-review

#24557 Tests: Skip Text/input/HTML/form-image-submission.html (flaky)
  Tests/LibWeb/TestConfig.ini
Labels: 👀 pr-needs-review

#24334 CrashReporter: Don't update window progress if window has been closed
  Userland/Applications/CrashReporter/main.cpp
Labels: 👀 pr-needs-review

#24565 Meta: Remove test262 workflow
  .github/workflows/libjs-test262.yml
Labels: 👀 pr-needs-review

#24568 Build: Update mold version to fix build problems
  Toolchain/BuildMold.sh
Labels: 👀 pr-needs-review

#24570 Utilities/du: Add options to filter files with min and max sizes
  Base/usr/share/man/man1/du.md
  Userland/Utilities/du.cpp
Labels: 👀 pr-needs-review

#24562 Ports: Update perl5 to 5.40.0
  Ports/AvailablePorts.md
  Ports/perl5/package.sh
  Ports/perl5/patches/0001-Disable-nanosleep.patch
  Ports/perl5/patches/0001-pp_sys-Avoid-redefining-h_errno.patch
  Ports/perl5/patches/0003-configure-Add-hint-for-serenity.patch
  Ports/perl5/patches/ReadMe.md
Labels: 👀 pr-needs-review

#24539 Ports: Add SpaceCadetPinball
  Ports/AvailablePorts.md
  Ports/SpaceCadetPinball/package.sh
Labels: 👀 pr-needs-review

#24508 Ports: Add Schism Tracker
  Ports/AvailablePorts.md
  Ports/schismtracker/package.sh
Labels: 👀 pr-needs-review

#24575 LibGfx/WebPWriter: Use AK's count_required_bits(), align_up_to()
  Userland/Libraries/LibGfx/ImageFormats/WebPWriterLossless.cpp
Labels: 👀 pr-needs-review

#24579 Fuzzers: Use libc++ on OSS-Fuzz for Lagom code generators
  Meta/Lagom/BuildFuzzers.sh
Labels: 👀 pr-needs-review

#24573 SystemMonitor: Add pause and refresh actions
  Userland/Applications/SystemMonitor/main.cpp
Labels: 👀 pr-needs-review

#24585 Meta: Add a warning suppression used in the cmake build to the gn build
  Meta/gn/build/BUILD.gn
Labels: 👀 pr-needs-review

#24584 LibJS: Initialize fields of on-stack `buf` structure
  Userland/Libraries/LibJS/Heap/Heap.cpp
Labels: 👀 pr-needs-review

#24435 Kernel: Support re-mapping MMIOVMObject-backed regions
  Kernel/Memory/MMIOVMObject.cpp
  Kernel/Memory/MMIOVMObject.h
  Kernel/Memory/Region.cpp
  Kernel/Memory/VMObject.h
Labels: 👀 pr-needs-review

#24586 LibIPC: Allow sync messages to completely block the event loop
  Userland/Libraries/LibIPC/Connection.cpp
  Userland/Libraries/LibIPC/Connection.h
  Userland/Libraries/LibIPC/Message.cpp
  Userland/Libraries/LibIPC/Message.h
Labels: 👀 pr-needs-review

#24467 LibAudio: Replace DeprecatedFlyString with FlyString
  Userland/Libraries/LibAudio/FlacLoader.cpp
  Userland/Libraries/LibAudio/Loader.cpp
  Userland/Libraries/LibAudio/LoaderError.h
  Userland/Libraries/LibAudio/MP3Loader.cpp
  Userland/Libraries/LibAudio/QOALoader.cpp
  Userland/Libraries/LibAudio/WavLoader.cpp
Labels: ✅ pr-community-approved

#24588 Kernel/Storage: Dump storage devices to the framebuffer console as well
  Kernel/Devices/Storage/StorageManagement.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#24589 Cherry-pick "LibWebSocket: Use HTTP::HeaderMap in WebSocket code"
  Userland/Libraries/LibProtocol/RequestClient.cpp
  Userland/Libraries/LibProtocol/RequestClient.h
  Userland/Libraries/LibWebSocket/ConnectionInfo.h
  Userland/Libraries/LibWebSocket/WebSocket.cpp
  Userland/Services/RequestServer/ConnectionFromClient.cpp
  Userland/Services/RequestServer/ConnectionFromClient.h
  Userland/Services/RequestServer/RequestServer.ipc
Labels: 👀 pr-needs-review

#24580 PixelPaint: Fixed some Color Masking issues
  Userland/Applications/PixelPaint/ImageMasking.cpp
Labels: 👀 pr-needs-review

#24591 Cherry-pick "LibWeb: Implement stub for ElementInternals"
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
  Meta/gn/secondary/Userland/Libraries/LibWeb/HTML/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWeb/idl_files.gni
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/DOM/Element.h
  Userland/Libraries/LibWeb/Forward.h
  Userland/Libraries/LibWeb/HTML/ElementInternals.cpp
  Userland/Libraries/LibWeb/HTML/ElementInternals.h
  Userland/Libraries/LibWeb/HTML/ElementInternals.idl
  Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLElement.h
  Userland/Libraries/LibWeb/HTML/HTMLElement.idl
  Userland/Libraries/LibWeb/idl_files.cmake
Labels: 👀 pr-needs-review

#24596 Cherry-pick "LibWeb: Check for navigable destruction in declarative refresh timer"
  Userland/Libraries/LibWeb/DOM/Document.cpp
Labels: 👀 pr-needs-review

#24597 Cherry-pick "LibWeb: Avoid null dereference when performing mixed content checks"
  Userland/Libraries/LibWeb/MixedContent/AbstractOperations.cpp
Labels: 👀 pr-needs-review

#24595 Cherry-pick "LibWeb: Implement HTMLImageElement::decode with a few FIXMEs"
  Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLImageElement.h
  Userland/Libraries/LibWeb/HTML/HTMLImageElement.idl
Labels: 👀 pr-needs-review

#24602 Cherry-pick "Tests/LibWeb: Wait until document fully loaded before simulating click"
  Tests/LibWeb/TestConfig.ini
  Tests/LibWeb/Text/input/HTML/form-image-submission.html
Labels: 👀 pr-needs-review

#24607 Meta: Port recent changes to the GN build
  Meta/gn/secondary/Userland/Libraries/LibWeb/SVG/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWeb/idl_files.gni
Labels: 👀 pr-needs-review

#24609 Cherry-pick "LibWeb: Add stub for ValidityState"
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/Forward.h
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.idl
  Userland/Libraries/LibWeb/HTML/ValidityState.cpp
  Userland/Libraries/LibWeb/HTML/ValidityState.h
  Userland/Libraries/LibWeb/HTML/ValidityState.idl
  Userland/Libraries/LibWeb/idl_files.cmake
Labels: 👀 pr-needs-review

#24606 Cherry-pick "LibWebView: Allow data URLs in sanitize_url"
  Tests/LibWebView/TestWebViewURL.cpp
  Userland/Libraries/LibWebView/URL.cpp
Labels: 👀 pr-needs-review

#24610 Meta: Port recent changes to the GN build
  Meta/gn/secondary/Userland/Libraries/LibWeb/HTML/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWeb/idl_files.gni
Labels: 👀 pr-needs-review

#24611 Cherry-pick "LibWeb/CSS: Avoid capturing structured binding in generic lambda"
  Userland/Libraries/LibWeb/CSS/StyleValues/EasingStyleValue.cpp
Labels: 👀 pr-needs-review

#24612 Cherry-pick "LibWeb: Disallow pasting into non-editable text nodes"
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
Labels: 👀 pr-needs-review

#24614 Ladybird/AppKit: Send correct mouse event on right click
  Ladybird/AppKit/UI/LadybirdWebView.mm
Labels: 👀 pr-needs-review

#24615 Ladybird/AppKit: Send mouse event on middle click
  Ladybird/AppKit/UI/LadybirdWebView.mm
Labels: 👀 pr-needs-review

#24616 Cherry-pick "LibWeb: Don't set hashChange for classic history navigate events"
  Userland/Libraries/LibWeb/HTML/Navigation.cpp
Labels: 👀 pr-needs-review

#24618 Cherry-pick "LibWeb: Refactor DOM parsing APIs"
  Meta/gn/secondary/Userland/Libraries/LibWeb/DOMParsing/BUILD.gn
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/DOM/Element.cpp
  Userland/Libraries/LibWeb/DOM/Element.h
  Userland/Libraries/LibWeb/DOM/Range.cpp
  Userland/Libraries/LibWeb/DOM/Range.idl
  Userland/Libraries/LibWeb/DOM/ShadowRoot.cpp
  Userland/Libraries/LibWeb/DOMParsing/InnerHTML.cpp
  Userland/Libraries/LibWeb/DOMParsing/InnerHTML.h
Labels: 👀 pr-needs-review

#24619 Cherry-pick "LibWeb: Implement CloseWatcher API"
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
  Meta/gn/secondary/Userland/Libraries/LibWeb/HTML/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWeb/idl_files.gni
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/DOM/EventTarget.cpp
  Userland/Libraries/LibWeb/Forward.h
  Userland/Libraries/LibWeb/HTML/CloseWatcher.cpp
  Userland/Libraries/LibWeb/HTML/CloseWatcher.h
  Userland/Libraries/LibWeb/HTML/CloseWatcher.idl
  Userland/Libraries/LibWeb/HTML/CloseWatcherManager.cpp
  Userland/Libraries/LibWeb/HTML/CloseWatcherManager.h
  Userland/Libraries/LibWeb/HTML/Window.cpp
  Userland/Libraries/LibWeb/HTML/Window.h
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
  Userland/Libraries/LibWeb/idl_files.cmake
Labels: 👀 pr-needs-review

#24617 Cherry-pick "LibWeb: Add HTMLSelectElement showPicker()"
  Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLSelectElement.h
  Userland/Libraries/LibWeb/HTML/HTMLSelectElement.idl
Labels: 👀 pr-needs-review

#24506 Utilities/nc: Don't use LibC `gethostbyname`, add an option to test a TCP-listening service
  Base/usr/share/man/man1/nc.md
  Userland/Utilities/nc.cpp
Labels: 👀 pr-needs-review

#24620 Cherry-pick "LibWeb: Prevent select.click() opening the dropdown"
  Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp
Labels: 👀 pr-needs-review

#24621 Cherry-pick "LibWeb: Implement dialog element's close watcher"
  Userland/Libraries/LibWeb/HTML/CloseWatcher.h
  Userland/Libraries/LibWeb/HTML/HTMLDialogElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLDialogElement.h
Labels: 👀 pr-needs-review

#24623 Cherry-pick "LibWeb: Add attribute list that must always be compared without casing"
  Tests/LibWeb/Ref/css-case-insensitive-html-attributes-selector.html
  Tests/LibWeb/Ref/reference/css-case-insensitive-html-attributes-selector-ref.html
  Userland/Libraries/LibWeb/CSS/Parser/Parser.h
  Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp
Labels: 👀 pr-needs-review

#24622 Cherry-pick "LibWeb: Implement unsafe HTML parsing methods"
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/DOM/Document.idl
  Userland/Libraries/LibWeb/DOM/Element.cpp
  Userland/Libraries/LibWeb/DOM/Element.h
  Userland/Libraries/LibWeb/DOM/Element.idl
  Userland/Libraries/LibWeb/DOM/Node.cpp
  Userland/Libraries/LibWeb/DOM/Node.h
  Userland/Libraries/LibWeb/DOM/ShadowRoot.cpp
  Userland/Libraries/LibWeb/DOM/ShadowRoot.h
  Userland/Libraries/LibWeb/DOM/ShadowRoot.idl
  Userland/Libraries/LibWeb/HTML/DOMParser.cpp
  Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
  Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.h
Labels: 👀 pr-needs-review

#24499 Utilities/wc: Seek the input file(s) if only -c is passed
  Userland/Utilities/wc.cpp
Labels: 👀 pr-needs-review

#24628 AK+LibTest: Choose definition of CO_TRY and CO_TRY_OR_FAIL more robustly
  AK/Coroutine.h
  AK/Platform.h
  Tests/AK/TestCoroutine.cpp
  Userland/Libraries/LibHTTP/Http11Connection.h
  Userland/Libraries/LibTest/AsyncTestCase.h
Labels: 👀 pr-needs-review

#24629 Everywhere: Define even more destructors out of line
  AK/MemoryStream.h
  Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Function.cpp
  Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Function.h
  Userland/Libraries/LibCore/Process.h
  Userland/Libraries/LibGUI/Event.cpp
  Userland/Libraries/LibGUI/Event.h
  Userland/Libraries/LibGUI/HeaderView.cpp
  Userland/Libraries/LibGUI/HeaderView.h
Labels: 👀 pr-needs-review

#24632 Meta: Enable VirtIO on Windows QEMU
  Meta/run.py
Labels: 👀 pr-needs-review

#24634 LibWasm/WASI: Don't convert enums and u8s into i64
  Userland/Libraries/LibWasm/WASI/Wasi.cpp
Labels: 👀 pr-needs-review
