Repository SerenityOS/serenity, pull requests merged in 2024-03, with the labels that each got.

#23407 LibWeb: Don't crash in offset_parent() if no ancestor element found
  Tests/LibWeb/Text/expected/Element-offsetParent-of-iframe.txt
  Tests/LibWeb/Text/input/Element-offsetParent-of-iframe.html
  Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
Labels: 👀 pr-needs-review

#23409 LibWeb: Empty CE reaction queue instead of destroying it on exception
  Tests/LibWeb/Text/expected/HTML/custom-elements-throw-in-constructor.txt
  Tests/LibWeb/Text/input/HTML/custom-elements-throw-in-constructor.html
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: 👀 pr-needs-review

#23411 LibWeb: Reduce paintable tree traversals during hit-testing
  Tests/LibWeb/Text/expected/hit_testing/positioned-z-index-0-and-floats.txt
  Tests/LibWeb/Text/input/hit_testing/positioned-z-index-0-and-floats.html
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
  Userland/Libraries/LibWeb/Painting/StackingContext.h
  Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp
Labels: 👀 pr-needs-review

#23413 LibJS/Bytecode: Handle awkward initialization case for duplicate `var`
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
  Userland/Libraries/LibJS/Tests/var-scoping.js
Labels: 👀 pr-needs-review

#23415 LibWeb: Make Paintable::containing_block() return a PaintableBox*
  Userland/Libraries/LibWeb/DOM/Element.cpp
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
  Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
  Userland/Libraries/LibWeb/Painting/Paintable.cpp
  Userland/Libraries/LibWeb/Painting/Paintable.h
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
  Userland/Libraries/LibWeb/Painting/PaintableFragment.cpp
  Userland/Libraries/LibWeb/Painting/SVGPaintable.cpp
  Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp
Labels: 👀 pr-needs-review

#23418 CI: Strip binaries and libraries during the installation step, reduce ccache size
  Meta/Azure/Caches.yml
  Meta/Azure/Lagom.yml
Labels: 👀 pr-needs-review

#23425 LibWeb: Skip large stacking context in gpu painter only if it allocates
  Userland/Libraries/LibWeb/Painting/CommandExecutorGPU.cpp
Labels: 👀 pr-needs-review

#23426 LibWeb: Correctly set @keyframe rule's effect target
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Labels: 👀 pr-needs-review

#23430 LibHTTP: Disable finish repeat timer before deferring job completion
  Userland/Libraries/LibHTTP/Job.cpp
Labels: 👀 pr-needs-review

#23434 Keymap: Draw the current keymap text with the correct theme color
  Userland/Applets/Keymap/KeymapStatusWidget.cpp
Labels: 👀 pr-needs-review

#23436 LibPDF: Silently ignore BX / EX operators
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: 👀 pr-needs-review

#23431 LibWeb: Use a precalculated list of positioned descendants for painting
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Labels: 👀 pr-needs-review

#23432 LibWeb: Do not issue `change` event for every update of color input
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
  Userland/Libraries/LibWeb/Page/Page.cpp
Labels: 👀 pr-needs-review

#22944 LibWeb: Add input and textarea minlength and maxlength
  Tests/LibWeb/Text/expected/input-maxlength.txt
  Tests/LibWeb/Text/expected/textarea-maxlength.txt
  Tests/LibWeb/Text/input/input-maxlength.html
  Tests/LibWeb/Text/input/textarea-maxlength.html
  Userland/Libraries/LibWeb/DOM/Text.h
  Userland/Libraries/LibWeb/HTML/AttributeNames.h
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.idl
  Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.h
  Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.idl
  Userland/Libraries/LibWeb/HTML/Numbers.cpp
  Userland/Libraries/LibWeb/HTML/Numbers.h
  Userland/Libraries/LibWeb/Page/EditEventHandler.cpp
Labels: 👀 pr-needs-review

#23437 Escalator: Set focus to password input automatically
  Userland/Applications/Escalator/EscalatorWindow.cpp
Labels: 👀 pr-needs-review

#23447 LibWeb: Remove wrappers for gradient painting command recording
  Userland/Libraries/LibWeb/CSS/StyleValues/ConicGradientStyleValue.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/LinearGradientStyleValue.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/RadialGradientStyleValue.cpp
  Userland/Libraries/LibWeb/Painting/GradientPainting.cpp
  Userland/Libraries/LibWeb/Painting/GradientPainting.h
Labels: 👀 pr-needs-review

#23433 Ports: Fix SRB2 asset file download
  Ports/SRB2/package.sh
Labels: 👀 pr-needs-review

#23441 Base: Add emoji
  Base/res/emoji/U+1F410.png
  Base/res/emoji/U+1F45E.png
  Base/res/emoji/U+1F45F.png
  Base/res/emoji/U+1F460.png
  Base/res/emoji/U+1F574.png
Labels: 👀 pr-needs-review

#23459 Ports: Update Python to 3.12.2
  Ports/AvailablePorts.md
  Ports/python3/version.sh
Labels: 👀 pr-needs-review

#23457 DynamicLoader: Disable stack protector in some files for RISC-V
  Userland/DynamicLoader/CMakeLists.txt
Labels: 👀 pr-needs-review

#23461 LibCore: Fix `AK_OS_ANDROID` build
  Userland/Libraries/LibCore/Environment.cpp
Labels: 👀 pr-needs-review

#23460 PDFViewer: Hide the rendering diagnostics window by default
  Userland/Applications/PDFViewer/PDFViewer.cpp
  Userland/Applications/PDFViewer/PDFViewer.h
  Userland/Applications/PDFViewer/PDFViewerWidget.cpp
  Userland/Applications/PDFViewer/PDFViewerWidget.h
  Userland/Libraries/LibPDF/Renderer.h
Labels: ✅ pr-community-approved

#23435 Escalator: Allow failed password attempts to be retried
  Userland/Applications/Escalator/EscalatorWindow.cpp
  Userland/Applications/Escalator/EscalatorWindow.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#23334 Kernel: Replace C-idioms with AK types in RTL8168 network adapter
  Kernel/Net/Realtek/RTL8168NetworkAdapter.cpp
  Kernel/Net/Realtek/RTL8168NetworkAdapter.h
Labels: ✅ pr-community-approved

#23472 LibJS/Bytecode: Always evaluate LHS first in assignment expressions
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
  Userland/Libraries/LibJS/Bytecode/Generator.cpp
  Userland/Libraries/LibJS/Tests/assignment-evaluation-order.js
Labels: 👀 pr-needs-review

#23474 LibJS/Bytecode: Don't fuse unrelated compare and jump in peephole pass
  Userland/Libraries/LibJS/Bytecode/Pass/Peephole.cpp
  Userland/Libraries/LibJS/Tests/optimizer-bugs.js
Labels: 👀 pr-needs-review

#23475 LibWeb: Always check paintable boxes children during hit-testing
  Tests/LibWeb/Text/expected/hit_testing/box-outside-of-abspos-containing-block-border-rect.txt
  Tests/LibWeb/Text/expected/hit_testing/open-details-by-clicking-on-triangle.txt
  Tests/LibWeb/Text/input/hit_testing/box-outside-of-abspos-containing-block-border-rect.html
  Tests/LibWeb/Text/input/hit_testing/open-details-by-clicking-on-triangle.html
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Labels: 👀 pr-needs-review

#23466 Ports/zlib: Switch to tarball copies hosted on GitHub
  Ports/zlib/package.sh
Labels: 👀 pr-needs-review

#23479 LibWeb: Respect "auto flow" property in grid layout
  Tests/LibWeb/Layout/expected/grid/placement-10.txt
  Tests/LibWeb/Layout/expected/grid/placement-5.txt
  Tests/LibWeb/Layout/expected/grid/placement-6.txt
  Tests/LibWeb/Layout/expected/grid/placement-7.txt
  Tests/LibWeb/Layout/expected/grid/placement-8.txt
  Tests/LibWeb/Layout/expected/grid/placement-9.txt
  Tests/LibWeb/Layout/input/grid/placement-10.html
  Tests/LibWeb/Layout/input/grid/placement-5.html
  Tests/LibWeb/Layout/input/grid/placement-6.html
  Tests/LibWeb/Layout/input/grid/placement-7.html
  Tests/LibWeb/Layout/input/grid/placement-8.html
  Tests/LibWeb/Layout/input/grid/placement-9.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#23482 RequestServer: Transfer ownership of Protocols to all_protocols map
  Ladybird/Android/src/main/cpp/RequestServerService.cpp
  Ladybird/RequestServer/main.cpp
  Userland/Services/RequestServer/GeminiProtocol.cpp
  Userland/Services/RequestServer/GeminiProtocol.h
  Userland/Services/RequestServer/HttpProtocol.cpp
  Userland/Services/RequestServer/HttpProtocol.h
  Userland/Services/RequestServer/HttpsProtocol.cpp
  Userland/Services/RequestServer/HttpsProtocol.h
  Userland/Services/RequestServer/Protocol.cpp
  Userland/Services/RequestServer/Protocol.h
  Userland/Services/RequestServer/main.cpp
Labels: 👀 pr-needs-review

#23485 Everywhere: Merge the WebSocket service into RequestServer
  Ladybird/Android/src/main/AndroidManifest.xml
  Ladybird/Android/src/main/cpp/WebContentService.cpp
  Ladybird/Android/src/main/cpp/WebContentServiceJNI.cpp
  Ladybird/Android/src/main/cpp/WebSocketService.cpp
  Ladybird/Android/src/main/java/org/serenityos/ladybird/WebContentService.kt
  Ladybird/Android/src/main/java/org/serenityos/ladybird/WebSocketService.kt
  Ladybird/CMakeLists.txt
  Ladybird/HelperProcess.cpp
  Ladybird/HelperProcess.h
  Ladybird/Qt/RequestManagerQt.cpp
  Ladybird/Qt/RequestManagerQt.h
  Ladybird/Qt/WebSocketClientManagerQt.cpp
  Ladybird/Qt/WebSocketClientManagerQt.h
  Ladybird/RequestServer/CMakeLists.txt
  Ladybird/WebContent/CMakeLists.txt
  Ladybird/WebContent/main.cpp
  Ladybird/WebSocket/CMakeLists.txt
  Ladybird/WebSocket/main.cpp
  Ladybird/WebWorker/main.cpp
  Meta/Lagom/CMakeLists.txt
  Meta/gn/secondary/Ladybird/BUILD.gn
  Meta/gn/secondary/Ladybird/RequestServer/BUILD.gn
  Meta/gn/secondary/Ladybird/WebSocket/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibProtocol/BUILD.gn
  Userland/Applications/Browser/CMakeLists.txt
  Userland/Libraries/LibProtocol/CMakeLists.txt
  Userland/Libraries/LibProtocol/RequestClient.cpp
  Userland/Libraries/LibProtocol/RequestClient.h
  Userland/Libraries/LibProtocol/WebSocket.cpp
  Userland/Libraries/LibProtocol/WebSocket.h
  Userland/Libraries/LibProtocol/WebSocketClient.cpp
  Userland/Libraries/LibProtocol/WebSocketClient.h
  Userland/Libraries/LibWeb/Loader/ResourceLoader.h
  Userland/Libraries/LibWeb/WebSockets/WebSocket.cpp
  Userland/Libraries/LibWeb/WebSockets/WebSocket.h
  Userland/Libraries/LibWebView/CMakeLists.txt
  Userland/Libraries/LibWebView/RequestServerAdapter.cpp
  Userland/Libraries/LibWebView/RequestServerAdapter.h
  Userland/Libraries/LibWebView/WebSocketClientAdapter.cpp
  Userland/Libraries/LibWebView/WebSocketClientAdapter.h
  Userland/Services/CMakeLists.txt
  Userland/Services/RequestServer/CMakeLists.txt
  Userland/Services/RequestServer/ConnectionFromClient.cpp
  Userland/Services/RequestServer/ConnectionFromClient.h
  Userland/Services/RequestServer/RequestClient.ipc
  Userland/Services/RequestServer/RequestServer.ipc
  Userland/Services/WebContent/CMakeLists.txt
  Userland/Services/WebContent/main.cpp
  Userland/Services/WebSocket/CMakeLists.txt
  Userland/Services/WebSocket/ConnectionFromClient.cpp
  Userland/Services/WebSocket/ConnectionFromClient.h
  Userland/Services/WebSocket/WebSocketClient.ipc
  Userland/Services/WebSocket/WebSocketServer.ipc
  Userland/Services/WebSocket/main.cpp
  Userland/Services/WebWorker/main.cpp
  Userland/Utilities/telws.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#23488 Ladybird/Qt: Explicitly ignore wheel events with the ctrl key pressed
  Ladybird/Qt/WebContentView.cpp
Labels: 👀 pr-needs-review

#23494 LibWebView: Ensure we resolve cookie promises upon early returns
  Userland/Libraries/LibWebView/CookieJar.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#23497 LibWeb: Apply transform origin in Element::get_client_rects()
  Tests/LibWeb/Text/expected/element-get-bounding-client-rect-css-transform.txt
  Tests/LibWeb/Text/input/element-get-bounding-client-rect-css-transform.html
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: 👀 pr-needs-review

#23499 Ladybird: Include Userland/ in for Applications that use LibWeb
  Ladybird/CMakeLists.txt
  Ladybird/WebContent/CMakeLists.txt
  Ladybird/WebWorker/CMakeLists.txt
Labels: 👀 pr-needs-review

#23465 LibWeb: Account for absolutely positioned table wrappers
  Tests/LibWeb/Layout/expected/table/absolute-positioning-alignment.txt
  Tests/LibWeb/Layout/input/table/absolute-positioning-alignment.html
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/FormattingContext.h
Labels: 👀 pr-needs-review

#23492 LibWeb: Grid placement code refactoring
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#23508 Ports: Update serenity-theming use latest commit 955c253
  Ports/AvailablePorts.md
  Ports/serenity-theming/package.sh
Labels: 👀 pr-needs-review

#23487 LibGfx/CCITT: Fix most PDF files from 0000.zip
  Userland/Libraries/LibGfx/ImageFormats/CCITTDecoder.cpp
  Userland/Libraries/LibPDF/Filter.cpp
Labels: ✅ pr-community-approved

#23489 LibGfx+Fallout: Make ImageDecoder return ErrorOr
  Userland/Applications/FileManager/PropertiesWindow.cpp
  Userland/Applications/ImageViewer/ViewWidget.cpp
  Userland/Applications/Maps/MapWidget.cpp
  Userland/Libraries/LibGUI/ImageWidget.cpp
  Userland/Libraries/LibGfx/Bitmap.cpp
  Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.cpp
  Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.h
  Userland/Services/ImageDecoder/ConnectionFromClient.cpp
  Userland/Services/SpiceAgent/SpiceAgent.cpp
  Userland/Utilities/file.cpp
  Userland/Utilities/icc.cpp
  Userland/Utilities/image.cpp
Labels: ✅ pr-community-approved

#23498 LibPDF: Make truetype fonts marked as symbol fonts actually work
  Userland/Libraries/LibPDF/Fonts/PDFFont.h
  Userland/Libraries/LibPDF/Fonts/TrueTypeFont.cpp
  Userland/Libraries/LibPDF/Fonts/Type1Font.cpp
Labels: 👀 pr-needs-review

#23504 LibGfx/TIFF: Reject images with a null value in tile's dimensions
  Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Labels: ✅ pr-community-approved

#23505 LibGfx: Prevent overflow when creating CMYKBitmaps
  Userland/Libraries/LibGfx/CMYKBitmap.cpp
Labels: 👀 pr-needs-review

#23464 Base: Add Emoji
  Base/res/emoji/U+1F6B7.png
  Base/res/emoji/U+1F97F.png
  Base/res/emoji/U+1F9EB.png
  Base/res/emoji/U+1FA94.png
  Base/res/emoji/U+1FAC0.png
Labels: 👀 pr-needs-review

#23467 Base: Remake Default Snake Sprites
  Base/res/graphics/snake/skins/Snake/corner.png
  Base/res/graphics/snake/skins/Snake/head.png
  Base/res/graphics/snake/skins/Snake/horizontal.png
  Base/res/graphics/snake/skins/Snake/tail.png
  Base/res/graphics/snake/skins/Snake/vertical.png
Labels: 👀 pr-needs-review

#23510 LibCrypto: Store ASN1 certificate timestamps as UnixDateTime
  Tests/LibCrypto/TestASN1.cpp
  Userland/Applications/CertificateSettings/CertificateStoreWidget.cpp
  Userland/Libraries/LibCrypto/ASN1/ASN1.cpp
  Userland/Libraries/LibCrypto/ASN1/ASN1.h
  Userland/Libraries/LibTLS/Certificate.cpp
  Userland/Libraries/LibTLS/Certificate.h
  Userland/Libraries/LibTLS/TLSv12.cpp
Labels: 👀 pr-needs-review

#23512 LibWeb: Add element adjust_computed_style and move set_property() to it
  Tests/LibWeb/Text/expected/HTML/form-image-submission.txt
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
  Userland/Libraries/LibWeb/DOM/Element.h
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
  Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLSelectElement.h
  Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.h
Labels: 👀 pr-needs-review

#23517 LibPDF: Clip stroke for B / B* operators
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: 👀 pr-needs-review

#23526 LibWeb: Add and use a helper to reject a promise with an exception
  Userland/Libraries/LibWeb/Crypto/SubtleCrypto.cpp
  Userland/Libraries/LibWeb/Fetch/Body.cpp
  Userland/Libraries/LibWeb/FileAPI/Blob.cpp
  Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
  Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBReader.cpp
  Userland/Libraries/LibWeb/Streams/ReadableStreamDefaultReader.cpp
  Userland/Libraries/LibWeb/Streams/ReadableStreamGenericReader.cpp
  Userland/Libraries/LibWeb/WebIDL/ExceptionOr.h
  Userland/Libraries/LibWeb/WebIDL/Promise.cpp
  Userland/Libraries/LibWeb/WebIDL/Promise.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#23537 LibGfx: Replace FLATTEN with ALWAYS_INLINE for `draw_glyph()` overload
  Userland/Libraries/LibGfx/Painter.cpp
Labels: 👀 pr-needs-review

#23540 LibWeb: Disable animations tests that depend on consistent timing
  Tests/LibWeb/TestConfig.ini
Labels: 👀 pr-needs-review

#23528 LibWeb: Use the parent container's y offset when finding static position
  Tests/LibWeb/Layout/expected/abspos-box-with-block-level-sibling.txt
  Tests/LibWeb/Layout/input/abspos-box-with-block-level-sibling.html
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/LayoutState.h
Labels: 👀 pr-needs-review

#23541 LibWeb: Use `resolve_grid_position` for abspos boxes layout in GFC
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#23548 LibGfx/JBIG2: Start implementing the generic region decoding procedure
  Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
Labels: ✅ pr-community-approved

#23531 LibWeb: Don't crash when visiting about:srcdoc
  Userland/Libraries/LibWeb/HTML/Navigable.cpp
Labels: 👀 pr-needs-review

#23559 Ports: Add missing dependency on glu to sdl12-compat
  Ports/sdl12-compat/package.sh
Labels: 👀 pr-needs-review

#23567 CI: Work around a libasan bug seen on Ubuntu with the Linux 6.5 kernel
  Meta/Azure/Lagom.yml
Labels: 👀 pr-needs-review

#23566 LibWeb: Implement the `window.opener` attribute
  Tests/LibWeb/Text/expected/HTML/Window-opener.txt
  Tests/LibWeb/Text/input/HTML/Window-opener.html
  Userland/Libraries/LibWeb/HTML/Window.cpp
  Userland/Libraries/LibWeb/HTML/Window.h
  Userland/Libraries/LibWeb/HTML/Window.idl
Labels: 👀 pr-needs-review

#23513 LibWeb: Allow CR inside of elements title attributes
  Ladybird/Qt/WebContentView.cpp
Labels: 👀 pr-needs-review

#23563 Snake: Set Snake as default skin
  Userland/Games/Snake/Game.cpp
  Userland/Games/Snake/main.cpp
Labels: 👀 pr-needs-review

#23249 Kernel: Implement support for RTL8168 chip versions 4, 5 and 6
  Kernel/Net/Realtek/RTL8168NetworkAdapter.cpp
  Kernel/Net/Realtek/RTL8168NetworkAdapter.h
Labels: 👀 pr-needs-review

#23573 Ports: Update lite-xl to 2.1.3
  Ports/AvailablePorts.md
  Ports/lite-xl/package.sh
  Ports/lite-xl/patches/0001-Add-SerenityOS-platform-support.patch
Labels: 👀 pr-needs-review

#23585 Tests: Remove logspam from TestPainter
  Tests/LibGfx/TestPainter.cpp
Labels: 👀 pr-needs-review

#23583 LibGfx/JBIG2: Simplify and restrict adaptive template pixel reading
  Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
Labels: ✅ pr-community-approved

#23582 MacPDF: Add "Show Images" debug menu entry
  Meta/Lagom/Contrib/MacPDF/MacPDFView.h
  Meta/Lagom/Contrib/MacPDF/MacPDFView.mm
  Meta/Lagom/Contrib/MacPDF/MacPDFWindowController.h
  Meta/Lagom/Contrib/MacPDF/MacPDFWindowController.mm
  Meta/Lagom/Contrib/MacPDF/MainMenu.xib
Labels: 👀 pr-needs-review

#23529 LibGfx/TIFF: Reject images with an incoherent number of BitsPerSample
  Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Labels: 👀 pr-needs-review

#23590 Meta: Handle output directories for multi-config CMake generators
  Ladybird/CMakeLists.txt
  Meta/CMake/lagom_install_options.cmake
Labels: 👀 pr-needs-review

#23556 LibGfx/JBIG2: Add arithmetic coding decoder
  Tests/LibGfx/TestImageDecoder.cpp
  Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
  Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.h
Labels: ✅ pr-community-approved

#23588 Userland/mount: Fix srcobfuscate => srchidden when printing mounts
  Userland/Utilities/mount.cpp
Labels: 👀 pr-needs-review

#23587 LibELF: Prevent negative index when determining dynamic symbol count
  Userland/Libraries/LibELF/DynamicObject.cpp
Labels: 👀 pr-needs-review

#23395 Kernel/Net: Add TCPSocket timer for TimeWait moving to Closed
  Kernel/Net/TCPSocket.cpp
  Kernel/Net/TCPSocket.h
Labels: 👀 pr-needs-review

#23605 LibWeb: Capture weak `this` ptr in HTMLTextAreaElement input callback
  Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.h
Labels: 👀 pr-needs-review

#23593 LibPDF+PDFViewer+MacPDF: Don't draw hidden text by default
  Meta/Lagom/Contrib/MacPDF/MacPDFView.h
  Meta/Lagom/Contrib/MacPDF/MacPDFView.mm
  Meta/Lagom/Contrib/MacPDF/MacPDFWindowController.h
  Meta/Lagom/Contrib/MacPDF/MacPDFWindowController.mm
  Meta/Lagom/Contrib/MacPDF/MainMenu.xib
  Userland/Applications/PDFViewer/PDFViewer.cpp
  Userland/Applications/PDFViewer/PDFViewer.h
  Userland/Applications/PDFViewer/PDFViewerWidget.cpp
  Userland/Libraries/LibPDF/Fonts/SimpleFont.cpp
  Userland/Libraries/LibPDF/Fonts/Type0Font.cpp
  Userland/Libraries/LibPDF/Renderer.h
Labels: 👀 pr-needs-review

#23611 Meta: Do not place headless-browser and WebDriver in libexec
  Ladybird/CMakeLists.txt
  Meta/gn/secondary/Ladybird/BUILD.gn
  Meta/gn/secondary/Ladybird/WebDriver/BUILD.gn
  Tests/LibWeb/WPT/run.sh
  Tests/LibWeb/rebaseline-libweb-test
Labels: 👀 pr-needs-review

#23613 LibWeb: A couple of shortcut handling fixes
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
Labels: 👀 pr-needs-review

#23614 LibWeb: Skip page scrolling for wheel events consumed by scrollable box
  Tests/LibWeb/Text/expected/wheel-events-consumed-by-scrollable-should-not-be-propagated-to-body-2.txt
  Tests/LibWeb/Text/input/wheel-events-consumed-by-scrollable-should-not-be-propagated-to-body-2.html
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
Labels: 👀 pr-needs-review

#23615 LibWeb: Update paint-only props only when needed in get_client_rects()
  Tests/LibWeb/Text/expected/element-get-bounding-client-rect-scroll-offset.txt
  Tests/LibWeb/Text/input/element-get-bounding-client-rect-scroll-offset.html
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: 👀 pr-needs-review

#23610 Meta: Correct gdb example in serenity.sh
  Meta/serenity.sh
Labels: 👀 pr-needs-review

#23618 LibGfx: Simplify path storage and tidy up APIs
  Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.cpp
  Userland/Libraries/LibGfx/Font/VectorFont.h
  Userland/Libraries/LibGfx/ImageFormats/TinyVGLoader.cpp
  Userland/Libraries/LibGfx/Path.cpp
  Userland/Libraries/LibGfx/Path.h
  Userland/Libraries/LibPDF/Renderer.cpp
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasPath.cpp
  Userland/Libraries/LibWeb/HTML/Path2D.cpp
  Userland/Libraries/LibWeb/SVG/SVGPathElement.cpp
Labels: 👀 pr-needs-review

#23629 LibWeb: Add basic implementation of has_a_rendering_opportunity()
  Userland/Libraries/LibWeb/HTML/Navigable.cpp
  Userland/Libraries/LibWeb/Page/Page.h
  Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
  Userland/Services/WebContent/PageClient.cpp
  Userland/Services/WebContent/PageClient.h
  Userland/Services/WebWorker/PageHost.h
Labels: 👀 pr-needs-review

#23569 Base: Add more emoji
  Base/home/anon/Documents/emoji-serenity.txt
  Base/res/emoji/U+1F3F4_U+E0062_U+E0071_U+E0062_U+E006F_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E0062_U+E0071_U+E0073_U+E0061_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E0062_U+E0071_U+E0073_U+E0065_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006B_U+E0072_U+E0031_U+E0031_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006B_U+E0072_U+E0032_U+E0039_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006B_U+E0072_U+E0033_U+E0030_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006B_U+E0072_U+E0034_U+E0031_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006B_U+E0072_U+E0034_U+E0034_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006B_U+E0072_U+E0034_U+E0036_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006B_U+E0072_U+E0034_U+E0038_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006B_U+E0072_U+E0034_U+E0039_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006E_U+E006C_U+E0062_U+E0071_U+E0031_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006E_U+E006C_U+E0062_U+E0071_U+E0032_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006E_U+E006C_U+E0062_U+E0071_U+E0033_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006E_U+E006C_U+E0064_U+E0072_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006E_U+E006C_U+E0066_U+E006C_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006E_U+E006C_U+E0066_U+E0072_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006E_U+E006C_U+E0067_U+E0065_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006E_U+E006C_U+E0067_U+E0072_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006E_U+E006C_U+E006C_U+E0069_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006E_U+E006C_U+E006E_U+E0062_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006E_U+E006C_U+E006E_U+E0068_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006E_U+E006C_U+E006F_U+E0076_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006E_U+E006C_U+E0075_U+E0074_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006E_U+E006C_U+E007A_U+E0065_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E006E_U+E006C_U+E007A_U+E0068_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E0075_U+E0073_U+E0061_U+E006C_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E0075_U+E0073_U+E0061_U+E007A_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E0075_U+E0073_U+E0074_U+E0078_U+E007F.png
  Base/res/emoji/U+1F97C.png
  Base/res/emoji/U+1F9E4.png
  Base/res/emoji/U+1F9E5.png
Labels: 👀 pr-needs-review

#23627 LibWeb: Skip cells layout in table box width calculation
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/TableFormattingContext.h
Labels: 👀 pr-needs-review

#23638 LibGfx: Output an SVG compatible string from `Path::to_byte_string()`
  Userland/Libraries/LibGfx/Path.cpp
  Userland/Libraries/LibGfx/Path.h
Labels: 👀 pr-needs-review

#23635 LibWeb: Add fast path to calculate invalidations for animated css props
  Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/CSS/StyleInvalidation.cpp
  Userland/Libraries/LibWeb/CSS/StyleInvalidation.h
  Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
  Userland/Libraries/LibWeb/CSS/StyleProperties.h
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Element.cpp
  Userland/Libraries/LibWeb/DOM/Element.h
Labels: 👀 pr-needs-review

#23645 LibGfx/WebPLossless: Fix out-of-bounds write in color indexing transform
  Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossless.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#23644 LibGfx/JBIG2: Make context index a u8
  Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#23651 LibWeb: Remove FLATTEN attribute from SelectorEngine::fast_matches
  Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
Labels: 👀 pr-needs-review

#23649 AK: Add base64url encoding and decoding methods
  AK/Base64.cpp
  AK/Base64.h
  Tests/AK/TestBase64.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#23368 Kernel/riscv64: Fix typo (CSR::SATP::Mode::{Sv67 => Sv57})
  Kernel/Arch/riscv64/CSR.h
Labels: 👀 pr-needs-review

#23662 LibWeb: Change update_style() to update animated style only if needed
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
Labels: 👀 pr-needs-review

#23665 LibWeb: Set animation update flag from Animation::invalidate_effect()
  Userland/Libraries/LibWeb/Animations/Animation.cpp
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#23667 AK: Use `else if constexpr` in explode_byte()
  AK/Types.h
Labels: ✅ pr-community-approved

#23658 Tests/LibGfx: Fix a small typo in the jbig2 decode tests
  Tests/LibGfx/TestImageDecoder.cpp
Labels: 👀 pr-needs-review

#23666 LibWeb: Do not include box's own scroll offset in get_client_rects()
  Tests/LibWeb/Text/expected/IntersectionObserver/observe-box-inside-container-with-scrollable-overflow.txt
  Tests/LibWeb/Text/input/IntersectionObserver/observe-box-inside-container-with-scrollable-overflow.html
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: 👀 pr-needs-review

#23677 LibWeb: Use an ancestor filter to quickly reject many CSS selectors
  Userland/Libraries/LibWeb/CSS/Selector.cpp
  Userland/Libraries/LibWeb/CSS/Selector.h
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
  Userland/Libraries/LibWeb/CSS/StyleComputer.h
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Labels: 👀 pr-needs-review

#23679 LibTLS: Avoid using new event loops when setting up connections
  Userland/Libraries/LibTLS/Socket.cpp
Labels: 👀 pr-needs-review

#23678 LibRIFF+LibGfx/ISOBMFF: Make ChunkID (de)serialization self-consistent
  Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/Boxes.cpp
  Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/Enums.h
  Userland/Libraries/LibRIFF/ChunkID.h
Labels: ✅ pr-community-approved

#23676 LibGfx/ISOBMFF: Support box header size 0 to mean "until end of data"
  Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/Boxes.cpp
  Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/Boxes.h
  Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/Reader.cpp
  Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/Reader.h
Labels: ✅ pr-community-approved

#23680 LibWeb: Change Element::closest() to check if any of selector matches
  Tests/LibWeb/Text/expected/DOM/Element-closest.txt
  Tests/LibWeb/Text/input/DOM/Element-closest.html
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: 👀 pr-needs-review

#23675 LibWeb+WebContent+Ladybird: Add ability to paste text from clipboard
  Ladybird/Qt/BrowserWindow.cpp
  Ladybird/Qt/BrowserWindow.h
  Ladybird/Qt/Tab.cpp
  Ladybird/cmake/ResourceFiles.cmake
  Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
  Userland/Libraries/LibWeb/HTML/BrowsingContext.h
  Userland/Libraries/LibWeb/Page/EditEventHandler.cpp
  Userland/Libraries/LibWeb/Page/EditEventHandler.h
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
  Userland/Libraries/LibWeb/Page/EventHandler.h
  Userland/Libraries/LibWebView/ViewImplementation.cpp
  Userland/Libraries/LibWebView/ViewImplementation.h
  Userland/Services/WebContent/ConnectionFromClient.cpp
  Userland/Services/WebContent/ConnectionFromClient.h
  Userland/Services/WebContent/WebContentServer.ipc
Labels: 👀 pr-needs-review

#23463 LibCore: Remove unnecessary or invalid write after child remove
  Userland/Libraries/LibCore/EventReceiver.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#23671 LibGfx/JPEG: Add a comment to inverse_dct_8x8()
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Labels: ✅ pr-community-approved

#23684 LibWeb: Look for labeled control in DOM tree instead of layout tree
  Tests/LibWeb/Text/expected/HTML/click-label-with-display-none-checkbox.txt
  Tests/LibWeb/Text/input/HTML/click-label-with-display-none-checkbox.html
  Userland/Libraries/LibWeb/HTML/HTMLLabelElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLLabelElement.h
  Userland/Libraries/LibWeb/HTML/HTMLLabelElement.idl
  Userland/Libraries/LibWeb/Layout/Label.cpp
  Userland/Libraries/LibWeb/Layout/Label.h
  Userland/Libraries/LibWeb/Painting/TextPaintable.cpp
Labels: 👀 pr-needs-review

#23673 Ports: Update rvvm to 0.6
  Ports/AvailablePorts.md
  Ports/rvvm/package.sh
  Ports/rvvm/patches/0001-Disable-threaded-IO-on-Serenity.patch
  Ports/rvvm/patches/ReadMe.md
Labels: 👀 pr-needs-review

#23659 Tests/LibGfx: Add a jbig2 file using basic symbol and text segments
  Tests/LibGfx/test-inputs/jbig2/bitmap-symbol.jbig2
Labels: 👀 pr-needs-review

#23656 LibJS: Separate validation of roundingIncrement option
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
  Userland/Libraries/LibJS/Runtime/Temporal/DurationPrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/InstantPrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.cpp
  Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainTime/PlainTime.prototype.round.js
Labels: ✅ pr-community-approved

#23653 LibJS: Rename ToSecondsStringPrecision to ToSecondsStringPrecisionRecord
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
  Userland/Libraries/LibJS/Runtime/Temporal/DurationPrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/InstantPrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
Labels: ✅ pr-community-approved

#23688 LibWeb: Allow any FC type for replaced boxes in dimension_box_on_line()
  Tests/LibWeb/Layout/expected/inline-flex-with-aspect-ratio.txt
  Tests/LibWeb/Layout/input/inline-flex-with-aspect-ratio.html
  Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Labels: 👀 pr-needs-review

#23694 LibRegex: Account for extra explicit And/Or in class parser assertion
  Tests/LibRegex/Regex.cpp
  Userland/Libraries/LibRegex/RegexParser.cpp
Labels: 👀 pr-needs-review

#23697 MacPDF: Fix capitalization of "Show Images" Debug menu entry
  Meta/Lagom/Contrib/MacPDF/MainMenu.xib
Labels: 👀 pr-needs-review

#23668 Shell: Add support for octal escapes in strings
  Userland/Shell/Parser.cpp
Labels: 👀 pr-needs-review

#23698 LibWeb: Reschedule repaint for navigables with ongoing painting
  Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
  Userland/Services/WebContent/PageClient.cpp
Labels: 👀 pr-needs-review

#23701 LibWeb: Normalize the angle delta in `CanvasPath::ellipse()`
  Tests/LibWeb/Ref/canvas-arcs-and-ellipses.html
  Tests/LibWeb/Ref/reference/canvas-arcs-and-ellipses-ref.html
  Tests/LibWeb/Ref/reference/images/canvas-arcs-and-ellipses-ref.png
  Userland/Libraries/LibWeb/HTML/Canvas/CanvasPath.cpp
Labels: 👀 pr-needs-review

#23696 LibGfx/JBIG2: Implement refinement coding for text segments
  Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
Labels: 👀 pr-needs-review

#23712 LibCore: Ignore timer events after stop() has been called
  Userland/Libraries/LibCore/EventReceiver.cpp
Labels: 👀 pr-needs-review

#23709 LibWeb: Remove cache for Paintable::is_visible()
  Tests/LibWeb/Ref/change-opacity.html
  Tests/LibWeb/Ref/reference/change-opacity-ref.html
  Userland/Libraries/LibWeb/Painting/Paintable.cpp
  Userland/Libraries/LibWeb/Painting/Paintable.h
Labels: 👀 pr-needs-review

#23711 LibGfx/JBIG2: Initialize POD members of refinement region input struct
  Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
Labels: 👀 pr-needs-review

#23719 CI: Revert ARCH_MMAP_RND_BITS libasan workaround
  Meta/Azure/Lagom.yml
Labels: 👀 pr-needs-review

#23713 Tests/LibGfx: Add a jbig2 file using refinement in the text segment
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/jbig2/bitmap-symbol-textrefine.jbig2
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#23669 LibC: Fix pthread_cond_broadcast() waking only one thread
  Userland/Libraries/LibC/pthread_cond.cpp
Labels: 👀 pr-needs-review

#23491 AnalogClock: Add feature to change and show time zone
  Userland/Applications/AnalogClock/AnalogClock.cpp
  Userland/Applications/AnalogClock/AnalogClock.h
  Userland/Applications/AnalogClock/main.cpp
Labels: 👀 pr-needs-review

#23530 Kernel/riscv64: Handle syscalls
  Kernel/Arch/riscv64/Interrupts.cpp
Labels: 👀 pr-needs-review

#23516 Kernel/riscv64: Add support for handling traps from userspace
  Kernel/Arch/riscv64/RegisterState.h
  Kernel/Arch/riscv64/boot.S
  Kernel/Arch/riscv64/mcontext.h
  Kernel/Arch/riscv64/trap_handler.S
Labels: 👀 pr-needs-review

#23515 Kernel/riscv64: Implement the signal trampoline
  Kernel/Tasks/Process.cpp
Labels: 👀 pr-needs-review

#23446 Kernel/riscv64: Don't hard-code the page fault reason on RISC-V
  Kernel/Arch/PageFault.cpp
  Kernel/Arch/PageFault.h
  Kernel/Arch/riscv64/Interrupts.cpp
  Kernel/Memory/Region.cpp
  Userland/Applications/CrashReporter/main.cpp
Labels: 👀 pr-needs-review

#23603 nix: clean up files, use good practices
  Documentation/BuildInstructionsLadybird.md
  Documentation/BuildInstructionsOther.md
  Ladybird/default.nix
  Toolchain/default.nix
  Toolchain/flake.nix
  flake.lock
  flake.nix
Labels: 👀 pr-needs-review

#23387 Kernel/riscv64: Only enable interrupts in trap handler if they were on
  Kernel/Arch/riscv64/Interrupts.cpp
Labels: 👀 pr-needs-review

#23359 Kernel/riscv64: Add Linux boot header
  Kernel/Arch/riscv64/boot.S
Labels: 👀 pr-needs-review

#23714 LibJS: Make PromiseJob store callback as a HeapFunction
  Userland/Libraries/LibJS/Forward.h
  Userland/Libraries/LibJS/Runtime/PromiseJobs.cpp
  Userland/Libraries/LibJS/Runtime/PromiseJobs.h
  Userland/Libraries/LibJS/Runtime/VM.cpp
  Userland/Libraries/LibJS/Runtime/VM.h
  Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp
Labels: 👀 pr-needs-review

#23730 LibWeb: Return the correct substring when parsing an HTTP quoted string
  Meta/gn/secondary/Tests/LibWeb/BUILD.gn
  Tests/LibWeb/CMakeLists.txt
  Tests/LibWeb/TestFetchInfrastructure.cpp
  Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP.cpp
Labels: ci-flakiness, 👀 pr-needs-review

#23728 LibCrypto: Allow CMS padding to span an entire block
  Userland/Libraries/LibCrypto/Cipher/Mode/Mode.h
Labels: ci-flakiness, ✅ pr-community-approved

#23731 LibJS: Do not unnecessarily revalidate a TypedArray
  Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
Labels: 👀 pr-needs-review

#23726 LibGfx/JBIG2: Don't assert on unexpected OOB values in the bitstream
  Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
Labels: ci-flakiness, 👀 pr-needs-review

#23718 LibJS: Remove ToTemporalDateTimeRoundingIncrement
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
  Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp
  Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
Labels: 👀 pr-needs-review

#23733 Tests/LibGfx: Add a jbig2 file using refinement in the symbol segment
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/jbig2/bitmap-symbol-symbolrefine.jbig2
Labels: 👀 pr-needs-review

#23740 LibGfx/JBIG2Loader: Add a short comment with spec history
  Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
Labels: 👀 pr-needs-review

#23747 headless-browser: Don't forget to load webpage before taking screenshot
  Userland/Utilities/headless-browser.cpp
Labels: 👀 pr-needs-review

#23746 Shell: Correctly auto format command lines consisting of only whitespace
  Userland/Shell/Formatter.h
Labels: 👀 pr-needs-review

#23755 Base+ImageViewer: Restore correct app icon
  Base/usr/share/man/man1/Applications/ImageViewer.md
  Userland/Applications/ImageViewer/CMakeLists.txt
Labels: 👀 pr-needs-review

#23753 LibWeb: Add basic "top layer" support
  Tests/LibWeb/Layout/expected/top-layer.txt
  Tests/LibWeb/Layout/input/top-layer.html
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/DOM/Element.h
  Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
  Userland/Libraries/LibWeb/HTML/HTMLDialogElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLDialogElement.h
  Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
  Userland/Libraries/LibWeb/Layout/TreeBuilder.h
Labels: 👀 pr-needs-review

#23757 LibWeb: Make empty images (no bitmap, no alt text) take no layout space
  Tests/LibWeb/Layout/expected/empty-image-should-be-zero-sized.txt
  Tests/LibWeb/Layout/expected/floating-replaced-element-percentage-padding-against-indefinite-width.txt
  Tests/LibWeb/Layout/expected/misc/corner-radius.txt
  Tests/LibWeb/Layout/expected/svg/svg-as-image-invalid.txt
  Tests/LibWeb/Layout/input/empty-image-should-be-zero-sized.html
  Userland/Libraries/LibWeb/Layout/ImageBox.cpp
Labels: 👀 pr-needs-review

#23765 LibCore: Turn LibCoreMinimal into a normal shared library
  Meta/gn/secondary/Ladybird/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibCore/BUILD.gn
  Userland/Libraries/LibCore/CMakeLists.txt
Labels: 👀 pr-needs-review

#23766 LibWeb: Don't fall apart on `transition: none` in CSS
  Tests/LibWeb/Layout/expected/css-transition-none.txt
  Tests/LibWeb/Layout/input/css-transition-none.html
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Labels: 👀 pr-needs-review

#23768 LibWeb: Fix infinite loop in CSS::Parser::parse_transition_value()
  Tests/LibWeb/Text/expected/WebAnimations/transitions/parse-transition-property.txt
  Tests/LibWeb/Text/input/WebAnimations/transitions/parse-transition-property.html
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#23767 LibXML: Don't emit a parser error for failing to resolve DTD URI
  Userland/Libraries/LibXML/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#23775 Meta: Fix the oss-fuzz build
  Meta/Lagom/CMakeLists.txt
Labels: 👀 pr-needs-review

#23738 LibWeb: Correct spec steps for serializable objects
  Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
Labels: 👀 pr-needs-review

#23776 LibWeb: Paint `SVGDecodedImageData` via `Navigable::paint()`
  Tests/LibWeb/Ref/assets/nested-svg.svg
  Tests/LibWeb/Ref/nested-svg-as-img.html
  Tests/LibWeb/Ref/reference/nested-svg-as-img-ref.html
  Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#23778 Ladybird/Qt: A couple of audio state button fixes specific to the Qt chrome
  Ladybird/Qt/BrowserWindow.cpp
  Ladybird/Qt/BrowserWindow.h
Labels: 👀 pr-needs-review

#23777 Ports: Update ports that depend on LibCore to depend on LibCoreMinimal
  Ports/OpenJDK/patches/0008-java.base-Enable-java.lang.Process-on-serenity.patch
  Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch
  Ports/SDL2_image/package.sh
  Ports/SDL2_mixer/package.sh
  Ports/SDL2_ttf/package.sh
  Ports/Super-Mario/patches/0003-Use-pkgconfig-instead-of-find_package-to-look-for-de.patch
  Ports/c-ray/patches/0004-Link-with-the-needed-serenity-libraries.patch
  Ports/nesalizer/patches/0001-Add-Serenity-to-Makefile.patch
  Ports/nesalizer/patches/ReadMe.md
  Ports/openssh/package.sh
  Ports/perl5/patches/0003-configure-Add-hint-for-serenity.patch
  Ports/xmp-cli/patches/0001-Add-support-for-Serenity-LibAudio.patch
Labels: 👀 pr-needs-review
