Repository SerenityOS/serenity, pull requests merged in 2024-01, with the labels that each got.

#22523 LibWeb/CSS: Fix crashing when calc() is used for border-radius
  Tests/LibWeb/Ref/calc-border-radius.html
  Tests/LibWeb/Ref/reference/calc-border-radius-ref.html
  Userland/Libraries/LibWeb/CSS/StyleValues/BorderRadiusStyleValue.cpp
Labels: 👀 pr-needs-review

#22526 LibWeb: Paint 1x1 backgrounds as color fill instead of tiling bitmap
  Userland/Libraries/LibWeb/CSS/StyleValues/AbstractImageStyleValue.h
  Userland/Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.h
  Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
Labels: 👀 pr-needs-review

#22525 Ladybird+LibWebView: Cleanup missing callbacks in InspectorClient
  Userland/Libraries/LibWebView/InspectorClient.cpp
Labels: 👀 pr-needs-review

#22296 Meta: Add RISC-V support to run.py
  Meta/run.py
Labels: 👀 pr-needs-review

#22268 Kernel: Only write text to serial console if no `ConsoleDevice` attached
  Kernel/kprintf.cpp
Labels: 👀 pr-needs-review

#22513 LibGfx/TIFF: Resolve more oss-fuzz issues
  Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Labels: 👀 pr-needs-review

#22543 LibWeb: Do not require box to be positioned to create stacking context
  Tests/LibWeb/Ref/abspos-z-index-painting-order.html
  Tests/LibWeb/Ref/reference/abspos-z-index-painting-order-ref.html
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Labels: 👀 pr-needs-review

#22544 LibWeb: Update create_new_child_navigable() after spec fix
  Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
Labels: 👀 pr-needs-review

#22542 LibWebView: Properly decode Base64-encoded strings as UTF-8
  Base/res/ladybird/inspector.js
Labels: 👀 pr-needs-review

#22535 LibPDF: Improve hex string parsing
  Tests/LibPDF/TestPDF.cpp
  Userland/Libraries/LibPDF/Parser.cpp
Labels: 👀 pr-needs-review

#22548 LibPDF: Scan for PDF file start in first 1024 bytes
  Userland/Libraries/LibPDF/Document.cpp
  Userland/Libraries/LibPDF/DocumentParser.cpp
  Userland/Libraries/LibPDF/DocumentParser.h
Labels: 👀 pr-needs-review

#22546 Tests/LibPDF: Add a PDF using the standard 14 fonts
  Tests/LibPDF/standard-14-fonts.pdf
Labels: 👀 pr-needs-review

#22549 LibWeb: Stop timers when finalizing a Window or WorkerGlobalScope
  Userland/Libraries/LibWeb/HTML/Window.cpp
  Userland/Libraries/LibWeb/HTML/Window.h
  Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
  Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.h
  Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.cpp
  Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.h
Labels: 👀 pr-needs-review

#22527 LibCompress/Brotli: Update the lookback buffer with uncompressed data
  Tests/LibCompress/TestBrotli.cpp
  Userland/Libraries/LibCompress/Brotli.cpp
Labels: 👀 pr-needs-review

#22559 Taskbar: Use name of Ladybird as default QuickLaunch
  Base/home/anon/.config/Taskbar.ini
Labels: 👀 pr-needs-review

#22570 LibGfx/OpenType: Survive simple glyphs with 0 contours
  Userland/Libraries/LibGfx/Font/OpenType/Glyf.cpp
Labels: 👀 pr-needs-review

#22569 LibPDF: An Encoding's /Differences entry is optional
  Userland/Libraries/LibPDF/Encoding.cpp
Labels: 👀 pr-needs-review

#22566 LibPDF: Tolerate trailing whitespace after %%EOF marker
  Userland/Libraries/LibPDF/DocumentParser.cpp
Labels: 👀 pr-needs-review

#22564 LibPDF: Port 59b50fa43f8c2 to xref and object streams
  Userland/Libraries/LibPDF/DocumentParser.cpp
Labels: 👀 pr-needs-review

#22500 LibGfx/TIFF: Don't stop decoding when failing to decode a tag
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/tiff/invalid_tag.tiff
  Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Labels: ✅ pr-community-approved

#22208 LibWeb/MimeSniff: Add a few more MIME type sniffing algos
  Tests/LibWeb/TestMimeSniff.cpp
  Userland/Libraries/LibWeb/MimeSniff/Resource.cpp
  Userland/Libraries/LibWeb/MimeSniff/Resource.h
Labels: 👀 pr-needs-review

#22580 LibPDF: Use mix() in SampledFunction::evaluate()
  Userland/Libraries/LibPDF/Function.cpp
Labels: 👀 pr-needs-review

#22581 LibWeb: Ignore layout/paint invalidations in subtree under display:none
  Userland/Libraries/LibWeb/DOM/Document.cpp
Labels: 👀 pr-needs-review

#22589 LibWeb: Remove available space from track sizing method params in GFC
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#22584 RequestServer: Make pre-connection job refcounted
  Userland/Services/RequestServer/ConnectionCache.h
  Userland/Services/RequestServer/ConnectionFromClient.cpp
  Userland/Services/RequestServer/GeminiProtocol.cpp
  Userland/Services/RequestServer/HttpCommon.h
Labels: 👀 pr-needs-review

#22595 LibWeb: Fix grid line name placement when repeat() is used
  Tests/LibWeb/Layout/expected/grid/line-placement-with-repeat.txt
  Tests/LibWeb/Layout/input/grid/line-placement-with-repeat.html
  Userland/Libraries/LibWeb/CSS/GridTrackSize.cpp
  Userland/Libraries/LibWeb/CSS/GridTrackSize.h
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#22588 LibWeb: Add support for LegacyWindowAlias IDL extended attribute
  Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWindowOrWorkerInterfaces.cpp
  Tests/LibWeb/Text/expected/geometry/legacy-window-alias.txt
  Tests/LibWeb/Text/input/geometry/legacy-window-alias.html
  Userland/Libraries/LibWeb/Geometry/DOMMatrix.idl
Labels: 👀 pr-needs-review

#22602 Kernel: Replace incorrect RTL8168 multicast config registers address
  Kernel/Net/Realtek/RTL8168NetworkAdapter.cpp
Labels: 👀 pr-needs-review

#22594 LibGfx/JPEG: More debug output + Refactor two u8 in a struct
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Labels: 👀 pr-needs-review

#22553 LibLine: Cursor jump non-space word and cut-and-paste functionality
  Userland/Libraries/LibLine/Editor.cpp
  Userland/Libraries/LibLine/Editor.h
  Userland/Libraries/LibLine/InternalFunctions.cpp
Labels: 👀 pr-needs-review

#22475 Kernel: Add unhandled cases for the FinWait2 state
  Kernel/Net/NetworkTask.cpp
Labels: 👀 pr-needs-review

#21385 Documentation: Expand package manager FAQ with pkg info
  Documentation/FAQ.md
Labels: 👀 pr-needs-review

#22522 HexEditor: Minor tweaks
  Userland/Applications/HexEditor/HexEditor.cpp
Labels: 👀 pr-needs-review

#22625 LibGUI: Make AboutDialog Copyright 2018-2024
  Userland/Libraries/LibGUI/AboutDialog.gml
Labels: 👀 pr-needs-review

#22306 LibWeb: Add input element valueAsDate property
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
  Tests/LibWeb/Text/expected/input-date.txt
  Tests/LibWeb/Text/input/input-date.html
  Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp
  Userland/Libraries/LibWeb/Animations/KeyframeEffect.h
  Userland/Libraries/LibWeb/HTML/Dates.cpp
  Userland/Libraries/LibWeb/HTML/Dates.h
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.idl
Labels: 👀 pr-needs-review

#22246 LibWeb: Allow input color to give continues updates
  Ladybird/AppKit/UI/LadybirdWebView.mm
  Ladybird/Qt/Tab.cpp
  Userland/Applications/Browser/Tab.cpp
  Userland/Libraries/LibWeb/HTML/ColorPickerUpdateState.h
  Userland/Libraries/LibWeb/Page/Page.cpp
  Userland/Libraries/LibWeb/Page/Page.h
  Userland/Libraries/LibWebView/ViewImplementation.cpp
  Userland/Libraries/LibWebView/ViewImplementation.h
  Userland/Services/WebContent/ConnectionFromClient.cpp
  Userland/Services/WebContent/ConnectionFromClient.h
  Userland/Services/WebContent/PageClient.cpp
  Userland/Services/WebContent/PageClient.h
  Userland/Services/WebContent/WebContentServer.ipc
Labels: 👀 pr-needs-review

#22627 LibWeb: Resolve grid item vertical margin/padding against CB width
  Tests/LibWeb/Layout/expected/grid/grid-item-vertical-padding-and-margin-percentages.txt
  Tests/LibWeb/Layout/input/grid/grid-item-vertical-padding-and-margin-percentages.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#22613 LibWeb: Remove rounding division for CSSPixels
  Tests/LibWeb/Layout/expected/abspos-box-with-replaced-element.txt
  Tests/LibWeb/Layout/expected/acid1.txt
  Tests/LibWeb/Layout/expected/block-and-inline/button-baseline-align.txt
  Tests/LibWeb/Layout/expected/block-and-inline/button-with-block-content-baseline-align.txt
  Tests/LibWeb/Layout/expected/block-and-inline/columns-33-percent-width.txt
  Tests/LibWeb/Layout/expected/block-and-inline/float-left-and-right-with-justified-text-in-between.txt
  Tests/LibWeb/Layout/expected/block-and-inline/small-percentage-margin.txt
  Tests/LibWeb/Layout/expected/css-font-size-math.txt
  Tests/LibWeb/Layout/expected/css-namespace-tag-name-selector.txt
  Tests/LibWeb/Layout/expected/flex/flex-item-with-intrinsic-aspect-ratio-and-max-height.txt
  Tests/LibWeb/Layout/expected/flex/reverse-flex-layout-with-space-between-and-space-around.txt
  Tests/LibWeb/Layout/expected/grid/grid-item-horizontal-margins-auto.txt
  Tests/LibWeb/Layout/expected/grid/grid-item-percentage-width.txt
  Tests/LibWeb/Layout/expected/grid/image-in-grid.txt
  Tests/LibWeb/Layout/expected/grid/item-column-span-2.txt
  Tests/LibWeb/Layout/expected/grid/justify-items.txt
  Tests/LibWeb/Layout/expected/grid/justify-self.txt
  Tests/LibWeb/Layout/expected/grid/place-self.txt
  Tests/LibWeb/Layout/expected/inline-size.txt
  Tests/LibWeb/Layout/expected/place-content-shorthand-property.txt
  Tests/LibWeb/Layout/expected/svg-text-with-viewbox.txt
  Tests/LibWeb/Layout/expected/svg-transforms-and-viewboxes.txt
  Tests/LibWeb/Layout/expected/svg/svg-different-types-of-opacity.txt
  Tests/LibWeb/Layout/expected/table/fixed-layout-percentage-width.txt
  Tests/LibWeb/Layout/expected/table/row-outer-size-with-computed-size.txt
  Tests/LibWeb/Layout/expected/table/row-span-and-nested-tables.txt
  Tests/LibWeb/Layout/input/block-and-inline/columns-33-percent-width.html
  Tests/LibWeb/Ref/reference/images/css-backgrounds-ref.png
  Tests/LibWeb/Ref/reference/images/object-fit-position.png
  Tests/LibWeb/Ref/reference/images/svg-background-no-natural-size-ref.png
  Tests/LibWeb/TestCSSPixels.cpp
  Userland/Libraries/LibWeb/PixelUnits.h
Labels: 👀 pr-needs-review

#22629 LibGfx/OpenType: Read the correct number of pairs from kern table
  Userland/Libraries/LibGfx/Font/OpenType/Tables.cpp
Labels: 👀 pr-needs-review

#22626 Meta: Update the year range in LICENSE
  LICENSE
Labels: 👀 pr-needs-review

#22624 LibWeb: Improve media document styling to center image
  Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
Labels: 👀 pr-needs-review

#22638 Tests/LibGfx: Fix a typo
  Tests/LibGfx/TestImageDecoder.cpp
Labels: 👀 pr-needs-review

#22640 LibWeb: Support auto-fill for rows in GFC
  Tests/LibWeb/Layout/expected/grid/auto-fill-rows.txt
  Tests/LibWeb/Layout/input/grid/auto-fill-rows.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Labels: 👀 pr-needs-review

#22616 LibWeb: Add DOMMatrix string constructor and set matrix value
  Tests/LibWeb/Text/expected/geometry/dommatrix-create.txt
  Tests/LibWeb/Text/expected/geometry/dommatrix-matrix-value.txt
  Tests/LibWeb/Text/input/geometry/dommatrix-create.html
  Tests/LibWeb/Text/input/geometry/dommatrix-matrix-value.html
  Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
  Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
  Userland/Libraries/LibWeb/CSS/StyleProperties.h
  Userland/Libraries/LibWeb/CSS/Transformation.cpp
  Userland/Libraries/LibWeb/CSS/Transformation.h
  Userland/Libraries/LibWeb/Geometry/DOMMatrix.cpp
  Userland/Libraries/LibWeb/Geometry/DOMMatrix.h
  Userland/Libraries/LibWeb/Geometry/DOMMatrix.idl
  Userland/Libraries/LibWeb/Geometry/DOMMatrixReadOnly.cpp
  Userland/Libraries/LibWeb/Geometry/DOMMatrixReadOnly.h
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Labels: 👀 pr-needs-review

#22641 LibWeb/CSS: Revert to PercentageOr::resolve() to be templated
  Userland/Libraries/LibWeb/CSS/PercentageOr.h
Labels: 👀 pr-needs-review

#22600 LibWeb: Fail to parse cookie date when date does not exist
  Base/res/html/misc/cookie.html
  Userland/Libraries/LibWeb/Cookie/ParsedCookie.cpp
Labels: 👀 pr-needs-review

#22642 LibWeb: Improve style propagation to anonymous wrappers
  Tests/LibWeb/Layout/expected/style-invalidation-line-height-propagation.txt
  Tests/LibWeb/Layout/expected/table/style-invalidation-propagation-to-table-wrapper.txt
  Tests/LibWeb/Layout/input/style-invalidation-line-height-propagation.html
  Tests/LibWeb/Layout/input/table/style-invalidation-propagation-to-table-wrapper.html
  Userland/Libraries/LibWeb/Layout/Node.cpp
  Userland/Libraries/LibWeb/Layout/Node.h
Labels: 👀 pr-needs-review

#22643 LibWeb: Take padding into account when resolving border radii
  Tests/LibWeb/Ref/border-radius-with-padding.html
  Tests/LibWeb/Ref/reference/border-radius-with-padding-ref.html
  Userland/Libraries/LibWeb/Layout/LayoutState.cpp
Labels: 👀 pr-needs-review

#22644 LibWebView+WebContent: Let the WebView client broadcast when it painted
  Userland/Libraries/LibWebView/ViewImplementation.cpp
  Userland/Services/WebContent/ConnectionFromClient.cpp
  Userland/Services/WebContent/ConnectionFromClient.h
  Userland/Services/WebContent/PageClient.cpp
  Userland/Services/WebContent/PageClient.h
  Userland/Services/WebContent/WebContentClient.ipc
  Userland/Services/WebContent/WebContentServer.ipc
Labels: 👀 pr-needs-review

#22649 LibGfx: Take into account unicode ranges to find font for space glyph
  Tests/LibWeb/Ref/reference/space-glyph-width-ref.html
  Tests/LibWeb/Ref/space-glyph-width.html
  Userland/Libraries/LibGfx/TextLayout.h
Labels: 👀 pr-needs-review

#22651 LibWeb: Add support for implicit grid lines formed by grid areas in GFC
  Tests/LibWeb/Layout/expected/grid/implicit-lines.txt
  Tests/LibWeb/Layout/input/grid/implicit-lines.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#22655 LibWeb: Fix reverse flex layout with `justify-content: normal`
  Tests/LibWeb/Layout/expected/flex/reverse-with-justify-content-normal.txt
  Tests/LibWeb/Layout/input/flex/reverse-with-justify-content-normal.html
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Labels: 👀 pr-needs-review

#22656 LibWeb/CSS: Resolve percentages in NumericCalculationNode
  Tests/LibWeb/Layout/expected/css-values/calc-min-with-percentage.txt
  Tests/LibWeb/Layout/input/css-values/calc-min-with-percentage.html
  Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
Labels: 👀 pr-needs-review

#22663 LibWeb: Fix drawing axis-aligned lines
  Tests/LibWeb/Ref/reference/images/svg-axis-aligned-lines-ref.png
  Tests/LibWeb/Ref/reference/svg-axis-aligned-lines-ref.html
  Tests/LibWeb/Ref/svg-axis-aligned-lines.html
  Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
Labels: 👀 pr-needs-review

#22668 LibWeb/CSS: Improve parsing of length percentage values for transforms
  Tests/LibWeb/Ref/reference/transform-calc-length-percentage-ref.html
  Tests/LibWeb/Ref/transform-calc-length-percentage.html
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
Labels: 👀 pr-needs-review

#22669 LibWeb: Implement calc() value equality check in a more efficient way
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
Labels: 👀 pr-needs-review

#22648 Hearts: Port to GML compiler
  Userland/Games/Hearts/CMakeLists.txt
  Userland/Games/Hearts/Game.cpp
  Userland/Games/Hearts/Hearts.gml
  Userland/Games/Hearts/MainWidget.h
  Userland/Games/Hearts/main.cpp
Labels: 👀 pr-needs-review

#22645 LibWeb/CSS: Remove nullpointer dereference in Parser
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/CSS/Parser/ParsingContext.cpp
Labels: 👀 pr-needs-review

#22469 Escalator: Port Escalator to GML Compiler
  Userland/Applications/Escalator/CMakeLists.txt
  Userland/Applications/Escalator/Escalator.gml
  Userland/Applications/Escalator/EscalatorWindow.cpp
  Userland/Applications/Escalator/EscalatorWindow.h
  Userland/Applications/Escalator/MainWidget.h
  Userland/Applications/Escalator/main.cpp
Labels: 👀 pr-needs-review

#22673 CI: Update comment-on-pr version
  .github/workflows/lintcommits.yml
Labels: 👀 pr-needs-review

#22677 Meta: Let test_pdf.py be less dramatic about issue counts
  Meta/test_pdf.py
Labels: 👀 pr-needs-review

#22678 LibGfx: Fix off-by-some in Painter::draw_scaled_bitmap_with_transform()
  Tests/LibGfx/CMakeLists.txt
  Tests/LibGfx/TestPainter.cpp
  Userland/Libraries/LibGfx/Painter.cpp
Labels: 👀 pr-needs-review

#22614 RequestServer: Avoid multiple connections to incompatible servers
  Userland/Services/RequestServer/ConnectionCache.cpp
  Userland/Services/RequestServer/ConnectionCache.h
Labels: 👀 pr-needs-review

#22671 LibCompress: Use a __FILE__-relative path for the brotli dictionary file
  Userland/Libraries/LibCompress/BrotliDictionary.cpp
  Userland/Libraries/LibCompress/BrotliDictionary.cpp.dict.bin
Labels: 👀 pr-needs-review

#22676 LibPDF: Add support for image masks
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: 👀 pr-needs-review

#22686 LibWeb: Let parent formatting context determine size of flex containers
  Tests/LibWeb/Layout/expected/flex-item-with-cyclic-percentage-height.txt
  Tests/LibWeb/Layout/expected/flex/flex-item-with-intrinsic-aspect-ratio-and-max-height.txt
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
  Userland/Libraries/LibWeb/Layout/FormattingContext.h
  Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/InlineFormattingContext.h
Labels: 👀 pr-needs-review

#22687 LibPDF: Mark text rendering matrix dirty after changing it in text_begin
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: ✅ pr-community-approved

#22684 LibPDF: Simplify load_image() a tiny bit
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: 👀 pr-needs-review

#22693 SystemMonitor: Don't include the Idle Task in process statistics
  Userland/Applications/SystemMonitor/ProcessModel.cpp
Labels: 👀 pr-needs-review

#22689 LibProtocol: Don't assume request creation will succeed across IPC
  Userland/Libraries/LibProtocol/RequestClient.cpp
Labels: 👀 pr-needs-review

#22688 LibGfx/ILBMLoader: Don't throw too early when decoding bitplanes
  Userland/Libraries/LibGfx/ImageFormats/ILBMLoader.cpp
Labels: 👀 pr-needs-review

#22697 LibWeb/CSS: Resolve NumericCalculationNode to percentage when requested
  Tests/LibWeb/Text/expected/css/css-hsl-with-calc.txt
  Tests/LibWeb/Text/input/css/css-hsl-with-calc.html
  Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
Labels: 👀 pr-needs-review

#22457 Mandelbrot: Improvements and features
  Userland/Demos/Mandelbrot/Mandelbrot.cpp
Labels: ✅ pr-community-approved

#22696 image: Fix flag names and grammar in diagnostic texts
  Userland/Utilities/image.cpp
Labels: 👀 pr-needs-review

#22683 LibGfx/ICC: Speedups, round 1
  Userland/Libraries/LibGfx/ICC/Profile.cpp
  Userland/Libraries/LibGfx/ICC/Profile.h
Labels: ✅ pr-community-approved

#22698 LibRegex: Correct And/Or and inversion interplay semantics
  Tests/LibRegex/Regex.cpp
  Userland/Libraries/LibRegex/RegexByteCode.cpp
  Userland/Libraries/LibRegex/RegexParser.cpp
Labels: 👀 pr-needs-review

#22692 Base: Document NumericInput properties
  Base/usr/share/man/man5/GML/Widget/NumericInput.md
Labels: 👀 pr-needs-review

#22572 Calculator: Allow system shortcuts
  Userland/Applications/Calculator/CalculatorWidget.cpp
Labels: 👀 pr-needs-review

#22604 PartitionEditor: Show better error when can't find partition table
  Userland/Applications/PartitionEditor/main.cpp
Labels: 👀 pr-needs-review

#22706 SystemMonitor: Condense process statistics displayed in processes tab
  Userland/Applications/SystemMonitor/ProcessModel.cpp
  Userland/Applications/SystemMonitor/ProcessModel.h
  Userland/Applications/SystemMonitor/ProcessStateWidget.cpp
Labels: 👀 pr-needs-review

#22712 LibWeb: Combine has_attribute/attribute calls in HTMLFormElement
  Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
Labels: 👀 pr-needs-review

#22714 Shell: Print paths in plain mode when stdout is not a tty
  Userland/Shell/Shell.cpp
Labels: 👀 pr-needs-review

#22707 Calculator: Make calculator display non-interactive
  Userland/Applications/Calculator/CalculatorWindow.gml
Labels: ✅ pr-community-approved

#22715 LibWeb: Cache the viewport rect across all of style computation
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
  Userland/Libraries/LibWeb/CSS/StyleComputer.h
  Userland/Libraries/LibWeb/DOM/Document.cpp
Labels: 👀 pr-needs-review

#22722 CI: Update comment-on-pr version
  .github/workflows/lintcommits.yml
Labels: 👀 pr-needs-review

#22664 LibWeb+WebContent: Spawn Worker processes from the chrome
  Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
  Ladybird/HelperProcess.cpp
  Ladybird/HelperProcess.h
  Ladybird/Qt/WebContentView.cpp
  Ladybird/WebWorker/main.cpp
  Meta/gn/secondary/Userland/Libraries/LibWebView/BUILD.gn
  Userland/Applications/Browser/main.cpp
  Userland/Libraries/LibWeb/Forward.h
  Userland/Libraries/LibWeb/HTML/WorkerAgent.cpp
  Userland/Libraries/LibWeb/HTML/WorkerAgent.h
  Userland/Libraries/LibWeb/Page/Page.h
  Userland/Libraries/LibWeb/Worker/WebWorkerClient.cpp
  Userland/Libraries/LibWeb/Worker/WebWorkerClient.h
  Userland/Libraries/LibWebView/CMakeLists.txt
  Userland/Libraries/LibWebView/Forward.h
  Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
  Userland/Libraries/LibWebView/SocketPair.cpp
  Userland/Libraries/LibWebView/SocketPair.h
  Userland/Libraries/LibWebView/ViewImplementation.h
  Userland/Libraries/LibWebView/WebContentClient.cpp
  Userland/Libraries/LibWebView/WebContentClient.h
  Userland/Services/WebContent/PageClient.cpp
  Userland/Services/WebContent/PageClient.h
  Userland/Services/WebContent/WebContentClient.ipc
  Userland/Services/WebContent/main.cpp
  Userland/Utilities/headless-browser.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#22415 Calculator: Finish operation-in-progress only on new binary operations
  Userland/Applications/Calculator/Calculator.cpp
Labels: 👀 pr-needs-review

#22498 pixelflut: Two improvements from 37c3
  Userland/Utilities/pixelflut.cpp
Labels: 👀 pr-needs-review

#22583 LibELF: Ignore RISC-V attribute section program header
  Userland/Libraries/LibELF/ELFABI.h
  Userland/Libraries/LibELF/Validation.cpp
Labels: 👀 pr-needs-review

#22632 LibCore: Avoid running fstatat on skipped entries in DirIterator
  Userland/Libraries/LibCore/DirIterator.cpp
Labels: 👀 pr-needs-review

#22592 JSSpecCompiler: Add SSA form building pass
  Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/CMakeLists.txt
  Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/Passes/SSABuildingPass.cpp
  Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/Passes/SSABuildingPass.h
  Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Tests/simple.cpp.expectation
  Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/main.cpp
Labels: 👀 pr-needs-review

#22571 Browser: Add help menu item
  Userland/Applications/Browser/BrowserWindow.cpp
  Userland/Applications/Browser/BrowserWindow.h
  Userland/Applications/Browser/main.cpp
Labels: 👀 pr-needs-review

#22646 Kernel: Properly ack segment
  Kernel/Net/NetworkTask.cpp
Labels: 👀 pr-needs-review

#22568 HackStudio: Correctly handle invalid addresses during backtrace creation
  Userland/DevTools/HackStudio/Debugger/BacktraceModel.cpp
Labels: 👀 pr-needs-review

#22597 Assistant: Check for access before showing results
  Userland/Applications/Assistant/Providers.cpp
Labels: 👀 pr-needs-review

#21388 AK: Remove ByteString from GenericLexer
  AK/Format.cpp
  AK/GenericLexer.h
  AK/JsonParser.cpp
  Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
  Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSEasingFunctions.cpp
  Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWindowOrWorkerInterfaces.cpp
  Meta/Lagom/Tools/CodeGenerators/StateMachineGenerator/main.cpp
  Tests/AK/TestGenericLexer.cpp
  Userland/Applications/Spreadsheet/Readers/XSV.cpp
  Userland/Applications/Spreadsheet/Writers/XSV.h
  Userland/Libraries/LibCrypto/ASN1/PEM.cpp
  Userland/Libraries/LibDiff/Hunks.cpp
  Userland/Libraries/LibIDL/IDLParser.cpp
  Userland/Libraries/LibLine/Editor.cpp
  Userland/Libraries/LibXML/Parser/Parser.cpp
  Userland/Utilities/pro.cpp
Labels: 👀 pr-needs-review

#22647 LibELF: Correctly determine symbol amount for DT_GNU_HASH table
  Userland/Libraries/LibELF/DynamicObject.cpp
  Userland/Utilities/readelf.cpp
Labels: 👀 pr-needs-review

#22652 LibWeb/MimeSniff: Implement MP4 signature matching
  Tests/LibWeb/TestMimeSniff.cpp
  Userland/Libraries/LibWeb/MimeSniff/Resource.cpp
Labels: 👀 pr-needs-review

#22653 Calendar: Fix issues and implement duration feature in AddEventDialog
  Userland/Applications/Calendar/AddEventDialog.cpp
  Userland/Applications/Calendar/AddEventDialog.gml
  Userland/Applications/Calendar/AddEventDialog.h
Labels: 👀 pr-needs-review

#22662 Base: Improve About, AnalogClock & Assistant manpages
  Base/usr/share/man/man1/Applications/About.md
  Base/usr/share/man/man1/Applications/AnalogClock.md
  Base/usr/share/man/man1/Applications/Assistant.md
Labels: 👀 pr-needs-review

#22699 Solitaire: Hide solve button when game ends
  Userland/Games/Solitaire/main.cpp
Labels: 👀 pr-needs-review

#22631 Everywhere: Add deprecated_ prefix to `JsonValue::to_byte_string`
  AK/JsonValue.h
  Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSEnums.cpp
  Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp
  Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSTransformFunctions.cpp
  Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSValueID.cpp
  Tests/AK/TestJSON.cpp
  Userland/Applications/Presenter/Presentation.cpp
  Userland/Applications/Presenter/SlideObject.cpp
  Userland/Applications/Spreadsheet/HelpWindow.cpp
  Userland/Applications/Spreadsheet/Spreadsheet.cpp
  Userland/DevTools/Profiler/Profile.cpp
  Userland/Libraries/LibGUI/DynamicWidgetContainer.cpp
  Userland/Libraries/LibGUI/JsonArrayModel.cpp
  Userland/Libraries/LibJS/Runtime/JSONObject.cpp
  Userland/Libraries/LibWeb/WebDriver/Client.cpp
  Userland/Services/WebDriver/Client.cpp
  Userland/Shell/Shell.cpp
  Userland/Utilities/json.cpp
  Userland/Utilities/lsirq.cpp
  Userland/Utilities/pmap.cpp
Labels: 👀 pr-needs-review

#22728 LibWeb/MimeSniff: Remove unnecessary addition in mp4 signature match
  Userland/Libraries/LibWeb/MimeSniff/Resource.cpp
Labels: ✅ pr-community-approved

#22738 LibWeb: Set box-shadow for inline paintables in LayoutState::commit()
  Userland/Libraries/LibWeb/Layout/LayoutState.cpp
  Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
  Userland/Libraries/LibWeb/Painting/InlinePaintable.h
Labels: 👀 pr-needs-review

#22742 LibWeb: Make inline paintables own their fragments
  Tests/LibWeb/Layout/expected/acid1.txt
  Tests/LibWeb/Layout/expected/block-and-inline/float-clear-by-line-break.txt
  Tests/LibWeb/Layout/expected/block-and-inline/forced-break-stops-non-whitespace-sequence.txt
  Tests/LibWeb/Layout/expected/block-and-inline/margin-padding-block-inline-start.txt
  Tests/LibWeb/Layout/expected/block-and-inline/margin-padding-block-inline.txt
  Tests/LibWeb/Layout/expected/block-and-inline/relpos-inline-element-js-offsets.txt
  Tests/LibWeb/Layout/expected/block-and-inline/relpos-inline-elements.txt
  Tests/LibWeb/Layout/expected/br-should-not-generate-pseudo-before.txt
  Tests/LibWeb/Layout/expected/css-all-unset.txt
  Tests/LibWeb/Layout/expected/css-font-size-math.txt
  Tests/LibWeb/Layout/expected/css-namespace-rule-matches.txt
  Tests/LibWeb/Layout/expected/css-namespace-rule-no-match.txt
  Tests/LibWeb/Layout/expected/css-namespace-tag-name-selector.txt
  Tests/LibWeb/Layout/expected/css-quotes-nesting.txt
  Tests/LibWeb/Layout/expected/details-open.txt
  Tests/LibWeb/Layout/expected/display-contents-with-in-children.txt
  Tests/LibWeb/Layout/expected/display-table-inline-children.txt
  Tests/LibWeb/Layout/expected/font-fractional-size.txt
  Tests/LibWeb/Layout/expected/font-size-legacy.txt
  Tests/LibWeb/Layout/expected/font-with-many-normal-values.txt
  Tests/LibWeb/Layout/expected/nowrap-and-no-line-break-opportunity.txt
  Tests/LibWeb/Layout/expected/percentage-max-height-when-containing-block-has-indefinite-height.txt
  Tests/LibWeb/Layout/expected/picture-source-media-query.txt
  Tests/LibWeb/Layout/expected/pre.txt
  Tests/LibWeb/Layout/expected/shadow-tree-removed-from-dom-receives-event.txt
  Tests/LibWeb/Layout/expected/space-is-soft-line-break-opportunity.txt
  Tests/LibWeb/Layout/expected/table/row-outer-size-with-computed-size.txt
  Userland/Libraries/LibWeb/Dump.cpp
  Userland/Libraries/LibWeb/Layout/LayoutState.cpp
  Userland/Libraries/LibWeb/Layout/Node.cpp
  Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
  Userland/Libraries/LibWeb/Painting/InlinePaintable.h
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
  Userland/Libraries/LibWeb/Painting/PaintableBox.h
Labels: 👀 pr-needs-review

#22731 Tests/LibCompress: Add a reproducer of oss-fuzz issue 58046
  Tests/LibCompress/TestDeflate.cpp
  Tests/LibCompress/deflate-test-files/clusterfuzz-testcase-minimized-FuzzDeflateDecompression-5523852259360768.fuzz
Labels: 👀 pr-needs-review

#22741 LibGUI+Applications: Default the SpinBox min/max to the full int range
  Userland/Applications/Calendar/AddEventDialog.gml
  Userland/Applications/FontEditor/FontEditorWindow.gml
  Userland/Libraries/LibGUI/FontPickerDialog.gml
  Userland/Libraries/LibGUI/SpinBox.h
Labels: 👀 pr-needs-review

#22747 LibCrypto: Parse negative input correctly in `BigFraction::from_string()`
  Tests/LibCrypto/CMakeLists.txt
  Tests/LibCrypto/TestBigFraction.cpp
  Userland/Libraries/LibCrypto/BigFraction/BigFraction.cpp
Labels: 👀 pr-needs-review

#22723 LibGfx/ILBMLoader: Don't decode bits once full row has been decoded
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/ilbm/small-24bit.iff
  Userland/Libraries/LibGfx/ImageFormats/ILBMLoader.cpp
Labels: 👀 pr-needs-review

#22756 LibCompress/Deflate: Code clean up!
  Userland/Libraries/LibCompress/Deflate.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#22757 LibGUI: Use BoxSampling to draw thumbnails
  Userland/Libraries/LibGUI/FileSystemModel.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#22753 Ports: Update ScummVM to 2.8.0
  Ports/AvailablePorts.md
  Ports/scummvm/package.sh
Labels: 👀 pr-needs-review

#22541 LibVideo: Replace DeprecatedFlyString with FlyString
  Userland/Libraries/LibVideo/Containers/Matroska/Document.h
  Userland/Libraries/LibVideo/Containers/Matroska/MatroskaDemuxer.cpp
  Userland/Libraries/LibVideo/Containers/Matroska/MatroskaDemuxer.h
  Userland/Libraries/LibVideo/Containers/Matroska/Reader.cpp
  Userland/Utilities/matroska.cpp
Labels: 👀 pr-needs-review

#22721 HackStudio: Stop crash from leaking Editor widgets when closing tabs
  Userland/DevTools/HackStudio/HackStudioWidget.cpp
Labels: 👀 pr-needs-review

#22750 LibC: Implement setjmp and longjmp for riscv64
  Userland/Libraries/LibC/arch/riscv64/setjmp.S
  Userland/Libraries/LibC/setjmp.h
Labels: 👀 pr-needs-review

#22703 HackStudio: Make Editor ask Debugger if a breakpoint was added/removed
  Userland/DevTools/HackStudio/Debugger/Debugger.cpp
  Userland/DevTools/HackStudio/Debugger/Debugger.h
  Userland/DevTools/HackStudio/Editor.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#22760 LibPDF: Mark text rendering matrix dirty for Td operator
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: 👀 pr-needs-review

#22761 LibPDF: Mark text rendering matrix as dirty after TJ numbers
  Tests/LibPDF/text.pdf
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: 👀 pr-needs-review

#22762 LibWeb: Treat flex item cross axis max-size as "none" in more cases
  Tests/LibWeb/Layout/expected/flex/svg-flex-item-with-percentage-max-size.txt
  Tests/LibWeb/Layout/input/flex/svg-flex-item-with-percentage-max-size.html
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
Labels: 👀 pr-needs-review

#22763 LibWeb+WebContent: Move paint recording init into BrowsingContext
  Tests/LibWeb/Ref/reference/images/css-background-repeat-ref.png
  Userland/Libraries/LibWeb/HTML/Navigable.cpp
  Userland/Libraries/LibWeb/HTML/Navigable.h
  Userland/Libraries/LibWeb/Painting/NestedBrowsingContextPaintable.cpp
  Userland/Services/WebContent/PageClient.cpp
  Userland/Services/WebContent/PageClient.h
Labels: 👀 pr-needs-review

#22764 LibC: Pass arguments correctly to sigprocmask in setjmp for riscv64
  Userland/Libraries/LibC/arch/riscv64/setjmp.S
Labels: 👀 pr-needs-review

#22768 MacPDF: Add a "Debug" menu with a "Show Clipping Paths" entry
  Meta/Lagom/Contrib/MacPDF/MacPDFView.h
  Meta/Lagom/Contrib/MacPDF/MacPDFView.mm
  Meta/Lagom/Contrib/MacPDF/MainMenu.xib
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#22772 Ladybird/AppKit/CMake: Use a more civilized way of finding Cocoa
  Ladybird/CMakeLists.txt
Labels: 👀 pr-needs-review

#22758 LibGfx/JPEG: Allow decoding more subsampling factors
  Tests/LibGfx/TestImageDecoder.cpp
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Labels: ✅ pr-community-approved

#22778 LibGfx: Use read_effective_chunk_size() in skip_segment()
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Labels: 👀 pr-needs-review

#22782 LibGfx/PNG: Spec comment for PNGImageDecoderPlugin::unfilter_scanline()
  Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp
Labels: 👀 pr-needs-review

#22786 LibWeb: Skip select element internal shadow tree update unless it exists
  Tests/LibWeb/Text/expected/HTML/select-setValue-after-construction.txt
  Tests/LibWeb/Text/input/HTML/select-setValue-after-construction.html
  Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp
Labels: 👀 pr-needs-review

#22769 LibGfx/JPEG: Simplify loops walking all pixels in all macroblocks
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#22793 cksum: Consider empty file operand when printing
  Userland/Utilities/cksum.cpp
Labels: 👀 pr-needs-review

#22792 Make run.py work with python 3.9
  Meta/run.py
Labels: 👀 pr-needs-review

#22789 LibPDF: Make `pdf --dump-contents` handle \r line endings better
  Userland/Libraries/LibPDF/ObjectDerivatives.cpp
Labels: ✅ pr-community-approved

#22788 Tests/LibGfx: Use `TRY_OR_FAIL` more in TestImageDecoder
  Tests/LibGfx/TestImageDecoder.cpp
Labels: ✅ pr-community-approved

#22800 LibWeb: Align with spec "stretch auto tracks" step in GFC
  Tests/LibWeb/Layout/expected/grid/align-items.txt
  Tests/LibWeb/Layout/expected/grid/align-self.txt
  Tests/LibWeb/Layout/expected/grid/all-implicit-rows.txt
  Tests/LibWeb/Layout/expected/grid/auto-flow-column-spanning-item.txt
  Tests/LibWeb/Layout/expected/grid/auto-flow-column.txt
  Tests/LibWeb/Layout/expected/grid/basic.txt
  Tests/LibWeb/Layout/expected/grid/borders.txt
  Tests/LibWeb/Layout/expected/grid/grid-gap-1.txt
  Tests/LibWeb/Layout/expected/grid/grid-gap-2.txt
  Tests/LibWeb/Layout/expected/grid/grid-item-percentage-width.txt
  Tests/LibWeb/Layout/expected/grid/negative-grid-item-column-index.txt
  Tests/LibWeb/Layout/expected/grid/place-self.txt
  Tests/LibWeb/Layout/expected/grid/placement-using-named-tracks-1.txt
  Tests/LibWeb/Layout/expected/grid/row-height.txt
  Tests/LibWeb/Layout/expected/grid/row-span-2-maxcontent.txt
  Tests/LibWeb/Layout/expected/grid/row-span-2-with-gaps.txt
  Tests/LibWeb/Layout/expected/grid/row-span-2.txt
  Tests/LibWeb/Layout/expected/grid/should-not-hang-in-size-distribution.txt
  Tests/LibWeb/Layout/expected/grid/stretch-auto-tracks.txt
  Tests/LibWeb/Layout/input/grid/stretch-auto-tracks.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#22807 HackStudio: Make Files and Classes tabs have the same border width
  Userland/DevTools/HackStudio/HackStudioWidget.cpp
Labels: 👀 pr-needs-review

#22803 LibPDF: Be more forgiving about trailing image data
  Userland/Libraries/LibPDF/Filter.cpp
Labels: 👀 pr-needs-review

#22801 Meta/run.py: Fix grammar in method names
  Meta/run.py
Labels: 👀 pr-needs-review

#22814 LibWeb: Account for gaps in grid container's intrinsic size calculation
  Tests/LibWeb/Layout/expected/grid/intrinsic-sizing-should-account-for-gaps.txt
  Tests/LibWeb/Layout/input/grid/intrinsic-sizing-should-account-for-gaps.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#22816 LibPDF: Fix paths with negatively sized `re` (rect) commands
  Userland/Libraries/LibPDF/Renderer.cpp
  Userland/Libraries/LibPDF/Renderer.h
Labels: ✅ pr-community-approved

#22821 LibPDF: Tweak vertical position of truetype fonts
  Userland/Libraries/LibPDF/Fonts/TrueTypeFont.cpp
  Userland/Libraries/LibPDF/Fonts/Type1Font.cpp
Labels: 👀 pr-needs-review

#22826 LibWeb: Fix accounting for gaps in auto-fit count calculation in GFC
  Tests/LibWeb/Layout/expected/grid/columns-auto-fill-with-gap-3.txt
  Tests/LibWeb/Layout/input/grid/columns-auto-fill-with-gap-3.html
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#22827 LibWeb: Remove duplicated code in grid auto track counting
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#22825 LibWeb/CSS: Support calc() in grid placement values
  Tests/LibWeb/Layout/expected/grid/css-calc-in-grid-position.txt
  Tests/LibWeb/Layout/input/grid/css-calc-in-grid-position.html
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#22832 LibAudio: Avoid UAF when loading WAV metadata
  Userland/Libraries/LibAudio/WavLoader.cpp
Labels: 👀 pr-needs-review

#22835 Fuzzers: Continue if frame is malformed in GIF fuzzer
  Meta/Lagom/Fuzzers/FuzzGIFLoader.cpp
Labels: 👀 pr-needs-review

#22808 LibGfx/ILBMLoader: Properly display images with a bitplane mask
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/ilbm/test-stencil.iff
  Userland/Libraries/LibGfx/ImageFormats/ILBMLoader.cpp
Labels: ✅ pr-community-approved

#22836 CMake: Set `CMAKE_COLOR_DIAGNOSTICS` to `ON` for colored diagnostics
  Meta/CMake/common_compile_options.cmake
Labels: 👀 pr-needs-review

#22834 LibWeb: Format all .idl files to use four space indentation
  Userland/Libraries/LibWeb/Animations/Animation.idl
  Userland/Libraries/LibWeb/Animations/AnimationEffect.idl
  Userland/Libraries/LibWeb/Animations/DocumentTimeline.idl
  Userland/Libraries/LibWeb/Animations/KeyframeEffect.idl
  Userland/Libraries/LibWeb/CSS/CSSNamespaceRule.idl
  Userland/Libraries/LibWeb/Clipboard/Clipboard.idl
  Userland/Libraries/LibWeb/Crypto/SubtleCrypto.idl
  Userland/Libraries/LibWeb/DOM/HTMLFormControlsCollection.idl
  Userland/Libraries/LibWeb/HTML/NavigateEvent.idl
  Userland/Libraries/LibWeb/HTML/Navigation.idl
  Userland/Libraries/LibWeb/HTML/NavigationDestination.idl
  Userland/Libraries/LibWeb/HTML/NavigationHistoryEntry.idl
  Userland/Libraries/LibWeb/HTML/NavigationTransition.idl
  Userland/Libraries/LibWeb/HTML/NavigationType.idl
  Userland/Libraries/LibWeb/HTML/NavigatorConcurrentHardware.idl
  Userland/Libraries/LibWeb/HTML/NavigatorID.idl
  Userland/Libraries/LibWeb/HTML/NavigatorOnLine.idl
  Userland/Libraries/LibWeb/HTML/SubmitEvent.idl
  Userland/Libraries/LibWeb/SVG/SVGAnimatedNumber.idl
  Userland/Libraries/LibWeb/SVG/SVGAnimatedString.idl
  Userland/Libraries/LibWeb/SVG/SVGTextPathElement.idl
Labels: 👀 pr-needs-review

#22837 LibPDF: Ensure that xref subsection numbers are u32
  Userland/Libraries/LibPDF/DocumentParser.cpp
Labels: ✅ pr-community-approved

#22843 LibWeb: Resolve relpos fragment offsets only for inline paintables
  Userland/Libraries/LibWeb/Layout/LayoutState.cpp
  Userland/Libraries/LibWeb/Layout/LayoutState.h
Labels: 👀 pr-needs-review

#22854 LibWeb: Correctly categorize Fetch responses as network errors
  Tests/LibWeb/Text/expected/video-failed-load.txt
  Tests/LibWeb/Text/input/video-failed-load.html
  Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.cpp
Labels: 👀 pr-needs-review
