Repository SerenityOS/serenity, pull requests merged in 2024-02, with the labels that each got.

#23037 LibWeb: Apply scroll offset to PushStackingContext command
  Tests/LibWeb/Ref/reference/scrollable-contains-boxes-with-hidden-overflow-and-opacity-ref.html
  Tests/LibWeb/Ref/scrollable-contains-boxes-with-hidden-overflow-and-opacity.html
  Userland/Libraries/LibWeb/Painting/PaintableBox.h
  Userland/Libraries/LibWeb/Painting/RecordingPainter.h
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Labels: 👀 pr-needs-review

#23039 LibWeb: Use Window::scroll() in set_scroll_left() and set_scroll_top()
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: 👀 pr-needs-review

#23045 image: Minor cleanups and reorganizations
  Userland/Utilities/image.cpp
Labels: ✅ pr-community-approved

#23044 LibGfx/PNM: Remove two fixmes
  Userland/Libraries/LibGfx/ImageFormats/PortableImageLoaderCommon.h
Labels: ✅ pr-community-approved

#23040 SystemServer: Treat services terminated by signals as not successful
  Userland/Services/SystemServer/Service.cpp
Labels: 👀 pr-needs-review

#23053 LibWeb: Create AccelGfx context only once in PageClient
  Userland/Services/WebContent/PageClient.cpp
Labels: 👀 pr-needs-review

#23048 LibPDF: Make `pdf --dump-contents` dump less binary data
  Userland/Libraries/LibPDF/ObjectDerivatives.cpp
Labels: 👀 pr-needs-review

#23047 LibWeb: Fix invalidation of CSS properties that do not affect layout
  Tests/LibWeb/Ref/invalidate-css-transform-property.html
  Tests/LibWeb/Ref/reference/invalidate-css-transform-property-ref.html
  Userland/Libraries/LibWeb/DOM/Element.cpp
  Userland/Libraries/LibWeb/HTML/Navigable.cpp
  Userland/Libraries/LibWeb/HTML/Navigable.h
  Userland/Libraries/LibWeb/Layout/LayoutState.cpp
  Userland/Libraries/LibWeb/Layout/LayoutState.h
  Userland/Libraries/LibWeb/Painting/Paintable.h
  Userland/Libraries/LibWeb/Painting/PaintableFragment.h
  Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp
  Userland/Libraries/LibWeb/Painting/ViewportPaintable.h
Labels: 👀 pr-needs-review

#23055 LibWeb: Remove some function that became unused after migrating to navigables
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
Labels: 👀 pr-needs-review

#23057 LibWeb: Do not add CSS transforms into clip rect in PaintableWithLines
  Tests/LibWeb/Ref/overflow-hidden-text-inside-translated-container.html
  Tests/LibWeb/Ref/reference/overflow-hidden-text-inside-translated-container-ref.html
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Labels: 👀 pr-needs-review

#23022 LibWeb: Don't update input text if Ctrl or Alt are pressed
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#23049 image: Add an --invert-cmyk option
  Userland/Utilities/image.cpp
Labels: ✅ pr-community-approved

#23050 LibGfx+LibPDF: Simpler and faster N-D linear sampling
  Userland/Libraries/LibGfx/ICC/TagTypes.h
  Userland/Libraries/LibPDF/Function.cpp
Labels: 👀 pr-needs-review

#23064 Ports: Update poppler to 24.02.0
  Ports/AvailablePorts.md
  Ports/poppler/package.sh
Labels: 👀 pr-needs-review

#23074 Everywhere: Prefer `VERIFY` over `assert()`
  AK/Assertions.h
  Tests/LibJS/test262-runner.cpp
  Userland/Libraries/LibDSP/MDCT.h
  Userland/Utilities/tsort.cpp
Labels: 👀 pr-needs-review

#23084 Ladybird/Qt: Map Enter keypresses to the code point '\n'
  Ladybird/Qt/WebContentView.cpp
Labels: 👀 pr-needs-review

#23060 AK: Fix OptionParser argument shifting
  AK/OptionParser.cpp
  Meta/Lagom/CMakeLists.txt
  Tests/AK/CMakeLists.txt
  Tests/AK/TestOptionParser.cpp
  Tests/LibCore/TestLibCoreArgsParser.cpp
Labels: 👀 pr-needs-review

#23088 LibPDF: Always treat `/Subtype /Image` as binary data when dumping
  Userland/Libraries/LibPDF/ObjectDerivatives.cpp
Labels: 👀 pr-needs-review

#23066 LibWeb: Resolve effective overflow-x and overflow-y according to spec
  Tests/LibWeb/Ref/overflow-hidden-7.html
  Tests/LibWeb/Ref/reference/overflow-hidden-7-ref.html
  Tests/LibWeb/Text/expected/resolve-css-overflow-effective-value.txt
  Tests/LibWeb/Text/input/resolve-css-overflow-effective-value.html
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
  Userland/Libraries/LibWeb/CSS/StyleComputer.h
Labels: 👀 pr-needs-review

#23082 LibWeb: Make WebDriver check if the BC's navigable has been destroyed
  Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
  Userland/Libraries/LibWeb/HTML/BrowsingContext.h
  Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
  Userland/Services/WebContent/WebDriverConnection.cpp
Labels: 👀 pr-needs-review

#23019 Run: Fix bug where it would crash because uninitialized main widget
  Userland/Applications/Run/RunWindow.cpp
  Userland/Applications/Run/RunWindow.h
  Userland/Applications/Run/main.cpp
Labels: ✅ pr-community-approved

#23076 LibWeb/CSS: Resolve value of "height" in special way according to spec
  Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
  Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
Labels: 👀 pr-needs-review

#23090 LibWeb: Implement `document.elementFromPoint()`
  Tests/LibWeb/Text/expected/DOM/Element-from-point.txt
  Tests/LibWeb/Text/input/DOM/Element-from-point.html
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/DOM/Document.idl
Labels: 👀 pr-needs-review

#23070 Ports: Update URL for qt6-qt5compat
  Ports/qt6-qt5compat/package.sh
Labels: 👀 pr-needs-review

#23081 ntpquery: Use AK::convert_between_host_and_network_endian
  AK/Endian.h
  Userland/Utilities/ntpquery.cpp
Labels: 👀 pr-needs-review

#23093 Tests: Remove UserspaceEmulator more
  Tests/UserspaceEmulator/CMakeLists.txt
  Tests/UserspaceEmulator/ue-write-oob.cpp
Labels: 👀 pr-needs-review

#23091 Ports/devilutionX: Update to version 1.5.2
  Ports/AvailablePorts.md
  Ports/devilutionX/package.sh
Labels: 👀 pr-needs-review

#22957 Ladybird/Qt: Properly listen for DPI changes on Wayland
  Ladybird/Qt/BrowserWindow.cpp
  Ladybird/Qt/BrowserWindow.h
  Ladybird/Qt/InspectorWidget.cpp
  Ladybird/Qt/InspectorWidget.h
  Ladybird/Qt/Tab.cpp
  Ladybird/Qt/WebContentView.cpp
  Ladybird/Qt/WebContentView.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#22982 RequestServer: Replace use of gethostbyname with Core::Socket::resolve_host
  Userland/Libraries/LibCore/Socket.h
  Userland/Services/RequestServer/ConnectionFromClient.cpp
Labels: 👀 pr-needs-review

#23095 Presenter: Add Manual link in help menu
  Userland/Applications/Presenter/CMakeLists.txt
  Userland/Applications/Presenter/PresenterWidget.cpp
  Userland/Applications/Presenter/main.cpp
Labels: 👀 pr-needs-review

#23103 LibGfx/OpenType: Support cmaps with format Unicode
  Userland/Libraries/LibGfx/Font/OpenType/Cmap.h
  Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
Labels: 👀 pr-needs-review

#23102 LibGfx: Add a comment to Font::try_load_from_offset()
  Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
Labels: 👀 pr-needs-review

#23109 LibWeb: Invalidate paint-only property after relayout
  Tests/LibWeb/Ref/reference/resolve-paint-only-properties-after-layout-ref.html
  Tests/LibWeb/Ref/resolve-paint-only-properties-after-layout.html
  Userland/Libraries/LibWeb/DOM/Document.cpp
Labels: 👀 pr-needs-review

#23118 LibGfx/OpenType: Reject fonts we can't render glyphs from earlier
  Userland/Libraries/LibGfx/Font/OpenType/Cmap.cpp
  Userland/Libraries/LibGfx/Font/OpenType/Cmap.h
  Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
Labels: 👀 pr-needs-review

#23122 LibPDF: Fix small bug from #21452
  Userland/Libraries/LibPDF/Fonts/CFF.cpp
Labels: 👀 pr-needs-review

#22907 Kernel/Net: E1000ENetworkAdapter detect EEPROM
  Kernel/Net/Intel/E1000ENetworkAdapter.cpp
Labels: 👀 pr-needs-review

#22915 KeyboardMapper: Convert Utf-8 char in String to Utf-32 code point
  Userland/Applications/KeyboardMapper/KeyboardMapperWidget.cpp
Labels: 👀 pr-needs-review

#22901 cp: add `--interactive`/`-i` flag
  Userland/Utilities/cp.cpp
Labels: 👀 pr-needs-review

#22923 Kernel/riscv64: Add QEMU virt machine memory map
  Kernel/Arch/init.cpp
Labels: 👀 pr-needs-review

#20869 LibAudio: Automatically write a FLAC seektable
  Userland/Libraries/LibAudio/FlacTypes.h
  Userland/Libraries/LibAudio/FlacWriter.cpp
  Userland/Libraries/LibAudio/FlacWriter.h
  Userland/Libraries/LibAudio/GenericTypes.cpp
  Userland/Libraries/LibAudio/GenericTypes.h
Labels: 👀 pr-needs-review

#22956 cut: Add -c,--characters option
  Userland/Utilities/cut.cpp
Labels: 👀 pr-needs-review

#22985 LibGfx/JPEGLoader: Make byte_offset() return offset from start of stream
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Labels: 👀 pr-needs-review

#23033 LibJS: Don't crash when attempting to load from an invalid reference
  Userland/Libraries/LibJS/Bytecode/Generator.cpp
  Userland/Libraries/LibJS/Tests/invalid-lhs-in-assignment.js
Labels: 👀 pr-needs-review

#23017 LibWeb: Set document's URL when loading markdown file as inline content
  Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
Labels: 👀 pr-needs-review

#22897 AK: Store JsonValue's value in AK::Variant
  AK/JsonObject.h
  AK/JsonValue.cpp
  AK/JsonValue.h
Labels: 👀 pr-needs-review

#23058 Kernel/HID: Move code_point assignment before its use in key assignment
  Kernel/Devices/HID/KeyboardDevice.cpp
Labels: 👀 pr-needs-review

#23065 Calendar: Add ability to view events
  Userland/Applications/Calendar/CMakeLists.txt
  Userland/Applications/Calendar/CalendarWidget.cpp
  Userland/Applications/Calendar/ViewEventDialog.cpp
  Userland/Applications/Calendar/ViewEventDialog.gml
  Userland/Applications/Calendar/ViewEventDialog.h
  Userland/Applications/Calendar/ViewEventWidget.cpp
  Userland/Applications/Calendar/ViewEventWidget.h
Labels: 👀 pr-needs-review

#23071 Kernel/riscv64: Don't touch reserved fields of the sstatus CSR in boot.S
  Kernel/Arch/riscv64/boot.S
Labels: 👀 pr-needs-review

#22999 LibVT: Write emoji to the pseudo-terminal master fd on emoji input
  Userland/Libraries/LibVT/TerminalWidget.cpp
Labels: 👀 pr-needs-review

#23112 Everywhere: Prefer `_string` when constructing strings from literals
  AK/URLParser.cpp
  Meta/Lagom/Tools/CodeGenerators/GMLCompiler/main.cpp
  Tests/LibCrypto/TestChacha20Poly1305.cpp
  Userland/Libraries/LibCore/Version.cpp
Labels: 👀 pr-needs-review

#23128 LibPDF: Make CFF::parse_charset() return SIDs
  Userland/Libraries/LibPDF/Fonts/CFF.cpp
  Userland/Libraries/LibPDF/Fonts/CFF.h
Labels: 👀 pr-needs-review

#23127 Revert "LibPDF: Don't over-read in charset formats 1 and 2"
  Userland/Libraries/LibPDF/Fonts/CFF.cpp
Labels: 👀 pr-needs-review

#23083 HexEditor: Deduplicate repeated coordinate calculations, and fix some bugs in the process
  Userland/Applications/HexEditor/HexEditor.cpp
  Userland/Applications/HexEditor/HexEditor.h
Labels: 👀 pr-needs-review

#23141 Kernel/HID: Set Caps Lock state before doing code point remapping
  Kernel/Devices/HID/KeyboardDevice.cpp
Labels: 👀 pr-needs-review

#23124 Ports: Add Sonic Robo Blast 2
  Ports/AvailablePorts.md
  Ports/SRB2/package.sh
  Ports/SRB2/patches/0001-add-openmpt-to-build.patch
  Ports/SRB2/patches/0002-fix-libgme-include.patch
  Ports/SRB2/patches/0003-disable-consolevar-value-checker-sad-path.patch
  Ports/SRB2/patches/0004-i_video.c-mouse-hacks.patch
  Ports/SRB2/patches/0005-i_system.c-hacks.patch
  Ports/SRB2/patches/ReadMe.md
Labels: 👀 pr-needs-review

#23140 LibWeb: Add internals.wheel() to simulate mouse wheel events
  Tests/LibWeb/Ref/reference/scroll-using-mousewheel-event-ref.html
  Tests/LibWeb/Ref/scroll-using-mousewheel-event.html
  Userland/Libraries/LibWeb/Internals/Internals.cpp
  Userland/Libraries/LibWeb/Internals/Internals.h
  Userland/Libraries/LibWeb/Internals/Internals.idl
Labels: 👀 pr-needs-review

#23101 LibWeb: Use correct offset value when replacing character data
  Tests/LibWeb/Text/expected/DOM/Delete-from-text-node-with-associated-range.txt
  Tests/LibWeb/Text/input/DOM/Delete-from-text-node-with-associated-range.html
  Userland/Libraries/LibWeb/DOM/CharacterData.cpp
Labels: ✅ pr-community-approved

#23148 LibWeb: Account for all clipped border radii in containing block chain
  Tests/LibWeb/Ref/nested-boxes-with-hidden-overflow-and-border-radius.html
  Tests/LibWeb/Ref/reference/images/nested-boxes-with-hidden-overflow-and-border-radius-ref.png
  Tests/LibWeb/Ref/reference/nested-boxes-with-hidden-overflow-and-border-radius-ref.html
  Userland/Libraries/LibWeb/Painting/BorderRadiiData.h
  Userland/Libraries/LibWeb/Painting/ClipFrame.h
  Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
  Userland/Libraries/LibWeb/Painting/PaintableBox.h
  Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp
Labels: 👀 pr-needs-review

#23125 LibWeb: Update the cursor position when an editable element is clicked
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
Labels: 👀 pr-needs-review

#23135 LibPDF/CFF: Add enum values for remaining PrivDictOperators
  Userland/Libraries/LibPDF/Fonts/CFF.cpp
  Userland/Libraries/LibPDF/Fonts/CFF.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#23155 LibWeb: ignore repeat(auto-fit/auto-fill, auto) as it is not allowed
  Tests/LibWeb/Layout/expected/grid/repeat-auto-fit-fill-cannot-have-auto.txt
  Tests/LibWeb/Layout/input/grid/repeat-auto-fit-fill-cannot-have-auto.html
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#23139 BrickGame: Make action shortcuts work when the game is paused
  Userland/Games/BrickGame/BrickGame.cpp
Labels: 👀 pr-needs-review

#23146 LibWeb: Implement `document.designMode`
  Tests/LibWeb/Text/expected/DOM/Document-set-designMode.txt
  Tests/LibWeb/Text/input/DOM/Document-set-designMode.html
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/DOM/Document.idl
Labels: 👀 pr-needs-review

#23158 LibWeb: Use paths for text in CRC2D (if possible)
  Tests/LibWeb/Ref/canvas-text.html
  Tests/LibWeb/Ref/reference/canvas-text-ref.html
  Tests/LibWeb/Ref/reference/images/canvas-text-ref.png
  Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
  Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.h
Labels: 👀 pr-needs-review

#23136 LibPDF/CFF: Add code for fdselect parsing
  Userland/Libraries/LibPDF/Fonts/CFF.cpp
  Userland/Libraries/LibPDF/Fonts/CFF.h
Labels: 👀 pr-needs-review

#23165 LibPDF: Scale default glyph width by font size and x scale
  Userland/Libraries/LibPDF/Fonts/SimpleFont.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#23164 Kernel: Make `ftruncate` change `st_ctime` as per spec
  Kernel/FileSystem/InodeFile.cpp
Labels: 👀 pr-needs-review

#23166 LibWeb: Fix hit-testing for button element
  Tests/LibWeb/Text/expected/hit_testing/button.txt
  Tests/LibWeb/Text/input/hit_testing/button.html
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
Labels: 👀 pr-needs-review

#23167 LibPDF: Add string drawing code for Type0Fonts
  Userland/Libraries/LibPDF/Fonts/Type0Font.cpp
Labels: 👀 pr-needs-review

#23179 LibPDF: Separate Type0 CMap errors
  Userland/Libraries/LibPDF/Fonts/Type0Font.cpp
Labels: 👀 pr-needs-review

#23173 LibWeb: Display an IBeam cursor by default when mousing over a text node
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
Labels: 👀 pr-needs-review

#23177 Kernel/TTY: Support non-blocking reads with termios VMIN == 0
  Kernel/Devices/TTY/TTY.cpp
  Kernel/Devices/TTY/TTY.h
Labels: 👀 pr-needs-review

#23192 LibGfx/ICO: Remove unused parameter
  Userland/Libraries/LibGfx/ImageFormats/ICOLoader.cpp
  Userland/Libraries/LibGfx/ImageFormats/ICOLoader.h
Labels: 👀 pr-needs-review

#23190 LibPDF: Give CFF built-in encoding and charset arrays an underlying type
  Userland/Libraries/LibPDF/Fonts/CFF.cpp
Labels: 👀 pr-needs-review

#23196 Kernel/riscv64: Add missing include in Delay.cpp
  Kernel/Arch/riscv64/Delay.cpp
Labels: ✅ pr-community-approved

#23174 Fuzzers: Add PAM fuzzer
  Meta/Lagom/Fuzzers/FuzzPAMLoader.cpp
  Meta/Lagom/Fuzzers/FuzzPAMLoader.dict
  Meta/Lagom/Fuzzers/fuzzers.cmake
  Userland/Utilities/test-fuzz.cpp
Labels: ✅ pr-community-approved

#23200 LibAudio/Wav: Small code clean-up
  Userland/Libraries/LibAudio/WavWriter.cpp
  Userland/Libraries/LibAudio/WavWriter.h
Labels: 👀 pr-needs-review

#23199 Ports/SDL2: Support ShowMessageBox before VideoInit
  Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch
Labels: 👀 pr-needs-review

#23208 LibWeb: Implement `document.scrollingElement`
  Tests/LibWeb/Text/expected/document-scrollingElement-quirks-mode.txt
  Tests/LibWeb/Text/expected/document-scrollingElement.txt
  Tests/LibWeb/Text/input/document-scrollingElement-quirks-mode.html
  Tests/LibWeb/Text/input/document-scrollingElement.html
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/DOM/Document.idl
Labels: 👀 pr-needs-review

#23156 LibWeb: Only dump layout and text tree for the desired URL
  Userland/Utilities/headless-browser.cpp
Labels: 👀 pr-needs-review

#23206 LibWeb: Implement Document named properties with light caching
  Tests/LibWeb/Text/expected/DOM/Document-named-properties.txt
  Tests/LibWeb/Text/input/DOM/Document-named-properties.html
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/DOM/Document.idl
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#23209 LibWeb: Stub out all the functions from the execCommand spec
  Tests/LibWeb/Text/expected/Editing/execCommand-is-a-noop.txt
  Tests/LibWeb/Text/input/Editing/execCommand-is-a-noop.html
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/DOM/Document.idl
Labels: 👀 pr-needs-review

#23221 Meta: Don't search for both Python and Python3 in CMake
  Userland/Libraries/LibGfx/CMakeLists.txt
Labels: ✅ pr-community-approved

#23232 LibGfx/ICC: Optimizations for PDF image rendering
  Userland/Libraries/LibGfx/ICC/TagTypes.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#23226 LibPDF: Ignore unknown CFF operators
  Userland/Libraries/LibPDF/Fonts/Type1FontProgram.cpp
Labels: 👀 pr-needs-review

#23236 LibWeb: Fully implement the HTMLInputElement `value` setter and getter
  Tests/LibWeb/Text/expected/input-value.txt
  Tests/LibWeb/Text/input/input-value.html
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
Labels: 👀 pr-needs-review

#23235 2048: Ensure that correct font is requested
  Userland/Games/2048/BoardView.cpp
Labels: 👀 pr-needs-review

#23230 LibPDF: Implement stream CIDToGIDMaps for Type0 CIDFontType2 fonts
  Userland/Libraries/LibPDF/Fonts/Type0Font.cpp
Labels: 👀 pr-needs-review

#23244 LibWeb: Set `cursor: default` for button and select elements
  Userland/Libraries/LibWeb/CSS/Default.css
Labels: 👀 pr-needs-review

#23213 LibGfx/TIFF: Reduce execution time by 50% to 70%
  Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Labels: ✅ pr-community-approved

#23182 tail: Support skip from start mode
  Userland/Utilities/tail.cpp
Labels: 👀 pr-needs-review

#22830 Utilities: Add xxd utility
  Userland/Utilities/CMakeLists.txt
  Userland/Utilities/xxd.cpp
Labels: ✅ pr-community-approved

#23227 Kernel/HID: Modify index for shifted scan codes of non-printing chars
  Kernel/Devices/HID/PS2/KeyboardDevice.cpp
Labels: 👀 pr-needs-review

#22573 FlappyBug: Allow shortcuts for quitting and help
  Userland/Games/FlappyBug/Game.cpp
Labels: 👀 pr-needs-review, ⚠️ pr-has-conflicts

#23205 Kernel/riscv64: Don't use the memory before .text as the initial stack
  Kernel/Arch/riscv64/MMU.cpp
  Kernel/Arch/riscv64/boot.S
  Kernel/Arch/riscv64/linker.ld
Labels: 👀 pr-needs-review

#23222 LibGfx/CCITT: Add support for Group3 2D
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/tiff/ccitt3_2d.tiff
  Tests/LibGfx/test-inputs/tiff/ccitt3_2d_fill.tiff
  Userland/Libraries/LibGfx/ImageFormats/CCITTDecoder.cpp
Labels: ✅ pr-community-approved

#23258 Meta: Increase default VM RAM size to 2GiB
  Meta/run.py
Labels: 👀 pr-needs-review

#23170 Ladybird/AppKit: Fix select dropdown position high dpi bug
  Ladybird/AppKit/UI/LadybirdWebView.mm
Labels: 👀 pr-needs-review

#23265 LibPDF/CFF: Fix off-by-one when reading internal encoding
  Userland/Libraries/LibPDF/Fonts/CFF.cpp
Labels: 👀 pr-needs-review

#23266 LibWeb: Extract common integral IDL generators to a helper
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Labels: 👀 pr-needs-review

#23263 Tests/LibWeb: Make the WPT runner grab only the one commit it needs
  Tests/LibWeb/WPT/run.sh
Labels: 👀 pr-needs-review

#23267 LibJS: Fix copy paste errors in Temporal's Calendar Methods Record
  Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
Labels: 👀 pr-needs-review

#23264 LibPDF: Give CFF Glyph 0 the name .notdef
  Userland/Libraries/LibPDF/Fonts/CFF.cpp
Labels: 👀 pr-needs-review

#23270 LibJS: Further increase the free stack limit to 256 KiB
  Userland/Libraries/LibJS/Runtime/VM.h
Labels: 👀 pr-needs-review

#23273 LibWeb: Fix division by zero in `solve_replaced_size_constraint()`
  Tests/LibWeb/Layout/expected/zero-size-replaced-box-with-aspect-ratio.txt
  Tests/LibWeb/Layout/input/zero-size-replaced-box-with-aspect-ratio.html
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Labels: 👀 pr-needs-review

#23278 LibWeb: Allow bypassing transient activation checks for tests
  Tests/LibWeb/Text/input/clipboard.html
  Userland/Libraries/LibWeb/HTML/Window.cpp
  Userland/Libraries/LibWeb/HTML/Window.h
  Userland/Libraries/LibWeb/Internals/Internals.cpp
  Userland/Libraries/LibWeb/Internals/Internals.h
  Userland/Libraries/LibWeb/Internals/Internals.idl
Labels: 👀 pr-needs-review

#23277 LibWeb: Fix infinite recursion when grid has "max-width: max-content"
  Tests/LibWeb/Layout/expected/grid/container-max-width-max-content.txt
  Tests/LibWeb/Layout/input/grid/container-max-width-max-content.html
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Labels: 👀 pr-needs-review

#23285 LibWeb: Treat global as EventTarget in notify_about_rejected_promises
  Userland/Libraries/LibWeb/HTML/Scripting/Environments.cpp
Labels: 👀 pr-needs-review

#23279 LibWeb: Implement `AbortSignal.abort()`
  Tests/LibWeb/Text/expected/abortsignal-abort.txt
  Tests/LibWeb/Text/input/abortsignal-abort.html
  Userland/Libraries/LibWeb/DOM/AbortSignal.cpp
  Userland/Libraries/LibWeb/DOM/AbortSignal.h
  Userland/Libraries/LibWeb/DOM/AbortSignal.idl
Labels: 👀 pr-needs-review

#23287 LibWeb: Add various window transformation methods
  Userland/Libraries/LibWeb/HTML/Window.cpp
  Userland/Libraries/LibWeb/HTML/Window.h
  Userland/Libraries/LibWeb/HTML/Window.idl
Labels: 👀 pr-needs-review

#23292 Everywhere: Prefer {:#x} over 0x{:x} in format strings
  Kernel/Arch/aarch64/Interrupts.cpp
  Kernel/Bus/USB/UHCI/UHCIController.cpp
  Kernel/Bus/USB/UHCI/UHCIRootHub.cpp
  Kernel/Bus/USB/USBHub.cpp
  Kernel/Bus/USB/USBManagement.cpp
  Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodeData.cpp
  Userland/Libraries/LibDebug/Dwarf/AddressRanges.cpp
  Userland/Libraries/LibDeviceTree/Validation.cpp
  Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/Boxes.cpp
  Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
  Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
  Userland/Libraries/LibWasm/AbstractMachine/Validator.cpp
  Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
  Userland/Libraries/LibWeb/WebGL/WebGLRenderingContextBase.cpp
  Userland/Utilities/icc.cpp
  Userland/Utilities/lsusb.cpp
  Userland/Utilities/strace.cpp
  Userland/Utilities/xxd.cpp
Labels: 👀 pr-needs-review

#23294 LibGfx: Tweak semantics of some SkipTables enum values
  Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
  Userland/Libraries/LibGfx/Font/OpenType/Font.h
Labels: 👀 pr-needs-review

#23119 LibWeb: Properly round CSSPixels values in device_to_css_rect
  Userland/Libraries/LibWeb/Page/Page.cpp
  Userland/Libraries/LibWeb/PixelUnits.h
Labels: 👀 pr-needs-review

#23298 Ports: Add app category hotkey for Milkytracker
  Ports/milkytracker/package.sh
Labels: 👀 pr-needs-review

#23295 LibC: Save callee-saved floating-point registers in setjmp for riscv64
  Userland/Libraries/LibC/arch/riscv64/setjmp.S
  Userland/Libraries/LibC/setjmp.h
Labels: 👀 pr-needs-review

#23282 Kernel/Graphics: Probe PCI graphics adapters on all architectures
  Kernel/Devices/GPU/Management.cpp
Labels: 👀 pr-needs-review

#23126 LibTest: Return 0 if all test cases pass and 1 otherwise from TEST_MAIN
  Userland/Libraries/LibTest/TestMain.cpp
  Userland/Utilities/run-tests.cpp
Labels: 👀 pr-needs-review

#23299 LibPDF/CFF: Make compound characters work in Type1 fonts using type 2 CFF data
  Userland/Libraries/LibPDF/Fonts/Type1FontProgram.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#23303 LibWeb: Fix hit-testing by excluding CSS transform from clip rect check
  Tests/LibWeb/Text/expected/hit_testing/overflow-hidden-wrapped-into-css-translate.txt
  Tests/LibWeb/Text/input/hit_testing/overflow-hidden-wrapped-into-css-translate.html
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Labels: 👀 pr-needs-review

#23246 Kernel/USB: Handle non-page aligned EHCI controller BARs correctly
  Kernel/Bus/USB/EHCI/EHCIController.cpp
  Kernel/Bus/USB/EHCI/EHCIController.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci, ✅ pr-community-approved

#23309 Ports: Fix broken syntax in Milkytracker package script
  Ports/milkytracker/package.sh
Labels: 👀 pr-needs-review

#23305 LibGfx/CCITT: Reimplement PassMode in a less naive way
  Userland/Libraries/LibGfx/ImageFormats/CCITTDecoder.cpp
Labels: ✅ pr-community-approved

#23042 Kernel: don't panic when LocalSocket is already bound
  Kernel/Net/LocalSocket.cpp
  Tests/Kernel/TestTCPSocket.cpp
Labels: 👀 pr-needs-review

#23131 LibGUI/Application: Resize recent files list to max open file size
  Userland/Libraries/LibGUI/Application.cpp
Labels: 👀 pr-needs-review

#23052 useradd: Don't error out on `-m` if directory already exists
  Userland/Utilities/useradd.cpp
Labels: ✅ pr-community-approved

#23172 LibWeb: Invert return value from EventHandler key event handling methods
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
Labels: 👀 pr-needs-review

#23315 LibJS/Bytecode: Don't clobber dst when assigning from object expression
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
  Userland/Libraries/LibJS/Tests/builtins/Array/array-basic.js
  Userland/Libraries/LibJS/Tests/object-basic.js
Labels: 👀 pr-needs-review

#23310 LibPDF: Minor, mostly-noop cleanups around hex conversion
  Userland/Libraries/LibPDF/Parser.cpp
Labels: 👀 pr-needs-review

#23317 LibWeb: Implement almost all of the remaining Animation prototype methods
  Userland/Libraries/LibWeb/Animations/Animation.cpp
  Userland/Libraries/LibWeb/Animations/Animation.h
  Userland/Libraries/LibWeb/Animations/Animation.idl
Labels: 👀 pr-needs-review

#23322 Meta: Set the RAM size to 1G for aarch64 in run.py
  Meta/run.py
Labels: 👀 pr-needs-review

#23320 LibWeb: Allow HTMLElement with contenteditable=true to be focusable
  Tests/LibWeb/Text/expected/focus-contenteditable.txt
  Tests/LibWeb/Text/input/focus-contenteditable.html
  Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLElement.h
Labels: 👀 pr-needs-review

#23319 LibWeb: Add special handling for WindowProxy in [Replaceable] setters
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
  Tests/LibWeb/Text/expected/window-event-property-setter.txt
  Tests/LibWeb/Text/input/window-event-property-setter.html
Labels: 👀 pr-needs-review

#23329 LibWeb: Clamp calculated border width values to zero
  Tests/LibWeb/Layout/expected/calc-negative-border-width.txt
  Tests/LibWeb/Layout/input/calc-negative-border-width.html
  Userland/Libraries/LibWeb/Layout/Node.cpp
Labels: 👀 pr-needs-review

#23331 Ports: Update OpenRCT2 to version 0.4.8
  Ports/AvailablePorts.md
  Ports/openrct2/package.sh
  Ports/openrct2/patches/0001-Add-SerenityOS-platform-detection.patch
  Ports/openrct2/patches/0002-Add-missing-includes.patch
  Ports/openrct2/patches/0003-Read-the-executable-path-from-proc-self-exe.patch
  Ports/openrct2/patches/0005-Add-compile-options-to-CMakeLists.txt.patch
  Ports/openrct2/patches/0005-Don-t-try-linking-to-stdc-fs.patch
  Ports/openrct2/patches/0006-Disable-locale-detection-for-writing-the-default-con.patch
  Ports/openrct2/patches/0007-Disable-g2.dat-target.patch
  Ports/openrct2/patches/ReadMe.md
Labels: 👀 pr-needs-review

#23297 LibELF: Add riscv64 PLT trampoline
  Userland/Libraries/LibELF/Arch/riscv64/plt_trampoline.S
  Userland/Libraries/LibELF/DynamicLoader.cpp
Labels: 👀 pr-needs-review

#23312 Kernel/Net: Send RST packet when socket receives in closed state
  Kernel/Net/NetworkTask.cpp
Labels: 👀 pr-needs-review

#22784 mktemp: Ensure `--tmpdir` and template paths are concatenated correctly
  Userland/Utilities/mktemp.cpp
Labels: 👀 pr-needs-review

#23111 Meta: Prevent "serenity.sh gdb" to close other tmux sessions
  Meta/serenity.sh
Labels: 👀 pr-needs-review

#23301 LibPDF: Plug in the CCITT decoder
  Userland/Libraries/LibPDF/Filter.cpp
Labels: 👀 pr-needs-review

#22574 Browser: Allow system shortcuts to function
  Userland/Applications/Browser/BrowserWindow.cpp
Labels: 👀 pr-needs-review

#23261 LibWeb: Add HTMLPreElement width property
  Tests/LibWeb/Text/expected/HTML/pre-width.txt
  Tests/LibWeb/Text/input/HTML/pre-width.html
  Userland/Libraries/LibWeb/HTML/HTMLPreElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLPreElement.h
  Userland/Libraries/LibWeb/HTML/HTMLPreElement.idl
Labels: 👀 pr-needs-review

#23314 Kernel/riscv64: Use TimeManagement as an entropy source for now
  Kernel/Security/Random.cpp
Labels: 👀 pr-needs-review

#23318 Documentation: Recommend using clangd for code formatting in VSCode
  Documentation/VSCodeConfiguration.md
Labels: 👀 pr-needs-review

#23333 Meta: Allow collecting code coverage on Lagom
  Meta/CMake/lagom_compile_options.cmake
  Meta/CMake/lagom_options.cmake
Labels: 👀 pr-needs-review

#23340 LibWeb: Remove spammy dbgln about unsupported SVG mask content units
  Userland/Libraries/LibWeb/Painting/SVGGraphicsPaintable.cpp
Labels: 👀 pr-needs-review

#23339 LibWeb: Handle scenario when Window property setter is called on global
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
  Tests/LibWeb/Text/expected/global-performance-property.txt
  Tests/LibWeb/Text/input/global-performance-property.html
Labels: 👀 pr-needs-review

#23336 LibWeb: Increase the transient activation duration from 5ms to 5s
  Tests/LibWeb/Text/input/clipboard.html
  Userland/Libraries/LibWeb/HTML/Window.cpp
  Userland/Libraries/LibWeb/HTML/Window.h
  Userland/Libraries/LibWeb/Internals/Internals.cpp
  Userland/Libraries/LibWeb/Internals/Internals.h
  Userland/Libraries/LibWeb/Internals/Internals.idl
Labels: 👀 pr-needs-review

#23313 Kernel/Storage: Don't allocate IRQs in NVMeCntlr when nvme_poll passed
  Kernel/Devices/Storage/NVMe/NVMeController.cpp
  Kernel/Devices/Storage/NVMe/NVMeController.h
  Kernel/Devices/Storage/NVMe/NVMeQueue.cpp
  Kernel/Devices/Storage/NVMe/NVMeQueue.h
Labels: 👀 pr-needs-review

#23337 LibELF: Ignore mapping symbols when symbolicating RISC-V ELFs
  Userland/Libraries/LibELF/Image.cpp
Labels: 👀 pr-needs-review

#23348 LibWeb: Skip StackingContext with erroneously large rect in GPU painter
  Userland/Libraries/LibWeb/Painting/CommandExecutorGPU.cpp
Labels: 👀 pr-needs-review
