Repository SerenityOS/serenity, pull requests merged in 2024-04, with the labels that each got.

#23787 LibGfx/JBIG2: Remove a now-unneeded void cast
  Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
Labels: 👀 pr-needs-review

#23786 LibWeb: Catch up with the spec on document destroy, abort and unload
  Tests/LibWeb/Text/expected/HTML/WindowProxy-Get-after-detaching-from-browsing-context.txt
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/HTML/Navigable.cpp
  Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
  Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
Labels: 👀 pr-needs-review

#23781 LibPDF: Add a fastpath for 1bpp grayscale to load_image()
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: ✅ pr-community-approved

#23804 LibJS: Mark GCPtr's operator bool as explicit
  Userland/Libraries/LibJS/Heap/GCPtr.h
Labels: 👀 pr-needs-review

#23803 Meta/jbig2_to_pdf.py: Allow jbig2 files with random-access organization
  Meta/jbig2_to_pdf.py
Labels: ci-flakiness, 👀 pr-needs-review

#23812 LibJS+AK: Register GC memory as root regions for LeakSanitizer
  AK/Platform.h
  Userland/Libraries/LibJS/Heap/BlockAllocator.cpp
Labels: 👀 pr-needs-review

#23813 LibWeb: Don't use JS::SafeFunction for WebIDL promise reaction steps
  Userland/Libraries/LibWeb/WebIDL/Promise.h
Labels: 👀 pr-needs-review

#23406 LibWeb: Don't load fallback icon for SVG documents
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
  Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.h
Labels: 👀 pr-needs-review

#23785 LibC: Minor improvements in `ttyname_r_for_directory()`
  Userland/Libraries/LibC/unistd.cpp
Labels: 👀 pr-needs-review

#23816 LibWebView+Browser: Collect memory and cpu usage for helpers on Serenity
  Meta/gn/secondary/Userland/Libraries/LibWebView/BUILD.gn
  Userland/Applications/Browser/main.cpp
  Userland/Libraries/LibWebView/CMakeLists.txt
  Userland/Libraries/LibWebView/Platform/ProcessInfo.h
  Userland/Libraries/LibWebView/Platform/ProcessStatistics.h
  Userland/Libraries/LibWebView/Platform/ProcessStatisticsNoop.cpp
  Userland/Libraries/LibWebView/Platform/ProcessStatisticsSerenity.cpp
  Userland/Libraries/LibWebView/ProcessManager.cpp
  Userland/Libraries/LibWebView/ProcessManager.h
Labels: 👀 pr-needs-review

#23821 LibWeb: Fix "destroy the child navigable" to call `Document::destroy()`
  Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
Labels: 👀 pr-needs-review

#23826 LibWeb: Avoid UAF when encoding a fetch request body via URLSearchParams
  Tests/LibWeb/Text/expected/fetch-request-url-search-params.txt
  Tests/LibWeb/Text/input/fetch-request-url-search-params.html
  Userland/Libraries/LibWeb/Fetch/BodyInit.cpp
Labels: 👀 pr-needs-review

#23823 LibWeb: Remove WebContent include from SVGDecodedImageData
  Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.h
Labels: ✅ pr-community-approved

#23818 LibWebView: Collect memory and cpu usage for helpers on Linux
  Meta/gn/secondary/Userland/Libraries/LibWebView/BUILD.gn
  Userland/Libraries/LibWebView/CMakeLists.txt
  Userland/Libraries/LibWebView/Platform/ProcessStatisticsLinux.cpp
Labels: 👀 pr-needs-review

#23833 LibWebView: Avoid CPU% precision loss by doing the float cast later
  Userland/Libraries/LibWebView/Platform/ProcessStatisticsLinux.cpp
Labels: 👀 pr-needs-review

#23827 LibPDF: Invert image masks used as alpha too
  Userland/Libraries/LibPDF/Renderer.cpp
Labels: ci-flakiness, 👀 pr-needs-review

#23843 RequestServer: Avoid race condition between timeout and socket creation
  Userland/Services/RequestServer/ConnectionCache.cpp
Labels: 👀 pr-needs-review

#23846 Ladybird/Qt: Add a "new tab" button to the Qt chrome
  Ladybird/Icons/new_tab.tvg
  Ladybird/Qt/BrowserWindow.cpp
  Ladybird/Qt/BrowserWindow.h
  Ladybird/Qt/Tab.cpp
  Ladybird/Qt/ladybird.qrc
Labels: 👀 pr-needs-review

#23825 LibCore: Prevent SIGPIPE on Sockets by default
  Userland/Libraries/LibCore/LocalServer.cpp
  Userland/Libraries/LibCore/Socket.h
  Userland/Libraries/LibWeb/HTML/MessagePort.cpp
Labels: 👀 pr-needs-review

#23842 LibGfx/JBIG2: Support custom adaptive template pixels in refinement
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/jbig2/bitmap-symbol-textrefine-customat.jbig2
  Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
Labels: 👀 pr-needs-review

#23858 LibJSGCVerifier: Support building & running with the Lagom build
  Meta/Lagom/Tools/LibJSGCVerifier/CMakeLists.txt
  Meta/Lagom/Tools/LibJSGCVerifier/README.md
  Meta/Lagom/Tools/LibJSGCVerifier/src/main.py
Labels: 👀 pr-needs-review

#23859 LibURL: Avoid expensive IDNA::to_ascii() for all-ASCII domain strings
  Userland/Libraries/LibURL/Parser.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#23865 AK: Simplify and optimize ASCIICaseInsensitiveFlyStringTraits::equals
  AK/FlyString.h
Labels: 👀 pr-needs-review

#23672 Base: Add and Change Emoji
  Base/res/emoji/U+1F577.png
  Base/res/emoji/U+1F578.png
  Base/res/emoji/U+1F6F3.png
  Meta/emoji-file-list.txt
Labels: 👀 pr-needs-review

#23868 LibUnicode: Optimize the canonical composition algorithm implementation
  Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodeData.cpp
  Userland/Libraries/LibUnicode/Normalize.cpp
  Userland/Libraries/LibUnicode/Normalize.h
Labels: 👀 pr-needs-review

#23867 LibWeb: Fix crash for calculated transition duration/delays
  Tests/LibWeb/Text/expected/WebAnimations/transitions/parse-transition-calc-duration-delay.txt
  Tests/LibWeb/Text/input/WebAnimations/transitions/parse-transition-calc-duration-delay.html
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
  Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
  Userland/Libraries/LibWeb/CSS/StyleValues/TransitionStyleValue.h
Labels: 👀 pr-needs-review

#23870 LibWeb: Fix out of order spec step numbers in "create child navigable"
  Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
Labels: 👀 pr-needs-review

#23501 LibGfx/TIFF: Prevent recursion when following IFD pointers
  Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Labels: 👀 pr-needs-review

#23872 Ports/stockfish: Update to version 16.1
  Ports/AvailablePorts.md
  Ports/stockfish/package.sh
Labels: 👀 pr-needs-review

#23885 LibCrypto: Remove simple-template-id from constructors
  Userland/Libraries/LibCrypto/Cipher/Cipher.h
  Userland/Libraries/LibCrypto/Cipher/Mode/GCM.h
Labels: 👀 pr-needs-review

#23864 LibGfx/JBIG2: Add support for pattern and halftone segments
  Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
Labels: 👀 pr-needs-review

#23889 LibWeb: Wait for initial navigation to complete before modifying iframe
  Tests/LibWeb/Text/expected/navigation/populate-iframe-using-document-write.txt
  Tests/LibWeb/Text/input/navigation/populate-iframe-using-document-write.html
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.cpp
  Userland/Libraries/LibWeb/HTML/NavigableContainer.h
Labels: 👀 pr-needs-review

#23887 LibWeb: Split `SVGFormattingContext` up into functions
  Tests/LibWeb/Layout/expected/css-namespace-tag-name-selector.txt
  Tests/LibWeb/Layout/expected/svg/svg-g-inside-g.txt
  Tests/LibWeb/Layout/expected/svg/svg-symbol-with-viewbox.txt
  Tests/LibWeb/Layout/expected/svg/use-honor-outer-viewBox.txt
  Tests/LibWeb/Layout/input/svg/svg-g-inside-g.html
  Userland/Libraries/LibWeb/Layout/SVGFormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/SVGFormattingContext.h
Labels: 👀 pr-needs-review

#23891 LibWeb: Allow executing scripts for iframes with src=about:blank
  Tests/LibWeb/Text/expected/navigation/run-script-from-about-blank-iframe.txt
  Tests/LibWeb/Text/input/navigation/run-script-from-about-blank-iframe.html
  Userland/Libraries/LibWeb/DOM/Document.h
  Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
Labels: 👀 pr-needs-review

#23893 Documentation: Add more specific instructions on how to use the GN build
  Documentation/BuildInstructionsLadybird.md
  Meta/gn/README.md
Labels: 👀 pr-needs-review

#23875 HexEditor: Make offsets column configurable to be hex, decimal, or hidden entirely
  Userland/Applications/HexEditor/HexEditor.cpp
  Userland/Applications/HexEditor/HexEditor.h
  Userland/Applications/HexEditor/HexEditorWidget.cpp
  Userland/Applications/HexEditor/HexEditorWidget.h
Labels: 👀 pr-needs-review

#23898 LibJS: Implement Promise.try()
  Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
  Userland/Libraries/LibJS/Runtime/PromiseConstructor.cpp
  Userland/Libraries/LibJS/Runtime/PromiseConstructor.h
  Userland/Libraries/LibJS/Tests/builtins/Promise/Promise.try.js
Labels: ✅ pr-community-approved

#23888 LibGfx/JPEG2000: Add some scaffolding for reading codestream markers
  Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp
Labels: 👀 pr-needs-review

#23901 LibGfx/JPEG2000: Decode SIZ, COD, QCD, QCC, COM marker segments
  Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp
Labels: 👀 pr-needs-review

#23904 LibWebView: Respect dark mode/light mode TaskManager windows
  Userland/Libraries/LibWebView/ProcessManager.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#23905 LibWeb: Implement Element.outerHTML
  Tests/LibWeb/Text/expected/HTML/outerHTML.txt
  Tests/LibWeb/Text/input/HTML/outerHTML.html
  Userland/Libraries/LibWeb/DOM/Element.cpp
  Userland/Libraries/LibWeb/DOM/Element.h
  Userland/Libraries/LibWeb/DOM/Element.idl
  Userland/Libraries/LibWeb/DOM/Node.cpp
  Userland/Libraries/LibWeb/DOM/Node.h
  Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
  Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.h
Labels: 👀 pr-needs-review

#23906 LibGfx/JPEG2000: Use streams instead of manual offsets + minor cleanups
  Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp
Labels: 👀 pr-needs-review

#23917 LibWeb: Make SessionHistoryTraversalQueue GC-allocated
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/HTML/SessionHistoryTraversalQueue.cpp
  Userland/Libraries/LibWeb/HTML/SessionHistoryTraversalQueue.h
  Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
  Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
Labels: 👀 pr-needs-review

#23924 Base: Return the correct value for `fib(0)` in Wasm example
  Base/res/html/misc/wasm.html
Labels: 👀 pr-needs-review

#23914 Tests/LibWeb: Add a script to create a new test, starting with Text
  Tests/LibWeb/add_libweb_test.py
Labels: 👀 pr-needs-review

#23910 LibWeb: Add a workaround for excessive memory usage in Page::load_html
  Userland/Libraries/LibWeb/Page/Page.cpp
Labels: 👀 pr-needs-review

#23933 LibWeb: Add popstate event support
  Tests/LibWeb/Text/data/iframe-popstate-event.html
  Tests/LibWeb/Text/expected/navigation/history-popstate-event.txt
  Tests/LibWeb/Text/input/navigation/history-popstate-event.html
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/HTML/History.cpp
  Userland/Libraries/LibWeb/HTML/History.h
  Userland/Libraries/LibWeb/HTML/PopStateEvent.cpp
  Userland/Libraries/LibWeb/HTML/PopStateEvent.h
  Userland/Libraries/LibWeb/HTML/PopStateEvent.idl
  Userland/Libraries/LibWeb/idl_files.cmake
Labels: 👀 pr-needs-review

#23934 LibWeb: Use static position for abspos box axes with auto insets
  Tests/LibWeb/Layout/expected/abspos-with-static-position-in-one-axis.txt
  Tests/LibWeb/Layout/input/abspos-with-static-position-in-one-axis.html
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
  Userland/Libraries/LibWeb/Layout/Node.cpp
  Userland/Libraries/LibWeb/Layout/Node.h
Labels: 👀 pr-needs-review

#23916 Ladybird/AppKit: Implement a simple TaskManager window
  Ladybird/AppKit/Application/ApplicationDelegate.mm
  Ladybird/AppKit/UI/TaskManager.h
  Ladybird/AppKit/UI/TaskManager.mm
  Ladybird/AppKit/UI/TaskManagerController.h
  Ladybird/AppKit/UI/TaskManagerController.mm
  Ladybird/CMakeLists.txt
  Meta/gn/secondary/Ladybird/BUILD.gn
Labels: 👀 pr-needs-review

#23948 LibWeb: Don't limit available space during early height for inline-flex
  Tests/LibWeb/Layout/expected/flex/inline-flex-early-resolution-of-percentage-height.txt
  Tests/LibWeb/Layout/input/flex/inline-flex-early-resolution-of-percentage-height.html
  Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Labels: 👀 pr-needs-review

#23940 LibWeb: Fix always hanging Navigable::reload()
  Tests/LibWeb/Text/data/iframe-reload.html
  Tests/LibWeb/Text/expected/navigation/location-reload-fetch.txt
  Tests/LibWeb/Text/expected/navigation/location-reload-srcdoc.txt
  Tests/LibWeb/Text/input/navigation/location-reload-fetch.html
  Tests/LibWeb/Text/input/navigation/location-reload-srcdoc.html
  Userland/Libraries/LibWeb/HTML/DocumentState.cpp
  Userland/Libraries/LibWeb/HTML/DocumentState.h
  Userland/Libraries/LibWeb/HTML/SessionHistoryEntry.cpp
  Userland/Libraries/LibWeb/HTML/SessionHistoryEntry.h
  Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
Labels: 👀 pr-needs-review

#23955 Meta/gn: Port #23933
  Meta/gn/secondary/Userland/Libraries/LibWeb/HTML/BUILD.gn
  Meta/gn/secondary/Userland/Libraries/LibWeb/idl_files.gni
Labels: 👀 pr-needs-review

#23925 LibWeb: Remove `RecordingPainter::paint_frame()`
  Tests/LibWeb/Ref/alt-frame.html
  Tests/LibWeb/Ref/reference/alt-frame.html
  Tests/LibWeb/Ref/reference/images/alt-frame.png
  Userland/Libraries/LibWeb/Painting/Command.h
  Userland/Libraries/LibWeb/Painting/CommandExecutorCPU.cpp
  Userland/Libraries/LibWeb/Painting/CommandExecutorCPU.h
  Userland/Libraries/LibWeb/Painting/CommandExecutorGPU.cpp
  Userland/Libraries/LibWeb/Painting/CommandExecutorGPU.h
  Userland/Libraries/LibWeb/Painting/CommandList.cpp
  Userland/Libraries/LibWeb/Painting/CommandList.h
  Userland/Libraries/LibWeb/Painting/ImagePaintable.cpp
  Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
  Userland/Libraries/LibWeb/Painting/RecordingPainter.h
Labels: 👀 pr-needs-review

#23957 LibPDF: Make CFF.cpp use Stream instead of Reader
  Userland/Libraries/LibPDF/Fonts/CFF.cpp
  Userland/Libraries/LibPDF/Fonts/CFF.h
Labels: ✅ pr-community-approved

#23953 LibWeb/Fetch: Don't crash when a fetch request times out
  Tests/LibWeb/Text/expected/fetch-timed-out-request.txt
  Tests/LibWeb/Text/input/fetch-timed-out-request.html
  Userland/Libraries/LibWeb/Fetch/FetchMethod.cpp
Labels: 👀 pr-needs-review

#23950 LibWeb: Let queue_a_microtask() take a JS::HeapFunction
  Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp
  Userland/Libraries/LibWeb/DOM/Element.cpp
  Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
  Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.h
  Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
  Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
  Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
  Userland/Libraries/LibWeb/WebIDL/Promise.cpp
Labels: 👀 pr-needs-review

#23954 LibWeb: Support "importmap" scripts
  Tests/LibWeb/Text/expected/HTML/HTMLScriptElement-supports-importmap.txt
  Tests/LibWeb/Text/expected/HTML/import-maps.txt
  Tests/LibWeb/Text/input/HTML/HTMLScriptElement-supports-importmap.html
  Tests/LibWeb/Text/input/HTML/import-maps.html
  Tests/LibWeb/Text/input/HTML/import-maps.js
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/HTML/HTMLScriptElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLScriptElement.h
  Userland/Libraries/LibWeb/HTML/Scripting/ImportMap.cpp
  Userland/Libraries/LibWeb/HTML/Scripting/ImportMap.h
  Userland/Libraries/LibWeb/HTML/Scripting/ImportMapParseResult.cpp
  Userland/Libraries/LibWeb/HTML/Scripting/ImportMapParseResult.h
  Userland/Libraries/LibWeb/HTML/Window.h
Labels: 👀 pr-needs-review

#23972 LibGfx/WebP: Two tiny cleanups
  Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossless.cpp
Labels: 👀 pr-needs-review

#23967 LibWeb: Invalidate style when CSSStyleRule selectorText changes
  Tests/LibWeb/Text/expected/css/CSSStyleRule-set-selectorText.txt
  Tests/LibWeb/Text/input/css/CSSStyleRule-set-selectorText.html
  Userland/Libraries/LibWeb/CSS/CSSStyleRule.cpp
  Userland/Libraries/LibWeb/CSS/CSSStyleSheet.h
Labels: 👀 pr-needs-review

#23938 LibGfx/JPEG2000: Implement tag trees
  Tests/LibGfx/TestImageDecoder.cpp
  Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp
  Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.h
Labels: ci-flakiness, 👀 pr-needs-review

#23947 Utilities/w: Work around Clang 18 bug with templated lambda + Variant
  Userland/Utilities/w.cpp
Labels: 👀 pr-needs-review

#23976 LibWeb: Unset stylesheet properties when removing from a StyleSheetList
  Tests/LibWeb/Text/expected/HTMLLinkElement-disabled.txt
  Tests/LibWeb/Text/input/HTMLLinkElement-disabled.html
  Userland/Libraries/LibWeb/CSS/StyleSheetList.cpp
  Userland/Libraries/LibWeb/CSS/StyleSheetList.h
  Userland/Libraries/LibWeb/DOM/StyleElementUtils.cpp
  Userland/Libraries/LibWeb/DOM/StyleElementUtils.h
  Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Labels: 👀 pr-needs-review

#23977 LibWeb: Run <object> fallback steps if data type is not supported
  Tests/LibWeb/Text/expected/object-with-unsupported-type-in-data-attribute.txt
  Tests/LibWeb/Text/input/object-with-unsupported-type-in-data-attribute.html
  Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
  Userland/Libraries/LibWeb/DOM/DocumentLoading.h
  Userland/Libraries/LibWeb/HTML/HTMLObjectElement.cpp
Labels: 👀 pr-needs-review

#23983 LibWeb: Abort ongoing navigation before firing next navigation event
  Tests/LibWeb/Text/expected/navigation/trigger-fragment-navigation-from-js.txt
  Tests/LibWeb/Text/input/navigation/trigger-fragment-navigation-from-js.html
  Userland/Libraries/LibWeb/HTML/Navigation.cpp
Labels: 👀 pr-needs-review

#23985 LibWeb: Default to an empty string when a string attr substitution fails
  Tests/LibWeb/Layout/expected/css-attr-typed-fallback.txt
  Tests/LibWeb/Layout/input/css-attr-typed-fallback.html
  Tests/LibWeb/Ref/css-attr-typed-fallback.html
  Tests/LibWeb/Ref/css-attr-typed.html
  Tests/LibWeb/Ref/reference/css-attr-typed-ref.html
  Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Labels: 👀 pr-needs-review

#23988 LibCore: Stop obsessing about tiny OOMs in Core::Timer
  Ladybird/AppKit/UI/TaskManager.mm
  Tests/LibCore/TestLibCoreDeferredInvoke.cpp
  Tests/LibCore/TestLibCoreFileWatcher.cpp
  Userland/Applications/Assistant/main.cpp
  Userland/Applications/Browser/TaskManagerWidget.cpp
  Userland/Applications/ClockSettings/ClockSettingsWidget.cpp
  Userland/Applications/DisplaySettings/MonitorSettingsWidget.cpp
  Userland/Applications/MouseSettings/HighlightPreviewWidget.cpp
  Userland/Applications/Piano/main.cpp
  Userland/Applications/PixelPaint/Filters/Filter.cpp
  Userland/Applications/PixelPaint/ImageEditor.cpp
  Userland/Applications/PixelPaint/Tools/SprayTool.cpp
  Userland/Applications/PixelPaint/Tools/TextTool.cpp
  Userland/Applications/SoundPlayer/PlaybackManager.cpp
  Userland/Applications/Terminal/main.cpp
  Userland/Demos/CatDog/main.cpp
  Userland/Demos/WidgetGallery/DemoWizardDialog.cpp
  Userland/DevTools/HackStudio/Editor.cpp
  Userland/DevTools/Profiler/main.cpp
  Userland/Games/Hearts/Game.cpp
  Userland/Games/MasterWord/WordGame.cpp
  Userland/Games/Minesweeper/Field.cpp
  Userland/Games/Solitaire/main.cpp
  Userland/Games/Spider/main.cpp
  Userland/Libraries/LibAudio/PlaybackStreamSerenity.cpp
  Userland/Libraries/LibCore/Debounce.h
  Userland/Libraries/LibCore/Timer.cpp
  Userland/Libraries/LibCore/Timer.h
  Userland/Libraries/LibGUI/Application.cpp
  Userland/Libraries/LibGUI/TextEditor.cpp
  Userland/Libraries/LibIPC/Connection.cpp
  Userland/Libraries/LibTLS/Socket.cpp
  Userland/Libraries/LibVideo/PlaybackManager.cpp
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/HTML/AnimationFrameCallbackDriver.h
  Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
  Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
  Userland/Libraries/LibWeb/HTML/SessionHistoryTraversalQueue.cpp
  Userland/Libraries/LibWeb/HTML/Timer.cpp
  Userland/Libraries/LibWeb/Platform/AudioCodecPluginAgnostic.cpp
  Userland/Libraries/LibWebView/ViewImplementation.cpp
  Userland/Services/AudioServer/Mixer.cpp
  Userland/Services/ConfigServer/ConnectionFromClient.cpp
  Userland/Services/DHCPClient/DHCPv4Client.cpp
  Userland/Services/RequestServer/ConnectionCache.h
  Userland/Services/WindowServer/Compositor.cpp
  Userland/Services/WindowServer/ConnectionFromClient.cpp
  Userland/Services/WindowServer/Menu.cpp
  Userland/Services/WindowServer/WindowFrame.cpp
  Userland/Shell/Shell.cpp
  Userland/Utilities/headless-browser.cpp
Labels: 👀 pr-needs-review

#23981 LibTLS+LibHTTP: Tolerate improperly closed TLS sockets
  Tests/LibTLS/TestTLSHandshake.cpp
  Userland/Libraries/LibHTTP/Job.cpp
  Userland/Libraries/LibTLS/Socket.cpp
Labels: 👀 pr-needs-review

#23995 LibWeb: Fix two problems where media queries didn't invalidate properly
  Tests/LibWeb/Text/expected/css/text-transform-invalidation-on-media-query-change.txt
  Tests/LibWeb/Text/input/css/text-transform-invalidation-on-media-query-change.html
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: 👀 pr-needs-review

#23997 Kernel/riscv64: Increment sepc before re-enabling interrupts
  Kernel/Arch/riscv64/Interrupts.cpp
Labels: 👀 pr-needs-review

#24004 Base: Add manpage for Screenshot
  Base/usr/share/man/man1/Applications/Screenshot.md
Labels: 👀 pr-needs-review

#24015 CI: Enable KVM on Github Actions runners
  .github/workflows/cmake.yml
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#24023 LibWeb: Generate a simple error page when XML decode/parse fails
  Tests/LibWeb/Text/data/bad.xml
  Tests/LibWeb/Text/expected/XML/error-page.txt
  Tests/LibWeb/Text/input/XML/error-page.html
  Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
Labels: 👀 pr-needs-review

#24000 LibWeb: Add name validation and document check to setAttribute.
  Tests/LibWeb/Text/expected/DOM/Element-setAttribute-capitalization.txt
  Tests/LibWeb/Text/expected/DOM/Element-setAttribute-name-validation.txt
  Tests/LibWeb/Text/input/DOM/Element-setAttribute-capitalization.html
  Tests/LibWeb/Text/input/DOM/Element-setAttribute-name-validation.html
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: 👀 pr-needs-review, student project

#23989 LibWeb: Stop leaking socket fds when sending them over IPC
  Userland/DevTools/HackStudio/LanguageClient.cpp
  Userland/Libraries/LibGUI/Window.cpp
  Userland/Libraries/LibGfx/ShareableBitmap.cpp
  Userland/Libraries/LibIPC/Decoder.cpp
  Userland/Libraries/LibIPC/Encoder.cpp
  Userland/Libraries/LibIPC/Encoder.h
  Userland/Libraries/LibIPC/File.h
  Userland/Libraries/LibWeb/HTML/MessagePort.cpp
  Userland/Libraries/LibWeb/HTML/SelectedFile.cpp
  Userland/Libraries/LibWeb/Page/Page.h
  Userland/Libraries/LibWeb/Worker/WebWorkerClient.cpp
  Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
  Userland/Libraries/LibWebView/ViewImplementation.cpp
  Userland/Libraries/LibWebView/WebContentClient.cpp
  Userland/Services/FileSystemAccessServer/ConnectionFromClient.cpp
  Userland/Services/RequestServer/ConnectionFromClient.cpp
  Userland/Services/WebWorker/ConnectionFromClient.cpp
Labels: 👀 pr-needs-review

#24024 LibWeb: Do not destroy document until whole subtree completed unloading
  Tests/LibWeb/Text/data/iframe-unload-event.html
  Tests/LibWeb/Text/expected/navigation/iframe-unloading-order.txt
  Tests/LibWeb/Text/input/navigation/iframe-unloading-order.html
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/HTML/Navigable.cpp
  Userland/Libraries/LibWeb/HTML/Navigable.h
Labels: 👀 pr-needs-review

#24037 LibWeb: Remove unused blend mode param in FillEllipse painting command
  Userland/Libraries/LibWeb/Painting/Command.h
  Userland/Libraries/LibWeb/Painting/CommandExecutorCPU.cpp
  Userland/Libraries/LibWeb/Painting/CommandExecutorCPU.h
  Userland/Libraries/LibWeb/Painting/CommandExecutorGPU.cpp
  Userland/Libraries/LibWeb/Painting/CommandExecutorGPU.h
  Userland/Libraries/LibWeb/Painting/CommandList.cpp
  Userland/Libraries/LibWeb/Painting/CommandList.h
  Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
  Userland/Libraries/LibWeb/Painting/RecordingPainter.h
Labels: 👀 pr-needs-review

#24038 LibWeb: Fix nodesToRemove collecting traversal in Range::delete_contents
  Tests/LibWeb/Text/expected/DOM/Range-deleteContents.txt
  Tests/LibWeb/Text/input/DOM/Range-deleteContents.html
  Userland/Libraries/LibWeb/DOM/Range.cpp
Labels: 👀 pr-needs-review

#24040 LibCrypto+LibGfx: Fix GCC 14 compile errors
  Userland/Libraries/LibCrypto/Cipher/Mode/CBC.h
  Userland/Libraries/LibGfx/Size.h
Labels: 👀 pr-needs-review

#23982 AK: Add methods to BufferedStream to resize the user supplied buffer
  AK/BufferedStream.h
  Tests/AK/TestMemoryStream.cpp
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#24052 LibWeb: Update document url after same-document back/forward navigation
  Tests/LibWeb/Text/data/iframe-popstate-event.html
  Tests/LibWeb/Text/expected/navigation/history-popstate-event.txt
  Userland/Libraries/LibWeb/DOM/Document.cpp
Labels: 👀 pr-needs-review

#24054 LibWeb: Remove changing_navigable_continuation capture in callback
  Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
Labels: 👀 pr-needs-review

#24048 LibWeb: Add an initial implementation of the SVG `.getBBox()` method
  Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
Labels: 👀 pr-needs-review

#24060 LibWeb: Allow cloneNode() to clone elements with weird attributes
  Tests/LibWeb/Text/expected/DOM/cloneNode-with-goofy-attribute.txt
  Tests/LibWeb/Text/input/DOM/cloneNode-with-goofy-attribute.html
  Userland/Libraries/LibWeb/DOM/Element.cpp
  Userland/Libraries/LibWeb/DOM/Element.h
  Userland/Libraries/LibWeb/DOM/Node.cpp
Labels: 👀 pr-needs-review

#24057 LibWebView: Do not update cookie access time when fetched with WebDriver
  Userland/Libraries/LibWebView/CookieJar.cpp
Labels: 👀 pr-needs-review

#24059 LibELF: Get rid of DynamicLoader::m_cached_dynamic_object
  Userland/Libraries/LibELF/DynamicLoader.cpp
  Userland/Libraries/LibELF/DynamicLoader.h
Labels: 👀 pr-needs-review

#24053 Kernel/riscv64: Don't flush the entire TLB in Processor::flush_tlb_local
  Kernel/Arch/riscv64/Processor.cpp
Labels: 👀 pr-needs-review

#24055 Kernel/riscv64: Implement Processor::read_cpu_counter
  Kernel/Arch/riscv64/CSR.h
  Kernel/Arch/riscv64/Processor.h
Labels: 👀 pr-needs-review

#24061 LibWeb: Allow moving StyleSheets between documents without falling apart
  Tests/LibWeb/Text/expected/css/move-loaded-link-stylesheet-between-documents.txt
  Tests/LibWeb/Text/input/css/move-loaded-link-stylesheet-between-documents.html
  Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLLinkElement.h
Labels: 👀 pr-needs-review

#24069 LibWeb: Make NavigationParams be GC-allocated
  Userland/Libraries/LibWeb/CMakeLists.txt
  Userland/Libraries/LibWeb/DOM/Document.cpp
  Userland/Libraries/LibWeb/DOM/DocumentLoading.h
  Userland/Libraries/LibWeb/HTML/Navigable.cpp
  Userland/Libraries/LibWeb/HTML/Navigable.h
  Userland/Libraries/LibWeb/HTML/NavigationParams.cpp
  Userland/Libraries/LibWeb/HTML/NavigationParams.h
  Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
Labels: 👀 pr-needs-review

#24073 LibWeb: Fire "scroll" events on DOM elements
  Tests/LibWeb/Text/expected/element-scroll-event.txt
  Tests/LibWeb/Text/input/element-scroll-event.html
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Labels: 👀 pr-needs-review

#24075 LibWeb: Don't crash if the document element is not visible
  Tests/LibWeb/Layout/expected/hidden-root-element.txt
  Tests/LibWeb/Layout/input/hidden-root-element.html
  Userland/Libraries/LibWeb/DOM/Document.cpp
Labels: 👀 pr-needs-review

#24079 LibWeb: Add `background-clip: text` support for InlinePaintable
  Tests/LibWeb/Ref/inline-paintable-background-clip-text.html
  Tests/LibWeb/Ref/reference/inline-paintable-background-clip-text-ref.html
  Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
  Userland/Libraries/LibWeb/Painting/BackgroundPainting.h
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
  Userland/Libraries/LibWeb/Painting/PaintableBox.h
Labels: 👀 pr-needs-review

#24080 LibWeb: Fix division by zero in `solve_replaced_size_constraint()`
  Tests/LibWeb/Layout/expected/zero-height-replaced-box-with-aspect-ratio.txt
  Tests/LibWeb/Layout/input/zero-height-replaced-box-with-aspect-ratio.html
  Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Labels: 👀 pr-needs-review

#24063 Ladybird: Calculate the 'physical pixels' for screens
  Ladybird/Qt/WebContentView.cpp
Labels: 👀 pr-needs-review

#24042 LibTextCodec: Add Windows-1250 text decoder
  Userland/Libraries/LibTextCodec/Decoder.cpp
  Userland/Libraries/LibTextCodec/Decoder.h
Labels: 👀 pr-needs-review

#24002 PixelPaint: Avoid infinite loop when updating zoom level ComboBox text
  Userland/Applications/PixelPaint/MainWidget.cpp
Labels: 👀 pr-needs-review

#24077 Documentation: Update Ladybird README with more descriptive information
  Ladybird/README.md
Labels: 👀 pr-needs-review

#24082 DynamicLoader: Resolve missing weak absolute symbols to null
  Userland/Libraries/LibELF/DynamicLoader.cpp
Labels: 👀 pr-needs-review

#24076 Meta: Trim the CI ccache down to files used in the current build
  .github/workflows/cmake.yml
  Meta/Azure/Caches.yml
  Meta/Azure/Lagom.yml
  Meta/Azure/Serenity.yml
  Toolchain/BuildClang.sh
Labels: 👀 pr-needs-review

#24087 CI: Test using Clang for ASAN+UBSAN on linux
  Meta/Azure/Lagom.yml
  Meta/Azure/nightly-pipeline.yml
  azure-pipelines.yml
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#24086 LibELF: Perform weak relocations in much more straight-forward manner
  Userland/Libraries/LibELF/DynamicLoader.cpp
  Userland/Libraries/LibELF/DynamicLoader.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#24084 LibJS: Save min and max block addresses in CellAllocator
  Userland/Libraries/LibJS/Heap/CellAllocator.cpp
  Userland/Libraries/LibJS/Heap/CellAllocator.h
  Userland/Libraries/LibJS/Heap/Heap.cpp
Labels: 👀 pr-needs-review

#24097 CI: Configure ccache before modifying its contents (if any)
  .github/workflows/cmake.yml
  Meta/Azure/Caches.yml
Labels: 👀 pr-needs-review

#23990 LibWeb: Fix get_client_rects() on elements that are not paintable
  Tests/LibWeb/Text/expected/get-bounding-client-rect-display-none.txt
  Tests/LibWeb/Text/input/get-bounding-client-rect-display-none.html
  Userland/Libraries/LibWeb/DOM/Element.cpp
Labels: 👀 pr-needs-review

#24100 LibWeb: Allocate dataset lazily for HTML/SVG/MathML elements
  Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
  Userland/Libraries/LibWeb/HTML/HTMLElement.h
  Userland/Libraries/LibWeb/MathML/MathMLElement.cpp
  Userland/Libraries/LibWeb/MathML/MathMLElement.h
  Userland/Libraries/LibWeb/SVG/SVGElement.cpp
  Userland/Libraries/LibWeb/SVG/SVGElement.h
Labels: 👀 pr-needs-review

#24101 LibWeb: Skip HTMLLinkElement resource fetching for inactive documents
  Tests/LibWeb/Text/expected/css/move-loaded-link-stylesheet-between-documents.txt
  Tests/LibWeb/Text/expected/favicon-in-inactive-document.txt
  Tests/LibWeb/Text/input/favicon-in-inactive-document.html
  Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Labels: 👀 pr-needs-review

#24109 Ladybird: Use RequestServer for networking by default
  Ladybird/AppKit/main.mm
  Ladybird/Types.h
Labels: 👀 pr-needs-review

#24111 LibWeb: Run page activation behavior when skipping context menu events
  Userland/Libraries/LibWeb/Page/EventHandler.cpp
Labels: 👀 pr-needs-review

#24115 LibWeb: Only react to link element attribute changes when BC connected
  Userland/Libraries/LibWeb/DOM/Node.cpp
  Userland/Libraries/LibWeb/DOM/Node.h
  Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Labels: 👀 pr-needs-review

#24118 LibWeb: Look for first ID _or_ name in HTMLCollection::named_item
  Tests/LibWeb/Text/expected/DOM/HTMLCollection-order.txt
  Tests/LibWeb/Text/input/DOM/HTMLCollection-order.html
  Userland/Libraries/LibWeb/DOM/HTMLCollection.cpp
  Userland/Libraries/LibWeb/DOM/HTMLCollection.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#24120 LibTLS: Ignore empty reads from underlying socket while connecting
  Userland/Libraries/LibTLS/Socket.cpp
  Userland/Libraries/LibTLS/TLSv12.h
Labels: 👀 pr-needs-review

#23936 LibWeb: Set decoder error when decoding fails
  Userland/Libraries/LibWeb/HTML/AudioTrack.cpp
  Userland/Libraries/LibWeb/Platform/AudioCodecPlugin.h
  Userland/Libraries/LibWeb/Platform/AudioCodecPluginAgnostic.cpp
Labels: 👀 pr-needs-review

#24122 LibWeb: Remove CSS transform from InlinePaintable's clip rectangle
  Tests/LibWeb/Ref/inline-paintable-inside-translated-container.html
  Tests/LibWeb/Ref/reference/inline-paintable-inside-translated-container-ref.html
  Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
  Userland/Libraries/LibWeb/Painting/Paintable.cpp
  Userland/Libraries/LibWeb/Painting/Paintable.h
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
  Userland/Libraries/LibWeb/Painting/PaintableBox.h
Labels: 👀 pr-needs-review

#23835 LibWeb: Exclude [Global] interfaces from legacy platform object method
  Tests/LibWeb/Text/expected/HTML/Window-iterate-properties.txt
  Tests/LibWeb/Text/input/HTML/Window-iterate-properties.html
  Userland/Libraries/LibWeb/Bindings/PlatformObject.cpp
Labels: 👀 pr-needs-review

#24006 IDLGenerators: Set namespace object prototype to Object.prototype
  Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
  Tests/LibWeb/Text/expected/namespace-object-prototype.txt
  Tests/LibWeb/Text/input/namespace-object-prototype.html
Labels: 👀 pr-needs-review

#24104 Kernel/riscv64: Don't clobber the boot info argument in enable_paging
  Kernel/Arch/riscv64/MMU.cpp
Labels: 👀 pr-needs-review

#24127 AK: Make ceil_div() handle one argument being negative correctly
  AK/StdLibExtras.h
  Tests/AK/TestStdLibExtras.cpp
Labels: 👀 pr-needs-review

#24136 LibJS: Fix bug where argument++ happened before call
  Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
  Userland/Libraries/LibJS/Tests/postfix-increment-eval-order.js
Labels: 👀 pr-needs-review

#24135 Ladybird: Retreive the tab title from the underlying Tab
  Ladybird/Qt/BrowserWindow.cpp
  Ladybird/Qt/Tab.h
Labels: 👀 pr-needs-review

#24140 LibWeb: Skip unnecessary sample corner and blit corner commands
  Userland/Libraries/LibWeb/HTML/Navigable.cpp
  Userland/Libraries/LibWeb/Painting/CommandList.cpp
  Userland/Libraries/LibWeb/Painting/CommandList.h
Labels: 👀 pr-needs-review

#24137 LibGfx/JPEG2000: Remove an incorrect VERIFY in TagTree construction
  Tests/LibGfx/TestImageDecoder.cpp
  Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp
Labels: ci-flakiness, 👀 pr-needs-review

#24145 Toolchain/Stubs: Fix small typo in README.md
  Toolchain/Stubs/README.md
Labels: 👀 pr-needs-review

#24146 LibWeb: Use cached absolute rect and transform in refresh_clip_state()
  Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Labels: 👀 pr-needs-review

#24155 LibWeb: Paint non-positioned SC with z-index=0 in paint_descendants()
  Tests/LibWeb/Ref/non-positioned-stacking-context-with-z-index-0.html
  Tests/LibWeb/Ref/reference/non-positioned-stacking-context-with-z-index-0-ref.html
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Labels: 👀 pr-needs-review

#24154 Kernel/USB: Don't include UHCIController.h in USBPipe.h
  Kernel/Bus/USB/USBPipe.cpp
  Kernel/Bus/USB/USBPipe.h
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#24148 Ladybird: Add a context menu to the tab bar
  Ladybird/Qt/BrowserWindow.cpp
  Ladybird/Qt/BrowserWindow.h
  Ladybird/Qt/Tab.cpp
  Ladybird/Qt/Tab.h
  Ladybird/Qt/TabBar.cpp
  Ladybird/Qt/TabBar.h
Labels: 👀 pr-needs-review

#24157 LibWeb: Fix paint recording to stop visiting stacking context twice
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Labels: 👀 pr-needs-review

#24159 LibWeb: Verify in runtime that stacking context is not painted twice
  Userland/Libraries/LibWeb/Painting/PaintContext.cpp
  Userland/Libraries/LibWeb/Painting/PaintContext.h
  Userland/Libraries/LibWeb/Painting/StackingContext.cpp
  Userland/Libraries/LibWeb/Painting/StackingContext.h
Labels: 👀 pr-needs-review

#24147 Utilities: Initialize raw variables to default values in some utilities
  Userland/Utilities/arp.cpp
  Userland/Utilities/sleep.cpp
  Userland/Utilities/slugify.cpp
  Userland/Utilities/tar.cpp
  Userland/Utilities/test-imap.cpp
  Userland/Utilities/tsort.cpp
Labels: 👀 pr-needs-review

#24161 Meta: Add section about Ladybird to top-level README
  README.md
Labels: 👀 pr-needs-review

#24156 Utilities/mount: Resolve regression on mounting non-storage-backed FSes
  Userland/Utilities/mount.cpp
Labels: 👀 pr-needs-review

#24113 Kernel/aarch64: Explicitly allow float instrs in {load,store}_fpu_state
  Kernel/Arch/aarch64/FPUState.S
  Kernel/Arch/aarch64/FPUState.h
  Kernel/Arch/aarch64/Processor.cpp
  Kernel/CMakeLists.txt
Labels: 👀 pr-needs-review

#24167 Tests: Skip flaky unicode-range LibWeb Ref test
  Tests/LibWeb/TestConfig.ini
Labels: 👀 pr-needs-review
