Repository SerenityOS/serenity, pull requests merged in 2025-01, with the labels that each got.

#25608 Meta: Add User-Agent string on request for download_file
  Meta/download_file.py
Labels: 👀 pr-needs-review

#25598 Base+Meta: Add Canadian Provincial Flag Emojis
  Base/home/anon/Documents/emoji-serenity.txt
  Base/res/emoji/U+1F3F4_U+E0063_U+E0061_U+E0061_U+E0062_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E0063_U+E0061_U+E0062_U+E0063_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E0063_U+E0061_U+E006D_U+E0062_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E0063_U+E0061_U+E006E_U+E0062_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E0063_U+E0061_U+E006E_U+E006C_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E0063_U+E0061_U+E006E_U+E0073_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E0063_U+E0061_U+E006E_U+E0074_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E0063_U+E0061_U+E006E_U+E0075_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E0063_U+E0061_U+E006F_U+E006E_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E0063_U+E0061_U+E0070_U+E0065_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E0063_U+E0061_U+E0071_U+E0063_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E0063_U+E0061_U+E0073_U+E006B_U+E007F.png
  Base/res/emoji/U+1F3F4_U+E0063_U+E0061_U+E0079_U+E0074_U+E007F.png
  Meta/emoji-file-list.txt
Labels: 👀 pr-needs-review

#25613 Tests/LibC: Don't implicitly convert float to double in TestSnprintf
  Tests/LibC/TestSnprintf.cpp
Labels: 👀 pr-needs-review

#25623 Ports/SDL2: Sync scancode map with Kernel/API/KeyCode.h
  Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch
Labels: 👀 pr-needs-review

#25621 Meta: Disable "Zoom To Fit" when using the gtk display backend
  Meta/run.py
Labels: 👀 pr-needs-review

#25622 ThemeEditor: Add new system theme properties
  Userland/Applications/ThemeEditor/CMakeLists.txt
  Userland/Applications/ThemeEditor/MainWidget.cpp
  Userland/Applications/ThemeEditor/MainWidget.h
  Userland/Applications/ThemeEditor/WindowThemeProperty.gml
  Userland/Libraries/LibGUI/Variant.h
  Userland/Libraries/LibGfx/Palette.h
Labels: 👀 pr-needs-review

#25614 LibGfx: Fix title bar text clipping in Redmond Glass/Plastic
  Userland/Libraries/LibGfx/GlassWindowTheme.cpp
  Userland/Libraries/LibGfx/PlasticWindowTheme.cpp
Labels: 👀 pr-needs-review

#25618 Ports/isl: Update to version 0.27
  Ports/AvailablePorts.md
  Ports/isl/package.sh
Labels: 👀 pr-needs-review

#25611 Ports/bzip3: Update to version 1.5.1
  Ports/AvailablePorts.md
  Ports/bzip3/package.sh
Labels: 👀 pr-needs-review

#25619 Ports/nasm: Update to version 2.16.03
  Ports/AvailablePorts.md
  Ports/nasm/package.sh
Labels: 👀 pr-needs-review

#25617 Ports/md4c: Update to version 0.5.2
  Ports/AvailablePorts.md
  Ports/md4c/package.sh
Labels: 👀 pr-needs-review

#25624 Ports/lynx: Update to version 2.9.2
  Ports/AvailablePorts.md
  Ports/lynx/package.sh
Labels: 👀 pr-needs-review

#25632 Meta: Omit -cpu arguments on windows for qemu 9 compatibility
  Meta/run.py
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#25635 LibGfx: Only use draw_scaled_bitmap() fast path when not flipping image
  Userland/Libraries/LibGfx/AffineTransform.h
  Userland/Libraries/LibGfx/Painter.cpp
  Userland/Libraries/LibWeb/Painting/AffineDisplayListPlayerCPU.cpp
Labels: 👀 pr-needs-review

#25638 Ports/giflib: Update to 5.2.2
  Ports/AvailablePorts.md
  Ports/giflib/package.sh
Labels: 👀 pr-needs-review

#25625 Ports/ca-certificates: Update to version 2024-12-31
  Ports/AvailablePorts.md
  Ports/ca-certificates/package.sh
Labels: 👀 pr-needs-review

#25626 Ports/file: Update to 5.46
  Ports/AvailablePorts.md
  Ports/file/package.sh
Labels: 👀 pr-needs-review

#25607 Base+Fonts: Add Lucidity Mono Bold terminal font
  Base/res/fonts/LucidityMonoBold10.font
Labels: 👀 pr-needs-review

#25599 Base+Fonts: Add Lucidity Mono Regular terminal font
  Base/res/fonts/LucidityMonoRegular10.font
Labels: 👀 pr-needs-review

#25641 Ports/imagemagick: Update to 7.1.1-43
  Ports/AvailablePorts.md
  Ports/imagemagick/package.sh
Labels: 👀 pr-needs-review

#25639 Ports/lcms2: Update to 2.16
  Ports/AvailablePorts.md
  Ports/lcms2/package.sh
Labels: 👀 pr-needs-review

#25631 AK: Improve performance of u64 randoms
  AK/Random.cpp
Labels: ✅ pr-community-approved

#25643 LibCrypto: Smaller stack usage
  Userland/Libraries/LibCrypto/Hash/SHA1.cpp
  Userland/Libraries/LibCrypto/Hash/SHA2.cpp
Labels: 👀 pr-needs-review

#25646 Meta: Correct the Pi 3 devicetree blob path
  Meta/run.py
Labels: 👀 pr-needs-review

#25642 Kernel/GPU: Add a simple-framebuffer devicetree driver
  Kernel/CMakeLists.txt
  Kernel/Devices/GPU/Generic/SimpleFramebuffer.cpp
Labels: 👀 pr-needs-review

#25645 Ports/libexpat: Update to 2.6.4
  Ports/AvailablePorts.md
  Ports/libexpat/package.sh
Labels: 👀 pr-needs-review

#25647 Ports/stockfish: Update to 17
  Ports/AvailablePorts.md
  Ports/stockfish/package.sh
Labels: 👀 pr-needs-review

#25648 Ports/libarchive: Update to 3.7.7
  Ports/AvailablePorts.md
  Ports/libarchive/package.sh
Labels: 👀 pr-needs-review

#25650 Ports/libmikmod: Update to 3.3.12
  Ports/AvailablePorts.md
  Ports/libmikmod/package.sh
Labels: 👀 pr-needs-review

#25651 Kernel/RTL8168: Change invalid u32 mmio reads to u8
  Kernel/Net/Realtek/RTL8168NetworkAdapter.cpp
Labels: 👀 pr-needs-review

#25652 Ports/libslirp: Update to 4.8.0
  Ports/AvailablePorts.md
  Ports/libslirp/package.sh
Labels: 👀 pr-needs-review

#25654 Ports/libunistring: Update to 1.3
  Ports/AvailablePorts.md
  Ports/libunistring/package.sh
Labels: 👀 pr-needs-review

#25655 Cherry-pick "LibJS: Propagate direct eval presence if the current scope is screwed"
  Userland/Libraries/LibJS/Parser.cpp
  Userland/Libraries/LibJS/Tests/var-scoping.js
Labels: 👀 pr-needs-review

#25657 Ports/libxmp: Update to 4.6.1
  Ports/AvailablePorts.md
  Ports/libxmp/package.sh
Labels: 👀 pr-needs-review

#25656 LibGfx/ISOBMFF: Add JPEG2000PaletteBox
  Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/JPEG2000Boxes.cpp
  Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/JPEG2000Boxes.h
Labels: 👀 pr-needs-review

#25659 Taskbar: Fix applet/clock area background color
  Userland/Services/Taskbar/TaskbarFrame.cpp
Labels: 👀 pr-needs-review

#25661 Ports/openjpeg: Update to 2.5.3
  Ports/AvailablePorts.md
  Ports/openjpeg/package.sh
Labels: 👀 pr-needs-review

#25630 Ports/boost: Fix download link, fix paths in patches
  Ports/boost/package.sh
  Ports/boost/patches/0001-Add-platform-support-for-SerenityOS.patch
  Ports/boost/patches/0002-Fix-building-Boost.Interprocess.patch
Labels: 👀 pr-needs-review

#25663 LibPDF: Check DecodeParms array element type before casting
  Userland/Libraries/LibPDF/Parser.cpp
Labels: 👀 pr-needs-review

#25665 Ports: Add missing dependency on readline to bash
  Ports/bash/package.sh
Labels: 👀 pr-needs-review

#25666 Cherry-pick "Meta: Disable clang-tidy “implicit-bool-conversion” check"
  .clang-tidy
Labels: 👀 pr-needs-review
