Repository SerenityOS/serenity, pull requests merged in 2025-03, with the labels that each got.

#25735 Meta: Use the raw archive.org copy for the download_file fallback
  Meta/CMake/utils.cmake
Labels: 👀 pr-needs-review

#25736 Meta: Merge errors from `du --help` into stdout
  Meta/shell_include.sh
Labels: 👀 pr-needs-review

#25738 LibGfx/JPEG2000: Do not run bit depth conversion for 8 bpp channels
  Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp
Labels: 👀 pr-needs-review

#25737 Meta: Add a script for building x86-64 UEFI GRUB disk images
  CMakeLists.txt
  Documentation/AdvancedBuildInstructions.md
  Meta/build-image-grub-uefi.sh
Labels: 👀 pr-needs-review

#25743 LibPDF: Skip whitespace before values in compressed stream
  Userland/Libraries/LibPDF/DocumentParser.cpp
  Userland/Libraries/LibPDF/Parser.h
Labels: 👀 pr-needs-review

#25739 LibC: Disallow environment variable names that are empty or contain '='
  Tests/LibC/TestEnvironment.cpp
  Userland/Libraries/LibC/stdlib.cpp
Labels: 👀 pr-needs-review

#25744 LibPDF: Remove incorrect page tree heuristic
  Tests/LibPDF/colorspaces.pdf
  Userland/Libraries/LibPDF/Document.cpp
Labels: 👀 pr-needs-review

#25747 Services/ImageDecoder: Return an error if no frame was decoded
  Userland/Services/ImageDecoder/ConnectionFromClient.cpp
Labels: 👀 pr-needs-review

#25750 Cherry-pick "LibJS+LibWebView: Treat trivia tokens as comments"
  Userland/Libraries/LibJS/SyntaxHighlighter.cpp
  Userland/Libraries/LibJS/Token.h
  Userland/Libraries/LibWebView/SourceHighlighter.cpp
Labels: 👀 pr-needs-review

#25749 Kernel/xHCI: Enable memory space accesses before trying to access MMIO
  Kernel/Bus/USB/xHCI/PCIxHCIController.cpp
Labels: 👀 pr-needs-review

#25755 LibGfx/JPEGXL: VarDCT-related progress
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Labels: 👀 pr-needs-review

#25753 Services/ImageDecoder: Move bitmaps instead of copying them
  Userland/Services/ImageDecoder/ConnectionFromClient.cpp
Labels: 👀 pr-needs-review

#25746 LibC: Free variables with clearenv()
  Userland/Libraries/LibC/stdlib.cpp
Labels: ⏳ pr-waiting-for-author

#25758 Kernel: Remove some unnecessary VERIFYs from StorageManagement
  Kernel/Devices/Storage/StorageManagement.cpp
Labels: 👀 pr-needs-review

#25762 LibGfx+Base: Try harder to add .jpf to known image extensions
  Base/res/apps/ImageViewer.af
  Userland/Libraries/LibGfx/Bitmap.h
Labels: 👀 pr-needs-review

#25766 Base: Add ilbm, jbig2, jpeg2000, tiff to Pixel Paint file type list
  Base/res/apps/PixelPaint.af
Labels: 👀 pr-needs-review

#25765 Ports/ca-certificates: Create symlinks in /usr/local/ssl
  Ports/ca-certificates/package.sh
Labels: 👀 pr-needs-review

#25763 Utilities/ln: Add verbose option
  Userland/Utilities/ln.cpp
Labels: 👀 pr-needs-review

#25767 Tests/JPEG2000: Rename -tile test files to have correct dimensions
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/jpeg2000/jasper-tile4x2-res5.jp2
  Tests/LibGfx/test-inputs/jpeg2000/openjpeg-lossless-rgba-u8-prog0-tile4x2-cblk4x16-tp3-layers3-res2.jp2
  Tests/LibGfx/test-inputs/jpeg2000/openjpeg-lossless-rgba-u8-prog1-tile4x2-cblk4x16-tp3-layers3-res2.jp2
  Tests/LibGfx/test-inputs/jpeg2000/openjpeg-lossless-rgba-u8-prog2-tile4x2-cblk4x16-tp3-layers3-res2.jp2
  Tests/LibGfx/test-inputs/jpeg2000/openjpeg-lossless-rgba-u8-prog3-tile4x2-cblk4x16-tp3-layers3-res2.jp2
  Tests/LibGfx/test-inputs/jpeg2000/openjpeg-lossless-rgba-u8-prog4-tile4x2-cblk4x16-tp3-layers3-res2.jp2
Labels: 👀 pr-needs-review

#25769 TextEditor: Add gmi to TextEditor file type list
  Base/res/apps/TextEditor.af
Labels: 👀 pr-needs-review

#25770 Ports: Update Python to 3.13.2
  Ports/AvailablePorts.md
  Ports/python3/patches/0002-Tweak-configure.patch
  Ports/python3/version.sh
Labels: 👀 pr-needs-review

#25776 Kernel: BlockBasedFilesystem cleanup
  Kernel/FileSystem/BlockBasedFileSystem.cpp
  Kernel/FileSystem/BlockBasedFileSystem.h
  Kernel/FileSystem/Ext2FS/FileSystem.cpp
  Kernel/FileSystem/ISO9660FS/FileSystem.cpp
Labels: 👀 pr-needs-review

#25782 Libraries: Fix my remaining legacy mail attributions
  Userland/Libraries/LibCore/EventLoop.cpp
  Userland/Libraries/LibThreading/Mutex.h
  Userland/Libraries/LibThreading/MutexProtected.h
Labels: 👀 pr-needs-review

#25785 LibC: Add missing dependency on LibUBSanitizer
  Userland/Libraries/LibC/CMakeLists.txt
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#25784 LibGfx/JPEGXL: Reduce included headers from JPEGXLICC.cpp
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLICC.cpp
Labels: 👀 pr-needs-review

#25781 Documentation: Consolidate and extend clangd configuration docs
  Documentation/ClangdConfiguration.md
  Documentation/EmacsConfiguration.md
  Documentation/HelixConfiguration.md
  Documentation/NvimConfiguration.md
  Documentation/README.md
  Documentation/VSCodeConfiguration.md
Labels: 👀 pr-needs-review

#25644 Base: Update the Syrian flag
  Base/res/emoji/U+1F1F8_U+1F1FE.png
Labels: ⛔️ pr-is-blocked

#25787 mkfs.fat: Don't wipe the first 34 MiB if we don't need to
  Userland/Utilities/mkfs.fat.cpp
Labels: 👀 pr-needs-review

#25789 Ports: Update LLVM sha256sum
  Ports/llvm/package.sh
Labels: 👀 pr-needs-review

#25793 Tests: Add full ref test for JPEG2000 CMYK decoding
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/jpeg2000/ref-cmyk.tif
Labels: 👀 pr-needs-review

#25794 Kernel/aarch64: Add basic support for PSCI and HVC calls
  Kernel/Arch/aarch64/PSCI.cpp
  Kernel/Arch/aarch64/PSCI.h
  Kernel/Arch/aarch64/PowerState.cpp
  Kernel/CMakeLists.txt
Labels: ✅ pr-maintainer-approved-but-awaiting-ci

#25798 Kernel/riscv64: Don't use __builtin___clear_cache on RISC-V
  Kernel/Arch/Processor.h
  Kernel/Arch/ProcessorFunctions.include
  Kernel/Arch/aarch64/Processor.cpp
  Kernel/Arch/riscv64/Processor.cpp
  Kernel/Arch/x86_64/Processor.cpp
  Kernel/Memory/Region.cpp
Labels: 👀 pr-needs-review

#25799 Kernel/riscv64: Correctly calculate symbol addresses again
  Kernel/KSyms.cpp
Labels: 👀 pr-needs-review

#25801 Ports: Add fribidi
  Ports/AvailablePorts.md
  Ports/fribidi/package.sh
Labels: 👀 pr-needs-review

#25812 LibGfx/JPEGXL: Avoid allocations in the hot path
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Labels: 👀 pr-needs-review

#25814 AK: Allow ConstrainedStream to discard bytes until the limit
  AK/ConstrainedStream.cpp
  Tests/AK/CMakeLists.txt
  Tests/AK/TestConstrainedStream.cpp
Labels: 👀 pr-needs-review

#25822 Kernel/aarch64: Add support for the PL031
  Kernel/Arch/aarch64/Time/PL031.cpp
  Kernel/Arch/aarch64/Time/PL031.h
  Kernel/CMakeLists.txt
  Kernel/Time/TimeManagement.cpp
Labels: 👀 pr-needs-review

#25823 LibGfx/JPEG2000: Remove obsolete FIXME
  Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp
Labels: 👀 pr-needs-review

#25819 LibGfx/JPEGXL: Enough work on the decoder to reach the point where it sees there is no work to do in the GlobalModular section
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Labels: 👀 pr-needs-review

#25827 LibGfx/JPEGXL: General bugfixes for the decoder :^)
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Labels: 👀 pr-needs-review

#25830 LibGfx/JPEG2000: Read end-of-packet-header marker for empty packets
  Tests/LibGfx/TestImageDecoder.cpp
  Tests/LibGfx/test-inputs/jpeg2000/openjpeg-lossless-rgba-u8-prog0-EPH-empty-packets.jp2
  Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp
Labels: 👀 pr-needs-review

#25831 Kernel/aarch64: Correct the RPi Mini UART register map
  Kernel/Arch/aarch64/RPi/MiniUART.cpp
Labels: 👀 pr-needs-review

#25835 Kernel/PCI: Use correct access width during PCI-to-PCI bridge setup
  Kernel/Bus/PCI/Controller/HostController.cpp
Labels: 👀 pr-needs-review

#25839 LibGfx/JPEGXL: Compare both dimensions when checking the channel size
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Labels: 👀 pr-needs-review

#25840 LibGfx/JPEGXL: Enough progress to decode a nice flower :^)
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLChannel.h
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Labels: 👀 pr-needs-review

#25848 Kernel/Input: Correct the HID keyboard driver usage ID range check
  Kernel/Devices/Input/HID/KeyboardDriver.cpp
Labels: 👀 pr-needs-review

#25847 Tests/LibGfx: A JPEG XL palette test sooner than expected
  Tests/LibGfx/TestImageDecoder.cpp
Labels: 👀 pr-needs-review

#25849 Tests/LibPDF: Tweak gouraud test files even more
  Tests/LibPDF/shade-gouraud-free.pdf
  Tests/LibPDF/shade-gouraud-lattice.pdf
Labels: 👀 pr-needs-review

#25842 LibPDF: Read lattice-form gouraud-shaded triangle mesh shading entries
  Userland/Libraries/LibPDF/CommonNames.h
  Userland/Libraries/LibPDF/Shading.cpp
Labels: 👀 pr-needs-review

#25846 LibGfx/JPEGXL: Correctly compute groups' y index from the group index
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Labels: 👀 pr-needs-review

#25845 LibGfx/JPEGXL: Use more structs to pass arguments
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Labels: 👀 pr-needs-review

#25844 LibGfx/JPEGXL: Honor the use_mtf option when reading clustering maps
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLEntropyDecoder.cpp
Labels: 👀 pr-needs-review

#25851 Kernel/USB: Correct the HID driver probe success check
  Kernel/Bus/USB/Drivers/HID.cpp
Labels: 👀 pr-needs-review

#25852 Kernel: Remove reference to RegisterState from UnhandledInterruptHandler
  Kernel/Interrupts/UnhandledInterruptHandler.cpp
Labels: 👀 pr-needs-review

#25855 LibGfx/JPEGXL: Add a custom formatter for FrameHeader::FrameType
  Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Labels: 👀 pr-needs-review

#25858 Meta: Remove unnecessary nonlocal from serenity_gdb.py
  Meta/serenity_gdb.py
Labels: 👀 pr-needs-review

#25860 LibC: Enable randomized malloc locations on x86_64, aarch64 and riscv64
  Userland/Libraries/LibC/malloc.cpp
Labels: 👀 pr-needs-review
